QGroundControl: src/Android/AndroidInit.cc File Reference
AndroidInit.cc File Reference
#include "AndroidInterface.h"
#include "AndroidSerial.h"
#include <QtCore/QJniEnvironment>
#include <QtCore/QJniObject>
#include <QtCore/QLoggingCategory>
#include <atomic>
#include "QGCLoggingCategory.h"
Functions
QGC_LOGGING_CATEGORY (AndroidInitLog, "Android.AndroidInit")
static jboolean jniInit (JNIEnv *env, jobject thiz)
static jint jniSetNativeMethods ()
jint JNI_OnLoad (JavaVM *vm, void *)
void JNI_OnUnload (JavaVM *vm, void *)
Variables
static std::atomic< jobject > _context {nullptr}
static std::atomic< jobject > _class_loader {nullptr}
static std::atomic< JavaVM * > _java_vm {nullptr}
Function Documentation
JNI_OnLoad()
jint JNI_OnLoad (JavaVM * vm, void *)
Definition at line 144 of file AndroidInit.cc.
References _java_vm, jniSetNativeMethods(), AndroidInterface::setNativeMethods(), and AndroidSerial::setNativeMethods().
JNI_OnUnload()
void JNI_OnUnload (JavaVM * vm, void *)
Definition at line 170 of file AndroidInit.cc.
References _class_loader, _context, _java_vm, and AndroidSerial::cleanupJniCache().
jniInit()
static jboolean jniInit (JNIEnv * env, jobject thiz) static
Definition at line 46 of file AndroidInit.cc.
References _class_loader, and _context.
Referenced by jniSetNativeMethods().
jniSetNativeMethods()
static jint jniSetNativeMethods () static
Definition at line 111 of file AndroidInit.cc.
References jniInit(), and AndroidInterface::kJniQGCActivityClassName.
Referenced by JNI_OnLoad().
QGC_LOGGING_CATEGORY()
QGC_LOGGING_CATEGORY (AndroidInitLog , "Android.AndroidInit")
Variable Documentation
_class_loader
std::atomic<jobject> _class_loader {nullptr} static
Definition at line 16 of file AndroidInit.cc.
Referenced by JNI_OnUnload(), and jniInit().
_context
std::atomic<jobject> _context {nullptr} static
Definition at line 15 of file AndroidInit.cc.
Referenced by JNI_OnUnload(), and jniInit().
_java_vm
std::atomic<JavaVM*> _java_vm {nullptr} static
Definition at line 17 of file AndroidInit.cc.
Referenced by JNI_OnLoad(), and JNI_OnUnload().