QGroundControl: AirframeComponent Class Reference
AirframeComponent Class Reference
#include <AirframeComponent.h>
Public Member Functions
AirframeComponent (Vehicle *vehicles, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
virtual QStringList setupCompleteChangedTriggerList (void) const
virtual QString name (void) const
virtual QString description (void) const
virtual QString iconResource (void) const
virtual bool requiresSetup (void) const
virtual bool setupComplete (void) const
virtual QUrl setupSource (void) const
virtual QUrl summaryQmlSource (void) const
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file AirframeComponent.h.
Constructor & Destructor Documentation
AirframeComponent()
AirframeComponent::AirframeComponent (Vehicle * vehicles, AutoPilotPlugin * autopilot, QObject * parent = nullptr)
Definition at line 5 of file AirframeComponent.cc.
Member Function Documentation
description()
QString AirframeComponent::description (void) const virtual
Reimplemented from VehicleComponent.
Definition at line 17 of file AirframeComponent.cc.
iconResource()
QString AirframeComponent::iconResource (void) const virtual
Implements VehicleComponent.
Definition at line 23 of file AirframeComponent.cc.
name()
QString AirframeComponent::name (void) const virtual
Implements VehicleComponent.
Definition at line 12 of file AirframeComponent.cc.
Referenced by PX4AutoPilotPlugin::prerequisiteSetup().
requiresSetup()
bool AirframeComponent::requiresSetup (void) const virtual
Implements VehicleComponent.
Definition at line 28 of file AirframeComponent.cc.
setupComplete()
bool AirframeComponent::setupComplete (void) const virtual
Implements VehicleComponent.
Definition at line 33 of file AirframeComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), and Vehicle::parameterManager().
Referenced by PX4AutoPilotPlugin::prerequisiteSetup().
setupCompleteChangedTriggerList()
QStringList AirframeComponent::setupCompleteChangedTriggerList (void) const virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 38 of file AirframeComponent.cc.
setupSource()
QUrl AirframeComponent::setupSource (void) const virtual
Implements VehicleComponent.
Definition at line 43 of file AirframeComponent.cc.
summaryQmlSource()
QUrl AirframeComponent::summaryQmlSource (void) const virtual
Implements VehicleComponent.
Definition at line 48 of file AirframeComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/AirframeComponent.h
src/AutoPilotPlugins/PX4/AirframeComponent.cc