QGroundControl: PX4AutoPilotPlugin Class Reference
PX4AutoPilotPlugin Class Reference
#include <PX4AutoPilotPlugin.h>
Public Member Functions
PX4AutoPilotPlugin (Vehicle *vehicle, QObject *parent)
~PX4AutoPilotPlugin ()
const QVariantList & vehicleComponents (void) override
void parametersReadyPreChecks (void) override
QString prerequisiteSetup (VehicleComponent *component) const override
Returns the name of the vehicle component which must complete setup prior to this one. Empty string for none.
Protected Attributes
bool _incorrectParameterVersion
true: parameter version incorrect, setup not allowed
PX4AirframeLoader * _airframeFacts
AirframeComponent * _airframeComponent
PX4RadioComponent * _radioComponent
ESP8266Component * _esp8266Component
FlightModesComponent * _flightModesComponent
SensorsComponent * _sensorsComponent
SafetyComponent * _safetyComponent
PowerComponent * _powerComponent
MotorComponent * _motorComponent
ActuatorComponent * _actuatorComponent
PX4TuningComponent * _tuningComponent
PX4FlightBehavior * _flightBehavior
SyslinkComponent * _syslinkComponent
JoystickComponent * _joystickComponent
Protected Attributes inherited from AutoPilotPlugin
Vehicle * _vehicle = nullptr
FirmwarePlugin * _firmwarePlugin = nullptr
bool _setupComplete = false
Additional Inherited Members
Signals inherited from AutoPilotPlugin
void setupCompleteChanged ()
void vehicleComponentsChanged ()
Detailed Description
Definition at line 21 of file PX4AutoPilotPlugin.h.
Constructor & Destructor Documentation
PX4AutoPilotPlugin()
PX4AutoPilotPlugin::PX4AutoPilotPlugin (Vehicle * vehicle, QObject * parent)
Definition at line 15 of file PX4AutoPilotPlugin.cc.
References _airframeFacts, and PX4AirframeLoader::loadAirframeMetaData().
~PX4AutoPilotPlugin()
PX4AutoPilotPlugin::~PX4AutoPilotPlugin ()
Definition at line 43 of file PX4AutoPilotPlugin.cc.
References _airframeFacts.
Member Function Documentation
parametersReadyPreChecks()
void PX4AutoPilotPlugin::parametersReadyPreChecks (void) override virtual
Called when parameters are ready for the first time. Note that parameters may still be missing. Overrides must call base class.
Reimplemented from AutoPilotPlugin.
Definition at line 150 of file PX4AutoPilotPlugin.cc.
References AutoPilotPlugin::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), ParameterManager::parameterExists(), Vehicle::parameterManager(), and qgcApp.
prerequisiteSetup()
QString PX4AutoPilotPlugin::prerequisiteSetup (VehicleComponent * component) const override virtual
Returns the name of the vehicle component which must complete setup prior to this one. Empty string for none.
Implements AutoPilotPlugin.
Definition at line 162 of file PX4AutoPilotPlugin.cc.
References _airframeComponent, _radioComponent, AutoPilotPlugin::_vehicle, ParameterManager::getParameter(), AirframeComponent::name(), PX4RadioComponent::name(), Vehicle::parameterManager(), AirframeComponent::setupComplete(), and PX4RadioComponent::setupComplete().
vehicleComponents()
const QVariantList & PX4AutoPilotPlugin::vehicleComponents (void) override virtual
Implements AutoPilotPlugin.
Definition at line 48 of file PX4AutoPilotPlugin.cc.
References _actuatorComponent, _airframeComponent, _esp8266Component, _flightBehavior, _flightModesComponent, _incorrectParameterVersion, _joystickComponent, _motorComponent, _powerComponent, _radioComponent, _safetyComponent, _sensorsComponent, _syslinkComponent, _tuningComponent, AutoPilotPlugin::_vehicle, Vehicle::actuators(), Vehicle::compId(), Vehicle::hilMode(), Actuators::init(), Actuators::initializationError(), Actuators::isInitialized(), ParameterManager::parameterExists(), Vehicle::parameterManager(), ParameterManager::parametersReady(), and Actuators::showUi().
Member Data Documentation
_actuatorComponent
ActuatorComponent* PX4AutoPilotPlugin::_actuatorComponent protected
Definition at line 45 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_airframeComponent
AirframeComponent* PX4AutoPilotPlugin::_airframeComponent protected
Definition at line 37 of file PX4AutoPilotPlugin.h.
Referenced by prerequisiteSetup(), and vehicleComponents().
_airframeFacts
PX4AirframeLoader* PX4AutoPilotPlugin::_airframeFacts protected
Definition at line 36 of file PX4AutoPilotPlugin.h.
Referenced by PX4AutoPilotPlugin(), and ~PX4AutoPilotPlugin().
_esp8266Component
ESP8266Component* PX4AutoPilotPlugin::_esp8266Component protected
Definition at line 39 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_flightBehavior
PX4FlightBehavior* PX4AutoPilotPlugin::_flightBehavior protected
Definition at line 47 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_flightModesComponent
FlightModesComponent* PX4AutoPilotPlugin::_flightModesComponent protected
Definition at line 40 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_incorrectParameterVersion
bool PX4AutoPilotPlugin::_incorrectParameterVersion protected
true: parameter version incorrect, setup not allowed
Definition at line 35 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_joystickComponent
JoystickComponent* PX4AutoPilotPlugin::_joystickComponent protected
Definition at line 49 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_motorComponent
MotorComponent* PX4AutoPilotPlugin::_motorComponent protected
Definition at line 44 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_powerComponent
PowerComponent* PX4AutoPilotPlugin::_powerComponent protected
Definition at line 43 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_radioComponent
PX4RadioComponent* PX4AutoPilotPlugin::_radioComponent protected
Definition at line 38 of file PX4AutoPilotPlugin.h.
Referenced by prerequisiteSetup(), and vehicleComponents().
_safetyComponent
SafetyComponent* PX4AutoPilotPlugin::_safetyComponent protected
Definition at line 42 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_sensorsComponent
SensorsComponent* PX4AutoPilotPlugin::_sensorsComponent protected
Definition at line 41 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_syslinkComponent
SyslinkComponent* PX4AutoPilotPlugin::_syslinkComponent protected
Definition at line 48 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
_tuningComponent
PX4TuningComponent* PX4AutoPilotPlugin::_tuningComponent protected
Definition at line 46 of file PX4AutoPilotPlugin.h.
Referenced by vehicleComponents().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.h
src/AutoPilotPlugins/PX4/PX4AutoPilotPlugin.cc