QGroundControl: VehicleCameraControl Class Reference
VehicleCameraControl Class Reference
MAVLink Camera API controller - connected to a real mavlink v2 camera.
#include <VehicleCameraControl.h>
Public Member Functions
VehicleCameraControl (const mavlink_camera_information_t *info, Vehicle *vehicle, int compID, QObject *parent=nullptr)
~VehicleCameraControl () override
void setCameraModeVideo () override
void setCameraModePhoto () override
void toggleCameraMode () override
bool takePhoto () override
bool stopTakePhoto () override
bool startVideoRecording () override
bool stopVideoRecording () override
bool toggleVideoRecording () override
void resetSettings () override
void formatCard (int id=1) override
void stepZoom (int direction) override
void startZoom (int direction) override
void stopZoom () override
void stepFocus (int direction) override
void startFocus (int direction) override
void stopFocus () override
void stopStream () override
void resumeStream () override
void startTrackingRect (QRectF rec) override
void startTrackingPoint (QPointF point, double radius) override
void stopTracking () override
int version () const override
QString modelName () const override
QString vendor () const override
QString firmwareVersion () const override
qreal focalLength () const override
QSizeF sensorSize () const override
QSize resolution () const override
bool capturesVideo () const override
bool capturesPhotos () const override
bool hasModes () const override
bool hasZoom () const override
bool hasFocus () const override
bool hasTracking () const override
bool supportsTrackingPoint () const override
bool supportsTrackingRect () const override
bool hasVideoStream () const override
bool photosInVideoMode () const override
bool videoInPhotoMode () const override
CaptureVideoState captureVideoState () const override
CapturePhotosState capturePhotosState () const override
int compID () const override
bool isBasic () const override
StorageStatus storageStatus () const override
QStringList activeSettings () const override
quint32 storageFree () const override
QString storageFreeStr () const override
quint32 storageTotal () const override
int batteryRemaining () const override
QString batteryRemainingStr () const override
bool paramComplete () const override
qreal zoomLevel () const override
qreal focusLevel () const override
QmlObjectListModel * streams () override
QGCVideoStreamInfo * currentStreamInstance () override
QGCVideoStreamInfo * thermalStreamInstance () override
int currentStream () const override
void setCurrentStream (int stream) override
bool autoStream () const override
quint32 recordTime () const override
QString recordTimeStr () const override
QStringList streamLabels () const override
Stream names to show the user (for selection)
ThermalViewMode thermalMode () const override
void setThermalMode (ThermalViewMode mode) override
double thermalOpacity () const override
void setThermalOpacity (double val) override
void setZoomLevel (qreal level) override
void setFocusLevel (qreal level) override
void setCameraMode (CameraMode cameraMode) override
void setPhotoCaptureMode (PhotoCaptureMode mode) override
void setPhotoLapse (qreal interval) override
void setPhotoLapseCount (int count) override
void handleCameraSettings (const mavlink_camera_settings_t &settings) override
void handleCameraCaptureStatus (const mavlink_camera_capture_status_t &cameraCaptureStatus) override
void handleParamExtAck (const mavlink_param_ext_ack_t &paramExtAck) override
void handleParamExtValue (const mavlink_param_ext_value_t &paramExtValue) override
void handleStorageInformation (const mavlink_storage_information_t &storageInformation) override
void handleBatteryStatus (const mavlink_battery_status_t &bs) override
void handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t &trackingImageStatus) override
void handleVideoStreamInformation (const mavlink_video_stream_information_t &videoStreamInformation) override
void handleVideoStreamStatus (const mavlink_video_stream_status_t &videoStreamStatus) override
bool trackingEnabled () const override
void setTrackingEnabled (bool set) override
bool trackingImageIsActive () const override
bool trackingImageIsPoint () const override
QRectF trackingImageRect () const override
QPointF trackingImagePoint () const override
qreal trackingImageRadius () const override
Fact * exposureMode () override
Fact * ev () override
Fact * iso () override
Fact * shutterSpeed () override
Fact * aperture () override
Fact * wb () override
Fact * mode () override
void factChanged (Fact *pFact) override
Notify controller a parameter has changed.
bool incomingParameter (Fact *pFact, QVariant &newValue) override
Allow controller to modify or invalidate incoming parameter.
bool validateParameter (Fact *pFact, QVariant &newValue) override
Allow controller to modify or invalidate parameter change.
Public Member Functions inherited from MavlinkCameraControlInterface
MavlinkCameraControlInterface (Vehicle *vehicle, QObject *parent=nullptr)
virtual ~MavlinkCameraControlInterface ()
virtual PhotoCaptureMode photoCaptureMode () const
virtual qreal photoLapse () const
virtual int photoLapseCount () const
virtual CameraMode cameraMode () const
QString cameraModeToStr (CameraMode mode)
QString captureImageStatusToStr (uint8_t image_status)
QString captureVideoStatusToStr (uint8_t video_status)
QString storageStatusToStr (uint8_t status)
Static Public Attributes
static constexpr const char * kCondition = "condition"
static constexpr const char * kControl = "control"
static constexpr const char * kDefault = "default"
static constexpr const char * kDefnition = "definition"
static constexpr const char * kDescription = "description"
static constexpr const char * kExclusion = "exclude"
static constexpr const char * kExclusions = "exclusions"
static constexpr const char * kLocale = "locale"
static constexpr const char * kLocalization = "localization"
static constexpr const char * kMax = "max"
static constexpr const char * kMin = "min"
static constexpr const char * kModel = "model"
static constexpr const char * kName = "name"
static constexpr const char * kOption = "option"
static constexpr const char * kOptions = "options"
static constexpr const char * kOriginal = "original"
static constexpr const char * kParameter = "parameter"
static constexpr const char * kParameterrange = "parameterrange"
static constexpr const char * kParameterranges = "parameterranges"
static constexpr const char * kParameters = "parameters"
static constexpr const char * kReadOnly = "readonly"
static constexpr const char * kWriteOnly = "writeonly"
static constexpr const char * kRoption = "roption"
static constexpr const char * kStep = "step"
static constexpr const char * kDecimalPlaces = "decimalPlaces"
static constexpr const char * kStrings = "strings"
static constexpr const char * kTranslated = "translated"
static constexpr const char * kType = "type"
static constexpr const char * kUnit = "unit"
static constexpr const char * kUpdate = "update"
static constexpr const char * kUpdates = "updates"
static constexpr const char * kValue = "value"
static constexpr const char * kVendor = "vendor"
static constexpr const char * kVersion = "version"
static constexpr const char * kPhotoMode = "PhotoCaptureMode"
static constexpr const char * kPhotoLapse = "PhotoLapse"
static constexpr const char * kPhotoLapseCount = "PhotoLapseCount"
static constexpr const char * kThermalOpacity = "ThermalOpacity"
static constexpr const char * kThermalMode = "ThermalMode"
static constexpr const char * kCAM_EV = "CAM_EV"
static constexpr const char * kCAM_EXPMODE = "CAM_EXPMODE"
static constexpr const char * kCAM_ISO = "CAM_ISO"
static constexpr const char * kCAM_SHUTTERSPD = "CAM_SHUTTERSPD"
static constexpr const char * kCAM_APERTURE = "CAM_APERTURE"
static constexpr const char * kCAM_WBMODE = "CAM_WBMODE"
static constexpr const char * kCAM_MODE = "CAM_MODE"
Protected Slots
virtual void _initWhenReady ()
virtual void _requestCameraSettings ()
virtual void _requestAllParameters ()
virtual void _requestParamUpdates ()
virtual void _requestCaptureStatus ()
virtual void _requestStorageInfo ()
virtual void _downloadFinished ()
virtual void _mavCommandResult (int vehicleId, int component, int command, int result, int failureCode)
virtual void _dataReady (QByteArray data)
virtual void _streamInfoTimeout ()
virtual void _streamStatusTimeout ()
virtual void _cameraSettingsTimeout ()
virtual void _storageInfoTimeout ()
virtual void _recTimerHandler ()
virtual void _checkForVideoStreams ()
virtual void _onVideoManagerRecordingChanged (bool recording)
void _paramDone () override
Protected Slots inherited from MavlinkCameraControlInterface
virtual void _paramDone ()=0
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Protected Member Functions
virtual void _setVideoCaptureStatus (VideoCaptureStatus captureStatus)
virtual void _setPhotoCaptureStatus (PhotoCaptureStatus captureStatus)
virtual void _setCameraMode (CameraMode mode)
virtual void _requestStreamInfo (uint8_t streamID)
virtual void _requestStreamStatus (uint8_t streamID)
virtual void _requestTrackingStatus ()
virtual QGCVideoStreamInfo * _findStream (uint8_t streamID, bool report=true)
virtual QGCVideoStreamInfo * _findStream (const QString name)
Protected Member Functions inherited from MavlinkCameraControlInterface
VideoCaptureStatus _videoCaptureStatus () const
PhotoCaptureStatus _photoCaptureStatus () const
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
int _compID = 0
mavlink_camera_information_t _mavlinkCameraInfo
int _version = 0
bool _cached = false
bool _paramComplete = false
qreal _zoomLevel = 0.0
qreal _focusLevel = 0.0
uint32_t _storageFree = 0
uint32_t _storageTotal = 0
int _batteryRemaining = -1
QNetworkAccessManager * _netManager = nullptr
QString _modelName
QString _vendor
QString _cacheFile
StorageStatus _storageStatus = STORAGE_NOT_SUPPORTED
QStringList _activeSettings
QStringList _settings
QTimer _captureStatusTimer
QList< QGCCameraOptionExclusion * > _valueExclusions
QList< QGCCameraOptionRange * > _optionRanges
QMap< QString, QStringList > _originalOptNames
QMap< QString, QVariantList > _originalOptValues
QMap< QString, QGCCameraParamIO * > _paramIO
int _cameraSettingsRetries = 0
int _cameraCaptureStatusRetries = 0
int _storageInfoRetries = 0
int _captureInfoRetries = 0
bool _resetting = false
QTime _recTime
uint32_t _recordTime = 0
QMap< QString, QStringList > _requestUpdates
QStringList _updatesToRequest
int _videoStreamInfoRetries = 0
int _videoStreamStatusRetries = 0
int _requestCount = 0
int _currentStream = 0
int _expectedCount = 1
QTimer _streamInfoTimer
QTimer _streamStatusTimer
QTimer _cameraSettingsTimer
QTimer _storageInfoTimer
QmlObjectListModel _streams
QStringList _streamLabels
ThermalViewMode _thermalMode = THERMAL_BLEND
double _thermalOpacity = 85.0
bool _hasTrackingRectCapability = false
bool _hasTrackingPointCapability = false
bool _trackingEnabled = false
bool _trackingImageIsActive = false
bool _trackingImageIsPoint = false
mavlink_camera_tracking_image_status_t _trackingImageStatus {}
QRectF _trackingImageRect
QPointF _trackingImagePoint
qreal _trackingImageRadius = 0.0
Protected Attributes inherited from MavlinkCameraControlInterface
Vehicle * _vehicle = nullptr
CameraMode _cameraMode = CAM_MODE_UNDEFINED
VideoCaptureStatus _videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED
PhotoCaptureStatus _photoCaptureStatusValue = PHOTO_CAPTURE_IDLE
PhotoCaptureMode _photoCaptureMode = PHOTO_CAPTURE_SINGLE
qreal _photoLapse = 1.0
int _photoLapseCount = 0
QTimer _videoRecordTimeUpdateTimer
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Additional Inherited Members
Public Types inherited from MavlinkCameraControlInterface
enum CameraMode { CAM_MODE_UNDEFINED = -1 , CAM_MODE_PHOTO = 0 , CAM_MODE_VIDEO = 1 , CAM_MODE_SURVEY = 2 }
enum PhotoCaptureMode { PHOTO_CAPTURE_SINGLE = 0 , PHOTO_CAPTURE_TIMELAPSE }
enum CaptureVideoState { CaptureVideoStateDisabled = 0 , CaptureVideoStateIdle , CaptureVideoStateCapturing }
enum CapturePhotosState { CapturePhotosStateDisabled = 0 , CapturePhotosStateIdle , CapturePhotosStateCapturingSinglePhoto , CapturePhotosStateCapturingMultiplePhotos }
enum StorageStatus { STORAGE_EMPTY = STORAGE_STATUS_EMPTY , STORAGE_UNFORMATTED = STORAGE_STATUS_UNFORMATTED , STORAGE_READY = STORAGE_STATUS_READY , STORAGE_NOT_SUPPORTED = STORAGE_STATUS_NOT_SUPPORTED }
enum ThermalViewMode { THERMAL_OFF = 0 , THERMAL_BLEND , THERMAL_FULL , THERMAL_PIP }
Signals inherited from MavlinkCameraControlInterface
void infoChanged ()
void videoCaptureStatusChanged ()
void photoCaptureStatusChanged ()
void photoCaptureModeChanged ()
void photoLapseChanged ()
void photoLapseCountChanged ()
void cameraModeChanged ()
void activeSettingsChanged ()
void storageFreeChanged ()
void storageTotalChanged ()
void batteryRemainingChanged ()
void dataReady (const QByteArray &data)
void parametersReady ()
void zoomLevelChanged ()
void focusLevelChanged ()
void streamsChanged ()
void currentStreamChanged ()
void thermalStreamChanged ()
void autoStreamChanged ()
void recordTimeChanged ()
void streamLabelsChanged ()
void trackingEnabledChanged ()
void trackingImageIsActiveChanged ()
void trackingImageIsPointChanged ()
void trackingImageRectChanged ()
void trackingImagePointChanged ()
void trackingImageRadiusChanged ()
void thermalModeChanged ()
void thermalOpacityChanged ()
void storageStatusChanged ()
void captureVideoStateChanged ()
void capturePhotosStateChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Types inherited from MavlinkCameraControlInterface
enum VideoCaptureStatus { VIDEO_CAPTURE_STATUS_STOPPED = 0 , VIDEO_CAPTURE_STATUS_RUNNING , VIDEO_CAPTURE_STATUS_LAST , VIDEO_CAPTURE_STATUS_UNDEFINED = 255 }
enum PhotoCaptureStatus {
PHOTO_CAPTURE_IDLE = 0 , PHOTO_CAPTURE_IN_PROGRESS , PHOTO_CAPTURE_INTERVAL_IDLE , PHOTO_CAPTURE_INTERVAL_IN_PROGRESS ,
PHOTO_CAPTURE_LAST , PHOTO_CAPTURE_STATUS_UNDEFINED = 255
}
Detailed Description
MAVLink Camera API controller - connected to a real mavlink v2 camera.
Definition at line 38 of file VehicleCameraControl.h.
Constructor & Destructor Documentation
VehicleCameraControl()
VehicleCameraControl::VehicleCameraControl (const mavlink_camera_information_t * info, Vehicle * vehicle, int compID, QObject * parent = nullptr)
Definition at line 107 of file VehicleCameraControl.cc.
References _cacheFile, _dataReady(), _hasTrackingPointCapability, _hasTrackingRectCapability, _initWhenReady(), _mavlinkCameraInfo, _modelName, MavlinkCameraControlInterface::_photoCaptureMode, MavlinkCameraControlInterface::_photoLapse, MavlinkCameraControlInterface::_photoLapseCount, _recTimerHandler(), _thermalMode, _thermalOpacity, _vendor, MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer, capturesPhotos(), capturesVideo(), MavlinkCameraControlInterface::dataReady(), firmwareVersion(), focalLength(), hasFocus(), hasModes(), hasTracking(), hasVideoStream(), hasZoom(), kPhotoLapse, kPhotoLapseCount, kPhotoMode, kThermalMode, kThermalOpacity, modelName(), MavlinkCameraControlInterface::PHOTO_CAPTURE_SINGLE, photosInVideoMode(), resolution(), sensorSize(), MavlinkCameraControlInterface::THERMAL_BLEND, vendor(), version(), and videoInPhotoMode().
~VehicleCameraControl()
VehicleCameraControl::~VehicleCameraControl () override
Definition at line 166 of file VehicleCameraControl.cc.
References _cameraSettingsTimer, _captureStatusTimer, _netManager, _storageInfoTimer, _streamInfoTimer, _streamStatusTimer, and MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer.
Member Function Documentation
_cameraSettingsTimeout
void VehicleCameraControl::_cameraSettingsTimeout () protected virtual slot
Definition at line 2003 of file VehicleCameraControl.cc.
References _cameraSettingsRetries, _cameraSettingsTimer, and _requestCameraSettings().
Referenced by _initWhenReady().
_checkForVideoStreams
void VehicleCameraControl::_checkForVideoStreams () protected virtual slot
Definition at line 2310 of file VehicleCameraControl.cc.
References _mavlinkCameraInfo, _requestStreamInfo(), _streamInfoTimeout(), _streamInfoTimer, _streamStatusTimeout(), and _streamStatusTimer.
Referenced by _initWhenReady().
_dataReady
void VehicleCameraControl::_dataReady (QByteArray data) protected virtual slot
Definition at line 2275 of file VehicleCameraControl.cc.
References _initWhenReady(), and _modelName.
Referenced by VehicleCameraControl().
_downloadFinished
void VehicleCameraControl::_downloadFinished () protected virtual slot
Definition at line 2225 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::dataReady().
_findStream() [1/2]
QGCVideoStreamInfo * VehicleCameraControl::_findStream (const QString name) protected virtual
Definition at line 1951 of file VehicleCameraControl.cc.
References _streams, and QmlObjectListModel::count().
_findStream() [2/2]
QGCVideoStreamInfo * VehicleCameraControl::_findStream (uint8_t streamID, bool report = true) protected virtual
Definition at line 1930 of file VehicleCameraControl.cc.
References _streams, and QmlObjectListModel::count().
Referenced by _streamInfoTimeout(), currentStreamInstance(), handleVideoStreamInformation(), and handleVideoStreamStatus().
_initWhenReady
void VehicleCameraControl::_initWhenReady () protected virtual slot
Definition at line 180 of file VehicleCameraControl.cc.
References _cameraSettingsTimeout(), _cameraSettingsTimer, _captureStatusTimer, _checkForVideoStreams(), _mavCommandResult(), _netManager, _onVideoManagerRecordingChanged(), _paramComplete, _requestAllParameters(), _requestCameraSettings(), _requestCaptureStatus(), _requestStorageInfo(), _storageInfoTimeout(), _storageInfoTimer, MavlinkCameraControlInterface::_vehicle, MavlinkCameraControlInterface::cameraModeChanged(), MavlinkCameraControlInterface::capturePhotosStateChanged(), MavlinkCameraControlInterface::captureVideoStateChanged(), MavlinkCameraControlInterface::infoChanged(), VideoManager::instance(), isBasic(), Vehicle::mavCommandResult(), MavlinkCameraControlInterface::parametersReady(), MavlinkCameraControlInterface::photoCaptureStatusChanged(), VideoManager::recordingChanged(), and MavlinkCameraControlInterface::videoCaptureStatusChanged().
Referenced by _dataReady(), and VehicleCameraControl().
_mavCommandResult
void VehicleCameraControl::_mavCommandResult (int vehicleId, int component, int command, int result, int failureCode) protected virtual slot
Definition at line 738 of file VehicleCameraControl.cc.
References _cameraCaptureStatusRetries, _captureInfoRetries, _captureStatusTimer, _requestAllParameters(), _requestCameraSettings(), _requestStorageInfo(), _resetting, _setPhotoCaptureStatus(), _setVideoCaptureStatus(), _storageInfoRetries, MavlinkCameraControlInterface::_vehicle, compID(), Vehicle::id(), MissionCommandTree::instance(), isBasic(), QGCMAVLink::mavResultToString(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, MissionCommandTree::rawName(), MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING, and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_STOPPED.
Referenced by _initWhenReady().
_onVideoManagerRecordingChanged
void VehicleCameraControl::_onVideoManagerRecordingChanged (bool recording) protected virtual slot
Definition at line 844 of file VehicleCameraControl.cc.
References _recordTime, _recTime, MavlinkCameraControlInterface::_videoCaptureStatus(), MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer, MavlinkCameraControlInterface::recordTimeChanged(), and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
Referenced by _initWhenReady().
_paramDone
void VehicleCameraControl::_paramDone () override protected slot
Definition at line 2298 of file VehicleCameraControl.cc.
References _paramComplete, _paramIO, and MavlinkCameraControlInterface::parametersReady().
_recTimerHandler
void VehicleCameraControl::_recTimerHandler () protected virtual slot
Definition at line 838 of file VehicleCameraControl.cc.
References _recordTime, _recTime, and MavlinkCameraControlInterface::recordTimeChanged().
Referenced by VehicleCameraControl().
_requestAllParameters
void VehicleCameraControl::_requestAllParameters () protected virtual slot
Definition at line 1229 of file VehicleCameraControl.cc.
References _paramIO, MavlinkCameraControlInterface::_vehicle, compID(), MAVLinkProtocol::getComponentId(), Vehicle::id(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), Vehicle::sendMessageOnLinkThreadSafe(), and Vehicle::vehicleLinkManager().
Referenced by _initWhenReady(), and _mavCommandResult().
_requestCameraSettings
void VehicleCameraControl::_requestCameraSettings () protected virtual slot
Definition at line 1491 of file VehicleCameraControl.cc.
References _cameraSettingsRetries, _cameraSettingsTimer, _compID, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
Referenced by _cameraSettingsTimeout(), _initWhenReady(), and _mavCommandResult().
_requestCaptureStatus
void VehicleCameraControl::_requestCaptureStatus () protected virtual slot
Definition at line 711 of file VehicleCameraControl.cc.
References _cameraCaptureStatusRetries, _compID, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
Referenced by _initWhenReady().
_requestParamUpdates
void VehicleCameraControl::_requestParamUpdates () protected virtual slot
Definition at line 1483 of file VehicleCameraControl.cc.
References _paramIO, and _updatesToRequest.
_requestStorageInfo
void VehicleCameraControl::_requestStorageInfo () protected virtual slot
Definition at line 1523 of file VehicleCameraControl.cc.
References _compID, _storageInfoRetries, _storageInfoTimer, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
Referenced by _initWhenReady(), _mavCommandResult(), and _storageInfoTimeout().
_requestStreamInfo()
void VehicleCameraControl::_requestStreamInfo (uint8_t streamID) protected virtual
Definition at line 1881 of file VehicleCameraControl.cc.
References _compID, _streamInfoTimer, MavlinkCameraControlInterface::_vehicle, _videoStreamInfoRetries, and Vehicle::sendMavCommand().
Referenced by _checkForVideoStreams(), and _streamInfoTimeout().
_requestStreamStatus()
void VehicleCameraControl::_requestStreamStatus (uint8_t streamID) protected virtual
Definition at line 1905 of file VehicleCameraControl.cc.
References _compID, _streamStatusTimer, MavlinkCameraControlInterface::_vehicle, _videoStreamStatusRetries, and Vehicle::sendMavCommand().
Referenced by _streamStatusTimeout(), and setCurrentStream().
_requestTrackingStatus()
void VehicleCameraControl::_requestTrackingStatus () protected virtual
Definition at line 2474 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
Referenced by startTrackingPoint(), and startTrackingRect().
_setCameraMode()
void VehicleCameraControl::_setCameraMode (CameraMode mode) protected virtual
Definition at line 383 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, _streamStatusTimer, MavlinkCameraControlInterface::cameraModeChanged(), and mode().
Referenced by handleCameraSettings(), and setCameraMode().
_setPhotoCaptureStatus()
void VehicleCameraControl::_setPhotoCaptureStatus (PhotoCaptureStatus captureStatus) protected virtual
Definition at line 862 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_photoCaptureStatusValue, and MavlinkCameraControlInterface::photoCaptureStatusChanged().
Referenced by _mavCommandResult(), handleCameraCaptureStatus(), stopTakePhoto(), and takePhoto().
_setVideoCaptureStatus()
void VehicleCameraControl::_setVideoCaptureStatus (VideoCaptureStatus captureStatus) protected virtual
Definition at line 821 of file VehicleCameraControl.cc.
References _recordTime, _recTime, MavlinkCameraControlInterface::_videoCaptureStatusValue, MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer, MavlinkCameraControlInterface::recordTimeChanged(), MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING, and MavlinkCameraControlInterface::videoCaptureStatusChanged().
Referenced by _mavCommandResult(), and handleCameraCaptureStatus().
_storageInfoTimeout
void VehicleCameraControl::_storageInfoTimeout () protected virtual slot
Definition at line 2016 of file VehicleCameraControl.cc.
References _requestStorageInfo(), _storageInfoRetries, and _storageInfoTimer.
Referenced by _initWhenReady().
_streamInfoTimeout
void VehicleCameraControl::_streamInfoTimeout () protected virtual slot
Definition at line 1966 of file VehicleCameraControl.cc.
References _expectedCount, _findStream(), _requestStreamInfo(), _streamInfoTimer, _streams, MavlinkCameraControlInterface::_vehicle, _videoStreamInfoRetries, MavlinkCameraControlInterface::autoStreamChanged(), and QmlObjectListModel::count().
Referenced by _checkForVideoStreams().
_streamStatusTimeout
void VehicleCameraControl::_streamStatusTimeout () protected virtual slot
Definition at line 1989 of file VehicleCameraControl.cc.
References _requestStreamStatus(), _streamStatusTimer, _videoStreamStatusRetries, and currentStreamInstance().
Referenced by _checkForVideoStreams().
activeSettings()
QStringList VehicleCameraControl::activeSettings () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2338 of file VehicleCameraControl.cc.
References _activeSettings.
aperture()
Fact * VehicleCameraControl::aperture () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2369 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_APERTURE.
autoStream()
bool VehicleCameraControl::autoStream () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1846 of file VehicleCameraControl.cc.
References _streams, QmlObjectListModel::count(), and hasVideoStream().
batteryRemaining()
int VehicleCameraControl::batteryRemaining () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 94 of file VehicleCameraControl.h.
References _batteryRemaining.
batteryRemainingStr()
QString VehicleCameraControl::batteryRemainingStr () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 285 of file VehicleCameraControl.cc.
References _batteryRemaining, and QGC::numberToString().
capturePhotosState()
MavlinkCameraControlInterface::CapturePhotosState VehicleCameraControl::capturePhotosState () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 251 of file VehicleCameraControl.cc.
References _mavlinkCameraInfo, MavlinkCameraControlInterface::_photoCaptureStatus(), MavlinkCameraControlInterface::CapturePhotosStateCapturingMultiplePhotos, MavlinkCameraControlInterface::CapturePhotosStateCapturingSinglePhoto, MavlinkCameraControlInterface::CapturePhotosStateDisabled, MavlinkCameraControlInterface::CapturePhotosStateIdle, MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_IN_PROGRESS, MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IDLE, and MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IN_PROGRESS.
Referenced by stopTakePhoto(), and takePhoto().
capturesPhotos()
bool VehicleCameraControl::capturesPhotos () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 228 of file VehicleCameraControl.cc.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
capturesVideo()
bool VehicleCameraControl::capturesVideo () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 220 of file VehicleCameraControl.cc.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
captureVideoState()
MavlinkCameraControlInterface::CaptureVideoState VehicleCameraControl::captureVideoState () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 235 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, _mavlinkCameraInfo, MavlinkCameraControlInterface::_photoCaptureStatus(), MavlinkCameraControlInterface::_videoCaptureStatus(), MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_SURVEY, MavlinkCameraControlInterface::CaptureVideoStateCapturing, MavlinkCameraControlInterface::CaptureVideoStateDisabled, MavlinkCameraControlInterface::CaptureVideoStateIdle, hasModes(), VideoManager::instance(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
Referenced by startVideoRecording(), stopVideoRecording(), and toggleVideoRecording().
compID()
int VehicleCameraControl::compID () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 87 of file VehicleCameraControl.h.
References _compID.
Referenced by _mavCommandResult(), and _requestAllParameters().
currentStream()
int VehicleCameraControl::currentStream () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 103 of file VehicleCameraControl.h.
References _currentStream.
currentStreamInstance()
QGCVideoStreamInfo * VehicleCameraControl::currentStreamInstance () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1855 of file VehicleCameraControl.cc.
References _currentStream, _findStream(), and _streamLabels.
Referenced by _streamStatusTimeout(), resumeStream(), setCurrentStream(), and stopStream().
ev()
Fact * VehicleCameraControl::ev () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2351 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_EV.
exposureMode()
Fact * VehicleCameraControl::exposureMode () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2345 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_EXPMODE.
factChanged()
void VehicleCameraControl::factChanged (Fact * pFact) override virtual
Notify controller a parameter has changed.
Implements MavlinkCameraControlInterface.
Definition at line 732 of file VehicleCameraControl.cc.
firmwareVersion()
QString VehicleCameraControl::firmwareVersion () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 267 of file VehicleCameraControl.cc.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
focalLength()
qreal VehicleCameraControl::focalLength () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 70 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
focusLevel()
qreal VehicleCameraControl::focusLevel () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 98 of file VehicleCameraControl.h.
References _focusLevel.
formatCard()
void VehicleCameraControl::formatCard (int id = 1) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 618 of file VehicleCameraControl.cc.
References _compID, _resetting, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
handleBatteryStatus()
void VehicleCameraControl::handleBatteryStatus (const mavlink_battery_status_t & bs) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1605 of file VehicleCameraControl.cc.
References _batteryRemaining, and MavlinkCameraControlInterface::batteryRemainingChanged().
handleCameraCaptureStatus()
void VehicleCameraControl::handleCameraCaptureStatus (const mavlink_camera_capture_status_t & cameraCaptureStatus) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1616 of file VehicleCameraControl.cc.
References _cameraCaptureStatusRetries, _captureStatusTimer, MavlinkCameraControlInterface::_photoCaptureStatus(), _recordTime, _recTime, _setPhotoCaptureStatus(), _setVideoCaptureStatus(), _storageFree, MavlinkCameraControlInterface::_videoCaptureStatus(), MavlinkCameraControlInterface::captureImageStatusToStr(), MavlinkCameraControlInterface::captureVideoStatusToStr(), QGCFileHelper::ensureDirectoryExists(), VideoManager::grabImage(), VideoManager::instance(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IDLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IN_PROGRESS, MavlinkCameraControlInterface::PHOTO_CAPTURE_LAST, MavlinkCameraControlInterface::PHOTO_CAPTURE_SINGLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_STATUS_UNDEFINED, MavlinkCameraControlInterface::photoCaptureMode(), MavlinkCameraControlInterface::recordTimeChanged(), AppSettings::savePath(), MavlinkCameraControlInterface::storageFreeChanged(), MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_LAST, MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING, and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_UNDEFINED.
handleCameraSettings()
void VehicleCameraControl::handleCameraSettings (const mavlink_camera_settings_t & settings) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1551 of file VehicleCameraControl.cc.
References _cameraSettingsRetries, _cameraSettingsTimer, _focusLevel, _setCameraMode(), _zoomLevel, MavlinkCameraControlInterface::focusLevelChanged(), and MavlinkCameraControlInterface::zoomLevelChanged().
handleParamExtAck()
void VehicleCameraControl::handleParamExtAck (const mavlink_param_ext_ack_t & paramExtAck) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1263 of file VehicleCameraControl.cc.
References _paramIO.
handleParamExtValue()
void VehicleCameraControl::handleParamExtValue (const mavlink_param_ext_value_t & paramExtValue) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1282 of file VehicleCameraControl.cc.
References _paramIO.
handleStorageInformation()
void VehicleCameraControl::handleStorageInformation (const mavlink_storage_information_t & storageInformation) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1574 of file VehicleCameraControl.cc.
References _storageFree, _storageInfoRetries, _storageInfoTimer, _storageStatus, _storageTotal, MavlinkCameraControlInterface::storageFreeChanged(), MavlinkCameraControlInterface::storageStatusChanged(), MavlinkCameraControlInterface::storageStatusToStr(), and MavlinkCameraControlInterface::storageTotalChanged().
handleTrackingImageStatus()
void VehicleCameraControl::handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t & trackingImageStatus) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1725 of file VehicleCameraControl.cc.
References _trackingImageIsActive, _trackingImageIsPoint, _trackingImagePoint, _trackingImageRadius, _trackingImageRect, _trackingImageStatus, trackingEnabled(), MavlinkCameraControlInterface::trackingImageIsActiveChanged(), MavlinkCameraControlInterface::trackingImageIsPointChanged(), MavlinkCameraControlInterface::trackingImagePointChanged(), MavlinkCameraControlInterface::trackingImageRadiusChanged(), and MavlinkCameraControlInterface::trackingImageRectChanged().
handleVideoStreamInformation()
void VehicleCameraControl::handleVideoStreamInformation (const mavlink_video_stream_information_t & videoStreamInformation) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1663 of file VehicleCameraControl.cc.
References _expectedCount, _findStream(), _streamInfoTimer, _streamLabels, _streams, MavlinkCameraControlInterface::_vehicle, _videoStreamInfoRetries, QmlObjectListModel::append(), MavlinkCameraControlInterface::autoStreamChanged(), QmlObjectListModel::count(), MavlinkCameraControlInterface::streamLabelsChanged(), MavlinkCameraControlInterface::streamsChanged(), and MavlinkCameraControlInterface::thermalStreamChanged().
handleVideoStreamStatus()
void VehicleCameraControl::handleVideoStreamStatus (const mavlink_video_stream_status_t & videoStreamStatus) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1705 of file VehicleCameraControl.cc.
References _findStream(), _streamStatusTimer, and _videoStreamStatusRetries.
hasFocus()
bool VehicleCameraControl::hasFocus () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 77 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by setFocusLevel(), startFocus(), stepFocus(), stopFocus(), and VehicleCameraControl().
hasModes()
bool VehicleCameraControl::hasModes () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 75 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by captureVideoState(), setCameraMode(), setCameraModePhoto(), setCameraModeVideo(), and VehicleCameraControl().
hasTracking()
bool VehicleCameraControl::hasTracking () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 78 of file VehicleCameraControl.h.
References _hasTrackingPointCapability, and _hasTrackingRectCapability.
Referenced by VehicleCameraControl().
hasVideoStream()
bool VehicleCameraControl::hasVideoStream () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 81 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by autoStream(), and VehicleCameraControl().
hasZoom()
bool VehicleCameraControl::hasZoom () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 76 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by setZoomLevel(), startZoom(), stepZoom(), stopZoom(), and VehicleCameraControl().
incomingParameter()
bool VehicleCameraControl::incomingParameter (Fact * pFact, QVariant & newValue) override virtual
Allow controller to modify or invalidate incoming parameter.
Implements MavlinkCameraControlInterface.
Definition at line 2323 of file VehicleCameraControl.cc.
isBasic()
bool VehicleCameraControl::isBasic () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 88 of file VehicleCameraControl.h.
References _settings.
Referenced by _initWhenReady(), and _mavCommandResult().
iso()
Fact * VehicleCameraControl::iso () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2357 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_ISO.
mode()
Fact * VehicleCameraControl::mode () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2381 of file VehicleCameraControl.cc.
References _paramComplete, and kCAM_MODE.
Referenced by _setCameraMode(), setCameraMode(), setPhotoCaptureMode(), and setThermalMode().
modelName()
QString VehicleCameraControl::modelName () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 67 of file VehicleCameraControl.h.
References _modelName.
Referenced by VehicleCameraControl().
paramComplete()
bool VehicleCameraControl::paramComplete () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 96 of file VehicleCameraControl.h.
References _paramComplete.
photosInVideoMode()
bool VehicleCameraControl::photosInVideoMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 82 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by takePhoto(), and VehicleCameraControl().
recordTime()
quint32 VehicleCameraControl::recordTime () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 106 of file VehicleCameraControl.h.
References _recordTime.
Referenced by recordTimeStr().
recordTimeStr()
QString VehicleCameraControl::recordTimeStr () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 275 of file VehicleCameraControl.cc.
References recordTime().
resetSettings()
void VehicleCameraControl::resetSettings () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 605 of file VehicleCameraControl.cc.
References _compID, _resetting, MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
resolution()
QSize VehicleCameraControl::resolution () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 72 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
resumeStream()
void VehicleCameraControl::resumeStream () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1833 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, currentStreamInstance(), and Vehicle::sendMavCommand().
sensorSize()
QSizeF VehicleCameraControl::sensorSize () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 71 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
setCameraMode()
void VehicleCameraControl::setCameraMode (CameraMode cameraMode) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 321 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, _compID, _resetting, _setCameraMode(), MavlinkCameraControlInterface::_vehicle, MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_VIDEO, MavlinkCameraControlInterface::cameraMode(), MavlinkCameraControlInterface::cameraModeToStr(), hasModes(), mode(), and Vehicle::sendMavCommand().
Referenced by setCameraModePhoto(), and setCameraModeVideo().
setCameraModePhoto()
void VehicleCameraControl::setCameraModePhoto () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 307 of file VehicleCameraControl.cc.
References _resetting, MavlinkCameraControlInterface::CAM_MODE_PHOTO, hasModes(), and setCameraMode().
Referenced by toggleCameraMode().
setCameraModeVideo()
void VehicleCameraControl::setCameraModeVideo () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 293 of file VehicleCameraControl.cc.
References _resetting, MavlinkCameraControlInterface::CAM_MODE_VIDEO, hasModes(), and setCameraMode().
Referenced by toggleCameraMode().
setCurrentStream()
void VehicleCameraControl::setCurrentStream (int stream) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1789 of file VehicleCameraControl.cc.
References _compID, _currentStream, _requestStreamStatus(), _streamLabels, MavlinkCameraControlInterface::_vehicle, MavlinkCameraControlInterface::currentStreamChanged(), currentStreamInstance(), and Vehicle::sendMavCommand().
setFocusLevel()
void VehicleCameraControl::setFocusLevel (qreal level) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 588 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasFocus(), and Vehicle::sendMavCommand().
setPhotoCaptureMode()
void VehicleCameraControl::setPhotoCaptureMode (PhotoCaptureMode mode) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 357 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_photoCaptureMode, _resetting, kPhotoMode, mode(), and MavlinkCameraControlInterface::photoCaptureModeChanged().
setPhotoLapse()
void VehicleCameraControl::setPhotoLapse (qreal interval) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 367 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_photoLapse, kPhotoLapse, and MavlinkCameraControlInterface::photoLapseChanged().
setPhotoLapseCount()
void VehicleCameraControl::setPhotoLapseCount (int count) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 375 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_photoLapseCount, kPhotoLapseCount, and MavlinkCameraControlInterface::photoLapseCountChanged().
setThermalMode()
void VehicleCameraControl::setThermalMode (ThermalViewMode mode) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 551 of file VehicleCameraControl.cc.
References _thermalMode, kThermalMode, mode(), and MavlinkCameraControlInterface::thermalModeChanged().
setThermalOpacity()
void VehicleCameraControl::setThermalOpacity (double val) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 559 of file VehicleCameraControl.cc.
References _thermalOpacity, kThermalOpacity, and MavlinkCameraControlInterface::thermalOpacityChanged().
setTrackingEnabled()
void VehicleCameraControl::setTrackingEnabled (bool set) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2386 of file VehicleCameraControl.cc.
References _trackingEnabled, stopTracking(), and MavlinkCameraControlInterface::trackingEnabledChanged().
setZoomLevel()
void VehicleCameraControl::setZoomLevel (qreal level) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 571 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasZoom(), and Vehicle::sendMavCommand().
shutterSpeed()
Fact * VehicleCameraControl::shutterSpeed () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2363 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_SHUTTERSPD.
startFocus()
void VehicleCameraControl::startFocus (int direction) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 685 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasFocus(), and Vehicle::sendMavCommand().
startTrackingPoint()
void VehicleCameraControl::startTrackingPoint (QPointF point, double radius) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2422 of file VehicleCameraControl.cc.
References _compID, _hasTrackingPointCapability, _requestTrackingStatus(), MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
startTrackingRect()
void VehicleCameraControl::startTrackingRect (QRectF rec) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2398 of file VehicleCameraControl.cc.
References _compID, _hasTrackingRectCapability, _requestTrackingStatus(), MavlinkCameraControlInterface::_vehicle, and Vehicle::sendMavCommand().
startVideoRecording()
bool VehicleCameraControl::startVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 490 of file VehicleCameraControl.cc.
References _compID, _mavlinkCameraInfo, _resetting, MavlinkCameraControlInterface::_vehicle, captureVideoState(), MavlinkCameraControlInterface::CaptureVideoStateCapturing, MavlinkCameraControlInterface::CaptureVideoStateDisabled, VideoManager::instance(), Vehicle::sendMavCommand(), and VideoManager::startRecording().
Referenced by toggleVideoRecording().
startZoom()
void VehicleCameraControl::startZoom (int direction) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 646 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasZoom(), and Vehicle::sendMavCommand().
stepFocus()
void VehicleCameraControl::stepFocus (int direction) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 672 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasFocus(), and Vehicle::sendMavCommand().
stepZoom()
void VehicleCameraControl::stepZoom (int direction) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 633 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasZoom(), and Vehicle::sendMavCommand().
stopFocus()
void VehicleCameraControl::stopFocus () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 698 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasFocus(), and Vehicle::sendMavCommand().
stopStream()
void VehicleCameraControl::stopStream () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1820 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, currentStreamInstance(), and Vehicle::sendMavCommand().
stopTakePhoto()
bool VehicleCameraControl::stopTakePhoto () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 466 of file VehicleCameraControl.cc.
References _captureInfoRetries, _compID, _resetting, _setPhotoCaptureStatus(), MavlinkCameraControlInterface::_vehicle, capturePhotosState(), MavlinkCameraControlInterface::CapturePhotosStateCapturingMultiplePhotos, MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, and Vehicle::sendMavCommand().
stopTracking()
void VehicleCameraControl::stopTracking () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2444 of file VehicleCameraControl.cc.
References _compID, _trackingImageIsActive, _trackingImageIsPoint, _trackingImagePoint, _trackingImageRadius, _trackingImageRect, MavlinkCameraControlInterface::_vehicle, Vehicle::sendMavCommand(), MavlinkCameraControlInterface::trackingImageIsActiveChanged(), and MavlinkCameraControlInterface::trackingImageIsPointChanged().
Referenced by setTrackingEnabled().
stopVideoRecording()
bool VehicleCameraControl::stopVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 523 of file VehicleCameraControl.cc.
References _compID, _mavlinkCameraInfo, _resetting, MavlinkCameraControlInterface::_vehicle, captureVideoState(), MavlinkCameraControlInterface::CaptureVideoStateIdle, VideoManager::instance(), Vehicle::sendMavCommand(), and VideoManager::stopRecording().
Referenced by toggleVideoRecording().
stopZoom()
void VehicleCameraControl::stopZoom () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 659 of file VehicleCameraControl.cc.
References _compID, MavlinkCameraControlInterface::_vehicle, hasZoom(), and Vehicle::sendMavCommand().
storageFree()
quint32 VehicleCameraControl::storageFree () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 91 of file VehicleCameraControl.h.
References _storageFree.
storageFreeStr()
QString VehicleCameraControl::storageFreeStr () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 280 of file VehicleCameraControl.cc.
References _storageFree, and QGC::bigSizeMBToString().
storageStatus()
StorageStatus VehicleCameraControl::storageStatus () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 89 of file VehicleCameraControl.h.
References _storageStatus.
storageTotal()
quint32 VehicleCameraControl::storageTotal () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 93 of file VehicleCameraControl.h.
References _storageTotal.
streamLabels()
QStringList VehicleCameraControl::streamLabels () const inline override virtual
Stream names to show the user (for selection)
Implements MavlinkCameraControlInterface.
Definition at line 109 of file VehicleCameraControl.h.
References _streamLabels.
streams()
QmlObjectListModel * VehicleCameraControl::streams () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 100 of file VehicleCameraControl.h.
References _streams.
supportsTrackingPoint()
bool VehicleCameraControl::supportsTrackingPoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 79 of file VehicleCameraControl.h.
References _hasTrackingPointCapability.
supportsTrackingRect()
bool VehicleCameraControl::supportsTrackingRect () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 80 of file VehicleCameraControl.h.
References _hasTrackingRectCapability.
takePhoto()
bool VehicleCameraControl::takePhoto () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 419 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, _captureInfoRetries, _compID, _mavlinkCameraInfo, MavlinkCameraControlInterface::_photoCaptureMode, MavlinkCameraControlInterface::_photoLapse, MavlinkCameraControlInterface::_photoLapseCount, _resetting, _setPhotoCaptureStatus(), MavlinkCameraControlInterface::_vehicle, MavlinkCameraControlInterface::CAM_MODE_VIDEO, capturePhotosState(), MavlinkCameraControlInterface::CapturePhotosStateDisabled, MavlinkCameraControlInterface::CapturePhotosStateIdle, VideoManager::grabImage(), VideoManager::instance(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_IN_PROGRESS, MavlinkCameraControlInterface::PHOTO_CAPTURE_SINGLE, photosInVideoMode(), Vehicle::sendMavCommand(), and QGC::showAppMessage().
thermalMode()
ThermalViewMode VehicleCameraControl::thermalMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 111 of file VehicleCameraControl.h.
References _thermalMode.
thermalOpacity()
double VehicleCameraControl::thermalOpacity () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 113 of file VehicleCameraControl.h.
References _thermalOpacity.
thermalStreamInstance()
QGCVideoStreamInfo * VehicleCameraControl::thermalStreamInstance () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 1865 of file VehicleCameraControl.cc.
References _streams, and QmlObjectListModel::count().
toggleCameraMode()
void VehicleCameraControl::toggleCameraMode () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 393 of file VehicleCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, _resetting, MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_SURVEY, MavlinkCameraControlInterface::CAM_MODE_VIDEO, setCameraModePhoto(), and setCameraModeVideo().
toggleVideoRecording()
bool VehicleCameraControl::toggleVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 404 of file VehicleCameraControl.cc.
References _resetting, captureVideoState(), MavlinkCameraControlInterface::CaptureVideoStateCapturing, startVideoRecording(), and stopVideoRecording().
trackingEnabled()
bool VehicleCameraControl::trackingEnabled () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 133 of file VehicleCameraControl.h.
References _trackingEnabled.
Referenced by handleTrackingImageStatus().
trackingImageIsActive()
bool VehicleCameraControl::trackingImageIsActive () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 136 of file VehicleCameraControl.h.
References _trackingImageIsActive.
trackingImageIsPoint()
bool VehicleCameraControl::trackingImageIsPoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 137 of file VehicleCameraControl.h.
References _trackingImageIsPoint.
trackingImagePoint()
QPointF VehicleCameraControl::trackingImagePoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 139 of file VehicleCameraControl.h.
References _trackingImagePoint.
trackingImageRadius()
qreal VehicleCameraControl::trackingImageRadius () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 140 of file VehicleCameraControl.h.
References _trackingImageRadius.
trackingImageRect()
QRectF VehicleCameraControl::trackingImageRect () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 138 of file VehicleCameraControl.h.
References _trackingImageRect.
validateParameter()
bool VehicleCameraControl::validateParameter (Fact * pFact, QVariant & newValue) override virtual
Allow controller to modify or invalidate parameter change.
Implements MavlinkCameraControlInterface.
Definition at line 2330 of file VehicleCameraControl.cc.
vendor()
QString VehicleCameraControl::vendor () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 68 of file VehicleCameraControl.h.
References _vendor.
Referenced by VehicleCameraControl().
version()
int VehicleCameraControl::version () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 66 of file VehicleCameraControl.h.
References _version.
Referenced by VehicleCameraControl().
videoInPhotoMode()
bool VehicleCameraControl::videoInPhotoMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 83 of file VehicleCameraControl.h.
References _mavlinkCameraInfo.
Referenced by VehicleCameraControl().
wb()
Fact * VehicleCameraControl::wb () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 2375 of file VehicleCameraControl.cc.
References _activeSettings, _paramComplete, and kCAM_WBMODE.
zoomLevel()
qreal VehicleCameraControl::zoomLevel () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 97 of file VehicleCameraControl.h.
References _zoomLevel.
Member Data Documentation
_activeSettings
QStringList VehicleCameraControl::_activeSettings protected
Definition at line 270 of file VehicleCameraControl.h.
Referenced by activeSettings(), aperture(), ev(), exposureMode(), iso(), shutterSpeed(), and wb().
_batteryRemaining
int VehicleCameraControl::_batteryRemaining = -1 protected
Definition at line 264 of file VehicleCameraControl.h.
Referenced by batteryRemaining(), batteryRemainingStr(), and handleBatteryStatus().
_cached
bool VehicleCameraControl::_cached = false protected
Definition at line 258 of file VehicleCameraControl.h.
_cacheFile
QString VehicleCameraControl::_cacheFile protected
Definition at line 268 of file VehicleCameraControl.h.
Referenced by VehicleCameraControl().
_cameraCaptureStatusRetries
int VehicleCameraControl::_cameraCaptureStatusRetries = 0 protected
Definition at line 279 of file VehicleCameraControl.h.
Referenced by _mavCommandResult(), _requestCaptureStatus(), and handleCameraCaptureStatus().
_cameraSettingsRetries
int VehicleCameraControl::_cameraSettingsRetries = 0 protected
Definition at line 278 of file VehicleCameraControl.h.
Referenced by _cameraSettingsTimeout(), _requestCameraSettings(), and handleCameraSettings().
_cameraSettingsTimer
QTimer VehicleCameraControl::_cameraSettingsTimer protected
Definition at line 296 of file VehicleCameraControl.h.
Referenced by _cameraSettingsTimeout(), _initWhenReady(), _requestCameraSettings(), handleCameraSettings(), and ~VehicleCameraControl().
_captureInfoRetries
int VehicleCameraControl::_captureInfoRetries = 0 protected
Definition at line 281 of file VehicleCameraControl.h.
Referenced by _mavCommandResult(), stopTakePhoto(), and takePhoto().
_captureStatusTimer
QTimer VehicleCameraControl::_captureStatusTimer protected
Definition at line 272 of file VehicleCameraControl.h.
Referenced by _initWhenReady(), _mavCommandResult(), handleCameraCaptureStatus(), and ~VehicleCameraControl().
_compID
int VehicleCameraControl::_compID = 0 protected
Definition at line 255 of file VehicleCameraControl.h.
Referenced by _requestCameraSettings(), _requestCaptureStatus(), _requestStorageInfo(), _requestStreamInfo(), _requestStreamStatus(), _requestTrackingStatus(), compID(), formatCard(), resetSettings(), resumeStream(), setCameraMode(), setCurrentStream(), setFocusLevel(), setZoomLevel(), startFocus(), startTrackingPoint(), startTrackingRect(), startVideoRecording(), startZoom(), stepFocus(), stepZoom(), stopFocus(), stopStream(), stopTakePhoto(), stopTracking(), stopVideoRecording(), stopZoom(), and takePhoto().
_currentStream
int VehicleCameraControl::_currentStream = 0 protected
Definition at line 292 of file VehicleCameraControl.h.
Referenced by currentStream(), currentStreamInstance(), and setCurrentStream().
_expectedCount
int VehicleCameraControl::_expectedCount = 1 protected
Definition at line 293 of file VehicleCameraControl.h.
Referenced by _streamInfoTimeout(), and handleVideoStreamInformation().
_focusLevel
qreal VehicleCameraControl::_focusLevel = 0.0 protected
Definition at line 261 of file VehicleCameraControl.h.
Referenced by focusLevel(), and handleCameraSettings().
_hasTrackingPointCapability
bool VehicleCameraControl::_hasTrackingPointCapability = false protected
Definition at line 303 of file VehicleCameraControl.h.
Referenced by hasTracking(), startTrackingPoint(), supportsTrackingPoint(), and VehicleCameraControl().
_hasTrackingRectCapability
bool VehicleCameraControl::_hasTrackingRectCapability = false protected
Definition at line 302 of file VehicleCameraControl.h.
Referenced by hasTracking(), startTrackingRect(), supportsTrackingRect(), and VehicleCameraControl().
_mavlinkCameraInfo
mavlink_camera_information_t VehicleCameraControl::_mavlinkCameraInfo protected
Definition at line 256 of file VehicleCameraControl.h.
Referenced by _checkForVideoStreams(), capturePhotosState(), capturesPhotos(), capturesVideo(), captureVideoState(), firmwareVersion(), focalLength(), hasFocus(), hasModes(), hasVideoStream(), hasZoom(), photosInVideoMode(), resolution(), sensorSize(), startVideoRecording(), stopVideoRecording(), takePhoto(), VehicleCameraControl(), and videoInPhotoMode().
_modelName
QString VehicleCameraControl::_modelName protected
Definition at line 266 of file VehicleCameraControl.h.
Referenced by _dataReady(), modelName(), and VehicleCameraControl().
_netManager
QNetworkAccessManager* VehicleCameraControl::_netManager = nullptr protected
Definition at line 265 of file VehicleCameraControl.h.
Referenced by _initWhenReady(), and ~VehicleCameraControl().
_optionRanges
QList<QGCCameraOptionRange*> VehicleCameraControl::_optionRanges protected
Definition at line 274 of file VehicleCameraControl.h.
_originalOptNames
QMap<QString, QStringList> VehicleCameraControl::_originalOptNames protected
Definition at line 275 of file VehicleCameraControl.h.
_originalOptValues
QMap<QString, QVariantList> VehicleCameraControl::_originalOptValues protected
Definition at line 276 of file VehicleCameraControl.h.
_paramComplete
bool VehicleCameraControl::_paramComplete = false protected
Definition at line 259 of file VehicleCameraControl.h.
Referenced by _initWhenReady(), _paramDone(), aperture(), ev(), exposureMode(), iso(), mode(), paramComplete(), shutterSpeed(), and wb().
_paramIO
QMap<QString, QGCCameraParamIO*> VehicleCameraControl::_paramIO protected
Definition at line 277 of file VehicleCameraControl.h.
Referenced by _paramDone(), _requestAllParameters(), _requestParamUpdates(), handleParamExtAck(), and handleParamExtValue().
_recordTime
uint32_t VehicleCameraControl::_recordTime = 0 protected
Definition at line 284 of file VehicleCameraControl.h.
Referenced by _onVideoManagerRecordingChanged(), _recTimerHandler(), _setVideoCaptureStatus(), handleCameraCaptureStatus(), and recordTime().
_recTime
QTime VehicleCameraControl::_recTime protected
Definition at line 283 of file VehicleCameraControl.h.
Referenced by _onVideoManagerRecordingChanged(), _recTimerHandler(), _setVideoCaptureStatus(), and handleCameraCaptureStatus().
_requestCount
int VehicleCameraControl::_requestCount = 0 protected
Definition at line 291 of file VehicleCameraControl.h.
_requestUpdates
QMap<QString, QStringList> VehicleCameraControl::_requestUpdates protected
Definition at line 286 of file VehicleCameraControl.h.
_resetting
bool VehicleCameraControl::_resetting = false protected
Definition at line 282 of file VehicleCameraControl.h.
Referenced by _mavCommandResult(), formatCard(), resetSettings(), setCameraMode(), setCameraModePhoto(), setCameraModeVideo(), setPhotoCaptureMode(), startVideoRecording(), stopTakePhoto(), stopVideoRecording(), takePhoto(), toggleCameraMode(), and toggleVideoRecording().
_settings
QStringList VehicleCameraControl::_settings protected
Definition at line 271 of file VehicleCameraControl.h.
Referenced by isBasic().
_storageFree
uint32_t VehicleCameraControl::_storageFree = 0 protected
Definition at line 262 of file VehicleCameraControl.h.
Referenced by handleCameraCaptureStatus(), handleStorageInformation(), storageFree(), and storageFreeStr().
_storageInfoRetries
int VehicleCameraControl::_storageInfoRetries = 0 protected
Definition at line 280 of file VehicleCameraControl.h.
Referenced by _mavCommandResult(), _requestStorageInfo(), _storageInfoTimeout(), and handleStorageInformation().
_storageInfoTimer
QTimer VehicleCameraControl::_storageInfoTimer protected
Definition at line 297 of file VehicleCameraControl.h.
Referenced by _initWhenReady(), _requestStorageInfo(), _storageInfoTimeout(), handleStorageInformation(), and ~VehicleCameraControl().
_storageStatus
StorageStatus VehicleCameraControl::_storageStatus = STORAGE_NOT_SUPPORTED protected
Definition at line 269 of file VehicleCameraControl.h.
Referenced by handleStorageInformation(), and storageStatus().
_storageTotal
uint32_t VehicleCameraControl::_storageTotal = 0 protected
Definition at line 263 of file VehicleCameraControl.h.
Referenced by handleStorageInformation(), and storageTotal().
_streamInfoTimer
QTimer VehicleCameraControl::_streamInfoTimer protected
Definition at line 294 of file VehicleCameraControl.h.
Referenced by _checkForVideoStreams(), _requestStreamInfo(), _streamInfoTimeout(), handleVideoStreamInformation(), and ~VehicleCameraControl().
_streamLabels
QStringList VehicleCameraControl::_streamLabels protected
Definition at line 299 of file VehicleCameraControl.h.
Referenced by currentStreamInstance(), handleVideoStreamInformation(), setCurrentStream(), and streamLabels().
_streams
QmlObjectListModel VehicleCameraControl::_streams protected
Definition at line 298 of file VehicleCameraControl.h.
Referenced by _findStream(), _findStream(), _streamInfoTimeout(), autoStream(), handleVideoStreamInformation(), streams(), and thermalStreamInstance().
_streamStatusTimer
QTimer VehicleCameraControl::_streamStatusTimer protected
Definition at line 295 of file VehicleCameraControl.h.
Referenced by _checkForVideoStreams(), _requestStreamStatus(), _setCameraMode(), _streamStatusTimeout(), handleVideoStreamStatus(), and ~VehicleCameraControl().
_thermalMode
ThermalViewMode VehicleCameraControl::_thermalMode = THERMAL_BLEND protected
Definition at line 300 of file VehicleCameraControl.h.
Referenced by setThermalMode(), thermalMode(), and VehicleCameraControl().
_thermalOpacity
double VehicleCameraControl::_thermalOpacity = 85.0 protected
Definition at line 301 of file VehicleCameraControl.h.
Referenced by setThermalOpacity(), thermalOpacity(), and VehicleCameraControl().
_trackingEnabled
bool VehicleCameraControl::_trackingEnabled = false protected
Definition at line 304 of file VehicleCameraControl.h.
Referenced by setTrackingEnabled(), and trackingEnabled().
_trackingImageIsActive
bool VehicleCameraControl::_trackingImageIsActive = false protected
Definition at line 305 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus(), stopTracking(), and trackingImageIsActive().
_trackingImageIsPoint
bool VehicleCameraControl::_trackingImageIsPoint = false protected
Definition at line 306 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus(), stopTracking(), and trackingImageIsPoint().
_trackingImagePoint
QPointF VehicleCameraControl::_trackingImagePoint protected
Definition at line 309 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus(), stopTracking(), and trackingImagePoint().
_trackingImageRadius
qreal VehicleCameraControl::_trackingImageRadius = 0.0 protected
Definition at line 310 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus(), stopTracking(), and trackingImageRadius().
_trackingImageRect
QRectF VehicleCameraControl::_trackingImageRect protected
Definition at line 308 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus(), stopTracking(), and trackingImageRect().
_trackingImageStatus
mavlink_camera_tracking_image_status_t VehicleCameraControl::_trackingImageStatus {} protected
Definition at line 307 of file VehicleCameraControl.h.
Referenced by handleTrackingImageStatus().
_updatesToRequest
QStringList VehicleCameraControl::_updatesToRequest protected
Definition at line 287 of file VehicleCameraControl.h.
Referenced by _requestParamUpdates().
_valueExclusions
QList<QGCCameraOptionExclusion*> VehicleCameraControl::_valueExclusions protected
Definition at line 273 of file VehicleCameraControl.h.
_vendor
QString VehicleCameraControl::_vendor protected
Definition at line 267 of file VehicleCameraControl.h.
Referenced by VehicleCameraControl(), and vendor().
_version
int VehicleCameraControl::_version = 0 protected
Definition at line 257 of file VehicleCameraControl.h.
Referenced by version().
_videoStreamInfoRetries
int VehicleCameraControl::_videoStreamInfoRetries = 0 protected
Definition at line 289 of file VehicleCameraControl.h.
Referenced by _requestStreamInfo(), _streamInfoTimeout(), and handleVideoStreamInformation().
_videoStreamStatusRetries
int VehicleCameraControl::_videoStreamStatusRetries = 0 protected
Definition at line 290 of file VehicleCameraControl.h.
Referenced by _requestStreamStatus(), _streamStatusTimeout(), and handleVideoStreamStatus().
_zoomLevel
qreal VehicleCameraControl::_zoomLevel = 0.0 protected
Definition at line 260 of file VehicleCameraControl.h.
Referenced by handleCameraSettings(), and zoomLevel().
kCAM_APERTURE
constexpr const char* VehicleCameraControl::kCAM_APERTURE = "CAM_APERTURE" static constexpr
Definition at line 200 of file VehicleCameraControl.h.
Referenced by aperture().
kCAM_EV
constexpr const char* VehicleCameraControl::kCAM_EV = "CAM_EV" static constexpr
Definition at line 196 of file VehicleCameraControl.h.
Referenced by ev().
kCAM_EXPMODE
constexpr const char* VehicleCameraControl::kCAM_EXPMODE = "CAM_EXPMODE" static constexpr
Definition at line 197 of file VehicleCameraControl.h.
Referenced by exposureMode().
kCAM_ISO
constexpr const char* VehicleCameraControl::kCAM_ISO = "CAM_ISO" static constexpr
Definition at line 198 of file VehicleCameraControl.h.
Referenced by iso().
kCAM_MODE
constexpr const char* VehicleCameraControl::kCAM_MODE = "CAM_MODE" static constexpr
Definition at line 202 of file VehicleCameraControl.h.
Referenced by mode().
kCAM_SHUTTERSPD
constexpr const char* VehicleCameraControl::kCAM_SHUTTERSPD = "CAM_SHUTTERSPD" static constexpr
Definition at line 199 of file VehicleCameraControl.h.
Referenced by shutterSpeed().
kCAM_WBMODE
constexpr const char* VehicleCameraControl::kCAM_WBMODE = "CAM_WBMODE" static constexpr
Definition at line 201 of file VehicleCameraControl.h.
Referenced by wb().
kCondition
constexpr const char* VehicleCameraControl::kCondition = "condition" static constexpr
Definition at line 153 of file VehicleCameraControl.h.
kControl
constexpr const char* VehicleCameraControl::kControl = "control" static constexpr
Definition at line 154 of file VehicleCameraControl.h.
kDecimalPlaces
constexpr const char* VehicleCameraControl::kDecimalPlaces = "decimalPlaces" static constexpr
Definition at line 177 of file VehicleCameraControl.h.
kDefault
constexpr const char* VehicleCameraControl::kDefault = "default" static constexpr
Definition at line 155 of file VehicleCameraControl.h.
kDefnition
constexpr const char* VehicleCameraControl::kDefnition = "definition" static constexpr
Definition at line 156 of file VehicleCameraControl.h.
kDescription
constexpr const char* VehicleCameraControl::kDescription = "description" static constexpr
Definition at line 157 of file VehicleCameraControl.h.
kExclusion
constexpr const char* VehicleCameraControl::kExclusion = "exclude" static constexpr
Definition at line 158 of file VehicleCameraControl.h.
kExclusions
constexpr const char* VehicleCameraControl::kExclusions = "exclusions" static constexpr
Definition at line 159 of file VehicleCameraControl.h.
kLocale
constexpr const char* VehicleCameraControl::kLocale = "locale" static constexpr
Definition at line 160 of file VehicleCameraControl.h.
kLocalization
constexpr const char* VehicleCameraControl::kLocalization = "localization" static constexpr
Definition at line 161 of file VehicleCameraControl.h.
kMax
constexpr const char* VehicleCameraControl::kMax = "max" static constexpr
Definition at line 162 of file VehicleCameraControl.h.
kMin
constexpr const char* VehicleCameraControl::kMin = "min" static constexpr
Definition at line 163 of file VehicleCameraControl.h.
kModel
constexpr const char* VehicleCameraControl::kModel = "model" static constexpr
Definition at line 164 of file VehicleCameraControl.h.
kName
constexpr const char* VehicleCameraControl::kName = "name" static constexpr
Definition at line 165 of file VehicleCameraControl.h.
kOption
constexpr const char* VehicleCameraControl::kOption = "option" static constexpr
Definition at line 166 of file VehicleCameraControl.h.
kOptions
constexpr const char* VehicleCameraControl::kOptions = "options" static constexpr
Definition at line 167 of file VehicleCameraControl.h.
kOriginal
constexpr const char* VehicleCameraControl::kOriginal = "original" static constexpr
Definition at line 168 of file VehicleCameraControl.h.
kParameter
constexpr const char* VehicleCameraControl::kParameter = "parameter" static constexpr
Definition at line 169 of file VehicleCameraControl.h.
kParameterrange
constexpr const char* VehicleCameraControl::kParameterrange = "parameterrange" static constexpr
Definition at line 170 of file VehicleCameraControl.h.
kParameterranges
constexpr const char* VehicleCameraControl::kParameterranges = "parameterranges" static constexpr
Definition at line 171 of file VehicleCameraControl.h.
kParameters
constexpr const char* VehicleCameraControl::kParameters = "parameters" static constexpr
Definition at line 172 of file VehicleCameraControl.h.
kPhotoLapse
constexpr const char* VehicleCameraControl::kPhotoLapse = "PhotoLapse" static constexpr
Definition at line 189 of file VehicleCameraControl.h.
Referenced by setPhotoLapse(), and VehicleCameraControl().
kPhotoLapseCount
constexpr const char* VehicleCameraControl::kPhotoLapseCount = "PhotoLapseCount" static constexpr
Definition at line 190 of file VehicleCameraControl.h.
Referenced by setPhotoLapseCount(), and VehicleCameraControl().
kPhotoMode
constexpr const char* VehicleCameraControl::kPhotoMode = "PhotoCaptureMode" static constexpr
Definition at line 188 of file VehicleCameraControl.h.
Referenced by setPhotoCaptureMode(), and VehicleCameraControl().
kReadOnly
constexpr const char* VehicleCameraControl::kReadOnly = "readonly" static constexpr
Definition at line 173 of file VehicleCameraControl.h.
kRoption
constexpr const char* VehicleCameraControl::kRoption = "roption" static constexpr
Definition at line 175 of file VehicleCameraControl.h.
kStep
constexpr const char* VehicleCameraControl::kStep = "step" static constexpr
Definition at line 176 of file VehicleCameraControl.h.
kStrings
constexpr const char* VehicleCameraControl::kStrings = "strings" static constexpr
Definition at line 178 of file VehicleCameraControl.h.
kThermalMode
constexpr const char* VehicleCameraControl::kThermalMode = "ThermalMode" static constexpr
Definition at line 192 of file VehicleCameraControl.h.
Referenced by setThermalMode(), and VehicleCameraControl().
kThermalOpacity
constexpr const char* VehicleCameraControl::kThermalOpacity = "ThermalOpacity" static constexpr
Definition at line 191 of file VehicleCameraControl.h.
Referenced by setThermalOpacity(), and VehicleCameraControl().
kTranslated
constexpr const char* VehicleCameraControl::kTranslated = "translated" static constexpr
Definition at line 179 of file VehicleCameraControl.h.
kType
constexpr const char* VehicleCameraControl::kType = "type" static constexpr
Definition at line 180 of file VehicleCameraControl.h.
kUnit
constexpr const char* VehicleCameraControl::kUnit = "unit" static constexpr
Definition at line 181 of file VehicleCameraControl.h.
kUpdate
constexpr const char* VehicleCameraControl::kUpdate = "update" static constexpr
Definition at line 182 of file VehicleCameraControl.h.
kUpdates
constexpr const char* VehicleCameraControl::kUpdates = "updates" static constexpr
Definition at line 183 of file VehicleCameraControl.h.
kValue
constexpr const char* VehicleCameraControl::kValue = "value" static constexpr
Definition at line 184 of file VehicleCameraControl.h.
kVendor
constexpr const char* VehicleCameraControl::kVendor = "vendor" static constexpr
Definition at line 185 of file VehicleCameraControl.h.
kVersion
constexpr const char* VehicleCameraControl::kVersion = "version" static constexpr
Definition at line 186 of file VehicleCameraControl.h.
kWriteOnly
constexpr const char* VehicleCameraControl::kWriteOnly = "writeonly" static constexpr
Definition at line 174 of file VehicleCameraControl.h.
The documentation for this class was generated from the following files:
src/Camera/VehicleCameraControl.h
src/Camera/VehicleCameraControl.cc