QGroundControl: OsmParser Class Reference
OsmParser Class Reference
#include <OsmParser.h>
Signals
void buildingLevelHeightChanged ()
Signals inherited from Viewer3DMapProvider
void gpsRefChanged (QGeoCoordinate newGpsRef, bool isRefSet)
void mapChanged ()
Public Member Functions
OsmParser (QObject *parent=nullptr)
bool mapLoaded () const override
QGeoCoordinate gpsRef () const override
std::pair< QGeoCoordinate, QGeoCoordinate > mapBoundingBox () const override
float buildingLevelHeight () const
void setGpsRef (const QGeoCoordinate &gpsRef)
void resetGpsRef ()
void parseOsmFile (const QString &filePath)
QByteArray buildingToMesh ()
Public Member Functions inherited from Viewer3DMapProvider
Viewer3DMapProvider (QObject *parent=nullptr)
Friends
class OsmParserTest
Detailed Description
Definition at line 15 of file OsmParser.h.
Constructor & Destructor Documentation
OsmParser()
OsmParser::OsmParser (QObject * parent = nullptr) explicit
Definition at line 14 of file OsmParser.cc.
Member Function Documentation
buildingLevelHeight()
float OsmParser::buildingLevelHeight () const inline
Definition at line 30 of file OsmParser.h.
buildingLevelHeightChanged
void OsmParser::buildingLevelHeightChanged () signal
buildingToMesh()
QByteArray OsmParser::buildingToMesh ()
Definition at line 68 of file OsmParser.cc.
References OsmParserThread::mapBuildings().
gpsRef()
QGeoCoordinate OsmParser::gpsRef () const inline override virtual
Implements Viewer3DMapProvider.
Definition at line 27 of file OsmParser.h.
Referenced by setGpsRef().
mapBoundingBox()
std::pair< QGeoCoordinate, QGeoCoordinate > OsmParser::mapBoundingBox () const inline override virtual
Implements Viewer3DMapProvider.
Definition at line 28 of file OsmParser.h.
mapLoaded()
bool OsmParser::mapLoaded () const inline override virtual
Implements Viewer3DMapProvider.
Definition at line 26 of file OsmParser.h.
parseOsmFile()
void OsmParser::parseOsmFile (const QString & filePath)
Definition at line 59 of file OsmParser.cc.
References resetGpsRef(), and OsmParserThread::start().
resetGpsRef()
void OsmParser::resetGpsRef ()
Definition at line 31 of file OsmParser.cc.
References Viewer3DMapProvider::gpsRefChanged().
Referenced by parseOsmFile().
setGpsRef()
void OsmParser::setGpsRef (const QGeoCoordinate & gpsRef)
Definition at line 24 of file OsmParser.cc.
References gpsRef(), and Viewer3DMapProvider::gpsRefChanged().
Friends And Related Symbol Documentation
OsmParserTest
friend class OsmParserTest friend
Definition at line 21 of file OsmParser.h.
The documentation for this class was generated from the following files:
src/Viewer3D/Providers/Osm/OsmParser.h
src/Viewer3D/Providers/Osm/OsmParser.cc