QGroundControl: QGCApplication Class Reference
QGCApplication Class Reference
#include <QGCApplication.h>
Public Slots
void showVehicleConfig ()
void qmlAttemptWindowClose ()
QLocale getCurrentLanguage () const
Get current language.
void showCriticalVehicleMessage (const QString &message)
Show non-modal vehicle message to the user.
void showAppMessage (const QString &message, const QString &title=QString())
Show modal application message to the user.
void showRebootAppMessage (const QString &message, const QString &title=QString())
QGCImageProvider * qgcImageProvider ()
Signals
void languageChanged (const QLocale &locale)
Public Member Functions
QGCApplication (int &argc, char *argv[], const QGCCommandLineParser::CommandLineParseResult &args)
~QGCApplication ()
bool runningUnitTests () const
bool simpleBootTest () const
bool bootTestPassed () const
bool logOutput () const
Returns true if Qt debug output should be logged to a file.
void reportMissingParameter (int componentId, const QString &name)
bool fakeMobile () const
void setLanguage ()
QQuickWindow * mainRootWindow ()
uint64_t msecsSinceBoot () const
QString numberToString (quint64 number)
QString bigSizeToString (quint64 size)
QString bigSizeMBToString (quint64 size_MB)
void addCompressedSignal (const QMetaMethod &method)
Registers the signal such that only the last duplicate signal added is left in the queue.
void removeCompressedSignal (const QMetaMethod &method)
bool event (QEvent *e) final
void init ()
Perform initialize which is common to both normal application running and unit tests.
void shutdown ()
QQmlApplicationEngine * qmlAppEngine () const
Although public, these methods are internal and should only be called by UnitTest code.
Static Public Member Functions
static QString cachedParameterMetaDataFile ()
static QString cachedAirframeMetaDataFile ()
Friends
class UnitTest
Unit Test have access to creating and destroying singletons.
Detailed Description
The main application and management class. Needs QApplication base to support QtCharts module. TODO: Use QtGraphs to convert to QGuiApplication
Definition at line 41 of file QGCApplication.h.
Constructor & Destructor Documentation
QGCApplication()
QGCApplication::QGCApplication (int & argc, char * argv[], const QGCCommandLineParser::CommandLineParseResult & args)
Definition at line 52 of file QGCApplication.cc.
References AppSettings::clearSettingsNextBootKey, QGCNetworkHelper::initializeProxySupport(), and ParameterManager::parameterCacheDir().
~QGCApplication()
QGCApplication::~QGCApplication ()
Definition at line 215 of file QGCApplication.cc.
Member Function Documentation
addCompressedSignal()
void QGCApplication::addCompressedSignal (const QMetaMethod & method)
Registers the signal such that only the last duplicate signal added is left in the queue.
Definition at line 669 of file QGCApplication.cc.
bigSizeMBToString()
QString QGCApplication::bigSizeMBToString (quint64 size_MB)
Definition at line 820 of file QGCApplication.cc.
References getCurrentLanguage().
bigSizeToString()
QString QGCApplication::bigSizeToString (quint64 size)
Definition at line 802 of file QGCApplication.cc.
References getCurrentLanguage().
bootTestPassed()
bool QGCApplication::bootTestPassed () const inline
Definition at line 53 of file QGCApplication.h.
Referenced by main().
cachedAirframeMetaDataFile()
QString QGCApplication::cachedAirframeMetaDataFile () static
Definition at line 615 of file QGCApplication.cc.
cachedParameterMetaDataFile()
QString QGCApplication::cachedParameterMetaDataFile () static
Definition at line 608 of file QGCApplication.cc.
event()
QT_WARNING_POP bool QGCApplication::event (QEvent * e) final
Definition at line 721 of file QGCApplication.cc.
fakeMobile()
bool QGCApplication::fakeMobile () const inline
Returns
true: Fake ui into showing mobile interface
Definition at line 63 of file QGCApplication.h.
getCurrentLanguage
QLocale QGCApplication::getCurrentLanguage () const inline slot
Get current language.
Definition at line 99 of file QGCApplication.h.
Referenced by bigSizeMBToString(), bigSizeToString(), and numberToString().
init()
void QGCApplication::init ()
Perform initialize which is common to both normal application running and unit tests.
Definition at line 220 of file QGCApplication.cc.
References MavlinkSettings::gcsMavlinkSystemID(), Fact::rawValueChanged(), and AppSettings::savePathsChanged().
Referenced by main().
languageChanged
void QGCApplication::languageChanged (const QLocale & locale) signal
Referenced by QGeoTiledMappingManagerEngineQGC::QGeoTiledMappingManagerEngineQGC(), and setLanguage().
logOutput()
bool QGCApplication::logOutput () const inline
Returns true if Qt debug output should be logged to a file.
Definition at line 56 of file QGCApplication.h.
mainRootWindow()
QQuickWindow * QGCApplication::mainRootWindow ()
Definition at line 524 of file QGCApplication.cc.
msecsSinceBoot()
uint64_t QGCApplication::msecsSinceBoot () const inline
Definition at line 67 of file QGCApplication.h.
numberToString()
QString QGCApplication::numberToString (quint64 number)
Definition at line 797 of file QGCApplication.cc.
References getCurrentLanguage().
qgcImageProvider
QGCImageProvider * QGCApplication::qgcImageProvider () slot
Definition at line 746 of file QGCApplication.cc.
qmlAppEngine()
QQmlApplicationEngine * QGCApplication::qmlAppEngine () const inline
Although public, these methods are internal and should only be called by UnitTest code.
Definition at line 88 of file QGCApplication.h.
qmlAttemptWindowClose
void QGCApplication::qmlAttemptWindowClose () slot
Definition at line 540 of file QGCApplication.cc.
removeCompressedSignal()
void QGCApplication::removeCompressedSignal (const QMetaMethod & method)
Definition at line 674 of file QGCApplication.cc.
reportMissingParameter()
void QGCApplication::reportMissingParameter (int componentId, const QString & name)
Used to report a missing Parameter. Warning will be displayed to user. Method may be called multiple times.
Definition at line 416 of file QGCApplication.cc.
runningUnitTests()
bool QGCApplication::runningUnitTests () const inline
Definition at line 51 of file QGCApplication.h.
Referenced by showAppMessage(), and showCriticalVehicleMessage().
setLanguage()
void QGCApplication::setLanguage ()
Definition at line 166 of file QGCApplication.cc.
References languageChanged(), and JsonHelper::translator().
showAppMessage
void QGCApplication::showAppMessage (const QString & message, const QString & title = QString()) slot
Show modal application message to the user.
Definition at line 476 of file QGCApplication.cc.
References runningUnitTests().
Referenced by showRebootAppMessage().
showCriticalVehicleMessage
void QGCApplication::showCriticalVehicleMessage (const QString & message) slot
Show non-modal vehicle message to the user.
Definition at line 456 of file QGCApplication.cc.
References runningUnitTests().
showRebootAppMessage
void QGCApplication::showRebootAppMessage (const QString & message, const QString & title = QString()) slot
Show modal application message to the user about the need for a reboot. Multiple messages will be supressed if they occur one after the other.
Definition at line 496 of file QGCApplication.cc.
References showAppMessage().
showVehicleConfig
void QGCApplication::showVehicleConfig () slot
Definition at line 533 of file QGCApplication.cc.
shutdown()
void QGCApplication::shutdown ()
Definition at line 751 of file QGCApplication.cc.
References VideoManager::cleanup(), VideoManager::instance(), and ParameterManager::parameterCacheDir().
Referenced by main().
simpleBootTest()
bool QGCApplication::simpleBootTest () const inline
Definition at line 52 of file QGCApplication.h.
Friends And Related Symbol Documentation
UnitTest
friend class UnitTest friend
Unit Test have access to creating and destroying singletons.
Definition at line 46 of file QGCApplication.h.
The documentation for this class was generated from the following files:
src/QGCApplication.h
src/QGCApplication.cc