QGroundControl: BluetoothLink Class Reference
BluetoothLink Class Reference
#include <BluetoothLink.h>
Public Member Functions
BluetoothLink (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
~BluetoothLink () override
bool isConnected () const override
void disconnect () override
Public Member Functions inherited from LinkInterface
virtual ~LinkInterface ()
virtual bool isLogReplay () const
virtual bool isSecureConnection () const
Returns true if the connection is secure (e.g. USB, wired ethernet)
SharedLinkConfigurationPtr linkConfiguration ()
const SharedLinkConfigurationPtr linkConfiguration () const
uint8_t mavlinkChannel () const
bool mavlinkChannelIsSet () const
bool decodedFirstMavlinkPacket () const
void setDecodedFirstMavlinkPacket (bool decodedFirstMavlinkPacket)
void writeBytesThreadSafe (const char *bytes, int length)
void addVehicleReference ()
void removeVehicleReference ()
bool initMavlinkSigning ()
void setSigningSignatureFailure (bool failure)
void reportMavlinkV1Traffic ()
Additional Inherited Members
Signals inherited from LinkInterface
void bytesReceived (LinkInterface *link, const QByteArray &data)
void bytesSent (LinkInterface *link, const QByteArray &data)
void connected ()
void disconnected ()
void communicationError (const QString &title, const QString &error)
Protected Member Functions inherited from LinkInterface
LinkInterface (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
Links are only created by LinkManager so constructor is not public.
virtual bool _allocateMavlinkChannel ()
virtual void _freeMavlinkChannel ()
void _connectionRemoved ()
Protected Attributes inherited from LinkInterface
SharedLinkConfigurationPtr _config
Detailed Description
Definition at line 13 of file BluetoothLink.h.
Constructor & Destructor Documentation
BluetoothLink()
BluetoothLink::BluetoothLink (SharedLinkConfigurationPtr & config, QObject * parent = nullptr) explicit
Definition at line 13 of file BluetoothLink.cc.
References BluetoothWorker::connected(), BluetoothWorker::create(), BluetoothWorker::dataReceived(), BluetoothWorker::dataSent(), BluetoothWorker::disconnected(), BluetoothConfiguration::errorOccurred(), BluetoothWorker::errorOccurred(), BluetoothWorker::rssiUpdated(), and BluetoothWorker::setupConnection().
~BluetoothLink()
BluetoothLink::~BluetoothLink () override
Definition at line 49 of file BluetoothLink.cc.
Member Function Documentation
disconnect()
void BluetoothLink::disconnect () override virtual
Implements LinkInterface.
Definition at line 83 of file BluetoothLink.cc.
isConnected()
bool BluetoothLink::isConnected () const override virtual
Implements LinkInterface.
Definition at line 67 of file BluetoothLink.cc.
The documentation for this class was generated from the following files:
src/Comms/Bluetooth/BluetoothLink.h
src/Comms/Bluetooth/BluetoothLink.cc