QGroundControl: APMSafetyComponent Class Reference
APMSafetyComponent Class Reference
#include <APMSafetyComponent.h>
Public Member Functions
APMSafetyComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
QStringList setupCompleteChangedTriggerList () const final
QString name () const final
QString description () const final
QString vehicleConfigJson () const final
Resource path to a VehicleConfig.json page definition, or empty if none.
QString iconResource () const final
bool requiresSetup () const final
bool setupComplete () const final
QUrl setupSource () const final
QUrl summaryQmlSource () const final
bool allowSetupWhileArmed () const final
bool allowSetupWhileFlying () const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file APMSafetyComponent.h.
Constructor & Destructor Documentation
APMSafetyComponent()
APMSafetyComponent::APMSafetyComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr) explicit
Definition at line 5 of file APMSafetyComponent.cc.
Member Function Documentation
allowSetupWhileArmed()
bool APMSafetyComponent::allowSetupWhileArmed (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 22 of file APMSafetyComponent.h.
allowSetupWhileFlying()
bool APMSafetyComponent::allowSetupWhileFlying (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 23 of file APMSafetyComponent.h.
description()
QString APMSafetyComponent::description (void) const final virtual
Reimplemented from VehicleComponent.
Definition at line 16 of file APMSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
iconResource()
QString APMSafetyComponent::iconResource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 17 of file APMSafetyComponent.h.
name()
QString APMSafetyComponent::name (void) const inline final virtual
Implements VehicleComponent.
Definition at line 14 of file APMSafetyComponent.h.
requiresSetup()
bool APMSafetyComponent::requiresSetup (void) const inline final virtual
Implements VehicleComponent.
Definition at line 18 of file APMSafetyComponent.h.
setupComplete()
bool APMSafetyComponent::setupComplete (void) const inline final virtual
Implements VehicleComponent.
Definition at line 19 of file APMSafetyComponent.h.
setupCompleteChangedTriggerList()
QStringList APMSafetyComponent::setupCompleteChangedTriggerList () const inline final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 12 of file APMSafetyComponent.h.
setupSource()
QUrl APMSafetyComponent::setupSource (void) const final virtual
Implements VehicleComponent.
Definition at line 30 of file APMSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
summaryQmlSource()
QUrl APMSafetyComponent::summaryQmlSource (void) const final virtual
Implements VehicleComponent.
Definition at line 49 of file APMSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
vehicleConfigJson()
QString APMSafetyComponent::vehicleConfigJson (void) const final virtual
Resource path to a VehicleConfig.json page definition, or empty if none.
Reimplemented from VehicleComponent.
Definition at line 11 of file APMSafetyComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMSafetyComponent.h
src/AutoPilotPlugins/APM/APMSafetyComponent.cc