QGroundControl: QGCGeoBoundingCube Class Reference
QGCGeoBoundingCube Class Reference
#include <QGCGeoBoundingCube.h>
Public Member Functions
QGCGeoBoundingCube (QObject *parent=nullptr)
QGCGeoBoundingCube (const QGCGeoBoundingCube &other)
QGCGeoBoundingCube (QGeoCoordinate p1, QGeoCoordinate p2)
QGeoCoordinate pointNW MEMBER pointNW CONSTANT (QGeoCoordinate pointSE MEMBER pointSE CONSTANT) 1 void reset()
bool isValid () const
QGeoCoordinate center () const
bool operator== (const QGCGeoBoundingCube &other) const
bool operator== (const QList< QGeoCoordinate > &coords) const
bool operator!= (const QGCGeoBoundingCube &other)
const QGCGeoBoundingCube & operator= (const QGCGeoBoundingCube &other)
QList< QGeoCoordinate > polygon2D (double clipTo=0.0) const
double width () const
double height () const
double area () const
double radius () const
Public Attributes
QGeoCoordinate pointNW
QGeoCoordinate pointSE
Static Public Attributes
static double MaxAlt = 1000000.0
static double MinAlt = -1000000.0
static double MaxNorth = 90.0
static double MaxSouth = -90.0
static double MaxWest = -180.0
static double MaxEast = 180.0
Detailed Description
Definition at line 9 of file QGCGeoBoundingCube.h.
Constructor & Destructor Documentation
QGCGeoBoundingCube() [1/3]
QGCGeoBoundingCube::QGCGeoBoundingCube (QObject * parent = nullptr)
Definition at line 13 of file QGCGeoBoundingCube.cc.
QGCGeoBoundingCube() [2/3]
QGCGeoBoundingCube::QGCGeoBoundingCube (const QGCGeoBoundingCube & other) inline
Definition at line 17 of file QGCGeoBoundingCube.h.
References pointNW, and pointSE.
QGCGeoBoundingCube() [3/3]
QGCGeoBoundingCube::QGCGeoBoundingCube (QGeoCoordinate p1, QGeoCoordinate p2) inline
Definition at line 24 of file QGCGeoBoundingCube.h.
Member Function Documentation
area()
double QGCGeoBoundingCube::area () const
Definition at line 112 of file QGCGeoBoundingCube.cc.
References height(), isValid(), and width().
Referenced by polygon2D().
center()
QGeoCoordinate QGCGeoBoundingCube::center () const
Definition at line 37 of file QGCGeoBoundingCube.cc.
References isValid(), pointNW, and pointSE.
Referenced by polygon2D().
CONSTANT()
QGeoCoordinate pointNW MEMBER pointNW QGCGeoBoundingCube::CONSTANT (QGeoCoordinate pointSE MEMBER pointSE CONSTANT)
height()
double QGCGeoBoundingCube::height () const
Definition at line 102 of file QGCGeoBoundingCube.cc.
References isValid(), pointNW, and pointSE.
Referenced by area().
isValid()
bool QGCGeoBoundingCube::isValid () const
Definition at line 21 of file QGCGeoBoundingCube.cc.
References MaxAlt, MaxEast, MaxNorth, MaxSouth, MaxWest, MinAlt, pointNW, and pointSE.
Referenced by area(), center(), height(), polygon2D(), radius(), and width().
operator!=()
bool QGCGeoBoundingCube::operator!= (const QGCGeoBoundingCube & other) inline
Definition at line 44 of file QGCGeoBoundingCube.h.
operator=()
const QGCGeoBoundingCube & QGCGeoBoundingCube::operator= (const QGCGeoBoundingCube & other) inline
Definition at line 49 of file QGCGeoBoundingCube.h.
References pointNW, and pointSE.
operator==() [1/2]
bool QGCGeoBoundingCube::operator== (const QGCGeoBoundingCube & other) const inline
Definition at line 37 of file QGCGeoBoundingCube.h.
References pointNW, and pointSE.
operator==() [2/2]
bool QGCGeoBoundingCube::operator== (const QList< QGeoCoordinate > & coords) const
Definition at line 80 of file QGCGeoBoundingCube.cc.
References polygon2D().
polygon2D()
QList< QGeoCoordinate > QGCGeoBoundingCube::polygon2D (double clipTo = 0.0) const
Definition at line 49 of file QGCGeoBoundingCube.cc.
References area(), center(), isValid(), pointNW, and pointSE.
Referenced by operator==().
radius()
double QGCGeoBoundingCube::radius () const
Definition at line 123 of file QGCGeoBoundingCube.cc.
References isValid(), pointNW, and pointSE.
width()
double QGCGeoBoundingCube::width () const
Definition at line 92 of file QGCGeoBoundingCube.cc.
References isValid(), pointNW, and pointSE.
Referenced by area().
Member Data Documentation
MaxAlt
double QGCGeoBoundingCube::MaxAlt = 1000000.0 static
Definition at line 66 of file QGCGeoBoundingCube.h.
Referenced by isValid().
MaxEast
double QGCGeoBoundingCube::MaxEast = 180.0 static
Definition at line 71 of file QGCGeoBoundingCube.h.
Referenced by isValid().
MaxNorth
double QGCGeoBoundingCube::MaxNorth = 90.0 static
Definition at line 68 of file QGCGeoBoundingCube.h.
Referenced by isValid().
MaxSouth
double QGCGeoBoundingCube::MaxSouth = -90.0 static
Definition at line 69 of file QGCGeoBoundingCube.h.
Referenced by isValid().
MaxWest
double QGCGeoBoundingCube::MaxWest = -180.0 static
Definition at line 70 of file QGCGeoBoundingCube.h.
Referenced by isValid().
MinAlt
double QGCGeoBoundingCube::MinAlt = -1000000.0 static
Definition at line 67 of file QGCGeoBoundingCube.h.
Referenced by isValid().
pointNW
QGeoCoordinate QGCGeoBoundingCube::pointNW
Definition at line 64 of file QGCGeoBoundingCube.h.
Referenced by center(), height(), isValid(), operator=(), operator==(), polygon2D(), QGCGeoBoundingCube(), radius(), and width().
pointSE
QGeoCoordinate QGCGeoBoundingCube::pointSE
Definition at line 65 of file QGCGeoBoundingCube.h.
Referenced by center(), height(), isValid(), operator=(), operator==(), polygon2D(), QGCGeoBoundingCube(), radius(), and width().
The documentation for this class was generated from the following files:
src/QmlControls/QGCGeoBoundingCube.h
src/QmlControls/QGCGeoBoundingCube.cc