QGroundControl: FlyViewSettings Class Reference
FlyViewSettings Class Reference
#include <FlyViewSettings.h>
Public Member Functions
FlyViewSettings (QObject *parent=nullptr)
Fact *guidedMinimumAltitude READ guidedMinimumAltitude CONSTANT Fact * guidedMinimumAltitude ()
Fact *guidedMaximumAltitude READ guidedMaximumAltitude CONSTANT Fact * guidedMaximumAltitude ()
Fact *showLogReplayStatusBar READ showLogReplayStatusBar CONSTANT Fact * showLogReplayStatusBar ()
Fact *showAdditionalIndicatorsCompass READ showAdditionalIndicatorsCompass CONSTANT Fact * showAdditionalIndicatorsCompass ()
Fact *lockNoseUpCompass READ lockNoseUpCompass CONSTANT Fact * lockNoseUpCompass ()
Fact *maxGoToLocationDistance READ maxGoToLocationDistance CONSTANT Fact * maxGoToLocationDistance ()
Fact *forwardFlightGoToLocationLoiterRad READ forwardFlightGoToLocationLoiterRad CONSTANT Fact * forwardFlightGoToLocationLoiterRad ()
Fact *goToLocationRequiresConfirmInGuided READ goToLocationRequiresConfirmInGuided CONSTANT Fact * goToLocationRequiresConfirmInGuided ()
Fact *keepMapCenteredOnVehicle READ keepMapCenteredOnVehicle CONSTANT Fact * keepMapCenteredOnVehicle ()
Fact *showSimpleCameraControl READ showSimpleCameraControl CONSTANT Fact * showSimpleCameraControl ()
Fact *showObstacleDistanceOverlay READ showObstacleDistanceOverlay CONSTANT Fact * showObstacleDistanceOverlay ()
Fact *updateHomePosition READ updateHomePosition CONSTANT Fact * updateHomePosition ()
Fact *instrumentQmlFile2 READ instrumentQmlFile2 CONSTANT Fact * instrumentQmlFile2 ()
Fact *requestControlAllowTakeover READ requestControlAllowTakeover CONSTANT Fact * requestControlAllowTakeover ()
Fact *requestControlTimeout READ requestControlTimeout CONSTANT Fact * requestControlTimeout ()
Fact *enableAutomaticMissionPopups READ enableAutomaticMissionPopups CONSTANT Fact * enableAutomaticMissionPopups ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "FlyView"
static const char * settingsGroup = "FlyView"
static const char * guidedMinimumAltitudeName = "guidedMinimumAltitude"
static const char * guidedMaximumAltitudeName = "guidedMaximumAltitude"
static const char * showLogReplayStatusBarName = "showLogReplayStatusBar"
static const char * showAdditionalIndicatorsCompassName = "showAdditionalIndicatorsCompass"
static const char * lockNoseUpCompassName = "lockNoseUpCompass"
static const char * maxGoToLocationDistanceName = "maxGoToLocationDistance"
static const char * forwardFlightGoToLocationLoiterRadName = "forwardFlightGoToLocationLoiterRad"
static const char * goToLocationRequiresConfirmInGuidedName = "goToLocationRequiresConfirmInGuided"
static const char * keepMapCenteredOnVehicleName = "keepMapCenteredOnVehicle"
static const char * showSimpleCameraControlName = "showSimpleCameraControl"
static const char * showObstacleDistanceOverlayName = "showObstacleDistanceOverlay"
static const char * updateHomePositionName = "updateHomePosition"
static const char * instrumentQmlFile2Name = "instrumentQmlFile2"
static const char * requestControlAllowTakeoverName = "requestControlAllowTakeover"
static const char * requestControlTimeoutName = "requestControlTimeout"
static const char * enableAutomaticMissionPopupsName = "enableAutomaticMissionPopups"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file FlyViewSettings.h.
Constructor & Destructor Documentation
FlyViewSettings()
FlyViewSettings::FlyViewSettings (QObject * parent = nullptr)
Definition at line 3 of file FlyViewSettings.cc.
Member Function Documentation
enableAutomaticMissionPopups()
Fact * FlyViewSettings::enableAutomaticMissionPopups ()
Definition at line 22 of file FlyViewSettings.cc.
forwardFlightGoToLocationLoiterRad()
Fact * FlyViewSettings::forwardFlightGoToLocationLoiterRad ()
Definition at line 13 of file FlyViewSettings.cc.
goToLocationRequiresConfirmInGuided()
Fact * FlyViewSettings::goToLocationRequiresConfirmInGuided ()
Definition at line 14 of file FlyViewSettings.cc.
guidedMaximumAltitude()
Fact * FlyViewSettings::guidedMaximumAltitude ()
Definition at line 8 of file FlyViewSettings.cc.
guidedMinimumAltitude()
Fact * FlyViewSettings::guidedMinimumAltitude ()
Definition at line 7 of file FlyViewSettings.cc.
instrumentQmlFile2()
Fact * FlyViewSettings::instrumentQmlFile2 ()
Definition at line 19 of file FlyViewSettings.cc.
keepMapCenteredOnVehicle()
Fact * FlyViewSettings::keepMapCenteredOnVehicle ()
Definition at line 15 of file FlyViewSettings.cc.
lockNoseUpCompass()
Fact * FlyViewSettings::lockNoseUpCompass ()
Definition at line 11 of file FlyViewSettings.cc.
maxGoToLocationDistance()
Fact * FlyViewSettings::maxGoToLocationDistance ()
Definition at line 12 of file FlyViewSettings.cc.
Referenced by Vehicle::guidedModeGotoLocation().
requestControlAllowTakeover()
Fact * FlyViewSettings::requestControlAllowTakeover ()
Definition at line 20 of file FlyViewSettings.cc.
requestControlTimeout()
Fact * FlyViewSettings::requestControlTimeout ()
Definition at line 21 of file FlyViewSettings.cc.
Referenced by Vehicle::requestOperatorControl().
showAdditionalIndicatorsCompass()
Fact * FlyViewSettings::showAdditionalIndicatorsCompass ()
Definition at line 10 of file FlyViewSettings.cc.
showLogReplayStatusBar()
Fact * FlyViewSettings::showLogReplayStatusBar ()
Definition at line 9 of file FlyViewSettings.cc.
showObstacleDistanceOverlay()
Fact * FlyViewSettings::showObstacleDistanceOverlay ()
Definition at line 17 of file FlyViewSettings.cc.
showSimpleCameraControl()
Fact * FlyViewSettings::showSimpleCameraControl ()
Definition at line 16 of file FlyViewSettings.cc.
Referenced by SimulatedCameraControl::capturesPhotos(), and SimulatedCameraControl::SimulatedCameraControl().
updateHomePosition()
Fact * FlyViewSettings::updateHomePosition ()
Definition at line 18 of file FlyViewSettings.cc.
Member Data Documentation
enableAutomaticMissionPopupsName
const char * FlyViewSettings::enableAutomaticMissionPopupsName = "enableAutomaticMissionPopups" static
Definition at line 32 of file FlyViewSettings.h.
forwardFlightGoToLocationLoiterRadName
const char * FlyViewSettings::forwardFlightGoToLocationLoiterRadName = "forwardFlightGoToLocationLoiterRad" static
Definition at line 23 of file FlyViewSettings.h.
goToLocationRequiresConfirmInGuidedName
const char * FlyViewSettings::goToLocationRequiresConfirmInGuidedName = "goToLocationRequiresConfirmInGuided" static
Definition at line 24 of file FlyViewSettings.h.
guidedMaximumAltitudeName
const char * FlyViewSettings::guidedMaximumAltitudeName = "guidedMaximumAltitude" static
Definition at line 18 of file FlyViewSettings.h.
guidedMinimumAltitudeName
const char * FlyViewSettings::guidedMinimumAltitudeName = "guidedMinimumAltitude" static
Definition at line 17 of file FlyViewSettings.h.
instrumentQmlFile2Name
const char * FlyViewSettings::instrumentQmlFile2Name = "instrumentQmlFile2" static
Definition at line 29 of file FlyViewSettings.h.
keepMapCenteredOnVehicleName
const char * FlyViewSettings::keepMapCenteredOnVehicleName = "keepMapCenteredOnVehicle" static
Definition at line 25 of file FlyViewSettings.h.
lockNoseUpCompassName
const char * FlyViewSettings::lockNoseUpCompassName = "lockNoseUpCompass" static
Definition at line 21 of file FlyViewSettings.h.
maxGoToLocationDistanceName
const char * FlyViewSettings::maxGoToLocationDistanceName = "maxGoToLocationDistance" static
Definition at line 22 of file FlyViewSettings.h.
name
const char * FlyViewSettings::name = "FlyView" static
Definition at line 15 of file FlyViewSettings.h.
requestControlAllowTakeoverName
const char * FlyViewSettings::requestControlAllowTakeoverName = "requestControlAllowTakeover" static
Definition at line 30 of file FlyViewSettings.h.
requestControlTimeoutName
const char * FlyViewSettings::requestControlTimeoutName = "requestControlTimeout" static
Definition at line 31 of file FlyViewSettings.h.
settingsGroup
const char * FlyViewSettings::settingsGroup = "FlyView" static
Definition at line 15 of file FlyViewSettings.h.
showAdditionalIndicatorsCompassName
const char * FlyViewSettings::showAdditionalIndicatorsCompassName = "showAdditionalIndicatorsCompass" static
Definition at line 20 of file FlyViewSettings.h.
showLogReplayStatusBarName
const char * FlyViewSettings::showLogReplayStatusBarName = "showLogReplayStatusBar" static
Definition at line 19 of file FlyViewSettings.h.
showObstacleDistanceOverlayName
const char * FlyViewSettings::showObstacleDistanceOverlayName = "showObstacleDistanceOverlay" static
Definition at line 27 of file FlyViewSettings.h.
showSimpleCameraControlName
const char * FlyViewSettings::showSimpleCameraControlName = "showSimpleCameraControl" static
Definition at line 26 of file FlyViewSettings.h.
updateHomePositionName
const char * FlyViewSettings::updateHomePositionName = "updateHomePosition" static
Definition at line 28 of file FlyViewSettings.h.
The documentation for this class was generated from the following files:
src/Settings/FlyViewSettings.h
src/Settings/FlyViewSettings.cc