QGroundControl: VisualMissionItem Class Reference
VisualMissionItem Class Reference abstract
#include <VisualMissionItem.h>
Public Types
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Signals
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool dirty (void) const =0
virtual bool isSimpleItem (void) const =0
virtual bool isTakeoffItem (void) const
virtual bool isLandCommand (void) const
virtual bool isSurveyItem (void) const
virtual bool isStandaloneCoordinate (void) const =0
virtual bool specifiesCoordinate (void) const =0
virtual bool specifiesAltitudeOnly (void) const =0
virtual QString commandDescription (void) const =0
virtual QString commandName (void) const =0
virtual QString abbreviation (void) const =0
virtual QGeoCoordinate coordinate (void) const =0
virtual QGeoCoordinate entryCoordinate (void) const =0
virtual QGeoCoordinate exitCoordinate (void) const =0
virtual double editableAlt (void) const =0
virtual double amslEntryAlt (void) const =0
virtual double amslExitAlt (void) const =0
virtual int sequenceNumber (void) const =0
virtual double specifiedFlightSpeed (void)=0
virtual double specifiedGimbalYaw (void)=0
virtual double specifiedGimbalPitch (void)=0
virtual double specifiedVehicleYaw (void)
virtual QGCGeoBoundingCube * boundingCube (void)
virtual void setMissionFlightStatus (MissionController::MissionFlightStatus_t &missionFlightStatus)
virtual bool exitCoordinateSameAsEntry (void) const =0
virtual void setDirty (bool dirty)=0
virtual void setCoordinate (const QGeoCoordinate &coordinate)=0
virtual void setSequenceNumber (int sequenceNumber)=0
virtual int lastSequenceNumber (void) const =0
virtual ReadyForSaveState readyForSaveState (void) const
virtual void save (QJsonArray &missionItems)=0
virtual QString mapVisualQML (void) const =0
virtual void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent)=0
virtual void applyNewAltitude (double newAltitude)=0
Adjust the altitude of the item if appropriate to the new altitude.
virtual double additionalTimeDelay (void) const =0
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Static Public Attributes
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Slots
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Detailed Description
Definition at line 19 of file VisualMissionItem.h.
Member Enumeration Documentation
ReadyForSaveState
enum VisualMissionItem::ReadyForSaveState
Enumerator
ReadyForSave
NotReadyForSaveTerrain
NotReadyForSaveData
Definition at line 34 of file VisualMissionItem.h.
Constructor & Destructor Documentation
VisualMissionItem() [1/2]
VisualMissionItem::VisualMissionItem (PlanMasterController * masterController, bool flyView)
Definition at line 9 of file VisualMissionItem.cc.
VisualMissionItem() [2/2]
VisualMissionItem::VisualMissionItem (const VisualMissionItem & other, bool flyView)
Definition at line 19 of file VisualMissionItem.cc.
~VisualMissionItem()
VisualMissionItem::~VisualMissionItem ()
Definition at line 62 of file VisualMissionItem.cc.
Member Function Documentation
_amslEntryAltChanged
void VisualMissionItem::_amslEntryAltChanged (void) protected slot
Definition at line 233 of file VisualMissionItem.cc.
References amslEntryAlt(), and amslEntryAltChanged().
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), ComplexMissionItem::ComplexMissionItem(), MissionSettingsItem::MissionSettingsItem(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
_amslExitAltChanged
void VisualMissionItem::_amslExitAltChanged (void) protected slot
Definition at line 238 of file VisualMissionItem.cc.
References amslExitAlt(), and amslExitAltChanged().
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), ComplexMissionItem::ComplexMissionItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
_setBoundingCube()
void VisualMissionItem::_setBoundingCube (QGCGeoBoundingCube bc) protected
Definition at line 209 of file VisualMissionItem.cc.
References _boundingCube, and boundingCubeChanged().
Referenced by TransectStyleComplexItem::_rebuildTransects().
abbreviation()
virtual QString VisualMissionItem::abbreviation (void) const pure virtual
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
abbreviationChanged
void VisualMissionItem::abbreviationChanged (void) signal
Referenced by SimpleMissionItem::setSequenceNumber().
additionalTimeDelay()
virtual double VisualMissionItem::additionalTimeDelay (void) const pure virtual
Returns
Amount of additional time delay in seconds needed to fly this item
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and SurveyComplexItem.
Referenced by MissionFlightStatusCalculator::recalc().
additionalTimeDelayChanged
void VisualMissionItem::additionalTimeDelayChanged (void) signal
Referenced by TransectStyleComplexItem::_rebuildTransects().
altDifference()
double VisualMissionItem::altDifference (void) const inline
Definition at line 95 of file VisualMissionItem.h.
References _altDifference.
Referenced by setAltDifference().
altDifferenceChanged
void VisualMissionItem::altDifferenceChanged (double altDifference) signal
Referenced by setAltDifference().
altPercent()
double VisualMissionItem::altPercent (void) const inline
Definition at line 96 of file VisualMissionItem.h.
References _altPercent.
Referenced by setAltPercent().
altPercentChanged
void VisualMissionItem::altPercentChanged (double altPercent) signal
Referenced by setAltPercent().
amslEntryAlt()
virtual double VisualMissionItem::amslEntryAlt (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by _amslEntryAltChanged(), MissionFlightStatusCalculator::calcPrevWaypointValues(), and MissionFlightStatusCalculator::recalc().
amslEntryAltChanged
void VisualMissionItem::amslEntryAltChanged (double alt) signal
Referenced by _amslEntryAltChanged(), LandingComplexItem::_init(), MissionSettingsItem::MissionSettingsItem(), and StructureScanComplexItem::StructureScanComplexItem().
amslExitAlt()
virtual double VisualMissionItem::amslExitAlt (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by _amslExitAltChanged(), and MissionFlightStatusCalculator::calcPrevWaypointValues().
amslExitAltChanged
void VisualMissionItem::amslExitAltChanged (double alt) signal
Referenced by _amslExitAltChanged(), LandingComplexItem::_init(), MissionSettingsItem::MissionSettingsItem(), and StructureScanComplexItem::StructureScanComplexItem().
appendMissionItems()
virtual void VisualMissionItem::appendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) pure virtual
Returns the mission items associated with the complex item. Caller is responsible for freeing.
Parameters
items List to append to
missionItemParent Parent object for newly created MissionItems
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
applyNewAltitude()
virtual void VisualMissionItem::applyNewAltitude (double newAltitude) pure virtual
Adjust the altitude of the item if appropriate to the new altitude.
Implemented in LandingComplexItem, SimpleMissionItem, StructureScanComplexItem, TransectStyleComplexItem, and MissionSettingsItem.
Referenced by MissionController::applyDefaultMissionAltitude(), and MissionController::offsetMission().
azimuth()
double VisualMissionItem::azimuth (void) const inline
Definition at line 99 of file VisualMissionItem.h.
References _azimuth.
Referenced by setAzimuth().
azimuthChanged
void VisualMissionItem::azimuthChanged (double azimuth) signal
Referenced by setAzimuth().
boundingCube()
virtual QGCGeoBoundingCube * VisualMissionItem::boundingCube (void) inline virtual
Definition at line 158 of file VisualMissionItem.h.
References _boundingCube.
boundingCubeChanged
void VisualMissionItem::boundingCubeChanged (void) signal
Referenced by _setBoundingCube().
childItems()
QmlObjectListModel * VisualMissionItem::childItems (void) inline
Definition at line 110 of file VisualMissionItem.h.
References _childItems.
clearSimpleFlighPathSegment()
void VisualMissionItem::clearSimpleFlighPathSegment (void) inline
Definition at line 128 of file VisualMissionItem.h.
References _simpleFlightPathSegment.
commandDescription()
virtual QString VisualMissionItem::commandDescription (void) const pure virtual
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
commandDescriptionChanged
void VisualMissionItem::commandDescriptionChanged (void) signal
commandName()
virtual QString VisualMissionItem::commandName (void) const pure virtual
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
commandNameChanged
void VisualMissionItem::commandNameChanged (void) signal
CONSTANT()
bool homePosition READ homePosition VisualMissionItem::CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) const inline
< true: This item is being used as a home position indicator
< The altitude of terrain at the coordinate position, NaN if not known < true: Last terrain query failed < Does not include altitude < Does not include altitude < true: entryCoordinate and exitCoordinate are the same value < Item is dirty and requires save/send < true: On of this items children is current < true: Item is associated with a coordinate position < true: Waypoint line does not go through item < true: Item has altitude only, no full coordinate < Simple or Complex MissionItem < true: Takeoff item special case < true: Survey item special case for editing center position through mission item list menue < Qml code for editing this item < QMl code for map visuals < NaN for not specified < NaN for not specified < NaN for not specified < NaN for not specified < Current gimbal yaw state at this point in mission < Expected vehicle yaw at this point in mission < Current VTOL mode (VehicleClass_t) prior to executing this item < Change in altitude from previous waypoint < Percent of total altitude change in mission altitude < Percent of terrain altitude in mission altitude < true: Item collides with terrain < Azimuth to previous waypoint < Distance to previous waypoint < Flight path cumalative horizontal distance from home point to this item
Parameters
coordinateChanged Does not include altitude
Definition at line 41 of file VisualMissionItem.h.
References _homePositionSpecialCase.
coordinate()
virtual QGeoCoordinate VisualMissionItem::coordinate (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::offsetMission(), MissionController::repositionMission(), and MissionController::rotateMission().
coordinateChanged
void VisualMissionItem::coordinateChanged (const QGeoCoordinate & coordinate) signal
Referenced by LandingComplexItem::_init(), MissionSettingsItem::MissionSettingsItem(), StructureScanComplexItem::rotateEntryPoint(), MissionSettingsItem::setCoordinate(), SimpleMissionItem::SimpleMissionItem(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
currentVTOLModeChanged
void VisualMissionItem::currentVTOLModeChanged (void) signal
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
dirty()
virtual bool VisualMissionItem::dirty (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, TransectStyleComplexItem, and SimpleMissionItem.
dirtyChanged
void VisualMissionItem::dirtyChanged (bool dirty) signal
Referenced by LandingComplexItem::setDirty(), MissionSettingsItem::setDirty(), SimpleMissionItem::setDirty(), StructureScanComplexItem::setDirty(), and TransectStyleComplexItem::setDirty().
distance()
double VisualMissionItem::distance (void) const inline
Definition at line 100 of file VisualMissionItem.h.
References _distance.
Referenced by LandingComplexItem::_recalcFromCoordinateChange(), LandingComplexItem::_recalcFromHeadingAndDistanceChange(), StructureScanComplexItem::greatestDistanceTo(), TransectStyleComplexItem::greatestDistanceTo(), and setDistance().
distanceChanged
void VisualMissionItem::distanceChanged (double distance) signal
Referenced by setDistance().
distanceFromStart()
double VisualMissionItem::distanceFromStart (void) const inline
Definition at line 101 of file VisualMissionItem.h.
References _distanceFromStart.
Referenced by setDistanceFromStart().
distanceFromStartChanged
void VisualMissionItem::distanceFromStartChanged (double distanceFromStart) signal
Referenced by setDistanceFromStart().
editableAlt()
virtual double VisualMissionItem::editableAlt (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::offsetMission().
entryCoordinate()
virtual QGeoCoordinate VisualMissionItem::entryCoordinate (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::calcDistanceToHome(), and MissionFlightStatusCalculator::calcPrevWaypointValues().
entryCoordinateChanged
void VisualMissionItem::entryCoordinateChanged (const QGeoCoordinate & entryCoordinate) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_updateCoordinateAltitudes(), MissionSettingsItem::MissionSettingsItem(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
exitCoordinate()
virtual QGeoCoordinate VisualMissionItem::exitCoordinate (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::calcDistanceToHome(), MissionFlightStatusCalculator::calcPrevWaypointValues(), and MissionFlightStatusCalculator::recalc().
exitCoordinateChanged
void VisualMissionItem::exitCoordinateChanged (const QGeoCoordinate & exitCoordinate) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_updateCoordinateAltitudes(), MissionSettingsItem::MissionSettingsItem(), and StructureScanComplexItem::StructureScanComplexItem().
exitCoordinateSameAsEntry()
virtual bool VisualMissionItem::exitCoordinateSameAsEntry (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
exitCoordinateSameAsEntryChanged
void VisualMissionItem::exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry) signal
flyView()
bool VisualMissionItem::flyView (void) const inline
Definition at line 106 of file VisualMissionItem.h.
References _flyView.
Referenced by LandingComplexItem::_scanForItem(), LandingComplexItem::_scanForItems(), FixedWingLandingComplexItem::scanForItems(), and VTOLLandingComplexItem::scanForItems().
hasCurrentChildItem()
bool VisualMissionItem::hasCurrentChildItem (void) const inline
Definition at line 103 of file VisualMissionItem.h.
References _hasCurrentChildItem.
Referenced by setHasCurrentChildItem().
hasCurrentChildItemChanged
void VisualMissionItem::hasCurrentChildItemChanged (bool hasCurrentChildItem) signal
Referenced by setHasCurrentChildItem().
isCurrentItem()
bool VisualMissionItem::isCurrentItem (void) const inline
Definition at line 102 of file VisualMissionItem.h.
References _isCurrentItem.
Referenced by setIsCurrentItem().
isCurrentItemChanged
void VisualMissionItem::isCurrentItemChanged (bool isCurrentItem) signal
Referenced by setIsCurrentItem().
isLandCommand()
virtual bool VisualMissionItem::isLandCommand (void) const inline virtual
Reimplemented in LandingComplexItem, and SimpleMissionItem.
Definition at line 137 of file VisualMissionItem.h.
Referenced by MissionController::offsetMission(), MissionFlightStatusCalculator::recalc(), MissionController::repositionMission(), and MissionController::rotateMission().
isLandCommandChanged
void VisualMissionItem::isLandCommandChanged (void) signal
isSimpleItem()
virtual bool VisualMissionItem::isSimpleItem (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
isSimpleItemChanged
void VisualMissionItem::isSimpleItemChanged (bool isSimpleItem) signal
isStandaloneCoordinate()
virtual bool VisualMissionItem::isStandaloneCoordinate (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::offsetMission(), MissionFlightStatusCalculator::recalc(), MissionController::repositionMission(), MissionController::rotateMission(), and MissionController::setCurrentPlanViewSeqNum().
isStandaloneCoordinateChanged
void VisualMissionItem::isStandaloneCoordinateChanged (void) signal
isSurveyItem()
virtual bool VisualMissionItem::isSurveyItem (void) const inline virtual
Reimplemented in SurveyComplexItem.
Definition at line 138 of file VisualMissionItem.h.
isTakeoffItem()
virtual bool VisualMissionItem::isTakeoffItem (void) const inline virtual
Reimplemented in TakeoffMissionItem.
Definition at line 136 of file VisualMissionItem.h.
Referenced by MissionController::offsetMission(), MissionController::repositionMission(), and MissionController::rotateMission().
isTakeoffItemChanged
void VisualMissionItem::isTakeoffItemChanged (bool isTakeoffItem) signal
lastSequenceNumber()
virtual int VisualMissionItem::lastSequenceNumber (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
lastSequenceNumberChanged
void VisualMissionItem::lastSequenceNumberChanged (int sequenceNumber) signal
Referenced by TransectStyleComplexItem::_rebuildTransects(), LandingComplexItem::setSequenceNumber(), MissionSettingsItem::setSequenceNumber(), StructureScanComplexItem::setSequenceNumber(), and TransectStyleComplexItem::setSequenceNumber().
mapVisualQML()
virtual QString VisualMissionItem::mapVisualQML (void) const pure virtual
Returns
The QML resource file which contains the control which visualizes the item on the map.
Implemented in CorridorScanComplexItem, FixedWingLandingComplexItem, MissionSettingsItem, StructureScanComplexItem, SurveyComplexItem, VTOLLandingComplexItem, SimpleMissionItem, TakeoffMissionItem, and TransectStyleComplexItem.
masterController()
PlanMasterController * VisualMissionItem::masterController (void) inline
Definition at line 130 of file VisualMissionItem.h.
References _masterController.
Referenced by LandingComplexItem::_scanForItem(), LandingComplexItem::_scanForItems(), FixedWingLandingComplexItem::scanForItems(), and VTOLLandingComplexItem::scanForItems().
missionGimbalYaw()
double VisualMissionItem::missionGimbalYaw (void) const inline
Definition at line 192 of file VisualMissionItem.h.
References _missionGimbalYaw.
missionGimbalYawChanged
void VisualMissionItem::missionGimbalYawChanged (double missionGimbalYaw) signal
Referenced by setMissionFlightStatus().
missionVehicleYaw()
double VisualMissionItem::missionVehicleYaw (void) const inline
Definition at line 193 of file VisualMissionItem.h.
References _missionVehicleYaw.
missionVehicleYawChanged
void VisualMissionItem::missionVehicleYawChanged (double missionVehicleYaw) signal
Referenced by setMissionVehicleYaw().
operator=()
const VisualMissionItem & VisualMissionItem::operator= (const VisualMissionItem & other)
Definition at line 41 of file VisualMissionItem.cc.
References _altDifference, _altPercent, _azimuth, _controllerVehicle, _dirty, _distance, _homePositionSpecialCase, _isCurrentItem, _masterController, _terrainAltitude, _terrainPercent, setAltDifference(), setAltPercent(), setAzimuth(), setDirty(), setDistance(), setDistanceFromStart(), setIsCurrentItem(), and setTerrainPercent().
Referenced by ComplexMissionItem::operator=().
parentItem()
VisualMissionItem * VisualMissionItem::parentItem (void) inline
Definition at line 108 of file VisualMissionItem.h.
References _parentItem.
Referenced by MissionController::setCurrentPlanViewSeqNum(), and setParentItem().
parentItemChanged
void VisualMissionItem::parentItemChanged (VisualMissionItem * parentItem) signal
Referenced by setParentItem().
previousVTOLModeChanged
void VisualMissionItem::previousVTOLModeChanged (void) signal
Referenced by setMissionFlightStatus().
readyForSaveState()
virtual ReadyForSaveState VisualMissionItem::readyForSaveState (void) const inline virtual
Returns
Returns whether the item is ready for save and if not, why
Reimplemented in CorridorScanComplexItem, LandingComplexItem, SimpleMissionItem, StructureScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
Definition at line 172 of file VisualMissionItem.h.
References ReadyForSave.
Referenced by MissionController::readyForSaveState().
readyForSaveStateChanged
void VisualMissionItem::readyForSaveStateChanged (void) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_missionItemCoordTerrainData(), TransectStyleComplexItem::_polyPathTerrainData(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
save()
virtual void VisualMissionItem::save (QJsonArray & missionItems) pure virtual
Save the item(s) in Json format
Parameters
missionItems Current set of mission items, new items should be appended to the end
Implemented in FixedWingLandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, VTOLLandingComplexItem, CorridorScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::save().
sequenceNumber()
virtual int VisualMissionItem::sequenceNumber (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by CorridorScanPlanCreator::createPlan(), StructureScanPlanCreator::createPlan(), SurveyPlanCreator::createPlan(), MissionFlightStatusCalculator::recalc(), MissionController::resumeMissionIndex(), and MissionController::setCurrentPlanViewSeqNum().
sequenceNumberChanged
void VisualMissionItem::sequenceNumberChanged (int sequenceNumber) signal
Referenced by LandingComplexItem::setSequenceNumber(), MissionSettingsItem::setSequenceNumber(), SimpleMissionItem::setSequenceNumber(), StructureScanComplexItem::setSequenceNumber(), and TransectStyleComplexItem::setSequenceNumber().
setAltDifference()
void VisualMissionItem::setAltDifference (double altDifference)
Definition at line 98 of file VisualMissionItem.cc.
References _altDifference, altDifference(), altDifferenceChanged(), and QGC::fuzzyCompare().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setAltPercent()
void VisualMissionItem::setAltPercent (double altPercent)
Definition at line 106 of file VisualMissionItem.cc.
References _altPercent, altPercent(), altPercentChanged(), and QGC::fuzzyCompare().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setAzimuth()
void VisualMissionItem::setAzimuth (double azimuth)
Definition at line 130 of file VisualMissionItem.cc.
References _azimuth, azimuth(), azimuthChanged(), and QGC::fuzzyCompare().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setCoordinate()
virtual void VisualMissionItem::setCoordinate (const QGeoCoordinate & coordinate) pure virtual
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, SimpleMissionItem, TakeoffMissionItem, and TransectStyleComplexItem.
Referenced by MissionController::insertComplexMissionItem(), MissionController::offsetMission(), MissionController::repositionMission(), and MissionController::rotateMission().
setDirty()
virtual void VisualMissionItem::setDirty (bool dirty) pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by operator=().
setDistance()
void VisualMissionItem::setDistance (double distance)
Definition at line 82 of file VisualMissionItem.cc.
References _distance, distance(), distanceChanged(), and QGC::fuzzyCompare().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setDistanceFromStart()
void VisualMissionItem::setDistanceFromStart (double distanceFromStart)
Definition at line 90 of file VisualMissionItem.cc.
References _distanceFromStart, distanceFromStart(), distanceFromStartChanged(), and QGC::fuzzyCompare().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setHasCurrentChildItem()
void VisualMissionItem::setHasCurrentChildItem (bool hasCurrentChildItem)
Definition at line 74 of file VisualMissionItem.cc.
References _hasCurrentChildItem, hasCurrentChildItem(), and hasCurrentChildItemChanged().
Referenced by MissionController::setCurrentPlanViewSeqNum().
setHomePositionSpecialCase()
void VisualMissionItem::setHomePositionSpecialCase (bool homePositionSpecialCase) inline
Definition at line 124 of file VisualMissionItem.h.
References _homePositionSpecialCase.
setIsCurrentItem()
void VisualMissionItem::setIsCurrentItem (bool isCurrentItem)
Definition at line 66 of file VisualMissionItem.cc.
References _isCurrentItem, isCurrentItem(), and isCurrentItemChanged().
Referenced by operator=(), and MissionController::setCurrentPlanViewSeqNum().
setMissionFlightStatus()
void VisualMissionItem::setMissionFlightStatus (MissionController::MissionFlightStatus_t & missionFlightStatus) virtual
Update item to mission flight status at point where this item appears in mission. IMPORTANT: Overrides must call base class implementation
Reimplemented in SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Definition at line 138 of file VisualMissionItem.cc.
References _missionGimbalYaw, _previousVTOLMode, QGC::fuzzyCompare(), missionGimbalYawChanged(), and previousVTOLModeChanged().
Referenced by MissionFlightStatusCalculator::recalc(), SimpleMissionItem::setMissionFlightStatus(), StructureScanComplexItem::setMissionFlightStatus(), and TransectStyleComplexItem::setMissionFlightStatus().
setMissionVehicleYaw()
void VisualMissionItem::setMissionVehicleYaw (double vehicleYaw)
Definition at line 150 of file VisualMissionItem.cc.
References _missionVehicleYaw, QGC::fuzzyCompare(), and missionVehicleYawChanged().
Referenced by MissionFlightStatusCalculator::recalc().
setParentItem()
void VisualMissionItem::setParentItem (VisualMissionItem * parentItem)
Definition at line 225 of file VisualMissionItem.cc.
References _parentItem, parentItem(), and parentItemChanged().
setSequenceNumber()
virtual void VisualMissionItem::setSequenceNumber (int sequenceNumber) pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
setSimpleFlighPathSegment()
void VisualMissionItem::setSimpleFlighPathSegment (FlightPathSegment * segment) inline
Definition at line 127 of file VisualMissionItem.h.
References _simpleFlightPathSegment.
setTerrainCollision()
void VisualMissionItem::setTerrainCollision (bool terrainCollision)
Definition at line 122 of file VisualMissionItem.cc.
References _terrainCollision, terrainCollision(), and terrainCollisionChanged().
Referenced by MissionFlightStatusCalculator::recalc().
setTerrainPercent()
void VisualMissionItem::setTerrainPercent (double terrainPercent)
Definition at line 114 of file VisualMissionItem.cc.
References _terrainPercent, QGC::fuzzyCompare(), terrainPercent(), and terrainPercentChanged().
Referenced by operator=(), and MissionFlightStatusCalculator::recalc().
setWizardMode()
void VisualMissionItem::setWizardMode (bool wizardMode)
Definition at line 217 of file VisualMissionItem.cc.
References _wizardMode, wizardMode(), and wizardModeChanged().
Referenced by StructureScanPlanCreator::createPlan().
simpleFlightPathSegment()
FlightPathSegment * VisualMissionItem::simpleFlightPathSegment (void) inline
Definition at line 126 of file VisualMissionItem.h.
References _simpleFlightPathSegment.
Referenced by TerrainProfile::updatePaintNode().
specifiedFlightSpeed()
virtual double VisualMissionItem::specifiedFlightSpeed (void) pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, TakeoffMissionItem, TransectStyleComplexItem, and SimpleMissionItem.
Referenced by MissionFlightStatusCalculator::recalc().
specifiedFlightSpeedChanged
void VisualMissionItem::specifiedFlightSpeedChanged (void) signal
Referenced by MissionSettingsItem::MissionSettingsItem().
specifiedGimbalPitch()
virtual double VisualMissionItem::specifiedGimbalPitch (void) pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, TakeoffMissionItem, TransectStyleComplexItem, and SimpleMissionItem.
Referenced by MissionFlightStatusCalculator::recalc().
specifiedGimbalPitchChanged
void VisualMissionItem::specifiedGimbalPitchChanged (void) signal
Referenced by MissionSettingsItem::MissionSettingsItem().
specifiedGimbalYaw()
virtual double VisualMissionItem::specifiedGimbalYaw (void) pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, TakeoffMissionItem, TransectStyleComplexItem, and SimpleMissionItem.
Referenced by MissionFlightStatusCalculator::recalc().
specifiedGimbalYawChanged
void VisualMissionItem::specifiedGimbalYawChanged (void) signal
Referenced by MissionSettingsItem::MissionSettingsItem().
specifiedVehicleYaw()
virtual double VisualMissionItem::specifiedVehicleYaw (void) inline virtual
Reimplemented in SimpleMissionItem.
Definition at line 155 of file VisualMissionItem.h.
specifiedVehicleYawChanged
void VisualMissionItem::specifiedVehicleYawChanged (void) signal
specifiesAltitudeOnly()
virtual bool VisualMissionItem::specifiesAltitudeOnly (void) const pure virtual
Implemented in LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::offsetMission().
specifiesAltitudeOnlyChanged
void VisualMissionItem::specifiesAltitudeOnlyChanged (void) signal
specifiesCoordinate()
virtual bool VisualMissionItem::specifiesCoordinate (void) const pure virtual
Implemented in CorridorScanComplexItem, LandingComplexItem, MissionSettingsItem, SimpleMissionItem, StructureScanComplexItem, SurveyComplexItem, and TransectStyleComplexItem.
Referenced by MissionController::offsetMission(), MissionFlightStatusCalculator::recalc(), MissionController::repositionMission(), MissionController::rotateMission(), and MissionController::setCurrentPlanViewSeqNum().
specifiesCoordinateChanged
void VisualMissionItem::specifiesCoordinateChanged (void) signal
terrainAltitude()
double VisualMissionItem::terrainAltitude (void) const inline
Definition at line 104 of file VisualMissionItem.h.
References _terrainAltitude.
Referenced by MissionFlightStatusCalculator::recalc().
terrainAltitudeChanged
void VisualMissionItem::terrainAltitudeChanged (double terrainAltitude) signal
Referenced by MissionSettingsItem::MissionSettingsItem().
terrainCollision()
bool VisualMissionItem::terrainCollision (void) const inline
Definition at line 98 of file VisualMissionItem.h.
References _terrainCollision.
Referenced by setTerrainCollision().
terrainCollisionChanged
void VisualMissionItem::terrainCollisionChanged (bool terrainCollision) signal
Referenced by setTerrainCollision().
terrainPercent()
double VisualMissionItem::terrainPercent (void) const inline
Definition at line 97 of file VisualMissionItem.h.
References _terrainPercent.
Referenced by setTerrainPercent().
terrainPercentChanged
void VisualMissionItem::terrainPercentChanged (double terrainPercent) signal
Referenced by setTerrainPercent().
terrainQueryFailed()
bool VisualMissionItem::terrainQueryFailed (void) const inline
Definition at line 105 of file VisualMissionItem.h.
References _terrainQueryFailed.
terrainQueryFailedChanged
void VisualMissionItem::terrainQueryFailedChanged (bool terrainQueryFailed) signal
wizardMode()
bool VisualMissionItem::wizardMode (void) const inline
Definition at line 107 of file VisualMissionItem.h.
References _wizardMode.
Referenced by setWizardMode().
wizardModeChanged
void VisualMissionItem::wizardModeChanged (bool wizardMode) signal
Referenced by LandingComplexItem::_init(), setWizardMode(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
Member Data Documentation
_altDifference
double VisualMissionItem::_altDifference = 0 protected
Difference in altitude from previous waypoint.
Definition at line 258 of file VisualMissionItem.h.
Referenced by altDifference(), operator=(), and setAltDifference().
_altPercent
double VisualMissionItem::_altPercent = 0 protected
Percent of total altitude change in mission.
Definition at line 259 of file VisualMissionItem.h.
Referenced by altPercent(), operator=(), and setAltPercent().
_azimuth
double VisualMissionItem::_azimuth = 0 protected
Azimuth to previous waypoint.
Definition at line 262 of file VisualMissionItem.h.
Referenced by azimuth(), operator=(), and setAzimuth().
_boundingCube
QGCGeoBoundingCube VisualMissionItem::_boundingCube protected
The bounding "cube" of this element.
Definition at line 275 of file VisualMissionItem.h.
Referenced by _setBoundingCube(), and boundingCube().
_childItems
QmlObjectListModel VisualMissionItem::_childItems protected
This is used to reference any subsequent mission items which do not specify a coordinate.
Definition at line 278 of file VisualMissionItem.h.
Referenced by childItems().
_controllerVehicle
Vehicle* VisualMissionItem::_controllerVehicle = nullptr protected
Definition at line 272 of file VisualMissionItem.h.
Referenced by LandingComplexItem::_createDoLandStartItem(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslExitAlt(), SimpleMissionItem::applyNewAltitude(), SimpleMissionItem::category(), SimpleMissionItem::commandDescription(), SimpleMissionItem::commandName(), SimpleMissionItem::friendlyEditAllowed(), TransectStyleComplexItem::hoverAndCaptureAllowed(), SimpleMissionItem::isLoiterItem(), SimpleMissionItem::isStandaloneCoordinate(), operator=(), SimpleMissionItem::showLoiterRadius(), SimpleMissionItem::specifiesAltitudeOnly(), and SimpleMissionItem::specifiesCoordinate().
_dirty
bool VisualMissionItem::_dirty = false protected
Definition at line 253 of file VisualMissionItem.h.
Referenced by MissionSettingsItem::dirty(), StructureScanComplexItem::dirty(), TransectStyleComplexItem::dirty(), operator=(), MissionSettingsItem::setDirty(), StructureScanComplexItem::setDirty(), and TransectStyleComplexItem::setDirty().
_distance
double VisualMissionItem::_distance = 0 protected
Distance to previous waypoint.
Definition at line 263 of file VisualMissionItem.h.
Referenced by distance(), operator=(), and setDistance().
_distanceFromStart
double VisualMissionItem::_distanceFromStart = 0 protected
Flight path cumalative horizontal distance from home point to this item.
Definition at line 264 of file VisualMissionItem.h.
Referenced by distanceFromStart(), and setDistanceFromStart().
_editorQml
QString VisualMissionItem::_editorQml protected
Qml resource for editing item.
Definition at line 265 of file VisualMissionItem.h.
Referenced by SimpleMissionItem::SimpleMissionItem(), and SimpleMissionItem::SimpleMissionItem().
_flyView
bool VisualMissionItem::_flyView = false protected
Definition at line 250 of file VisualMissionItem.h.
Referenced by MissionSettingsItem::abbreviation(), flyView(), and SimpleMissionItem::SimpleMissionItem().
_hasCurrentChildItem
bool VisualMissionItem::_hasCurrentChildItem = false protected
Definition at line 252 of file VisualMissionItem.h.
Referenced by hasCurrentChildItem(), and setHasCurrentChildItem().
_homePositionSpecialCase
bool VisualMissionItem::_homePositionSpecialCase = false protected
true: This item is being used as a ui home position indicator
Definition at line 254 of file VisualMissionItem.h.
Referenced by CONSTANT(), operator=(), SimpleMissionItem::setDirty(), and setHomePositionSpecialCase().
_isCurrentItem
bool VisualMissionItem::_isCurrentItem = false protected
Definition at line 251 of file VisualMissionItem.h.
Referenced by isCurrentItem(), operator=(), setIsCurrentItem(), and SimpleMissionItem::SimpleMissionItem().
_masterController
PlanMasterController* VisualMissionItem::_masterController = nullptr protected
Definition at line 270 of file VisualMissionItem.h.
Referenced by LandingComplexItem::_createDoLandStartItem(), LandingComplexItem::_init(), SimpleMissionItem::amslEntryAlt(), masterController(), operator=(), FixedWingLandingComplexItem::patternName(), and VTOLLandingComplexItem::patternName().
_missionController
MissionController* VisualMissionItem::_missionController = nullptr protected
Definition at line 271 of file VisualMissionItem.h.
Referenced by ComplexMissionItem::_appendFlightPathSegment(), LandingComplexItem::_init(), LandingComplexItem::amslEntryAlt(), StructureScanComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslEntryAlt(), LandingComplexItem::amslExitAlt(), ComplexMissionItem::ComplexMissionItem(), StructureScanComplexItem::maxAMSLAltitude(), TransectStyleComplexItem::maxAMSLAltitude(), StructureScanComplexItem::minAMSLAltitude(), and TransectStyleComplexItem::minAMSLAltitude().
_missionGimbalYaw
double VisualMissionItem::_missionGimbalYaw = qQNaN() protected
Definition at line 266 of file VisualMissionItem.h.
Referenced by missionGimbalYaw(), and setMissionFlightStatus().
_missionVehicleYaw
double VisualMissionItem::_missionVehicleYaw = qQNaN() protected
Definition at line 267 of file VisualMissionItem.h.
Referenced by missionVehicleYaw(), and setMissionVehicleYaw().
_parentItem
VisualMissionItem* VisualMissionItem::_parentItem = nullptr protected
Definition at line 274 of file VisualMissionItem.h.
Referenced by parentItem(), and setParentItem().
_previousVTOLMode
QGCMAVLinkTypes::VehicleClass_t VisualMissionItem::_previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric protected
Generic == unknown.
Definition at line 268 of file VisualMissionItem.h.
Referenced by LandingComplexItem::_createDoLandStartItem(), SimpleMissionItem::applyNewAltitude(), SimpleMissionItem::category(), SimpleMissionItem::commandDescription(), SimpleMissionItem::commandName(), SimpleMissionItem::friendlyEditAllowed(), SimpleMissionItem::isLoiterItem(), SimpleMissionItem::isStandaloneCoordinate(), setMissionFlightStatus(), SimpleMissionItem::showLoiterRadius(), SimpleMissionItem::specifiesAltitudeOnly(), and SimpleMissionItem::specifiesCoordinate().
_simpleFlightPathSegment
FlightPathSegment* VisualMissionItem::_simpleFlightPathSegment = nullptr protected
The simple item flight segment (if any) which starts with this visual item.
Definition at line 273 of file VisualMissionItem.h.
Referenced by clearSimpleFlighPathSegment(), setSimpleFlighPathSegment(), and simpleFlightPathSegment().
_terrainAltitude
double VisualMissionItem::_terrainAltitude = qQNaN() protected
Altitude of terrain at coordinate position, NaN for not known.
Definition at line 256 of file VisualMissionItem.h.
Referenced by SimpleMissionItem::amslEntryAlt(), operator=(), and terrainAltitude().
_terrainCollision
bool VisualMissionItem::_terrainCollision = false protected
true: item collides with terrain
Definition at line 261 of file VisualMissionItem.h.
Referenced by setTerrainCollision(), and terrainCollision().
_terrainPercent
double VisualMissionItem::_terrainPercent = qQNaN() protected
Percent of terrain altitude for coordinate.
Definition at line 260 of file VisualMissionItem.h.
Referenced by operator=(), setTerrainPercent(), and terrainPercent().
_terrainQueryFailed
bool VisualMissionItem::_terrainQueryFailed = false protected
true: Last terrain query failed
Definition at line 257 of file VisualMissionItem.h.
Referenced by terrainQueryFailed().
_wizardMode
bool VisualMissionItem::_wizardMode = false protected
true: Item editor is showing wizard completion panel
Definition at line 255 of file VisualMissionItem.h.
Referenced by TakeoffMissionItem::load(), TakeoffMissionItem::load(), LandingComplexItem::readyForSaveState(), SimpleMissionItem::readyForSaveState(), StructureScanComplexItem::readyForSaveState(), TransectStyleComplexItem::readyForSaveState(), setWizardMode(), and wizardMode().
jsonTypeComplexItemValue
constexpr const char* VisualMissionItem::jsonTypeComplexItemValue = "ComplexItem" static constexpr
Item type is Complex Item.
Definition at line 198 of file VisualMissionItem.h.
Referenced by LandingComplexItem::_load(), StructureScanComplexItem::load(), SurveyComplexItem::load(), FixedWingLandingComplexItem::save(), StructureScanComplexItem::save(), and VTOLLandingComplexItem::save().
jsonTypeKey
constexpr const char* VisualMissionItem::jsonTypeKey = "type" static constexpr
Json file attribute which specifies the item type.
Definition at line 196 of file VisualMissionItem.h.
Referenced by LandingComplexItem::_load(), StructureScanComplexItem::load(), SurveyComplexItem::load(), MissionItem::load(), FixedWingLandingComplexItem::save(), StructureScanComplexItem::save(), VTOLLandingComplexItem::save(), and MissionItem::save().
jsonTypeSimpleItemValue
constexpr const char* VisualMissionItem::jsonTypeSimpleItemValue = "SimpleItem" static constexpr
Item type is MISSION_ITEM.
Definition at line 197 of file VisualMissionItem.h.
Referenced by MissionItem::load(), and MissionItem::save().
The documentation for this class was generated from the following files:
src/MissionManager/VisualMissionItem.h
src/MissionManager/VisualMissionItem.cc