QGroundControl: ActuatorComponent Class Reference
ActuatorComponent Class Reference
#include <ActuatorComponent.h>
Public Member Functions
ActuatorComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
QStringList setupCompleteChangedTriggerList (void) const final
QString name (void) const final
QString description (void) const final
QString iconResource (void) const final
bool requiresSetup (void) const final
bool setupComplete (void) const final
virtual QUrl setupSource (void) const
QUrl summaryQmlSource (void) const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 7 of file ActuatorComponent.h.
Constructor & Destructor Documentation
ActuatorComponent()
ActuatorComponent::ActuatorComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr)
Definition at line 11 of file ActuatorComponent.cc.
References VehicleComponent::_triggerUpdated(), Actuators::hasUnsetRequiredFunctionsChanged(), imageProviderAdded, GeometryImage::VehicleGeometryImageProvider::instance(), and qgcApp.
Member Function Documentation
description()
QString ActuatorComponent::description (void) const final virtual
Reimplemented from VehicleComponent.
Definition at line 30 of file ActuatorComponent.cc.
iconResource()
QString ActuatorComponent::iconResource (void) const final virtual
Implements VehicleComponent.
Definition at line 35 of file ActuatorComponent.cc.
name()
QString ActuatorComponent::name (void) const final virtual
Implements VehicleComponent.
Definition at line 25 of file ActuatorComponent.cc.
requiresSetup()
bool ActuatorComponent::requiresSetup (void) const final virtual
Implements VehicleComponent.
Definition at line 40 of file ActuatorComponent.cc.
setupComplete()
bool ActuatorComponent::setupComplete (void) const final virtual
Implements VehicleComponent.
Definition at line 45 of file ActuatorComponent.cc.
References Actuators::hasUnsetRequiredFunctions().
setupCompleteChangedTriggerList()
QStringList ActuatorComponent::setupCompleteChangedTriggerList (void) const final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 50 of file ActuatorComponent.cc.
setupSource()
QUrl ActuatorComponent::setupSource (void) const virtual
Implements VehicleComponent.
Definition at line 55 of file ActuatorComponent.cc.
summaryQmlSource()
QUrl ActuatorComponent::summaryQmlSource (void) const final virtual
Implements VehicleComponent.
Definition at line 60 of file ActuatorComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/ActuatorComponent.h
src/AutoPilotPlugins/PX4/ActuatorComponent.cc