QGroundControl: MissionSettingsItem Class Reference
MissionSettingsItem Class Reference
#include <MissionSettingsItem.h>
Signals
void specifyMissionFlightSpeedChanged (bool specifyMissionFlightSpeed)
Signals inherited from ComplexMissionItem
void patternNameChanged (void)
void complexDistanceChanged (void)
void boundingCubeChanged (void)
void greatestDistanceToChanged (void)
void presetNamesChanged (void)
void isIncompleteChanged (void)
void minAMSLAltitudeChanged (void)
void maxAMSLAltitudeChanged (void)
void terrainCollisionChanged (bool terrainCollision)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
MissionSettingsItem (PlanMasterController *masterController, bool flyView)
Fact *plannedHomePositionAltitude READ plannedHomePositionAltitude CONSTANT (QObject *cameraSection READ cameraSection CONSTANT) 1(QObject *speedSection READ speedSection CONSTANT) Fact *plannedHomePositionAltitude(void)
CameraSection * cameraSection (void)
SpeedSection * speedSection (void)
bool scanForMissionSettings (QmlObjectListModel *visualItems, int scanIndex)
Scans the loaded items for settings items.
bool addMissionEndAction (QList< MissionItem * > &items, int seqNum, QObject *missionItemParent)
QString patternName (void) const final
double complexDistance (void) const final
int lastSequenceNumber (void) const final
bool load (const QJsonObject &complexObject, int sequenceNumber, QString &errorString) final
double greatestDistanceTo (const QGeoCoordinate &other) const final
QString mapVisualQML (void) const final
bool isSingleItem (void) const final
bool terrainCollision (void) const final
bool dirty (void) const final
bool isSimpleItem (void) const final
bool isStandaloneCoordinate (void) const final
bool specifiesCoordinate (void) const final
bool specifiesAltitudeOnly (void) const final
QString commandDescription (void) const final
QString commandName (void) const final
QString abbreviation (void) const final
QGeoCoordinate coordinate (void) const final
QGeoCoordinate entryCoordinate (void) const final
QGeoCoordinate exitCoordinate (void) const final
int sequenceNumber (void) const final
double specifiedGimbalYaw (void) final
double specifiedGimbalPitch (void) final
void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent) final
void applyNewAltitude (double) final
Adjust the altitude of the item if appropriate to the new altitude.
double specifiedFlightSpeed (void) final
double additionalTimeDelay (void) const final
bool exitCoordinateSameAsEntry (void) const final
void setDirty (bool dirty) final
void setCoordinate (const QGeoCoordinate &coordinate) final
void setSequenceNumber (int sequenceNumber) final
void save (QJsonArray &missionItems) final
double editableAlt (void) const final
double amslEntryAlt (void) const final
double amslExitAlt (void) const final
double minAMSLAltitude (void) const final
double maxAMSLAltitude (void) const final
Public Member Functions inherited from ComplexMissionItem
ComplexMissionItem (PlanMasterController *masterController, bool flyView)
const ComplexMissionItem & operator= (const ComplexMissionItem &other)
QString patternName READ patternName NOTIFY patternNameChanged (double complexDistance READ complexDistance NOTIFY complexDistanceChanged) 1(bool presetsSupported READ presetsSupported CONSTANT) 1(QStringList presetNames READ presetNames NOTIFY presetNamesChanged) 1(bool isIncomplete READ isIncomplete NOTIFY isIncompleteChanged) 1(double minAMSLAltitude READ minAMSLAltitude NOTIFY minAMSLAltitudeChanged) 1(double maxAMSLAltitude READ maxAMSLAltitude NOTIFY maxAMSLAltitudeChanged) 1(bool isSingleItem READ isSingleItem CONSTANT) 1(QmlObjectListModel *flightPathSegments READ flightPathSegments CONSTANT) 1(bool terrainCollision READ terrainCollision NOTIFY terrainCollisionChanged) QmlObjectListModel *flightPathSegments(void)
< Minimum altitude of all coordinates in item
virtual void loadPreset (const QString &name)
virtual void savePreset (const QString &name)
void deletePreset (const QString &name)
virtual QStringList presetNames (void)
virtual QString presetsSettingsGroup (void)
virtual void addKMLVisuals (KMLPlanDomDocument &domDocument)
bool presetsSupported (void)
bool isIncomplete (void) const
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool isTakeoffItem (void) const
virtual bool isLandCommand (void) const
virtual bool isSurveyItem (void) const
virtual double specifiedVehicleYaw (void)
virtual QGCGeoBoundingCube * boundingCube (void)
virtual void setMissionFlightStatus (MissionFlightStatus_t &missionFlightStatus)
virtual ReadyForSaveState readyForSaveState (void) const
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Static Public Attributes inherited from ComplexMissionItem
static constexpr const char * jsonComplexItemTypeKey = "complexItemType"
This mission item attribute specifies the type of the complex item.
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Slots inherited from ComplexMissionItem
virtual void _segmentTerrainCollisionChanged (bool terrainCollision)
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions inherited from ComplexMissionItem
void _savePresetJson (const QString &name, QJsonObject &presetObject)
QJsonObject _loadPresetJson (const QString &name)
void _appendFlightPathSegment (FlightPathSegment::SegmentType segmentType, const QGeoCoordinate &coord1, double coord1AMSLAlt, const QGeoCoordinate &coord2, double coord2AMSLAlt)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes inherited from ComplexMissionItem
bool _isIncomplete = true
int _cTerrainCollisionSegments = 0
QmlObjectListModel _flightPathSegments
QMap< QString, FactMetaData * > _metaDataMap
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Static Protected Attributes inherited from ComplexMissionItem
static constexpr const char * _presetSettingsKey = "_presets"
Detailed Description
Definition at line 12 of file MissionSettingsItem.h.
Constructor & Destructor Documentation
MissionSettingsItem()
MissionSettingsItem::MissionSettingsItem (PlanMasterController * masterController, bool flyView)
Definition at line 14 of file MissionSettingsItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::amslEntryAltChanged(), VisualMissionItem::amslExitAltChanged(), VisualMissionItem::coordinateChanged(), FactMetaData::createMapFromJsonFile(), Section::dirtyChanged(), VisualMissionItem::entryCoordinateChanged(), VisualMissionItem::exitCoordinateChanged(), Vehicle::homePositionChanged(), Section::itemCountChanged(), ComplexMissionItem::maxAMSLAltitudeChanged(), ComplexMissionItem::minAMSLAltitudeChanged(), Fact::rawValueChanged(), SpeedSection::specifiedFlightSpeedChanged(), VisualMissionItem::specifiedFlightSpeedChanged(), CameraSection::specifiedGimbalPitchChanged(), VisualMissionItem::specifiedGimbalPitchChanged(), CameraSection::specifiedGimbalYawChanged(), VisualMissionItem::specifiedGimbalYawChanged(), specifyMissionFlightSpeedChanged(), and VisualMissionItem::terrainAltitudeChanged().
Member Function Documentation
abbreviation()
QString MissionSettingsItem::abbreviation (void) const final virtual
Implements VisualMissionItem.
Definition at line 235 of file MissionSettingsItem.cc.
References VisualMissionItem::_flyView.
additionalTimeDelay()
double MissionSettingsItem::additionalTimeDelay (void) const inline final virtual
Returns
Amount of additional time delay in seconds needed to fly this item
Implements VisualMissionItem.
Definition at line 65 of file MissionSettingsItem.h.
addMissionEndAction()
bool MissionSettingsItem::addMissionEndAction (QList< MissionItem * > & items, int seqNum, QObject * missionItemParent)
Adds the optional mission end action to the list
Parameters
items Mission items list to append to
seqNum Sequence number for new item
missionItemParent Parent for newly allocated MissionItems
Returns
true: Mission end action was added
Definition at line 147 of file MissionSettingsItem.cc.
amslEntryAlt()
double MissionSettingsItem::amslEntryAlt (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 72 of file MissionSettingsItem.h.
Referenced by amslExitAlt(), maxAMSLAltitude(), and minAMSLAltitude().
amslExitAlt()
double MissionSettingsItem::amslExitAlt (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 73 of file MissionSettingsItem.h.
References amslEntryAlt().
appendMissionItems()
void MissionSettingsItem::appendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) final virtual
Returns the mission items associated with the complex item. Caller is responsible for freeing.
Parameters
items List to append to
missionItemParent Parent object for newly created MissionItems
Implements VisualMissionItem.
Definition at line 121 of file MissionSettingsItem.cc.
References CameraSection::appendSectionItems(), SpeedSection::appendSectionItems(), and coordinate().
Referenced by save().
applyNewAltitude()
void MissionSettingsItem::applyNewAltitude (double newAltitude) inline final virtual
Adjust the altitude of the item if appropriate to the new altitude.
Implements VisualMissionItem.
Definition at line 63 of file MissionSettingsItem.h.
cameraSection()
CameraSection * MissionSettingsItem::cameraSection (void) inline
Definition at line 24 of file MissionSettingsItem.h.
commandDescription()
QString MissionSettingsItem::commandDescription (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 53 of file MissionSettingsItem.h.
commandName()
QString MissionSettingsItem::commandName (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 54 of file MissionSettingsItem.h.
complexDistance()
double MissionSettingsItem::complexDistance (void) const final virtual
Returns
The distance covered the complex mission item in meters. Signals complexDistanceChanged
Implements ComplexMissionItem.
Definition at line 166 of file MissionSettingsItem.cc.
CONSTANT()
Fact *plannedHomePositionAltitude READ plannedHomePositionAltitude MissionSettingsItem::CONSTANT (QObject *cameraSection READ cameraSection CONSTANT) inline
Definition at line 19 of file MissionSettingsItem.h.
coordinate()
QGeoCoordinate MissionSettingsItem::coordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 56 of file MissionSettingsItem.h.
Referenced by appendMissionItems(), entryCoordinate(), exitCoordinate(), MissionController::homePositionSet(), MissionController::plannedHomePosition(), MissionFlightStatusCalculator::recalc(), MissionController::repositionMission(), MissionController::rotateMission(), MissionController::save(), and setCoordinate().
dirty()
bool MissionSettingsItem::dirty (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 48 of file MissionSettingsItem.h.
References VisualMissionItem::_dirty.
Referenced by setDirty().
editableAlt()
double MissionSettingsItem::editableAlt (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 71 of file MissionSettingsItem.h.
entryCoordinate()
QGeoCoordinate MissionSettingsItem::entryCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 57 of file MissionSettingsItem.h.
References coordinate().
exitCoordinate()
QGeoCoordinate MissionSettingsItem::exitCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 58 of file MissionSettingsItem.h.
References coordinate().
exitCoordinateSameAsEntry()
bool MissionSettingsItem::exitCoordinateSameAsEntry (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 66 of file MissionSettingsItem.h.
greatestDistanceTo()
double MissionSettingsItem::greatestDistanceTo (const QGeoCoordinate & other) const final virtual
Get the point of complex mission item furthest away from a coordinate
Parameters
other QGeoCoordinate to which distance is calculated
Returns
the greatest distance from any point of the complex item to some coordinate Signals greatestDistanceToChanged
Implements ComplexMissionItem.
Definition at line 110 of file MissionSettingsItem.cc.
isSimpleItem()
bool MissionSettingsItem::isSimpleItem (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 49 of file MissionSettingsItem.h.
isSingleItem()
bool MissionSettingsItem::isSingleItem (void) const inline final virtual
Returns
true: Represents a single coordinate (ex: MissionSettingsItem), false: Represents multiple items (ex: Survey)
Reimplemented from ComplexMissionItem.
Definition at line 44 of file MissionSettingsItem.h.
isStandaloneCoordinate()
bool MissionSettingsItem::isStandaloneCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 50 of file MissionSettingsItem.h.
lastSequenceNumber()
int MissionSettingsItem::lastSequenceNumber (void) const final virtual
Implements VisualMissionItem.
Definition at line 57 of file MissionSettingsItem.cc.
References CameraSection::itemCount(), SpeedSection::itemCount(), and lastSequenceNumber().
Referenced by lastSequenceNumber(), and setSequenceNumber().
load()
bool MissionSettingsItem::load (const QJsonObject & complexObject, int sequenceNumber, QString & errorString) final virtual
Load the complex mission item from Json
Parameters
complexObject Complex mission item json object
sequenceNumber Sequence number for first MISSION_ITEM in survey
[out] errorString Error if load fails
Returns
true: load success, false: load failed, errorString set
Implements ComplexMissionItem.
Definition at line 105 of file MissionSettingsItem.cc.
mapVisualQML()
QString MissionSettingsItem::mapVisualQML (void) const inline final virtual
Returns
The QML resource file which contains the control which visualizes the item on the map.
Implements VisualMissionItem.
Definition at line 43 of file MissionSettingsItem.h.
maxAMSLAltitude()
double MissionSettingsItem::maxAMSLAltitude (void) const inline final virtual
Returns
Maximum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 75 of file MissionSettingsItem.h.
References amslEntryAlt().
minAMSLAltitude()
double MissionSettingsItem::minAMSLAltitude (void) const inline final virtual
Returns
Minimum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 74 of file MissionSettingsItem.h.
References amslEntryAlt().
patternName()
QString MissionSettingsItem::patternName (void) const inline final virtual
Implements ComplexMissionItem.
Definition at line 38 of file MissionSettingsItem.h.
save()
void MissionSettingsItem::save (QJsonArray & missionItems) final virtual
Save the item(s) in Json format
Parameters
missionItems Current set of mission items, new items should be appended to the end
Implements VisualMissionItem.
Definition at line 79 of file MissionSettingsItem.cc.
References appendMissionItems(), and MissionItem::save().
scanForMissionSettings()
bool MissionSettingsItem::scanForMissionSettings (QmlObjectListModel * visualItems, int scanIndex)
Scans the loaded items for settings items.
Definition at line 152 of file MissionSettingsItem.cc.
References QmlObjectListModel::count(), CameraSection::scanForSection(), and SpeedSection::scanForSection().
sequenceNumber()
int MissionSettingsItem::sequenceNumber (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 59 of file MissionSettingsItem.h.
Referenced by setSequenceNumber().
setCoordinate()
void MissionSettingsItem::setCoordinate (const QGeoCoordinate & coordinate) final virtual
Implements VisualMissionItem.
Definition at line 176 of file MissionSettingsItem.cc.
References coordinate(), and VisualMissionItem::coordinateChanged().
Referenced by TakeoffMissionItem::setCoordinate(), and MissionController::setHomePosition().
setDirty()
void MissionSettingsItem::setDirty (bool dirty) final virtual
Implements VisualMissionItem.
Definition at line 67 of file MissionSettingsItem.cc.
References VisualMissionItem::_dirty, dirty(), VisualMissionItem::dirtyChanged(), CameraSection::setDirty(), and SpeedSection::setDirty().
setSequenceNumber()
void MissionSettingsItem::setSequenceNumber (int sequenceNumber) final virtual
Implements VisualMissionItem.
Definition at line 96 of file MissionSettingsItem.cc.
References lastSequenceNumber(), VisualMissionItem::lastSequenceNumberChanged(), sequenceNumber(), and VisualMissionItem::sequenceNumberChanged().
specifiedFlightSpeed()
double MissionSettingsItem::specifiedFlightSpeed (void) final virtual
Implements VisualMissionItem.
Definition at line 218 of file MissionSettingsItem.cc.
References SpeedSection::flightSpeed().
specifiedGimbalPitch()
double MissionSettingsItem::specifiedGimbalPitch (void) final virtual
Implements VisualMissionItem.
Definition at line 202 of file MissionSettingsItem.cc.
References CameraSection::gimbalPitch().
specifiedGimbalYaw()
double MissionSettingsItem::specifiedGimbalYaw (void) final virtual
Implements VisualMissionItem.
Definition at line 197 of file MissionSettingsItem.cc.
References CameraSection::gimbalYaw().
specifiesAltitudeOnly()
bool MissionSettingsItem::specifiesAltitudeOnly (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 52 of file MissionSettingsItem.h.
specifiesCoordinate()
bool MissionSettingsItem::specifiesCoordinate (void) const final virtual
Implements VisualMissionItem.
Definition at line 116 of file MissionSettingsItem.cc.
specifyMissionFlightSpeedChanged
void MissionSettingsItem::specifyMissionFlightSpeedChanged (bool specifyMissionFlightSpeed) signal
Referenced by MissionSettingsItem().
speedSection()
SpeedSection * MissionSettingsItem::speedSection (void) inline
Definition at line 25 of file MissionSettingsItem.h.
terrainCollision()
bool MissionSettingsItem::terrainCollision (void) const inline final virtual
Returns
true: This complex item is colliding with terrain
Reimplemented from ComplexMissionItem.
Definition at line 45 of file MissionSettingsItem.h.
The documentation for this class was generated from the following files:
src/MissionManager/MissionSettingsItem.h
src/MissionManager/MissionSettingsItem.cc