QGroundControl: MockLinkWorker Class Reference
MockLinkWorker Class Reference
#include <MockLinkWorker.h>
Public Slots
void startWork ()
void stopWork ()
Public Member Functions
MockLinkWorker (MockLink *link, QObject *parent=nullptr)
~MockLinkWorker ()
Static Public Attributes
static constexpr int kTimer1HzIntervalMs = 1000
Timer intervals in milliseconds.
static constexpr int kTimer10HzIntervalMs = 100
10 Hz tasks (heartbeat, GPS, position)
static constexpr int kTimer500HzIntervalMs = 2
500 Hz tasks (param list, log download)
static constexpr int kStatusTextDelayMs = 10000
Delay before sending status text messages.
Detailed Description
Worker class that runs periodic tasks for MockLink simulation. Operates on a separate thread to avoid blocking the main thread.
Definition at line 10 of file MockLinkWorker.h.
Constructor & Destructor Documentation
MockLinkWorker()
MockLinkWorker::MockLinkWorker (MockLink * link, QObject * parent = nullptr) explicit
Definition at line 6 of file MockLinkWorker.cc.
~MockLinkWorker()
MockLinkWorker::~MockLinkWorker ()
Definition at line 13 of file MockLinkWorker.cc.
References stopWork().
Member Function Documentation
startWork
void MockLinkWorker::startWork () slot
Definition at line 18 of file MockLinkWorker.cc.
References kStatusTextDelayMs, kTimer10HzIntervalMs, kTimer1HzIntervalMs, kTimer500HzIntervalMs, and MockLink::shouldSendStatusText().
Referenced by MockLink::MockLink().
stopWork
void MockLinkWorker::stopWork () slot
Definition at line 49 of file MockLinkWorker.cc.
Referenced by ~MockLinkWorker().
Member Data Documentation
kStatusTextDelayMs
constexpr int MockLinkWorker::kStatusTextDelayMs = 10000 static constexpr
Delay before sending status text messages.
Definition at line 22 of file MockLinkWorker.h.
Referenced by startWork().
kTimer10HzIntervalMs
constexpr int MockLinkWorker::kTimer10HzIntervalMs = 100 static constexpr
10 Hz tasks (heartbeat, GPS, position)
Definition at line 20 of file MockLinkWorker.h.
Referenced by startWork().
kTimer1HzIntervalMs
constexpr int MockLinkWorker::kTimer1HzIntervalMs = 1000 static constexpr
Timer intervals in milliseconds.
1 Hz tasks (battery, sys status, ADSB, etc.)
Definition at line 19 of file MockLinkWorker.h.
Referenced by startWork().
kTimer500HzIntervalMs
constexpr int MockLinkWorker::kTimer500HzIntervalMs = 2 static constexpr
500 Hz tasks (param list, log download)
Definition at line 21 of file MockLinkWorker.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
src/Comms/MockLink/MockLinkWorker.h
src/Comms/MockLink/MockLinkWorker.cc