QGroundControl: MockLinkMissionItemHandler Class Reference
MockLinkMissionItemHandler Class Reference
#include <MockLinkMissionItemHandler.h>
Public Types
enum FailureMode_t {
FailNone , FailReadRequestListNoResponse , FailReadRequestListFirstResponse , FailReadRequest0NoResponse ,
FailReadRequest1NoResponse , FailReadRequest1FirstResponse , FailReadRequest0IncorrectSequence , FailReadRequest1IncorrectSequence ,
FailReadRequest0ErrorAck , FailReadRequest1ErrorAck , FailWriteMissionCountNoResponse , FailWriteMissionCountFirstResponse ,
FailWriteRequest1NoResponse , FailWriteRequest0IncorrectSequence , FailWriteRequest1IncorrectSequence , FailWriteRequest0ErrorAck ,
FailWriteRequest1ErrorAck , FailWriteFinalAckNoResponse , FailWriteFinalAckErrorAck , FailWriteFinalAckMissingRequests
}
Public Member Functions
MockLinkMissionItemHandler (MockLink *mockLink)
~MockLinkMissionItemHandler ()
void shutdown ()
bool handleMavlinkMessage (const mavlink_message_t &msg)
void setFailureMode (FailureMode_t failureMode, MAV_MISSION_RESULT failureAckResult)
void sendUnexpectedMissionAck (MAV_MISSION_RESULT ackType)
Called to send a MISSION_ACK message while the MissionManager is in idle state.
void sendUnexpectedMissionItem ()
Called to send a MISSION_ITEM message while the MissionManager is in idle state.
void sendUnexpectedMissionRequest ()
Called to send a MISSION_REQUEST message while the MissionManager is in idle state.
void reset ()
Reset the state of the MissionItemHandler to no items, no transactions in progress.
void setSendHomePositionOnEmptyList (bool sendHomePositionOnEmptyList)
int requestListCount (MAV_MISSION_TYPE type) const
void clearRequestListCounts ()
Detailed Description
Definition at line 11 of file MockLinkMissionItemHandler.h.
Member Enumeration Documentation
FailureMode_t
enum MockLinkMissionItemHandler::FailureMode_t
Enumerator
FailNone
FailReadRequestListNoResponse
FailReadRequestListFirstResponse
FailReadRequest0NoResponse
FailReadRequest1NoResponse
FailReadRequest1FirstResponse
FailReadRequest0IncorrectSequence
FailReadRequest1IncorrectSequence
FailReadRequest0ErrorAck
FailReadRequest1ErrorAck
FailWriteMissionCountNoResponse
FailWriteMissionCountFirstResponse
FailWriteRequest1NoResponse
FailWriteRequest0IncorrectSequence
FailWriteRequest1IncorrectSequence
FailWriteRequest0ErrorAck
FailWriteRequest1ErrorAck
FailWriteFinalAckNoResponse
FailWriteFinalAckErrorAck
FailWriteFinalAckMissingRequests
Definition at line 27 of file MockLinkMissionItemHandler.h.
Constructor & Destructor Documentation
MockLinkMissionItemHandler()
MockLinkMissionItemHandler::MockLinkMissionItemHandler (MockLink * mockLink)
Definition at line 9 of file MockLinkMissionItemHandler.cc.
~MockLinkMissionItemHandler()
MockLinkMissionItemHandler::~MockLinkMissionItemHandler ()
Definition at line 20 of file MockLinkMissionItemHandler.cc.
Member Function Documentation
clearRequestListCounts()
void MockLinkMissionItemHandler::clearRequestListCounts () inline
Definition at line 70 of file MockLinkMissionItemHandler.h.
Referenced by MockLink::clearReceivedMavlinkMessageCounts().
handleMavlinkMessage()
bool MockLinkMissionItemHandler::handleMavlinkMessage (const mavlink_message_t & msg)
Called to handle mission item related messages. All messages should be passed to this method. It will handle the appropriate set.
Returns
true: message handled
Definition at line 30 of file MockLinkMissionItemHandler.cc.
requestListCount()
int MockLinkMissionItemHandler::requestListCount (MAV_MISSION_TYPE type) const inline
Definition at line 69 of file MockLinkMissionItemHandler.h.
Referenced by MockLink::receivedMissionRequestListCount().
reset()
void MockLinkMissionItemHandler::reset () inline
Reset the state of the MissionItemHandler to no items, no transactions in progress.
Definition at line 65 of file MockLinkMissionItemHandler.h.
Referenced by MockLink::resetMissionItemHandler().
sendUnexpectedMissionAck()
void MockLinkMissionItemHandler::sendUnexpectedMissionAck (MAV_MISSION_RESULT ackType)
Called to send a MISSION_ACK message while the MissionManager is in idle state.
Definition at line 403 of file MockLinkMissionItemHandler.cc.
Referenced by MockLink::sendUnexpectedMissionAck().
sendUnexpectedMissionItem()
void MockLinkMissionItemHandler::sendUnexpectedMissionItem ()
Called to send a MISSION_ITEM message while the MissionManager is in idle state.
Definition at line 408 of file MockLinkMissionItemHandler.cc.
Referenced by MockLink::sendUnexpectedMissionItem().
sendUnexpectedMissionRequest()
void MockLinkMissionItemHandler::sendUnexpectedMissionRequest ()
Called to send a MISSION_REQUEST message while the MissionManager is in idle state.
Definition at line 414 of file MockLinkMissionItemHandler.cc.
Referenced by MockLink::sendUnexpectedMissionRequest().
setFailureMode()
void MockLinkMissionItemHandler::setFailureMode (FailureMode_t failureMode, MAV_MISSION_RESULT failureAckResult)
Sets a failure mode for unit testing
Parameters
failureMode Type of failure to simulate
failureAckResult Error to send if one the ack error modes
Definition at line 420 of file MockLinkMissionItemHandler.cc.
Referenced by MockLink::setMissionItemFailureMode().
setSendHomePositionOnEmptyList()
void MockLinkMissionItemHandler::setSendHomePositionOnEmptyList (bool sendHomePositionOnEmptyList) inline
Definition at line 67 of file MockLinkMissionItemHandler.h.
shutdown()
void MockLinkMissionItemHandler::shutdown ()
Definition at line 426 of file MockLinkMissionItemHandler.cc.
Referenced by MockLink::disconnect().
The documentation for this class was generated from the following files:
src/Comms/MockLink/MockLinkMissionItemHandler.h
src/Comms/MockLink/MockLinkMissionItemHandler.cc