QGroundControl: FlightMapSettings Class Reference
FlightMapSettings Class Reference
#include <FlightMapSettings.h>
Public Member Functions
FlightMapSettings (QObject *parent=nullptr)
Fact *mapProvider READ mapProvider CONSTANT Fact * mapProvider ()
Fact *mapType READ mapType CONSTANT Fact * mapType ()
Fact *elevationMapProvider READ elevationMapProvider CONSTANT Fact * elevationMapProvider ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "FlightMap"
static const char * settingsGroup = "FlightMap"
static const char * mapProviderName = "mapProvider"
static const char * mapTypeName = "mapType"
static const char * elevationMapProviderName = "elevationMapProvider"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file FlightMapSettings.h.
Constructor & Destructor Documentation
FlightMapSettings()
FlightMapSettings::FlightMapSettings (QObject * parent = nullptr)
Definition at line 3 of file FlightMapSettings.cc.
Member Function Documentation
elevationMapProvider()
Fact * FlightMapSettings::elevationMapProvider ()
Definition at line 9 of file FlightMapSettings.cc.
Referenced by QGroundControlQmlGlobal::elevationProviderName(), QGroundControlQmlGlobal::elevationProviderNotice(), and TerrainTileManager::getAltitudesForCoordinates().
mapProvider()
Fact * FlightMapSettings::mapProvider ()
Definition at line 7 of file FlightMapSettings.cc.
mapType()
Fact * FlightMapSettings::mapType ()
Definition at line 8 of file FlightMapSettings.cc.
Member Data Documentation
elevationMapProviderName
const char * FlightMapSettings::elevationMapProviderName = "elevationMapProvider" static
Definition at line 19 of file FlightMapSettings.h.
mapProviderName
const char * FlightMapSettings::mapProviderName = "mapProvider" static
Definition at line 17 of file FlightMapSettings.h.
mapTypeName
const char * FlightMapSettings::mapTypeName = "mapType" static
Definition at line 18 of file FlightMapSettings.h.
name
const char * FlightMapSettings::name = "FlightMap" static
Definition at line 16 of file FlightMapSettings.h.
settingsGroup
const char * FlightMapSettings::settingsGroup = "FlightMap" static
Definition at line 16 of file FlightMapSettings.h.
The documentation for this class was generated from the following files:
src/Settings/FlightMapSettings.h
src/Settings/FlightMapSettings.cc