QGroundControl: AndroidInterface::JniLocalRef< T > Class Template Reference
AndroidInterface::JniLocalRef< T > Class Template Reference
#include <AndroidInterface.h>
Public Member Functions
JniLocalRef (JNIEnv *env, T ref=nullptr)
~JniLocalRef ()
JniLocalRef (const JniLocalRef &)=delete
JniLocalRef & operator= (const JniLocalRef &)=delete
JniLocalRef (JniLocalRef &&other) noexcept
JniLocalRef & operator= (JniLocalRef &&other) noexcept
T get () const
operator T () const
void reset (T ref=nullptr)
Detailed Description
template<typename T>
class AndroidInterface::JniLocalRef< T >
Definition at line 18 of file AndroidInterface.h.
Constructor & Destructor Documentation
JniLocalRef() [1/3]
template<typename T > AndroidInterface::JniLocalRef< T >::JniLocalRef (JNIEnv * env, T ref = nullptr) inline
Definition at line 21 of file AndroidInterface.h.
~JniLocalRef()
template<typename T > AndroidInterface::JniLocalRef< T >::~JniLocalRef () inline
Definition at line 25 of file AndroidInterface.h.
References AndroidInterface::JniLocalRef< T >::reset().
JniLocalRef() [2/3]
template<typename T > AndroidInterface::JniLocalRef< T >::JniLocalRef (const JniLocalRef< T > &) delete
JniLocalRef() [3/3]
template<typename T > AndroidInterface::JniLocalRef< T >::JniLocalRef (JniLocalRef< T > && other) inline noexcept
Definition at line 33 of file AndroidInterface.h.
Member Function Documentation
get()
template<typename T > T AndroidInterface::JniLocalRef< T >::get () const inline
Definition at line 51 of file AndroidInterface.h.
Referenced by AndroidSerial::availableDevices(), AndroidSerial::getControlLines(), AndroidSerial::read(), and AndroidSerial::write().
operator T()
template<typename T > AndroidInterface::JniLocalRef< T >::operator T () const inline
Definition at line 56 of file AndroidInterface.h.
operator=() [1/2]
template<typename T > JniLocalRef & AndroidInterface::JniLocalRef< T >::operator= (const JniLocalRef< T > &) delete
operator=() [2/2]
template<typename T > JniLocalRef & AndroidInterface::JniLocalRef< T >::operator= (JniLocalRef< T > && other) inline noexcept
Definition at line 38 of file AndroidInterface.h.
References AndroidInterface::JniLocalRef< T >::reset().
reset()
template<typename T > void AndroidInterface::JniLocalRef< T >::reset (T ref = nullptr) inline
Definition at line 61 of file AndroidInterface.h.
Referenced by AndroidInterface::JniLocalRef< T >::operator=(), and AndroidInterface::JniLocalRef< T >::~JniLocalRef().
The documentation for this class was generated from the following file:
src/Android/AndroidInterface.h