QGroundControl: GstVideoWorker Class Reference
GstVideoWorker Class Reference
#include <GstVideoReceiver.h>
Public Member Functions
GstVideoWorker (QObject *parent=nullptr)
~GstVideoWorker ()
bool needDispatch () const
void dispatch (Task task)
void shutdown ()
Detailed Description
Definition at line 19 of file GstVideoReceiver.h.
Constructor & Destructor Documentation
GstVideoWorker()
GstVideoWorker::GstVideoWorker (QObject * parent = nullptr) explicit
Definition at line 1515 of file GstVideoReceiver.cc.
~GstVideoWorker()
GstVideoWorker::~GstVideoWorker ()
Definition at line 1521 of file GstVideoReceiver.cc.
Member Function Documentation
dispatch()
void GstVideoWorker::dispatch (Task task)
Definition at line 1531 of file GstVideoReceiver.cc.
Referenced by shutdown(), GstVideoReceiver::start(), GstVideoReceiver::startDecoding(), GstVideoReceiver::startRecording(), GstVideoReceiver::stop(), GstVideoReceiver::stopDecoding(), GstVideoReceiver::stopRecording(), and GstVideoReceiver::takeScreenshot().
needDispatch()
bool GstVideoWorker::needDispatch () const
Definition at line 1526 of file GstVideoReceiver.cc.
Referenced by shutdown().
shutdown()
void GstVideoWorker::shutdown ()
Definition at line 1538 of file GstVideoReceiver.cc.
References dispatch(), and needDispatch().
Referenced by GstVideoReceiver::~GstVideoReceiver().
The documentation for this class was generated from the following files:
src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.h
src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc