QGroundControl: NTRIPSourceTableFetcher Class Reference
NTRIPSourceTableFetcher Class Reference
#include <NTRIPSourceTable.h>
Signals
void sourceTableReceived (const QString &table)
void error (const QString &errorMsg)
void finished ()
Public Member Functions
NTRIPSourceTableFetcher (const QString &host, int port, const QString &username, const QString &password, bool useTls=false, QObject *parent=nullptr)
~NTRIPSourceTableFetcher () override=default
void fetch ()
Static Public Attributes
static constexpr int kFetchTimeoutMs = 10000
Detailed Description
Definition at line 113 of file NTRIPSourceTable.h.
Constructor & Destructor Documentation
NTRIPSourceTableFetcher()
NTRIPSourceTableFetcher::NTRIPSourceTableFetcher (const QString & host, int port, const QString & username, const QString & password, bool useTls = false, QObject * parent = nullptr)
Definition at line 136 of file NTRIPSourceTable.cc.
References QGCNetworkHelper::createNetworkManager().
~NTRIPSourceTableFetcher()
NTRIPSourceTableFetcher::~NTRIPSourceTableFetcher () override default
Member Function Documentation
error
void NTRIPSourceTableFetcher::error (const QString & errorMsg) signal
fetch()
void NTRIPSourceTableFetcher::fetch ()
Definition at line 150 of file NTRIPSourceTable.cc.
References QGCNetworkHelper::RequestConfig::cacheEnabled, QGCNetworkHelper::createRequest(), QGCNetworkHelper::RequestConfig::http2Allowed, kFetchTimeoutMs, QGCNetworkHelper::setBasicAuth(), QGCNetworkHelper::RequestConfig::timeoutMs, and QGCNetworkHelper::RequestConfig::userAgent.
finished
void NTRIPSourceTableFetcher::finished () signal
sourceTableReceived
void NTRIPSourceTableFetcher::sourceTableReceived (const QString & table) signal
Member Data Documentation
kFetchTimeoutMs
constexpr int NTRIPSourceTableFetcher::kFetchTimeoutMs = 10000 static constexpr
Definition at line 118 of file NTRIPSourceTable.h.
Referenced by fetch().
The documentation for this class was generated from the following files:
src/GPS/NTRIP/NTRIPSourceTable.h
src/GPS/NTRIP/NTRIPSourceTable.cc