QGroundControl: APMAirframeComponent Class Reference
APMAirframeComponent Class Reference
#include <APMAirframeComponent.h>
Public Member Functions
APMAirframeComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
QStringList setupCompleteChangedTriggerList () const final
QString name () const final
QString description () const final
QString iconResource () const final
bool requiresSetup () const final
bool setupComplete () const final
QUrl setupSource () const final
QUrl summaryQmlSource () const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 7 of file APMAirframeComponent.h.
Constructor & Destructor Documentation
APMAirframeComponent()
APMAirframeComponent::APMAirframeComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr) explicit
Definition at line 5 of file APMAirframeComponent.cc.
References ParameterManager::defaultComponentId, ParameterManager::getParameter(), ParameterManager::parameterExists(), Vehicle::parameterManager(), and Vehicle::vehicleType().
Member Function Documentation
description()
QString APMAirframeComponent::description (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 17 of file APMAirframeComponent.h.
iconResource()
QString APMAirframeComponent::iconResource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 18 of file APMAirframeComponent.h.
name()
QString APMAirframeComponent::name (void) const inline final virtual
Implements VehicleComponent.
Definition at line 16 of file APMAirframeComponent.h.
Referenced by APMAutoPilotPlugin::prerequisiteSetup().
requiresSetup()
bool APMAirframeComponent::requiresSetup (void) const inline final virtual
Implements VehicleComponent.
Definition at line 19 of file APMAirframeComponent.h.
setupComplete()
bool APMAirframeComponent::setupComplete (void) const final virtual
Implements VehicleComponent.
Definition at line 31 of file APMAirframeComponent.cc.
Referenced by APMAutoPilotPlugin::prerequisiteSetup().
setupCompleteChangedTriggerList()
QStringList APMAirframeComponent::setupCompleteChangedTriggerList () const final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 20 of file APMAirframeComponent.cc.
setupSource()
QUrl APMAirframeComponent::setupSource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 21 of file APMAirframeComponent.h.
summaryQmlSource()
QUrl APMAirframeComponent::summaryQmlSource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 22 of file APMAirframeComponent.h.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMAirframeComponent.h
src/AutoPilotPlugins/APM/APMAirframeComponent.cc