QGroundControl: FirmwarePluginManager Class Reference
FirmwarePluginManager Class Reference
FirmwarePluginManager is a singleton which is used to return the correct FirmwarePlugin for a MAV_AUTOPILOT type.
#include <FirmwarePluginManager.h>
Public Member Functions
FirmwarePluginManager (QObject *parent=nullptr)
~FirmwarePluginManager ()
Destructor for the FirmwarePluginManager class.
QList< QGCMAVLink::FirmwareClass_t > supportedFirmwareClasses ()
Returns list of firmwares which are supported by the system.
QList< QGCMAVLink::VehicleClass_t > supportedVehicleClasses (QGCMAVLink::FirmwareClass_t firmwareClass)
Returns the list of supported vehicle types for the specified firmware.
FirmwarePlugin * firmwarePluginForAutopilot (MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType)
Static Public Member Functions
static FirmwarePluginManager * instance ()
Detailed Description
FirmwarePluginManager is a singleton which is used to return the correct FirmwarePlugin for a MAV_AUTOPILOT type.
Definition at line 14 of file FirmwarePluginManager.h.
Constructor & Destructor Documentation
FirmwarePluginManager()
FirmwarePluginManager::FirmwarePluginManager (QObject * parent = nullptr) explicit
Constructs an FirmwarePluginManager object.
Parameters
parent The parent QObject.
Definition at line 12 of file FirmwarePluginManager.cc.
~FirmwarePluginManager()
FirmwarePluginManager::~FirmwarePluginManager ()
Destructor for the FirmwarePluginManager class.
Definition at line 18 of file FirmwarePluginManager.cc.
Member Function Documentation
firmwarePluginForAutopilot()
FirmwarePlugin * FirmwarePluginManager::firmwarePluginForAutopilot (MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType)
Returns appropriate plugin for autopilot type.
Parameters
firmwareType Type of firmwware to return plugin for.
vehicleType Vehicle type to return plugin for.
Returns
Singleton FirmwarePlugin instance for the specified MAV_AUTOPILOT.
Definition at line 59 of file FirmwarePluginManager.cc.
References FirmwarePluginFactory::firmwarePluginForAutopilot().
Referenced by Vehicle::_offlineFirmwareTypeSettingChanged(), MissionCommandTree::getCommandsForCategory(), and MissionCommandTree::MissionCommandTree().
instance()
FirmwarePluginManager * FirmwarePluginManager::instance () static
Gets the singleton instance of FirmwarePluginManager.
Returns
The singleton instance.
Definition at line 23 of file FirmwarePluginManager.cc.
Referenced by Vehicle::_offlineFirmwareTypeSettingChanged(), QGroundControlQmlGlobal::apmFirmwareSupported(), MissionCommandTree::getCommandsForCategory(), MissionCommandTree::MissionCommandTree(), QGroundControlQmlGlobal::px4ProFirmwareSupported(), QGroundControlQmlGlobal::singleFirmwareSupport(), and QGroundControlQmlGlobal::singleVehicleSupport().
supportedFirmwareClasses()
QList< QGCMAVLink::FirmwareClass_t > FirmwarePluginManager::supportedFirmwareClasses ()
Returns list of firmwares which are supported by the system.
Definition at line 28 of file FirmwarePluginManager.cc.
References QGCMAVLink::FirmwareClassGeneric, FirmwarePluginFactoryRegister::instance(), and FirmwarePluginFactoryRegister::pluginFactories().
Referenced by QGroundControlQmlGlobal::apmFirmwareSupported(), MissionCommandTree::MissionCommandTree(), QGroundControlQmlGlobal::px4ProFirmwareSupported(), and QGroundControlQmlGlobal::singleFirmwareSupport().
supportedVehicleClasses()
QList< QGCMAVLink::VehicleClass_t > FirmwarePluginManager::supportedVehicleClasses (QGCMAVLink::FirmwareClass_t firmwareClass)
Returns the list of supported vehicle types for the specified firmware.
Definition at line 41 of file FirmwarePluginManager.cc.
References QGCMAVLink::allVehicleClasses(), QGCMAVLink::FirmwareClassGeneric, FirmwarePluginFactory::supportedVehicleClasses(), and QGCMAVLinkTypes::VehicleClassGeneric.
Referenced by QGroundControlQmlGlobal::singleVehicleSupport().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/FirmwarePluginManager.h
src/FirmwarePlugin/FirmwarePluginManager.cc