QGroundControl: QGCCacheWorker Class Reference
QGCCacheWorker Class Reference
#include <QGCTileCacheWorker.h>
Public Slots
bool enqueueTask (QGCMapTask *task)
void stop ()
Signals
void updateTotals (quint32 totaltiles, quint64 totalsize, quint32 defaulttiles, quint64 defaultsize)
Public Member Functions
QGCCacheWorker (QObject *parent=nullptr)
~QGCCacheWorker ()
void setDatabaseFile (const QString &path)
Protected Member Functions
void run () final
Detailed Description
Definition at line 15 of file QGCTileCacheWorker.h.
Constructor & Destructor Documentation
QGCCacheWorker()
QGCCacheWorker::QGCCacheWorker (QObject * parent = nullptr) explicit
Definition at line 14 of file QGCTileCacheWorker.cpp.
~QGCCacheWorker()
QGCCacheWorker::~QGCCacheWorker ()
Definition at line 21 of file QGCTileCacheWorker.cpp.
References stop().
Member Function Documentation
enqueueTask
bool QGCCacheWorker::enqueueTask (QGCMapTask * task) slot
Definition at line 43 of file QGCTileCacheWorker.cpp.
References QGCMapTask::setError(), QGCMapTask::taskInit, and QGCMapTask::type().
Referenced by QGCMapEngine::addTask().
run()
void QGCCacheWorker::run () final protected
Definition at line 64 of file QGCTileCacheWorker.cpp.
setDatabaseFile()
void QGCCacheWorker::setDatabaseFile (const QString & path) inline
Definition at line 23 of file QGCTileCacheWorker.h.
Referenced by QGCMapEngine::init().
stop
void QGCCacheWorker::stop () slot
Definition at line 30 of file QGCTileCacheWorker.cpp.
Referenced by ~QGCCacheWorker(), and QGCMapEngine::~QGCMapEngine().
updateTotals
void QGCCacheWorker::updateTotals (quint32 totaltiles, quint64 totalsize, quint32 defaulttiles, quint64 defaultsize) signal
Referenced by QGCMapEngine::init().
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGCTileCacheWorker.h
src/QtLocationPlugin/QGCTileCacheWorker.cpp