QGroundControl: ActuatorOutputs::ActuatorOutputChannel Class Reference
ActuatorOutputs::ActuatorOutputChannel Class Reference
#include <ActuatorOutputs.h>
Signals
void configInstancesChanged ()
Public Member Functions
ActuatorOutputChannel (QObject *parent, const QString &label, int paramIndex, QmlObjectListModel &channelConfigs, ParameterManager *parameterManager, std::function< void(Fact *)> factAddedCb)
QString label READ label CONSTANT (QmlObjectListModel *configInstances READ configInstances NOTIFY configInstancesChanged) const QString &label() const
QmlObjectListModel * configInstances ()
Detailed Description
Definition at line 112 of file ActuatorOutputs.h.
Constructor & Destructor Documentation
ActuatorOutputChannel()
ActuatorOutputChannel::ActuatorOutputChannel (QObject * parent, const QString & label, int paramIndex, QmlObjectListModel & channelConfigs, ParameterManager * parameterManager, std::function< void(Fact *)> factAddedCb)
Definition at line 11 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), Parameter::Bitset, Parameter::BoolTrueIfPositive, QmlObjectListModel::count(), ParameterManager::defaultComponentId, ParameterManager::getParameter(), ActuatorOutputs::ChannelConfig::parameter(), ParameterManager::parameterExists(), and QmlObjectListModel::value().
Member Function Documentation
configInstances()
QmlObjectListModel * ActuatorOutputs::ActuatorOutputChannel::configInstances () inline
Definition at line 124 of file ActuatorOutputs.h.
Referenced by ActuatorOutputs::ActuatorOutput::forEachOutputFunction().
configInstancesChanged
void ActuatorOutputs::ActuatorOutputChannel::configInstancesChanged () signal
CONSTANT()
QString label READ label ActuatorOutputs::ActuatorOutputChannel::CONSTANT (QmlObjectListModel *configInstances READ configInstances NOTIFY configInstancesChanged) const & inline
Definition at line 119 of file ActuatorOutputs.h.
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/ActuatorOutputs.h
src/Vehicle/Actuators/ActuatorOutputs.cc