QGroundControl: TrajectoryPoints Class Reference
TrajectoryPoints Class Reference
#include <TrajectoryPoints.h>
Public Slots
void clear (void)
Signals
void pointAdded (QGeoCoordinate coordinate)
void updateLastPoint (QGeoCoordinate coordinate)
void pointsCleared (void)
Public Member Functions
TrajectoryPoints (Vehicle *vehicle, QObject *parent=nullptr)
QVariantList list (void) const
void start (void)
void stop (void)
Detailed Description
Definition at line 10 of file TrajectoryPoints.h.
Constructor & Destructor Documentation
TrajectoryPoints()
TrajectoryPoints::TrajectoryPoints (Vehicle * vehicle, QObject * parent = nullptr)
Definition at line 4 of file TrajectoryPoints.cc.
Member Function Documentation
clear
void TrajectoryPoints::clear (void) slot
Definition at line 56 of file TrajectoryPoints.cc.
References pointsCleared().
Referenced by start().
list()
QVariantList TrajectoryPoints::list (void) const inline
Definition at line 18 of file TrajectoryPoints.h.
pointAdded
void TrajectoryPoints::pointAdded (QGeoCoordinate coordinate) signal
pointsCleared
void TrajectoryPoints::pointsCleared (void) signal
Referenced by clear().
start()
void TrajectoryPoints::start (void)
Definition at line 45 of file TrajectoryPoints.cc.
References clear(), and Vehicle::coordinateChanged().
stop()
void TrajectoryPoints::stop (void)
Definition at line 51 of file TrajectoryPoints.cc.
References Vehicle::coordinateChanged().
updateLastPoint
void TrajectoryPoints::updateLastPoint (QGeoCoordinate coordinate) signal
The documentation for this class was generated from the following files:
src/Vehicle/TrajectoryPoints.h
src/Vehicle/TrajectoryPoints.cc