QGroundControl: MAVLinkEventManager Class Reference
MAVLinkEventManager Class Reference
#include <MAVLinkEventManager.h>
Signals
void statusTextMessageFromEvent (uint8_t compid, int severity, const QString &text, const QString &description)
Public Member Functions
MAVLinkEventManager (Vehicle *vehicle)
~MAVLinkEventManager () override
HealthAndArmingCheckReport * healthAndArmingCheckReport () const
void handleEventMessage (const mavlink_message_t &message)
void setMetadata (uint8_t compid, const QString &metadataJsonFileName)
bool healthAndArmingChecksSupported (uint8_t compid) const
Detailed Description
Owns per-component EventHandler instances and drives the Health & Arming Check report.
Definition at line 23 of file MAVLinkEventManager.h.
Constructor & Destructor Documentation
MAVLinkEventManager()
MAVLinkEventManager::MAVLinkEventManager (Vehicle * vehicle) explicit
Definition at line 18 of file MAVLinkEventManager.cc.
References Vehicle::flightModeChanged().
~MAVLinkEventManager()
MAVLinkEventManager::~MAVLinkEventManager () override default
Member Function Documentation
handleEventMessage()
void MAVLinkEventManager::handleEventMessage (const mavlink_message_t & message)
Route MAVLink event protocol messages (EVENT, CURRENT_EVENT_SEQUENCE, RESPONSE_EVENT_ERROR) to the EventHandler for the source component.
Definition at line 41 of file MAVLinkEventManager.cc.
References EventHandler::handleEvents().
healthAndArmingCheckReport()
HealthAndArmingCheckReport * MAVLinkEventManager::healthAndArmingCheckReport () const
Definition at line 36 of file MAVLinkEventManager.cc.
healthAndArmingChecksSupported()
bool MAVLinkEventManager::healthAndArmingChecksSupported (uint8_t compid) const
True if an EventHandler already exists for this component and it reports the health_and_arming_check protocol as supported.
Definition at line 46 of file MAVLinkEventManager.cc.
setMetadata()
void MAVLinkEventManager::setMetadata (uint8_t compid, const QString & metadataJsonFileName)
Load event metadata JSON for a component, then compute takeoff and mission mode groups and publish them to the report.
Definition at line 55 of file MAVLinkEventManager.cc.
References Vehicle::firmwarePlugin(), EventHandler::getModeGroup(), Vehicle::missionFlightMode(), FirmwarePlugin::setFlightMode(), EventHandler::setMetadata(), and FirmwarePlugin::takeOffFlightMode().
statusTextMessageFromEvent
void MAVLinkEventManager::statusTextMessageFromEvent (uint8_t compid, int severity, const QString & text, const QString & description) signal
Emitted for "default"-group events that should render as a status-text message. Vehicle routes this into its StatusTextHandler.
The documentation for this class was generated from the following files:
src/MAVLink/LibEvents/MAVLinkEventManager.h
src/MAVLink/LibEvents/MAVLinkEventManager.cc