QGroundControl: FactMetaData Class Reference
FactMetaData Class Reference
#include <FactMetaData.h>
Public Types
enum ValueType_t {
valueTypeUint8 , valueTypeInt8 , valueTypeUint16 , valueTypeInt16 ,
valueTypeUint32 , valueTypeInt32 , valueTypeUint64 , valueTypeInt64 ,
valueTypeFloat , valueTypeDouble , valueTypeString , valueTypeBool ,
valueTypeElapsedTimeInSeconds , valueTypeCustom
}
typedef QVariant(* Translator) (const QVariant &from)
typedef QString(* CustomCookedValidator) (const QVariant &cookedValue)
typedef QHash< QString, FactMetaData * > NameToMetaDataMap_t
typedef QMap< QString, QString > DefineMap_t
Public Member Functions
FactMetaData (QObject *parent=nullptr)
FactMetaData (ValueType_t type, QObject *parent=nullptr)
FactMetaData (ValueType_t type, const QString &name, QObject *parent=nullptr)
FactMetaData (const FactMetaData &other, QObject *parent=nullptr)
~FactMetaData ()
const FactMetaData & operator= (const FactMetaData &other)
int decimalPlaces () const
QVariant rawDefaultValue () const
QVariant cookedDefaultValue () const
bool defaultValueAvailable () const
QStringList bitmaskStrings () const
QVariantList bitmaskValues () const
QStringList enumStrings () const
QVariantList enumValues () const
QString category () const
QString group () const
QString longDescription () const
QVariant rawMax () const
QVariant cookedMax () const
bool maxIsDefaultForType () const
QVariant rawMin () const
QVariant cookedMin () const
bool minIsDefaultForType () const
QVariant rawUserMin () const
QVariant rawUserMax () const
QVariant cookedUserMin () const
QVariant cookedUserMax () const
QString name () const
QString label () const
QString shortDescription () const
ValueType_t type () const
QString rawUnits () const
QString cookedUnits () const
bool vehicleRebootRequired () const
bool qgcRebootRequired () const
bool hasControl () const
bool readOnly () const
bool writeOnly () const
bool volatileValue () const
double rawIncrement () const
double cookedIncrement () const
Translator rawTranslator () const
Translator cookedTranslator () const
void addBitmaskInfo (const QString &name, const QVariant &value)
Used to add new values to the bitmask lists after the meta data has been loaded.
void addEnumInfo (const QString &name, const QVariant &value)
Used to add new values to the enum lists after the meta data has been loaded.
void removeEnumInfo (const QVariant &value)
Used to remove values from the enum lists after the meta data has been loaded.
void setDecimalPlaces (int decimalPlaces)
void setRawDefaultValue (const QVariant &rawDefaultValue)
void setBitmaskInfo (const QStringList &strings, const QVariantList &values)
void setEnumInfo (const QStringList &strings, const QVariantList &values)
void setCategory (const QString &category)
void setGroup (const QString &group)
void setLongDescription (const QString &longDescription)
void setRawMax (const QVariant &rawMax)
void setRawMin (const QVariant &rawMin)
void setRawUserMin (const QVariant &rawUserMin)
void setRawUserMax (const QVariant &rawUserMax)
void setName (const QString &name)
void setLabel (const QString &label)
void setShortDescription (const QString &shortDescription)
void setRawUnits (const QString &rawUnits)
void setVehicleRebootRequired (bool rebootRequired)
void setQGCRebootRequired (bool rebootRequired)
void setRawIncrement (double increment)
void setHasControl (bool bValue)
void setReadOnly (bool bValue)
void setWriteOnly (bool bValue)
void setVolatileValue (bool bValue)
void setTranslators (Translator rawTranslator_, Translator cookedTranslator_)
void setBuiltInTranslator ()
Set the translators to the standard built in versions.
bool convertAndValidateRaw (const QVariant &rawValue, bool convertOnly, QVariant &typedValue, QString &errorString) const
bool convertAndValidateCooked (const QVariant &cookedValue, bool convertOnly, QVariant &typedValue, QString &errorString) const
Same as convertAndValidateRaw except for cookedValue input.
bool clampValue (const QVariant &cookedValue, QVariant &typedValue) const
void setCustomCookedValidator (CustomCookedValidator customValidator)
Static Public Member Functions
static QMap< QString, FactMetaData * > createMapFromJsonFile (const QString &jsonFilename, QObject *metaDataParent)
static QMap< QString, FactMetaData * > createMapFromJsonArray (const QJsonArray &jsonArray, const DefineMap_t &defineMap, QObject *metaDataParent)
static FactMetaData * createFromJsonObject (const QJsonObject &json, const QMap< QString, QString > &defineMap, QObject *metaDataParent)
static QVariant metersToAppSettingsHorizontalDistanceUnits (const QVariant &meters)
Converts from meters to the user specified horizontal distance unit.
static QVariant appSettingsHorizontalDistanceUnitsToMeters (const QVariant &distance)
Converts from user specified horizontal distance unit to meters.
static QString appSettingsHorizontalDistanceUnitsString ()
Returns the string for horizontal distance units which has configued by user.
static QVariant metersToAppSettingsVerticalDistanceUnits (const QVariant &meters)
Converts from meters to the user specified vertical distance unit.
static QVariant appSettingsVerticalDistanceUnitsToMeters (const QVariant &distance)
Converts from user specified vertical distance unit to meters.
static QString appSettingsVerticalDistanceUnitsString ()
Returns the string for vertical distance units which has configued by user.
static QVariant gramsToAppSettingsWeightUnits (const QVariant &grams)
Converts from grams to the user specified weight unit.
static QVariant appSettingsWeightUnitsToGrams (const QVariant &weight)
Converts from user specified weight unit to grams.
static QString appSettingsWeightUnitsString ()
Returns the string for weight units which has configued by user.
static QVariant squareMetersToAppSettingsAreaUnits (const QVariant &squareMeters)
Converts from meters to the user specified distance unit.
static QVariant appSettingsAreaUnitsToSquareMeters (const QVariant &area)
Converts from user specified distance unit to meters.
static QString appSettingsAreaUnitsString ()
Returns the string for distance units which has configued by user.
static QVariant metersSecondToAppSettingsSpeedUnits (const QVariant &metersSecond)
Converts from meters/second to the user specified speed unit.
static QVariant appSettingsSpeedUnitsToMetersSecond (const QVariant &speed)
Converts from user specified speed unit to meters/second.
static QString appSettingsSpeedUnitsString ()
Returns the string for speed units which has configued by user.
static const QString defaultCategory ()
static const QString defaultGroup ()
static QStringList splitTranslatedList (const QString &translatedList)
static ValueType_t stringToType (const QString &typeString, bool &unknownType)
static QString typeToString (ValueType_t type)
static size_t typeToSize (ValueType_t type)
static QVariant minForType (ValueType_t type)
static QVariant maxForType (ValueType_t type)
Static Public Attributes
static constexpr int kDefaultDecimalPlaces = 3
Default value for decimal places if not specified/known.
static constexpr int kUnknownDecimalPlaces = -1
Number of decimal places to specify is not known.
static constexpr const char * kDefaultCategory = QT_TRANSLATE_NOOP("FactMetaData", "Other")
static constexpr const char * kDefaultGroup = QT_TRANSLATE_NOOP("FactMetaData", "Misc")
static constexpr const char * qgcFileType = "FactMetaData"
Friends
class SettingsManager
Detailed Description
Holds the meta data associated with a Fact. This is kept in a separate object from the Fact itself since you may have multiple instances of the same Fact. But there is only ever one FactMetaData instance or each Fact.
Definition at line 14 of file FactMetaData.h.
Member Typedef Documentation
CustomCookedValidator
typedef QString(* FactMetaData::CustomCookedValidator) (const QVariant &cookedValue)
Definition at line 44 of file FactMetaData.h.
DefineMap_t
typedef QMap<QString, QString> FactMetaData::DefineMap_t
Definition at line 54 of file FactMetaData.h.
NameToMetaDataMap_t
typedef QHash<QString , FactMetaData*> FactMetaData::NameToMetaDataMap_t
Definition at line 46 of file FactMetaData.h.
Translator
typedef QVariant(* FactMetaData::Translator) (const QVariant &from)
Definition at line 40 of file FactMetaData.h.
Member Enumeration Documentation
ValueType_t
enum FactMetaData::ValueType_t
Enumerator
valueTypeUint8
valueTypeInt8
valueTypeUint16
valueTypeInt16
valueTypeUint32
valueTypeInt32
valueTypeUint64
valueTypeInt64
valueTypeFloat
valueTypeDouble
valueTypeString
valueTypeBool
valueTypeElapsedTimeInSeconds
valueTypeCustom
Definition at line 22 of file FactMetaData.h.
Constructor & Destructor Documentation
FactMetaData() [1/4]
FactMetaData::FactMetaData (QObject * parent = nullptr) explicit
Definition at line 56 of file FactMetaData.cc.
FactMetaData() [2/4]
FactMetaData::FactMetaData (ValueType_t type, QObject * parent = nullptr) explicit
Definition at line 62 of file FactMetaData.cc.
FactMetaData() [3/4]
FactMetaData::FactMetaData (ValueType_t type, const QString & name, QObject * parent = nullptr) explicit
Definition at line 76 of file FactMetaData.cc.
FactMetaData() [4/4]
FactMetaData::FactMetaData (const FactMetaData & other, QObject * parent = nullptr) explicit
Definition at line 69 of file FactMetaData.cc.
~FactMetaData()
FactMetaData::~FactMetaData ()
Definition at line 84 of file FactMetaData.cc.
Member Function Documentation
addBitmaskInfo()
void FactMetaData::addBitmaskInfo (const QString & name, const QVariant & value)
Used to add new values to the bitmask lists after the meta data has been loaded.
Definition at line 572 of file FactMetaData.cc.
References name().
Referenced by createFromJsonObject().
addEnumInfo()
void FactMetaData::addEnumInfo (const QString & name, const QVariant & value)
Used to add new values to the enum lists after the meta data has been loaded.
Definition at line 590 of file FactMetaData.cc.
References name().
Referenced by createFromJsonObject().
appSettingsAreaUnitsString()
QString FactMetaData::appSettingsAreaUnitsString () static
Returns the string for distance units which has configued by user.
Definition at line 1066 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsAreaUnitsString().
appSettingsAreaUnitsToSquareMeters()
QVariant FactMetaData::appSettingsAreaUnitsToSquareMeters (const QVariant & area) static
Converts from user specified distance unit to meters.
Definition at line 1056 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsAreaUnitsToSquareMeters().
appSettingsHorizontalDistanceUnitsString()
QString FactMetaData::appSettingsHorizontalDistanceUnitsString () static
Returns the string for horizontal distance units which has configued by user.
Definition at line 1016 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsHorizontalDistanceUnitsString(), and Vehicle::guidedModeGotoLocation().
appSettingsHorizontalDistanceUnitsToMeters()
QVariant FactMetaData::appSettingsHorizontalDistanceUnitsToMeters (const QVariant & distance) static
Converts from user specified horizontal distance unit to meters.
Definition at line 996 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsHorizontalDistanceUnitsToMeters().
appSettingsSpeedUnitsString()
QString FactMetaData::appSettingsSpeedUnitsString () static
Returns the string for speed units which has configued by user.
Definition at line 1114 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsSpeedUnitsString().
appSettingsSpeedUnitsToMetersSecond()
QVariant FactMetaData::appSettingsSpeedUnitsToMetersSecond (const QVariant & speed) static
Converts from user specified speed unit to meters/second.
Definition at line 1104 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsSpeedUnitsToMetersSecond().
appSettingsVerticalDistanceUnitsString()
QString FactMetaData::appSettingsVerticalDistanceUnitsString () static
Returns the string for vertical distance units which has configued by user.
Definition at line 1026 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsVerticalDistanceUnitsString().
appSettingsVerticalDistanceUnitsToMeters()
QVariant FactMetaData::appSettingsVerticalDistanceUnitsToMeters (const QVariant & distance) static
Converts from user specified vertical distance unit to meters.
Definition at line 1006 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsVerticalDistanceUnitsToMeters().
appSettingsWeightUnitsString()
QString FactMetaData::appSettingsWeightUnitsString () static
Returns the string for weight units which has configued by user.
Definition at line 1036 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsWeightUnitsString().
appSettingsWeightUnitsToGrams()
QVariant FactMetaData::appSettingsWeightUnitsToGrams (const QVariant & weight) static
Converts from user specified weight unit to grams.
Definition at line 1085 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::appSettingsWeightUnitsToGrams().
bitmaskStrings()
QStringList FactMetaData::bitmaskStrings () const inline
Definition at line 119 of file FactMetaData.h.
bitmaskValues()
QVariantList FactMetaData::bitmaskValues () const inline
Definition at line 120 of file FactMetaData.h.
category()
QString FactMetaData::category () const inline
Definition at line 123 of file FactMetaData.h.
Referenced by PX4ParameterMetaData::_postProcessMetaData(), and setCategory().
clampValue()
bool FactMetaData::clampValue (const QVariant & cookedValue, QVariant & typedValue) const
Converts the specified cooked value and clamps it (max/min)
Parameters
cookedValue Value to convert, can be string
typeValue Converted value, correctly typed and clamped
Returns
false: Convertion failed
Definition at line 497 of file FactMetaData.cc.
References type(), valueTypeBool, valueTypeCustom, valueTypeDouble, valueTypeElapsedTimeInSeconds, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeString, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
convertAndValidateCooked()
bool FactMetaData::convertAndValidateCooked (const QVariant & cookedValue, bool convertOnly, QVariant & typedValue, QString & errorString) const
Same as convertAndValidateRaw except for cookedValue input.
Definition at line 409 of file FactMetaData.cc.
References cookedMax(), cookedMin(), errorString, type(), valueTypeBool, valueTypeCustom, valueTypeDouble, valueTypeElapsedTimeInSeconds, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeString, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
convertAndValidateRaw()
bool FactMetaData::convertAndValidateRaw (const QVariant & rawValue, bool convertOnly, QVariant & typedValue, QString & errorString) const
Converts the specified raw value, validating against meta data
Parameters
rawValue Value to convert, can be string
convertOnly true: convert to correct type only, do not validate against meta data
typeValue Converted value, correctly typed
errorString Error string if convert fails, values are cooked values since user visible
Returns
false: Convert failed, errorString set
Definition at line 328 of file FactMetaData.cc.
References errorString, rawMax(), rawMin(), type(), valueTypeBool, valueTypeCustom, valueTypeDouble, valueTypeElapsedTimeInSeconds, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeString, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
Referenced by createFromJsonObject(), ParameterMetaData::setBitmaskFromPairs(), ParameterMetaData::setEnumFromPairs(), ParameterMetaData::setRawConvertedValue(), and SettingsFact::SettingsFact().
cookedDefaultValue()
QVariant FactMetaData::cookedDefaultValue () const inline
Definition at line 117 of file FactMetaData.h.
References rawDefaultValue().
cookedIncrement()
double FactMetaData::cookedIncrement () const
Definition at line 1124 of file FactMetaData.cc.
References rawIncrement().
cookedMax()
QVariant FactMetaData::cookedMax () const
Definition at line 1469 of file FactMetaData.cc.
Referenced by convertAndValidateCooked().
cookedMin()
QVariant FactMetaData::cookedMin () const
Definition at line 1475 of file FactMetaData.cc.
Referenced by convertAndValidateCooked().
cookedTranslator()
Translator FactMetaData::cookedTranslator () const inline
Definition at line 155 of file FactMetaData.h.
cookedUnits()
QString FactMetaData::cookedUnits () const inline
Definition at line 141 of file FactMetaData.h.
cookedUserMax()
QVariant FactMetaData::cookedUserMax () const
Definition at line 1604 of file FactMetaData.cc.
cookedUserMin()
QVariant FactMetaData::cookedUserMin () const
Definition at line 1595 of file FactMetaData.cc.
createFromJsonObject()
FactMetaData * FactMetaData::createFromJsonObject (const QJsonObject & json, const QMap< QString, QString > & defineMap, QObject * metaDataParent) static
Definition at line 1171 of file FactMetaData.cc.
References addBitmaskInfo(), addEnumInfo(), convertAndValidateRaw(), errorString, kUnknownDecimalPlaces, name(), qgcRebootRequired(), setCategory(), setDecimalPlaces(), setGroup(), setHasControl(), setLabel(), setLongDescription(), setQGCRebootRequired(), setRawDefaultValue(), setRawIncrement(), setRawMax(), setRawMin(), setRawUnits(), setRawUserMax(), setRawUserMin(), setReadOnly(), setShortDescription(), setVehicleRebootRequired(), setVolatileValue(), stringToType(), type(), JsonHelper::validateKeys(), valueTypeDouble, valueTypeFloat, valueTypeUint32, and volatileValue().
Referenced by createMapFromJsonArray(), PX4ParameterMetaData::parseParameterJson(), and CompInfoParam::setJson().
createMapFromJsonArray()
QMap< QString, FactMetaData * > FactMetaData::createMapFromJsonArray (const QJsonArray & jsonArray, const DefineMap_t & defineMap, QObject * metaDataParent) static
Definition at line 1447 of file FactMetaData.cc.
References createFromJsonObject(), and name().
Referenced by FactGroup::_loadFromJsonArray(), and createMapFromJsonFile().
createMapFromJsonFile()
QMap< QString, FactMetaData * > FactMetaData::createMapFromJsonFile (const QString & jsonFilename, QObject * metaDataParent) static
Definition at line 1419 of file FactMetaData.cc.
References createMapFromJsonArray(), errorString, JsonHelper::openInternalQGCJsonFile(), qgcFileType, and JsonHelper::validateKeys().
Referenced by CameraSection::CameraSection(), GeoFenceController::GeoFenceController(), MissionSettingsItem::MissionSettingsItem(), SettingsGroup::SettingsGroup(), and SpeedSection::SpeedSection().
decimalPlaces()
int FactMetaData::decimalPlaces () const
Definition at line 1129 of file FactMetaData.cc.
References kDefaultDecimalPlaces, kUnknownDecimalPlaces, and rawIncrement().
Referenced by setDecimalPlaces().
defaultCategory()
static const QString FactMetaData::defaultCategory () inline static
Definition at line 108 of file FactMetaData.h.
References kDefaultCategory.
Referenced by PX4ParameterMetaData::_postProcessMetaData().
defaultGroup()
static const QString FactMetaData::defaultGroup () inline static
Definition at line 109 of file FactMetaData.h.
References kDefaultGroup.
defaultValueAvailable()
bool FactMetaData::defaultValueAvailable () const inline
Definition at line 118 of file FactMetaData.h.
Referenced by SettingsFact::SettingsFact().
enumStrings()
QStringList FactMetaData::enumStrings () const inline
Definition at line 121 of file FactMetaData.h.
enumValues()
QVariantList FactMetaData::enumValues () const inline
Definition at line 122 of file FactMetaData.h.
gramsToAppSettingsWeightUnits()
QVariant FactMetaData::gramsToAppSettingsWeightUnits (const QVariant & grams) static
Converts from grams to the user specified weight unit.
Definition at line 1076 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::gramsToAppSettingsWeightUnits().
group()
QString FactMetaData::group () const inline
Definition at line 124 of file FactMetaData.h.
Referenced by setGroup().
hasControl()
bool FactMetaData::hasControl () const inline
Definition at line 144 of file FactMetaData.h.
label()
QString FactMetaData::label () const inline
Definition at line 137 of file FactMetaData.h.
Referenced by SettingsGroup::_createSettingsFact(), and setLabel().
longDescription()
QString FactMetaData::longDescription () const inline
Definition at line 125 of file FactMetaData.h.
Referenced by PX4ParameterMetaData::_postProcessMetaData(), and setLongDescription().
maxForType()
QVariant FactMetaData::maxForType (ValueType_t type) static
Definition at line 294 of file FactMetaData.cc.
References type(), valueTypeBool, valueTypeCustom, valueTypeDouble, valueTypeElapsedTimeInSeconds, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeString, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
maxIsDefaultForType()
bool FactMetaData::maxIsDefaultForType () const inline
Definition at line 128 of file FactMetaData.h.
metersSecondToAppSettingsSpeedUnits()
QVariant FactMetaData::metersSecondToAppSettingsSpeedUnits (const QVariant & metersSecond) static
Converts from meters/second to the user specified speed unit.
Definition at line 1094 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::metersSecondToAppSettingsSpeedUnits().
metersToAppSettingsHorizontalDistanceUnits()
QVariant FactMetaData::metersToAppSettingsHorizontalDistanceUnits (const QVariant & meters) static
Converts from meters to the user specified horizontal distance unit.
Definition at line 976 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::CONSTANT(), and Vehicle::guidedModeGotoLocation().
metersToAppSettingsVerticalDistanceUnits()
QVariant FactMetaData::metersToAppSettingsVerticalDistanceUnits (const QVariant & meters) static
Converts from meters to the user specified vertical distance unit.
Definition at line 986 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::metersToAppSettingsVerticalDistanceUnits().
minForType()
QVariant FactMetaData::minForType (ValueType_t type) static
Definition at line 259 of file FactMetaData.cc.
References type(), valueTypeBool, valueTypeCustom, valueTypeDouble, valueTypeElapsedTimeInSeconds, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeString, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
minIsDefaultForType()
bool FactMetaData::minIsDefaultForType () const inline
Definition at line 131 of file FactMetaData.h.
name()
QString FactMetaData::name () const inline
Definition at line 136 of file FactMetaData.h.
Referenced by addBitmaskInfo(), addEnumInfo(), ArduSubFirmwarePlugin::adjustMetaData(), createFromJsonObject(), createMapFromJsonArray(), PX4ParameterMetaData::parseParameterJson(), ParameterMetaData::setBitmaskFromPairs(), ParameterMetaData::setEnumFromPairs(), CompInfoParam::setJson(), setName(), ParameterMetaData::setRawConvertedValue(), setRawMax(), setRawMin(), setRawUserMax(), and setRawUserMin().
operator=()
const FactMetaData & FactMetaData::operator= (const FactMetaData & other)
Definition at line 89 of file FactMetaData.cc.
qgcRebootRequired()
bool FactMetaData::qgcRebootRequired () const inline
Definition at line 143 of file FactMetaData.h.
Referenced by createFromJsonObject().
rawDefaultValue()
QVariant FactMetaData::rawDefaultValue () const
Definition at line 123 of file FactMetaData.cc.
Referenced by cookedDefaultValue(), setRawDefaultValue(), and SettingsFact::SettingsFact().
rawIncrement()
double FactMetaData::rawIncrement () const inline
Amount to increment value when used in controls such as spin button or slider with detents. NaN for no increment available.
Definition at line 151 of file FactMetaData.h.
Referenced by cookedIncrement(), and decimalPlaces().
rawMax()
QVariant FactMetaData::rawMax () const inline
Definition at line 126 of file FactMetaData.h.
Referenced by convertAndValidateRaw(), and setRawMax().
rawMin()
QVariant FactMetaData::rawMin () const inline
Definition at line 129 of file FactMetaData.h.
Referenced by convertAndValidateRaw(), setRawMin(), and VTOLLandingComplexItem::VTOLLandingComplexItem().
rawTranslator()
Translator FactMetaData::rawTranslator () const inline
Definition at line 154 of file FactMetaData.h.
rawUnits()
QString FactMetaData::rawUnits () const inline
Definition at line 140 of file FactMetaData.h.
Referenced by setRawUnits().
rawUserMax()
QVariant FactMetaData::rawUserMax () const inline
Definition at line 133 of file FactMetaData.h.
Referenced by setRawUserMax().
rawUserMin()
QVariant FactMetaData::rawUserMin () const inline
Definition at line 132 of file FactMetaData.h.
Referenced by setRawUserMin().
readOnly()
bool FactMetaData::readOnly () const inline
Definition at line 145 of file FactMetaData.h.
removeEnumInfo()
void FactMetaData::removeEnumInfo (const QVariant & value)
Used to remove values from the enum lists after the meta data has been loaded.
Definition at line 596 of file FactMetaData.cc.
setBitmaskInfo()
void FactMetaData::setBitmaskInfo (const QStringList & strings, const QVariantList & values)
Definition at line 560 of file FactMetaData.cc.
References setBuiltInTranslator().
Referenced by ParameterMetaData::setBitmaskFromPairs().
setBuiltInTranslator()
void FactMetaData::setBuiltInTranslator ()
Set the translators to the standard built in versions.
Definition at line 614 of file FactMetaData.cc.
References setTranslators().
Referenced by setBitmaskInfo(), setEnumInfo(), and setRawUnits().
setCategory()
void FactMetaData::setCategory (const QString & category) inline
Definition at line 170 of file FactMetaData.h.
References category().
Referenced by APMParameterMetaData::_createDefaultMetaData(), PX4ParameterMetaData::_postProcessMetaData(), and createFromJsonObject().
setCustomCookedValidator()
void FactMetaData::setCustomCookedValidator (CustomCookedValidator customValidator) inline
Sets a custom cooked validator function for this metadata. The custom validator will be called prior to the standard validator when convertAndValidateCooked is called.
Definition at line 213 of file FactMetaData.h.
setDecimalPlaces()
void FactMetaData::setDecimalPlaces (int decimalPlaces) inline
Definition at line 166 of file FactMetaData.h.
References decimalPlaces().
Referenced by APMParameterMetaData::_postProcessMetaData(), createFromJsonObject(), and Mixer::ChannelConfig::instantiate().
setEnumInfo()
void FactMetaData::setEnumInfo (const QStringList & strings, const QVariantList & values)
Definition at line 578 of file FactMetaData.cc.
References setBuiltInTranslator().
Referenced by Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), UnitsSettings::areaUnits(), UnitsSettings::horizontalDistanceUnits(), AppSettings::qLocaleLanguage(), ParameterMetaData::setEnumFromPairs(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setGroup()
void FactMetaData::setGroup (const QString & group) inline
Definition at line 171 of file FactMetaData.h.
References group().
Referenced by APMParameterMetaData::_createDefaultMetaData(), and createFromJsonObject().
setHasControl()
void FactMetaData::setHasControl (bool bValue) inline
Definition at line 184 of file FactMetaData.h.
Referenced by createFromJsonObject().
setLabel()
void FactMetaData::setLabel (const QString & label) inline
Definition at line 178 of file FactMetaData.h.
References label().
Referenced by UnitsSettings::areaUnits(), createFromJsonObject(), UnitsSettings::horizontalDistanceUnits(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setLongDescription()
void FactMetaData::setLongDescription (const QString & longDescription) inline
Definition at line 172 of file FactMetaData.h.
References longDescription().
Referenced by PX4ParameterMetaData::_postProcessMetaData(), and createFromJsonObject().
setName()
void FactMetaData::setName (const QString & name) inline
Definition at line 177 of file FactMetaData.h.
References name().
Referenced by UnitsSettings::areaUnits(), UnitsSettings::horizontalDistanceUnits(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setQGCRebootRequired()
void FactMetaData::setQGCRebootRequired (bool rebootRequired) inline
Definition at line 182 of file FactMetaData.h.
Referenced by UnitsSettings::areaUnits(), createFromJsonObject(), UnitsSettings::horizontalDistanceUnits(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setRawDefaultValue()
void FactMetaData::setRawDefaultValue (const QVariant & rawDefaultValue)
Definition at line 133 of file FactMetaData.cc.
References rawDefaultValue(), and valueTypeString.
Referenced by UnitsSettings::areaUnits(), createFromJsonObject(), UnitsSettings::horizontalDistanceUnits(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setRawIncrement()
void FactMetaData::setRawIncrement (double increment) inline
Definition at line 183 of file FactMetaData.h.
Referenced by createFromJsonObject().
setRawMax()
void FactMetaData::setRawMax (const QVariant & rawMax)
Definition at line 160 of file FactMetaData.cc.
References name(), rawMax(), and type().
Referenced by APMParameterMetaData::_lookupMetaData(), and createFromJsonObject().
setRawMin()
void FactMetaData::setRawMin (const QVariant & rawMin)
Definition at line 143 of file FactMetaData.cc.
References name(), rawMin(), and type().
Referenced by APMParameterMetaData::_lookupMetaData(), and createFromJsonObject().
setRawUnits()
void FactMetaData::setRawUnits (const QString & rawUnits)
Definition at line 831 of file FactMetaData.cc.
References rawUnits(), and setBuiltInTranslator().
Referenced by createFromJsonObject().
setRawUserMax()
void FactMetaData::setRawUserMax (const QVariant & rawUserMax)
Definition at line 190 of file FactMetaData.cc.
References name(), rawUserMax(), and type().
Referenced by APMParameterMetaData::_lookupMetaData(), and createFromJsonObject().
setRawUserMin()
void FactMetaData::setRawUserMin (const QVariant & rawUserMin)
Definition at line 177 of file FactMetaData.cc.
References name(), rawUserMin(), and type().
Referenced by APMParameterMetaData::_lookupMetaData(), and createFromJsonObject().
setReadOnly()
void FactMetaData::setReadOnly (bool bValue) inline
Definition at line 185 of file FactMetaData.h.
Referenced by PX4ParameterMetaData::_postProcessMetaData(), createFromJsonObject(), and Mixer::ChannelConfig::instantiate().
setShortDescription()
void FactMetaData::setShortDescription (const QString & shortDescription) inline
Definition at line 179 of file FactMetaData.h.
References shortDescription().
Referenced by PX4ParameterMetaData::_postProcessMetaData(), ArduSubFirmwarePlugin::adjustMetaData(), UnitsSettings::areaUnits(), createFromJsonObject(), UnitsSettings::horizontalDistanceUnits(), UnitsSettings::speedUnits(), UnitsSettings::temperatureUnits(), UnitsSettings::verticalDistanceUnits(), and UnitsSettings::weightUnits().
setTranslators()
void FactMetaData::setTranslators (Translator rawTranslator_, Translator cookedTranslator_)
Definition at line 608 of file FactMetaData.cc.
Referenced by setBuiltInTranslator().
setVehicleRebootRequired()
void FactMetaData::setVehicleRebootRequired (bool rebootRequired) inline
Definition at line 181 of file FactMetaData.h.
Referenced by createFromJsonObject().
setVolatileValue()
void FactMetaData::setVolatileValue (bool bValue)
Definition at line 1481 of file FactMetaData.cc.
Referenced by createFromJsonObject().
setWriteOnly()
void FactMetaData::setWriteOnly (bool bValue) inline
Definition at line 186 of file FactMetaData.h.
shortDescription()
QString FactMetaData::shortDescription () const inline
Definition at line 138 of file FactMetaData.h.
Referenced by PX4ParameterMetaData::_postProcessMetaData(), and setShortDescription().
splitTranslatedList()
QStringList FactMetaData::splitTranslatedList (const QString & translatedList) static
Definition at line 1489 of file FactMetaData.cc.
Referenced by MissionCommandUIInfo::loadJsonInfo().
squareMetersToAppSettingsAreaUnits()
QVariant FactMetaData::squareMetersToAppSettingsAreaUnits (const QVariant & squareMeters) static
Converts from meters to the user specified distance unit.
Definition at line 1046 of file FactMetaData.cc.
Referenced by QmlUnitsConversion::squareMetersToAppSettingsAreaUnits().
stringToType()
FactMetaData::ValueType_t FactMetaData::stringToType (const QString & typeString, bool & unknownType) static
Definition at line 839 of file FactMetaData.cc.
References valueTypeDouble.
Referenced by createFromJsonObject().
type()
ValueType_t FactMetaData::type () const inline
Definition at line 139 of file FactMetaData.h.
Referenced by APMParameterMetaData::_postProcessMetaData(), clampValue(), convertAndValidateCooked(), convertAndValidateRaw(), createFromJsonObject(), maxForType(), minForType(), setRawMax(), setRawMin(), setRawUserMax(), setRawUserMin(), typeToSize(), and typeToString().
typeToSize()
size_t FactMetaData::typeToSize (ValueType_t type) static
Definition at line 865 of file FactMetaData.cc.
References MAVLINK_MSG_PARAM_EXT_SET_FIELD_PARAM_VALUE_LEN, type(), valueTypeCustom, valueTypeDouble, valueTypeFloat, valueTypeInt16, valueTypeInt32, valueTypeInt64, valueTypeInt8, valueTypeUint16, valueTypeUint32, valueTypeUint64, and valueTypeUint8.
typeToString()
QString FactMetaData::typeToString (ValueType_t type) static
Definition at line 854 of file FactMetaData.cc.
References type().
vehicleRebootRequired()
bool FactMetaData::vehicleRebootRequired () const inline
Definition at line 142 of file FactMetaData.h.
volatileValue()
bool FactMetaData::volatileValue () const inline
Definition at line 147 of file FactMetaData.h.
Referenced by PX4ParameterMetaData::_postProcessMetaData(), and createFromJsonObject().
writeOnly()
bool FactMetaData::writeOnly () const inline
Definition at line 146 of file FactMetaData.h.
Friends And Related Symbol Documentation
SettingsManager
friend class SettingsManager friend
Definition at line 19 of file FactMetaData.h.
Member Data Documentation
kDefaultCategory
constexpr const char* FactMetaData::kDefaultCategory = QT_TRANSLATE_NOOP("FactMetaData", "Other") static constexpr
Definition at line 225 of file FactMetaData.h.
Referenced by defaultCategory().
kDefaultDecimalPlaces
constexpr int FactMetaData::kDefaultDecimalPlaces = 3 static constexpr
Default value for decimal places if not specified/known.
Definition at line 215 of file FactMetaData.h.
Referenced by decimalPlaces().
kDefaultGroup
constexpr const char* FactMetaData::kDefaultGroup = QT_TRANSLATE_NOOP("FactMetaData", "Misc") static constexpr
Definition at line 226 of file FactMetaData.h.
Referenced by defaultGroup().
kUnknownDecimalPlaces
constexpr int FactMetaData::kUnknownDecimalPlaces = -1 static constexpr
Number of decimal places to specify is not known.
Definition at line 216 of file FactMetaData.h.
Referenced by createFromJsonObject(), decimalPlaces(), and MissionCommandUIInfo::loadJsonInfo().
qgcFileType
constexpr const char* FactMetaData::qgcFileType = "FactMetaData" static constexpr
Definition at line 227 of file FactMetaData.h.
Referenced by JsonHelper::_addDefaultLocKeys(), and createMapFromJsonFile().
The documentation for this class was generated from the following files:
src/FactSystem/FactMetaData.h
src/FactSystem/FactMetaData.cc