QGroundControl: SimulatedPosition Class Reference
SimulatedPosition Class Reference
#include <SimulatedPosition.h>
Public Slots
void startUpdates () final
void stopUpdates () final
void requestUpdate (int timeout=5000) final
Public Member Functions
SimulatedPosition (QObject *parent=nullptr)
~SimulatedPosition ()
QGeoPositionInfo lastKnownPosition (bool) const final
PositioningMethods supportedPositioningMethods () const final
int minimumUpdateInterval () const final
Error error () const final
Detailed Description
Definition at line 11 of file SimulatedPosition.h.
Constructor & Destructor Documentation
SimulatedPosition()
SimulatedPosition::SimulatedPosition (QObject * parent = nullptr)
Definition at line 12 of file SimulatedPosition.cc.
References MultiVehicleManager::vehicleAdded().
~SimulatedPosition()
SimulatedPosition::~SimulatedPosition ()
Definition at line 30 of file SimulatedPosition.cc.
Member Function Documentation
error()
Error SimulatedPosition::error () const inline final
Definition at line 23 of file SimulatedPosition.h.
lastKnownPosition()
QGeoPositionInfo SimulatedPosition::lastKnownPosition (bool) const inline final
Definition at line 19 of file SimulatedPosition.h.
minimumUpdateInterval()
int SimulatedPosition::minimumUpdateInterval () const inline final
Definition at line 22 of file SimulatedPosition.h.
Referenced by startUpdates().
requestUpdate
void SimulatedPosition::requestUpdate (int timeout = 5000) final slot
Definition at line 45 of file SimulatedPosition.cc.
startUpdates
void SimulatedPosition::startUpdates () final slot
Definition at line 35 of file SimulatedPosition.cc.
References minimumUpdateInterval().
stopUpdates
void SimulatedPosition::stopUpdates () final slot
Definition at line 40 of file SimulatedPosition.cc.
supportedPositioningMethods()
PositioningMethods SimulatedPosition::supportedPositioningMethods () const inline final
Definition at line 21 of file SimulatedPosition.h.
The documentation for this class was generated from the following files:
src/PositionManager/SimulatedPosition.h
src/PositionManager/SimulatedPosition.cc