QGroundControl: Joystick Class Reference
Joystick Class Reference abstract
#include <Joystick.h>
Classes
struct AxisCalibration_t
Public Types
enum ButtonEvent_t { ButtonEventUpTransition , ButtonEventDownTransition , ButtonEventRepeat , ButtonEventNone }
enum AxisFunction_t {
rollFunction , pitchFunction , yawFunction , throttleFunction ,
pitchExtensionFunction , rollExtensionFunction , aux1ExtensionFunction , aux2ExtensionFunction ,
aux3ExtensionFunction , aux4ExtensionFunction , aux5ExtensionFunction , aux6ExtensionFunction ,
maxAxisFunction
}
enum HatDirection : quint8 {
HatCentered = 0x00 , HatUp = 0x01 , HatRight = 0x02 , HatDown = 0x04 ,
HatLeft = 0x08 , HatRightUp = HatRight | HatUp , HatRightDown = HatRight | HatDown , HatLeftUp = HatLeft | HatUp ,
HatLeftDown = HatLeft | HatDown
}
Standard gamepad hat/D-pad directions.
enum GamepadButton {
ButtonA = 0 , ButtonB = 1 , ButtonX = 2 , ButtonY = 3 ,
ButtonBack = 4 , ButtonGuide = 5 , ButtonStart = 6 , ButtonLeftStick = 7 ,
ButtonRightStick = 8 , ButtonLeftShoulder = 9 , ButtonRightShoulder = 10 , ButtonDPadUp = 11 ,
ButtonDPadDown = 12 , ButtonDPadLeft = 13 , ButtonDPadRight = 14
}
Standard gamepad button indices.
enum GamepadAxis {
AxisLeftX = 0 , AxisLeftY = 1 , AxisRightX = 2 , AxisRightY = 3 ,
AxisTriggerLeft = 4 , AxisTriggerRight = 5
}
Standard gamepad axis indices.
Signals
void buttonActionsChanged ()
void assignableActionsChanged ()
void playerIndexChanged ()
void batteryStateChanged ()
void connectionStateChanged (const QString &newState)
void linkedGroupChanged ()
void axisValues (float roll, float pitch, float yaw, float throttle)
void startContinuousZoom (int direction)
void stopContinuousZoom ()
void stepZoom (int direction)
void stepCamera (int direction)
void stepStream (int direction)
void triggerCamera ()
void startVideoRecord ()
void stopVideoRecord ()
void toggleVideoRecord ()
void gimbalPitchStart (int direction)
void gimbalYawStart (int direction)
void gimbalPitchStop ()
void gimbalYawStop ()
void centerGimbal ()
void gimbalYawLock (bool lock)
void setArmed (bool arm)
void setVtolInFwdFlight (bool set)
void setFlightMode (const QString &flightMode)
void emergencyStop ()
void gripperAction (QGCMAVLink::GripperActions gripperAction)
void landingGearDeploy ()
void landingGearRetract ()
void motorInterlock (bool enable)
void unknownAction (const QString &action)
void vehicleJoystickData (float roll, float pitch, float yaw, float throttle, uint16_t buttonsLow, uint16_t buttonsHigh, float gimbalPitch, float gimbalYaw)
void rawChannelValuesChanged (QVector< int > channelValues)
Signalled during PollingForConfiguration.
void rawButtonPressedChanged (int index, bool pressed)
Signalled during PollingForConfiguration.
void gyroscopeDataUpdated (const QVector3D &data)
void accelerometerDataUpdated (const QVector3D &data)
void touchpadEvent (int touchpad, int finger, bool down, float x, float y, float pressure)
void mappingRemapped ()
void updateComplete ()
Public Member Functions
QString name READ name CONSTANT (JoystickSettings *settings READ settings CONSTANT) 1(int axisCount READ axisCount CONSTANT) 1(int buttonCount READ buttonCount CONSTANT) 1(bool requiresCalibration READ requiresCalibration CONSTANT) 1(bool hasRumble READ hasRumble CONSTANT) 1(bool hasRumbleTriggers READ hasRumbleTriggers CONSTANT) 1(bool hasLED READ hasLED CONSTANT) 1(QString guid READ guid CONSTANT) 1(quint16 vendorId READ vendorId CONSTANT) 1(quint16 productId READ productId CONSTANT) 1(QString serial READ serial CONSTANT) 1(QString deviceType READ deviceType CONSTANT) 1(int playerIndex READ playerIndex WRITE setPlayerIndex NOTIFY playerIndexChanged) 1(int batteryPercent READ batteryPercent NOTIFY batteryStateChanged) 1(QString powerState READ powerState NOTIFY batteryStateChanged) 1(bool isGamepad READ isGamepad CONSTANT) 1(QString gamepadType READ gamepadType CONSTANT) 1(QString path READ path CONSTANT) 1(bool isVirtual READ isVirtual CONSTANT) 1(quint16 firmwareVersion READ firmwareVersion CONSTANT) 1(QString connectionType READ connectionType CONSTANT) 1(int ballCount READ ballCount CONSTANT) 1(const QmlObjectListModel *assignableActions READ assignableActions NOTIFY assignableActionsChanged) 1(QString disabledActionName READ disabledActionName CONSTANT) 1(QStringList assignableActionTitles READ assignableActionTitles NOTIFY assignableActionsChanged) 1(QStringList buttonActions READ buttonActions NOTIFY buttonActionsChanged) 1(QString buttonActionNone READ buttonActionNone CONSTANT) 1(QString linkedGroupId READ linkedGroupId WRITE setLinkedGroupId NOTIFY linkedGroupChanged) 1(QString linkedGroupRole READ linkedGroupRole WRITE setLinkedGroupRole NOTIFY linkedGroupChanged) Joystick(const QString &name
virtual ~Joystick ()
void setButtonRepeat (int button, bool repeat)
bool getButtonRepeat (int button)
void setButtonAction (int button, const QString &action)
QString getButtonAction (int button) const
JoystickSettings * settings ()
QString name () const
int buttonCount () const
int axisCount () const
virtual bool requiresCalibration () const
virtual bool hasRumble () const
virtual bool hasRumbleTriggers () const
virtual bool hasLED () const
virtual QString guid () const
virtual quint16 vendorId () const
virtual quint16 productId () const
virtual QString serial () const
virtual QString deviceType () const
virtual int playerIndex () const
virtual void setPlayerIndex (int index)
virtual int batteryPercent () const
virtual QString powerState () const
virtual bool isGamepad () const
virtual QString gamepadType () const
virtual QString path () const
virtual bool isVirtual () const
virtual quint16 firmwareVersion () const
virtual QString connectionType () const
virtual int ballCount () const
virtual void rumble (quint16 lowFreq, quint16 highFreq, quint32 durationMs)
virtual void rumbleTriggers (quint16 left, quint16 right, quint32 durationMs)
virtual void setLED (quint8 red, quint8 green, quint8 blue)
virtual QString axisLabel (int axis) const
virtual QString buttonLabel (int button) const
virtual QString getMapping () const
virtual bool addMapping (const QString &mapping)
virtual bool hasGyroscope () const
virtual bool hasAccelerometer () const
virtual bool setGyroscopeEnabled (bool enabled)
virtual bool setAccelerometerEnabled (bool enabled)
virtual QVector3D gyroscopeData () const
virtual QVector3D accelerometerData () const
virtual float gyroscopeDataRate () const
virtual float accelerometerDataRate () const
virtual int touchpadCount () const
virtual int touchpadFingerCount (int touchpad) const
virtual QVariantMap getTouchpadFinger (int touchpad, int finger) const
virtual QVariantMap getBall (int ball) const
virtual bool sendEffect (const QByteArray &data)
virtual QVariantMap getAxisBinding (int axis) const
virtual QVariantMap getButtonBinding (int button) const
virtual bool hasButton (int button) const
virtual bool hasAxis (int axis) const
virtual QString realGamepadType () const
virtual QString buttonLabelForType (int button) const
virtual bool hasHaptic () const
virtual int hapticEffectsCount () const
virtual bool hapticRumbleSupported () const
virtual bool hapticRumbleInit ()
virtual bool hapticRumblePlay (float strength, quint32 durationMs)
virtual void hapticRumbleStop ()
virtual QString getMappingForGUID (const QString &guid) const
virtual bool setVirtualAxis (int axis, int value)
virtual bool setVirtualButton (int button, bool down)
virtual bool setVirtualHat (int hat, quint8 value)
virtual bool setVirtualBall (int ball, int dx, int dy)
virtual bool setVirtualTouchpad (int touchpad, int finger, bool down, float x, float y, float pressure)
virtual bool sendVirtualSensorData (int sensorType, float x, float y, float z)
virtual bool hasMonoLED () const
virtual bool hasRGBLED () const
virtual bool hasPlayerLED () const
virtual QString connectionState () const
virtual QVariantMap getAxisInitialState (int axis) const
virtual bool setMapping (const QString &mapping)
QStringList buttonActions () const
QString buttonActionNone () const
QString disabledActionName () const
const QmlObjectListModel * assignableActions () const
QStringList assignableActionTitles () const
QString linkedGroupId () const
HOTAS/Multi-device linking (devices with same groupId act as single joystick)
void setLinkedGroupId (const QString &groupId)
QString linkedGroupRole () const
void setLinkedGroupRole (const QString &role)
void setAxisCalibration (int axis, const AxisCalibration_t &calibration)
Joystick::AxisCalibration_t getAxisCalibration (int axis) const
RemoteControlCalibrationController::StickFunction mapAxisFunctionToRCCStickFunction (AxisFunction_t axisFunction) const
AxisFunction_t mapRCCStickFunctionToAxisFunction (RemoteControlCalibrationController::StickFunction stickFunction) const
void setFunctionForChannel (RemoteControlCalibrationController::StickFunction stickFunction, int channel)
int getChannelForFunction (RemoteControlCalibrationController::StickFunction stickFunction) const
void startConfiguration ()
Tells the joystick that the configuration UI is being displayed so it can do any special processing required.
void stopConfiguration ()
Tells the joystick that the configuration UI is being closed so it can do any special processing required.
void stop ()
Static Public Member Functions
static QString axisFunctionToString (AxisFunction_t function)
Public Attributes
QString name READ name int axisCount
QString name READ name int int buttonCount
QString name READ name int int int hatCount
QString name READ name int int int QObject * parent = nullptr)
Static Public Attributes
static constexpr int AxisMin = -32768
static constexpr int AxisMax = 32767
Protected Attributes
QString _name
int _axisCount = 0
int _buttonCount = 0
int _hatCount = 0
Friends
class JoystickManager
class JoystickConfigController
Detailed Description
Definition at line 55 of file Joystick.h.
Member Enumeration Documentation
AxisFunction_t
enum Joystick::AxisFunction_t
Enumerator
rollFunction
pitchFunction
yawFunction
throttleFunction
pitchExtensionFunction
rollExtensionFunction
aux1ExtensionFunction
aux2ExtensionFunction
aux3ExtensionFunction
aux4ExtensionFunction
aux5ExtensionFunction
aux6ExtensionFunction
maxAxisFunction
Definition at line 130 of file Joystick.h.
ButtonEvent_t
enum Joystick::ButtonEvent_t
Enumerator
ButtonEventUpTransition
ButtonEventDownTransition
ButtonEventRepeat
ButtonEventNone
Definition at line 107 of file Joystick.h.
GamepadAxis
enum Joystick::GamepadAxis
Standard gamepad axis indices.
Enumerator
AxisLeftX
AxisLeftY
AxisRightX
AxisRightY
AxisTriggerLeft
AxisTriggerRight
Definition at line 182 of file Joystick.h.
GamepadButton
enum Joystick::GamepadButton
Standard gamepad button indices.
Enumerator
ButtonA
ButtonB
ButtonX
ButtonY
ButtonBack
ButtonGuide
ButtonStart
ButtonLeftStick
ButtonRightStick
ButtonLeftShoulder
ButtonRightShoulder
ButtonDPadUp
ButtonDPadDown
ButtonDPadLeft
ButtonDPadRight
Definition at line 162 of file Joystick.h.
HatDirection
enum Joystick::HatDirection : quint8
Standard gamepad hat/D-pad directions.
Enumerator
HatCentered
HatUp
HatRight
HatDown
HatLeft
HatRightUp
HatRightDown
HatLeftUp
HatLeftDown
Definition at line 148 of file Joystick.h.
Constructor & Destructor Documentation
~Joystick()
Joystick::~Joystick () virtual
Definition at line 146 of file Joystick.cc.
References QmlObjectListModel::clearAndDeleteContents().
Member Function Documentation
accelerometerData()
virtual QVector3D Joystick::accelerometerData () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 236 of file Joystick.h.
accelerometerDataRate()
virtual float Joystick::accelerometerDataRate () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 238 of file Joystick.h.
accelerometerDataUpdated
void Joystick::accelerometerDataUpdated (const QVector3D & data) signal
Referenced by JoystickSDL::updateCachedAccelData().
addMapping()
virtual bool Joystick::addMapping (const QString & mapping) inline virtual
Reimplemented in JoystickSDL.
Definition at line 228 of file Joystick.h.
assignableActions()
const QmlObjectListModel * Joystick::assignableActions () const inline
Definition at line 307 of file Joystick.h.
assignableActionsChanged
void Joystick::assignableActionsChanged () signal
assignableActionTitles()
QStringList Joystick::assignableActionTitles () const inline
Definition at line 308 of file Joystick.h.
axisCount()
int Joystick::axisCount () const inline
Definition at line 200 of file Joystick.h.
References _axisCount.
axisFunctionToString()
QString Joystick::axisFunctionToString (AxisFunction_t function) static
Definition at line 1602 of file Joystick.cc.
References aux1ExtensionFunction, aux2ExtensionFunction, aux3ExtensionFunction, aux4ExtensionFunction, aux5ExtensionFunction, aux6ExtensionFunction, maxAxisFunction, pitchExtensionFunction, pitchFunction, rollExtensionFunction, rollFunction, throttleFunction, and yawFunction.
axisLabel()
virtual QString Joystick::axisLabel (int axis) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 225 of file Joystick.h.
axisValues
void Joystick::axisValues (float roll, float pitch, float yaw, float throttle) signal
ballCount()
virtual int Joystick::ballCount () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 220 of file Joystick.h.
batteryPercent()
virtual int Joystick::batteryPercent () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 212 of file Joystick.h.
batteryStateChanged
void Joystick::batteryStateChanged () signal
buttonActionNone()
QString Joystick::buttonActionNone () const inline
Definition at line 305 of file Joystick.h.
buttonActions()
QStringList Joystick::buttonActions () const
Definition at line 1392 of file Joystick.cc.
buttonActionsChanged
void Joystick::buttonActionsChanged () signal
Referenced by setButtonAction().
buttonCount()
int Joystick::buttonCount () const inline
Definition at line 199 of file Joystick.h.
buttonLabel()
virtual QString Joystick::buttonLabel (int button) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 226 of file Joystick.h.
buttonLabelForType()
virtual QString Joystick::buttonLabelForType (int button) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 265 of file Joystick.h.
centerGimbal
void Joystick::centerGimbal () signal
connectionState()
virtual QString Joystick::connectionState () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 296 of file Joystick.h.
connectionStateChanged
void Joystick::connectionStateChanged (const QString & newState) signal
Referenced by JoystickSDL::checkConnectionStateChanged().
connectionType()
virtual QString Joystick::connectionType () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 219 of file Joystick.h.
CONSTANT()
QString name READ name Joystick::CONSTANT (JoystickSettings *settings READ settings CONSTANT) const &
deviceType()
virtual QString Joystick::deviceType () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 209 of file Joystick.h.
disabledActionName()
QString Joystick::disabledActionName () const inline
Definition at line 306 of file Joystick.h.
emergencyStop
void Joystick::emergencyStop () signal
firmwareVersion()
virtual quint16 Joystick::firmwareVersion () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 218 of file Joystick.h.
gamepadType()
virtual QString Joystick::gamepadType () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 215 of file Joystick.h.
getAxisBinding()
virtual QVariantMap Joystick::getAxisBinding (int axis) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 254 of file Joystick.h.
getAxisCalibration()
Joystick::AxisCalibration_t Joystick::getAxisCalibration (int axis) const
Definition at line 1191 of file Joystick.cc.
getAxisInitialState()
virtual QVariantMap Joystick::getAxisInitialState (int axis) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 299 of file Joystick.h.
getBall()
virtual QVariantMap Joystick::getBall (int ball) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 248 of file Joystick.h.
getButtonAction()
QString Joystick::getButtonAction (int button) const
Definition at line 1381 of file Joystick.cc.
getButtonBinding()
virtual QVariantMap Joystick::getButtonBinding (int button) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 255 of file Joystick.h.
getButtonRepeat()
bool Joystick::getButtonRepeat (int button)
Definition at line 1324 of file Joystick.cc.
getChannelForFunction()
int Joystick::getChannelForFunction (RemoteControlCalibrationController::StickFunction stickFunction) const
Definition at line 1299 of file Joystick.cc.
References mapRCCStickFunctionToAxisFunction().
getMapping()
virtual QString Joystick::getMapping () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 227 of file Joystick.h.
getMappingForGUID()
virtual QString Joystick::getMappingForGUID (const QString & guid) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 276 of file Joystick.h.
References guid().
getTouchpadFinger()
virtual QVariantMap Joystick::getTouchpadFinger (int touchpad, int finger) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 243 of file Joystick.h.
gimbalPitchStart
void Joystick::gimbalPitchStart (int direction) signal
gimbalPitchStop
void Joystick::gimbalPitchStop () signal
gimbalYawLock
void Joystick::gimbalYawLock (bool lock) signal
gimbalYawStart
void Joystick::gimbalYawStart (int direction) signal
gimbalYawStop
void Joystick::gimbalYawStop () signal
gripperAction
void Joystick::gripperAction (QGCMAVLink::GripperActions gripperAction) signal
guid()
virtual QString Joystick::guid () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 205 of file Joystick.h.
Referenced by getMappingForGUID().
gyroscopeData()
virtual QVector3D Joystick::gyroscopeData () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 235 of file Joystick.h.
gyroscopeDataRate()
virtual float Joystick::gyroscopeDataRate () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 237 of file Joystick.h.
gyroscopeDataUpdated
void Joystick::gyroscopeDataUpdated (const QVector3D & data) signal
Referenced by JoystickSDL::updateCachedGyroData().
hapticEffectsCount()
virtual int Joystick::hapticEffectsCount () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 269 of file Joystick.h.
hapticRumbleInit()
virtual bool Joystick::hapticRumbleInit () inline virtual
Reimplemented in JoystickSDL.
Definition at line 271 of file Joystick.h.
hapticRumblePlay()
virtual bool Joystick::hapticRumblePlay (float strength, quint32 durationMs) inline virtual
Reimplemented in JoystickSDL.
Definition at line 272 of file Joystick.h.
hapticRumbleStop()
virtual void Joystick::hapticRumbleStop () inline virtual
Reimplemented in JoystickSDL.
Definition at line 273 of file Joystick.h.
hapticRumbleSupported()
virtual bool Joystick::hapticRumbleSupported () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 270 of file Joystick.h.
hasAccelerometer()
virtual bool Joystick::hasAccelerometer () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 232 of file Joystick.h.
hasAxis()
virtual bool Joystick::hasAxis (int axis) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 259 of file Joystick.h.
hasButton()
virtual bool Joystick::hasButton (int button) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 258 of file Joystick.h.
hasGyroscope()
virtual bool Joystick::hasGyroscope () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 231 of file Joystick.h.
hasHaptic()
virtual bool Joystick::hasHaptic () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 268 of file Joystick.h.
hasLED()
virtual bool Joystick::hasLED () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 204 of file Joystick.h.
hasMonoLED()
virtual bool Joystick::hasMonoLED () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 291 of file Joystick.h.
hasPlayerLED()
virtual bool Joystick::hasPlayerLED () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 293 of file Joystick.h.
hasRGBLED()
virtual bool Joystick::hasRGBLED () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 292 of file Joystick.h.
hasRumble()
virtual bool Joystick::hasRumble () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 202 of file Joystick.h.
hasRumbleTriggers()
virtual bool Joystick::hasRumbleTriggers () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 203 of file Joystick.h.
isGamepad()
virtual bool Joystick::isGamepad () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 214 of file Joystick.h.
isVirtual()
virtual bool Joystick::isVirtual () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 217 of file Joystick.h.
landingGearDeploy
void Joystick::landingGearDeploy () signal
landingGearRetract
void Joystick::landingGearRetract () signal
linkedGroupChanged
void Joystick::linkedGroupChanged () signal
Referenced by setLinkedGroupId(), and setLinkedGroupRole().
linkedGroupId()
QString Joystick::linkedGroupId () const inline
HOTAS/Multi-device linking (devices with same groupId act as single joystick)
Definition at line 311 of file Joystick.h.
linkedGroupRole()
QString Joystick::linkedGroupRole () const inline
Definition at line 313 of file Joystick.h.
mapAxisFunctionToRCCStickFunction()
RemoteControlCalibrationController::StickFunction Joystick::mapAxisFunctionToRCCStickFunction (Joystick::AxisFunction_t axisFunction) const
Definition at line 1228 of file Joystick.cc.
References aux1ExtensionFunction, aux2ExtensionFunction, aux3ExtensionFunction, aux4ExtensionFunction, aux5ExtensionFunction, aux6ExtensionFunction, maxAxisFunction, pitchExtensionFunction, pitchFunction, rollExtensionFunction, rollFunction, throttleFunction, and yawFunction.
mappingRemapped
void Joystick::mappingRemapped () signal
mapRCCStickFunctionToAxisFunction()
Joystick::AxisFunction_t Joystick::mapRCCStickFunctionToAxisFunction (RemoteControlCalibrationController::StickFunction stickFunction) const
Definition at line 1261 of file Joystick.cc.
References aux1ExtensionFunction, aux2ExtensionFunction, aux3ExtensionFunction, aux4ExtensionFunction, aux5ExtensionFunction, aux6ExtensionFunction, maxAxisFunction, pitchExtensionFunction, pitchFunction, rollExtensionFunction, rollFunction, throttleFunction, and yawFunction.
Referenced by getChannelForFunction(), and setFunctionForChannel().
motorInterlock
void Joystick::motorInterlock (bool enable) signal
name()
QString Joystick::name () const inline
Definition at line 198 of file Joystick.h.
References _name.
Referenced by JoystickSDL::discover(), and JoystickConfigController::start().
path()
virtual QString Joystick::path () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 216 of file Joystick.h.
playerIndex()
virtual int Joystick::playerIndex () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 210 of file Joystick.h.
playerIndexChanged
void Joystick::playerIndexChanged () signal
Referenced by JoystickSDL::setPlayerIndex().
powerState()
virtual QString Joystick::powerState () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 213 of file Joystick.h.
productId()
virtual quint16 Joystick::productId () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 207 of file Joystick.h.
rawButtonPressedChanged
void Joystick::rawButtonPressedChanged (int index, bool pressed) signal
Signalled during PollingForConfiguration.
rawChannelValuesChanged
void Joystick::rawChannelValuesChanged (QVector< int > channelValues) signal
Signalled during PollingForConfiguration.
realGamepadType()
virtual QString Joystick::realGamepadType () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 262 of file Joystick.h.
requiresCalibration()
virtual bool Joystick::requiresCalibration () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 201 of file Joystick.h.
rumble()
virtual void Joystick::rumble (quint16 lowFreq, quint16 highFreq, quint32 durationMs) inline virtual
Reimplemented in JoystickSDL.
Definition at line 222 of file Joystick.h.
rumbleTriggers()
virtual void Joystick::rumbleTriggers (quint16 left, quint16 right, quint32 durationMs) inline virtual
Reimplemented in JoystickSDL.
Definition at line 223 of file Joystick.h.
sendEffect()
virtual bool Joystick::sendEffect (const QByteArray & data) inline virtual
Reimplemented in JoystickSDL.
Definition at line 251 of file Joystick.h.
sendVirtualSensorData()
virtual bool Joystick::sendVirtualSensorData (int sensorType, float x, float y, float z) inline virtual
Reimplemented in JoystickSDL.
Definition at line 286 of file Joystick.h.
serial()
virtual QString Joystick::serial () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 208 of file Joystick.h.
setAccelerometerEnabled()
virtual bool Joystick::setAccelerometerEnabled (bool enabled) inline virtual
Reimplemented in JoystickSDL.
Definition at line 234 of file Joystick.h.
setArmed
void Joystick::setArmed (bool arm) signal
setAxisCalibration()
void Joystick::setAxisCalibration (int axis, const AxisCalibration_t & calibration)
Definition at line 1182 of file Joystick.cc.
setButtonAction()
void Joystick::setButtonAction (int button, const QString & action)
Definition at line 1333 of file Joystick.cc.
References buttonActionsChanged(), QmlObjectListModel::get(), settings(), and SettingsGroup::settingsGroup().
setButtonRepeat()
void Joystick::setButtonRepeat (int button, bool repeat)
Definition at line 1304 of file Joystick.cc.
References settings(), and SettingsGroup::settingsGroup().
setFlightMode
void Joystick::setFlightMode (const QString & flightMode) signal
setFunctionForChannel()
void Joystick::setFunctionForChannel (RemoteControlCalibrationController::StickFunction stickFunction, int channel)
Definition at line 1294 of file Joystick.cc.
References mapRCCStickFunctionToAxisFunction().
setGyroscopeEnabled()
virtual bool Joystick::setGyroscopeEnabled (bool enabled) inline virtual
Reimplemented in JoystickSDL.
Definition at line 233 of file Joystick.h.
setLED()
virtual void Joystick::setLED (quint8 red, quint8 green, quint8 blue) inline virtual
Reimplemented in JoystickSDL.
Definition at line 224 of file Joystick.h.
setLinkedGroupId()
void Joystick::setLinkedGroupId (const QString & groupId)
Definition at line 1673 of file Joystick.cc.
References _name, linkedGroupChanged(), and settings().
setLinkedGroupRole()
void Joystick::setLinkedGroupRole (const QString & role)
Definition at line 1694 of file Joystick.cc.
References _name, linkedGroupChanged(), and settings().
setMapping()
virtual bool Joystick::setMapping (const QString & mapping) inline virtual
Reimplemented in JoystickSDL.
Definition at line 302 of file Joystick.h.
setPlayerIndex()
virtual void Joystick::setPlayerIndex (int index) inline virtual
Reimplemented in JoystickSDL.
Definition at line 211 of file Joystick.h.
settings()
JoystickSettings * Joystick::settings () inline
Definition at line 197 of file Joystick.h.
Referenced by setButtonAction(), setButtonRepeat(), setLinkedGroupId(), and setLinkedGroupRole().
setVirtualAxis()
virtual bool Joystick::setVirtualAxis (int axis, int value) inline virtual
Reimplemented in JoystickSDL.
Definition at line 279 of file Joystick.h.
setVirtualBall()
virtual bool Joystick::setVirtualBall (int ball, int dx, int dy) inline virtual
Reimplemented in JoystickSDL.
Definition at line 282 of file Joystick.h.
setVirtualButton()
virtual bool Joystick::setVirtualButton (int button, bool down) inline virtual
Reimplemented in JoystickSDL.
Definition at line 280 of file Joystick.h.
setVirtualHat()
virtual bool Joystick::setVirtualHat (int hat, quint8 value) inline virtual
Reimplemented in JoystickSDL.
Definition at line 281 of file Joystick.h.
setVirtualTouchpad()
virtual bool Joystick::setVirtualTouchpad (int touchpad, int finger, bool down, float x, float y, float pressure) inline virtual
Reimplemented in JoystickSDL.
Definition at line 283 of file Joystick.h.
setVtolInFwdFlight
void Joystick::setVtolInFwdFlight (bool set) signal
startConfiguration()
void Joystick::startConfiguration ()
Tells the joystick that the configuration UI is being displayed so it can do any special processing required.
Definition at line 1635 of file Joystick.cc.
startContinuousZoom
void Joystick::startContinuousZoom (int direction) signal
Referenced by QGCCameraManager::_activeJoystickChanged().
startVideoRecord
void Joystick::startVideoRecord () signal
Referenced by QGCCameraManager::_activeJoystickChanged().
stepCamera
void Joystick::stepCamera (int direction) signal
Referenced by QGCCameraManager::_activeJoystickChanged().
stepStream
void Joystick::stepStream (int direction) signal
Referenced by QGCCameraManager::_activeJoystickChanged().
stepZoom
void Joystick::stepZoom (int direction) signal
Referenced by QGCCameraManager::_activeJoystickChanged().
stop()
void Joystick::stop ()
Definition at line 1661 of file Joystick.cc.
stopConfiguration()
void Joystick::stopConfiguration ()
Tells the joystick that the configuration UI is being closed so it can do any special processing required.
Definition at line 1640 of file Joystick.cc.
stopContinuousZoom
void Joystick::stopContinuousZoom () signal
Referenced by QGCCameraManager::_activeJoystickChanged().
stopVideoRecord
void Joystick::stopVideoRecord () signal
Referenced by QGCCameraManager::_activeJoystickChanged().
toggleVideoRecord
void Joystick::toggleVideoRecord () signal
Referenced by QGCCameraManager::_activeJoystickChanged().
touchpadCount()
virtual int Joystick::touchpadCount () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 241 of file Joystick.h.
touchpadEvent
void Joystick::touchpadEvent (int touchpad, int finger, bool down, float x, float y, float pressure) signal
touchpadFingerCount()
virtual int Joystick::touchpadFingerCount (int touchpad) const inline virtual
Reimplemented in JoystickSDL.
Definition at line 242 of file Joystick.h.
triggerCamera
void Joystick::triggerCamera () signal
Referenced by QGCCameraManager::_activeJoystickChanged().
unknownAction
void Joystick::unknownAction (const QString & action) signal
updateComplete
void Joystick::updateComplete () signal
vehicleJoystickData
void Joystick::vehicleJoystickData (float roll, float pitch, float yaw, float throttle, uint16_t buttonsLow, uint16_t buttonsHigh, float gimbalPitch, float gimbalYaw) signal
vendorId()
virtual quint16 Joystick::vendorId () const inline virtual
Reimplemented in JoystickSDL.
Definition at line 206 of file Joystick.h.
Friends And Related Symbol Documentation
JoystickConfigController
friend class JoystickConfigController friend
Definition at line 64 of file Joystick.h.
JoystickManager
friend class JoystickManager friend
Definition at line 63 of file Joystick.h.
Member Data Documentation
_axisCount
int Joystick::_axisCount = 0 protected
Definition at line 377 of file Joystick.h.
Referenced by axisCount().
_buttonCount
int Joystick::_buttonCount = 0 protected
Definition at line 378 of file Joystick.h.
_hatCount
int Joystick::_hatCount = 0 protected
Definition at line 379 of file Joystick.h.
_name
QString Joystick::_name protected
Definition at line 376 of file Joystick.h.
Referenced by name(), setLinkedGroupId(), and setLinkedGroupRole().
axisCount
QString name READ name int Joystick::axisCount
Definition at line 101 of file Joystick.h.
Referenced by JoystickSDL::discover().
AxisMax
constexpr int Joystick::AxisMax = 32767 static constexpr
Definition at line 105 of file Joystick.h.
Referenced by Joystick::AxisCalibration_t::reset().
AxisMin
constexpr int Joystick::AxisMin = -32768 static constexpr
Definition at line 104 of file Joystick.h.
Referenced by Joystick::AxisCalibration_t::reset().
buttonCount
QString name READ name int int Joystick::buttonCount
Definition at line 101 of file Joystick.h.
Referenced by JoystickSDL::discover().
hatCount
QString name READ name int int int Joystick::hatCount
Definition at line 101 of file Joystick.h.
Referenced by JoystickSDL::discover().
parent
QString name READ name int int int QObject* Joystick::parent = nullptr)
Definition at line 101 of file Joystick.h.
The documentation for this class was generated from the following files:
src/Joystick/Joystick.h
src/Joystick/Joystick.cc