QGroundControl: LogReplayLink Class Reference
LogReplayLink Class Reference
#include <LogReplayLink.h>
Signals
void logFileStats (uint32_t logDurationSecs)
void playbackStarted ()
void playbackPaused ()
void playbackAtEnd ()
void playbackPercentCompleteChanged (qreal percentComplete)
void currentLogTimeSecs (uint32_t secs)
Signals inherited from LinkInterface
void bytesReceived (LinkInterface *link, const QByteArray &data)
void bytesSent (LinkInterface *link, const QByteArray &data)
void connected ()
void disconnected ()
void communicationError (const QString &title, const QString &error)
Public Member Functions
LogReplayLink (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
virtual ~LogReplayLink ()
bool isConnected () const override
void disconnect () override
bool isLogReplay () const final
bool isPlaying () const
void play ()
void pause ()
void setPlaybackSpeed (qreal playbackSpeed)
void movePlayhead (qreal percentComplete)
Public Member Functions inherited from LinkInterface
virtual ~LinkInterface ()
virtual bool isSecureConnection () const
Returns true if the connection is secure (e.g. USB, wired ethernet)
SharedLinkConfigurationPtr linkConfiguration ()
const SharedLinkConfigurationPtr linkConfiguration () const
uint8_t mavlinkChannel () const
bool mavlinkChannelIsSet () const
bool decodedFirstMavlinkPacket () const
void setDecodedFirstMavlinkPacket (bool decodedFirstMavlinkPacket)
void writeBytesThreadSafe (const char *bytes, int length)
void addVehicleReference ()
void removeVehicleReference ()
bool initMavlinkSigning ()
void setSigningSignatureFailure (bool failure)
void reportMavlinkV1Traffic ()
Additional Inherited Members
Protected Member Functions inherited from LinkInterface
LinkInterface (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
Links are only created by LinkManager so constructor is not public.
virtual bool _allocateMavlinkChannel ()
virtual void _freeMavlinkChannel ()
void _connectionRemoved ()
Protected Attributes inherited from LinkInterface
SharedLinkConfigurationPtr _config
Detailed Description
Definition at line 115 of file LogReplayLink.h.
Constructor & Destructor Documentation
LogReplayLink()
LogReplayLink::LogReplayLink (SharedLinkConfigurationPtr & config, QObject * parent = nullptr) explicit
Definition at line 399 of file LogReplayLink.cc.
References LogReplayWorker::connected(), LogReplayWorker::currentLogTimeSecs(), currentLogTimeSecs(), LogReplayWorker::dataReceived(), LinkInterface::disconnected(), LogReplayWorker::disconnected(), LogReplayWorker::errorOccurred(), LogReplayWorker::logFileStats(), logFileStats(), LogReplayWorker::playbackPaused(), playbackPaused(), LogReplayWorker::playbackPercentCompleteChanged(), playbackPercentCompleteChanged(), LogReplayWorker::playbackStarted(), playbackStarted(), and LogReplayWorker::setup().
~LogReplayLink()
LogReplayLink::~LogReplayLink () virtual
Definition at line 429 of file LogReplayLink.cc.
References isConnected().
Member Function Documentation
currentLogTimeSecs
void LogReplayLink::currentLogTimeSecs (uint32_t secs) signal
Referenced by LogReplayLink().
disconnect()
void LogReplayLink::disconnect () override virtual
Implements LinkInterface.
Definition at line 454 of file LogReplayLink.cc.
References isConnected().
isConnected()
bool LogReplayLink::isConnected () const override virtual
Implements LinkInterface.
Definition at line 444 of file LogReplayLink.cc.
References LogReplayWorker::isConnected().
Referenced by disconnect(), and ~LogReplayLink().
isLogReplay()
bool LogReplayLink::isLogReplay () const inline final virtual
Reimplemented from LinkInterface.
Definition at line 125 of file LogReplayLink.h.
isPlaying()
bool LogReplayLink::isPlaying () const
Definition at line 485 of file LogReplayLink.cc.
References LogReplayWorker::isPlaying().
logFileStats
void LogReplayLink::logFileStats (uint32_t logDurationSecs) signal
Referenced by LogReplayLink().
movePlayhead()
void LogReplayLink::movePlayhead (qreal percentComplete)
Definition at line 505 of file LogReplayLink.cc.
pause()
void LogReplayLink::pause ()
Definition at line 495 of file LogReplayLink.cc.
play()
void LogReplayLink::play ()
Definition at line 490 of file LogReplayLink.cc.
playbackAtEnd
void LogReplayLink::playbackAtEnd () signal
playbackPaused
void LogReplayLink::playbackPaused () signal
Referenced by LogReplayLink().
playbackPercentCompleteChanged
void LogReplayLink::playbackPercentCompleteChanged (qreal percentComplete) signal
Referenced by LogReplayLink().
playbackStarted
void LogReplayLink::playbackStarted () signal
Referenced by LogReplayLink().
setPlaybackSpeed()
void LogReplayLink::setPlaybackSpeed (qreal playbackSpeed)
Definition at line 500 of file LogReplayLink.cc.
The documentation for this class was generated from the following files:
src/Comms/LogReplayLink.h
src/Comms/LogReplayLink.cc