QGroundControl: APMFlightSafetyComponent Class Reference
APMFlightSafetyComponent Class Reference
#include <APMFlightSafetyComponent.h>
Public Member Functions
APMFlightSafetyComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
QStringList setupCompleteChangedTriggerList () const final
QString name () const final
QString description () const final
QString vehicleConfigJson () const final
Resource path to a VehicleConfig.json page definition, or empty if none.
QString iconResource () const final
bool requiresSetup () const final
bool setupComplete () const final
QUrl setupSource () const final
QUrl summaryQmlSource () const final
bool allowSetupWhileArmed () const final
bool allowSetupWhileFlying () const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file APMFlightSafetyComponent.h.
Constructor & Destructor Documentation
APMFlightSafetyComponent()
APMFlightSafetyComponent::APMFlightSafetyComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr) explicit
Definition at line 5 of file APMFlightSafetyComponent.cc.
Member Function Documentation
allowSetupWhileArmed()
bool APMFlightSafetyComponent::allowSetupWhileArmed (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 22 of file APMFlightSafetyComponent.h.
allowSetupWhileFlying()
bool APMFlightSafetyComponent::allowSetupWhileFlying (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 23 of file APMFlightSafetyComponent.h.
description()
QString APMFlightSafetyComponent::description (void) const final virtual
Reimplemented from VehicleComponent.
Definition at line 16 of file APMFlightSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
iconResource()
QString APMFlightSafetyComponent::iconResource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 17 of file APMFlightSafetyComponent.h.
name()
QString APMFlightSafetyComponent::name (void) const inline final virtual
Implements VehicleComponent.
Definition at line 14 of file APMFlightSafetyComponent.h.
requiresSetup()
bool APMFlightSafetyComponent::requiresSetup (void) const inline final virtual
Implements VehicleComponent.
Definition at line 18 of file APMFlightSafetyComponent.h.
setupComplete()
bool APMFlightSafetyComponent::setupComplete (void) const inline final virtual
Implements VehicleComponent.
Definition at line 19 of file APMFlightSafetyComponent.h.
setupCompleteChangedTriggerList()
QStringList APMFlightSafetyComponent::setupCompleteChangedTriggerList () const inline final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 12 of file APMFlightSafetyComponent.h.
setupSource()
QUrl APMFlightSafetyComponent::setupSource (void) const final virtual
Implements VehicleComponent.
Definition at line 30 of file APMFlightSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
summaryQmlSource()
QUrl APMFlightSafetyComponent::summaryQmlSource (void) const final virtual
Implements VehicleComponent.
Definition at line 50 of file APMFlightSafetyComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
vehicleConfigJson()
QString APMFlightSafetyComponent::vehicleConfigJson (void) const final virtual
Resource path to a VehicleConfig.json page definition, or empty if none.
Reimplemented from VehicleComponent.
Definition at line 11 of file APMFlightSafetyComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMFlightSafetyComponent.h
src/AutoPilotPlugins/APM/APMFlightSafetyComponent.cc