QGroundControl: NTRIPTCPLink Class Reference
NTRIPTCPLink Class Reference
#include <NTRIP.h>
Public Slots
void start ()
void requestStop ()
void sendNMEA (const QByteArray &sentence)
Signals
void finished ()
void error (const QString &errorMsg)
void RTCMDataUpdate (const QByteArray &message)
void SPARTNDataUpdate (const QByteArray &message)
void connected ()
Public Member Functions
NTRIPTCPLink (const QString &hostAddress, int port, const QString &username, const QString &password, const QString &mountpoint, const QString &whitelist, bool useSpartn, bool autoStart=true, QObject *parent=nullptr)
void debugFetchSourceTable ()
~NTRIPTCPLink ()
Detailed Description
Definition at line 53 of file NTRIP.h.
Constructor & Destructor Documentation
NTRIPTCPLink()
NTRIPTCPLink::NTRIPTCPLink (const QString & hostAddress, int port, const QString & username, const QString & password, const QString & mountpoint, const QString & whitelist, bool useSpartn, bool autoStart = true, QObject * parent = nullptr)
Definition at line 178 of file NTRIP.cc.
References RTCMParser::reset(), and start().
~NTRIPTCPLink()
NTRIPTCPLink::~NTRIPTCPLink ()
Definition at line 235 of file NTRIP.cc.
Member Function Documentation
connected
void NTRIPTCPLink::connected () signal
debugFetchSourceTable()
void NTRIPTCPLink::debugFetchSourceTable ()
Definition at line 667 of file NTRIP.cc.
error
void NTRIPTCPLink::error (const QString & errorMsg) signal
finished
void NTRIPTCPLink::finished () signal
Referenced by requestStop().
requestStop
void NTRIPTCPLink::requestStop () slot
Definition at line 799 of file NTRIP.cc.
References finished().
RTCMDataUpdate
void NTRIPTCPLink::RTCMDataUpdate (const QByteArray & message) signal
sendNMEA
void NTRIPTCPLink::sendNMEA (const QByteArray & sentence) slot
Definition at line 730 of file NTRIP.cc.
SPARTNDataUpdate
void NTRIPTCPLink::SPARTNDataUpdate (const QByteArray & message) signal
start
void NTRIPTCPLink::start () slot
Definition at line 253 of file NTRIP.cc.
Referenced by NTRIPTCPLink().
The documentation for this class was generated from the following files:
src/GPS/NTRIP.h
src/GPS/NTRIP.cc