QGroundControl: Mixer::ChannelConfigInstanceVirtualAxis Class Reference
Mixer::ChannelConfigInstanceVirtualAxis Class Reference
#include <Mixer.h>
Public Types
enum class Direction {
Custom = 0 , Upwards = 1 , Downwards = 2 , Forwards = 3 ,
Backwards = 4 , Leftwards = 5 , Rightwards = 6
}
Public Member Functions
ChannelConfigInstanceVirtualAxis (QObject *parent, ChannelConfig &config)
void allInstancesInitialized (QmlObjectListModel *configInstances) override
Public Member Functions inherited from Mixer::ChannelConfigInstance
ChannelConfigInstance (QObject *parent, Fact *fact, ChannelConfig &config)
ChannelConfig *config READ channelConfig CONSTANT (Fact *fact READ fact CONSTANT) 1(bool visible READ visible NOTIFY visibleChanged) 1(bool enabled READ enabled NOTIFY enabledChanged) ChannelConfig *channelConfig() const
Fact * fact ()
bool visible () const
bool enabled () const
bool visibleRule () const
bool enabledRule () const
void setVisibleRule (bool visible)
void setEnabledRule (bool enabled)
void setVisibleAxis (bool visible)
int ruleApplyIdentifierIdx () const
void setRuleApplyIdentifierIdx (int idx)
Additional Inherited Members
Signals inherited from Mixer::ChannelConfigInstance
void visibleChanged ()
void enabledChanged ()
Protected Attributes inherited from Mixer::ChannelConfigInstance
Fact * _fact {nullptr}
Detailed Description
Definition at line 236 of file Mixer.h.
Member Enumeration Documentation
Direction
enum class Mixer::ChannelConfigInstanceVirtualAxis::Direction strong
Enumerator
Custom
Upwards
Downwards
Forwards
Backwards
Leftwards
Rightwards
Definition at line 240 of file Mixer.h.
Constructor & Destructor Documentation
ChannelConfigInstanceVirtualAxis()
Mixer::ChannelConfigInstanceVirtualAxis::ChannelConfigInstanceVirtualAxis (QObject * parent, ChannelConfig & config) inline
Definition at line 249 of file Mixer.h.
Member Function Documentation
allInstancesInitialized()
void ChannelConfigInstanceVirtualAxis::allInstancesInitialized (QmlObjectListModel * configInstances) override virtual
Reimplemented from Mixer::ChannelConfigInstance.
Definition at line 82 of file Mixer.cc.
References Mixer::ChannelConfigInstance::_fact, Mixer::AxisX, Mixer::AxisY, Mixer::AxisZ, QmlObjectListModel::count(), Mixer::ChannelConfigInstance::enabledChanged(), Mixer::ChannelConfigInstance::fact(), Fact::rawValueChanged(), FactMetaData::setEnumInfo(), QmlObjectListModel::value(), FactMetaData::valueTypeUint32, and Mixer::ChannelConfigInstance::visibleChanged().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Mixer.h
src/Vehicle/Actuators/Mixer.cc