QGroundControl: CameraCalc Class Reference
CameraCalc Class Reference
#include <CameraCalc.h>
Signals
void imageFootprintSideChanged (double imageFootprintSide)
void imageFootprintFrontalChanged (double imageFootprintFrontal)
void distanceModeChanged (int altMode)
void isManualCameraChanged (void)
void isCustomCameraChanged (void)
void cameraBrandChanged (void)
void cameraModelChanged (void)
void cameraModelListChanged (void)
void updateCameraStats (void)
Signals inherited from CameraSpec
void dirtyChanged (bool dirty)
Public Member Functions
CameraCalc (PlanMasterController *masterController, const QString &settingsGroup, QObject *parent=nullptr)
Fact * valueSetIsDistance (void)
Fact * distanceToSurface (void)
Fact * imageDensity (void)
Fact * frontalOverlap (void)
Fact * sideOverlap (void)
Fact * adjustedFootprintSide (void)
Fact * adjustedFootprintFrontal (void)
const Fact * valueSetIsDistance (void) const
const Fact * distanceToSurface (void) const
const Fact * imageDensity (void) const
const Fact * frontalOverlap (void) const
const Fact * sideOverlap (void) const
const Fact * adjustedFootprintSide (void) const
const Fact * adjustedFootprintFrontal (void) const
bool isManualCamera (void) const
bool isCustomCamera (void) const
double imageFootprintSide (void) const
double imageFootprintFrontal (void) const
QGroundControlQmlGlobal::AltMode distanceMode (void) const
void setDistanceMode (QGroundControlQmlGlobal::AltMode altMode)
void setCameraBrand (const QString &cameraBrand)
void setCameraModel (const QString &cameraModel)
void save (QJsonObject &json) const
bool load (const QJsonObject &json, bool deprecatedFollowTerrain, QString &errorString, bool forPresets)
void _setCameraNameFromV3TransectLoad (const QString &cameraName)
Public Member Functions inherited from CameraSpec
CameraSpec (const QString &settingsGroup, QObject *parent=nullptr)
const CameraSpec & operator= (const CameraSpec &other)
Fact *sensorWidth READ sensorWidth CONSTANT (Fact *sensorHeight READ sensorHeight CONSTANT) 1(Fact *imageWidth READ imageWidth CONSTANT) 1(Fact *imageHeight READ imageHeight CONSTANT) 1(Fact *focalLength READ focalLength CONSTANT) 1(Fact *landscape READ landscape CONSTANT) 1(Fact *fixedOrientation READ fixedOrientation CONSTANT) 1(Fact *minTriggerInterval READ minTriggerInterval CONSTANT) SettingsFact *sensorWidth(void)
< Sensor size in millimeters
SettingsFact * sensorHeight (void)
SettingsFact * imageWidth (void)
SettingsFact * imageHeight (void)
SettingsFact * focalLength (void)
SettingsFact * landscape (void)
SettingsFact * fixedOrientation (void)
SettingsFact * minTriggerInterval (void)
bool dirty (void) const
void setDirty (bool dirty)
void save (QJsonObject &json) const
bool load (const QJsonObject &json, QString &errorString)
Static Public Member Functions
static QString canonicalCustomCameraName (void)
static QString canonicalManualCameraName (void)
Static Public Attributes
QString xlatCustomCameraName READ xlatCustomCameraName static CONSTANT(QString xlatManualCameraName READ xlatManualCameraName CONSTANT) 1(bool isManualCamera READ isManualCamera NOTIFY isManualCameraChanged) 1(bool isCustomCamera READ isCustomCamera NOTIFY isCustomCameraChanged) 1(QString cameraBrand MEMBER _cameraBrand WRITE setCameraBrand NOTIFY cameraBrandChanged) 1(QString cameraModel MEMBER _cameraModel WRITE setCameraModel NOTIFY cameraModelChanged) 1(QStringList cameraBrandList MEMBER _cameraBrandList CONSTANT) 1(QStringList cameraModelList MEMBER _cameraModelList NOTIFY cameraModelListChanged) 1(Fact *valueSetIsDistance READ valueSetIsDistance CONSTANT) 1(Fact *distanceToSurface READ distanceToSurface CONSTANT) 1(Fact *imageDensity READ imageDensity CONSTANT) 1(Fact *frontalOverlap READ frontalOverlap CONSTANT) 1(Fact *sideOverlap READ sideOverlap CONSTANT) 1(Fact *adjustedFootprintSide READ adjustedFootprintSide CONSTANT) 1(Fact *adjustedFootprintFrontal READ adjustedFootprintFrontal CONSTANT) 1(QGroundControlQmlGlobal QStrin xlatManualCameraName)(void)
< User visible camera name for custom camera setting
static constexpr const char * cameraNameName = "CameraName"
static constexpr const char * valueSetIsDistanceName = "ValueSetIsDistance"
static constexpr const char * distanceToSurfaceName = "DistanceToSurface"
static constexpr const char * distanceModeName = "DistanceMode"
static constexpr const char * imageDensityName = "ImageDensity"
static constexpr const char * frontalOverlapName = "FrontalOverlap"
static constexpr const char * sideOverlapName = "SideOverlap"
static constexpr const char * adjustedFootprintFrontalName = "AdjustedFootprintFrontal"
static constexpr const char * adjustedFootprintSideName = "AdjustedFootprintSide"
Detailed Description
Definition at line 11 of file CameraCalc.h.
Constructor & Destructor Documentation
CameraCalc()
CameraCalc::CameraCalc (PlanMasterController * masterController, const QString & settingsGroup, QObject * parent = nullptr)
Definition at line 9 of file CameraCalc.cc.
References distanceModeChanged(), CameraSpec::focalLength(), CameraSpec::imageHeight(), CameraSpec::imageWidth(), isCustomCameraChanged(), isManualCameraChanged(), CameraSpec::landscape(), Fact::rawValueChanged(), CameraSpec::sensorHeight(), CameraSpec::setDirty(), Fact::valueChanged(), and xlatManualCameraName.
Member Function Documentation
_setCameraNameFromV3TransectLoad()
void CameraCalc::_setCameraNameFromV3TransectLoad (const QString & cameraName)
Definition at line 392 of file CameraCalc.cc.
adjustedFootprintFrontal() [1/2]
Fact * CameraCalc::adjustedFootprintFrontal (void) inline
Definition at line 58 of file CameraCalc.h.
Referenced by StructureScanComplexItem::appendMissionItems(), StructureScanComplexItem::bottomFlightAlt(), CorridorScanComplexItem::timeBetweenShots(), StructureScanComplexItem::topFlightAlt(), and TransectStyleComplexItem::triggerDistance().
adjustedFootprintFrontal() [2/2]
const Fact * CameraCalc::adjustedFootprintFrontal (void) const inline
Definition at line 66 of file CameraCalc.h.
adjustedFootprintSide() [1/2]
Fact * CameraCalc::adjustedFootprintSide (void) inline
Definition at line 57 of file CameraCalc.h.
Referenced by StructureScanComplexItem::appendMissionItems(), and StructureScanComplexItem::timeBetweenShots().
adjustedFootprintSide() [2/2]
const Fact * CameraCalc::adjustedFootprintSide (void) const inline
Definition at line 65 of file CameraCalc.h.
cameraBrandChanged
void CameraCalc::cameraBrandChanged (void) signal
Referenced by setCameraBrand().
cameraModelChanged
void CameraCalc::cameraModelChanged (void) signal
Referenced by setCameraBrand(), and setCameraModel().
cameraModelListChanged
void CameraCalc::cameraModelListChanged (void) signal
canonicalCustomCameraName()
QString CameraCalc::canonicalCustomCameraName (void) static
Definition at line 274 of file CameraCalc.cc.
Referenced by isCustomCamera(), and load().
canonicalManualCameraName()
QString CameraCalc::canonicalManualCameraName (void) static
Definition at line 280 of file CameraCalc.cc.
Referenced by isManualCamera(), and load().
distanceMode()
QGroundControlQmlGlobal::AltMode CameraCalc::distanceMode (void) const inline
Definition at line 72 of file CameraCalc.h.
Referenced by TransectStyleComplexItem::_appendConditionGate(), TransectStyleComplexItem::_appendWaypoint(), TransectStyleComplexItem::_buildAndAppendMissionItems(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), TransectStyleComplexItem::_save(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslExitAlt(), TransectStyleComplexItem::maxAMSLAltitude(), TransectStyleComplexItem::minAMSLAltitude(), and TransectStyleComplexItem::readyForSaveState().
distanceModeChanged
void CameraCalc::distanceModeChanged (int altMode) signal
Referenced by CameraCalc(), setDistanceMode(), and TransectStyleComplexItem::TransectStyleComplexItem().
distanceToSurface() [1/2]
Fact * CameraCalc::distanceToSurface (void) inline
Definition at line 53 of file CameraCalc.h.
Referenced by TransectStyleComplexItem::_appendConditionGate(), TransectStyleComplexItem::_appendWaypoint(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::applyNewAltitude(), TransectStyleComplexItem::maxAMSLAltitude(), and TransectStyleComplexItem::minAMSLAltitude().
distanceToSurface() [2/2]
const Fact * CameraCalc::distanceToSurface (void) const inline
Definition at line 61 of file CameraCalc.h.
frontalOverlap() [1/2]
Fact * CameraCalc::frontalOverlap (void) inline
Definition at line 55 of file CameraCalc.h.
frontalOverlap() [2/2]
const Fact * CameraCalc::frontalOverlap (void) const inline
Definition at line 63 of file CameraCalc.h.
imageDensity() [1/2]
Fact * CameraCalc::imageDensity (void) inline
Definition at line 54 of file CameraCalc.h.
imageDensity() [2/2]
const Fact * CameraCalc::imageDensity (void) const inline
Definition at line 62 of file CameraCalc.h.
imageFootprintFrontal()
double CameraCalc::imageFootprintFrontal (void) const inline
Definition at line 71 of file CameraCalc.h.
imageFootprintFrontalChanged
void CameraCalc::imageFootprintFrontalChanged (double imageFootprintFrontal) signal
imageFootprintSide()
double CameraCalc::imageFootprintSide (void) const inline
Definition at line 70 of file CameraCalc.h.
imageFootprintSideChanged
void CameraCalc::imageFootprintSideChanged (double imageFootprintSide) signal
isCustomCamera()
bool CameraCalc::isCustomCamera (void) const inline
Definition at line 69 of file CameraCalc.h.
References canonicalCustomCameraName().
isCustomCameraChanged
void CameraCalc::isCustomCameraChanged (void) signal
Referenced by CameraCalc().
isManualCamera()
bool CameraCalc::isManualCamera (void) const inline
Definition at line 68 of file CameraCalc.h.
References canonicalManualCameraName().
Referenced by load(), and save().
isManualCameraChanged
void CameraCalc::isManualCameraChanged (void) signal
Referenced by CameraCalc(), and StructureScanComplexItem::StructureScanComplexItem().
load()
bool CameraCalc::load (const QJsonObject & json, bool deprecatedFollowTerrain, QString & errorString, bool forPresets)
Definition at line 180 of file CameraCalc.cc.
References adjustedFootprintFrontalName, adjustedFootprintSideName, QGroundControlQmlGlobal::AltitudeModeAbsolute, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeRelative, cameraNameName, canonicalCustomCameraName(), canonicalManualCameraName(), distanceModeName, distanceToSurfaceName, errorString, frontalOverlapName, imageDensityName, isManualCamera(), JsonHelper::jsonVersionKey, CameraSpec::load(), setDistanceMode(), sideOverlapName, JsonHelper::validateKeys(), and valueSetIsDistanceName.
Referenced by TransectStyleComplexItem::_load(), and StructureScanComplexItem::load().
save()
void CameraCalc::save (QJsonObject & json) const
Definition at line 162 of file CameraCalc.cc.
References adjustedFootprintFrontalName, adjustedFootprintSideName, cameraNameName, distanceModeName, distanceToSurfaceName, frontalOverlapName, imageDensityName, isManualCamera(), JsonHelper::jsonVersionKey, CameraSpec::save(), sideOverlapName, and valueSetIsDistanceName.
Referenced by TransectStyleComplexItem::_save(), and StructureScanComplexItem::save().
setCameraBrand()
void CameraCalc::setCameraBrand (const QString & cameraBrand)
Definition at line 309 of file CameraCalc.cc.
References cameraBrandChanged(), cameraModelChanged(), and xlatManualCameraName.
setCameraModel()
void CameraCalc::setCameraModel (const QString & cameraModel)
Definition at line 339 of file CameraCalc.cc.
References cameraModelChanged().
setDistanceMode()
void CameraCalc::setDistanceMode (QGroundControlQmlGlobal::AltMode altMode)
Definition at line 296 of file CameraCalc.cc.
References distanceModeChanged().
Referenced by load().
sideOverlap() [1/2]
Fact * CameraCalc::sideOverlap (void) inline
Definition at line 56 of file CameraCalc.h.
sideOverlap() [2/2]
const Fact * CameraCalc::sideOverlap (void) const inline
Definition at line 64 of file CameraCalc.h.
updateCameraStats
void CameraCalc::updateCameraStats (void) signal
valueSetIsDistance() [1/2]
Fact * CameraCalc::valueSetIsDistance (void) inline
Definition at line 52 of file CameraCalc.h.
Referenced by TransectStyleComplexItem::applyNewAltitude().
valueSetIsDistance() [2/2]
const Fact * CameraCalc::valueSetIsDistance (void) const inline
Definition at line 60 of file CameraCalc.h.
Member Data Documentation
adjustedFootprintFrontalName
constexpr const char* CameraCalc::adjustedFootprintFrontalName = "AdjustedFootprintFrontal" static constexpr
Definition at line 90 of file CameraCalc.h.
Referenced by load(), and save().
adjustedFootprintSideName
constexpr const char* CameraCalc::adjustedFootprintSideName = "AdjustedFootprintSide" static constexpr
Definition at line 91 of file CameraCalc.h.
Referenced by load(), and save().
cameraNameName
constexpr const char* CameraCalc::cameraNameName = "CameraName" static constexpr
Definition at line 83 of file CameraCalc.h.
Referenced by load(), and save().
distanceModeName
constexpr const char* CameraCalc::distanceModeName = "DistanceMode" static constexpr
Definition at line 86 of file CameraCalc.h.
Referenced by load(), and save().
distanceToSurfaceName
constexpr const char* CameraCalc::distanceToSurfaceName = "DistanceToSurface" static constexpr
Definition at line 85 of file CameraCalc.h.
Referenced by load(), and save().
frontalOverlapName
constexpr const char* CameraCalc::frontalOverlapName = "FrontalOverlap" static constexpr
Definition at line 88 of file CameraCalc.h.
Referenced by load(), and save().
imageDensityName
constexpr const char* CameraCalc::imageDensityName = "ImageDensity" static constexpr
Definition at line 87 of file CameraCalc.h.
Referenced by load(), and save().
sideOverlapName
constexpr const char* CameraCalc::sideOverlapName = "SideOverlap" static constexpr
Definition at line 89 of file CameraCalc.h.
Referenced by load(), and save().
valueSetIsDistanceName
constexpr const char* CameraCalc::valueSetIsDistanceName = "ValueSetIsDistance" static constexpr
Definition at line 84 of file CameraCalc.h.
Referenced by load(), and save().
xlatManualCameraName
QString CameraCalc::xlatManualCameraName (void) static
< User visible camera name for custom camera setting
< true: distance specified, resolution calculated < Distance to surface for image foot print calculation < Image density on surface (cm/px) < Side footprint adjusted down for overlap < Frontal footprint adjusted down for overlap
Definition at line 48 of file CameraCalc.h.
Referenced by CameraCalc(), and setCameraBrand().
The documentation for this class was generated from the following files:
src/MissionManager/CameraCalc.h
src/MissionManager/CameraCalc.cc