QGroundControl: RemoteTransport Class Reference
RemoteTransport Class Reference abstract
#include <RemoteTransport.h>
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &message)
Public Member Functions
RemoteTransport (QObject *parent=nullptr)
virtual bool send (const QByteArray &data)=0
virtual void close ()=0
virtual bool isConnected () const =0
Detailed Description
Definition at line 14 of file RemoteTransport.h.
Constructor & Destructor Documentation
RemoteTransport()
RemoteTransport::RemoteTransport (QObject * parent = nullptr) inline explicit
Definition at line 19 of file RemoteTransport.h.
Member Function Documentation
close()
virtual void RemoteTransport::close () pure virtual
Implemented in UdpTransport, and TcpTransport.
connected
void RemoteTransport::connected () signal
disconnected
void RemoteTransport::disconnected () signal
Referenced by TcpTransport::close().
errorOccurred
void RemoteTransport::errorOccurred (const QString & message) signal
Referenced by UdpTransport::send(), and TcpTransport::send().
isConnected()
virtual bool RemoteTransport::isConnected () const pure virtual
Implemented in UdpTransport, and TcpTransport.
send()
virtual bool RemoteTransport::send (const QByteArray & data) pure virtual
Implemented in UdpTransport, and TcpTransport.
The documentation for this class was generated from the following file:
src/Utilities/Network/RemoteTransport.h