QGroundControl: TcpTransport Class Reference
TcpTransport Class Reference
#include <RemoteTransport.h>
Public Member Functions
TcpTransport (QObject *parent=nullptr)
void setTarget (const QString &host, quint16 port)
void setTlsEnabled (bool enabled)
void setTlsVerifyPeer (bool verify)
void setTlsCaCertificates (const QList< QSslCertificate > &certs)
void setTlsClientCertificate (const QSslCertificate &cert, const QSslKey &key)
bool send (const QByteArray &data) override
void close () override
bool isConnected () const override
void connectToHost ()
Public Member Functions inherited from RemoteTransport
RemoteTransport (QObject *parent=nullptr)
Additional Inherited Members
Signals inherited from RemoteTransport
void connected ()
void disconnected ()
void errorOccurred (const QString &message)
Detailed Description
Definition at line 56 of file RemoteTransport.h.
Constructor & Destructor Documentation
TcpTransport()
TcpTransport::TcpTransport (QObject * parent = nullptr) explicit
Definition at line 64 of file RemoteTransport.cc.
Member Function Documentation
close()
void TcpTransport::close () override virtual
Implements RemoteTransport.
Definition at line 104 of file RemoteTransport.cc.
References RemoteTransport::disconnected().
Referenced by TransportStrategy::reset(), TransportStrategy::setProtocol(), TransportStrategy::setTlsEnabled(), TransportStrategy::setTlsVerifyPeer(), and TransportStrategy::~TransportStrategy().
connectToHost()
void TcpTransport::connectToHost ()
Definition at line 118 of file RemoteTransport.cc.
Referenced by TransportStrategy::send().
isConnected()
bool TcpTransport::isConnected () const inline override virtual
Implements RemoteTransport.
Definition at line 71 of file RemoteTransport.h.
Referenced by TransportStrategy::isConnected(), TransportStrategy::send(), and TransportStrategy::tcpConnected().
send()
bool TcpTransport::send (const QByteArray & data) override virtual
Implements RemoteTransport.
Definition at line 84 of file RemoteTransport.cc.
References RemoteTransport::errorOccurred().
Referenced by TransportStrategy::send().
setTarget()
void TcpTransport::setTarget (const QString & host, quint16 port)
Definition at line 69 of file RemoteTransport.cc.
setTlsCaCertificates()
void TcpTransport::setTlsCaCertificates (const QList< QSslCertificate > & certs)
Definition at line 77 of file RemoteTransport.cc.
Referenced by TransportStrategy::setTlsCaCertificates().
setTlsClientCertificate()
void TcpTransport::setTlsClientCertificate (const QSslCertificate & cert, const QSslKey & key)
Definition at line 78 of file RemoteTransport.cc.
Referenced by TransportStrategy::setTlsClientCertificate().
setTlsEnabled()
void TcpTransport::setTlsEnabled (bool enabled)
Definition at line 75 of file RemoteTransport.cc.
setTlsVerifyPeer()
void TcpTransport::setTlsVerifyPeer (bool verify)
Definition at line 76 of file RemoteTransport.cc.
The documentation for this class was generated from the following files:
src/Utilities/Network/RemoteTransport.h
src/Utilities/Network/RemoteTransport.cc