QGroundControl: LogReplayWorker Class Reference
LogReplayWorker Class Reference
#include <LogReplayLink.h>
Public Slots
void setup ()
void connectToLog ()
void disconnectFromLog ()
void play ()
void pause ()
void setPlaybackSpeed (qreal playbackSpeed)
void movePlayhead (qreal percentComplete)
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &errorString)
void dataReceived (const QByteArray &data)
void logFileStats (uint32_t logDurationSecs)
void playbackStarted ()
void playbackPaused ()
void playbackAtEnd ()
void playbackPercentCompleteChanged (qreal percentComplete)
void currentLogTimeSecs (uint32_t secs)
Public Member Functions
LogReplayWorker (const LogReplayConfiguration *config, QObject *parent=nullptr)
~LogReplayWorker ()
bool isConnected () const
bool isPlaying () const
Detailed Description
Definition at line 52 of file LogReplayLink.h.
Constructor & Destructor Documentation
LogReplayWorker()
LogReplayWorker::LogReplayWorker (const LogReplayConfiguration * config, QObject * parent = nullptr) explicit
Definition at line 76 of file LogReplayLink.cc.
~LogReplayWorker()
LogReplayWorker::~LogReplayWorker ()
Definition at line 83 of file LogReplayLink.cc.
References disconnectFromLog().
Member Function Documentation
connected
void LogReplayWorker::connected () signal
Referenced by connectToLog(), and LogReplayLink::LogReplayLink().
connectToLog
void LogReplayWorker::connectToLog () slot
Definition at line 99 of file LogReplayLink.cc.
References connected(), disconnectFromLog(), errorOccurred(), isConnected(), and play().
currentLogTimeSecs
void LogReplayWorker::currentLogTimeSecs (uint32_t secs) signal
Referenced by LogReplayLink::LogReplayLink().
dataReceived
void LogReplayWorker::dataReceived (const QByteArray & data) signal
Referenced by LogReplayLink::LogReplayLink().
disconnected
void LogReplayWorker::disconnected () signal
Referenced by disconnectFromLog(), and LogReplayLink::LogReplayLink().
disconnectFromLog
void LogReplayWorker::disconnectFromLog () slot
Definition at line 122 of file LogReplayLink.cc.
References disconnected(), and isConnected().
Referenced by connectToLog(), and ~LogReplayWorker().
errorOccurred
void LogReplayWorker::errorOccurred (const QString & errorString) signal
Referenced by connectToLog(), LogReplayLink::LogReplayLink(), and movePlayhead().
isConnected()
bool LogReplayWorker::isConnected () const inline
Definition at line 60 of file LogReplayLink.h.
Referenced by connectToLog(), disconnectFromLog(), and LogReplayLink::isConnected().
isPlaying()
bool LogReplayWorker::isPlaying () const
Definition at line 143 of file LogReplayLink.cc.
Referenced by LogReplayLink::isPlaying(), and movePlayhead().
logFileStats
void LogReplayWorker::logFileStats (uint32_t logDurationSecs) signal
Referenced by LogReplayLink::LogReplayLink().
movePlayhead
void LogReplayWorker::movePlayhead (qreal percentComplete) slot
Definition at line 182 of file LogReplayLink.cc.
References errorOccurred(), isPlaying(), pause(), and playbackPercentCompleteChanged().
pause
void LogReplayWorker::pause () slot
Definition at line 164 of file LogReplayLink.cc.
References MAVLinkProtocol::instance(), playbackPaused(), and MAVLinkProtocol::suspendLogForReplay().
Referenced by movePlayhead().
play
void LogReplayWorker::play () slot
Definition at line 148 of file LogReplayLink.cc.
References MAVLinkProtocol::instance(), playbackStarted(), and MAVLinkProtocol::suspendLogForReplay().
Referenced by connectToLog().
playbackAtEnd
void LogReplayWorker::playbackAtEnd () signal
playbackPaused
void LogReplayWorker::playbackPaused () signal
Referenced by LogReplayLink::LogReplayLink(), and pause().
playbackPercentCompleteChanged
void LogReplayWorker::playbackPercentCompleteChanged (qreal percentComplete) signal
Referenced by LogReplayLink::LogReplayLink(), and movePlayhead().
playbackStarted
void LogReplayWorker::playbackStarted () signal
Referenced by LogReplayLink::LogReplayLink(), and play().
setPlaybackSpeed
void LogReplayWorker::setPlaybackSpeed (qreal playbackSpeed) slot
Definition at line 174 of file LogReplayLink.cc.
setup
void LogReplayWorker::setup () slot
Definition at line 90 of file LogReplayLink.cc.
Referenced by LogReplayLink::LogReplayLink().
The documentation for this class was generated from the following files:
src/Comms/LogReplayLink.h
src/Comms/LogReplayLink.cc