QGroundControl: VehicleFactGroup Class Reference
VehicleFactGroup Class Reference
#include <VehicleFactGroup.h>
Protected Member Functions
void _handleAttitude (Vehicle *vehicle, const mavlink_message_t &message)
void _handleAttitudeQuaternion (Vehicle *vehicle, const mavlink_message_t &message)
void _handleAltitude (const mavlink_message_t &message)
void _handleVfrHud (const mavlink_message_t &message)
void _handleRawImuTemp (const mavlink_message_t &message)
void _handleNavControllerOutput (const mavlink_message_t &message)
void _handleRangefinder (const mavlink_message_t &message)
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
Fact _rollFact = Fact(0, QStringLiteral("roll"), FactMetaData::valueTypeDouble)
Fact _pitchFact = Fact(0, QStringLiteral("pitch"), FactMetaData::valueTypeDouble)
Fact _headingFact = Fact(0, QStringLiteral("heading"), FactMetaData::valueTypeDouble)
Fact _rollRateFact = Fact(0, QStringLiteral("rollRate"), FactMetaData::valueTypeDouble)
Fact _pitchRateFact = Fact(0, QStringLiteral("pitchRate"), FactMetaData::valueTypeDouble)
Fact _yawRateFact = Fact(0, QStringLiteral("yawRate"), FactMetaData::valueTypeDouble)
Fact _groundSpeedFact = Fact(0, QStringLiteral("groundSpeed"), FactMetaData::valueTypeDouble)
Fact _airSpeedFact = Fact(0, QStringLiteral("airSpeed"), FactMetaData::valueTypeDouble)
Fact _airSpeedSetpointFact = Fact(0, QStringLiteral("airSpeedSetpoint"), FactMetaData::valueTypeDouble)
Fact _climbRateFact = Fact(0, QStringLiteral("climbRate"), FactMetaData::valueTypeDouble)
Fact _altitudeRelativeFact = Fact(0, QStringLiteral("altitudeRelative"), FactMetaData::valueTypeDouble)
Fact _altitudeAMSLFact = Fact(0, QStringLiteral("altitudeAMSL"), FactMetaData::valueTypeDouble)
Fact _altitudeAboveTerrFact = Fact(0, QStringLiteral("altitudeAboveTerr"), FactMetaData::valueTypeDouble)
Fact _altitudeTuningFact = Fact(0, QStringLiteral("altitudeTuning"), FactMetaData::valueTypeDouble)
Fact _altitudeTuningSetpointFact = Fact(0, QStringLiteral("altitudeTuningSetpoint"), FactMetaData::valueTypeDouble)
Fact _xTrackErrorFact = Fact(0, QStringLiteral("xTrackError"), FactMetaData::valueTypeDouble)
Fact _rangeFinderDistFact = Fact(0, QStringLiteral("rangeFinderDist"), FactMetaData::valueTypeFloat)
Fact _flightDistanceFact = Fact(0, QStringLiteral("flightDistance"), FactMetaData::valueTypeDouble)
Fact _flightTimeFact = Fact(0, QStringLiteral("flightTime"), FactMetaData::valueTypeElapsedTimeInSeconds)
Fact _distanceToHomeFact = Fact(0, QStringLiteral("distanceToHome"), FactMetaData::valueTypeDouble)
Fact _timeToHomeFact = Fact(0, QStringLiteral("timeToHome"), FactMetaData::valueTypeDouble)
Fact _missionItemIndexFact = Fact(0, QStringLiteral("missionItemIndex"), FactMetaData::valueTypeUint16)
Fact _headingToNextWPFact = Fact(0, QStringLiteral("headingToNextWP"), FactMetaData::valueTypeDouble)
Fact _distanceToNextWPFact = Fact(0, QStringLiteral("distanceToNextWP"), FactMetaData::valueTypeDouble)
Fact _headingToHomeFact = Fact(0, QStringLiteral("headingToHome"), FactMetaData::valueTypeDouble)
Fact _headingFromHomeFact = Fact(0, QStringLiteral("headingFromHome"),FactMetaData::valueTypeDouble)
Fact _headingFromGCSFact = Fact(0, QStringLiteral("headingFromGCS"),FactMetaData::valueTypeDouble)
Fact _distanceToGCSFact = Fact(0, QStringLiteral("distanceToGCS"), FactMetaData::valueTypeDouble)
Fact _hobbsFact = Fact(0, QStringLiteral("hobbs"), FactMetaData::valueTypeString)
Fact _throttlePctFact = Fact(0, QStringLiteral("throttlePct"), FactMetaData::valueTypeUint16)
Fact _imuTempFact = Fact(0, QStringLiteral("imuTemp"), FactMetaData::valueTypeInt16)
float _altitudeTuningOffset = qQNaN()
bool _altitudeMessageAvailable = false
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Additional Inherited Members
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Detailed Description
Definition at line 5 of file VehicleFactGroup.h.
Member Function Documentation
_handleAltitude()
void VehicleFactGroup::_handleAltitude (const mavlink_message_t & message) protected
Definition at line 116 of file VehicleFactGroup.cc.
References _altitudeMessageAvailable, and FactGroup::_setTelemetryAvailable().
_handleAttitude()
void VehicleFactGroup::_handleAttitude (Vehicle * vehicle, const mavlink_message_t & message) protected
Definition at line 98 of file VehicleFactGroup.cc.
References FactGroup::_setTelemetryAvailable(), Vehicle::compId(), and Vehicle::id().
_handleAttitudeQuaternion()
void VehicleFactGroup::_handleAttitudeQuaternion (Vehicle * vehicle, const mavlink_message_t & message) protected
Definition at line 129 of file VehicleFactGroup.cc.
References FactGroup::_setTelemetryAvailable(), Vehicle::compId(), and Vehicle::id().
_handleNavControllerOutput()
void VehicleFactGroup::_handleNavControllerOutput (const mavlink_message_t & message) protected
Definition at line 164 of file VehicleFactGroup.cc.
References _airSpeedFact, _altitudeTuningFact, and FactGroup::_setTelemetryAvailable().
_handleRangefinder()
void VehicleFactGroup::_handleRangefinder (const mavlink_message_t & message) protected
Definition at line 208 of file VehicleFactGroup.cc.
References FactGroup::_setTelemetryAvailable().
_handleRawImuTemp()
void VehicleFactGroup::_handleRawImuTemp (const mavlink_message_t & message) protected
Definition at line 197 of file VehicleFactGroup.cc.
References FactGroup::_setTelemetryAvailable().
_handleVfrHud()
void VehicleFactGroup::_handleVfrHud (const mavlink_message_t & message) protected
Definition at line 177 of file VehicleFactGroup.cc.
References _altitudeTuningOffset, _distanceToHomeFact, and FactGroup::_setTelemetryAvailable().
Member Data Documentation
_airSpeedFact
Fact VehicleFactGroup::_airSpeedFact = Fact(0, QStringLiteral("airSpeed"), FactMetaData::valueTypeDouble) protected
Definition at line 93 of file VehicleFactGroup.h.
Referenced by _handleNavControllerOutput().
_airSpeedSetpointFact
Fact VehicleFactGroup::_airSpeedSetpointFact = Fact(0, QStringLiteral("airSpeedSetpoint"), FactMetaData::valueTypeDouble) protected
Definition at line 94 of file VehicleFactGroup.h.
_altitudeAboveTerrFact
Fact VehicleFactGroup::_altitudeAboveTerrFact = Fact(0, QStringLiteral("altitudeAboveTerr"), FactMetaData::valueTypeDouble) protected
Definition at line 98 of file VehicleFactGroup.h.
_altitudeAMSLFact
Fact VehicleFactGroup::_altitudeAMSLFact = Fact(0, QStringLiteral("altitudeAMSL"), FactMetaData::valueTypeDouble) protected
Definition at line 97 of file VehicleFactGroup.h.
_altitudeMessageAvailable
bool VehicleFactGroup::_altitudeMessageAvailable = false protected
Definition at line 121 of file VehicleFactGroup.h.
Referenced by _handleAltitude().
_altitudeRelativeFact
Fact VehicleFactGroup::_altitudeRelativeFact = Fact(0, QStringLiteral("altitudeRelative"), FactMetaData::valueTypeDouble) protected
Definition at line 96 of file VehicleFactGroup.h.
_altitudeTuningFact
Fact VehicleFactGroup::_altitudeTuningFact = Fact(0, QStringLiteral("altitudeTuning"), FactMetaData::valueTypeDouble) protected
Definition at line 99 of file VehicleFactGroup.h.
Referenced by _handleNavControllerOutput(), and Vehicle::setPIDTuningTelemetryMode().
_altitudeTuningOffset
float VehicleFactGroup::_altitudeTuningOffset = qQNaN() protected
Definition at line 118 of file VehicleFactGroup.h.
Referenced by _handleVfrHud().
_altitudeTuningSetpointFact
Fact VehicleFactGroup::_altitudeTuningSetpointFact = Fact(0, QStringLiteral("altitudeTuningSetpoint"), FactMetaData::valueTypeDouble) protected
Definition at line 100 of file VehicleFactGroup.h.
Referenced by Vehicle::setPIDTuningTelemetryMode().
_climbRateFact
Fact VehicleFactGroup::_climbRateFact = Fact(0, QStringLiteral("climbRate"), FactMetaData::valueTypeDouble) protected
Definition at line 95 of file VehicleFactGroup.h.
_distanceToGCSFact
Fact VehicleFactGroup::_distanceToGCSFact = Fact(0, QStringLiteral("distanceToGCS"), FactMetaData::valueTypeDouble) protected
Definition at line 113 of file VehicleFactGroup.h.
_distanceToHomeFact
Fact VehicleFactGroup::_distanceToHomeFact = Fact(0, QStringLiteral("distanceToHome"), FactMetaData::valueTypeDouble) protected
Definition at line 105 of file VehicleFactGroup.h.
Referenced by _handleVfrHud().
_distanceToNextWPFact
Fact VehicleFactGroup::_distanceToNextWPFact = Fact(0, QStringLiteral("distanceToNextWP"), FactMetaData::valueTypeDouble) protected
Definition at line 109 of file VehicleFactGroup.h.
_flightDistanceFact
Fact VehicleFactGroup::_flightDistanceFact = Fact(0, QStringLiteral("flightDistance"), FactMetaData::valueTypeDouble) protected
Definition at line 103 of file VehicleFactGroup.h.
Referenced by Vehicle::updateFlightDistance().
_flightTimeFact
Fact VehicleFactGroup::_flightTimeFact = Fact(0, QStringLiteral("flightTime"), FactMetaData::valueTypeElapsedTimeInSeconds) protected
Definition at line 104 of file VehicleFactGroup.h.
_groundSpeedFact
Fact VehicleFactGroup::_groundSpeedFact = Fact(0, QStringLiteral("groundSpeed"), FactMetaData::valueTypeDouble) protected
Definition at line 92 of file VehicleFactGroup.h.
_headingFact
Fact VehicleFactGroup::_headingFact = Fact(0, QStringLiteral("heading"), FactMetaData::valueTypeDouble) protected
Definition at line 88 of file VehicleFactGroup.h.
_headingFromGCSFact
Fact VehicleFactGroup::_headingFromGCSFact = Fact(0, QStringLiteral("headingFromGCS"),FactMetaData::valueTypeDouble) protected
Definition at line 112 of file VehicleFactGroup.h.
_headingFromHomeFact
Fact VehicleFactGroup::_headingFromHomeFact = Fact(0, QStringLiteral("headingFromHome"),FactMetaData::valueTypeDouble) protected
Definition at line 111 of file VehicleFactGroup.h.
_headingToHomeFact
Fact VehicleFactGroup::_headingToHomeFact = Fact(0, QStringLiteral("headingToHome"), FactMetaData::valueTypeDouble) protected
Definition at line 110 of file VehicleFactGroup.h.
_headingToNextWPFact
Fact VehicleFactGroup::_headingToNextWPFact = Fact(0, QStringLiteral("headingToNextWP"), FactMetaData::valueTypeDouble) protected
Definition at line 108 of file VehicleFactGroup.h.
_hobbsFact
Fact VehicleFactGroup::_hobbsFact = Fact(0, QStringLiteral("hobbs"), FactMetaData::valueTypeString) protected
Definition at line 114 of file VehicleFactGroup.h.
_imuTempFact
Fact VehicleFactGroup::_imuTempFact = Fact(0, QStringLiteral("imuTemp"), FactMetaData::valueTypeInt16) protected
Definition at line 116 of file VehicleFactGroup.h.
_missionItemIndexFact
Fact VehicleFactGroup::_missionItemIndexFact = Fact(0, QStringLiteral("missionItemIndex"), FactMetaData::valueTypeUint16) protected
Definition at line 107 of file VehicleFactGroup.h.
_pitchFact
Fact VehicleFactGroup::_pitchFact = Fact(0, QStringLiteral("pitch"), FactMetaData::valueTypeDouble) protected
Definition at line 87 of file VehicleFactGroup.h.
_pitchRateFact
Fact VehicleFactGroup::_pitchRateFact = Fact(0, QStringLiteral("pitchRate"), FactMetaData::valueTypeDouble) protected
Definition at line 90 of file VehicleFactGroup.h.
_rangeFinderDistFact
Fact VehicleFactGroup::_rangeFinderDistFact = Fact(0, QStringLiteral("rangeFinderDist"), FactMetaData::valueTypeFloat) protected
Definition at line 102 of file VehicleFactGroup.h.
_rollFact
Fact VehicleFactGroup::_rollFact = Fact(0, QStringLiteral("roll"), FactMetaData::valueTypeDouble) protected
Definition at line 86 of file VehicleFactGroup.h.
_rollRateFact
Fact VehicleFactGroup::_rollRateFact = Fact(0, QStringLiteral("rollRate"), FactMetaData::valueTypeDouble) protected
Definition at line 89 of file VehicleFactGroup.h.
_throttlePctFact
Fact VehicleFactGroup::_throttlePctFact = Fact(0, QStringLiteral("throttlePct"), FactMetaData::valueTypeUint16) protected
Definition at line 115 of file VehicleFactGroup.h.
_timeToHomeFact
Fact VehicleFactGroup::_timeToHomeFact = Fact(0, QStringLiteral("timeToHome"), FactMetaData::valueTypeDouble) protected
Definition at line 106 of file VehicleFactGroup.h.
_xTrackErrorFact
Fact VehicleFactGroup::_xTrackErrorFact = Fact(0, QStringLiteral("xTrackError"), FactMetaData::valueTypeDouble) protected
Definition at line 101 of file VehicleFactGroup.h.
_yawRateFact
Fact VehicleFactGroup::_yawRateFact = Fact(0, QStringLiteral("yawRate"), FactMetaData::valueTypeDouble) protected
Definition at line 91 of file VehicleFactGroup.h.
The documentation for this class was generated from the following files:
src/Vehicle/FactGroups/VehicleFactGroup.h
src/Vehicle/FactGroups/VehicleFactGroup.cc