QGroundControl: CameraSection Class Reference
CameraSection Class Reference
#include <CameraSection.h>
Public Types
enum CameraAction {
CameraActionNone , TakePhotosIntervalTime , TakePhotoIntervalDistance , StopTakingPhotos ,
TakeVideo , StopTakingVideo , TakePhoto
}
Signals
bool specifyGimbalChanged (bool specifyGimbal)
bool specifyCameraModeChanged (bool specifyCameraMode)
void specifiedGimbalYawChanged (double gimbalYaw)
void specifiedGimbalPitchChanged (double gimbalPitch)
Signals inherited from Section
void availableChanged (bool available)
void settingsSpecifiedChanged (bool settingsSpecified)
void dirtyChanged (bool dirty)
void itemCountChanged (int itemCount)
Public Member Functions
CameraSection (PlanMasterController *masterController, QObject *parent=nullptr)
bool specifyGimbal READ specifyGimbal WRITE setSpecifyGimbal NOTIFY specifyGimbalChanged (Fact *gimbalPitch READ gimbalPitch CONSTANT) 1(Fact *gimbalYaw READ gimbalYaw CONSTANT) 1(Fact *cameraAction READ cameraAction CONSTANT) 1(Fact *cameraPhotoIntervalTime READ cameraPhotoIntervalTime CONSTANT) 1(Fact *cameraPhotoIntervalDistance READ cameraPhotoIntervalDistance CONSTANT) 1(bool cameraModeSupported READ cameraModeSupported CONSTANT) 1(bool specifyCameraMode READ specifyCameraMode WRITE setSpecifyCameraMode NOTIFY specifyCameraModeChanged) 1(Fact *cameraMode READ cameraMode CONSTANT) bool specifyGimbal(void) const
< true: cameraMode is supported by this vehicle
Fact * gimbalYaw (void)
Fact * gimbalPitch (void)
Fact * cameraAction (void)
Fact * cameraPhotoIntervalTime (void)
Fact * cameraPhotoIntervalDistance (void)
bool cameraModeSupported (void) const
bool specifyCameraMode (void) const
Fact * cameraMode (void)
void setSpecifyGimbal (bool specifyGimbal)
void setSpecifyCameraMode (bool specifyCameraMode)
double specifiedGimbalYaw (void) const
double specifiedGimbalPitch (void) const
bool available (void) const override
bool dirty (void) const override
void setAvailable (bool available) override
void setDirty (bool dirty) override
bool scanForSection (QmlObjectListModel *visualItems, int scanIndex) override
void appendSectionItems (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum) override
int itemCount (void) const override
bool settingsSpecified (void) const override
Public Member Functions inherited from Section
Section (PlanMasterController *masterController, QObject *parent=nullptr)
bool available READ available WRITE setAvailable NOTIFY availableChanged (bool settingsSpecified READ settingsSpecified NOTIFY settingsSpecifiedChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY availableChanged) virtual bool available(void) const =0
Static Public Member Functions
static bool scanStopTakingPhotos (QmlObjectListModel *visualItems, int scanIndex, bool removeScannedItems)
static bool scanStopTakingVideo (QmlObjectListModel *visualItems, int scanIndex, bool removeScannedItems)
static void appendStopTakingPhotos (QList< MissionItem * > &items, int &seqNum, QObject *missionItemParent)
static void appendStopTakingVideo (QList< MissionItem * > &items, int &seqNum, QObject *missionItemParent)
static int stopTakingPhotosCommandCount (void)
static int stopTakingVideoCommandCount (void)
Additional Inherited Members
Protected Attributes inherited from Section
PlanMasterController * _masterController = nullptr
Detailed Description
Definition at line 14 of file CameraSection.h.
Member Enumeration Documentation
CameraAction
enum CameraSection::CameraAction
Enumerator
CameraActionNone
TakePhotosIntervalTime
TakePhotoIntervalDistance
StopTakingPhotos
TakeVideo
StopTakingVideo
TakePhoto
Definition at line 23 of file CameraSection.h.
Constructor & Destructor Documentation
CameraSection()
CameraSection::CameraSection (PlanMasterController * masterController, QObject * parent = nullptr)
Definition at line 13 of file CameraSection.cc.
References FactMetaData::createMapFromJsonFile(), specifyCameraModeChanged(), specifyGimbalChanged(), and Fact::valueChanged().
Member Function Documentation
appendSectionItems()
void CameraSection::appendSectionItems (QList< MissionItem * > & items, QObject * missionItemParent, int & nextSequenceNumber) override virtual
Appends the mission items associated with this section
Parameters
items List to append to
missionItemParent QObject parent for created MissionItems
nextSequenceNumber[in,out] Sequence number for first item, updated as items are added
Implements Section.
Definition at line 106 of file CameraSection.cc.
References appendStopTakingPhotos(), appendStopTakingVideo(), CameraActionNone, StopTakingPhotos, StopTakingVideo, TakePhoto, TakePhotoIntervalDistance, TakePhotosIntervalTime, TakeVideo, and VIDEO_CAPTURE_STATUS_INTERVAL.
Referenced by MissionSettingsItem::appendMissionItems(), and SimpleMissionItem::appendMissionItems().
appendStopTakingPhotos()
void CameraSection::appendStopTakingPhotos (QList< MissionItem * > & items, int & seqNum, QObject * missionItemParent) static
Definition at line 208 of file CameraSection.cc.
Referenced by LandingComplexItem::appendMissionItems(), and appendSectionItems().
appendStopTakingVideo()
void CameraSection::appendStopTakingVideo (QList< MissionItem * > & items, int & seqNum, QObject * missionItemParent) static
Definition at line 230 of file CameraSection.cc.
Referenced by LandingComplexItem::appendMissionItems(), and appendSectionItems().
available()
bool CameraSection::available (void) const inline override
Definition at line 71 of file CameraSection.h.
Referenced by SimpleMissionItem::scanForSections(), setAvailable(), SimpleMissionItem::setMissionFlightStatus(), SimpleMissionItem::specifiedGimbalPitch(), and SimpleMissionItem::specifiedGimbalYaw().
cameraAction()
Fact * CameraSection::cameraAction (void) inline
Definition at line 47 of file CameraSection.h.
Referenced by scanForSection().
cameraMode()
Fact * CameraSection::cameraMode (void) inline
Definition at line 52 of file CameraSection.h.
cameraModeSupported()
bool CameraSection::cameraModeSupported (void) const
Definition at line 569 of file CameraSection.cc.
References Section::_masterController, PlanMasterController::controllerVehicle(), Vehicle::firmwarePlugin(), FirmwarePlugin::supportedMissionCommands(), and QGCMAVLink::VehicleClassGeneric.
cameraPhotoIntervalDistance()
Fact * CameraSection::cameraPhotoIntervalDistance (void) inline
Definition at line 49 of file CameraSection.h.
cameraPhotoIntervalTime()
Fact * CameraSection::cameraPhotoIntervalTime (void) inline
Definition at line 48 of file CameraSection.h.
dirty()
bool CameraSection::dirty (void) const inline override virtual
Implements Section.
Definition at line 72 of file CameraSection.h.
Referenced by setDirty().
gimbalPitch()
Fact * CameraSection::gimbalPitch (void) inline
Definition at line 46 of file CameraSection.h.
Referenced by SimpleMissionItem::setMissionFlightStatus(), and MissionSettingsItem::specifiedGimbalPitch().
gimbalYaw()
Fact * CameraSection::gimbalYaw (void) inline
Definition at line 45 of file CameraSection.h.
Referenced by SimpleMissionItem::setMissionFlightStatus(), and MissionSettingsItem::specifiedGimbalYaw().
itemCount()
int CameraSection::itemCount (void) const override virtual
Returns the number of mission items represented by this section. Signals: itemCountChanged
Implements Section.
Definition at line 81 of file CameraSection.cc.
References CameraActionNone, and itemCount().
Referenced by itemCount(), MissionSettingsItem::lastSequenceNumber(), and SimpleMissionItem::lastSequenceNumber().
scanForSection()
bool CameraSection::scanForSection (QmlObjectListModel * visualItems, int scanIndex) override virtual
Scans the loaded items for the section items
Parameters
visualItems Item list
scanIndex Index to start scanning from
Returns
true: section found, items added, scanIndex updated
Implements Section.
Definition at line 441 of file CameraSection.cc.
References cameraAction(), QmlObjectListModel::count(), scanStopTakingPhotos(), scanStopTakingVideo(), Section::settingsSpecifiedChanged(), StopTakingPhotos, and StopTakingVideo.
Referenced by MissionSettingsItem::scanForMissionSettings(), and SimpleMissionItem::scanForSections().
scanStopTakingPhotos()
bool CameraSection::scanStopTakingPhotos (QmlObjectListModel * visualItems, int scanIndex, bool removeScannedItems) static
Definition at line 306 of file CameraSection.cc.
References MissionItem::command(), SimpleMissionItem::command(), QmlObjectListModel::count(), SimpleMissionItem::missionItem(), MissionItem::param1(), MissionItem::param2(), MissionItem::param3(), MissionItem::param4(), MissionItem::param5(), MissionItem::param6(), MissionItem::param7(), QmlObjectListModel::removeAt(), and QmlObjectListModel::value().
Referenced by LandingComplexItem::_scanForItem(), and scanForSection().
scanStopTakingVideo()
bool CameraSection::scanStopTakingVideo (QmlObjectListModel * visualItems, int scanIndex, bool removeScannedItems) static
Definition at line 398 of file CameraSection.cc.
References SimpleMissionItem::command(), QmlObjectListModel::count(), SimpleMissionItem::missionItem(), MissionItem::param1(), QmlObjectListModel::removeAt(), and QmlObjectListModel::value().
Referenced by LandingComplexItem::_scanForItem(), and scanForSection().
setAvailable()
void CameraSection::setAvailable (bool available) override virtual
Implements Section.
Definition at line 516 of file CameraSection.cc.
References available(), and Section::availableChanged().
setDirty()
void CameraSection::setDirty (bool dirty) override virtual
Implements Section.
Definition at line 98 of file CameraSection.cc.
References dirty(), and Section::dirtyChanged().
Referenced by MissionSettingsItem::setDirty(), and SimpleMissionItem::setDirty().
setSpecifyCameraMode()
void CameraSection::setSpecifyCameraMode (bool specifyCameraMode)
Returns
The gimbal yaw specified by this item, NaN if not specified
Definition at line 73 of file CameraSection.cc.
References specifyCameraMode(), and specifyCameraModeChanged().
setSpecifyGimbal()
void CameraSection::setSpecifyGimbal (bool specifyGimbal)
Definition at line 63 of file CameraSection.cc.
References specifiedGimbalPitch(), specifiedGimbalPitchChanged(), specifiedGimbalYaw(), specifiedGimbalYawChanged(), and specifyGimbalChanged().
settingsSpecified()
bool CameraSection::settingsSpecified (void) const inline override virtual
Implements Section.
Definition at line 78 of file CameraSection.h.
specifiedGimbalPitch()
double CameraSection::specifiedGimbalPitch (void) const
Definition at line 529 of file CameraSection.cc.
Referenced by setSpecifyGimbal(), and SimpleMissionItem::specifiedGimbalPitch().
specifiedGimbalPitchChanged
void CameraSection::specifiedGimbalPitchChanged (double gimbalPitch) signal
Referenced by MissionSettingsItem::MissionSettingsItem(), and setSpecifyGimbal().
specifiedGimbalYaw()
double CameraSection::specifiedGimbalYaw (void) const
Returns
The gimbal pitch specified by this item, NaN if not specified
Definition at line 524 of file CameraSection.cc.
Referenced by setSpecifyGimbal(), and SimpleMissionItem::specifiedGimbalYaw().
specifiedGimbalYawChanged
void CameraSection::specifiedGimbalYawChanged (double gimbalYaw) signal
Referenced by MissionSettingsItem::MissionSettingsItem(), and setSpecifyGimbal().
specifyCameraMode()
bool CameraSection::specifyCameraMode (void) const inline
Definition at line 51 of file CameraSection.h.
Referenced by setSpecifyCameraMode().
specifyCameraModeChanged
bool CameraSection::specifyCameraModeChanged (bool specifyCameraMode) signal
Referenced by CameraSection(), and setSpecifyCameraMode().
specifyGimbalChanged [1/2]
bool CameraSection::specifyGimbalChanged (bool specifyGimbal) signal
specifyGimbalChanged() [2/2]
bool specifyGimbal READ specifyGimbal WRITE setSpecifyGimbal NOTIFY CameraSection::specifyGimbalChanged (Fact *gimbalPitch READ gimbalPitch CONSTANT) const inline
< true: cameraMode is supported by this vehicle
< MAV_CMD_SET_CAMERA_MODE.param2
Definition at line 34 of file CameraSection.h.
Referenced by CameraSection(), and setSpecifyGimbal().
stopTakingPhotosCommandCount()
static int CameraSection::stopTakingPhotosCommandCount (void) inline static
Definition at line 67 of file CameraSection.h.
Referenced by LandingComplexItem::_scanForItem().
stopTakingVideoCommandCount()
static int CameraSection::stopTakingVideoCommandCount (void) inline static
Definition at line 68 of file CameraSection.h.
Referenced by LandingComplexItem::_scanForItem().
The documentation for this class was generated from the following files:
src/MissionManager/CameraSection.h
src/MissionManager/CameraSection.cc