QGroundControl: KMLDomDocument Class Reference
KMLDomDocument Class Reference
Used to convert a Plan to a KML document.
#include <KMLDomDocument.h>
Public Member Functions
KMLDomDocument (const QString &name)
void appendChildToRoot (const QDomNode &child)
QDomElement addFolder (const QString &name)
QDomElement addPlacemark (const QString &name, bool visible)
void addTextElement (QDomElement &parentElement, const QString &name, const QString &value)
void addLookAt (QDomElement &parentElement, const QGeoCoordinate &coord)
void addDescription (QDomElement &parent, const QString &content)
QDomElement addStyle (const QString &id)
void addLineStyle (QDomElement &styleElement, const QColor &color, int width=1, double opacity=1.0)
void addPolyStyle (QDomElement &styleElement, const QColor &color, double opacity=1.0)
QDomElement addPoint (QDomElement &parent, const QGeoCoordinate &coord, const QString &altitudeMode=QLatin1String("absolute"), bool extrude=true)
QDomElement addLineString (QDomElement &parent, const QList< QGeoCoordinate > &coords, const QString &altitudeMode=QLatin1String("absolute"), bool extrude=true, bool tessellate=true)
QDomElement addPolygon (QDomElement &parent, const QList< QGeoCoordinate > &coords, const QString &altitudeMode=QLatin1String("clampToGround"))
Static Public Member Functions
static QString kmlColorString (const QColor &color, double opacity=1)
static QString kmlCoordString (const QGeoCoordinate &coord)
Static Public Attributes
static constexpr const char * kmlNamespace = "http://www.opengis.net/kml/2.2"
static constexpr const char * kmlSchemaLocation = "https://schemas.opengis.net/kml/2.2.0/ogckml22.xsd"
static constexpr const char * xsiNamespace = "http://www.w3.org/2001/XMLSchema-instance"
static constexpr const char * balloonStyleName = "BalloonStyle"
Protected Attributes
QDomElement _rootDocumentElement
Detailed Description
Used to convert a Plan to a KML document.
Definition at line 14 of file KMLDomDocument.h.
Constructor & Destructor Documentation
KMLDomDocument()
KMLDomDocument::KMLDomDocument (const QString & name)
Definition at line 9 of file KMLDomDocument.cc.
Member Function Documentation
addDescription()
void KMLDomDocument::addDescription (QDomElement & parent, const QString & content)
Definition at line 95 of file KMLDomDocument.cc.
addFolder()
QDomElement KMLDomDocument::addFolder (const QString & name)
Definition at line 87 of file KMLDomDocument.cc.
References _rootDocumentElement, and addTextElement().
addLineString()
QDomElement KMLDomDocument::addLineString (QDomElement & parent, const QList< QGeoCoordinate > & coords, const QString & altitudeMode = QLatin1String("absolute"), bool extrude = true, bool tessellate = true)
Definition at line 137 of file KMLDomDocument.cc.
References addTextElement(), and kmlCoordString().
addLineStyle()
void KMLDomDocument::addLineStyle (QDomElement & styleElement, const QColor & color, int width = 1, double opacity = 1.0)
Definition at line 111 of file KMLDomDocument.cc.
References addTextElement(), and kmlColorString().
addLookAt()
void KMLDomDocument::addLookAt (QDomElement & parentElement, const QGeoCoordinate & coord)
Definition at line 58 of file KMLDomDocument.cc.
References addTextElement().
addPlacemark()
QDomElement KMLDomDocument::addPlacemark (const QString & name, bool visible)
Definition at line 71 of file KMLDomDocument.cc.
References _rootDocumentElement, and addTextElement().
Referenced by TransectStyleComplexItem::addKMLVisuals().
addPoint()
QDomElement KMLDomDocument::addPoint (QDomElement & parent, const QGeoCoordinate & coord, const QString & altitudeMode = QLatin1String("absolute"), bool extrude = true)
Definition at line 126 of file KMLDomDocument.cc.
References addTextElement(), and kmlCoordString().
addPolygon()
QDomElement KMLDomDocument::addPolygon (QDomElement & parent, const QList< QGeoCoordinate > & coords, const QString & altitudeMode = QLatin1String("clampToGround"))
Definition at line 155 of file KMLDomDocument.cc.
References addTextElement(), and kmlCoordString().
addPolyStyle()
void KMLDomDocument::addPolyStyle (QDomElement & styleElement, const QColor & color, double opacity = 1.0)
Definition at line 119 of file KMLDomDocument.cc.
References addTextElement(), and kmlColorString().
addStyle()
QDomElement KMLDomDocument::addStyle (const QString & id)
Definition at line 103 of file KMLDomDocument.cc.
References _rootDocumentElement.
addTextElement()
void KMLDomDocument::addTextElement (QDomElement & parentElement, const QString & name, const QString & value)
Definition at line 51 of file KMLDomDocument.cc.
Referenced by addFolder(), TransectStyleComplexItem::addKMLVisuals(), addLineString(), addLineStyle(), addLookAt(), addPlacemark(), addPoint(), addPolygon(), addPolyStyle(), and QGCMapPolygon::kmlPolygonElement().
appendChildToRoot()
void KMLDomDocument::appendChildToRoot (const QDomNode & child)
Definition at line 82 of file KMLDomDocument.cc.
References _rootDocumentElement.
Referenced by TransectStyleComplexItem::addKMLVisuals().
kmlColorString()
QString KMLDomDocument::kmlColorString (const QColor & color, double opacity = 1) static
Definition at line 36 of file KMLDomDocument.cc.
Referenced by addLineStyle(), and addPolyStyle().
kmlCoordString()
QString KMLDomDocument::kmlCoordString (const QGeoCoordinate & coord) static
Definition at line 30 of file KMLDomDocument.cc.
Referenced by addLineString(), addPoint(), addPolygon(), and QGCMapPolygon::kmlPolygonElement().
Member Data Documentation
_rootDocumentElement
QDomElement KMLDomDocument::_rootDocumentElement protected
Definition at line 53 of file KMLDomDocument.h.
Referenced by addFolder(), addPlacemark(), addStyle(), and appendChildToRoot().
balloonStyleName
constexpr const char* KMLDomDocument::balloonStyleName = "BalloonStyle" static constexpr
Definition at line 50 of file KMLDomDocument.h.
kmlNamespace
constexpr const char* KMLDomDocument::kmlNamespace = "http://www.opengis.net/kml/2.2" static constexpr
Definition at line 47 of file KMLDomDocument.h.
Referenced by KMLSchemaValidator::validate().
kmlSchemaLocation
constexpr const char* KMLDomDocument::kmlSchemaLocation = "https://schemas.opengis.net/kml/2.2.0/ogckml22.xsd" static constexpr
Definition at line 48 of file KMLDomDocument.h.
xsiNamespace
constexpr const char* KMLDomDocument::xsiNamespace = "http://www.w3.org/2001/XMLSchema-instance" static constexpr
Definition at line 49 of file KMLDomDocument.h.
The documentation for this class was generated from the following files:
src/Utilities/Geo/KMLDomDocument.h
src/Utilities/Geo/KMLDomDocument.cc