QGroundControl: StatusText Class Reference
StatusText Class Reference
#include <StatusTextHandler.h>
Public Member Functions
StatusText (MAV_COMPONENT componentid, MAV_SEVERITY severity, const QString &text)
bool severityIsError () const
MAV_COMPONENT getComponentID () const
MAV_SEVERITY getSeverity () const
QString getText () const
QString getFormattedText () const
void setFormatedText (const QString &formatedText)
Detailed Description
Definition at line 12 of file StatusTextHandler.h.
Constructor & Destructor Documentation
StatusText()
StatusText::StatusText (MAV_COMPONENT componentid, MAV_SEVERITY severity, const QString & text)
Definition at line 10 of file StatusTextHandler.cc.
Member Function Documentation
getComponentID()
MAV_COMPONENT StatusText::getComponentID () const inline
Definition at line 19 of file StatusTextHandler.h.
getFormattedText()
QString StatusText::getFormattedText () const inline
Definition at line 22 of file StatusTextHandler.h.
getSeverity()
MAV_SEVERITY StatusText::getSeverity () const inline
Definition at line 20 of file StatusTextHandler.h.
getText()
QString StatusText::getText () const inline
Definition at line 21 of file StatusTextHandler.h.
Referenced by StatusTextHandler::handleHTMLEscapedTextMessage().
setFormatedText()
void StatusText::setFormatedText (const QString & formatedText) inline
Definition at line 24 of file StatusTextHandler.h.
Referenced by StatusTextHandler::handleHTMLEscapedTextMessage().
severityIsError()
bool StatusText::severityIsError () const
Definition at line 18 of file StatusTextHandler.cc.
Referenced by StatusTextHandler::handleHTMLEscapedTextMessage().
The documentation for this class was generated from the following files:
src/MAVLink/StatusTextHandler.h
src/MAVLink/StatusTextHandler.cc