QGroundControl: AirframeComponentController Class Reference
AirframeComponentController Class Reference
MVC Controller for AirframeComponent.qml.
#include <AirframeComponentController.h>
Signals
void autostartIdChanged (int newAutostartId)
void showCustomConfigPanelChanged (bool show)
Signals inherited from FactPanelController
void missingParametersAvailable ()
Public Member Functions
AirframeComponentController (void)
~AirframeComponentController ()
bool showCustomConfigPanel MEMBER _showCustomConfigPanel NOTIFY showCustomConfigPanelChanged (QVariantList airframeTypes MEMBER _airframeTypes CONSTANT) 1(QString currentAirframeType MEMBER _currentAirframeType CONSTANT) 1(QString currentVehicleName MEMBER _currentVehicleName CONSTANT) 1(int currentVehicleIndex MEMBER _currentVehicleIndex CONSTANT) 1(int autostartId MEMBER _autostartId NOTIFY autostartIdChanged) 1 void changeAutostart(void)
int currentAirframeIndex (void)
void setCurrentAirframeIndex (int newIndex)
Additional Inherited Members
Protected Member Functions inherited from FactPanelController
bool _allParametersExists (int componentId, const QStringList &names) const
void _reportMissingParameter (int componentId, const QString &name) const
Report a missing parameter.
Protected Attributes inherited from FactPanelController
Vehicle * _vehicle = nullptr
Detailed Description
MVC Controller for AirframeComponent.qml.
Definition at line 11 of file AirframeComponentController.h.
Constructor & Destructor Documentation
AirframeComponentController()
AirframeComponentController::AirframeComponentController (void)
Definition at line 18 of file AirframeComponentController.cc.
References FactPanelController::_allParametersExists(), AirframeComponentAirframes::AirframeInfo_t::autostartId, ParameterManager::defaultComponentId, AirframeComponentAirframes::get(), AirframeComponentAirframes::AirframeType_t::imageResource, AirframeComponentAirframes::AirframeInfo_t::name, AirframeComponentAirframes::AirframeType_t::name, AirframeComponentAirframes::AirframeType_t::rgAirframeInfo, and showCustomConfigPanelChanged().
~AirframeComponentController()
AirframeComponentController::~AirframeComponentController ()
Definition at line 71 of file AirframeComponentController.cc.
Member Function Documentation
autostartIdChanged
void AirframeComponentController::autostartIdChanged (int newAutostartId) signal
currentAirframeIndex()
int AirframeComponentController::currentAirframeIndex (void)
setCurrentAirframeIndex()
void AirframeComponentController::setCurrentAirframeIndex (int newIndex)
showCustomConfigPanelChanged [1/2]
void AirframeComponentController::showCustomConfigPanelChanged (bool show) signal
showCustomConfigPanelChanged() [2/2]
bool showCustomConfigPanel MEMBER _showCustomConfigPanel NOTIFY AirframeComponentController::showCustomConfigPanelChanged (QVariantList airframeTypes MEMBER _airframeTypes CONSTANT)
Referenced by AirframeComponentController().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/AirframeComponentController.h
src/AutoPilotPlugins/PX4/AirframeComponentController.cc