QGroundControl: APMFailsafesComponent Class Reference
APMFailsafesComponent Class Reference
#include <APMFailsafesComponent.h>
Public Member Functions
APMFailsafesComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
QStringList setupCompleteChangedTriggerList () const final
QString name () const final
QString description () const final
QString vehicleConfigJson () const final
Resource path to a VehicleConfig.json page definition, or empty if none.
QString iconResource () const final
bool requiresSetup () const final
bool setupComplete () const final
QUrl setupSource () const final
QUrl summaryQmlSource () const final
bool allowSetupWhileArmed () const final
bool allowSetupWhileFlying () const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file APMFailsafesComponent.h.
Constructor & Destructor Documentation
APMFailsafesComponent()
APMFailsafesComponent::APMFailsafesComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr) explicit
Definition at line 5 of file APMFailsafesComponent.cc.
Member Function Documentation
allowSetupWhileArmed()
bool APMFailsafesComponent::allowSetupWhileArmed (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 22 of file APMFailsafesComponent.h.
allowSetupWhileFlying()
bool APMFailsafesComponent::allowSetupWhileFlying (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 23 of file APMFailsafesComponent.h.
description()
QString APMFailsafesComponent::description (void) const final virtual
Reimplemented from VehicleComponent.
Definition at line 16 of file APMFailsafesComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
iconResource()
QString APMFailsafesComponent::iconResource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 17 of file APMFailsafesComponent.h.
name()
QString APMFailsafesComponent::name (void) const inline final virtual
Implements VehicleComponent.
Definition at line 14 of file APMFailsafesComponent.h.
requiresSetup()
bool APMFailsafesComponent::requiresSetup (void) const inline final virtual
Implements VehicleComponent.
Definition at line 18 of file APMFailsafesComponent.h.
setupComplete()
bool APMFailsafesComponent::setupComplete (void) const inline final virtual
Implements VehicleComponent.
Definition at line 19 of file APMFailsafesComponent.h.
setupCompleteChangedTriggerList()
QStringList APMFailsafesComponent::setupCompleteChangedTriggerList () const inline final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 12 of file APMFailsafesComponent.h.
setupSource()
QUrl APMFailsafesComponent::setupSource (void) const final virtual
Implements VehicleComponent.
Definition at line 30 of file APMFailsafesComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
summaryQmlSource()
QUrl APMFailsafesComponent::summaryQmlSource (void) const final virtual
Implements VehicleComponent.
Definition at line 49 of file APMFailsafesComponent.cc.
References VehicleComponent::_vehicle, and Vehicle::vehicleType().
vehicleConfigJson()
QString APMFailsafesComponent::vehicleConfigJson (void) const final virtual
Resource path to a VehicleConfig.json page definition, or empty if none.
Reimplemented from VehicleComponent.
Definition at line 11 of file APMFailsafesComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMFailsafesComponent.h
src/AutoPilotPlugins/APM/APMFailsafesComponent.cc