QGroundControl: FactGroup Class Reference
FactGroup Class Reference
Used to group Facts together into an object hierarachy.
#include <FactGroup.h>
Signals
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Slots
virtual void _updateAllValues ()
Protected Member Functions
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Used to group Facts together into an object hierarachy.
Definition at line 18 of file FactGroup.h.
Member Function Documentation
_addFact() [1/2]
void FactGroup::_addFact (Fact * fact) inline protected
Definition at line 64 of file FactGroup.h.
References _addFact().
Referenced by _addFact().
_addFact() [2/2]
void FactGroup::_addFact (Fact * fact, const QString & name) protected
Definition at line 113 of file FactGroup.cc.
References _factNames, _nameToFactMap, _nameToFactMetaDataMap, _updateRateMSecs, and factNamesChanged().
Referenced by FactGroupWithId::FactGroupWithId().
_addFactGroup() [1/2]
void FactGroup::_addFactGroup (FactGroup * factGroup) inline protected
Definition at line 66 of file FactGroup.h.
References _addFactGroup().
Referenced by _addFactGroup().
_addFactGroup() [2/2]
void FactGroup::_addFactGroup (FactGroup * factGroup, const QString & name) protected
Definition at line 130 of file FactGroup.cc.
References _nameToFactGroupMap, and factGroupNamesChanged().
Referenced by FactGroupListModel::_findOrAddFactGroupById().
_loadFromJsonArray()
void FactGroup::_loadFromJsonArray (const QJsonArray & jsonArray) protected
Definition at line 30 of file FactGroup.cc.
References _nameToFactMetaDataMap, and FactMetaData::createMapFromJsonArray().
_setTelemetryAvailable()
void FactGroup::_setTelemetryAvailable (bool telemetryAvailable) protected
Definition at line 172 of file FactGroup.cc.
References telemetryAvailableChanged().
Referenced by VehicleFactGroup::_handleAltitude(), VehicleFactGroup::_handleAttitude(), VehicleFactGroup::_handleAttitudeQuaternion(), VehicleGPSFactGroup::_handleGpsRawInt(), VehicleGPSFactGroup::_handleHighLatency(), VehicleGPSFactGroup::_handleHighLatency2(), VehicleHygrometerFactGroup::_handleHygrometerSensor(), VehicleFactGroup::_handleNavControllerOutput(), VehicleFactGroup::_handleRangefinder(), VehicleFactGroup::_handleRawImuTemp(), and VehicleFactGroup::_handleVfrHud().
_updateAllValues
void FactGroup::_updateAllValues () protected virtual slot
Definition at line 142 of file FactGroup.cc.
References _nameToFactMap.
factGroupNamesChanged
void FactGroup::factGroupNamesChanged () signal
Referenced by _addFactGroup(), and InstrumentValueData::InstrumentValueData().
factNamesChanged
void FactGroup::factNamesChanged () signal
Referenced by _addFact().
telemetryAvailableChanged
void FactGroup::telemetryAvailableChanged (bool telemetryAvailable) signal
Referenced by _setTelemetryAvailable().
Member Data Documentation
_factNames
QStringList FactGroup::_factNames protected
Definition at line 75 of file FactGroup.h.
Referenced by _addFact().
_nameToFactGroupMap
QMap<QString, FactGroup*> FactGroup::_nameToFactGroupMap protected
Definition at line 73 of file FactGroup.h.
Referenced by _addFactGroup().
_nameToFactMap
QMap<QString, Fact*> FactGroup::_nameToFactMap protected
Definition at line 72 of file FactGroup.h.
Referenced by _addFact(), and _updateAllValues().
_nameToFactMetaDataMap
QMap<QString, FactMetaData*> FactGroup::_nameToFactMetaDataMap protected
Definition at line 74 of file FactGroup.h.
Referenced by _addFact(), and _loadFromJsonArray().
_updateRateMSecs
const int FactGroup::_updateRateMSecs = 0 protected
Update rate for Fact::valueChanged signals, 0: immediate update.
Definition at line 70 of file FactGroup.h.
Referenced by _addFact().
The documentation for this class was generated from the following files:
src/FactSystem/FactGroup.h
src/FactSystem/FactGroup.cc