QGroundControl: ParameterMetaData Class Reference
ParameterMetaData Class Reference abstract
#include <ParameterMetaData.h>
Classes
struct ValueDescPair
A value/description pair used for enum and bitmask entries.
Public Member Functions
ParameterMetaData (QObject *parent=nullptr)
~ParameterMetaData () override
void loadParameterFactMetaDataFile (const QString &metaDataFile)
FactMetaData * getMetaDataForFact (const QString &name, FactMetaData::ValueType_t type)
Static Public Member Functions
static QVersionNumber versionFromMetaDataFile (const QString &metaDataFile)
static QVersionNumber versionFromJsonData (const QByteArray &jsonData)
static QVersionNumber versionFromJsonData (const QByteArray &jsonData, bool *validJson)
static QVersionNumber versionFromFileName (const QString &fileName)
Static Public Attributes
static const FactMetaData::DefineMap_t kEmptyDefines
Protected Member Functions
virtual void parseParameterJson (const QJsonObject &json)=0
virtual FactMetaData * _lookupMetaData (const QString &name, FactMetaData::ValueType_t type)
virtual FactMetaData * _createDefaultMetaData (const QString &name, FactMetaData::ValueType_t type)
virtual void _postProcessMetaData (const QString &name, FactMetaData *metaData)
Static Protected Member Functions
static bool textToBool (QStringView text)
static bool jsonToBool (const QJsonValue &value)
static bool setRawConvertedValue (FactMetaData *metaData, const QString &rawText, void(FactMetaData::*setter)(const QVariant &))
static void setEnumFromPairs (FactMetaData *metaData, const QList< ValueDescPair > &pairs)
static void setBitmaskFromPairs (FactMetaData *metaData, const QList< ValueDescPair > &pairs)
Protected Attributes
FactMetaData::NameToMetaDataMap_t _cachedMetaData
bool _parameterMetaDataLoaded = false
Detailed Description
Definition at line 12 of file ParameterMetaData.h.
Constructor & Destructor Documentation
ParameterMetaData()
ParameterMetaData::ParameterMetaData (QObject * parent = nullptr) explicit
Definition at line 15 of file ParameterMetaData.cc.
~ParameterMetaData()
ParameterMetaData::~ParameterMetaData () override
Definition at line 21 of file ParameterMetaData.cc.
Member Function Documentation
_createDefaultMetaData()
FactMetaData * ParameterMetaData::_createDefaultMetaData (const QString & name, FactMetaData::ValueType_t type) protected virtual
Reimplemented in APMParameterMetaData.
Definition at line 141 of file ParameterMetaData.cc.
Referenced by getMetaDataForFact().
_lookupMetaData()
FactMetaData * ParameterMetaData::_lookupMetaData (const QString & name, FactMetaData::ValueType_t type) protected virtual
Reimplemented in APMParameterMetaData.
Definition at line 134 of file ParameterMetaData.cc.
Referenced by getMetaDataForFact().
_postProcessMetaData()
void ParameterMetaData::_postProcessMetaData (const QString & name, FactMetaData * metaData) protected virtual
Reimplemented in APMParameterMetaData, and PX4ParameterMetaData.
Definition at line 147 of file ParameterMetaData.cc.
Referenced by getMetaDataForFact().
getMetaDataForFact()
FactMetaData * ParameterMetaData::getMetaDataForFact (const QString & name, FactMetaData::ValueType_t type)
Definition at line 55 of file ParameterMetaData.cc.
References _cachedMetaData, _createDefaultMetaData(), _lookupMetaData(), and _postProcessMetaData().
jsonToBool()
static bool ParameterMetaData::jsonToBool (const QJsonValue & value) inline static protected
Definition at line 41 of file ParameterMetaData.h.
References textToBool().
Referenced by APMParameterMetaData::_lookupMetaData().
loadParameterFactMetaDataFile()
void ParameterMetaData::loadParameterFactMetaDataFile (const QString & metaDataFile)
Definition at line 26 of file ParameterMetaData.cc.
References _parameterMetaDataLoaded, errorString, JsonParsing::isJsonFile(), and parseParameterJson().
Referenced by FirmwarePlugin::loadParameterMetaData().
parseParameterJson()
virtual void ParameterMetaData::parseParameterJson (const QJsonObject & json) protected pure virtual
Implemented in APMParameterMetaData, and PX4ParameterMetaData.
Referenced by loadParameterFactMetaDataFile().
setBitmaskFromPairs()
void ParameterMetaData::setBitmaskFromPairs (FactMetaData * metaData, const QList< ValueDescPair > & pairs) static protected
Definition at line 186 of file ParameterMetaData.cc.
References FactMetaData::convertAndValidateRaw(), errorString, FactMetaData::name(), and FactMetaData::setBitmaskInfo().
setEnumFromPairs()
void ParameterMetaData::setEnumFromPairs (FactMetaData * metaData, const QList< ValueDescPair > & pairs) static protected
Definition at line 165 of file ParameterMetaData.cc.
References FactMetaData::convertAndValidateRaw(), errorString, FactMetaData::name(), and FactMetaData::setEnumInfo().
setRawConvertedValue()
bool ParameterMetaData::setRawConvertedValue (FactMetaData * metaData, const QString & rawText, void(FactMetaData::*)(const QVariant &) setter) static protected
Definition at line 153 of file ParameterMetaData.cc.
References FactMetaData::convertAndValidateRaw(), errorString, and FactMetaData::name().
Referenced by APMParameterMetaData::_lookupMetaData().
textToBool()
static bool ParameterMetaData::textToBool (QStringView text) inline static protected
Definition at line 40 of file ParameterMetaData.h.
Referenced by jsonToBool().
versionFromFileName()
QVersionNumber ParameterMetaData::versionFromFileName (const QString & fileName) static
Definition at line 124 of file ParameterMetaData.cc.
Referenced by FirmwarePlugin::_cachedParameterMetaDataFile(), and FirmwarePlugin::cacheParameterMetaDataFile().
versionFromJsonData() [1/2]
QVersionNumber ParameterMetaData::versionFromJsonData (const QByteArray & jsonData) static
Definition at line 77 of file ParameterMetaData.cc.
References versionFromJsonData().
Referenced by FirmwarePlugin::cacheParameterMetaDataFile(), versionFromJsonData(), and versionFromMetaDataFile().
versionFromJsonData() [2/2]
QVersionNumber ParameterMetaData::versionFromJsonData (const QByteArray & jsonData, bool * validJson) static
Definition at line 82 of file ParameterMetaData.cc.
References errorString, and JsonParsing::isJsonFile().
versionFromMetaDataFile()
QVersionNumber ParameterMetaData::versionFromMetaDataFile (const QString & metaDataFile) static
Definition at line 112 of file ParameterMetaData.cc.
References errorString, QGCFileHelper::readFile(), and versionFromJsonData().
Referenced by FirmwarePlugin::_cachedParameterMetaDataFile().
Member Data Documentation
_cachedMetaData
FactMetaData::NameToMetaDataMap_t ParameterMetaData::_cachedMetaData protected
Definition at line 46 of file ParameterMetaData.h.
Referenced by getMetaDataForFact(), and PX4ParameterMetaData::parseParameterJson().
_parameterMetaDataLoaded
bool ParameterMetaData::_parameterMetaDataLoaded = false protected
Definition at line 47 of file ParameterMetaData.h.
Referenced by loadParameterFactMetaDataFile().
kEmptyDefines
const FactMetaData::DefineMap_t ParameterMetaData::kEmptyDefines static
Definition at line 26 of file ParameterMetaData.h.
Referenced by PX4ParameterMetaData::parseParameterJson(), and CompInfoParam::setJson().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/ParameterMetaData.h
src/FirmwarePlugin/ParameterMetaData.cc