QGroundControl: MavlinkCameraControlInterface Class Reference
MavlinkCameraControlInterface Class Reference abstract
Abstract base class for all camera controls: real and simulated.
#include <MavlinkCameraControlInterface.h>
Public Types
enum CameraMode { CAM_MODE_UNDEFINED = -1 , CAM_MODE_PHOTO = 0 , CAM_MODE_VIDEO = 1 , CAM_MODE_SURVEY = 2 }
enum PhotoCaptureMode { PHOTO_CAPTURE_SINGLE = 0 , PHOTO_CAPTURE_TIMELAPSE }
enum CaptureVideoState { CaptureVideoStateDisabled = 0 , CaptureVideoStateIdle , CaptureVideoStateCapturing }
enum CapturePhotosState { CapturePhotosStateDisabled = 0 , CapturePhotosStateIdle , CapturePhotosStateCapturingSinglePhoto , CapturePhotosStateCapturingMultiplePhotos }
enum StorageStatus { STORAGE_EMPTY = STORAGE_STATUS_EMPTY , STORAGE_UNFORMATTED = STORAGE_STATUS_UNFORMATTED , STORAGE_READY = STORAGE_STATUS_READY , STORAGE_NOT_SUPPORTED = STORAGE_STATUS_NOT_SUPPORTED }
enum ThermalViewMode { THERMAL_OFF = 0 , THERMAL_BLEND , THERMAL_FULL , THERMAL_PIP }
Signals
void infoChanged ()
void videoCaptureStatusChanged ()
void photoCaptureStatusChanged ()
void photoCaptureModeChanged ()
void photoLapseChanged ()
void photoLapseCountChanged ()
void cameraModeChanged ()
void activeSettingsChanged ()
void storageFreeChanged ()
void storageTotalChanged ()
void batteryRemainingChanged ()
void dataReady (const QByteArray &data)
void parametersReady ()
void zoomLevelChanged ()
void focusLevelChanged ()
void streamsChanged ()
void currentStreamChanged ()
void thermalStreamChanged ()
void autoStreamChanged ()
void recordTimeChanged ()
void streamLabelsChanged ()
void trackingEnabledChanged ()
void trackingImageIsActiveChanged ()
void trackingImageIsPointChanged ()
void trackingImageRectChanged ()
void trackingImagePointChanged ()
void trackingImageRadiusChanged ()
void thermalModeChanged ()
void thermalOpacityChanged ()
void storageStatusChanged ()
void captureVideoStateChanged ()
void capturePhotosStateChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Public Member Functions
MavlinkCameraControlInterface (Vehicle *vehicle, QObject *parent=nullptr)
virtual ~MavlinkCameraControlInterface ()
virtual void setCameraModeVideo ()=0
virtual void setCameraModePhoto ()=0
virtual void toggleCameraMode ()=0
virtual bool takePhoto ()=0
virtual bool stopTakePhoto ()=0
virtual bool startVideoRecording ()=0
virtual bool stopVideoRecording ()=0
virtual bool toggleVideoRecording ()=0
virtual void resetSettings ()=0
virtual void formatCard (int id=1)=0
virtual void stepZoom (int direction)=0
virtual void startZoom (int direction)=0
virtual void stopZoom ()=0
virtual void stepFocus (int direction)=0
virtual void startFocus (int direction)=0
virtual void stopFocus ()=0
virtual void stopStream ()=0
virtual void resumeStream ()=0
virtual void startTrackingRect (QRectF rec)=0
virtual void startTrackingPoint (QPointF point, double radius)=0
virtual void stopTracking ()=0
virtual int version () const =0
virtual QString modelName () const =0
virtual QString vendor () const =0
virtual QString firmwareVersion () const =0
virtual qreal focalLength () const =0
virtual QSizeF sensorSize () const =0
virtual QSize resolution () const =0
virtual bool capturesVideo () const =0
virtual bool capturesPhotos () const =0
virtual bool hasModes () const =0
virtual bool hasZoom () const =0
virtual bool hasFocus () const =0
virtual bool hasTracking () const =0
virtual bool supportsTrackingPoint () const =0
virtual bool supportsTrackingRect () const =0
virtual bool hasVideoStream () const =0
virtual bool photosInVideoMode () const =0
virtual bool videoInPhotoMode () const =0
virtual CaptureVideoState captureVideoState () const =0
virtual CapturePhotosState capturePhotosState () const =0
virtual int compID () const =0
virtual bool isBasic () const =0
virtual PhotoCaptureMode photoCaptureMode () const
virtual qreal photoLapse () const
virtual int photoLapseCount () const
virtual CameraMode cameraMode () const
virtual StorageStatus storageStatus () const =0
virtual QStringList activeSettings () const =0
virtual quint32 storageFree () const =0
virtual QString storageFreeStr () const =0
virtual quint32 storageTotal () const =0
virtual int batteryRemaining () const =0
virtual QString batteryRemainingStr () const =0
virtual bool paramComplete () const =0
virtual qreal zoomLevel () const =0
virtual qreal focusLevel () const =0
virtual QmlObjectListModel * streams ()=0
virtual QGCVideoStreamInfo * currentStreamInstance ()=0
virtual QGCVideoStreamInfo * thermalStreamInstance ()=0
virtual int currentStream () const =0
virtual void setCurrentStream (int stream)=0
virtual bool autoStream () const =0
virtual quint32 recordTime () const =0
virtual QString recordTimeStr () const =0
virtual Fact * exposureMode ()=0
virtual Fact * ev ()=0
virtual Fact * iso ()=0
virtual Fact * shutterSpeed ()=0
virtual Fact * aperture ()=0
virtual Fact * wb ()=0
virtual Fact * mode ()=0
virtual QStringList streamLabels () const =0
Stream names to show the user (for selection)
virtual ThermalViewMode thermalMode () const =0
virtual void setThermalMode (ThermalViewMode mode)=0
virtual double thermalOpacity () const =0
virtual void setThermalOpacity (double val)=0
virtual void setZoomLevel (qreal level)=0
virtual void setFocusLevel (qreal level)=0
virtual void setCameraMode (CameraMode cameraMode)=0
virtual void setPhotoCaptureMode (PhotoCaptureMode mode)=0
virtual void setPhotoLapse (qreal interval)=0
virtual void setPhotoLapseCount (int count)=0
virtual bool trackingEnabled () const =0
virtual void setTrackingEnabled (bool set)=0
virtual bool trackingImageIsActive () const =0
virtual bool trackingImageIsPoint () const =0
virtual QRectF trackingImageRect () const =0
virtual QPointF trackingImagePoint () const =0
virtual qreal trackingImageRadius () const =0
virtual void factChanged (Fact *pFact)=0
Notify controller a parameter has changed.
virtual bool incomingParameter (Fact *pFact, QVariant &newValue)=0
Allow controller to modify or invalidate incoming parameter.
virtual bool validateParameter (Fact *pFact, QVariant &newValue)=0
Allow controller to modify or invalidate parameter change.
virtual void handleBatteryStatus (const mavlink_battery_status_t &bs)=0
virtual void handleCameraCaptureStatus (const mavlink_camera_capture_status_t &cameraCaptureStatus)=0
virtual void handleParamExtAck (const mavlink_param_ext_ack_t &paramExtAck)=0
virtual void handleParamExtValue (const mavlink_param_ext_value_t &paramExtValue)=0
virtual void handleCameraSettings (const mavlink_camera_settings_t &settings)=0
virtual void handleStorageInformation (const mavlink_storage_information_t &storageInformation)=0
virtual void handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t &trackingImageStatus)=0
virtual void handleVideoStreamInformation (const mavlink_video_stream_information_t &videoStreamInformation)=0
virtual void handleVideoStreamStatus (const mavlink_video_stream_status_t &videoStreamStatus)=0
QString cameraModeToStr (CameraMode mode)
QString captureImageStatusToStr (uint8_t image_status)
QString captureVideoStatusToStr (uint8_t video_status)
QString storageStatusToStr (uint8_t status)
Protected Types
enum VideoCaptureStatus { VIDEO_CAPTURE_STATUS_STOPPED = 0 , VIDEO_CAPTURE_STATUS_RUNNING , VIDEO_CAPTURE_STATUS_LAST , VIDEO_CAPTURE_STATUS_UNDEFINED = 255 }
enum PhotoCaptureStatus {
PHOTO_CAPTURE_IDLE = 0 , PHOTO_CAPTURE_IN_PROGRESS , PHOTO_CAPTURE_INTERVAL_IDLE , PHOTO_CAPTURE_INTERVAL_IN_PROGRESS ,
PHOTO_CAPTURE_LAST , PHOTO_CAPTURE_STATUS_UNDEFINED = 255
}
Protected Slots
virtual void _paramDone ()=0
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Protected Member Functions
VideoCaptureStatus _videoCaptureStatus () const
PhotoCaptureStatus _photoCaptureStatus () const
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
Vehicle * _vehicle = nullptr
CameraMode _cameraMode = CAM_MODE_UNDEFINED
VideoCaptureStatus _videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED
PhotoCaptureStatus _photoCaptureStatusValue = PHOTO_CAPTURE_IDLE
PhotoCaptureMode _photoCaptureMode = PHOTO_CAPTURE_SINGLE
qreal _photoLapse = 1.0
int _photoLapseCount = 0
QTimer _videoRecordTimeUpdateTimer
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Abstract base class for all camera controls: real and simulated.
Definition at line 18 of file MavlinkCameraControlInterface.h.
Member Enumeration Documentation
CameraMode
enum MavlinkCameraControlInterface::CameraMode
Enumerator
CAM_MODE_UNDEFINED
CAM_MODE_PHOTO
CAM_MODE_VIDEO
CAM_MODE_SURVEY
Definition at line 103 of file MavlinkCameraControlInterface.h.
CapturePhotosState
enum MavlinkCameraControlInterface::CapturePhotosState
Enumerator
CapturePhotosStateDisabled
CapturePhotosStateIdle
CapturePhotosStateCapturingSinglePhoto
CapturePhotosStateCapturingMultiplePhotos
Definition at line 124 of file MavlinkCameraControlInterface.h.
CaptureVideoState
enum MavlinkCameraControlInterface::CaptureVideoState
Enumerator
CaptureVideoStateDisabled
CaptureVideoStateIdle
CaptureVideoStateCapturing
Definition at line 117 of file MavlinkCameraControlInterface.h.
PhotoCaptureMode
enum MavlinkCameraControlInterface::PhotoCaptureMode
Enumerator
PHOTO_CAPTURE_SINGLE
PHOTO_CAPTURE_TIMELAPSE
Definition at line 111 of file MavlinkCameraControlInterface.h.
PhotoCaptureStatus
enum MavlinkCameraControlInterface::PhotoCaptureStatus protected
Enumerator
PHOTO_CAPTURE_IDLE
PHOTO_CAPTURE_IN_PROGRESS
PHOTO_CAPTURE_INTERVAL_IDLE
PHOTO_CAPTURE_INTERVAL_IN_PROGRESS
PHOTO_CAPTURE_LAST
PHOTO_CAPTURE_STATUS_UNDEFINED
Definition at line 313 of file MavlinkCameraControlInterface.h.
StorageStatus
enum MavlinkCameraControlInterface::StorageStatus
Enumerator
STORAGE_EMPTY
STORAGE_UNFORMATTED
STORAGE_READY
STORAGE_NOT_SUPPORTED
Definition at line 132 of file MavlinkCameraControlInterface.h.
ThermalViewMode
enum MavlinkCameraControlInterface::ThermalViewMode
Enumerator
THERMAL_OFF
THERMAL_BLEND
THERMAL_FULL
THERMAL_PIP
Definition at line 140 of file MavlinkCameraControlInterface.h.
VideoCaptureStatus
enum MavlinkCameraControlInterface::VideoCaptureStatus protected
Enumerator
VIDEO_CAPTURE_STATUS_STOPPED
VIDEO_CAPTURE_STATUS_RUNNING
VIDEO_CAPTURE_STATUS_LAST
VIDEO_CAPTURE_STATUS_UNDEFINED
Definition at line 306 of file MavlinkCameraControlInterface.h.
Constructor & Destructor Documentation
MavlinkCameraControlInterface()
MavlinkCameraControlInterface::MavlinkCameraControlInterface (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 7 of file MavlinkCameraControlInterface.cc.
~MavlinkCameraControlInterface()
MavlinkCameraControlInterface::~MavlinkCameraControlInterface () virtual
Definition at line 14 of file MavlinkCameraControlInterface.cc.
Member Function Documentation
_paramDone
virtual void MavlinkCameraControlInterface::_paramDone () protected pure virtual slot
Referenced by QGCCameraParamIO::handleParamValue(), and QGCCameraParamIO::paramRequest().
_photoCaptureStatus()
PhotoCaptureStatus MavlinkCameraControlInterface::_photoCaptureStatus () const inline protected
Definition at line 323 of file MavlinkCameraControlInterface.h.
References _photoCaptureStatusValue.
Referenced by SimulatedCameraControl::capturePhotosState(), VehicleCameraControl::capturePhotosState(), SimulatedCameraControl::captureVideoState(), VehicleCameraControl::captureVideoState(), VehicleCameraControl::handleCameraCaptureStatus(), and SimulatedCameraControl::takePhoto().
_videoCaptureStatus()
VideoCaptureStatus MavlinkCameraControlInterface::_videoCaptureStatus () const inline protected
Definition at line 322 of file MavlinkCameraControlInterface.h.
References _videoCaptureStatusValue.
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), SimulatedCameraControl::captureVideoState(), VehicleCameraControl::captureVideoState(), VehicleCameraControl::handleCameraCaptureStatus(), SimulatedCameraControl::startVideoRecording(), SimulatedCameraControl::stopVideoRecording(), and SimulatedCameraControl::toggleVideoRecording().
activeSettings()
virtual QStringList MavlinkCameraControlInterface::activeSettings () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
activeSettingsChanged
void MavlinkCameraControlInterface::activeSettingsChanged () signal
aperture()
virtual Fact * MavlinkCameraControlInterface::aperture () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
autoStream()
virtual bool MavlinkCameraControlInterface::autoStream () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
autoStreamChanged
void MavlinkCameraControlInterface::autoStreamChanged () signal
Referenced by VehicleCameraControl::_streamInfoTimeout(), and VehicleCameraControl::handleVideoStreamInformation().
batteryRemaining()
virtual int MavlinkCameraControlInterface::batteryRemaining () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
batteryRemainingChanged
void MavlinkCameraControlInterface::batteryRemainingChanged () signal
Referenced by VehicleCameraControl::handleBatteryStatus().
batteryRemainingStr()
virtual QString MavlinkCameraControlInterface::batteryRemainingStr () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
cameraMode()
virtual CameraMode MavlinkCameraControlInterface::cameraMode () const inline virtual
Definition at line 197 of file MavlinkCameraControlInterface.h.
References _cameraMode.
Referenced by SimulatedCameraControl::setCameraMode(), and VehicleCameraControl::setCameraMode().
cameraModeChanged
void MavlinkCameraControlInterface::cameraModeChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setCameraMode(), and SimulatedCameraControl::SimulatedCameraControl().
cameraModeToStr()
QString MavlinkCameraControlInterface::cameraModeToStr (CameraMode mode)
Definition at line 63 of file MavlinkCameraControlInterface.cc.
References CAM_MODE_PHOTO, CAM_MODE_SURVEY, CAM_MODE_UNDEFINED, CAM_MODE_VIDEO, and mode().
Referenced by SimulatedCameraControl::setCameraMode(), VehicleCameraControl::setCameraMode(), and SimulatedCameraControl::takePhoto().
captureImageStatusToStr()
QString MavlinkCameraControlInterface::captureImageStatusToStr (uint8_t image_status)
Definition at line 19 of file MavlinkCameraControlInterface.cc.
References PHOTO_CAPTURE_IDLE, PHOTO_CAPTURE_IN_PROGRESS, PHOTO_CAPTURE_INTERVAL_IDLE, and PHOTO_CAPTURE_INTERVAL_IN_PROGRESS.
Referenced by VehicleCameraControl::handleCameraCaptureStatus().
capturePhotosState()
virtual CapturePhotosState MavlinkCameraControlInterface::capturePhotosState () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
capturePhotosStateChanged
void MavlinkCameraControlInterface::capturePhotosStateChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
capturesPhotos()
virtual bool MavlinkCameraControlInterface::capturesPhotos () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
capturesVideo()
virtual bool MavlinkCameraControlInterface::capturesVideo () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
captureVideoState()
virtual CaptureVideoState MavlinkCameraControlInterface::captureVideoState () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
captureVideoStateChanged
void MavlinkCameraControlInterface::captureVideoStateChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
captureVideoStatusToStr()
QString MavlinkCameraControlInterface::captureVideoStatusToStr (uint8_t video_status)
Definition at line 35 of file MavlinkCameraControlInterface.cc.
References VIDEO_CAPTURE_STATUS_RUNNING, and VIDEO_CAPTURE_STATUS_STOPPED.
Referenced by VehicleCameraControl::handleCameraCaptureStatus().
compID()
virtual int MavlinkCameraControlInterface::compID () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::paramRequest().
currentStream()
virtual int MavlinkCameraControlInterface::currentStream () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_stepStream().
currentStreamChanged
void MavlinkCameraControlInterface::currentStreamChanged () signal
Referenced by VehicleCameraControl::setCurrentStream().
currentStreamInstance()
virtual QGCVideoStreamInfo * MavlinkCameraControlInterface::currentStreamInstance () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
dataReady
void MavlinkCameraControlInterface::dataReady (const QByteArray & data) signal
Referenced by VehicleCameraControl::_downloadFinished(), and VehicleCameraControl::VehicleCameraControl().
ev()
virtual Fact * MavlinkCameraControlInterface::ev () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
exposureMode()
virtual Fact * MavlinkCameraControlInterface::exposureMode () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
factChanged()
virtual void MavlinkCameraControlInterface::factChanged (Fact * pFact) pure virtual
Notify controller a parameter has changed.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamAck(), and QGCCameraParamIO::handleParamValue().
firmwareVersion()
virtual QString MavlinkCameraControlInterface::firmwareVersion () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
focalLength()
virtual qreal MavlinkCameraControlInterface::focalLength () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
focusLevel()
virtual qreal MavlinkCameraControlInterface::focusLevel () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
focusLevelChanged
void MavlinkCameraControlInterface::focusLevelChanged () signal
Referenced by VehicleCameraControl::handleCameraSettings().
formatCard()
virtual void MavlinkCameraControlInterface::formatCard (int id = 1) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleBatteryStatus()
virtual void MavlinkCameraControlInterface::handleBatteryStatus (const mavlink_battery_status_t & bs) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleCameraCaptureStatus()
virtual void MavlinkCameraControlInterface::handleCameraCaptureStatus (const mavlink_camera_capture_status_t & cameraCaptureStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleCameraSettings()
virtual void MavlinkCameraControlInterface::handleCameraSettings (const mavlink_camera_settings_t & settings) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleParamExtAck()
virtual void MavlinkCameraControlInterface::handleParamExtAck (const mavlink_param_ext_ack_t & paramExtAck) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleParamExtValue()
virtual void MavlinkCameraControlInterface::handleParamExtValue (const mavlink_param_ext_value_t & paramExtValue) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleStorageInformation()
virtual void MavlinkCameraControlInterface::handleStorageInformation (const mavlink_storage_information_t & storageInformation) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleTrackingImageStatus()
virtual void MavlinkCameraControlInterface::handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t & trackingImageStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleVideoStreamInformation()
virtual void MavlinkCameraControlInterface::handleVideoStreamInformation (const mavlink_video_stream_information_t & videoStreamInformation) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleVideoStreamStatus()
virtual void MavlinkCameraControlInterface::handleVideoStreamStatus (const mavlink_video_stream_status_t & videoStreamStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasFocus()
virtual bool MavlinkCameraControlInterface::hasFocus () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasModes()
virtual bool MavlinkCameraControlInterface::hasModes () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasTracking()
virtual bool MavlinkCameraControlInterface::hasTracking () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasVideoStream()
virtual bool MavlinkCameraControlInterface::hasVideoStream () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasZoom()
virtual bool MavlinkCameraControlInterface::hasZoom () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
incomingParameter()
virtual bool MavlinkCameraControlInterface::incomingParameter (Fact * pFact, QVariant & newValue) pure virtual
Allow controller to modify or invalidate incoming parameter.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamValue().
infoChanged
void MavlinkCameraControlInterface::infoChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
isBasic()
virtual bool MavlinkCameraControlInterface::isBasic () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
iso()
virtual Fact * MavlinkCameraControlInterface::iso () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
mode()
virtual Fact * MavlinkCameraControlInterface::mode () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by cameraModeToStr().
modelName()
virtual QString MavlinkCameraControlInterface::modelName () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
paramComplete()
virtual bool MavlinkCameraControlInterface::paramComplete () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
parametersReady
void MavlinkCameraControlInterface::parametersReady () signal
Referenced by VehicleCameraControl::_initWhenReady(), and VehicleCameraControl::_paramDone().
photoCaptureMode()
virtual PhotoCaptureMode MavlinkCameraControlInterface::photoCaptureMode () const inline virtual
Definition at line 194 of file MavlinkCameraControlInterface.h.
References _photoCaptureMode.
Referenced by VehicleCameraControl::handleCameraCaptureStatus(), SimulatedCameraControl::setPhotoCaptureMode(), and SimulatedCameraControl::takePhoto().
photoCaptureModeChanged
void MavlinkCameraControlInterface::photoCaptureModeChanged () signal
Referenced by SimulatedCameraControl::setPhotoCaptureMode(), and VehicleCameraControl::setPhotoCaptureMode().
photoCaptureStatusChanged
void MavlinkCameraControlInterface::photoCaptureStatusChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setPhotoCaptureStatus(), SimulatedCameraControl::SimulatedCameraControl(), and SimulatedCameraControl::takePhoto().
photoLapse()
virtual qreal MavlinkCameraControlInterface::photoLapse () const inline virtual
Definition at line 195 of file MavlinkCameraControlInterface.h.
References _photoLapse.
photoLapseChanged
void MavlinkCameraControlInterface::photoLapseChanged () signal
Referenced by VehicleCameraControl::setPhotoLapse().
photoLapseCount()
virtual int MavlinkCameraControlInterface::photoLapseCount () const inline virtual
Definition at line 196 of file MavlinkCameraControlInterface.h.
References _photoLapseCount.
photoLapseCountChanged
void MavlinkCameraControlInterface::photoLapseCountChanged () signal
Referenced by VehicleCameraControl::setPhotoLapseCount().
photosInVideoMode()
virtual bool MavlinkCameraControlInterface::photosInVideoMode () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
recordTime()
virtual quint32 MavlinkCameraControlInterface::recordTime () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
recordTimeChanged
void MavlinkCameraControlInterface::recordTimeChanged () signal
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), VehicleCameraControl::_recTimerHandler(), VehicleCameraControl::_setVideoCaptureStatus(), VehicleCameraControl::handleCameraCaptureStatus(), and SimulatedCameraControl::SimulatedCameraControl().
recordTimeStr()
virtual QString MavlinkCameraControlInterface::recordTimeStr () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
resetSettings()
virtual void MavlinkCameraControlInterface::resetSettings () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
resolution()
virtual QSize MavlinkCameraControlInterface::resolution () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
resumeStream()
virtual void MavlinkCameraControlInterface::resumeStream () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
sensorSize()
virtual QSizeF MavlinkCameraControlInterface::sensorSize () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
setCameraMode()
virtual void MavlinkCameraControlInterface::setCameraMode (CameraMode cameraMode) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
setCameraModePhoto()
virtual void MavlinkCameraControlInterface::setCameraModePhoto () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
setCameraModeVideo()
virtual void MavlinkCameraControlInterface::setCameraModeVideo () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
setCurrentStream()
virtual void MavlinkCameraControlInterface::setCurrentStream (int stream) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepStream().
setFocusLevel()
virtual void MavlinkCameraControlInterface::setFocusLevel (qreal level) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setPhotoCaptureMode()
virtual void MavlinkCameraControlInterface::setPhotoCaptureMode (PhotoCaptureMode mode) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
setPhotoLapse()
virtual void MavlinkCameraControlInterface::setPhotoLapse (qreal interval) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setPhotoLapseCount()
virtual void MavlinkCameraControlInterface::setPhotoLapseCount (int count) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setThermalMode()
virtual void MavlinkCameraControlInterface::setThermalMode (ThermalViewMode mode) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setThermalOpacity()
virtual void MavlinkCameraControlInterface::setThermalOpacity (double val) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setTrackingEnabled()
virtual void MavlinkCameraControlInterface::setTrackingEnabled (bool set) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setZoomLevel()
virtual void MavlinkCameraControlInterface::setZoomLevel (qreal level) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
shutterSpeed()
virtual Fact * MavlinkCameraControlInterface::shutterSpeed () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
startFocus()
virtual void MavlinkCameraControlInterface::startFocus (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_startFocus().
startTrackingPoint()
virtual void MavlinkCameraControlInterface::startTrackingPoint (QPointF point, double radius) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
startTrackingRect()
virtual void MavlinkCameraControlInterface::startTrackingRect (QRectF rec) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
startVideoRecording()
virtual bool MavlinkCameraControlInterface::startVideoRecording () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_startVideoRecording().
startZoom()
virtual void MavlinkCameraControlInterface::startZoom (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_startZoom().
stepFocus()
virtual void MavlinkCameraControlInterface::stepFocus (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepFocus().
stepZoom()
virtual void MavlinkCameraControlInterface::stepZoom (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepZoom().
stopFocus()
virtual void MavlinkCameraControlInterface::stopFocus () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_stopFocus().
stopStream()
virtual void MavlinkCameraControlInterface::stopStream () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
stopTakePhoto()
virtual bool MavlinkCameraControlInterface::stopTakePhoto () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
stopTracking()
virtual void MavlinkCameraControlInterface::stopTracking () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
stopVideoRecording()
virtual bool MavlinkCameraControlInterface::stopVideoRecording () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_stopVideoRecording().
stopZoom()
virtual void MavlinkCameraControlInterface::stopZoom () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_stopZoom().
storageFree()
virtual quint32 MavlinkCameraControlInterface::storageFree () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
storageFreeChanged
void MavlinkCameraControlInterface::storageFreeChanged () signal
Referenced by VehicleCameraControl::handleCameraCaptureStatus(), and VehicleCameraControl::handleStorageInformation().
storageFreeStr()
virtual QString MavlinkCameraControlInterface::storageFreeStr () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
storageStatus()
virtual StorageStatus MavlinkCameraControlInterface::storageStatus () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
storageStatusChanged
void MavlinkCameraControlInterface::storageStatusChanged () signal
Referenced by VehicleCameraControl::handleStorageInformation().
storageStatusToStr()
QString MavlinkCameraControlInterface::storageStatusToStr (uint8_t status)
Definition at line 47 of file MavlinkCameraControlInterface.cc.
Referenced by VehicleCameraControl::handleStorageInformation().
storageTotal()
virtual quint32 MavlinkCameraControlInterface::storageTotal () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
storageTotalChanged
void MavlinkCameraControlInterface::storageTotalChanged () signal
Referenced by VehicleCameraControl::handleStorageInformation().
streamLabels()
virtual QStringList MavlinkCameraControlInterface::streamLabels () const pure virtual
Stream names to show the user (for selection)
Implemented in SimulatedCameraControl, and VehicleCameraControl.
streamLabelsChanged
void MavlinkCameraControlInterface::streamLabelsChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
streams()
virtual QmlObjectListModel * MavlinkCameraControlInterface::streams () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_stepStream().
streamsChanged
void MavlinkCameraControlInterface::streamsChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
supportsTrackingPoint()
virtual bool MavlinkCameraControlInterface::supportsTrackingPoint () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
supportsTrackingRect()
virtual bool MavlinkCameraControlInterface::supportsTrackingRect () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
takePhoto()
virtual bool MavlinkCameraControlInterface::takePhoto () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_triggerCamera().
thermalMode()
virtual ThermalViewMode MavlinkCameraControlInterface::thermalMode () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
thermalModeChanged
void MavlinkCameraControlInterface::thermalModeChanged () signal
Referenced by VehicleCameraControl::setThermalMode().
thermalOpacity()
virtual double MavlinkCameraControlInterface::thermalOpacity () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
thermalOpacityChanged
void MavlinkCameraControlInterface::thermalOpacityChanged () signal
Referenced by VehicleCameraControl::setThermalOpacity().
thermalStreamChanged
void MavlinkCameraControlInterface::thermalStreamChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
thermalStreamInstance()
virtual QGCVideoStreamInfo * MavlinkCameraControlInterface::thermalStreamInstance () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
toggleCameraMode()
virtual void MavlinkCameraControlInterface::toggleCameraMode () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
toggleVideoRecording()
virtual bool MavlinkCameraControlInterface::toggleVideoRecording () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraManager::_toggleVideoRecording().
trackingEnabled()
virtual bool MavlinkCameraControlInterface::trackingEnabled () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingEnabledChanged
void MavlinkCameraControlInterface::trackingEnabledChanged () signal
Referenced by VehicleCameraControl::setTrackingEnabled().
trackingImageIsActive()
virtual bool MavlinkCameraControlInterface::trackingImageIsActive () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingImageIsActiveChanged
void MavlinkCameraControlInterface::trackingImageIsActiveChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus(), and VehicleCameraControl::stopTracking().
trackingImageIsPoint()
virtual bool MavlinkCameraControlInterface::trackingImageIsPoint () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingImageIsPointChanged
void MavlinkCameraControlInterface::trackingImageIsPointChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus(), and VehicleCameraControl::stopTracking().
trackingImagePoint()
virtual QPointF MavlinkCameraControlInterface::trackingImagePoint () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingImagePointChanged
void MavlinkCameraControlInterface::trackingImagePointChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus().
trackingImageRadius()
virtual qreal MavlinkCameraControlInterface::trackingImageRadius () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingImageRadiusChanged
void MavlinkCameraControlInterface::trackingImageRadiusChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus().
trackingImageRect()
virtual QRectF MavlinkCameraControlInterface::trackingImageRect () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
trackingImageRectChanged
void MavlinkCameraControlInterface::trackingImageRectChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus().
validateParameter()
virtual bool MavlinkCameraControlInterface::validateParameter (Fact * pFact, QVariant & newValue) pure virtual
Allow controller to modify or invalidate parameter change.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamAck().
vendor()
virtual QString MavlinkCameraControlInterface::vendor () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
version()
virtual int MavlinkCameraControlInterface::version () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
videoCaptureStatusChanged
void MavlinkCameraControlInterface::videoCaptureStatusChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setVideoCaptureStatus(), and SimulatedCameraControl::SimulatedCameraControl().
videoInPhotoMode()
virtual bool MavlinkCameraControlInterface::videoInPhotoMode () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
wb()
virtual Fact * MavlinkCameraControlInterface::wb () pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
zoomLevel()
virtual qreal MavlinkCameraControlInterface::zoomLevel () const pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
zoomLevelChanged
void MavlinkCameraControlInterface::zoomLevelChanged () signal
Referenced by VehicleCameraControl::handleCameraSettings().
Member Data Documentation
_cameraMode
CameraMode MavlinkCameraControlInterface::_cameraMode = CAM_MODE_UNDEFINED protected
Definition at line 326 of file MavlinkCameraControlInterface.h.
Referenced by VehicleCameraControl::_setCameraMode(), cameraMode(), VehicleCameraControl::captureVideoState(), VehicleCameraControl::setCameraMode(), SimulatedCameraControl::startVideoRecording(), SimulatedCameraControl::takePhoto(), VehicleCameraControl::takePhoto(), SimulatedCameraControl::toggleCameraMode(), and VehicleCameraControl::toggleCameraMode().
_photoCaptureMode
PhotoCaptureMode MavlinkCameraControlInterface::_photoCaptureMode = PHOTO_CAPTURE_SINGLE protected
Definition at line 329 of file MavlinkCameraControlInterface.h.
Referenced by photoCaptureMode(), SimulatedCameraControl::setPhotoCaptureMode(), VehicleCameraControl::setPhotoCaptureMode(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_photoCaptureStatusValue
PhotoCaptureStatus MavlinkCameraControlInterface::_photoCaptureStatusValue = PHOTO_CAPTURE_IDLE protected
Definition at line 328 of file MavlinkCameraControlInterface.h.
Referenced by _photoCaptureStatus(), VehicleCameraControl::_setPhotoCaptureStatus(), and SimulatedCameraControl::takePhoto().
_photoLapse
qreal MavlinkCameraControlInterface::_photoLapse = 1.0 protected
Definition at line 330 of file MavlinkCameraControlInterface.h.
Referenced by photoLapse(), VehicleCameraControl::setPhotoLapse(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_photoLapseCount
int MavlinkCameraControlInterface::_photoLapseCount = 0 protected
Definition at line 331 of file MavlinkCameraControlInterface.h.
Referenced by photoLapseCount(), VehicleCameraControl::setPhotoLapseCount(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_vehicle
Vehicle* MavlinkCameraControlInterface::_vehicle = nullptr protected
Definition at line 325 of file MavlinkCameraControlInterface.h.
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_mavCommandResult(), VehicleCameraControl::_requestAllParameters(), VehicleCameraControl::_requestCameraSettings(), VehicleCameraControl::_requestCaptureStatus(), VehicleCameraControl::_requestStorageInfo(), VehicleCameraControl::_requestStreamInfo(), VehicleCameraControl::_requestStreamStatus(), VehicleCameraControl::_requestTrackingStatus(), VehicleCameraControl::_streamInfoTimeout(), VehicleCameraControl::formatCard(), VehicleCameraControl::handleVideoStreamInformation(), VehicleCameraControl::resetSettings(), VehicleCameraControl::resumeStream(), VehicleCameraControl::setCameraMode(), VehicleCameraControl::setCurrentStream(), VehicleCameraControl::setFocusLevel(), VehicleCameraControl::setZoomLevel(), VehicleCameraControl::startFocus(), VehicleCameraControl::startTrackingPoint(), VehicleCameraControl::startTrackingRect(), VehicleCameraControl::startVideoRecording(), VehicleCameraControl::startZoom(), VehicleCameraControl::stepFocus(), VehicleCameraControl::stepZoom(), VehicleCameraControl::stopFocus(), VehicleCameraControl::stopStream(), VehicleCameraControl::stopTakePhoto(), VehicleCameraControl::stopTracking(), VehicleCameraControl::stopVideoRecording(), VehicleCameraControl::stopZoom(), SimulatedCameraControl::takePhoto(), and VehicleCameraControl::takePhoto().
_videoCaptureStatusValue
VideoCaptureStatus MavlinkCameraControlInterface::_videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED protected
Definition at line 327 of file MavlinkCameraControlInterface.h.
Referenced by VehicleCameraControl::_setVideoCaptureStatus(), and _videoCaptureStatus().
_videoRecordTimeUpdateTimer
QTimer MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer protected
Definition at line 332 of file MavlinkCameraControlInterface.h.
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), VehicleCameraControl::_setVideoCaptureStatus(), SimulatedCameraControl::recordTime(), SimulatedCameraControl::startVideoRecording(), SimulatedCameraControl::stopVideoRecording(), VehicleCameraControl::VehicleCameraControl(), and VehicleCameraControl::~VehicleCameraControl().
The documentation for this class was generated from the following files:
src/Camera/MavlinkCameraControlInterface.h
src/Camera/MavlinkCameraControlInterface.cc