QGroundControl: APMAutoPilotPlugin Class Reference
APMAutoPilotPlugin Class Reference
This is the AutoPilotPlugin implementation for the MAV_AUTOPILOT_ARDUPILOT type.
#include <APMAutoPilotPlugin.h>
Public Member Functions
APMAutoPilotPlugin (Vehicle *vehicle, QObject *parent=nullptr)
~APMAutoPilotPlugin ()
const QVariantList & vehicleComponents () override
QString prerequisiteSetup (VehicleComponent *component) const override
Returns the name of the vehicle component which must complete setup prior to this one. Empty string for none.
Protected Attributes
bool _incorrectParameterVersion = false
true: parameter version incorrect, setup not allowed
APMAirframeComponent * _airframeComponent = nullptr
APMAirspeedComponent * _airspeedComponent = nullptr
APMGimbalComponent * _gimbalComponent = nullptr
APMLightsComponent * _lightsComponent = nullptr
APMSubFrameComponent * _subFrameComponent = nullptr
APMFlightModesComponent * _flightModesComponent = nullptr
APMServoComponent * _servoComponent = nullptr
APMPowerComponent * _powerComponent = nullptr
APMESCComponent * _escComponent = nullptr
APMMotorComponent * _motorComponent = nullptr
APMRadioComponent * _radioComponent = nullptr
APMFailsafesComponent * _failsafesComponent = nullptr
APMFlightSafetyComponent * _flightSafetyComponent = nullptr
APMSensorsComponent * _sensorsComponent = nullptr
APMTuningComponent * _tuningComponent = nullptr
APMAdvancedTuningCopterComponent * _advancedTuningCopterComponent = nullptr
ESP8266Component * _esp8266Component = nullptr
APMHeliComponent * _heliComponent = nullptr
APMRemoteSupportComponent * _apmRemoteSupportComponent = nullptr
APMFollowComponent * _followComponent = nullptr
JoystickComponent * _joystickComponent = nullptr
ScriptingComponent * _scriptingComponent = nullptr
Protected Attributes inherited from AutoPilotPlugin
Vehicle * _vehicle = nullptr
FirmwarePlugin * _firmwarePlugin = nullptr
bool _setupComplete = false
Additional Inherited Members
Signals inherited from AutoPilotPlugin
void setupCompleteChanged ()
void vehicleComponentsChanged ()
Detailed Description
This is the AutoPilotPlugin implementation for the MAV_AUTOPILOT_ARDUPILOT type.
Definition at line 33 of file APMAutoPilotPlugin.h.
Constructor & Destructor Documentation
APMAutoPilotPlugin()
APMAutoPilotPlugin::APMAutoPilotPlugin (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 44 of file APMAutoPilotPlugin.cc.
References ParameterManager::parametersReadyChanged().
~APMAutoPilotPlugin()
APMAutoPilotPlugin::~APMAutoPilotPlugin ()
Definition at line 54 of file APMAutoPilotPlugin.cc.
Member Function Documentation
prerequisiteSetup()
QString APMAutoPilotPlugin::prerequisiteSetup (VehicleComponent * component) const override virtual
Returns the name of the vehicle component which must complete setup prior to this one. Empty string for none.
Implements AutoPilotPlugin.
Definition at line 189 of file APMAutoPilotPlugin.cc.
References _airframeComponent, _radioComponent, APMAirframeComponent::name(), APMRadioComponent::name(), APMAirframeComponent::setupComplete(), and APMRadioComponent::setupComplete().
vehicleComponents()
const QVariantList & APMAutoPilotPlugin::vehicleComponents (void) override virtual
Implements AutoPilotPlugin.
Definition at line 59 of file APMAutoPilotPlugin.cc.
References _advancedTuningCopterComponent, _airframeComponent, _airspeedComponent, _apmRemoteSupportComponent, _escComponent, _esp8266Component, _failsafesComponent, _flightModesComponent, _flightSafetyComponent, _followComponent, _gimbalComponent, _heliComponent, _incorrectParameterVersion, _joystickComponent, _lightsComponent, _motorComponent, _powerComponent, _radioComponent, _scriptingComponent, _sensorsComponent, _servoComponent, _subFrameComponent, _tuningComponent, AutoPilotPlugin::_vehicle, Vehicle::firmwarePlugin(), Vehicle::multiRotor(), ParameterManager::parameterExists(), Vehicle::parameterManager(), ParameterManager::parametersReady(), VehicleSupports::radio(), Vehicle::sub(), Vehicle::supports(), Vehicle::vehicleType(), and Vehicle::versionCompare().
Member Data Documentation
_advancedTuningCopterComponent
APMAdvancedTuningCopterComponent* APMAutoPilotPlugin::_advancedTuningCopterComponent = nullptr protected
Definition at line 61 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_airframeComponent
APMAirframeComponent* APMAutoPilotPlugin::_airframeComponent = nullptr protected
Definition at line 46 of file APMAutoPilotPlugin.h.
Referenced by prerequisiteSetup(), and vehicleComponents().
_airspeedComponent
APMAirspeedComponent* APMAutoPilotPlugin::_airspeedComponent = nullptr protected
Definition at line 47 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_apmRemoteSupportComponent
APMRemoteSupportComponent* APMAutoPilotPlugin::_apmRemoteSupportComponent = nullptr protected
Definition at line 64 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_escComponent
APMESCComponent* APMAutoPilotPlugin::_escComponent = nullptr protected
Definition at line 54 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_esp8266Component
ESP8266Component* APMAutoPilotPlugin::_esp8266Component = nullptr protected
Definition at line 62 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_failsafesComponent
APMFailsafesComponent* APMAutoPilotPlugin::_failsafesComponent = nullptr protected
Definition at line 57 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_flightModesComponent
APMFlightModesComponent* APMAutoPilotPlugin::_flightModesComponent = nullptr protected
Definition at line 51 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_flightSafetyComponent
APMFlightSafetyComponent* APMAutoPilotPlugin::_flightSafetyComponent = nullptr protected
Definition at line 58 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_followComponent
APMFollowComponent* APMAutoPilotPlugin::_followComponent = nullptr protected
Definition at line 65 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_gimbalComponent
APMGimbalComponent* APMAutoPilotPlugin::_gimbalComponent = nullptr protected
Definition at line 48 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_heliComponent
APMHeliComponent* APMAutoPilotPlugin::_heliComponent = nullptr protected
Definition at line 63 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_incorrectParameterVersion
bool APMAutoPilotPlugin::_incorrectParameterVersion = false protected
true: parameter version incorrect, setup not allowed
Definition at line 45 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_joystickComponent
JoystickComponent* APMAutoPilotPlugin::_joystickComponent = nullptr protected
Definition at line 66 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_lightsComponent
APMLightsComponent* APMAutoPilotPlugin::_lightsComponent = nullptr protected
Definition at line 49 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_motorComponent
APMMotorComponent* APMAutoPilotPlugin::_motorComponent = nullptr protected
Definition at line 55 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_powerComponent
APMPowerComponent* APMAutoPilotPlugin::_powerComponent = nullptr protected
Definition at line 53 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_radioComponent
APMRadioComponent* APMAutoPilotPlugin::_radioComponent = nullptr protected
Definition at line 56 of file APMAutoPilotPlugin.h.
Referenced by prerequisiteSetup(), and vehicleComponents().
_scriptingComponent
ScriptingComponent* APMAutoPilotPlugin::_scriptingComponent = nullptr protected
Definition at line 67 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_sensorsComponent
APMSensorsComponent* APMAutoPilotPlugin::_sensorsComponent = nullptr protected
Definition at line 59 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_servoComponent
APMServoComponent* APMAutoPilotPlugin::_servoComponent = nullptr protected
Definition at line 52 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_subFrameComponent
APMSubFrameComponent* APMAutoPilotPlugin::_subFrameComponent = nullptr protected
Definition at line 50 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
_tuningComponent
APMTuningComponent* APMAutoPilotPlugin::_tuningComponent = nullptr protected
Definition at line 60 of file APMAutoPilotPlugin.h.
Referenced by vehicleComponents().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.h
src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc