QGroundControl: Qt6GLVideoItem Class Reference
Qt6GLVideoItem Class Reference
#include <qt6glitem.h>
Signals
void itemInitializedChanged ()
void forceAspectRatioChanged (bool)
Protected Member Functions
QSGNode * updatePaintNode (QSGNode *oldNode, UpdatePaintNodeData *updatePaintNodeData) override
void releaseResources () override
void wheelEvent (QWheelEvent *) override
void hoverEnterEvent (QHoverEvent *) override
void hoverLeaveEvent (QHoverEvent *) override
void hoverMoveEvent (QHoverEvent *) override
void mousePressEvent (QMouseEvent *) override
void mouseReleaseEvent (QMouseEvent *) override
void touchEvent (QTouchEvent *) override
Detailed Description
Definition at line 65 of file qt6glitem.h.
Member Function Documentation
forceAspectRatioChanged
void Qt6GLVideoItem::forceAspectRatioChanged (bool) signal
hoverEnterEvent()
void Qt6GLVideoItem::hoverEnterEvent (QHoverEvent *) override protected
Definition at line 422 of file qt6glitem.cc.
hoverLeaveEvent()
void Qt6GLVideoItem::hoverLeaveEvent (QHoverEvent *) override protected
Definition at line 428 of file qt6glitem.cc.
hoverMoveEvent()
void Qt6GLVideoItem::hoverMoveEvent (QHoverEvent * event) override protected
Definition at line 434 of file qt6glitem.cc.
itemInitializedChanged
void Qt6GLVideoItem::itemInitializedChanged () signal
mousePressEvent()
void Qt6GLVideoItem::mousePressEvent (QMouseEvent * event) override protected
Definition at line 452 of file qt6glitem.cc.
mouseReleaseEvent()
void Qt6GLVideoItem::mouseReleaseEvent (QMouseEvent * event) override protected
Definition at line 459 of file qt6glitem.cc.
releaseResources()
void Qt6GLVideoItem::releaseResources () override protected
Definition at line 643 of file qt6glitem.cc.
References _Qt6GLVideoItemPrivate::m_node.
touchEvent()
void Qt6GLVideoItem::touchEvent (QTouchEvent * event) override protected
Definition at line 440 of file qt6glitem.cc.
updatePaintNode()
QSGNode * Qt6GLVideoItem::updatePaintNode (QSGNode * oldNode, UpdatePaintNodeData * updatePaintNodeData) override protected
Definition at line 274 of file qt6glitem.cc.
References _Qt6GLVideoItemPrivate::bound_buffers, _Qt6GLVideoItemPrivate::buffer, _Qt6GLVideoItemPrivate::caps, _Qt6GLVideoItemPrivate::display_height, _Qt6GLVideoItemPrivate::display_width, _Qt6GLVideoItemPrivate::force_aspect_ratio, GstQSG6OpenGLNode::getBuffer(), _Qt6GLVideoItemPrivate::initted, _Qt6GLVideoItemPrivate::lock, _Qt6GLVideoItemPrivate::m_node, _Qt6GLVideoItemPrivate::other_context, _Qt6GLVideoItemPrivate::potentially_unbound_buffers, GstQSG6OpenGLNode::setBuffer(), and GstQSG6OpenGLNode::setCaps().
wheelEvent()
void Qt6GLVideoItem::wheelEvent (QWheelEvent * event) override protected
Definition at line 416 of file qt6glitem.cc.
The documentation for this class was generated from the following files:
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/qt6/qt6glitem.h
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/qt6/qt6glitem.cc