QGroundControl: HealthAndArmingCheckReport Class Reference
HealthAndArmingCheckReport Class Reference
#include <HealthAndArmingCheckReport.h>
Signals
void updated ()
Public Member Functions
bool supported READ supported NOTIFY updated (bool canArm READ canArm NOTIFY updated) 1(bool canTakeoff READ canTakeoff NOTIFY updated) 1(bool canStartMission READ canStartMission NOTIFY updated) 1(bool hasWarningsOrErrors READ hasWarningsOrErrors NOTIFY updated) 1(QString gpsState READ gpsState NOTIFY updated) 1(QmlObjectListModel *problemsForCurrentMode READ problemsForCurrentMode NOTIFY updated) HealthAndArmingCheckReport(QObject *parent
virtual ~HealthAndArmingCheckReport ()
bool supported () const
bool canArm () const
bool canTakeoff () const
bool canStartMission () const
bool hasWarningsOrErrors () const
const QString & gpsState () const
QmlObjectListModel * problemsForCurrentMode ()
void update (uint8_t compid, const events::HealthAndArmingChecks::Results &results, int flightModeGroup)
void setModeGroups (int takeoffModeGroup, int missionModeGroup)
Detailed Description
Definition at line 39 of file HealthAndArmingCheckReport.h.
Constructor & Destructor Documentation
~HealthAndArmingCheckReport()
HealthAndArmingCheckReport::~HealthAndArmingCheckReport () virtual
Definition at line 23 of file HealthAndArmingCheckReport.cc.
References QmlObjectListModel::clearAndDeleteContents().
Member Function Documentation
canArm()
bool HealthAndArmingCheckReport::canArm () const inline
Definition at line 57 of file HealthAndArmingCheckReport.h.
canStartMission()
bool HealthAndArmingCheckReport::canStartMission () const inline
Definition at line 59 of file HealthAndArmingCheckReport.h.
canTakeoff()
bool HealthAndArmingCheckReport::canTakeoff () const inline
Definition at line 58 of file HealthAndArmingCheckReport.h.
gpsState()
const QString & HealthAndArmingCheckReport::gpsState () const inline
Definition at line 62 of file HealthAndArmingCheckReport.h.
Referenced by update().
hasWarningsOrErrors()
bool HealthAndArmingCheckReport::hasWarningsOrErrors () const inline
Definition at line 60 of file HealthAndArmingCheckReport.h.
problemsForCurrentMode()
QmlObjectListModel * HealthAndArmingCheckReport::problemsForCurrentMode () inline
Definition at line 64 of file HealthAndArmingCheckReport.h.
setModeGroups()
void HealthAndArmingCheckReport::setModeGroups (int takeoffModeGroup, int missionModeGroup)
Definition at line 84 of file HealthAndArmingCheckReport.cc.
Referenced by Vehicle::setEventsMetadata().
supported()
bool HealthAndArmingCheckReport::supported () const inline
Definition at line 56 of file HealthAndArmingCheckReport.h.
update()
void HealthAndArmingCheckReport::update (uint8_t compid, const events::HealthAndArmingChecks::Results & results, int flightModeGroup)
Definition at line 28 of file HealthAndArmingCheckReport.cc.
References QmlObjectListModel::append(), QmlObjectListModel::clearAndDeleteContents(), gpsState(), and updated().
updated [1/2]
void HealthAndArmingCheckReport::updated () signal
Referenced by update().
updated() [2/2]
bool supported READ supported NOTIFY HealthAndArmingCheckReport::updated (bool canArm READ canArm NOTIFY updated)
The documentation for this class was generated from the following files:
src/MAVLink/LibEvents/HealthAndArmingCheckReport.h
src/MAVLink/LibEvents/HealthAndArmingCheckReport.cc