QGroundControl: UrlFactory Class Reference
UrlFactory Class Reference
#include <QGCMapUrlEngine.h>
Static Public Member Functions
static QString getImageFormat (QStringView type, QByteArrayView image)
static QString getImageFormat (int qtMapId, QByteArrayView image)
static QUrl getTileURL (QStringView type, int x, int y, int zoom)
static QUrl getTileURL (int qtMapId, int x, int y, int zoom)
static quint32 averageSizeForType (QStringView type)
static bool isElevation (int qtMapId)
static int long2tileX (QStringView mapType, double lon, int z)
static int lat2tileY (QStringView mapType, double lat, int z)
static QGCTileSet getTileCount (int zoom, double topleftLon, double topleftLat, double bottomRightLon, double bottomRightLat, QStringView mapType)
static const QList< std::shared_ptr< const MapProvider > > & getProviders ()
static QStringList getElevationProviderTypes ()
static QStringList getProviderTypes ()
static int getQtMapIdFromProviderType (QStringView type)
static QString getProviderTypeFromQtMapId (int qtMapId)
static std::shared_ptr< const MapProvider > getMapProviderFromQtMapId (int qtMapId)
static std::shared_ptr< const MapProvider > getMapProviderFromProviderType (QStringView type)
static QString providerTypeFromHash (int hash)
static int hashFromProviderType (QStringView type)
static QString tileHashToType (QStringView tileHash)
static QString getTileHash (QStringView type, int x, int y, int z)
Detailed Description
Definition at line 12 of file QGCMapUrlEngine.h.
Member Function Documentation
averageSizeForType()
quint32 UrlFactory::averageSizeForType (QStringView type) static
Definition at line 114 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType(), and QGC_AVERAGE_TILE_SIZE.
Referenced by QGCTileCacheDatabase::computeSetTotals().
getElevationProviderTypes()
QStringList UrlFactory::getElevationProviderTypes () static
Definition at line 230 of file QGCMapUrlEngine.cpp.
getImageFormat() [1/2]
QString UrlFactory::getImageFormat (int qtMapId, QByteArrayView image) static
Definition at line 74 of file QGCMapUrlEngine.cpp.
References getMapProviderFromQtMapId().
getImageFormat() [2/2]
QString UrlFactory::getImageFormat (QStringView type, QByteArrayView image) static
Definition at line 84 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType().
getMapProviderFromProviderType()
SharedMapProvider UrlFactory::getMapProviderFromProviderType (QStringView type) static
Definition at line 198 of file QGCMapUrlEngine.cpp.
Referenced by averageSizeForType(), TerrainTileManager::getAltitudesForCoordinates(), getImageFormat(), getTileCount(), getTileURL(), lat2tileY(), and long2tileX().
getMapProviderFromQtMapId()
SharedMapProvider UrlFactory::getMapProviderFromQtMapId (int qtMapId) static
Definition at line 182 of file QGCMapUrlEngine.cpp.
Referenced by getImageFormat(), QGeoTileFetcherQGC::getNetworkRequest(), getTileURL(), isElevation(), and Viewer3DTileQuery::maxTileCount().
getProviders()
static const QList< std::shared_ptr< const MapProvider > > & UrlFactory::getProviders () inline static
Definition at line 32 of file QGCMapUrlEngine.h.
Referenced by QGeoTiledMappingManagerEngineQGC::QGeoTiledMappingManagerEngineQGC().
getProviderTypeFromQtMapId()
QString UrlFactory::getProviderTypeFromQtMapId (int qtMapId) static
Definition at line 166 of file QGCMapUrlEngine.cpp.
Referenced by QGCTileCacheDatabase::getTile(), and QGeoTiledMapReplyQGC::init().
getProviderTypes()
QStringList UrlFactory::getProviderTypes () static
Definition at line 242 of file QGCMapUrlEngine.cpp.
getQtMapIdFromProviderType()
int UrlFactory::getQtMapIdFromProviderType (QStringView type) static
Definition at line 214 of file QGCMapUrlEngine.cpp.
Referenced by QGCTileCacheDatabase::createTileSet(), and QGCTileCacheDatabase::saveTile().
getTileCount()
QGCTileSet UrlFactory::getTileCount (int zoom, double topleftLon, double topleftLat, double bottomRightLon, double bottomRightLat, QStringView mapType) static
Definition at line 154 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType(), and QGC_MAX_MAP_ZOOM.
Referenced by QGCTileCacheDatabase::createTileSet().
getTileHash()
QString UrlFactory::getTileHash (QStringView type, int x, int y, int z) static
Definition at line 283 of file QGCMapUrlEngine.cpp.
References hashFromProviderType().
Referenced by QGeoFileTileCacheQGC::cacheTile(), QGeoFileTileCacheQGC::createFetchTileTask(), QGCTileCacheDatabase::createTileSet(), and TerrainTileManager::getAltitudesForCoordinates().
getTileURL() [1/2]
QUrl UrlFactory::getTileURL (int qtMapId, int x, int y, int zoom) static
Definition at line 94 of file QGCMapUrlEngine.cpp.
References getMapProviderFromQtMapId().
getTileURL() [2/2]
QUrl UrlFactory::getTileURL (QStringView type, int x, int y, int zoom) static
Definition at line 104 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType().
hashFromProviderType()
int UrlFactory::hashFromProviderType (QStringView type) static
Definition at line 265 of file QGCMapUrlEngine.cpp.
Referenced by getTileHash(), and providerTypeFromHash().
isElevation()
bool UrlFactory::isElevation (int qtMapId) static
Definition at line 124 of file QGCMapUrlEngine.cpp.
References getMapProviderFromQtMapId().
lat2tileY()
int UrlFactory::lat2tileY (QStringView mapType, double lat, int z) static
Definition at line 144 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType().
long2tileX()
int UrlFactory::long2tileX (QStringView mapType, double lon, int z) static
Definition at line 134 of file QGCMapUrlEngine.cpp.
References getMapProviderFromProviderType().
providerTypeFromHash()
QString UrlFactory::providerTypeFromHash (int hash) static
Definition at line 252 of file QGCMapUrlEngine.cpp.
References hashFromProviderType().
Referenced by tileHashToType().
tileHashToType()
QString UrlFactory::tileHashToType (QStringView tileHash) static
Definition at line 277 of file QGCMapUrlEngine.cpp.
References providerTypeFromHash().
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGCMapUrlEngine.h
src/QtLocationPlugin/QGCMapUrlEngine.cpp