QGroundControl: PowerComponentController Class Reference
PowerComponentController Class Reference
Power Component MVC Controller for PowerComponent.qml.
#include <PowerComponentController.h>
Signals
void oldFirmware (void)
void newerFirmware (void)
void incorrectFirmwareRevReporting (void)
void connectBattery (void)
void disconnectBattery (void)
void batteryConnected (void)
void calibrationFailed (const QString &errorMessage)
void calibrationSuccess (const QStringList &warningMessages)
Signals inherited from FactPanelController
void missingParametersAvailable ()
Public Member Functions
PowerComponentController (void)
void calibrateEsc (void)
void startBusConfigureActuators (void)
void stopBusConfigureActuators (void)
Additional Inherited Members
Protected Member Functions inherited from FactPanelController
bool _allParametersExists (int componentId, const QStringList &names) const
void _reportMissingParameter (int componentId, const QString &name) const
Report a missing parameter.
Protected Attributes inherited from FactPanelController
Vehicle * _vehicle = nullptr
Detailed Description
Power Component MVC Controller for PowerComponent.qml.
Definition at line 8 of file PowerComponentController.h.
Constructor & Destructor Documentation
PowerComponentController()
PowerComponentController::PowerComponentController (void)
Definition at line 4 of file PowerComponentController.cc.
Member Function Documentation
batteryConnected
void PowerComponentController::batteryConnected (void) signal
calibrateEsc()
void PowerComponentController::calibrateEsc (void)
Definition at line 9 of file PowerComponentController.cc.
References FactPanelController::_vehicle, QGCMAVLink::CalibrationEsc, Vehicle::startCalibration(), and Vehicle::textMessageReceived().
calibrationFailed
void PowerComponentController::calibrationFailed (const QString & errorMessage) signal
calibrationSuccess
void PowerComponentController::calibrationSuccess (const QStringList & warningMessages) signal
connectBattery
void PowerComponentController::connectBattery (void) signal
disconnectBattery
void PowerComponentController::disconnectBattery (void) signal
incorrectFirmwareRevReporting
void PowerComponentController::incorrectFirmwareRevReporting (void) signal
newerFirmware
void PowerComponentController::newerFirmware (void) signal
oldFirmware
void PowerComponentController::oldFirmware (void) signal
startBusConfigureActuators()
void PowerComponentController::startBusConfigureActuators (void)
Definition at line 16 of file PowerComponentController.cc.
References FactPanelController::_vehicle, Vehicle::startUAVCANBusConfig(), and Vehicle::textMessageReceived().
stopBusConfigureActuators()
void PowerComponentController::stopBusConfigureActuators (void)
Definition at line 23 of file PowerComponentController.cc.
References FactPanelController::_vehicle, Vehicle::stopUAVCANBusConfig(), and Vehicle::textMessageReceived().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/PowerComponentController.h
src/AutoPilotPlugins/PX4/PowerComponentController.cc