QGroundControl: QGCMAVLink Class Reference
QGCMAVLink Class Reference
#include <QGCMAVLink.h>
Public Types
enum MAV_BATTERY_FUNCTION {
MAV_BATTERY_FUNCTION_UNKNOWN =0 , MAV_BATTERY_FUNCTION_ALL =1 , MAV_BATTERY_FUNCTION_PROPULSION =2 , MAV_BATTERY_FUNCTION_AVIONICS =3 ,
MAV_BATTERY_TYPE_PAYLOAD =4
}
enum MAV_BATTERY_CHARGE_STATE {
MAV_BATTERY_CHARGE_STATE_UNDEFINED =0 , MAV_BATTERY_CHARGE_STATE_OK =1 , MAV_BATTERY_CHARGE_STATE_LOW =2 , MAV_BATTERY_CHARGE_STATE_CRITICAL =3 ,
MAV_BATTERY_CHARGE_STATE_EMERGENCY =4 , MAV_BATTERY_CHARGE_STATE_FAILED =5 , MAV_BATTERY_CHARGE_STATE_UNHEALTHY =6 , MAV_BATTERY_CHARGE_STATE_CHARGING =7
}
enum MavlinkSysStatus {
SysStatusSensor3dGyro = MAV_SYS_STATUS_SENSOR_3D_GYRO , SysStatusSensor3dAccel = MAV_SYS_STATUS_SENSOR_3D_ACCEL , SysStatusSensor3dMag = MAV_SYS_STATUS_SENSOR_3D_MAG , SysStatusSensorAbsolutePressure = MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE ,
SysStatusSensorDifferentialPressure = MAV_SYS_STATUS_SENSOR_DIFFERENTIAL_PRESSURE , SysStatusSensorGPS = MAV_SYS_STATUS_SENSOR_GPS , SysStatusSensorOpticalFlow = MAV_SYS_STATUS_SENSOR_OPTICAL_FLOW , SysStatusSensorVisionPosition = MAV_SYS_STATUS_SENSOR_VISION_POSITION ,
SysStatusSensorLaserPosition = MAV_SYS_STATUS_SENSOR_LASER_POSITION , SysStatusSensorExternalGroundTruth = MAV_SYS_STATUS_SENSOR_EXTERNAL_GROUND_TRUTH , SysStatusSensorAngularRateControl = MAV_SYS_STATUS_SENSOR_ANGULAR_RATE_CONTROL , SysStatusSensorAttitudeStabilization = MAV_SYS_STATUS_SENSOR_ATTITUDE_STABILIZATION ,
SysStatusSensorYawPosition = MAV_SYS_STATUS_SENSOR_YAW_POSITION , SysStatusSensorZAltitudeControl = MAV_SYS_STATUS_SENSOR_Z_ALTITUDE_CONTROL , SysStatusSensorXYPositionControl = MAV_SYS_STATUS_SENSOR_XY_POSITION_CONTROL , SysStatusSensorMotorOutputs = MAV_SYS_STATUS_SENSOR_MOTOR_OUTPUTS ,
SysStatusSensorRCReceiver = MAV_SYS_STATUS_SENSOR_RC_RECEIVER , SysStatusSensor3dGyro2 = MAV_SYS_STATUS_SENSOR_3D_GYRO2 , SysStatusSensor3dAccel2 = MAV_SYS_STATUS_SENSOR_3D_ACCEL2 , SysStatusSensor3dMag2 = MAV_SYS_STATUS_SENSOR_3D_MAG2 ,
SysStatusSensorGeoFence = MAV_SYS_STATUS_GEOFENCE , SysStatusSensorAHRS = MAV_SYS_STATUS_AHRS , SysStatusSensorTerrain = MAV_SYS_STATUS_TERRAIN , SysStatusSensorReverseMotor = MAV_SYS_STATUS_REVERSE_MOTOR ,
SysStatusSensorLogging = MAV_SYS_STATUS_LOGGING , SysStatusSensorBattery = MAV_SYS_STATUS_SENSOR_BATTERY
}
Sensor bits from sensors*Bits properties.
enum GripperActions { GripperActionRelease = GRIPPER_ACTION_RELEASE , GripperActionGrab = GRIPPER_ACTION_GRAB , GripperActionHold = GRIPPER_ACTION_HOLD , GripperOptionInvalid = GRIPPER_ACTIONS_ENUM_END }
enum CalibrationType {
CalibrationNone , CalibrationRadio , CalibrationGyro , CalibrationMag ,
CalibrationAccel , CalibrationLevel , CalibrationEsc , CalibrationCopyTrims ,
CalibrationAPMCompassMot , CalibrationAPMPressureAirspeed , CalibrationAPMPreFlight , CalibrationPX4Airspeed ,
CalibrationPX4Pressure , CalibrationAPMAccelSimple
}
typedef int FirmwareClass_t
typedef int VehicleClass_t
Public Member Functions
QGCMAVLink (QObject *parent=nullptr)
~QGCMAVLink ()
MAVPACKED (typedef struct param_ext_union { union { float param_float;double param_double;int64_t param_int64;uint64_t param_uint64;int32_t param_int32;uint32_t param_uint32;int16_t param_int16;uint16_t param_uint16;int8_t param_int8;uint8_t param_uint8;uint8_t bytes[MAVLINK_MSG_PARAM_EXT_SET_FIELD_PARAM_VALUE_LEN];};uint8_t type;}) param_ext_union_t
Static Public Member Functions
static bool isPX4FirmwareClass (MAV_AUTOPILOT autopilot)
static bool isArduPilotFirmwareClass (MAV_AUTOPILOT autopilot)
static bool isGenericFirmwareClass (MAV_AUTOPILOT autopilot)
static FirmwareClass_t firmwareClass (MAV_AUTOPILOT autopilot)
static MAV_AUTOPILOT firmwareClassToAutopilot (FirmwareClass_t firmwareClass)
static QString firmwareClassToString (FirmwareClass_t firmwareClass)
static MAV_AUTOPILOT firmwareTypeFromString (const QString &firmwareTypeStr)
static QList< FirmwareClass_t > allFirmwareClasses ()
static bool isAirship (MAV_TYPE mavType)
static bool isFixedWing (MAV_TYPE mavType)
static bool isRoverBoat (MAV_TYPE mavType)
static bool isSub (MAV_TYPE mavType)
static bool isSpacecraft (MAV_TYPE mavType)
static bool isMultiRotor (MAV_TYPE mavType)
static bool isVTOL (MAV_TYPE mavType)
static VehicleClass_t vehicleClass (MAV_TYPE mavType)
static MAV_TYPE vehicleClassToMavType (VehicleClass_t vehicleClass)
static QString vehicleClassToUserVisibleString (VehicleClass_t vehicleClass)
static QString vehicleClassToInternalString (VehicleClass_t vehicleClass)
static MAV_TYPE vehicleTypeFromString (const QString &vehicleStr)
static QList< VehicleClass_t > allVehicleClasses (void)
static QString mavResultToString (uint8_t result)
static QString mavResultToString (MAV_RESULT result)
static QString mavSysStatusSensorToString (MAV_SYS_STATUS_SENSOR sysStatusSensor)
static QString mavTypeToString (MAV_TYPE mavType)
static QString firmwareVersionTypeToString (FIRMWARE_VERSION_TYPE firmwareVersionType)
static FIRMWARE_VERSION_TYPE firmwareVersionTypeFromString (const QString &typeStr)
static int motorCount (MAV_TYPE mavType, uint8_t frameType=0)
static uint32_t highLatencyFailuresToMavSysStatus (mavlink_high_latency2_t &highLatency2)
static QString compIdToString (uint8_t compId)
static bool isValidChannel (uint8_t channel)
static bool isValidChannel (mavlink_channel_t channel)
static mavlink_status_t * getChannelStatus (mavlink_channel_t channel)
Static Public Attributes
static constexpr const FirmwareClass_t FirmwareClassPX4 = MAV_AUTOPILOT_PX4
static constexpr const FirmwareClass_t FirmwareClassArduPilot = MAV_AUTOPILOT_ARDUPILOTMEGA
static constexpr const FirmwareClass_t FirmwareClassGeneric = MAV_AUTOPILOT_GENERIC
static constexpr const VehicleClass_t VehicleClassAirship = MAV_TYPE_AIRSHIP
static constexpr const VehicleClass_t VehicleClassFixedWing = MAV_TYPE_FIXED_WING
static constexpr const VehicleClass_t VehicleClassRoverBoat = MAV_TYPE_GROUND_ROVER
static constexpr const VehicleClass_t VehicleClassSub = MAV_TYPE_SUBMARINE
static constexpr const VehicleClass_t VehicleClassSpacecraft = MAV_TYPE_SPACECRAFT_ORBITER
static constexpr const VehicleClass_t VehicleClassMultiRotor = MAV_TYPE_QUADROTOR
static constexpr const VehicleClass_t VehicleClassVTOL = MAV_TYPE_VTOL_TAILSITTER_QUADROTOR
static constexpr const VehicleClass_t VehicleClassGeneric = MAV_TYPE_GENERIC
static constexpr const uint8_t maxRcChannels = 18
static const QHash< int, QString > mavlinkCompIdHash
Detailed Description
Definition at line 16 of file QGCMAVLink.h.
Member Typedef Documentation
FirmwareClass_t
typedef int QGCMAVLink::FirmwareClass_t
Definition at line 27 of file QGCMAVLink.h.
VehicleClass_t
typedef int QGCMAVLink::VehicleClass_t
Definition at line 28 of file QGCMAVLink.h.
Member Enumeration Documentation
CalibrationType
enum QGCMAVLink::CalibrationType
Enumerator
CalibrationNone
CalibrationRadio
CalibrationGyro
CalibrationMag
CalibrationAccel
CalibrationLevel
CalibrationEsc
CalibrationCopyTrims
CalibrationAPMCompassMot
CalibrationAPMPressureAirspeed
CalibrationAPMPreFlight
CalibrationPX4Airspeed
CalibrationPX4Pressure
CalibrationAPMAccelSimple
Definition at line 157 of file QGCMAVLink.h.
GripperActions
enum QGCMAVLink::GripperActions
Enumerator
GripperActionRelease
GripperActionGrab
GripperActionHold
GripperOptionInvalid
Definition at line 149 of file QGCMAVLink.h.
MAV_BATTERY_CHARGE_STATE
enum QGCMAVLink::MAV_BATTERY_CHARGE_STATE
Enumerator
MAV_BATTERY_CHARGE_STATE_UNDEFINED
MAV_BATTERY_CHARGE_STATE_OK
MAV_BATTERY_CHARGE_STATE_LOW
MAV_BATTERY_CHARGE_STATE_CRITICAL
MAV_BATTERY_CHARGE_STATE_EMERGENCY
MAV_BATTERY_CHARGE_STATE_FAILED
MAV_BATTERY_CHARGE_STATE_UNHEALTHY
MAV_BATTERY_CHARGE_STATE_CHARGING
Definition at line 98 of file QGCMAVLink.h.
MAV_BATTERY_FUNCTION
enum QGCMAVLink::MAV_BATTERY_FUNCTION
Enumerator
MAV_BATTERY_FUNCTION_UNKNOWN
MAV_BATTERY_FUNCTION_ALL
MAV_BATTERY_FUNCTION_PROPULSION
MAV_BATTERY_FUNCTION_AVIONICS
MAV_BATTERY_TYPE_PAYLOAD
Definition at line 89 of file QGCMAVLink.h.
MavlinkSysStatus
enum QGCMAVLink::MavlinkSysStatus
Sensor bits from sensors*Bits properties.
Enumerator
SysStatusSensor3dGyro
SysStatusSensor3dAccel
SysStatusSensor3dMag
SysStatusSensorAbsolutePressure
SysStatusSensorDifferentialPressure
SysStatusSensorGPS
SysStatusSensorOpticalFlow
SysStatusSensorVisionPosition
SysStatusSensorLaserPosition
SysStatusSensorExternalGroundTruth
SysStatusSensorAngularRateControl
SysStatusSensorAttitudeStabilization
SysStatusSensorYawPosition
SysStatusSensorZAltitudeControl
SysStatusSensorXYPositionControl
SysStatusSensorMotorOutputs
SysStatusSensorRCReceiver
SysStatusSensor3dGyro2
SysStatusSensor3dAccel2
SysStatusSensor3dMag2
SysStatusSensorGeoFence
SysStatusSensorAHRS
SysStatusSensorTerrain
SysStatusSensorReverseMotor
SysStatusSensorLogging
SysStatusSensorBattery
Definition at line 119 of file QGCMAVLink.h.
Constructor & Destructor Documentation
QGCMAVLink()
QGCMAVLink::QGCMAVLink (QObject * parent = nullptr)
Definition at line 64 of file QGCMAVLink.cc.
~QGCMAVLink()
QGCMAVLink::~QGCMAVLink ()
Definition at line 75 of file QGCMAVLink.cc.
Member Function Documentation
allFirmwareClasses()
QList< QGCMAVLink::FirmwareClass_t > QGCMAVLink::allFirmwareClasses (void) static
Definition at line 80 of file QGCMAVLink.cc.
References FirmwareClassArduPilot, FirmwareClassGeneric, and FirmwareClassPX4.
allVehicleClasses()
QList< QGCMAVLink::VehicleClass_t > QGCMAVLink::allVehicleClasses (void) static
Definition at line 91 of file QGCMAVLink.cc.
References VehicleClassFixedWing, VehicleClassGeneric, VehicleClassMultiRotor, VehicleClassRoverBoat, VehicleClassSub, and VehicleClassVTOL.
Referenced by MissionCommandTree::MissionCommandTree(), FirmwarePluginFactory::supportedVehicleClasses(), and FirmwarePluginManager::supportedVehicleClasses().
compIdToString()
QString QGCMAVLink::compIdToString (uint8_t compId) static
Definition at line 512 of file QGCMAVLink.cc.
References mavlinkCompIdHash.
Referenced by QGCCameraManager::_checkForLostCameras(), _handleCameraInfoRetry(), _requestCameraInfoCommandResultHandler(), _requestCameraInfoHelper(), and _requestCameraInfoMessageResultHandler().
firmwareClass()
QGCMAVLink::FirmwareClass_t QGCMAVLink::firmwareClass (MAV_AUTOPILOT autopilot) static
Definition at line 105 of file QGCMAVLink.cc.
References FirmwareClassArduPilot, FirmwareClassGeneric, FirmwareClassPX4, isArduPilotFirmwareClass(), and isPX4FirmwareClass().
Referenced by firmwareClassToString().
firmwareClassToAutopilot()
static MAV_AUTOPILOT QGCMAVLink::firmwareClassToAutopilot (FirmwareClass_t firmwareClass) inline static
Definition at line 49 of file QGCMAVLink.h.
Referenced by MissionCommandTree::getCommandsForCategory(), and MissionCommandTree::MissionCommandTree().
firmwareClassToString()
QString QGCMAVLink::firmwareClassToString (FirmwareClass_t firmwareClass) static
Definition at line 116 of file QGCMAVLink.cc.
References firmwareClass(), FirmwareClassArduPilot, FirmwareClassGeneric, and FirmwareClassPX4.
Referenced by Vehicle::firmwareTypeString().
firmwareTypeFromString()
MAV_AUTOPILOT QGCMAVLink::firmwareTypeFromString (const QString & firmwareTypeStr) static
Definition at line 130 of file QGCMAVLink.cc.
firmwareVersionTypeFromString()
FIRMWARE_VERSION_TYPE QGCMAVLink::firmwareVersionTypeFromString (const QString & typeStr) static
Definition at line 403 of file QGCMAVLink.cc.
firmwareVersionTypeToString()
QString QGCMAVLink::firmwareVersionTypeToString (FIRMWARE_VERSION_TYPE firmwareVersionType) static
Definition at line 386 of file QGCMAVLink.cc.
Referenced by Vehicle::firmwareVersionTypeString().
getChannelStatus()
static mavlink_status_t * QGCMAVLink::getChannelStatus (mavlink_channel_t channel) inline static
Definition at line 196 of file QGCMAVLink.h.
References mavlink_get_channel_status().
highLatencyFailuresToMavSysStatus()
uint32_t QGCMAVLink::highLatencyFailuresToMavSysStatus (mavlink_high_latency2_t & highLatency2) static
Definition at line 483 of file QGCMAVLink.cc.
isAirship()
bool QGCMAVLink::isAirship (MAV_TYPE mavType) static
Definition at line 142 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassAirship.
Referenced by Vehicle::airship().
isArduPilotFirmwareClass()
static bool QGCMAVLink::isArduPilotFirmwareClass (MAV_AUTOPILOT autopilot) inline static
Definition at line 46 of file QGCMAVLink.h.
Referenced by firmwareClass().
isFixedWing()
bool QGCMAVLink::isFixedWing (MAV_TYPE mavType) static
Definition at line 147 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassFixedWing.
Referenced by Vehicle::fixedWing().
isGenericFirmwareClass()
static bool QGCMAVLink::isGenericFirmwareClass (MAV_AUTOPILOT autopilot) inline static
Definition at line 47 of file QGCMAVLink.h.
isMultiRotor()
bool QGCMAVLink::isMultiRotor (MAV_TYPE mavType) static
Definition at line 167 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassMultiRotor.
Referenced by Vehicle::multiRotor().
isPX4FirmwareClass()
static bool QGCMAVLink::isPX4FirmwareClass (MAV_AUTOPILOT autopilot) inline static
Definition at line 45 of file QGCMAVLink.h.
Referenced by firmwareClass().
isRoverBoat()
bool QGCMAVLink::isRoverBoat (MAV_TYPE mavType) static
Definition at line 152 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassRoverBoat.
Referenced by Vehicle::rover().
isSpacecraft()
bool QGCMAVLink::isSpacecraft (MAV_TYPE mavType) static
Definition at line 157 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassSpacecraft.
Referenced by Vehicle::spacecraft().
isSub()
bool QGCMAVLink::isSub (MAV_TYPE mavType) static
Definition at line 162 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassSub.
Referenced by Vehicle::sub().
isValidChannel() [1/2]
static bool QGCMAVLink::isValidChannel (mavlink_channel_t channel) inline static
Definition at line 194 of file QGCMAVLink.h.
References isValidChannel().
Referenced by isValidChannel().
isValidChannel() [2/2]
static bool QGCMAVLink::isValidChannel (uint8_t channel) inline static
Definition at line 193 of file QGCMAVLink.h.
References MAVLINK_COMM_NUM_BUFFERS.
Referenced by mavlink_get_channel_status().
isVTOL()
bool QGCMAVLink::isVTOL (MAV_TYPE mavType) static
Definition at line 172 of file QGCMAVLink.cc.
References vehicleClass(), and VehicleClassVTOL.
Referenced by Vehicle::vtol().
MAVPACKED()
QGCMAVLink::MAVPACKED (typedef struct param_ext_union { union { float param_float;double param_double;int64_t param_int64;uint64_t param_uint64;int32_t param_int32;uint32_t param_uint32;int16_t param_int16;uint16_t param_uint16;int8_t param_int8;uint8_t param_uint8;uint8_t bytes[MAVLINK_MSG_PARAM_EXT_SET_FIELD_PARAM_VALUE_LEN];};uint8_t type;})
mavResultToString() [1/2]
static QString QGCMAVLink::mavResultToString (MAV_RESULT result) inline static
Definition at line 69 of file QGCMAVLink.h.
References mavResultToString().
Referenced by mavResultToString().
mavResultToString() [2/2]
QString QGCMAVLink::mavResultToString (uint8_t result) static
Definition at line 277 of file QGCMAVLink.cc.
Referenced by VehicleCameraControl::_mavCommandResult(), _requestCameraInfoCommandResultHandler(), and _requestCameraInfoMessageResultHandler().
mavSysStatusSensorToString()
QString QGCMAVLink::mavSysStatusSensorToString (MAV_SYS_STATUS_SENSOR sysStatusSensor) static
Definition at line 297 of file QGCMAVLink.cc.
mavTypeToString()
QString QGCMAVLink::mavTypeToString (MAV_TYPE mavType) static
Definition at line 350 of file QGCMAVLink.cc.
Referenced by Vehicle::vehicleTypeString().
motorCount()
int QGCMAVLink::motorCount (MAV_TYPE mavType, uint8_t frameType = 0) static
Definition at line 421 of file QGCMAVLink.cc.
Referenced by Vehicle::motorCount().
vehicleClass()
QGCMAVLink::VehicleClass_t QGCMAVLink::vehicleClass (MAV_TYPE mavType) static
Definition at line 177 of file QGCMAVLink.cc.
References VehicleClassAirship, VehicleClassFixedWing, VehicleClassGeneric, VehicleClassMultiRotor, VehicleClassRoverBoat, VehicleClassSpacecraft, VehicleClassSub, and VehicleClassVTOL.
Referenced by APMFirmwarePlugin::_internalParameterMetaDataFile(), isAirship(), isFixedWing(), isMultiRotor(), isRoverBoat(), isSpacecraft(), isSub(), isVTOL(), MissionController::sendToVehiclePreCheck(), FactValueGrid::vehicleClass(), Vehicle::vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
vehicleClassToInternalString()
QString QGCMAVLink::vehicleClassToInternalString (VehicleClass_t vehicleClass) static
Definition at line 253 of file QGCMAVLink.cc.
References vehicleClass(), VehicleClassAirship, VehicleClassFixedWing, VehicleClassGeneric, VehicleClassMultiRotor, VehicleClassRoverBoat, VehicleClassSpacecraft, VehicleClassSub, and VehicleClassVTOL.
Referenced by Vehicle::vehicleClassInternalName().
vehicleClassToMavType()
static MAV_TYPE QGCMAVLink::vehicleClassToMavType (VehicleClass_t vehicleClass) inline static
Definition at line 62 of file QGCMAVLink.h.
Referenced by MissionCommandTree::getCommandsForCategory().
vehicleClassToUserVisibleString()
QString QGCMAVLink::vehicleClassToUserVisibleString (VehicleClass_t vehicleClass) static
Definition at line 211 of file QGCMAVLink.cc.
References vehicleClass(), VehicleClassAirship, VehicleClassFixedWing, VehicleClassGeneric, VehicleClassMultiRotor, VehicleClassRoverBoat, VehicleClassSpacecraft, VehicleClassSub, and VehicleClassVTOL.
vehicleTypeFromString()
MAV_TYPE QGCMAVLink::vehicleTypeFromString (const QString & vehicleStr) static
Definition at line 235 of file QGCMAVLink.cc.
Member Data Documentation
FirmwareClassArduPilot
constexpr const FirmwareClass_t QGCMAVLink::FirmwareClassArduPilot = MAV_AUTOPILOT_ARDUPILOTMEGA static constexpr
Definition at line 31 of file QGCMAVLink.h.
Referenced by allFirmwareClasses(), QGroundControlQmlGlobal::apmFirmwareSupported(), firmwareClass(), firmwareClassToString(), and APMFirmwarePluginFactory::supportedFirmwareClasses().
FirmwareClassGeneric
constexpr const FirmwareClass_t QGCMAVLink::FirmwareClassGeneric = MAV_AUTOPILOT_GENERIC static constexpr
Definition at line 32 of file QGCMAVLink.h.
Referenced by MissionCommandTree::allCommandIds(), allFirmwareClasses(), firmwareClass(), firmwareClassToString(), MissionCommandTree::friendlyName(), MissionCommandTree::isLandCommand(), MissionCommandTree::isTakeoffCommand(), MissionCommandTree::MissionCommandTree(), MissionCommandTree::rawName(), FirmwarePluginManager::supportedFirmwareClasses(), and FirmwarePluginManager::supportedVehicleClasses().
FirmwareClassPX4
constexpr const FirmwareClass_t QGCMAVLink::FirmwareClassPX4 = MAV_AUTOPILOT_PX4 static constexpr
Definition at line 30 of file QGCMAVLink.h.
Referenced by allFirmwareClasses(), firmwareClass(), firmwareClassToString(), QGroundControlQmlGlobal::px4ProFirmwareSupported(), and PX4FirmwarePluginFactory::supportedFirmwareClasses().
mavlinkCompIdHash
const QHash< int, QString > QGCMAVLink::mavlinkCompIdHash static
Definition at line 6 of file QGCMAVLink.h.
Referenced by compIdToString().
maxRcChannels
constexpr const uint8_t QGCMAVLink::maxRcChannels = 18 static constexpr
Definition at line 43 of file QGCMAVLink.h.
VehicleClassAirship
constexpr const VehicleClass_t QGCMAVLink::VehicleClassAirship = MAV_TYPE_AIRSHIP static constexpr
Definition at line 34 of file QGCMAVLink.h.
Referenced by isAirship(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassFixedWing
constexpr const VehicleClass_t QGCMAVLink::VehicleClassFixedWing = MAV_TYPE_FIXED_WING static constexpr
Definition at line 35 of file QGCMAVLink.h.
Referenced by allVehicleClasses(), isFixedWing(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), APMFirmwarePlugin::supportedMissionCommands(), PX4FirmwarePlugin::supportedMissionCommands(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassGeneric
constexpr const VehicleClass_t QGCMAVLink::VehicleClassGeneric = MAV_TYPE_GENERIC static constexpr
Definition at line 41 of file QGCMAVLink.h.
Referenced by TransectStyleComplexItem::_load(), MissionCommandTree::allCommandIds(), allVehicleClasses(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslExitAlt(), CameraSection::cameraModeSupported(), MissionCommandTree::friendlyName(), MissionCommandTree::getCommandsForCategory(), MissionController::insertCancelROIMissionItem(), MissionController::insertROIMissionItem(), MissionCommandTree::isLandCommand(), MissionCommandTree::isTakeoffCommand(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), MissionCommandTree::rawName(), APMFirmwarePlugin::supportedMissionCommands(), PX4FirmwarePlugin::supportedMissionCommands(), FirmwarePluginManager::supportedVehicleClasses(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassMultiRotor
constexpr const VehicleClass_t QGCMAVLink::VehicleClassMultiRotor = MAV_TYPE_QUADROTOR static constexpr
Definition at line 39 of file QGCMAVLink.h.
Referenced by allVehicleClasses(), isMultiRotor(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), APMFirmwarePlugin::supportedMissionCommands(), PX4FirmwarePlugin::supportedMissionCommands(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassRoverBoat
constexpr const VehicleClass_t QGCMAVLink::VehicleClassRoverBoat = MAV_TYPE_GROUND_ROVER static constexpr
Definition at line 36 of file QGCMAVLink.h.
Referenced by allVehicleClasses(), isRoverBoat(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassSpacecraft
constexpr const VehicleClass_t QGCMAVLink::VehicleClassSpacecraft = MAV_TYPE_SPACECRAFT_ORBITER static constexpr
Definition at line 38 of file QGCMAVLink.h.
Referenced by isSpacecraft(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassSub
constexpr const VehicleClass_t QGCMAVLink::VehicleClassSub = MAV_TYPE_SUBMARINE static constexpr
Definition at line 37 of file QGCMAVLink.h.
Referenced by allVehicleClasses(), isSub(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
VehicleClassVTOL
constexpr const VehicleClass_t QGCMAVLink::VehicleClassVTOL = MAV_TYPE_VTOL_TAILSITTER_QUADROTOR static constexpr
Definition at line 40 of file QGCMAVLink.h.
Referenced by allVehicleClasses(), isVTOL(), FirmwarePlugin::missionCommandOverrides(), APMFirmwarePlugin::missionCommandOverrides(), PX4FirmwarePlugin::missionCommandOverrides(), MissionCommandTree::MissionCommandTree(), APMFirmwarePlugin::supportedMissionCommands(), PX4FirmwarePlugin::supportedMissionCommands(), vehicleClass(), vehicleClassToInternalString(), and vehicleClassToUserVisibleString().
The documentation for this class was generated from the following files:
src/MAVLink/QGCMAVLink.h
src/MAVLink/QGCMAVLink.cc