QGroundControl: VideoSettings Class Reference
VideoSettings Class Reference
#include <VideoSettings.h>
Signals
void streamConfiguredChanged (bool configured)
Signals inherited from SettingsGroup
void userVisibleChanged ()
Public Member Functions
VideoSettings (QObject *parent=nullptr)
Fact *videoSource READ videoSource CONSTANT Fact * videoSource ()
Fact *udpUrl READ udpUrl CONSTANT Fact * udpUrl ()
Fact *tcpUrl READ tcpUrl CONSTANT Fact * tcpUrl ()
Fact *rtspUrl READ rtspUrl CONSTANT Fact * rtspUrl ()
Fact *aspectRatio READ aspectRatio CONSTANT Fact * aspectRatio ()
Fact *videoFit READ videoFit CONSTANT Fact * videoFit ()
Fact *gridLines READ gridLines CONSTANT Fact * gridLines ()
Fact *showRecControl READ showRecControl CONSTANT Fact * showRecControl ()
Fact *recordingFormat READ recordingFormat CONSTANT Fact * recordingFormat ()
Fact *maxVideoSize READ maxVideoSize CONSTANT Fact * maxVideoSize ()
Fact *enableStorageLimit READ enableStorageLimit CONSTANT Fact * enableStorageLimit ()
Fact *rtspTimeout READ rtspTimeout CONSTANT Fact * rtspTimeout ()
Fact *streamEnabled READ streamEnabled CONSTANT Fact * streamEnabled ()
Fact *disableWhenDisarmed READ disableWhenDisarmed CONSTANT Fact * disableWhenDisarmed ()
Fact *lowLatencyMode READ lowLatencyMode CONSTANT Fact * lowLatencyMode ()
Fact *forceVideoDecoder READ forceVideoDecoder CONSTANT Fact * forceVideoDecoder ()
bool streamConfigured READ streamConfigured NOTIFY streamConfiguredChanged (QString rtspVideoSource READ rtspVideoSource CONSTANT) 1(QString udp264VideoSource READ udp264VideoSource CONSTANT) 1(QString udp265VideoSource READ udp265VideoSource CONSTANT) 1(QString tcpVideoSource READ tcpVideoSource CONSTANT) 1(QString mpegtsVideoSource READ mpegtsVideoSource CONSTANT) 1(QString disabledVideoSource READ disabledVideoSource CONSTANT) bool streamConfigured()
QString rtspVideoSource ()
QString udp264VideoSource ()
QString udp265VideoSource ()
QString tcpVideoSource ()
QString mpegtsVideoSource ()
QString disabledVideoSource ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool userVisible READ userVisible WRITE setUserVisible NOTIFY virtual userVisibleChanged bool userVisible ()
virtual void setUserVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "Video"
static const char * settingsGroup = "Video"
static const char * videoSourceName = "videoSource"
static const char * udpUrlName = "udpUrl"
static const char * tcpUrlName = "tcpUrl"
static const char * rtspUrlName = "rtspUrl"
static const char * aspectRatioName = "aspectRatio"
static const char * videoFitName = "videoFit"
static const char * gridLinesName = "gridLines"
static const char * showRecControlName = "showRecControl"
static const char * recordingFormatName = "recordingFormat"
static const char * maxVideoSizeName = "maxVideoSize"
static const char * enableStorageLimitName = "enableStorageLimit"
static const char * rtspTimeoutName = "rtspTimeout"
static const char * streamEnabledName = "streamEnabled"
static const char * disableWhenDisarmedName = "disableWhenDisarmed"
static const char * lowLatencyModeName = "lowLatencyMode"
static const char * forceVideoDecoderName = "forceVideoDecoder"
static constexpr const char * videoSourceNoVideo = QT_TRANSLATE_NOOP("VideoSettings", "No Video Available")
static constexpr const char * videoDisabled = QT_TRANSLATE_NOOP("VideoSettings", "Video Stream Disabled")
static constexpr const char * videoSourceRTSP = QT_TRANSLATE_NOOP("VideoSettings", "RTSP Video Stream")
static constexpr const char * videoSourceUDPH264 = QT_TRANSLATE_NOOP("VideoSettings", "UDP h.264 Video Stream")
static constexpr const char * videoSourceUDPH265 = QT_TRANSLATE_NOOP("VideoSettings", "UDP h.265 Video Stream")
static constexpr const char * videoSourceTCP = QT_TRANSLATE_NOOP("VideoSettings", "TCP-MPEG2 Video Stream")
static constexpr const char * videoSourceMPEGTS = QT_TRANSLATE_NOOP("VideoSettings", "MPEG-TS Video Stream")
static constexpr const char * videoSource3DRSolo = QT_TRANSLATE_NOOP("VideoSettings", "3DR Solo (requires restart)")
static constexpr const char * videoSourceParrotDiscovery = QT_TRANSLATE_NOOP("VideoSettings", "Parrot Discovery")
static constexpr const char * videoSourceYuneecMantisG = QT_TRANSLATE_NOOP("VideoSettings", "Yuneec Mantis G")
static constexpr const char * videoSourceHerelinkAirUnit = QT_TRANSLATE_NOOP("VideoSettings", "Herelink AirUnit")
static constexpr const char * videoSourceHerelinkHotspot = QT_TRANSLATE_NOOP("VideoSettings", "Herelink Hotspot")
Additional Inherited Members
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _userVisible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file VideoSettings.h.
Constructor & Destructor Documentation
VideoSettings()
VideoSettings::VideoSettings (QObject * parent = nullptr)
Definition at line 19 of file VideoSettings.cc.
References UVCReceiver::getDeviceNameList().
Member Function Documentation
aspectRatio()
Fact * VideoSettings::aspectRatio ()
Definition at line 76 of file VideoSettings.cc.
Referenced by VideoManager::aspectRatio(), VideoManager::init(), and VideoManager::thermalHfov().
disabledVideoSource()
QString VideoSettings::disabledVideoSource () inline
Definition at line 47 of file VideoSettings.h.
References videoDisabled.
disableWhenDisarmed()
Fact * VideoSettings::disableWhenDisarmed ()
Definition at line 84 of file VideoSettings.cc.
enableStorageLimit()
Fact * VideoSettings::enableStorageLimit ()
Definition at line 82 of file VideoSettings.cc.
forceVideoDecoder()
Fact * VideoSettings::forceVideoDecoder ()
Definition at line 103 of file VideoSettings.cc.
References kGstEnabled, and Fact::valueChanged().
gridLines()
Fact * VideoSettings::gridLines ()
Definition at line 78 of file VideoSettings.cc.
lowLatencyMode()
Fact * VideoSettings::lowLatencyMode ()
Definition at line 115 of file VideoSettings.cc.
References kGstEnabled, and Fact::valueChanged().
Referenced by VideoManager::init(), and Vehicle::Vehicle().
maxVideoSize()
Fact * VideoSettings::maxVideoSize ()
Definition at line 81 of file VideoSettings.cc.
mpegtsVideoSource()
QString VideoSettings::mpegtsVideoSource () inline
Definition at line 46 of file VideoSettings.h.
References videoSourceMPEGTS.
recordingFormat()
Fact * VideoSettings::recordingFormat ()
Definition at line 80 of file VideoSettings.cc.
Referenced by VideoManager::startRecording().
rtspTimeout()
Fact * VideoSettings::rtspTimeout ()
Definition at line 127 of file VideoSettings.cc.
References kGstEnabled, and Fact::valueChanged().
rtspUrl()
Fact * VideoSettings::rtspUrl ()
Definition at line 148 of file VideoSettings.cc.
References Fact::valueChanged().
Referenced by VideoManager::init().
rtspVideoSource()
QString VideoSettings::rtspVideoSource () inline
Definition at line 42 of file VideoSettings.h.
References videoSourceRTSP.
showRecControl()
Fact * VideoSettings::showRecControl ()
Definition at line 79 of file VideoSettings.cc.
streamConfiguredChanged [1/2]
void VideoSettings::streamConfiguredChanged (bool configured) signal
streamConfiguredChanged() [2/2]
bool streamConfigured READ streamConfigured NOTIFY VideoSettings::streamConfiguredChanged (QString rtspVideoSource READ rtspVideoSource CONSTANT)
streamEnabled()
Fact * VideoSettings::streamEnabled ()
Definition at line 83 of file VideoSettings.cc.
Referenced by VideoManager::hasVideo().
tcpUrl()
Fact * VideoSettings::tcpUrl ()
Definition at line 157 of file VideoSettings.cc.
References Fact::valueChanged().
Referenced by VideoManager::init().
tcpVideoSource()
QString VideoSettings::tcpVideoSource () inline
Definition at line 45 of file VideoSettings.h.
References videoSourceTCP.
udp264VideoSource()
QString VideoSettings::udp264VideoSource () inline
Definition at line 43 of file VideoSettings.h.
References videoSourceUDPH264.
udp265VideoSource()
QString VideoSettings::udp265VideoSource () inline
Definition at line 44 of file VideoSettings.h.
References videoSourceUDPH265.
udpUrl()
Fact * VideoSettings::udpUrl ()
Definition at line 139 of file VideoSettings.cc.
References Fact::valueChanged().
Referenced by VideoManager::init().
videoFit()
Fact * VideoSettings::videoFit ()
Definition at line 77 of file VideoSettings.cc.
videoSource()
Fact * VideoSettings::videoSource ()
Definition at line 86 of file VideoSettings.cc.
References Fact::valueChanged().
Referenced by UVCReceiver::getSourceId(), VideoManager::init(), VideoManager::isStreamSource(), and Vehicle::Vehicle().
Member Data Documentation
aspectRatioName
const char * VideoSettings::aspectRatioName = "aspectRatio" static
Definition at line 20 of file VideoSettings.h.
disableWhenDisarmedName
const char * VideoSettings::disableWhenDisarmedName = "disableWhenDisarmed" static
Definition at line 29 of file VideoSettings.h.
enableStorageLimitName
const char * VideoSettings::enableStorageLimitName = "enableStorageLimit" static
Definition at line 26 of file VideoSettings.h.
forceVideoDecoderName
const char * VideoSettings::forceVideoDecoderName = "forceVideoDecoder" static
Definition at line 31 of file VideoSettings.h.
gridLinesName
const char * VideoSettings::gridLinesName = "gridLines" static
Definition at line 22 of file VideoSettings.h.
lowLatencyModeName
const char * VideoSettings::lowLatencyModeName = "lowLatencyMode" static
Definition at line 30 of file VideoSettings.h.
maxVideoSizeName
const char * VideoSettings::maxVideoSizeName = "maxVideoSize" static
Definition at line 25 of file VideoSettings.h.
name
const char * VideoSettings::name = "Video" static
Definition at line 14 of file VideoSettings.h.
recordingFormatName
const char * VideoSettings::recordingFormatName = "recordingFormat" static
Definition at line 24 of file VideoSettings.h.
rtspTimeoutName
const char * VideoSettings::rtspTimeoutName = "rtspTimeout" static
Definition at line 27 of file VideoSettings.h.
rtspUrlName
const char * VideoSettings::rtspUrlName = "rtspUrl" static
Definition at line 19 of file VideoSettings.h.
settingsGroup
const char * VideoSettings::settingsGroup = "Video" static
Definition at line 14 of file VideoSettings.h.
showRecControlName
const char * VideoSettings::showRecControlName = "showRecControl" static
Definition at line 23 of file VideoSettings.h.
streamEnabledName
const char * VideoSettings::streamEnabledName = "streamEnabled" static
Definition at line 28 of file VideoSettings.h.
tcpUrlName
const char * VideoSettings::tcpUrlName = "tcpUrl" static
Definition at line 18 of file VideoSettings.h.
udpUrlName
const char * VideoSettings::udpUrlName = "udpUrl" static
Definition at line 17 of file VideoSettings.h.
videoDisabled
constexpr const char* VideoSettings::videoDisabled = QT_TRANSLATE_NOOP("VideoSettings", "Video Stream Disabled") static constexpr
Definition at line 50 of file VideoSettings.h.
Referenced by disabledVideoSource(), and Vehicle::Vehicle().
videoFitName
const char * VideoSettings::videoFitName = "videoFit" static
Definition at line 21 of file VideoSettings.h.
videoSource3DRSolo
constexpr const char* VideoSettings::videoSource3DRSolo = QT_TRANSLATE_NOOP("VideoSettings", "3DR Solo (requires restart)") static constexpr
Definition at line 56 of file VideoSettings.h.
Referenced by APMFirmwarePlugin::initializeVehicle(), and VideoManager::isStreamSource().
videoSourceHerelinkAirUnit
constexpr const char* VideoSettings::videoSourceHerelinkAirUnit = QT_TRANSLATE_NOOP("VideoSettings", "Herelink AirUnit") static constexpr
Definition at line 59 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource().
videoSourceHerelinkHotspot
constexpr const char* VideoSettings::videoSourceHerelinkHotspot = QT_TRANSLATE_NOOP("VideoSettings", "Herelink Hotspot") static constexpr
Definition at line 60 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource().
videoSourceMPEGTS
constexpr const char* VideoSettings::videoSourceMPEGTS = QT_TRANSLATE_NOOP("VideoSettings", "MPEG-TS Video Stream") static constexpr
Definition at line 55 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource(), and mpegtsVideoSource().
videoSourceName
const char * VideoSettings::videoSourceName = "videoSource" static
Definition at line 16 of file VideoSettings.h.
videoSourceNoVideo
constexpr const char* VideoSettings::videoSourceNoVideo = QT_TRANSLATE_NOOP("VideoSettings", "No Video Available") static constexpr
Definition at line 49 of file VideoSettings.h.
videoSourceParrotDiscovery
constexpr const char* VideoSettings::videoSourceParrotDiscovery = QT_TRANSLATE_NOOP("VideoSettings", "Parrot Discovery") static constexpr
Definition at line 57 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource().
videoSourceRTSP
constexpr const char* VideoSettings::videoSourceRTSP = QT_TRANSLATE_NOOP("VideoSettings", "RTSP Video Stream") static constexpr
Definition at line 51 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource(), and rtspVideoSource().
videoSourceTCP
constexpr const char* VideoSettings::videoSourceTCP = QT_TRANSLATE_NOOP("VideoSettings", "TCP-MPEG2 Video Stream") static constexpr
Definition at line 54 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource(), and tcpVideoSource().
videoSourceUDPH264
constexpr const char* VideoSettings::videoSourceUDPH264 = QT_TRANSLATE_NOOP("VideoSettings", "UDP h.264 Video Stream") static constexpr
Definition at line 52 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource(), udp264VideoSource(), and Vehicle::Vehicle().
videoSourceUDPH265
constexpr const char* VideoSettings::videoSourceUDPH265 = QT_TRANSLATE_NOOP("VideoSettings", "UDP h.265 Video Stream") static constexpr
Definition at line 53 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource(), and udp265VideoSource().
videoSourceYuneecMantisG
constexpr const char* VideoSettings::videoSourceYuneecMantisG = QT_TRANSLATE_NOOP("VideoSettings", "Yuneec Mantis G") static constexpr
Definition at line 58 of file VideoSettings.h.
Referenced by VideoManager::isStreamSource().
The documentation for this class was generated from the following files:
src/Settings/VideoSettings.h
src/Settings/VideoSettings.cc