QGroundControl: Viewer3DTileQuery Class Reference
Viewer3DTileQuery Class Reference
#include <Viewer3DTileQuery.h>
Classes
struct TileStatistics_t
Signals
void loadingMapCompleted ()
void mapTileDownloaded (float progress)
void textureGeometryReady (TileStatistics_t tileInfo)
Public Member Functions
Viewer3DTileQuery (QObject *parent=nullptr)
void adaptiveMapTilesLoader (const QString &mapType, int mapId, const QGeoCoordinate &coordinateMin, const QGeoCoordinate &coordinateMax)
int maxTileCount (int zoomLevel, const QGeoCoordinate &coordinateMin, const QGeoCoordinate &coordinateMax)
QByteArray mapData () const
QSize mapSize () const
Friends
class Viewer3DTileQueryTest
Detailed Description
Definition at line 12 of file Viewer3DTileQuery.h.
Constructor & Destructor Documentation
Viewer3DTileQuery()
Viewer3DTileQuery::Viewer3DTileQuery (QObject * parent = nullptr) explicit
Definition at line 18 of file Viewer3DTileQuery.cc.
Member Function Documentation
adaptiveMapTilesLoader()
void Viewer3DTileQuery::adaptiveMapTilesLoader (const QString & mapType, int mapId, const QGeoCoordinate & coordinateMin, const QGeoCoordinate & coordinateMax)
Definition at line 123 of file Viewer3DTileQuery.cc.
References kMaxTileCounts, kMaxZoomLevel, maxTileCount(), and textureGeometryReady().
loadingMapCompleted
void Viewer3DTileQuery::loadingMapCompleted () signal
mapData()
QByteArray Viewer3DTileQuery::mapData () const inline
Definition at line 30 of file Viewer3DTileQuery.h.
mapSize()
QSize Viewer3DTileQuery::mapSize () const inline
Definition at line 31 of file Viewer3DTileQuery.h.
mapTileDownloaded
void Viewer3DTileQuery::mapTileDownloaded (float progress) signal
maxTileCount()
int Viewer3DTileQuery::maxTileCount (int zoomLevel, const QGeoCoordinate & coordinateMin, const QGeoCoordinate & coordinateMax)
Definition at line 139 of file Viewer3DTileQuery.cc.
References UrlFactory::getMapProviderFromQtMapId().
Referenced by adaptiveMapTilesLoader().
textureGeometryReady
void Viewer3DTileQuery::textureGeometryReady (TileStatistics_t tileInfo) signal
Referenced by adaptiveMapTilesLoader().
Friends And Related Symbol Documentation
Viewer3DTileQueryTest
friend class Viewer3DTileQueryTest friend
Definition at line 16 of file Viewer3DTileQuery.h.
The documentation for this class was generated from the following files:
src/Viewer3D/Viewer3DTileQuery.h
src/Viewer3D/Viewer3DTileQuery.cc