QGroundControl: VehicleGPSFactGroup Class Reference
VehicleGPSFactGroup Class Reference
#include <VehicleGPSFactGroup.h>
Signals
void gnssIntegrityReceived ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Member Functions
void _handleGpsRawInt (const mavlink_message_t &message)
void _handleHighLatency (const mavlink_message_t &message)
void _handleHighLatency2 (const mavlink_message_t &message)
void _handleGnssIntegrity (const mavlink_message_t &message)
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
Fact _latFact = Fact(0, QStringLiteral("lat"), FactMetaData::valueTypeDouble)
Fact _lonFact = Fact(0, QStringLiteral("lon"), FactMetaData::valueTypeDouble)
Fact _mgrsFact = Fact(0, QStringLiteral("mgrs"), FactMetaData::valueTypeString)
Fact _hdopFact = Fact(0, QStringLiteral("hdop"), FactMetaData::valueTypeDouble)
Fact _vdopFact = Fact(0, QStringLiteral("vdop"), FactMetaData::valueTypeDouble)
Fact _courseOverGroundFact = Fact(0, QStringLiteral("courseOverGround"), FactMetaData::valueTypeDouble)
Fact _yawFact = Fact(0, QStringLiteral("yaw"), FactMetaData::valueTypeDouble)
Fact _countFact = Fact(0, QStringLiteral("count"), FactMetaData::valueTypeInt32)
Fact _lockFact = Fact(0, QStringLiteral("lock"), FactMetaData::valueTypeInt32)
Fact _systemErrorsFact = Fact(0, QStringLiteral("systemErrors"), FactMetaData::valueTypeUint32)
Fact _spoofingStateFact = Fact(0, QStringLiteral("spoofingState"), FactMetaData::valueTypeUint8)
Fact _jammingStateFact = Fact(0, QStringLiteral("jammingState"), FactMetaData::valueTypeUint8)
Fact _authenticationStateFact = Fact(0, QStringLiteral("authenticationState"), FactMetaData::valueTypeUint8)
Fact _correctionsQualityFact = Fact(0, QStringLiteral("correctionsQuality"), FactMetaData::valueTypeUint8)
Fact _systemQualityFact = Fact(0, QStringLiteral("systemQuality"), FactMetaData::valueTypeUint8)
Fact _gnssSignalQualityFact = Fact(0, QStringLiteral("gnssSignalQuality"), FactMetaData::valueTypeUint8)
Fact _postProcessingQualityFact = Fact(0, QStringLiteral("postProcessingQuality"), FactMetaData::valueTypeUint8)
uint8_t _gnssIntegrityId {}
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Additional Inherited Members
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Detailed Description
Definition at line 5 of file VehicleGPSFactGroup.h.
Member Function Documentation
_handleGnssIntegrity()
void VehicleGPSFactGroup::_handleGnssIntegrity (const mavlink_message_t & message) protected
Definition at line 114 of file VehicleGPSFactGroup.cc.
References _gnssIntegrityId, and gnssIntegrityReceived().
Referenced by VehicleGPS2FactGroup::handleMessage().
_handleGpsRawInt()
void VehicleGPSFactGroup::_handleGpsRawInt (const mavlink_message_t & message) protected
Definition at line 68 of file VehicleGPSFactGroup.cc.
References FactGroup::_setTelemetryAvailable(), and QGCGeo::convertGeoToMGRS().
_handleHighLatency()
void VehicleGPSFactGroup::_handleHighLatency (const mavlink_message_t & message) protected
Definition at line 86 of file VehicleGPSFactGroup.cc.
References FactGroup::_setTelemetryAvailable(), and QGCGeo::convertGeoToMGRS().
_handleHighLatency2()
void VehicleGPSFactGroup::_handleHighLatency2 (const mavlink_message_t & message) protected
Definition at line 99 of file VehicleGPSFactGroup.cc.
References FactGroup::_setTelemetryAvailable(), and QGCGeo::convertGeoToMGRS().
gnssIntegrityReceived
void VehicleGPSFactGroup::gnssIntegrityReceived () signal
Referenced by _handleGnssIntegrity().
Member Data Documentation
_authenticationStateFact
Fact VehicleGPSFactGroup::_authenticationStateFact = Fact(0, QStringLiteral("authenticationState"), FactMetaData::valueTypeUint8) protected
Definition at line 71 of file VehicleGPSFactGroup.h.
_correctionsQualityFact
Fact VehicleGPSFactGroup::_correctionsQualityFact = Fact(0, QStringLiteral("correctionsQuality"), FactMetaData::valueTypeUint8) protected
Definition at line 72 of file VehicleGPSFactGroup.h.
_countFact
Fact VehicleGPSFactGroup::_countFact = Fact(0, QStringLiteral("count"), FactMetaData::valueTypeInt32) protected
Definition at line 66 of file VehicleGPSFactGroup.h.
_courseOverGroundFact
Fact VehicleGPSFactGroup::_courseOverGroundFact = Fact(0, QStringLiteral("courseOverGround"), FactMetaData::valueTypeDouble) protected
Definition at line 64 of file VehicleGPSFactGroup.h.
_gnssIntegrityId
uint8_t VehicleGPSFactGroup::_gnssIntegrityId {} protected
Definition at line 77 of file VehicleGPSFactGroup.h.
Referenced by _handleGnssIntegrity(), and VehicleGPS2FactGroup::VehicleGPS2FactGroup().
_gnssSignalQualityFact
Fact VehicleGPSFactGroup::_gnssSignalQualityFact = Fact(0, QStringLiteral("gnssSignalQuality"), FactMetaData::valueTypeUint8) protected
Definition at line 74 of file VehicleGPSFactGroup.h.
_hdopFact
Fact VehicleGPSFactGroup::_hdopFact = Fact(0, QStringLiteral("hdop"), FactMetaData::valueTypeDouble) protected
Definition at line 62 of file VehicleGPSFactGroup.h.
_jammingStateFact
Fact VehicleGPSFactGroup::_jammingStateFact = Fact(0, QStringLiteral("jammingState"), FactMetaData::valueTypeUint8) protected
Definition at line 70 of file VehicleGPSFactGroup.h.
_latFact
Fact VehicleGPSFactGroup::_latFact = Fact(0, QStringLiteral("lat"), FactMetaData::valueTypeDouble) protected
Definition at line 59 of file VehicleGPSFactGroup.h.
_lockFact
Fact VehicleGPSFactGroup::_lockFact = Fact(0, QStringLiteral("lock"), FactMetaData::valueTypeInt32) protected
Definition at line 67 of file VehicleGPSFactGroup.h.
_lonFact
Fact VehicleGPSFactGroup::_lonFact = Fact(0, QStringLiteral("lon"), FactMetaData::valueTypeDouble) protected
Definition at line 60 of file VehicleGPSFactGroup.h.
_mgrsFact
Fact VehicleGPSFactGroup::_mgrsFact = Fact(0, QStringLiteral("mgrs"), FactMetaData::valueTypeString) protected
Definition at line 61 of file VehicleGPSFactGroup.h.
_postProcessingQualityFact
Fact VehicleGPSFactGroup::_postProcessingQualityFact = Fact(0, QStringLiteral("postProcessingQuality"), FactMetaData::valueTypeUint8) protected
Definition at line 75 of file VehicleGPSFactGroup.h.
_spoofingStateFact
Fact VehicleGPSFactGroup::_spoofingStateFact = Fact(0, QStringLiteral("spoofingState"), FactMetaData::valueTypeUint8) protected
Definition at line 69 of file VehicleGPSFactGroup.h.
_systemErrorsFact
Fact VehicleGPSFactGroup::_systemErrorsFact = Fact(0, QStringLiteral("systemErrors"), FactMetaData::valueTypeUint32) protected
Definition at line 68 of file VehicleGPSFactGroup.h.
_systemQualityFact
Fact VehicleGPSFactGroup::_systemQualityFact = Fact(0, QStringLiteral("systemQuality"), FactMetaData::valueTypeUint8) protected
Definition at line 73 of file VehicleGPSFactGroup.h.
_vdopFact
Fact VehicleGPSFactGroup::_vdopFact = Fact(0, QStringLiteral("vdop"), FactMetaData::valueTypeDouble) protected
Definition at line 63 of file VehicleGPSFactGroup.h.
_yawFact
Fact VehicleGPSFactGroup::_yawFact = Fact(0, QStringLiteral("yaw"), FactMetaData::valueTypeDouble) protected
Definition at line 65 of file VehicleGPSFactGroup.h.
The documentation for this class was generated from the following files:
src/Vehicle/FactGroups/VehicleGPSFactGroup.h
src/Vehicle/FactGroups/VehicleGPSFactGroup.cc