QGroundControl: RemoteIDManager Class Reference
RemoteIDManager Class Reference
#include <RemoteIDManager.h>
Public Types
enum LocationTypes { TAKEOFF , LiveGNSS , FIXED }
enum Region { FAA , EU }
Signals
void availableChanged ()
void armStatusGoodChanged ()
void armStatusErrorChanged ()
void commsGoodChanged ()
void gcsGPSGoodChanged ()
void basicIDGoodChanged ()
void emergencyDeclaredChanged ()
void operatorIDGoodChanged ()
Public Member Functions
RemoteIDManager (Vehicle *vehicle)
bool available READ available NOTIFY availableChanged (bool armStatusGood READ armStatusGood NOTIFY armStatusGoodChanged) 1(QString armStatusError READ armStatusError NOTIFY armStatusErrorChanged) 1(bool commsGood READ commsGood NOTIFY commsGoodChanged) 1(bool gcsGPSGood READ gcsGPSGood NOTIFY gcsGPSGoodChanged) 1(bool basicIDGood READ basicIDGood NOTIFY basicIDGoodChanged) 1(bool emergencyDeclared READ emergencyDeclared NOTIFY emergencyDeclaredChanged) 1(bool operatorIDGood READ operatorIDGood NOTIFY operatorIDGoodChanged) 1 void checkOperatorID(const QString &operatorID)
< true: the vehicle supports Mavlink Open Drone ID messages
void setOperatorID ()
void setEmergency (bool declare)
bool available (void) const
bool armStatusGood (void) const
QString armStatusError (void) const
bool commsGood (void) const
bool gcsGPSGood (void) const
bool basicIDGood (void) const
bool emergencyDeclared (void) const
bool operatorIDGood (void) const
void mavlinkMessageReceived (mavlink_message_t &message)
Detailed Description
Definition at line 18 of file RemoteIDManager.h.
Member Enumeration Documentation
LocationTypes
enum RemoteIDManager::LocationTypes
Enumerator
TAKEOFF
LiveGNSS
FIXED
Definition at line 53 of file RemoteIDManager.h.
Region
enum RemoteIDManager::Region
Enumerator
FAA
EU
Definition at line 59 of file RemoteIDManager.h.
Constructor & Destructor Documentation
RemoteIDManager()
RemoteIDManager::RemoteIDManager (Vehicle * vehicle)
Definition at line 22 of file RemoteIDManager.cc.
References RemoteIDSettings::basicID(), RemoteIDSettings::basicIDType(), RemoteIDSettings::basicIDUaType(), Vehicle::compId(), EU, Vehicle::id(), RemoteIDSettings::operatorID(), operatorIDGoodChanged(), RemoteIDSettings::operatorIDValid(), QGCPositionManager::positionInfoUpdated(), Fact::rawValueChanged(), RemoteIDSettings::region(), RID_TIMEOUT, and SENDING_RATE_MSEC.
Member Function Documentation
armStatusError()
QString RemoteIDManager::armStatusError (void) const inline
Definition at line 44 of file RemoteIDManager.h.
armStatusErrorChanged
void RemoteIDManager::armStatusErrorChanged () signal
armStatusGood()
bool RemoteIDManager::armStatusGood (void) const inline
Definition at line 43 of file RemoteIDManager.h.
armStatusGoodChanged
void RemoteIDManager::armStatusGoodChanged () signal
available()
bool RemoteIDManager::available (void) const inline
Definition at line 42 of file RemoteIDManager.h.
availableChanged [1/2]
void RemoteIDManager::availableChanged () signal
availableChanged() [2/2]
bool available READ available NOTIFY RemoteIDManager::availableChanged (bool armStatusGood READ armStatusGood NOTIFY armStatusGoodChanged) const &
< true: the vehicle supports Mavlink Open Drone ID messages
basicIDGood()
bool RemoteIDManager::basicIDGood (void) const inline
Definition at line 47 of file RemoteIDManager.h.
basicIDGoodChanged
void RemoteIDManager::basicIDGoodChanged () signal
commsGood()
bool RemoteIDManager::commsGood (void) const inline
Definition at line 45 of file RemoteIDManager.h.
commsGoodChanged
void RemoteIDManager::commsGoodChanged () signal
emergencyDeclared()
bool RemoteIDManager::emergencyDeclared (void) const inline
Definition at line 48 of file RemoteIDManager.h.
emergencyDeclaredChanged
void RemoteIDManager::emergencyDeclaredChanged () signal
Referenced by setEmergency().
gcsGPSGood()
bool RemoteIDManager::gcsGPSGood (void) const inline
Definition at line 46 of file RemoteIDManager.h.
gcsGPSGoodChanged
void RemoteIDManager::gcsGPSGoodChanged () signal
mavlinkMessageReceived()
void RemoteIDManager::mavlinkMessageReceived (mavlink_message_t & message)
Definition at line 68 of file RemoteIDManager.cc.
operatorIDGood()
bool RemoteIDManager::operatorIDGood (void) const inline
Definition at line 49 of file RemoteIDManager.h.
operatorIDGoodChanged
void RemoteIDManager::operatorIDGoodChanged () signal
Referenced by RemoteIDManager(), and setOperatorID().
setEmergency()
void RemoteIDManager::setEmergency (bool declare)
Definition at line 476 of file RemoteIDManager.cc.
References emergencyDeclaredChanged().
setOperatorID()
void RemoteIDManager::setOperatorID ()
Definition at line 407 of file RemoteIDManager.cc.
References EU, RemoteIDSettings::operatorID(), operatorIDGoodChanged(), RemoteIDSettings::operatorIDType(), RemoteIDSettings::operatorIDValid(), and RemoteIDSettings::region().
The documentation for this class was generated from the following files:
src/Vehicle/RemoteIDManager.h
src/Vehicle/RemoteIDManager.cc