QGroundControl: FirmwarePluginFactory Class Reference
FirmwarePluginFactory Class Reference abstract
#include <FirmwarePluginFactory.h>
Public Member Functions
FirmwarePluginFactory (QObject *parent=nullptr)
virtual ~FirmwarePluginFactory ()
virtual FirmwarePlugin * firmwarePluginForAutopilot (MAV_AUTOPILOT autopilotType, MAV_TYPE vehicleType)=0
virtual QList< QGCMAVLink::FirmwareClass_t > supportedFirmwareClasses () const =0
virtual QList< QGCMAVLink::VehicleClass_t > supportedVehicleClasses () const
Detailed Description
Definition at line 12 of file FirmwarePluginFactory.h.
Constructor & Destructor Documentation
FirmwarePluginFactory()
FirmwarePluginFactory::FirmwarePluginFactory (QObject * parent = nullptr) explicit
Definition at line 11 of file FirmwarePluginFactory.cc.
References FirmwarePluginFactoryRegister::instance(), and FirmwarePluginFactoryRegister::registerPluginFactory().
~FirmwarePluginFactory()
FirmwarePluginFactory::~FirmwarePluginFactory () virtual
Definition at line 19 of file FirmwarePluginFactory.cc.
Member Function Documentation
firmwarePluginForAutopilot()
virtual FirmwarePlugin * FirmwarePluginFactory::firmwarePluginForAutopilot (MAV_AUTOPILOT autopilotType, MAV_TYPE vehicleType) pure virtual
Returns appropriate plugin for autopilot type.
Parameters
autopilotType Type of autopilot to return plugin for.
vehicleType Vehicle type of autopilot to return plugin for.
Returns
Singleton FirmwarePlugin instance for the specified MAV_AUTOPILOT.
Implemented in PX4FirmwarePluginFactory, and APMFirmwarePluginFactory.
Referenced by FirmwarePluginManager::firmwarePluginForAutopilot().
supportedFirmwareClasses()
virtual QList< QGCMAVLink::FirmwareClass_t > FirmwarePluginFactory::supportedFirmwareClasses () const pure virtual
Returns
List of firmware classes this plugin supports.
Implemented in APMFirmwarePluginFactory, and PX4FirmwarePluginFactory.
supportedVehicleClasses()
virtual QList< QGCMAVLink::VehicleClass_t > FirmwarePluginFactory::supportedVehicleClasses () const inline virtual
Returns
List of vehicle classes this plugin supports.
Definition at line 30 of file FirmwarePluginFactory.h.
References QGCMAVLink::allVehicleClasses().
Referenced by FirmwarePluginManager::supportedVehicleClasses().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/FirmwarePluginFactory.h
src/FirmwarePlugin/FirmwarePluginFactory.cc