QGroundControl: Viewer3DTerrainGeometry Class Reference
Viewer3DTerrainGeometry Class Reference
#include <Viewer3DTerrainGeometry.h>
Signals
void sectorCountChanged ()
void stackCountChanged ()
void roiMinChanged ()
void roiMaxChanged ()
void refCoordinateChanged ()
Public Member Functions
Viewer3DTerrainGeometry ()
void updateEarthData ()
int sectorCount () const
void setSectorCount (int newSectorCount)
int stackCount () const
void setStackCount (int newStackCount)
QGeoCoordinate roiMin () const
void setRoiMin (const QGeoCoordinate &newRoiMin)
QGeoCoordinate roiMax () const
void setRoiMax (const QGeoCoordinate &newRoiMax)
QGeoCoordinate refCoordinate () const
void setRefCoordinate (const QGeoCoordinate &newRefCoordinate)
Detailed Description
Definition at line 9 of file Viewer3DTerrainGeometry.h.
Constructor & Destructor Documentation
Viewer3DTerrainGeometry()
Viewer3DTerrainGeometry::Viewer3DTerrainGeometry () explicit
Definition at line 14 of file Viewer3DTerrainGeometry.cc.
References Fact::rawValueChanged(), refCoordinateChanged(), and updateEarthData().
Member Function Documentation
refCoordinate()
QGeoCoordinate Viewer3DTerrainGeometry::refCoordinate () const inline
Definition at line 39 of file Viewer3DTerrainGeometry.h.
Referenced by updateEarthData().
refCoordinateChanged
void Viewer3DTerrainGeometry::refCoordinateChanged () signal
Referenced by setRefCoordinate(), and Viewer3DTerrainGeometry().
roiMax()
QGeoCoordinate Viewer3DTerrainGeometry::roiMax () const inline
Definition at line 36 of file Viewer3DTerrainGeometry.h.
Referenced by updateEarthData().
roiMaxChanged
void Viewer3DTerrainGeometry::roiMaxChanged () signal
Referenced by setRoiMax().
roiMin()
QGeoCoordinate Viewer3DTerrainGeometry::roiMin () const inline
Definition at line 33 of file Viewer3DTerrainGeometry.h.
Referenced by updateEarthData().
roiMinChanged
void Viewer3DTerrainGeometry::roiMinChanged () signal
Referenced by setRoiMin().
sectorCount()
int Viewer3DTerrainGeometry::sectorCount () const inline
Definition at line 27 of file Viewer3DTerrainGeometry.h.
sectorCountChanged
void Viewer3DTerrainGeometry::sectorCountChanged () signal
Referenced by setSectorCount().
setRefCoordinate()
void Viewer3DTerrainGeometry::setRefCoordinate (const QGeoCoordinate & newRefCoordinate)
Definition at line 272 of file Viewer3DTerrainGeometry.cc.
References refCoordinateChanged().
setRoiMax()
void Viewer3DTerrainGeometry::setRoiMax (const QGeoCoordinate & newRoiMax)
Definition at line 263 of file Viewer3DTerrainGeometry.cc.
References roiMaxChanged().
setRoiMin()
void Viewer3DTerrainGeometry::setRoiMin (const QGeoCoordinate & newRoiMin)
Definition at line 254 of file Viewer3DTerrainGeometry.cc.
References roiMinChanged().
setSectorCount()
void Viewer3DTerrainGeometry::setSectorCount (int newSectorCount)
Definition at line 108 of file Viewer3DTerrainGeometry.cc.
References sectorCountChanged().
setStackCount()
void Viewer3DTerrainGeometry::setStackCount (int newStackCount)
Definition at line 117 of file Viewer3DTerrainGeometry.cc.
References stackCountChanged().
stackCount()
int Viewer3DTerrainGeometry::stackCount () const inline
Definition at line 30 of file Viewer3DTerrainGeometry.h.
stackCountChanged
void Viewer3DTerrainGeometry::stackCountChanged () signal
Referenced by setStackCount().
updateEarthData()
void Viewer3DTerrainGeometry::updateEarthData ()
Definition at line 21 of file Viewer3DTerrainGeometry.cc.
References refCoordinate(), roiMax(), and roiMin().
Referenced by Viewer3DTerrainGeometry().
The documentation for this class was generated from the following files:
src/Viewer3D/Viewer3DTerrainGeometry.h
src/Viewer3D/Viewer3DTerrainGeometry.cc