QGroundControl: SimulatedCameraControl Class Reference
SimulatedCameraControl Class Reference
#include <SimulatedCameraControl.h>
Public Member Functions
SimulatedCameraControl (Vehicle *vehicle, QObject *parent=nullptr)
~SimulatedCameraControl () override
void setCameraModeVideo () override
void setCameraModePhoto () override
void toggleCameraMode () override
bool takePhoto () override
bool startVideoRecording () override
bool stopVideoRecording () override
bool toggleVideoRecording () override
void resetSettings () override
void formatCard (int id=1) override
void stepZoom (int) override
void startZoom (int) override
void stopZoom () override
void stopStream () override
bool stopTakePhoto () override
void resumeStream () override
void startTrackingRect (QRectF) override
void startTrackingPoint (QPointF, double) override
void stopTracking () override
int version () const override
QString modelName () const override
QString vendor () const override
QString firmwareVersion () const override
qreal focalLength () const override
QSizeF sensorSize () const override
QSize resolution () const override
bool capturesVideo () const override
bool capturesPhotos () const override
bool hasModes () const override
bool hasZoom () const override
bool hasFocus () const override
bool hasTracking () const override
bool supportsTrackingPoint () const override
bool supportsTrackingRect () const override
bool hasVideoStream () const override
bool photosInVideoMode () const override
bool videoInPhotoMode () const override
CaptureVideoState captureVideoState () const override
CapturePhotosState capturePhotosState () const override
int compID () const override
bool isBasic () const override
StorageStatus storageStatus () const override
QStringList activeSettings () const override
quint32 storageFree () const override
QString storageFreeStr () const override
quint32 storageTotal () const override
int batteryRemaining () const override
QString batteryRemainingStr () const override
bool paramComplete () const override
qreal zoomLevel () const override
qreal focusLevel () const override
QmlObjectListModel * streams () override
QGCVideoStreamInfo * currentStreamInstance () override
QGCVideoStreamInfo * thermalStreamInstance () override
int currentStream () const override
void setCurrentStream (int) override
bool autoStream () const override
quint32 recordTime () const override
QString recordTimeStr () const override
Fact * exposureMode () override
Fact * ev () override
Fact * iso () override
Fact * shutterSpeed () override
Fact * aperture () override
Fact * wb () override
Fact * mode () override
QStringList streamLabels () const override
Stream names to show the user (for selection)
ThermalViewMode thermalMode () const override
void setThermalMode (ThermalViewMode) override
double thermalOpacity () const override
void setThermalOpacity (double) override
void setZoomLevel (qreal) override
void setFocusLevel (qreal) override
void setCameraMode (CameraMode cameraMode) override
void setPhotoCaptureMode (PhotoCaptureMode mode) override
void setPhotoLapse (qreal) override
void setPhotoLapseCount (int) override
bool trackingEnabled () const override
void setTrackingEnabled (bool) override
bool trackingImageIsActive () const override
bool trackingImageIsPoint () const override
QRectF trackingImageRect () const override
QPointF trackingImagePoint () const override
qreal trackingImageRadius () const override
void factChanged (Fact *) override
Notify controller a parameter has changed.
bool incomingParameter (Fact *, QVariant &) override
Allow controller to modify or invalidate incoming parameter.
bool validateParameter (Fact *, QVariant &) override
Allow controller to modify or invalidate parameter change.
void handleBatteryStatus (const mavlink_battery_status_t &) override
void handleCameraCaptureStatus (const mavlink_camera_capture_status_t &) override
void handleParamExtAck (const mavlink_param_ext_ack_t &) override
void handleParamExtValue (const mavlink_param_ext_value_t &) override
void handleCameraSettings (const mavlink_camera_settings_t &) override
void handleStorageInformation (const mavlink_storage_information_t &) override
void handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t &) override
void handleVideoStreamInformation (const mavlink_video_stream_information_t &) override
void handleVideoStreamStatus (const mavlink_video_stream_status_t &) override
Public Member Functions inherited from MavlinkCameraControlInterface
MavlinkCameraControlInterface (Vehicle *vehicle, QObject *parent=nullptr)
virtual ~MavlinkCameraControlInterface ()
virtual PhotoCaptureMode photoCaptureMode () const
virtual qreal photoLapse () const
virtual int photoLapseCount () const
virtual CameraMode cameraMode () const
QString cameraModeToStr (CameraMode mode)
QString captureImageStatusToStr (uint8_t image_status)
QString captureVideoStatusToStr (uint8_t video_status)
QString storageStatusToStr (uint8_t status)
Protected Slots
void _paramDone () override
Protected Slots inherited from MavlinkCameraControlInterface
virtual void _paramDone ()=0
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Additional Inherited Members
Public Types inherited from MavlinkCameraControlInterface
enum CameraMode { CAM_MODE_UNDEFINED = -1 , CAM_MODE_PHOTO = 0 , CAM_MODE_VIDEO = 1 , CAM_MODE_SURVEY = 2 }
enum PhotoCaptureMode { PHOTO_CAPTURE_SINGLE = 0 , PHOTO_CAPTURE_TIMELAPSE }
enum CaptureVideoState { CaptureVideoStateDisabled = 0 , CaptureVideoStateIdle , CaptureVideoStateCapturing }
enum CapturePhotosState { CapturePhotosStateDisabled = 0 , CapturePhotosStateIdle , CapturePhotosStateCapturingSinglePhoto , CapturePhotosStateCapturingMultiplePhotos }
enum StorageStatus { STORAGE_EMPTY = STORAGE_STATUS_EMPTY , STORAGE_UNFORMATTED = STORAGE_STATUS_UNFORMATTED , STORAGE_READY = STORAGE_STATUS_READY , STORAGE_NOT_SUPPORTED = STORAGE_STATUS_NOT_SUPPORTED }
enum ThermalViewMode { THERMAL_OFF = 0 , THERMAL_BLEND , THERMAL_FULL , THERMAL_PIP }
Signals inherited from MavlinkCameraControlInterface
void infoChanged ()
void videoCaptureStatusChanged ()
void photoCaptureStatusChanged ()
void photoCaptureModeChanged ()
void photoLapseChanged ()
void photoLapseCountChanged ()
void cameraModeChanged ()
void activeSettingsChanged ()
void storageFreeChanged ()
void storageTotalChanged ()
void batteryRemainingChanged ()
void dataReady (const QByteArray &data)
void parametersReady ()
void zoomLevelChanged ()
void focusLevelChanged ()
void streamsChanged ()
void currentStreamChanged ()
void thermalStreamChanged ()
void autoStreamChanged ()
void recordTimeChanged ()
void streamLabelsChanged ()
void trackingEnabledChanged ()
void trackingImageIsActiveChanged ()
void trackingImageIsPointChanged ()
void trackingImageRectChanged ()
void trackingImagePointChanged ()
void trackingImageRadiusChanged ()
void thermalModeChanged ()
void thermalOpacityChanged ()
void storageStatusChanged ()
void captureVideoStateChanged ()
void capturePhotosStateChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Types inherited from MavlinkCameraControlInterface
enum VideoCaptureStatus { VIDEO_CAPTURE_STATUS_STOPPED = 0 , VIDEO_CAPTURE_STATUS_RUNNING , VIDEO_CAPTURE_STATUS_LAST , VIDEO_CAPTURE_STATUS_UNDEFINED = 255 }
enum PhotoCaptureStatus {
PHOTO_CAPTURE_IDLE = 0 , PHOTO_CAPTURE_IN_PROGRESS , PHOTO_CAPTURE_INTERVAL_IDLE , PHOTO_CAPTURE_INTERVAL_IN_PROGRESS ,
PHOTO_CAPTURE_LAST , PHOTO_CAPTURE_STATUS_UNDEFINED = 255
}
Protected Member Functions inherited from MavlinkCameraControlInterface
VideoCaptureStatus _videoCaptureStatus () const
PhotoCaptureStatus _photoCaptureStatus () const
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes inherited from MavlinkCameraControlInterface
Vehicle * _vehicle = nullptr
CameraMode _cameraMode = CAM_MODE_UNDEFINED
VideoCaptureStatus _videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED
PhotoCaptureStatus _photoCaptureStatusValue = PHOTO_CAPTURE_IDLE
PhotoCaptureMode _photoCaptureMode = PHOTO_CAPTURE_SINGLE
qreal _photoLapse = 1.0
int _photoLapseCount = 0
QTimer _videoRecordTimeUpdateTimer
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Creates a simulated Camera Control which supports: Video record if a manual stream is available Photo capture using DO_DIGICAM_CONTROL if the setting is enabled It does not support time lapse capture
Definition at line 15 of file SimulatedCameraControl.h.
Constructor & Destructor Documentation
SimulatedCameraControl()
SimulatedCameraControl::SimulatedCameraControl (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 11 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::cameraModeChanged(), MavlinkCameraControlInterface::capturePhotosStateChanged(), MavlinkCameraControlInterface::captureVideoStateChanged(), VideoManager::decodingChanged(), VideoManager::hasVideoChanged(), MavlinkCameraControlInterface::infoChanged(), VideoManager::instance(), MavlinkCameraControlInterface::photoCaptureStatusChanged(), Fact::rawValueChanged(), VideoManager::recordingChanged(), MavlinkCameraControlInterface::recordTimeChanged(), FlyViewSettings::showSimpleCameraControl(), and MavlinkCameraControlInterface::videoCaptureStatusChanged().
~SimulatedCameraControl()
SimulatedCameraControl::~SimulatedCameraControl () override
Definition at line 49 of file SimulatedCameraControl.cc.
Member Function Documentation
_paramDone
void SimulatedCameraControl::_paramDone () inline override protected slot
Definition at line 131 of file SimulatedCameraControl.h.
activeSettings()
QStringList SimulatedCameraControl::activeSettings () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 66 of file SimulatedCameraControl.h.
aperture()
Fact * SimulatedCameraControl::aperture () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 89 of file SimulatedCameraControl.h.
autoStream()
bool SimulatedCameraControl::autoStream () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 81 of file SimulatedCameraControl.h.
batteryRemaining()
int SimulatedCameraControl::batteryRemaining () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 70 of file SimulatedCameraControl.h.
batteryRemainingStr()
QString SimulatedCameraControl::batteryRemainingStr () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 71 of file SimulatedCameraControl.h.
capturePhotosState()
MavlinkCameraControlInterface::CapturePhotosState SimulatedCameraControl::capturePhotosState () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 233 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_photoCaptureStatus(), MavlinkCameraControlInterface::CapturePhotosStateCapturingMultiplePhotos, MavlinkCameraControlInterface::CapturePhotosStateCapturingSinglePhoto, MavlinkCameraControlInterface::CapturePhotosStateDisabled, MavlinkCameraControlInterface::CapturePhotosStateIdle, capturesPhotos(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IN_PROGRESS, MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IDLE, and MavlinkCameraControlInterface::PHOTO_CAPTURE_INTERVAL_IN_PROGRESS.
capturesPhotos()
bool SimulatedCameraControl::capturesPhotos () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 203 of file SimulatedCameraControl.cc.
References FlyViewSettings::showSimpleCameraControl().
Referenced by capturePhotosState(), hasModes(), and takePhoto().
capturesVideo()
bool SimulatedCameraControl::capturesVideo () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 198 of file SimulatedCameraControl.cc.
References VideoManager::hasVideo(), and VideoManager::instance().
Referenced by captureVideoState(), hasModes(), and startVideoRecording().
captureVideoState()
MavlinkCameraControlInterface::CaptureVideoState SimulatedCameraControl::captureVideoState () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 219 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_photoCaptureStatus(), MavlinkCameraControlInterface::_videoCaptureStatus(), capturesVideo(), MavlinkCameraControlInterface::CaptureVideoStateCapturing, MavlinkCameraControlInterface::CaptureVideoStateDisabled, MavlinkCameraControlInterface::CaptureVideoStateIdle, VideoManager::instance(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
compID()
int SimulatedCameraControl::compID () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 63 of file SimulatedCameraControl.h.
currentStream()
int SimulatedCameraControl::currentStream () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 79 of file SimulatedCameraControl.h.
currentStreamInstance()
QGCVideoStreamInfo * SimulatedCameraControl::currentStreamInstance () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 77 of file SimulatedCameraControl.h.
ev()
Fact * SimulatedCameraControl::ev () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 86 of file SimulatedCameraControl.h.
exposureMode()
Fact * SimulatedCameraControl::exposureMode () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 85 of file SimulatedCameraControl.h.
factChanged()
void SimulatedCameraControl::factChanged (Fact * pFact) inline override virtual
Notify controller a parameter has changed.
Implements MavlinkCameraControlInterface.
Definition at line 116 of file SimulatedCameraControl.h.
firmwareVersion()
QString SimulatedCameraControl::firmwareVersion () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 45 of file SimulatedCameraControl.h.
focalLength()
qreal SimulatedCameraControl::focalLength () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 46 of file SimulatedCameraControl.h.
focusLevel()
qreal SimulatedCameraControl::focusLevel () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 74 of file SimulatedCameraControl.h.
formatCard()
void SimulatedCameraControl::formatCard (int id = 1) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 31 of file SimulatedCameraControl.h.
handleBatteryStatus()
void SimulatedCameraControl::handleBatteryStatus (const mavlink_battery_status_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 120 of file SimulatedCameraControl.h.
handleCameraCaptureStatus()
void SimulatedCameraControl::handleCameraCaptureStatus (const mavlink_camera_capture_status_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 121 of file SimulatedCameraControl.h.
handleCameraSettings()
void SimulatedCameraControl::handleCameraSettings (const mavlink_camera_settings_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 124 of file SimulatedCameraControl.h.
handleParamExtAck()
void SimulatedCameraControl::handleParamExtAck (const mavlink_param_ext_ack_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 122 of file SimulatedCameraControl.h.
handleParamExtValue()
void SimulatedCameraControl::handleParamExtValue (const mavlink_param_ext_value_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 123 of file SimulatedCameraControl.h.
handleStorageInformation()
void SimulatedCameraControl::handleStorageInformation (const mavlink_storage_information_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 125 of file SimulatedCameraControl.h.
handleTrackingImageStatus()
void SimulatedCameraControl::handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 126 of file SimulatedCameraControl.h.
handleVideoStreamInformation()
void SimulatedCameraControl::handleVideoStreamInformation (const mavlink_video_stream_information_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 127 of file SimulatedCameraControl.h.
handleVideoStreamStatus()
void SimulatedCameraControl::handleVideoStreamStatus (const mavlink_video_stream_status_t &) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 128 of file SimulatedCameraControl.h.
hasFocus()
bool SimulatedCameraControl::hasFocus () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 53 of file SimulatedCameraControl.h.
hasModes()
bool SimulatedCameraControl::hasModes () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 209 of file SimulatedCameraControl.cc.
References capturesPhotos(), and capturesVideo().
Referenced by setCameraMode(), setCameraModePhoto(), setCameraModeVideo(), and toggleCameraMode().
hasTracking()
bool SimulatedCameraControl::hasTracking () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 54 of file SimulatedCameraControl.h.
hasVideoStream()
bool SimulatedCameraControl::hasVideoStream () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 214 of file SimulatedCameraControl.cc.
References VideoManager::decoding(), and VideoManager::instance().
hasZoom()
bool SimulatedCameraControl::hasZoom () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 52 of file SimulatedCameraControl.h.
incomingParameter()
bool SimulatedCameraControl::incomingParameter (Fact * pFact, QVariant & newValue) inline override virtual
Allow controller to modify or invalidate incoming parameter.
Implements MavlinkCameraControlInterface.
Definition at line 117 of file SimulatedCameraControl.h.
isBasic()
bool SimulatedCameraControl::isBasic () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 64 of file SimulatedCameraControl.h.
iso()
Fact * SimulatedCameraControl::iso () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 87 of file SimulatedCameraControl.h.
mode()
Fact * SimulatedCameraControl::mode () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 91 of file SimulatedCameraControl.h.
modelName()
QString SimulatedCameraControl::modelName () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 43 of file SimulatedCameraControl.h.
paramComplete()
bool SimulatedCameraControl::paramComplete () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 72 of file SimulatedCameraControl.h.
photosInVideoMode()
bool SimulatedCameraControl::photosInVideoMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 58 of file SimulatedCameraControl.h.
recordTime()
quint32 SimulatedCameraControl::recordTime () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 193 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer.
Referenced by recordTimeStr().
recordTimeStr()
QString SimulatedCameraControl::recordTimeStr () const override virtual
Implements MavlinkCameraControlInterface.
Definition at line 54 of file SimulatedCameraControl.cc.
References recordTime().
resetSettings()
void SimulatedCameraControl::resetSettings () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 30 of file SimulatedCameraControl.h.
resolution()
QSize SimulatedCameraControl::resolution () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 48 of file SimulatedCameraControl.h.
resumeStream()
void SimulatedCameraControl::resumeStream () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 37 of file SimulatedCameraControl.h.
sensorSize()
QSizeF SimulatedCameraControl::sensorSize () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 47 of file SimulatedCameraControl.h.
setCameraMode()
void SimulatedCameraControl::setCameraMode (CameraMode cameraMode) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 59 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_VIDEO, MavlinkCameraControlInterface::cameraMode(), MavlinkCameraControlInterface::cameraModeToStr(), and hasModes().
setCameraModePhoto()
void SimulatedCameraControl::setCameraModePhoto () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 117 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::CAM_MODE_PHOTO, and hasModes().
Referenced by toggleCameraMode().
setCameraModeVideo()
void SimulatedCameraControl::setCameraModeVideo () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 107 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::CAM_MODE_VIDEO, and hasModes().
Referenced by toggleCameraMode().
setCurrentStream()
void SimulatedCameraControl::setCurrentStream (int) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 80 of file SimulatedCameraControl.h.
setFocusLevel()
void SimulatedCameraControl::setFocusLevel (qreal) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 101 of file SimulatedCameraControl.h.
setPhotoCaptureMode()
void SimulatedCameraControl::setPhotoCaptureMode (MavlinkCameraControlInterface::PhotoCaptureMode photoCaptureMode) override virtual
Implements MavlinkCameraControlInterface.
Definition at line 244 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_photoCaptureMode, MavlinkCameraControlInterface::PHOTO_CAPTURE_TIMELAPSE, MavlinkCameraControlInterface::photoCaptureMode(), and MavlinkCameraControlInterface::photoCaptureModeChanged().
setPhotoLapse()
void SimulatedCameraControl::setPhotoLapse (qreal) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 104 of file SimulatedCameraControl.h.
setPhotoLapseCount()
void SimulatedCameraControl::setPhotoLapseCount (int) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 105 of file SimulatedCameraControl.h.
setThermalMode()
void SimulatedCameraControl::setThermalMode (ThermalViewMode) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 96 of file SimulatedCameraControl.h.
setThermalOpacity()
void SimulatedCameraControl::setThermalOpacity (double) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 98 of file SimulatedCameraControl.h.
setTrackingEnabled()
void SimulatedCameraControl::setTrackingEnabled (bool) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 108 of file SimulatedCameraControl.h.
setZoomLevel()
void SimulatedCameraControl::setZoomLevel (qreal) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 100 of file SimulatedCameraControl.h.
shutterSpeed()
Fact * SimulatedCameraControl::shutterSpeed () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 88 of file SimulatedCameraControl.h.
startTrackingPoint()
void SimulatedCameraControl::startTrackingPoint (QPointF , double) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 39 of file SimulatedCameraControl.h.
startTrackingRect()
void SimulatedCameraControl::startTrackingRect (QRectF) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 38 of file SimulatedCameraControl.h.
startVideoRecording()
bool SimulatedCameraControl::startVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 160 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, MavlinkCameraControlInterface::_videoCaptureStatus(), MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer, MavlinkCameraControlInterface::CAM_MODE_PHOTO, capturesVideo(), VideoManager::instance(), VideoManager::startRecording(), and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
Referenced by toggleVideoRecording().
startZoom()
void SimulatedCameraControl::startZoom (int) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 33 of file SimulatedCameraControl.h.
stepZoom()
void SimulatedCameraControl::stepZoom (int) inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 32 of file SimulatedCameraControl.h.
stopStream()
void SimulatedCameraControl::stopStream () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 35 of file SimulatedCameraControl.h.
stopTakePhoto()
bool SimulatedCameraControl::stopTakePhoto () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 36 of file SimulatedCameraControl.h.
stopTracking()
void SimulatedCameraControl::stopTracking () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 40 of file SimulatedCameraControl.h.
stopVideoRecording()
bool SimulatedCameraControl::stopVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 181 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_videoCaptureStatus(), MavlinkCameraControlInterface::_videoRecordTimeUpdateTimer, VideoManager::instance(), VideoManager::stopRecording(), and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
Referenced by toggleVideoRecording().
stopZoom()
void SimulatedCameraControl::stopZoom () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 34 of file SimulatedCameraControl.h.
storageFree()
quint32 SimulatedCameraControl::storageFree () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 67 of file SimulatedCameraControl.h.
storageFreeStr()
QString SimulatedCameraControl::storageFreeStr () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 68 of file SimulatedCameraControl.h.
storageStatus()
StorageStatus SimulatedCameraControl::storageStatus () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 65 of file SimulatedCameraControl.h.
References MavlinkCameraControlInterface::STORAGE_NOT_SUPPORTED.
storageTotal()
quint32 SimulatedCameraControl::storageTotal () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 69 of file SimulatedCameraControl.h.
streamLabels()
QStringList SimulatedCameraControl::streamLabels () const inline override virtual
Stream names to show the user (for selection)
Implements MavlinkCameraControlInterface.
Definition at line 93 of file SimulatedCameraControl.h.
streams()
QmlObjectListModel * SimulatedCameraControl::streams () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 76 of file SimulatedCameraControl.h.
supportsTrackingPoint()
bool SimulatedCameraControl::supportsTrackingPoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 55 of file SimulatedCameraControl.h.
supportsTrackingRect()
bool SimulatedCameraControl::supportsTrackingRect () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 56 of file SimulatedCameraControl.h.
takePhoto()
bool SimulatedCameraControl::takePhoto () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 127 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, MavlinkCameraControlInterface::_photoCaptureStatus(), MavlinkCameraControlInterface::_photoCaptureStatusValue, MavlinkCameraControlInterface::_vehicle, MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_SURVEY, MavlinkCameraControlInterface::cameraModeToStr(), capturesPhotos(), MavlinkCameraControlInterface::PHOTO_CAPTURE_IDLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_IN_PROGRESS, MavlinkCameraControlInterface::PHOTO_CAPTURE_SINGLE, MavlinkCameraControlInterface::PHOTO_CAPTURE_TIMELAPSE, MavlinkCameraControlInterface::photoCaptureMode(), MavlinkCameraControlInterface::photoCaptureStatusChanged(), qgcApp, and Vehicle::triggerSimpleCamera().
thermalMode()
ThermalViewMode SimulatedCameraControl::thermalMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 95 of file SimulatedCameraControl.h.
References MavlinkCameraControlInterface::THERMAL_OFF.
thermalOpacity()
double SimulatedCameraControl::thermalOpacity () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 97 of file SimulatedCameraControl.h.
thermalStreamInstance()
QGCVideoStreamInfo * SimulatedCameraControl::thermalStreamInstance () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 78 of file SimulatedCameraControl.h.
toggleCameraMode()
void SimulatedCameraControl::toggleCameraMode () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 89 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_cameraMode, MavlinkCameraControlInterface::CAM_MODE_PHOTO, MavlinkCameraControlInterface::CAM_MODE_SURVEY, MavlinkCameraControlInterface::CAM_MODE_VIDEO, hasModes(), setCameraModePhoto(), and setCameraModeVideo().
toggleVideoRecording()
bool SimulatedCameraControl::toggleVideoRecording () override virtual
Implements MavlinkCameraControlInterface.
Definition at line 102 of file SimulatedCameraControl.cc.
References MavlinkCameraControlInterface::_videoCaptureStatus(), startVideoRecording(), stopVideoRecording(), and MavlinkCameraControlInterface::VIDEO_CAPTURE_STATUS_RUNNING.
trackingEnabled()
bool SimulatedCameraControl::trackingEnabled () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 107 of file SimulatedCameraControl.h.
trackingImageIsActive()
bool SimulatedCameraControl::trackingImageIsActive () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 110 of file SimulatedCameraControl.h.
trackingImageIsPoint()
bool SimulatedCameraControl::trackingImageIsPoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 111 of file SimulatedCameraControl.h.
trackingImagePoint()
QPointF SimulatedCameraControl::trackingImagePoint () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 113 of file SimulatedCameraControl.h.
trackingImageRadius()
qreal SimulatedCameraControl::trackingImageRadius () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 114 of file SimulatedCameraControl.h.
trackingImageRect()
QRectF SimulatedCameraControl::trackingImageRect () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 112 of file SimulatedCameraControl.h.
validateParameter()
bool SimulatedCameraControl::validateParameter (Fact * pFact, QVariant & newValue) inline override virtual
Allow controller to modify or invalidate parameter change.
Implements MavlinkCameraControlInterface.
Definition at line 118 of file SimulatedCameraControl.h.
vendor()
QString SimulatedCameraControl::vendor () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 44 of file SimulatedCameraControl.h.
version()
int SimulatedCameraControl::version () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 42 of file SimulatedCameraControl.h.
videoInPhotoMode()
bool SimulatedCameraControl::videoInPhotoMode () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 59 of file SimulatedCameraControl.h.
wb()
Fact * SimulatedCameraControl::wb () inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 90 of file SimulatedCameraControl.h.
zoomLevel()
qreal SimulatedCameraControl::zoomLevel () const inline override virtual
Implements MavlinkCameraControlInterface.
Definition at line 73 of file SimulatedCameraControl.h.
The documentation for this class was generated from the following files:
src/Camera/SimulatedCameraControl.h
src/Camera/SimulatedCameraControl.cc