QGroundControl: BluetoothWorker Class Reference
BluetoothWorker Class Reference abstract
#include <BluetoothWorker.h>
Public Slots
void setupConnection ()
void connectLink ()
void disconnectLink ()
void writeData (const QByteArray &data)
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &errorString)
void dataReceived (const QByteArray &data)
void dataSent (const QByteArray &data)
void rssiUpdated (qint16 rssi)
Public Member Functions
BluetoothWorker (const BluetoothConfiguration *config, QObject *parent=nullptr)
~BluetoothWorker () override
bool isConnected () const
Static Public Member Functions
static BluetoothWorker * create (const BluetoothConfiguration *config, QObject *parent=nullptr)
Protected Slots
void _reconnectTimeout ()
void _serviceDiscoveryTimeout ()
Protected Member Functions
virtual void onSetupConnection ()=0
virtual void onConnectLink ()=0
virtual void onDisconnectLink ()=0
virtual void onWriteData (const QByteArray &data)=0
virtual void onServiceDiscoveryTimeout ()=0
virtual void onResetAfterConsecutiveFailures ()=0
Protected Attributes
const QBluetoothDeviceInfo _device
const QBluetoothUuid _serviceUuid
const QBluetoothUuid _readCharacteristicUuid
const QBluetoothUuid _writeCharacteristicUuid
QPointer< QTimer > _reconnectTimer
QPointer< QTimer > _serviceDiscoveryTimer
std::atomic< bool > _intentionalDisconnect {false}
std::atomic< bool > _connected {false}
std::atomic< int > _reconnectAttempts {0}
int _consecutiveFailures = 0
Static Protected Attributes
static constexpr int MAX_RECONNECT_ATTEMPTS = 10
static constexpr int RECONNECT_BASE_INTERVAL_MS = 5000
static constexpr int MAX_RECONNECT_INTERVAL_MS = 60000
static constexpr int SERVICE_DISCOVERY_TIMEOUT_MS = 30000
static constexpr int MAX_CONSECUTIVE_FAILURES = 3
Detailed Description
Definition at line 12 of file BluetoothWorker.h.
Constructor & Destructor Documentation
BluetoothWorker()
BluetoothWorker::BluetoothWorker (const BluetoothConfiguration * config, QObject * parent = nullptr) explicit
Definition at line 8 of file BluetoothWorker.cc.
References _reconnectTimeout(), and _serviceDiscoveryTimeout().
~BluetoothWorker()
BluetoothWorker::~BluetoothWorker () override
Definition at line 28 of file BluetoothWorker.cc.
References _intentionalDisconnect, _reconnectTimer, and _serviceDiscoveryTimer.
Member Function Documentation
_reconnectTimeout
void BluetoothWorker::_reconnectTimeout () protected slot
Definition at line 108 of file BluetoothWorker.cc.
References _consecutiveFailures, _intentionalDisconnect, _reconnectAttempts, _reconnectTimer, connectLink(), errorOccurred(), MAX_CONSECUTIVE_FAILURES, MAX_RECONNECT_ATTEMPTS, MAX_RECONNECT_INTERVAL_MS, onResetAfterConsecutiveFailures(), and RECONNECT_BASE_INTERVAL_MS.
Referenced by BluetoothWorker().
_serviceDiscoveryTimeout
void BluetoothWorker::_serviceDiscoveryTimeout () protected slot
Definition at line 136 of file BluetoothWorker.cc.
References _consecutiveFailures, errorOccurred(), onServiceDiscoveryTimeout(), and SERVICE_DISCOVERY_TIMEOUT_MS.
Referenced by BluetoothWorker().
connected
void BluetoothWorker::connected () signal
Referenced by BluetoothLink::BluetoothLink().
connectLink
void BluetoothWorker::connectLink () slot
Definition at line 65 of file BluetoothWorker.cc.
References _device, _intentionalDisconnect, isConnected(), and onConnectLink().
Referenced by _reconnectTimeout().
create()
BluetoothWorker * BluetoothWorker::create (const BluetoothConfiguration * config, QObject * parent = nullptr) static
Definition at line 52 of file BluetoothWorker.cc.
Referenced by BluetoothLink::BluetoothLink().
dataReceived
void BluetoothWorker::dataReceived (const QByteArray & data) signal
Referenced by BluetoothLink::BluetoothLink().
dataSent
void BluetoothWorker::dataSent (const QByteArray & data) signal
Referenced by BluetoothLink::BluetoothLink().
disconnected
void BluetoothWorker::disconnected () signal
Referenced by BluetoothLink::BluetoothLink().
disconnectLink
void BluetoothWorker::disconnectLink () slot
Definition at line 77 of file BluetoothWorker.cc.
References _intentionalDisconnect, _reconnectAttempts, _reconnectTimer, _serviceDiscoveryTimer, onDisconnectLink(), and RECONNECT_BASE_INTERVAL_MS.
Referenced by BluetoothBleWorker::~BluetoothBleWorker(), and BluetoothClassicWorker::~BluetoothClassicWorker().
errorOccurred
void BluetoothWorker::errorOccurred (const QString & errorString) signal
Referenced by _reconnectTimeout(), _serviceDiscoveryTimeout(), BluetoothLink::BluetoothLink(), BluetoothBleWorker::onConnectLink(), BluetoothClassicWorker::onConnectLink(), and writeData().
isConnected()
bool BluetoothWorker::isConnected () const
Definition at line 47 of file BluetoothWorker.cc.
References _connected.
Referenced by connectLink(), and writeData().
onConnectLink()
virtual void BluetoothWorker::onConnectLink () protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by connectLink().
onDisconnectLink()
virtual void BluetoothWorker::onDisconnectLink () protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by disconnectLink().
onResetAfterConsecutiveFailures()
virtual void BluetoothWorker::onResetAfterConsecutiveFailures () protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by _reconnectTimeout().
onServiceDiscoveryTimeout()
virtual void BluetoothWorker::onServiceDiscoveryTimeout () protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by _serviceDiscoveryTimeout().
onSetupConnection()
virtual void BluetoothWorker::onSetupConnection () protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by setupConnection().
onWriteData()
virtual void BluetoothWorker::onWriteData (const QByteArray & data) protected pure virtual
Implemented in BluetoothBleWorker, and BluetoothClassicWorker.
Referenced by writeData().
rssiUpdated
void BluetoothWorker::rssiUpdated (qint16 rssi) signal
Referenced by BluetoothLink::BluetoothLink().
setupConnection
void BluetoothWorker::setupConnection () slot
Definition at line 60 of file BluetoothWorker.cc.
References onSetupConnection().
Referenced by BluetoothLink::BluetoothLink().
writeData
void BluetoothWorker::writeData (const QByteArray & data) slot
Definition at line 93 of file BluetoothWorker.cc.
References errorOccurred(), isConnected(), and onWriteData().
Member Data Documentation
_connected
std::atomic<bool> BluetoothWorker::_connected {false} protected
Definition at line 59 of file BluetoothWorker.h.
Referenced by isConnected().
_consecutiveFailures
int BluetoothWorker::_consecutiveFailures = 0 protected
Definition at line 61 of file BluetoothWorker.h.
Referenced by _reconnectTimeout(), _serviceDiscoveryTimeout(), and BluetoothBleWorker::onResetAfterConsecutiveFailures().
_device
const QBluetoothDeviceInfo BluetoothWorker::_device protected
Definition at line 50 of file BluetoothWorker.h.
Referenced by connectLink(), BluetoothBleWorker::onConnectLink(), and BluetoothClassicWorker::onConnectLink().
_intentionalDisconnect
std::atomic<bool> BluetoothWorker::_intentionalDisconnect {false} protected
Definition at line 58 of file BluetoothWorker.h.
Referenced by _reconnectTimeout(), connectLink(), disconnectLink(), BluetoothBleWorker::~BluetoothBleWorker(), BluetoothClassicWorker::~BluetoothClassicWorker(), and ~BluetoothWorker().
_readCharacteristicUuid
const QBluetoothUuid BluetoothWorker::_readCharacteristicUuid protected
Definition at line 52 of file BluetoothWorker.h.
_reconnectAttempts
std::atomic<int> BluetoothWorker::_reconnectAttempts {0} protected
Definition at line 60 of file BluetoothWorker.h.
Referenced by _reconnectTimeout(), and disconnectLink().
_reconnectTimer
QPointer<QTimer> BluetoothWorker::_reconnectTimer protected
Definition at line 55 of file BluetoothWorker.h.
Referenced by _reconnectTimeout(), disconnectLink(), and ~BluetoothWorker().
_serviceDiscoveryTimer
QPointer<QTimer> BluetoothWorker::_serviceDiscoveryTimer protected
Definition at line 56 of file BluetoothWorker.h.
Referenced by disconnectLink(), and ~BluetoothWorker().
_serviceUuid
const QBluetoothUuid BluetoothWorker::_serviceUuid protected
Definition at line 51 of file BluetoothWorker.h.
_writeCharacteristicUuid
const QBluetoothUuid BluetoothWorker::_writeCharacteristicUuid protected
Definition at line 53 of file BluetoothWorker.h.
MAX_CONSECUTIVE_FAILURES
constexpr int BluetoothWorker::MAX_CONSECUTIVE_FAILURES = 3 static constexpr protected
Definition at line 67 of file BluetoothWorker.h.
Referenced by _reconnectTimeout().
MAX_RECONNECT_ATTEMPTS
constexpr int BluetoothWorker::MAX_RECONNECT_ATTEMPTS = 10 static constexpr protected
Definition at line 63 of file BluetoothWorker.h.
Referenced by _reconnectTimeout().
MAX_RECONNECT_INTERVAL_MS
constexpr int BluetoothWorker::MAX_RECONNECT_INTERVAL_MS = 60000 static constexpr protected
Definition at line 65 of file BluetoothWorker.h.
Referenced by _reconnectTimeout().
RECONNECT_BASE_INTERVAL_MS
constexpr int BluetoothWorker::RECONNECT_BASE_INTERVAL_MS = 5000 static constexpr protected
Definition at line 64 of file BluetoothWorker.h.
Referenced by _reconnectTimeout(), and disconnectLink().
SERVICE_DISCOVERY_TIMEOUT_MS
constexpr int BluetoothWorker::SERVICE_DISCOVERY_TIMEOUT_MS = 30000 static constexpr protected
Definition at line 66 of file BluetoothWorker.h.
Referenced by _serviceDiscoveryTimeout().
The documentation for this class was generated from the following files:
src/Comms/Bluetooth/BluetoothWorker.h
src/Comms/Bluetooth/BluetoothWorker.cc