QGroundControl: Actuators Class Reference
Actuators Class Reference
#include <Actuators.h>
Public Slots
void parametersChanged ()
Signals
void actuatorOutputsChanged ()
void selectedActuatorOutputChanged ()
void imageRefreshFlagChanged ()
void hasUnsetRequiredFunctionsChanged ()
void motorAssignmentActiveChanged ()
void motorAssignmentEnabledChanged ()
void motorAssignmentMessageChanged ()
void actuatorActionsChanged ()
Public Member Functions
Actuators (QObject *parent, Vehicle *vehicle)
~Actuators ()=default
void load (const QString &json_file)
void init ()
QmlObjectListModel * actuatorOutputs ()
ActuatorOutputs::ActuatorOutput * selectedActuatorOutput () const
ActuatorTesting::ActuatorTest * actuatorTest ()
bool isMultirotor () const
bool imageRefreshFlag () const
Mixer::Mixers * mixer ()
bool hasUnsetRequiredFunctions () const
bool showUi () const
bool isInitialized () const
const QString & initializationError () const
QmlObjectListModel * actuatorActions ()
bool initMotorAssignment ()
void startMotorAssignment ()
void spinCurrentMotor ()
void abortMotorAssignment ()
bool motorAssignmentActive () const
bool motorAssignmentEnabled () const
const QString & motorAssignmentMessage () const
Public Attributes
QmlObjectListModel *actuatorOutputs READ actuatorOutputs NOTIFY actuatorOutputsChanged(QmlObjectListModel *actuatorActions READ actuatorActions NOTIFY actuatorActionsChanged) 1(bool isMultirotor READ isMultirotor CONSTANT) 1(bool imageRefreshFlag READ imageRefreshFlag NOTIFY imageRefreshFlagChanged) 1(bool hasUnsetRequiredFunctions READ hasUnsetRequiredFunctions NOTIFY hasUnsetRequiredFunctionsChanged) 1(bool motorAssignmentActive READ motorAssignmentActive NOTIFY motorAssignmentActiveChanged) 1(bool motorAssignmentEnabled READ motorAssignmentEnabled NOTIFY motorAssignmentEnabledChanged) 1(QString motorAssignmentMessage READ motorAssignmentMessage NOTIFY motorAssignmentMessageChanged) 1(ActuatorTesting voi selectActuatorOutput)(int index)
Detailed Description
Definition at line 14 of file Actuators.h.
Constructor & Destructor Documentation
Actuators()
Actuators::Actuators (QObject * parent, Vehicle * vehicle)
Definition at line 15 of file Actuators.cc.
References MotorAssignment::activeChanged(), Mixer::Mixers::geometryParamChanged(), MotorAssignment::messageChanged(), motorAssignmentActiveChanged(), motorAssignmentMessageChanged(), MotorAssignment::onAbort(), Mixer::Mixers::paramChanged(), and parametersChanged().
~Actuators()
Actuators::~Actuators () default
Member Function Documentation
abortMotorAssignment()
void Actuators::abortMotorAssignment ()
Definition at line 811 of file Actuators.cc.
References MotorAssignment::abort().
actuatorActions()
QmlObjectListModel * Actuators::actuatorActions () inline
Definition at line 65 of file Actuators.h.
actuatorActionsChanged
void Actuators::actuatorActionsChanged () signal
actuatorOutputs()
QmlObjectListModel * Actuators::actuatorOutputs () inline
Definition at line 48 of file Actuators.h.
actuatorOutputsChanged
void Actuators::actuatorOutputsChanged () signal
Referenced by init().
actuatorTest()
ActuatorTesting::ActuatorTest * Actuators::actuatorTest () inline
Definition at line 51 of file Actuators.h.
hasUnsetRequiredFunctions()
bool Actuators::hasUnsetRequiredFunctions () const inline
Definition at line 59 of file Actuators.h.
Referenced by ActuatorComponent::setupComplete().
hasUnsetRequiredFunctionsChanged
void Actuators::hasUnsetRequiredFunctionsChanged () signal
Referenced by ActuatorComponent::ActuatorComponent(), and parametersChanged().
imageRefreshFlag()
bool Actuators::imageRefreshFlag () const inline
Definition at line 55 of file Actuators.h.
imageRefreshFlagChanged
void Actuators::imageRefreshFlagChanged () signal
init()
void Actuators::init ()
Initialize the loaded metadata. Call this after all vehicle parameters are loaded.
Definition at line 135 of file Actuators.cc.
References actuatorOutputsChanged(), QmlObjectListModel::count(), ActuatorOutputs::ActuatorOutput::enableParam(), QmlObjectListModel::get(), ActuatorOutputs::ActuatorOutput::hasExistingOutputFunctionParams(), Vehicle::parameterManager(), parametersChanged(), ParameterManager::parametersReady(), and QmlObjectListModel::removeAt().
Referenced by PX4AutoPilotPlugin::vehicleComponents().
initializationError()
const QString & Actuators::initializationError () const inline
Definition at line 63 of file Actuators.h.
Referenced by PX4AutoPilotPlugin::vehicleComponents().
initMotorAssignment()
bool Actuators::initMotorAssignment ()
Definition at line 778 of file Actuators.cc.
References Mixer::Mixers::actuatorTypes(), MotorAssignment::initAssignment(), GeometryImage::VehicleGeometryImageProvider::instance(), and GeometryImage::VehicleGeometryImageProvider::numMotors().
isInitialized()
bool Actuators::isInitialized () const inline
Definition at line 62 of file Actuators.h.
Referenced by PX4AutoPilotPlugin::vehicleComponents().
isMultirotor()
bool Actuators::isMultirotor () const
Definition at line 105 of file Actuators.cc.
References Mixer::Mixers::configuredType().
load()
void Actuators::load (const QString & json_file)
load JSON metadata file
Definition at line 110 of file Actuators.cc.
Referenced by Vehicle::setActuatorsMetadata().
mixer()
Mixer::Mixers * Actuators::mixer () inline
Definition at line 57 of file Actuators.h.
motorAssignmentActive()
bool Actuators::motorAssignmentActive () const inline
Definition at line 71 of file Actuators.h.
References MotorAssignment::active().
motorAssignmentActiveChanged
void Actuators::motorAssignmentActiveChanged () signal
Referenced by Actuators().
motorAssignmentEnabled()
bool Actuators::motorAssignmentEnabled () const inline
Definition at line 72 of file Actuators.h.
motorAssignmentEnabledChanged
void Actuators::motorAssignmentEnabledChanged () signal
motorAssignmentMessage()
const QString & Actuators::motorAssignmentMessage () const inline
Definition at line 73 of file Actuators.h.
References MotorAssignment::message().
motorAssignmentMessageChanged
void Actuators::motorAssignmentMessageChanged () signal
Referenced by Actuators().
parametersChanged
void Actuators::parametersChanged () slot
Definition at line 165 of file Actuators.cc.
References Mixer::Mixers::actuatorTypes(), ActuatorOutputs::ActuatorOutput::addNote(), ActuatorOutputs::ActuatorOutputSubgroup::channelConfigs(), ActuatorOutputs::ActuatorOutput::clearNotes(), QmlObjectListModel::count(), Mixer::ActuatorType::Values::defaultVal, Mixer::ActuatorType::functionMax, Mixer::ActuatorType::functionMin, Mixer::Mixers::functions(), QmlObjectListModel::get(), ActuatorOutputs::ActuatorOutput::getAllChannelFunctions(), Mixer::Mixers::getFunctions(), Mixer::Mixers::getSpecificLabelForFunction(), hasUnsetRequiredFunctionsChanged(), Mixer::ActuatorType::Values::max, Mixer::ActuatorType::Values::min, ActuatorGeometry::Motor, ActuatorOutputs::ChannelConfig::reevaluate(), ActuatorOutputs::ActuatorOutput::subgroups(), ActuatorGeometry::typeFromStr(), Mixer::Mixers::update(), ActuatorTesting::ActuatorTest::updateFunctions(), and Mixer::ActuatorType::values.
Referenced by Actuators(), and init().
selectedActuatorOutput()
ActuatorOutput * Actuators::selectedActuatorOutput () const
Definition at line 60 of file Actuators.cc.
References QmlObjectListModel::count(), and QmlObjectListModel::value().
selectedActuatorOutputChanged
void Actuators::selectedActuatorOutputChanged () signal
showUi()
bool Actuators::showUi () const
Definition at line 773 of file Actuators.cc.
References Condition::evaluate().
Referenced by PX4AutoPilotPlugin::vehicleComponents().
spinCurrentMotor()
void Actuators::spinCurrentMotor () inline
Definition at line 69 of file Actuators.h.
References MotorAssignment::spinCurrentMotor().
startMotorAssignment()
void Actuators::startMotorAssignment ()
Definition at line 806 of file Actuators.cc.
References MotorAssignment::start().
Member Data Documentation
selectActuatorOutput
void Actuators::selectActuatorOutput
Definition at line 36 of file Actuators.h.
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Actuators.h
src/Vehicle/Actuators/Actuators.cc