QGroundControl: APMMavlinkStreamRateSettings Class Reference
APMMavlinkStreamRateSettings Class Reference
#include <APMMavlinkStreamRateSettings.h>
Public Member Functions
APMMavlinkStreamRateSettings (QObject *parent=nullptr)
Fact *streamRateRawSensors READ streamRateRawSensors CONSTANT Fact * streamRateRawSensors ()
Fact *streamRateExtendedStatus READ streamRateExtendedStatus CONSTANT Fact * streamRateExtendedStatus ()
Fact *streamRateRCChannels READ streamRateRCChannels CONSTANT Fact * streamRateRCChannels ()
Fact *streamRatePosition READ streamRatePosition CONSTANT Fact * streamRatePosition ()
Fact *streamRateExtra1 READ streamRateExtra1 CONSTANT Fact * streamRateExtra1 ()
Fact *streamRateExtra2 READ streamRateExtra2 CONSTANT Fact * streamRateExtra2 ()
Fact *streamRateExtra3 READ streamRateExtra3 CONSTANT Fact * streamRateExtra3 ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "APMMavlinkStreamRate"
static const char * settingsGroup = "APMMavlinkStreamRate"
static const char * streamRateRawSensorsName = "streamRateRawSensors"
static const char * streamRateExtendedStatusName = "streamRateExtendedStatus"
static const char * streamRateRCChannelsName = "streamRateRCChannels"
static const char * streamRatePositionName = "streamRatePosition"
static const char * streamRateExtra1Name = "streamRateExtra1"
static const char * streamRateExtra2Name = "streamRateExtra2"
static const char * streamRateExtra3Name = "streamRateExtra3"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 8 of file APMMavlinkStreamRateSettings.h.
Constructor & Destructor Documentation
APMMavlinkStreamRateSettings()
APMMavlinkStreamRateSettings::APMMavlinkStreamRateSettings (QObject * parent = nullptr)
Definition at line 5 of file APMMavlinkStreamRateSettings.cc.
References Fact::rawValueChanged().
Member Function Documentation
streamRateExtendedStatus()
Fact * APMMavlinkStreamRateSettings::streamRateExtendedStatus ()
Definition at line 17 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRateExtra1()
Fact * APMMavlinkStreamRateSettings::streamRateExtra1 ()
Definition at line 20 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRateExtra2()
Fact * APMMavlinkStreamRateSettings::streamRateExtra2 ()
Definition at line 21 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRateExtra3()
Fact * APMMavlinkStreamRateSettings::streamRateExtra3 ()
Definition at line 22 of file APMMavlinkStreamRateSettings.cc.
References Vehicle::requestDataStream().
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRatePosition()
Fact * APMMavlinkStreamRateSettings::streamRatePosition ()
Definition at line 19 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRateRawSensors()
Fact * APMMavlinkStreamRateSettings::streamRateRawSensors ()
Definition at line 16 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
streamRateRCChannels()
Fact * APMMavlinkStreamRateSettings::streamRateRCChannels ()
Definition at line 18 of file APMMavlinkStreamRateSettings.cc.
Referenced by APMFirmwarePlugin::initializeStreamRates().
Member Data Documentation
name
const char * APMMavlinkStreamRateSettings::name = "APMMavlinkStreamRate" static
Definition at line 16 of file APMMavlinkStreamRateSettings.h.
settingsGroup
const char * APMMavlinkStreamRateSettings::settingsGroup = "APMMavlinkStreamRate" static
Definition at line 16 of file APMMavlinkStreamRateSettings.h.
streamRateExtendedStatusName
const char * APMMavlinkStreamRateSettings::streamRateExtendedStatusName = "streamRateExtendedStatus" static
Definition at line 19 of file APMMavlinkStreamRateSettings.h.
streamRateExtra1Name
const char * APMMavlinkStreamRateSettings::streamRateExtra1Name = "streamRateExtra1" static
Definition at line 22 of file APMMavlinkStreamRateSettings.h.
streamRateExtra2Name
const char * APMMavlinkStreamRateSettings::streamRateExtra2Name = "streamRateExtra2" static
Definition at line 23 of file APMMavlinkStreamRateSettings.h.
streamRateExtra3Name
const char * APMMavlinkStreamRateSettings::streamRateExtra3Name = "streamRateExtra3" static
Definition at line 24 of file APMMavlinkStreamRateSettings.h.
streamRatePositionName
const char * APMMavlinkStreamRateSettings::streamRatePositionName = "streamRatePosition" static
Definition at line 21 of file APMMavlinkStreamRateSettings.h.
streamRateRawSensorsName
const char * APMMavlinkStreamRateSettings::streamRateRawSensorsName = "streamRateRawSensors" static
Definition at line 18 of file APMMavlinkStreamRateSettings.h.
streamRateRCChannelsName
const char * APMMavlinkStreamRateSettings::streamRateRCChannelsName = "streamRateRCChannels" static
Definition at line 20 of file APMMavlinkStreamRateSettings.h.
The documentation for this class was generated from the following files:
src/Settings/APMMavlinkStreamRateSettings.h
src/Settings/APMMavlinkStreamRateSettings.cc