QGroundControl: QGeoTiledMappingManagerEngineQGC Class Reference
QGeoTiledMappingManagerEngineQGC Class Reference
#include <QGeoTiledMappingManagerEngineQGC.h>
Public Member Functions
QGeoTiledMappingManagerEngineQGC (const QVariantMap &parameters, QGeoServiceProvider::Error *error, QString *errorString, QNetworkAccessManager *networkManager=nullptr, QObject *parent=nullptr)
~QGeoTiledMappingManagerEngineQGC ()
QGeoMap * createMap () final
QNetworkAccessManager * networkManager () const
Detailed Description
Definition at line 11 of file QGeoTiledMappingManagerEngineQGC.h.
Constructor & Destructor Documentation
QGeoTiledMappingManagerEngineQGC()
QGeoTiledMappingManagerEngineQGC::QGeoTiledMappingManagerEngineQGC (const QVariantMap & parameters, QGeoServiceProvider::Error * error, QString * errorString, QNetworkAccessManager * networkManager = nullptr, QObject * parent = nullptr)
Definition at line 28 of file QGeoTiledMappingManagerEngineQGC.cpp.
References error, errorString, QGeoFileTileCacheQGC::getDatabaseFilePath(), UrlFactory::getProviders(), getQGCMapEngine(), QGCMapEngine::init(), QGCNetworkHelper::isInternetAvailable(), QGCApplication::languageChanged(), QGC_MAX_MAP_ZOOM, and qgcApp.
~QGeoTiledMappingManagerEngineQGC()
QGeoTiledMappingManagerEngineQGC::~QGeoTiledMappingManagerEngineQGC ()
Definition at line 100 of file QGeoTiledMappingManagerEngineQGC.cpp.
Member Function Documentation
createMap()
QGeoMap * QGeoTiledMappingManagerEngineQGC::createMap () final
Definition at line 105 of file QGeoTiledMappingManagerEngineQGC.cpp.
networkManager()
QNetworkAccessManager * QGeoTiledMappingManagerEngineQGC::networkManager () const inline
Definition at line 20 of file QGeoTiledMappingManagerEngineQGC.h.
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.h
src/QtLocationPlugin/QGeoTiledMappingManagerEngineQGC.cpp