QGroundControl: ParameterTableModel Class Reference
ParameterTableModel Class Reference
#include <ParameterEditorController.h>
Public Types
enum { FactRole = Qt::UserRole + 1 }
enum { FavColumn = 0 , NameColumn , ValueColumn , DescriptionColumn }
typedef QVector< QVariant > ColumnData
Signals
void rowCountChanged (int count)
Public Member Functions
ParameterTableModel (QObject *parent=nullptr)
~ParameterTableModel () override
int rowCount READ rowCount NOTIFY rowCountChanged void append (Fact *fact)
void insert (int row, Fact *fact)
void clear ()
void beginReset ()
Supports nesting - only outermost call has effect.
void endReset ()
Supports nesting - only outermost call has effect.
Fact * factAt (int row) const
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QHash< int, QByteArray > roleNames (void) const override
Detailed Description
Definition at line 16 of file ParameterEditorController.h.
Member Typedef Documentation
ColumnData
typedef QVector<QVariant> ParameterTableModel::ColumnData
Definition at line 24 of file ParameterEditorController.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
FactRole
Definition at line 26 of file ParameterEditorController.h.
anonymous enum
anonymous enum
Enumerator
FavColumn
NameColumn
ValueColumn
DescriptionColumn
Definition at line 30 of file ParameterEditorController.h.
Constructor & Destructor Documentation
ParameterTableModel()
ParameterTableModel::ParameterTableModel (QObject * parent = nullptr) explicit
Definition at line 11 of file ParameterEditorController.cc.
~ParameterTableModel()
ParameterTableModel::~ParameterTableModel () override
Definition at line 17 of file ParameterEditorController.cc.
Member Function Documentation
append()
void ParameterTableModel::append (Fact * fact)
Definition at line 85 of file ParameterEditorController.cc.
References insert(), and rowCount().
beginReset()
void ParameterTableModel::beginReset ()
Supports nesting - only outermost call has effect.
Definition at line 113 of file ParameterEditorController.cc.
Referenced by clear().
clear()
void ParameterTableModel::clear ()
Definition at line 78 of file ParameterEditorController.cc.
References beginReset(), and endReset().
columnCount()
int ParameterTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 27 of file ParameterEditorController.cc.
data()
QVariant ParameterTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 32 of file ParameterEditorController.cc.
References FactRole, and ValueColumn.
endReset()
void ParameterTableModel::endReset ()
Supports nesting - only outermost call has effect.
Definition at line 122 of file ParameterEditorController.cc.
References rowCount(), and rowCountChanged().
Referenced by clear().
factAt()
Fact * ParameterTableModel::factAt (int row) const
Definition at line 135 of file ParameterEditorController.cc.
References ValueColumn.
headerData()
QVariant ParameterTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 55 of file ParameterEditorController.cc.
References DescriptionColumn, FavColumn, NameColumn, and ValueColumn.
insert()
void ParameterTableModel::insert (int row, Fact * fact)
Definition at line 90 of file ParameterEditorController.cc.
References DescriptionColumn, FavColumn, NameColumn, rowCount(), rowCountChanged(), and ValueColumn.
Referenced by append().
roleNames()
QHash< int, QByteArray > ParameterTableModel::roleNames (void) const override
Definition at line 70 of file ParameterEditorController.cc.
References FactRole.
rowCount()
int ParameterTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 22 of file ParameterEditorController.cc.
Referenced by append(), endReset(), and insert().
rowCountChanged
void ParameterTableModel::rowCountChanged (int count) signal
Referenced by endReset(), and insert().
The documentation for this class was generated from the following files:
src/QmlControls/ParameterEditorController.h
src/QmlControls/ParameterEditorController.cc