QGroundControl: PlanViewSettings Class Reference
PlanViewSettings Class Reference
#include <PlanViewSettings.h>
Public Member Functions
PlanViewSettings (QObject *parent=nullptr)
Fact *displayPresetsTabFirst READ displayPresetsTabFirst CONSTANT Fact * displayPresetsTabFirst ()
Fact *showMissionItemStatus READ showMissionItemStatus CONSTANT Fact * showMissionItemStatus ()
Fact *useConditionGate READ useConditionGate CONSTANT Fact * useConditionGate ()
Fact *takeoffItemNotRequired READ takeoffItemNotRequired CONSTANT Fact * takeoffItemNotRequired ()
Fact *allowMultipleLandingPatterns READ allowMultipleLandingPatterns CONSTANT Fact * allowMultipleLandingPatterns ()
Fact *showGimbalOnlyWhenSet READ showGimbalOnlyWhenSet CONSTANT Fact * showGimbalOnlyWhenSet ()
Fact *vtolTransitionDistance READ vtolTransitionDistance CONSTANT Fact * vtolTransitionDistance ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "PlanView"
static const char * settingsGroup = "PlanView"
static const char * displayPresetsTabFirstName = "displayPresetsTabFirst"
static const char * showMissionItemStatusName = "showMissionItemStatus"
static const char * useConditionGateName = "useConditionGate"
static const char * takeoffItemNotRequiredName = "takeoffItemNotRequired"
static const char * allowMultipleLandingPatternsName = "allowMultipleLandingPatterns"
static const char * showGimbalOnlyWhenSetName = "showGimbalOnlyWhenSet"
static const char * vtolTransitionDistanceName = "vtolTransitionDistance"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file PlanViewSettings.h.
Constructor & Destructor Documentation
PlanViewSettings()
PlanViewSettings::PlanViewSettings (QObject * parent = nullptr)
Definition at line 3 of file PlanViewSettings.cc.
Member Function Documentation
allowMultipleLandingPatterns()
Fact * PlanViewSettings::allowMultipleLandingPatterns ()
Definition at line 11 of file PlanViewSettings.cc.
Referenced by MissionController::multipleLandPatternsAllowed().
displayPresetsTabFirst()
Fact * PlanViewSettings::displayPresetsTabFirst ()
Definition at line 7 of file PlanViewSettings.cc.
showGimbalOnlyWhenSet()
Fact * PlanViewSettings::showGimbalOnlyWhenSet ()
Definition at line 12 of file PlanViewSettings.cc.
showMissionItemStatus()
Fact * PlanViewSettings::showMissionItemStatus ()
Definition at line 8 of file PlanViewSettings.cc.
takeoffItemNotRequired()
Fact * PlanViewSettings::takeoffItemNotRequired ()
Definition at line 10 of file PlanViewSettings.cc.
Referenced by MissionController::setCurrentPlanViewSeqNum().
useConditionGate()
Fact * PlanViewSettings::useConditionGate ()
Definition at line 9 of file PlanViewSettings.cc.
vtolTransitionDistance()
Fact * PlanViewSettings::vtolTransitionDistance ()
Definition at line 13 of file PlanViewSettings.cc.
Referenced by VTOLLandingComplexItem::VTOLLandingComplexItem().
Member Data Documentation
allowMultipleLandingPatternsName
const char * PlanViewSettings::allowMultipleLandingPatternsName = "allowMultipleLandingPatterns" static
Definition at line 22 of file PlanViewSettings.h.
displayPresetsTabFirstName
const char * PlanViewSettings::displayPresetsTabFirstName = "displayPresetsTabFirst" static
Definition at line 18 of file PlanViewSettings.h.
name
const char * PlanViewSettings::name = "PlanView" static
Definition at line 14 of file PlanViewSettings.h.
settingsGroup
const char * PlanViewSettings::settingsGroup = "PlanView" static
Definition at line 14 of file PlanViewSettings.h.
showGimbalOnlyWhenSetName
const char * PlanViewSettings::showGimbalOnlyWhenSetName = "showGimbalOnlyWhenSet" static
Definition at line 23 of file PlanViewSettings.h.
showMissionItemStatusName
const char * PlanViewSettings::showMissionItemStatusName = "showMissionItemStatus" static
Definition at line 19 of file PlanViewSettings.h.
takeoffItemNotRequiredName
const char * PlanViewSettings::takeoffItemNotRequiredName = "takeoffItemNotRequired" static
Definition at line 21 of file PlanViewSettings.h.
useConditionGateName
const char * PlanViewSettings::useConditionGateName = "useConditionGate" static
Definition at line 20 of file PlanViewSettings.h.
vtolTransitionDistanceName
const char * PlanViewSettings::vtolTransitionDistanceName = "vtolTransitionDistance" static
Definition at line 24 of file PlanViewSettings.h.
The documentation for this class was generated from the following files:
src/Settings/PlanViewSettings.h
src/Settings/PlanViewSettings.cc