QGroundControl: MissionCommandList Class Reference
MissionCommandList Class Reference
Maintains a list of MissionCommandUIInfo objects loaded from a json file.
#include <MissionCommandList.h>
Public Member Functions
MissionCommandList (const QString &jsonFilename, bool baseCommandList, QObject *parent=nullptr)
QStringList & categories (void)
Returns list of categories in this list.
MissionCommandUIInfo * getUIInfo (MAV_CMD command) const
Returns the ui info for specified command, NULL if command not found.
const QList< MAV_CMD > & commandIds (void) const
Static Public Attributes
static constexpr const char * qgcFileType = "MavCmdInfo"
Detailed Description
Maintains a list of MissionCommandUIInfo objects loaded from a json file.
Definition at line 12 of file MissionCommandList.h.
Constructor & Destructor Documentation
MissionCommandList()
MissionCommandList::MissionCommandList (const QString & jsonFilename, bool baseCommandList, QObject * parent = nullptr)
Parameters
baseCommandList true: bottomost level of mission command hierarchy (partial spec allowed), false: override level of hierarchy
Definition at line 8 of file MissionCommandList.cc.
Member Function Documentation
categories()
QStringList & MissionCommandList::categories (void) inline
Returns list of categories in this list.
Definition at line 21 of file MissionCommandList.h.
commandIds()
const QList< MAV_CMD > & MissionCommandList::commandIds (void) const inline
Definition at line 26 of file MissionCommandList.h.
getUIInfo()
MissionCommandUIInfo * MissionCommandList::getUIInfo (MAV_CMD command) const
Returns the ui info for specified command, NULL if command not found.
Definition at line 68 of file MissionCommandList.cc.
Referenced by MissionCommandTree::friendlyName(), MissionCommandTree::isLandCommand(), MissionCommandTree::isTakeoffCommand(), and MissionCommandTree::rawName().
Member Data Documentation
qgcFileType
constexpr const char* MissionCommandList::qgcFileType = "MavCmdInfo" static constexpr
Definition at line 28 of file MissionCommandList.h.
Referenced by JsonHelper::_addDefaultLocKeys().
The documentation for this class was generated from the following files:
src/MissionManager/MissionCommandList.h
src/MissionManager/MissionCommandList.cc