QGroundControl: TransectStyleComplexItem Class Reference
TransectStyleComplexItem Class Reference abstract
#include <TransectStyleComplexItem.h>
Classes
struct CoordInfo_t
Signals
void cameraShotsChanged (void)
void timeBetweenShotsChanged (void)
void visualTransectPointsChanged (void)
void coveredAreaChanged (void)
void _updateFlightPathSegmentsSignal (void)
Signals inherited from ComplexMissionItem
void patternNameChanged (void)
void complexDistanceChanged (void)
void boundingCubeChanged (void)
void greatestDistanceToChanged (void)
void presetNamesChanged (void)
void isIncompleteChanged (void)
void minAMSLAltitudeChanged (void)
void maxAMSLAltitudeChanged (void)
void terrainCollisionChanged (bool terrainCollision)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
TransectStyleComplexItem (PlanMasterController *masterController, bool flyView, QString settignsGroup)
QGCMapPolygon *surveyAreaPolygon READ surveyAreaPolygon CONSTANT (CameraCalc *cameraCalc READ cameraCalc CONSTANT) 1(Fact *turnAroundDistance READ turnAroundDistance CONSTANT) 1(Fact *cameraTriggerInTurnAround READ cameraTriggerInTurnAround CONSTANT) 1(Fact *hoverAndCapture READ hoverAndCapture CONSTANT) 1(Fact *refly90Degrees READ refly90Degrees CONSTANT) 1(int cameraShots READ cameraShots NOTIFY cameraShotsChanged) 1(double timeBetweenShots READ timeBetweenShots NOTIFY timeBetweenShotsChanged) 1(double coveredArea READ coveredArea NOTIFY coveredAreaChanged) 1(bool hoverAndCaptureAllowed READ hoverAndCaptureAllowed CONSTANT) 1(QVariantList visualTransectPoints READ visualTransectPoints NOTIFY visualTransectPointsChanged) 1(Fact *terrainAdjustTolerance READ terrainAdjustTolerance CONSTANT) 1(Fact *terrainAdjustMaxDescentRate READ terrainAdjustMaxDescentRate CONSTANT) 1(Fact *terrainAdjustMaxClimbRate READ terrainAdjustMaxClimbRate CONSTANT) QGCMapPolygon *surveyAreaPolygon(void)
CameraCalc * cameraCalc (void)
QVariantList visualTransectPoints (void)
Fact * turnAroundDistance (void)
Fact * cameraTriggerInTurnAround (void)
Fact * hoverAndCapture (void)
Fact * refly90Degrees (void)
Fact * terrainAdjustTolerance (void)
Fact * terrainAdjustMaxDescentRate (void)
Fact * terrainAdjustMaxClimbRate (void)
const Fact * hoverAndCapture (void) const
int cameraShots (void) const
double coveredArea (void) const
bool hoverAndCaptureAllowed (void) const
virtual double timeBetweenShots (void)
double triggerDistance (void) const
bool hoverAndCaptureEnabled (void) const
bool triggerCamera (void) const
int _transectCount (void) const
int lastSequenceNumber (void) const final
QString mapVisualQML (void) const override=0
bool load (const QJsonObject &complexObject, int sequenceNumber, QString &errorString) override=0
void addKMLVisuals (KMLPlanDomDocument &domDocument) final
double complexDistance (void) const final
double greatestDistanceTo (const QGeoCoordinate &other) const final
void save (QJsonArray &planItems) override=0
bool specifiesCoordinate (void) const override=0
void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent) final
void applyNewAltitude (double newAltitude) final
Adjust the altitude of the item if appropriate to the new altitude.
bool dirty (void) const final
bool isSimpleItem (void) const final
bool isStandaloneCoordinate (void) const final
bool specifiesAltitudeOnly (void) const final
QGeoCoordinate coordinate (void) const final
QGeoCoordinate entryCoordinate (void) const final
QGeoCoordinate exitCoordinate (void) const final
int sequenceNumber (void) const final
double specifiedFlightSpeed (void) final
double specifiedGimbalYaw (void) final
double specifiedGimbalPitch (void) final
void setMissionFlightStatus (MissionController::MissionFlightStatus_t &missionFlightStatus) final
ReadyForSaveState readyForSaveState (void) const override
QString commandDescription (void) const override
QString commandName (void) const override
QString abbreviation (void) const override
bool exitCoordinateSameAsEntry (void) const final
void setDirty (bool dirty) final
void setCoordinate (const QGeoCoordinate &coordinate) override
void setSequenceNumber (int sequenceNumber) final
double editableAlt (void) const final
double amslEntryAlt (void) const final
double amslExitAlt (void) const final
double minAMSLAltitude (void) const final
double maxAMSLAltitude (void) const final
Public Member Functions inherited from ComplexMissionItem
ComplexMissionItem (PlanMasterController *masterController, bool flyView)
const ComplexMissionItem & operator= (const ComplexMissionItem &other)
QString patternName READ patternName NOTIFY patternNameChanged (double complexDistance READ complexDistance NOTIFY complexDistanceChanged) 1(bool presetsSupported READ presetsSupported CONSTANT) 1(QStringList presetNames READ presetNames NOTIFY presetNamesChanged) 1(bool isIncomplete READ isIncomplete NOTIFY isIncompleteChanged) 1(double minAMSLAltitude READ minAMSLAltitude NOTIFY minAMSLAltitudeChanged) 1(double maxAMSLAltitude READ maxAMSLAltitude NOTIFY maxAMSLAltitudeChanged) 1(bool isSingleItem READ isSingleItem CONSTANT) 1(QmlObjectListModel *flightPathSegments READ flightPathSegments CONSTANT) 1(bool terrainCollision READ terrainCollision NOTIFY terrainCollisionChanged) QmlObjectListModel *flightPathSegments(void)
< Minimum altitude of all coordinates in item
virtual QString patternName (void) const =0
virtual bool terrainCollision (void) const
virtual bool isSingleItem (void) const
virtual void loadPreset (const QString &name)
virtual void savePreset (const QString &name)
void deletePreset (const QString &name)
virtual QStringList presetNames (void)
virtual QString presetsSettingsGroup (void)
bool presetsSupported (void)
bool isIncomplete (void) const
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool isTakeoffItem (void) const
virtual bool isLandCommand (void) const
virtual bool isSurveyItem (void) const
virtual double specifiedVehicleYaw (void)
virtual QGCGeoBoundingCube * boundingCube (void)
virtual double additionalTimeDelay (void) const =0
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Static Public Attributes
static constexpr const char * turnAroundDistanceName = "TurnAroundDistance"
static constexpr const char * turnAroundDistanceMultiRotorName = "TurnAroundDistanceMultiRotor"
static constexpr const char * cameraTriggerInTurnAroundName = "CameraTriggerInTurnAround"
static constexpr const char * hoverAndCaptureName = "HoverAndCapture"
static constexpr const char * refly90DegreesName = "Refly90Degrees"
static constexpr const char * terrainAdjustToleranceName = "TerrainAdjustTolerance"
static constexpr const char * terrainAdjustMaxClimbRateName = "TerrainAdjustMaxClimbRate"
static constexpr const char * terrainAdjustMaxDescentRateName = "TerrainAdjustMaxDescentRate"
Static Public Attributes inherited from ComplexMissionItem
static constexpr const char * jsonComplexItemTypeKey = "complexItemType"
This mission item attribute specifies the type of the complex item.
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Types
enum CoordType {
CoordTypeInterior , CoordTypeInteriorHoverTrigger , CoordTypeInteriorTerrainAdded , CoordTypeSurveyEntry ,
CoordTypeSurveyExit , CoordTypeTurnaround
}
Protected Slots
void _setDirty (void)
void _setIfDirty (bool dirty)
void _updateCoordinateAltitudes (void)
void _polyPathTerrainData (bool success, const QList< TerrainPathQuery::PathHeightInfo_t > &rgPathHeightInfo)
void _missionItemCoordTerrainData (bool success, QList< double > heights)
void _rebuildTransects (void)
Protected Slots inherited from ComplexMissionItem
virtual void _segmentTerrainCollisionChanged (bool terrainCollision)
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions
virtual void _rebuildTransectsPhase1 (void)=0
Rebuilds the _transects array.
virtual void _recalcCameraShots (void)=0
void _save (QJsonObject &saveObject)
bool _load (const QJsonObject &complexObject, bool forPresets, QString &errorString)
void _setExitCoordinate (const QGeoCoordinate &coordinate)
void _setCameraShots (int cameraShots)
double _triggerDistance (void) const
bool _hasTurnaround (void) const
double _turnAroundDistance (void) const
void _appendWaypoint (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum, MAV_FRAME mavFrame, float holdTime, const QGeoCoordinate &coordinate)
void _appendSinglePhotoCapture (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum)
void _appendConditionGate (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum, MAV_FRAME mavFrame, const QGeoCoordinate &coordinate)
void _appendCameraTriggerDistance (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum, float triggerDistance)
void _appendCameraTriggerDistanceUpdatePoint (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum, MAV_FRAME mavFrame, const QGeoCoordinate &coordinate, bool useConditionGate, float triggerDistance)
void _buildAndAppendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent)
void _appendLoadedMissionItems (QList< MissionItem * > &items, QObject *missionItemParent)
void _recalcComplexDistance (void)
Protected Member Functions inherited from ComplexMissionItem
void _savePresetJson (const QString &name, QJsonObject &presetObject)
QJsonObject _loadPresetJson (const QString &name)
void _appendFlightPathSegment (FlightPathSegment::SegmentType segmentType, const QGeoCoordinate &coord1, double coord1AMSLAlt, const QGeoCoordinate &coord2, double coord2AMSLAlt)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes
int _sequenceNumber = 0
QGeoCoordinate _entryCoordinate
QGeoCoordinate _exitCoordinate
QGCMapPolygon _surveyAreaPolygon
QVariantList _visualTransectPoints
Used to draw the flight path visuals on the screen.
QList< QList< CoordInfo_t > > _transects
QList< TerrainPathQuery::PathHeightInfo_t > _rgPathHeightInfo
Path height for each segment includes turn segments.
QList< QGeoCoordinate > _rgFlyThroughMissionItemCoords
QList< double > _rgFlyThroughMissionItemCoordsTerrainHeights
QList< CoordInfo_t > _rgFlightPathCoordInfo
Fully calculated flight path (including terrain if needed)
bool _ignoreRecalc = false
double _complexDistance = qQNaN()
int _cameraShots = 0
double _timeBetweenShots = 0
double _vehicleSpeed = 5
CameraCalc _cameraCalc
double _minAMSLAltitude = qQNaN()
double _maxAMSLAltitude = qQNaN()
QObject * _loadedMissionItemsParent = nullptr
Parent for all items in _loadedMissionItems for simpler delete.
QList< MissionItem * > _loadedMissionItems
Mission items loaded from plan file.
QMap< QString, FactMetaData * > _metaDataMap
SettingsFact _turnAroundDistanceFact
SettingsFact _cameraTriggerInTurnAroundFact
SettingsFact _hoverAndCaptureFact
SettingsFact _refly90DegreesFact
SettingsFact _terrainAdjustToleranceFact
SettingsFact _terrainAdjustMaxClimbRateFact
SettingsFact _terrainAdjustMaxDescentRateFact
Protected Attributes inherited from ComplexMissionItem
bool _isIncomplete = true
int _cTerrainCollisionSegments = 0
QmlObjectListModel _flightPathSegments
QMap< QString, FactMetaData * > _metaDataMap
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLink::VehicleClass_t _previousVTOLMode = QGCMAVLink::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Static Protected Attributes
static constexpr const char * _jsonTransectStyleComplexItemKey = "TransectStyleComplexItem"
static constexpr const char * _jsonCameraCalcKey = "CameraCalc"
static constexpr const char * _jsonVisualTransectPointsKey = "VisualTransectPoints"
static constexpr const char * _jsonItemsKey = "Items"
static constexpr const char * _jsonTerrainFlightSpeed = "TerrainFlightSpeed"
static constexpr const char * _jsonCameraShotsKey = "CameraShots"
static constexpr int _terrainQueryTimeoutMsecs = 1000
static constexpr int _hoverAndCaptureDelaySeconds = 4
static constexpr double _minimumTransectSpacingMeters = 0.3
static constexpr double _forceLargeTransectSpacingMeters = 100000
Static Protected Attributes inherited from ComplexMissionItem
static constexpr const char * _presetSettingsKey = "_presets"
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Detailed Description
Definition at line 16 of file TransectStyleComplexItem.h.
Member Enumeration Documentation
CoordType
enum TransectStyleComplexItem::CoordType protected
Enumerator
CoordTypeInterior
Interior waypoint for flight path only (example: interior corridor point)
CoordTypeInteriorHoverTrigger
Interior waypoint for hover and capture trigger.
CoordTypeInteriorTerrainAdded
Interior waypoint added for terrain.
CoordTypeSurveyEntry
Waypoint at entry edge of survey polygon.
CoordTypeSurveyExit
Waypoint at exit edge of survey polygon.
CoordTypeTurnaround
Turnaround extension waypoint.
Definition at line 155 of file TransectStyleComplexItem.h.
Constructor & Destructor Documentation
TransectStyleComplexItem()
TransectStyleComplexItem::TransectStyleComplexItem (PlanMasterController * masterController, bool flyView, QString settignsGroup)
Definition at line 19 of file TransectStyleComplexItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::_amslExitAltChanged(), _rebuildTransects(), _setDirty(), _setIfDirty(), _updateFlightPathSegmentsSignal(), ComplexMissionItem::complexDistanceChanged(), VisualMissionItem::coordinateChanged(), coveredAreaChanged(), CameraSpec::dirtyChanged(), QGCMapPolygon::dirtyChanged(), CameraCalc::distanceModeChanged(), VisualMissionItem::entryCoordinateChanged(), ComplexMissionItem::greatestDistanceToChanged(), QGCMapPolygon::isValidChanged(), ComplexMissionItem::maxAMSLAltitudeChanged(), ComplexMissionItem::minAMSLAltitudeChanged(), QGCMapPolygon::pathChanged(), qgcApp, Fact::rawValueChanged(), VisualMissionItem::readyForSaveStateChanged(), MissionController::recalcTerrainProfile(), Fact::valueChanged(), visualTransectPointsChanged(), and VisualMissionItem::wizardModeChanged().
Member Function Documentation
_appendCameraTriggerDistance()
void TransectStyleComplexItem::_appendCameraTriggerDistance (QList< MissionItem * > & items, QObject * missionItemParent, int & seqNum, float triggerDistance) protected
Definition at line 1187 of file TransectStyleComplexItem.cc.
References triggerDistance().
Referenced by _appendCameraTriggerDistanceUpdatePoint().
_appendCameraTriggerDistanceUpdatePoint()
void TransectStyleComplexItem::_appendCameraTriggerDistanceUpdatePoint (QList< MissionItem * > & items, QObject * missionItemParent, int & seqNum, MAV_FRAME mavFrame, const QGeoCoordinate & coordinate, bool useConditionGate, float triggerDistance) protected
Definition at line 1202 of file TransectStyleComplexItem.cc.
References _appendCameraTriggerDistance(), _appendConditionGate(), _appendWaypoint(), coordinate(), and triggerDistance().
Referenced by _buildAndAppendMissionItems().
_appendConditionGate()
void TransectStyleComplexItem::_appendConditionGate (QList< MissionItem * > & items, QObject * missionItemParent, int & seqNum, MAV_FRAME mavFrame, const QGeoCoordinate & coordinate) protected
Definition at line 1168 of file TransectStyleComplexItem.cc.
References _cameraCalc, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, coordinate(), CameraCalc::distanceMode(), and CameraCalc::distanceToSurface().
Referenced by _appendCameraTriggerDistanceUpdatePoint().
_appendLoadedMissionItems()
void TransectStyleComplexItem::_appendLoadedMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) protected
Definition at line 1310 of file TransectStyleComplexItem.cc.
References _loadedMissionItems, _sequenceNumber, and MissionItem::setSequenceNumber().
Referenced by appendMissionItems().
_appendSinglePhotoCapture()
void TransectStyleComplexItem::_appendSinglePhotoCapture (QList< MissionItem * > & items, QObject * missionItemParent, int & seqNum) protected
Definition at line 1152 of file TransectStyleComplexItem.cc.
Referenced by _buildAndAppendMissionItems().
_appendWaypoint()
void TransectStyleComplexItem::_appendWaypoint (QList< MissionItem * > & items, QObject * missionItemParent, int & seqNum, MAV_FRAME mavFrame, float holdTime, const QGeoCoordinate & coordinate) protected
Definition at line 1132 of file TransectStyleComplexItem.cc.
References _cameraCalc, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, coordinate(), CameraCalc::distanceMode(), and CameraCalc::distanceToSurface().
Referenced by _appendCameraTriggerDistanceUpdatePoint(), and _buildAndAppendMissionItems().
_buildAndAppendMissionItems()
void TransectStyleComplexItem::_buildAndAppendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) protected
Definition at line 1226 of file TransectStyleComplexItem.cc.
References _appendCameraTriggerDistanceUpdatePoint(), _appendSinglePhotoCapture(), _appendWaypoint(), _cameraCalc, _hoverAndCaptureDelaySeconds, _rgFlightPathCoordInfo, _sequenceNumber, QGroundControlQmlGlobal::AltitudeModeAbsolute, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeMixed, QGroundControlQmlGlobal::AltitudeModeNone, QGroundControlQmlGlobal::AltitudeModeRelative, QGroundControlQmlGlobal::AltitudeModeTerrainFrame, TransectStyleComplexItem::CoordInfo_t::coord, TransectStyleComplexItem::CoordInfo_t::coordType, CoordTypeInterior, CoordTypeInteriorHoverTrigger, CoordTypeInteriorTerrainAdded, CoordTypeSurveyEntry, CoordTypeSurveyExit, CoordTypeTurnaround, CameraCalc::distanceMode(), hoverAndCaptureEnabled(), triggerCamera(), and triggerDistance().
Referenced by appendMissionItems().
_hasTurnaround()
bool TransectStyleComplexItem::_hasTurnaround (void) const protected
Definition at line 383 of file TransectStyleComplexItem.cc.
References _turnAroundDistance().
_load()
bool TransectStyleComplexItem::_load (const QJsonObject & complexObject, bool forPresets, QString & errorString) protected
Definition at line 195 of file TransectStyleComplexItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::_amslExitAltChanged(), _cameraCalc, _cameraShots, _cameraTriggerInTurnAroundFact, VisualMissionItem::_controllerVehicle, _entryCoordinate, _exitCoordinate, _hoverAndCaptureFact, ComplexMissionItem::_isIncomplete, _jsonCameraCalcKey, _jsonCameraShotsKey, _jsonItemsKey, _jsonTerrainFlightSpeed, _jsonTransectStyleComplexItemKey, _jsonVisualTransectPointsKey, _loadedMissionItems, _loadedMissionItemsParent, _maxAMSLAltitude, _minAMSLAltitude, _refly90DegreesFact, _terrainAdjustMaxClimbRateFact, _terrainAdjustMaxDescentRateFact, _terrainAdjustToleranceFact, _turnAroundDistanceFact, _updateFlightPathSegmentsSignal(), _vehicleSpeed, _visualTransectPoints, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeTerrainFrame, cameraTriggerInTurnAroundName, CameraCalc::distanceMode(), errorString, MissionCommandTree::getUIInfo(), hoverAndCaptureName, MissionCommandTree::instance(), MissionCommandUIInfo::isStandaloneCoordinate(), JsonHelper::jsonVersionKey, CameraCalc::load(), MissionItem::load(), JsonHelper::loadGeoCoordinateArray(), ComplexMissionItem::maxAMSLAltitudeChanged(), ComplexMissionItem::minAMSLAltitudeChanged(), refly90DegreesName, MissionCommandUIInfo::specifiesCoordinate(), terrainAdjustMaxClimbRateName, terrainAdjustMaxDescentRateName, terrainAdjustToleranceName, turnAroundDistanceName, JsonHelper::validateKeys(), and QGCMAVLink::VehicleClassGeneric.
_missionItemCoordTerrainData
void TransectStyleComplexItem::_missionItemCoordTerrainData (bool success, QList< double > heights) protected slot
Definition at line 651 of file TransectStyleComplexItem.cc.
References _rgFlyThroughMissionItemCoordsTerrainHeights, _rgPathHeightInfo, and VisualMissionItem::readyForSaveStateChanged().
_polyPathTerrainData
void TransectStyleComplexItem::_polyPathTerrainData (bool success, const QList< TerrainPathQuery::PathHeightInfo_t > & rgPathHeightInfo) protected slot
Definition at line 635 of file TransectStyleComplexItem.cc.
References _rgPathHeightInfo, and VisualMissionItem::readyForSaveStateChanged().
_rebuildTransects
void TransectStyleComplexItem::_rebuildTransects (void) protected slot
Definition at line 398 of file TransectStyleComplexItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::_amslExitAltChanged(), _cameraCalc, _entryCoordinate, _exitCoordinate, _ignoreRecalc, ComplexMissionItem::_isIncomplete, _maxAMSLAltitude, _minAMSLAltitude, _rebuildTransectsPhase1(), _recalcCameraShots(), _recalcComplexDistance(), _rgFlightPathCoordInfo, _rgPathHeightInfo, VisualMissionItem::_setBoundingCube(), _transects, _updateCoordinateAltitudes(), _updateFlightPathSegmentsSignal(), _visualTransectPoints, VisualMissionItem::additionalTimeDelayChanged(), QGroundControlQmlGlobal::AltitudeModeAbsolute, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeMixed, QGroundControlQmlGlobal::AltitudeModeNone, QGroundControlQmlGlobal::AltitudeModeRelative, QGroundControlQmlGlobal::AltitudeModeTerrainFrame, CameraCalc::distanceMode(), ComplexMissionItem::isIncompleteChanged(), lastSequenceNumber(), VisualMissionItem::lastSequenceNumberChanged(), ComplexMissionItem::maxAMSLAltitudeChanged(), ComplexMissionItem::minAMSLAltitudeChanged(), timeBetweenShotsChanged(), and visualTransectPointsChanged().
Referenced by SurveyComplexItem::load(), CorridorScanComplexItem::loadPreset(), SurveyComplexItem::loadPreset(), CorridorScanComplexItem::rotateEntryPoint(), SurveyComplexItem::rotateEntryPoint(), setMissionFlightStatus(), SurveyComplexItem::SurveyComplexItem(), and TransectStyleComplexItem().
_rebuildTransectsPhase1()
virtual void TransectStyleComplexItem::_rebuildTransectsPhase1 (void) protected pure virtual
Rebuilds the _transects array.
Referenced by _rebuildTransects().
_recalcCameraShots()
virtual void TransectStyleComplexItem::_recalcCameraShots (void) protected pure virtual
Referenced by _rebuildTransects().
_recalcComplexDistance()
void TransectStyleComplexItem::_recalcComplexDistance (void) protected
Definition at line 1335 of file TransectStyleComplexItem.cc.
References _complexDistance, _visualTransectPoints, and ComplexMissionItem::complexDistanceChanged().
Referenced by _rebuildTransects(), and SurveyComplexItem::load().
_save()
void TransectStyleComplexItem::_save (QJsonObject & saveObject) protected
Definition at line 142 of file TransectStyleComplexItem.cc.
References _cameraCalc, _cameraShots, _cameraTriggerInTurnAroundFact, _hoverAndCaptureFact, _jsonCameraCalcKey, _jsonCameraShotsKey, _jsonItemsKey, _jsonTerrainFlightSpeed, _jsonTransectStyleComplexItemKey, _jsonVisualTransectPointsKey, _refly90DegreesFact, _terrainAdjustMaxClimbRateFact, _terrainAdjustMaxDescentRateFact, _terrainAdjustToleranceFact, _turnAroundDistanceFact, _vehicleSpeed, _visualTransectPoints, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, appendMissionItems(), cameraTriggerInTurnAroundName, CameraCalc::distanceMode(), hoverAndCaptureName, JsonHelper::jsonVersionKey, refly90DegreesName, CameraCalc::save(), JsonHelper::saveGeoCoordinateArray(), terrainAdjustMaxClimbRateName, terrainAdjustMaxDescentRateName, terrainAdjustToleranceName, and turnAroundDistanceName.
_setCameraShots()
void TransectStyleComplexItem::_setCameraShots (int cameraShots) protected
Definition at line 103 of file TransectStyleComplexItem.cc.
References _cameraShots, cameraShots(), and cameraShotsChanged().
_setDirty
void TransectStyleComplexItem::_setDirty (void) protected slot
Definition at line 360 of file TransectStyleComplexItem.cc.
References setDirty().
Referenced by CorridorScanComplexItem::CorridorScanComplexItem(), SurveyComplexItem::SurveyComplexItem(), and TransectStyleComplexItem().
_setExitCoordinate()
void TransectStyleComplexItem::_setExitCoordinate (const QGeoCoordinate & coordinate) protected
_setIfDirty
void TransectStyleComplexItem::_setIfDirty (bool dirty) protected slot
Definition at line 365 of file TransectStyleComplexItem.cc.
References dirty(), and setDirty().
Referenced by TransectStyleComplexItem().
_transectCount()
int TransectStyleComplexItem::_transectCount (void) const inline
Definition at line 65 of file TransectStyleComplexItem.h.
References _transects.
_triggerDistance()
double TransectStyleComplexItem::_triggerDistance (void) const protected
_turnAroundDistance()
double TransectStyleComplexItem::_turnAroundDistance (void) const protected
Definition at line 388 of file TransectStyleComplexItem.cc.
References _turnAroundDistanceFact.
Referenced by _hasTurnaround().
_updateCoordinateAltitudes
void TransectStyleComplexItem::_updateCoordinateAltitudes (void) protected slot
Definition at line 372 of file TransectStyleComplexItem.cc.
References entryCoordinate(), VisualMissionItem::entryCoordinateChanged(), exitCoordinate(), and VisualMissionItem::exitCoordinateChanged().
Referenced by _rebuildTransects().
_updateFlightPathSegmentsSignal
void TransectStyleComplexItem::_updateFlightPathSegmentsSignal (void) signal
Referenced by _load(), _rebuildTransects(), and TransectStyleComplexItem().
abbreviation()
QString TransectStyleComplexItem::abbreviation (void) const inline override virtual
Implements VisualMissionItem.
Definition at line 95 of file TransectStyleComplexItem.h.
addKMLVisuals()
void TransectStyleComplexItem::addKMLVisuals (KMLPlanDomDocument & domDocument) final virtual
Reimplemented from ComplexMissionItem.
Definition at line 1323 of file TransectStyleComplexItem.cc.
References _surveyAreaPolygon, KMLDomDocument::addPlacemark(), KMLDomDocument::addTextElement(), KMLDomDocument::appendChildToRoot(), QGCMapPolygon::kmlPolygonElement(), and KMLPlanDomDocument::surveyPolygonStyleName.
amslEntryAlt()
double TransectStyleComplexItem::amslEntryAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 1349 of file TransectStyleComplexItem.cc.
References _cameraCalc, VisualMissionItem::_controllerVehicle, _loadedMissionItems, VisualMissionItem::_missionController, _rgFlightPathCoordInfo, _rgPathHeightInfo, QGroundControlQmlGlobal::AltitudeModeAbsolute, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeMixed, QGroundControlQmlGlobal::AltitudeModeNone, QGroundControlQmlGlobal::AltitudeModeRelative, QGroundControlQmlGlobal::AltitudeModeTerrainFrame, MissionItem::command(), CameraCalc::distanceMode(), CameraCalc::distanceToSurface(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), MissionCommandUIInfo::isStandaloneCoordinate(), MissionItem::param7(), MissionController::plannedHomePosition(), MissionCommandUIInfo::specifiesCoordinate(), and QGCMAVLink::VehicleClassGeneric.
Referenced by amslExitAlt().
amslExitAlt()
double TransectStyleComplexItem::amslExitAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 1396 of file TransectStyleComplexItem.cc.
References _cameraCalc, VisualMissionItem::_controllerVehicle, _loadedMissionItems, _rgFlightPathCoordInfo, _rgPathHeightInfo, QGroundControlQmlGlobal::AltitudeModeAbsolute, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeMixed, QGroundControlQmlGlobal::AltitudeModeNone, QGroundControlQmlGlobal::AltitudeModeRelative, QGroundControlQmlGlobal::AltitudeModeTerrainFrame, amslEntryAlt(), MissionItem::command(), CameraCalc::distanceMode(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), MissionCommandUIInfo::isStandaloneCoordinate(), MissionItem::param7(), MissionCommandUIInfo::specifiesCoordinate(), and QGCMAVLink::VehicleClassGeneric.
appendMissionItems()
void TransectStyleComplexItem::appendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) final virtual
Returns the mission items associated with the complex item. Caller is responsible for freeing.
Parameters
items List to append to
missionItemParent Parent object for newly created MissionItems
Implements VisualMissionItem.
Definition at line 1121 of file TransectStyleComplexItem.cc.
References _appendLoadedMissionItems(), _buildAndAppendMissionItems(), and _loadedMissionItems.
Referenced by _save().
applyNewAltitude()
void TransectStyleComplexItem::applyNewAltitude (double newAltitude) final virtual
Adjust the altitude of the item if appropriate to the new altitude.
Implements VisualMissionItem.
Definition at line 1440 of file TransectStyleComplexItem.cc.
References _cameraCalc, CameraCalc::distanceToSurface(), and CameraCalc::valueSetIsDistance().
cameraCalc()
CameraCalc * TransectStyleComplexItem::cameraCalc (void) inline
Definition at line 41 of file TransectStyleComplexItem.h.
References _cameraCalc.
cameraShots()
int TransectStyleComplexItem::cameraShots (void) const inline
Definition at line 54 of file TransectStyleComplexItem.h.
References _cameraShots.
Referenced by _setCameraShots().
cameraShotsChanged
void TransectStyleComplexItem::cameraShotsChanged (void) signal
Referenced by _setCameraShots().
cameraTriggerInTurnAround()
Fact * TransectStyleComplexItem::cameraTriggerInTurnAround (void) inline
Definition at line 45 of file TransectStyleComplexItem.h.
References _cameraTriggerInTurnAroundFact.
commandDescription()
QString TransectStyleComplexItem::commandDescription (void) const inline override virtual
Implements VisualMissionItem.
Definition at line 93 of file TransectStyleComplexItem.h.
commandName()
QString TransectStyleComplexItem::commandName (void) const inline override virtual
Implements VisualMissionItem.
Definition at line 94 of file TransectStyleComplexItem.h.
complexDistance()
double TransectStyleComplexItem::complexDistance (void) const inline final virtual
Returns
The distance covered the complex mission item in meters. Signals complexDistanceChanged
Implements ComplexMissionItem.
Definition at line 72 of file TransectStyleComplexItem.h.
References _complexDistance.
CONSTANT()
QGCMapPolygon *surveyAreaPolygon READ surveyAreaPolygon TransectStyleComplexItem::CONSTANT (CameraCalc *cameraCalc READ cameraCalc CONSTANT) inline
Definition at line 23 of file TransectStyleComplexItem.h.
References _surveyAreaPolygon.
coordinate()
QGeoCoordinate TransectStyleComplexItem::coordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 84 of file TransectStyleComplexItem.h.
References entryCoordinate().
Referenced by _appendCameraTriggerDistanceUpdatePoint(), _appendConditionGate(), _appendWaypoint(), SurveyComplexItem::setCenterCoordinate(), CorridorScanComplexItem::setCoordinate(), and setCoordinate().
coveredArea()
double TransectStyleComplexItem::coveredArea (void) const
Definition at line 378 of file TransectStyleComplexItem.cc.
References _surveyAreaPolygon, and QGCMapPolygon::area().
coveredAreaChanged
void TransectStyleComplexItem::coveredAreaChanged (void) signal
Referenced by TransectStyleComplexItem().
dirty()
bool TransectStyleComplexItem::dirty (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 80 of file TransectStyleComplexItem.h.
References VisualMissionItem::_dirty.
Referenced by _setIfDirty(), and setDirty().
editableAlt()
double TransectStyleComplexItem::editableAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 1344 of file TransectStyleComplexItem.cc.
References _cameraCalc, and CameraCalc::distanceToSurface().
entryCoordinate()
QGeoCoordinate TransectStyleComplexItem::entryCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 85 of file TransectStyleComplexItem.h.
References _entryCoordinate.
Referenced by _updateCoordinateAltitudes(), and coordinate().
exitCoordinate()
QGeoCoordinate TransectStyleComplexItem::exitCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 86 of file TransectStyleComplexItem.h.
References _exitCoordinate.
Referenced by _updateCoordinateAltitudes().
exitCoordinateSameAsEntry()
bool TransectStyleComplexItem::exitCoordinateSameAsEntry (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 96 of file TransectStyleComplexItem.h.
greatestDistanceTo()
double TransectStyleComplexItem::greatestDistanceTo (const QGeoCoordinate & other) const final virtual
Get the point of complex mission item furthest away from a coordinate
Parameters
other QGeoCoordinate to which distance is calculated
Returns
the greatest distance from any point of the complex item to some coordinate Signals greatestDistanceToChanged
Implements ComplexMissionItem.
Definition at line 335 of file TransectStyleComplexItem.cc.
References _visualTransectPoints, and VisualMissionItem::distance().
hoverAndCapture() [1/2]
Fact * TransectStyleComplexItem::hoverAndCapture (void) inline
Definition at line 46 of file TransectStyleComplexItem.h.
References _hoverAndCaptureFact.
Referenced by hoverAndCaptureEnabled().
hoverAndCapture() [2/2]
const Fact * TransectStyleComplexItem::hoverAndCapture (void) const inline
Definition at line 52 of file TransectStyleComplexItem.h.
References _hoverAndCaptureFact.
hoverAndCaptureAllowed()
bool TransectStyleComplexItem::hoverAndCaptureAllowed (void) const
Definition at line 393 of file TransectStyleComplexItem.cc.
References VisualMissionItem::_controllerVehicle, Vehicle::multiRotor(), and Vehicle::vtol().
hoverAndCaptureEnabled()
bool TransectStyleComplexItem::hoverAndCaptureEnabled (void) const inline
Definition at line 61 of file TransectStyleComplexItem.h.
References hoverAndCapture().
Referenced by _buildAndAppendMissionItems(), SurveyComplexItem::additionalTimeDelay(), and lastSequenceNumber().
isSimpleItem()
bool TransectStyleComplexItem::isSimpleItem (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 81 of file TransectStyleComplexItem.h.
isStandaloneCoordinate()
bool TransectStyleComplexItem::isStandaloneCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 82 of file TransectStyleComplexItem.h.
lastSequenceNumber()
int TransectStyleComplexItem::lastSequenceNumber (void) const final virtual
Implements VisualMissionItem.
Definition at line 1032 of file TransectStyleComplexItem.cc.
References _loadedMissionItems, _rgFlightPathCoordInfo, _sequenceNumber, _transects, TransectStyleComplexItem::CoordInfo_t::coordType, CoordTypeInterior, CoordTypeInteriorHoverTrigger, CoordTypeInteriorTerrainAdded, CoordTypeSurveyEntry, CoordTypeSurveyExit, CoordTypeTurnaround, hoverAndCaptureEnabled(), and triggerCamera().
Referenced by _rebuildTransects(), and setSequenceNumber().
load()
bool TransectStyleComplexItem::load (const QJsonObject & complexObject, int sequenceNumber, QString & errorString) override pure virtual
Load the complex mission item from Json
Parameters
complexObject Complex mission item json object
sequenceNumber Sequence number for first MISSION_ITEM in survey
[out] errorString Error if load fails
Returns
true: load success, false: load failed, errorString set
Implements ComplexMissionItem.
Implemented in CorridorScanComplexItem, and SurveyComplexItem.
mapVisualQML()
QString TransectStyleComplexItem::mapVisualQML (void) const override pure virtual
Returns
The QML resource file which contains the control which visualizes the item on the map.
Implements VisualMissionItem.
Implemented in CorridorScanComplexItem, and SurveyComplexItem.
maxAMSLAltitude()
double TransectStyleComplexItem::maxAMSLAltitude (void) const final virtual
Returns
Maximum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 1457 of file TransectStyleComplexItem.cc.
References _cameraCalc, _maxAMSLAltitude, VisualMissionItem::_missionController, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeRelative, CameraCalc::distanceMode(), CameraCalc::distanceToSurface(), and MissionController::plannedHomePosition().
minAMSLAltitude()
double TransectStyleComplexItem::minAMSLAltitude (void) const final virtual
Returns
Minimum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 1446 of file TransectStyleComplexItem.cc.
References _cameraCalc, _minAMSLAltitude, VisualMissionItem::_missionController, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeModeRelative, CameraCalc::distanceMode(), CameraCalc::distanceToSurface(), and MissionController::plannedHomePosition().
readyForSaveState()
TransectStyleComplexItem::ReadyForSaveState TransectStyleComplexItem::readyForSaveState (void) const override virtual
Returns
Returns whether the item is ready for save and if not, why
Reimplemented from VisualMissionItem.
Definition at line 667 of file TransectStyleComplexItem.cc.
References _cameraCalc, _loadedMissionItems, _rgPathHeightInfo, _surveyAreaPolygon, VisualMissionItem::_wizardMode, QGroundControlQmlGlobal::AltitudeModeCalcAboveTerrain, CameraCalc::distanceMode(), QGCMapPolygon::isValid(), VisualMissionItem::NotReadyForSaveData, VisualMissionItem::NotReadyForSaveTerrain, and VisualMissionItem::ReadyForSave.
Referenced by CorridorScanComplexItem::readyForSaveState(), and SurveyComplexItem::readyForSaveState().
refly90Degrees()
Fact * TransectStyleComplexItem::refly90Degrees (void) inline
Definition at line 47 of file TransectStyleComplexItem.h.
References _refly90DegreesFact.
save()
void TransectStyleComplexItem::save (QJsonArray & missionItems) override pure virtual
Save the item(s) in Json format
Parameters
missionItems Current set of mission items, new items should be appended to the end
Implements VisualMissionItem.
Implemented in CorridorScanComplexItem, and SurveyComplexItem.
sequenceNumber()
int TransectStyleComplexItem::sequenceNumber (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 87 of file TransectStyleComplexItem.h.
References _sequenceNumber.
Referenced by CorridorScanComplexItem::load(), SurveyComplexItem::load(), and setSequenceNumber().
setCoordinate()
void TransectStyleComplexItem::setCoordinate (const QGeoCoordinate & coordinate) override virtual
Implements VisualMissionItem.
Definition at line 123 of file TransectStyleComplexItem.cc.
References _entryCoordinate, _surveyAreaPolygon, coordinate(), QGCMapPolygon::coordinateList(), QGCMapPolygon::count(), and QGCMapPolygon::setPath().
setDirty()
void TransectStyleComplexItem::setDirty (bool dirty) final virtual
Implements VisualMissionItem.
Definition at line 111 of file TransectStyleComplexItem.cc.
References _cameraCalc, VisualMissionItem::_dirty, _surveyAreaPolygon, dirty(), VisualMissionItem::dirtyChanged(), CameraSpec::setDirty(), and QGCMapPolygon::setDirty().
Referenced by _setDirty(), _setIfDirty(), and SurveyComplexItem::rotateEntryPoint().
setMissionFlightStatus()
void TransectStyleComplexItem::setMissionFlightStatus (MissionController::MissionFlightStatus_t & missionFlightStatus) final virtual
Update item to mission flight status at point where this item appears in mission. IMPORTANT: Overrides must call base class implementation
Reimplemented from VisualMissionItem.
Definition at line 349 of file TransectStyleComplexItem.cc.
References _rebuildTransects(), _vehicleSpeed, QGC::fuzzyCompare(), VisualMissionItem::setMissionFlightStatus(), timeBetweenShotsChanged(), and MissionController::MissionFlightStatus_t::vehicleSpeed.
setSequenceNumber()
void TransectStyleComplexItem::setSequenceNumber (int sequenceNumber) final virtual
Implements VisualMissionItem.
Definition at line 186 of file TransectStyleComplexItem.cc.
References _sequenceNumber, lastSequenceNumber(), VisualMissionItem::lastSequenceNumberChanged(), sequenceNumber(), and VisualMissionItem::sequenceNumberChanged().
specifiedFlightSpeed()
double TransectStyleComplexItem::specifiedFlightSpeed (void) inline final virtual
Implements VisualMissionItem.
Definition at line 88 of file TransectStyleComplexItem.h.
specifiedGimbalPitch()
double TransectStyleComplexItem::specifiedGimbalPitch (void) inline final virtual
Implements VisualMissionItem.
Definition at line 90 of file TransectStyleComplexItem.h.
specifiedGimbalYaw()
double TransectStyleComplexItem::specifiedGimbalYaw (void) inline final virtual
Implements VisualMissionItem.
Definition at line 89 of file TransectStyleComplexItem.h.
specifiesAltitudeOnly()
bool TransectStyleComplexItem::specifiesAltitudeOnly (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 83 of file TransectStyleComplexItem.h.
specifiesCoordinate()
bool TransectStyleComplexItem::specifiesCoordinate (void) const override pure virtual
Implements VisualMissionItem.
Implemented in CorridorScanComplexItem, and SurveyComplexItem.
terrainAdjustMaxClimbRate()
Fact * TransectStyleComplexItem::terrainAdjustMaxClimbRate (void) inline
Definition at line 50 of file TransectStyleComplexItem.h.
References _terrainAdjustMaxClimbRateFact.
terrainAdjustMaxDescentRate()
Fact * TransectStyleComplexItem::terrainAdjustMaxDescentRate (void) inline
Definition at line 49 of file TransectStyleComplexItem.h.
References _terrainAdjustMaxDescentRateFact.
terrainAdjustTolerance()
Fact * TransectStyleComplexItem::terrainAdjustTolerance (void) inline
Definition at line 48 of file TransectStyleComplexItem.h.
References _terrainAdjustToleranceFact.
timeBetweenShots()
virtual double TransectStyleComplexItem::timeBetweenShots (void) inline virtual
Reimplemented in CorridorScanComplexItem, and SurveyComplexItem.
Definition at line 58 of file TransectStyleComplexItem.h.
timeBetweenShotsChanged
void TransectStyleComplexItem::timeBetweenShotsChanged (void) signal
Referenced by _rebuildTransects(), and setMissionFlightStatus().
triggerCamera()
bool TransectStyleComplexItem::triggerCamera (void) const inline
Definition at line 62 of file TransectStyleComplexItem.h.
References triggerDistance().
Referenced by _buildAndAppendMissionItems(), and lastSequenceNumber().
triggerDistance()
double TransectStyleComplexItem::triggerDistance (void) const inline
Definition at line 60 of file TransectStyleComplexItem.h.
References _cameraCalc, and CameraCalc::adjustedFootprintFrontal().
Referenced by _appendCameraTriggerDistance(), _appendCameraTriggerDistanceUpdatePoint(), _buildAndAppendMissionItems(), SurveyComplexItem::timeBetweenShots(), and triggerCamera().
turnAroundDistance()
Fact * TransectStyleComplexItem::turnAroundDistance (void) inline
Definition at line 44 of file TransectStyleComplexItem.h.
References _turnAroundDistanceFact.
visualTransectPoints()
QVariantList TransectStyleComplexItem::visualTransectPoints (void) inline
Definition at line 42 of file TransectStyleComplexItem.h.
References _visualTransectPoints.
visualTransectPointsChanged
void TransectStyleComplexItem::visualTransectPointsChanged (void) signal
Referenced by _rebuildTransects(), and TransectStyleComplexItem().
Member Data Documentation
_cameraCalc
CameraCalc TransectStyleComplexItem::_cameraCalc protected
Definition at line 181 of file TransectStyleComplexItem.h.
Referenced by _appendConditionGate(), _appendWaypoint(), _buildAndAppendMissionItems(), _load(), _rebuildTransects(), _save(), amslEntryAlt(), amslExitAlt(), applyNewAltitude(), cameraCalc(), editableAlt(), maxAMSLAltitude(), minAMSLAltitude(), readyForSaveState(), setDirty(), CorridorScanComplexItem::timeBetweenShots(), and triggerDistance().
_cameraShots
int TransectStyleComplexItem::_cameraShots = 0 protected
Definition at line 178 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), _setCameraShots(), cameraShots(), and SurveyComplexItem::load().
_cameraTriggerInTurnAroundFact
SettingsFact TransectStyleComplexItem::_cameraTriggerInTurnAroundFact protected
Definition at line 191 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), and cameraTriggerInTurnAround().
_complexDistance
double TransectStyleComplexItem::_complexDistance = qQNaN() protected
Definition at line 177 of file TransectStyleComplexItem.h.
Referenced by _recalcComplexDistance(), and complexDistance().
_entryCoordinate
QGeoCoordinate TransectStyleComplexItem::_entryCoordinate protected
Definition at line 151 of file TransectStyleComplexItem.h.
Referenced by _load(), _rebuildTransects(), entryCoordinate(), CorridorScanComplexItem::setCoordinate(), and setCoordinate().
_exitCoordinate
QGeoCoordinate TransectStyleComplexItem::_exitCoordinate protected
Definition at line 152 of file TransectStyleComplexItem.h.
Referenced by _load(), _rebuildTransects(), and exitCoordinate().
_forceLargeTransectSpacingMeters
constexpr double TransectStyleComplexItem::_forceLargeTransectSpacingMeters = 100000 static constexpr protected
Definition at line 208 of file TransectStyleComplexItem.h.
_hoverAndCaptureDelaySeconds
constexpr int TransectStyleComplexItem::_hoverAndCaptureDelaySeconds = 4 static constexpr protected
Definition at line 206 of file TransectStyleComplexItem.h.
Referenced by _buildAndAppendMissionItems(), and SurveyComplexItem::additionalTimeDelay().
_hoverAndCaptureFact
SettingsFact TransectStyleComplexItem::_hoverAndCaptureFact protected
Definition at line 192 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), hoverAndCapture(), and hoverAndCapture().
_ignoreRecalc
bool TransectStyleComplexItem::_ignoreRecalc = false protected
Definition at line 176 of file TransectStyleComplexItem.h.
Referenced by _rebuildTransects().
_jsonCameraCalcKey
constexpr const char* TransectStyleComplexItem::_jsonCameraCalcKey = "CameraCalc" static constexpr protected
Definition at line 199 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_jsonCameraShotsKey
constexpr const char* TransectStyleComplexItem::_jsonCameraShotsKey = "CameraShots" static constexpr protected
Definition at line 203 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_jsonItemsKey
constexpr const char* TransectStyleComplexItem::_jsonItemsKey = "Items" static constexpr protected
Definition at line 201 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_jsonTerrainFlightSpeed
constexpr const char* TransectStyleComplexItem::_jsonTerrainFlightSpeed = "TerrainFlightSpeed" static constexpr protected
Definition at line 202 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_jsonTransectStyleComplexItemKey
constexpr const char* TransectStyleComplexItem::_jsonTransectStyleComplexItemKey = "TransectStyleComplexItem" static constexpr protected
Definition at line 198 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_jsonVisualTransectPointsKey
constexpr const char* TransectStyleComplexItem::_jsonVisualTransectPointsKey = "VisualTransectPoints" static constexpr protected
Definition at line 200 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
_loadedMissionItems
QList<MissionItem*> TransectStyleComplexItem::_loadedMissionItems protected
Mission items loaded from plan file.
Definition at line 186 of file TransectStyleComplexItem.h.
Referenced by _appendLoadedMissionItems(), _load(), amslEntryAlt(), amslExitAlt(), appendMissionItems(), lastSequenceNumber(), and readyForSaveState().
_loadedMissionItemsParent
QObject* TransectStyleComplexItem::_loadedMissionItemsParent = nullptr protected
Parent for all items in _loadedMissionItems for simpler delete.
Definition at line 185 of file TransectStyleComplexItem.h.
Referenced by _load().
_maxAMSLAltitude
double TransectStyleComplexItem::_maxAMSLAltitude = qQNaN() protected
Definition at line 183 of file TransectStyleComplexItem.h.
Referenced by _load(), _rebuildTransects(), and maxAMSLAltitude().
_metaDataMap
QMap<QString, FactMetaData*> TransectStyleComplexItem::_metaDataMap protected
Definition at line 188 of file TransectStyleComplexItem.h.
_minAMSLAltitude
double TransectStyleComplexItem::_minAMSLAltitude = qQNaN() protected
Definition at line 182 of file TransectStyleComplexItem.h.
Referenced by _load(), _rebuildTransects(), and minAMSLAltitude().
_minimumTransectSpacingMeters
constexpr double TransectStyleComplexItem::_minimumTransectSpacingMeters = 0.3 static constexpr protected
Definition at line 207 of file TransectStyleComplexItem.h.
_refly90DegreesFact
SettingsFact TransectStyleComplexItem::_refly90DegreesFact protected
Definition at line 193 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), and refly90Degrees().
_rgFlightPathCoordInfo
QList<CoordInfo_t> TransectStyleComplexItem::_rgFlightPathCoordInfo protected
Fully calculated flight path (including terrain if needed)
Definition at line 174 of file TransectStyleComplexItem.h.
Referenced by _buildAndAppendMissionItems(), _rebuildTransects(), amslEntryAlt(), amslExitAlt(), and lastSequenceNumber().
_rgFlyThroughMissionItemCoords
QList<QGeoCoordinate> TransectStyleComplexItem::_rgFlyThroughMissionItemCoords protected
Definition at line 172 of file TransectStyleComplexItem.h.
_rgFlyThroughMissionItemCoordsTerrainHeights
QList<double> TransectStyleComplexItem::_rgFlyThroughMissionItemCoordsTerrainHeights protected
Definition at line 173 of file TransectStyleComplexItem.h.
Referenced by _missionItemCoordTerrainData().
_rgPathHeightInfo
QList<TerrainPathQuery::PathHeightInfo_t> TransectStyleComplexItem::_rgPathHeightInfo protected
Path height for each segment includes turn segments.
Definition at line 171 of file TransectStyleComplexItem.h.
Referenced by _missionItemCoordTerrainData(), _polyPathTerrainData(), _rebuildTransects(), amslEntryAlt(), amslExitAlt(), and readyForSaveState().
_sequenceNumber
int TransectStyleComplexItem::_sequenceNumber = 0 protected
Definition at line 150 of file TransectStyleComplexItem.h.
Referenced by _appendLoadedMissionItems(), _buildAndAppendMissionItems(), lastSequenceNumber(), sequenceNumber(), and setSequenceNumber().
_surveyAreaPolygon
QGCMapPolygon TransectStyleComplexItem::_surveyAreaPolygon protected
Definition at line 153 of file TransectStyleComplexItem.h.
Referenced by addKMLVisuals(), SurveyComplexItem::centerCoordinate(), CONSTANT(), coveredArea(), readyForSaveState(), SurveyComplexItem::setCenterCoordinate(), setCoordinate(), and setDirty().
_terrainAdjustMaxClimbRateFact
SettingsFact TransectStyleComplexItem::_terrainAdjustMaxClimbRateFact protected
Definition at line 195 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), and terrainAdjustMaxClimbRate().
_terrainAdjustMaxDescentRateFact
SettingsFact TransectStyleComplexItem::_terrainAdjustMaxDescentRateFact protected
Definition at line 196 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), and terrainAdjustMaxDescentRate().
_terrainAdjustToleranceFact
SettingsFact TransectStyleComplexItem::_terrainAdjustToleranceFact protected
Definition at line 194 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), and terrainAdjustTolerance().
_terrainQueryTimeoutMsecs
constexpr int TransectStyleComplexItem::_terrainQueryTimeoutMsecs = 1000 static constexpr protected
Definition at line 205 of file TransectStyleComplexItem.h.
_timeBetweenShots
double TransectStyleComplexItem::_timeBetweenShots = 0 protected
Definition at line 179 of file TransectStyleComplexItem.h.
_transects
QList<QList<CoordInfo_t> > TransectStyleComplexItem::_transects protected
Definition at line 170 of file TransectStyleComplexItem.h.
Referenced by _rebuildTransects(), _transectCount(), SurveyComplexItem::additionalTimeDelay(), and lastSequenceNumber().
_turnAroundDistanceFact
SettingsFact TransectStyleComplexItem::_turnAroundDistanceFact protected
Definition at line 190 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), _turnAroundDistance(), and turnAroundDistance().
_vehicleSpeed
double TransectStyleComplexItem::_vehicleSpeed = 5 protected
Definition at line 180 of file TransectStyleComplexItem.h.
Referenced by _load(), _save(), setMissionFlightStatus(), CorridorScanComplexItem::timeBetweenShots(), and SurveyComplexItem::timeBetweenShots().
_visualTransectPoints
QVariantList TransectStyleComplexItem::_visualTransectPoints protected
Used to draw the flight path visuals on the screen.
Definition at line 169 of file TransectStyleComplexItem.h.
Referenced by _load(), _rebuildTransects(), _recalcComplexDistance(), _save(), greatestDistanceTo(), and visualTransectPoints().
cameraTriggerInTurnAroundName
constexpr const char* TransectStyleComplexItem::cameraTriggerInTurnAroundName = "CameraTriggerInTurnAround" static constexpr
Definition at line 108 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
hoverAndCaptureName
constexpr const char* TransectStyleComplexItem::hoverAndCaptureName = "HoverAndCapture" static constexpr
Definition at line 109 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
refly90DegreesName
constexpr const char* TransectStyleComplexItem::refly90DegreesName = "Refly90Degrees" static constexpr
Definition at line 110 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
terrainAdjustMaxClimbRateName
constexpr const char* TransectStyleComplexItem::terrainAdjustMaxClimbRateName = "TerrainAdjustMaxClimbRate" static constexpr
Definition at line 112 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
terrainAdjustMaxDescentRateName
constexpr const char* TransectStyleComplexItem::terrainAdjustMaxDescentRateName = "TerrainAdjustMaxDescentRate" static constexpr
Definition at line 113 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
terrainAdjustToleranceName
constexpr const char* TransectStyleComplexItem::terrainAdjustToleranceName = "TerrainAdjustTolerance" static constexpr
Definition at line 111 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
turnAroundDistanceMultiRotorName
constexpr const char* TransectStyleComplexItem::turnAroundDistanceMultiRotorName = "TurnAroundDistanceMultiRotor" static constexpr
Definition at line 107 of file TransectStyleComplexItem.h.
turnAroundDistanceName
constexpr const char* TransectStyleComplexItem::turnAroundDistanceName = "TurnAroundDistance" static constexpr
Definition at line 106 of file TransectStyleComplexItem.h.
Referenced by _load(), and _save().
The documentation for this class was generated from the following files:
src/MissionManager/TransectStyleComplexItem.h
src/MissionManager/TransectStyleComplexItem.cc