QGroundControl: ActuatorOutputs::ActuatorOutputSubgroup Class Reference
ActuatorOutputs::ActuatorOutputSubgroup Class Reference
#include <ActuatorOutputs.h>
Signals
void channelsChanged ()
void channelConfigsChanged ()
Public Member Functions
ActuatorOutputSubgroup (QObject *parent, const QString &label)
QString label READ label CONSTANT (QmlObjectListModel *channels READ channels NOTIFY channelsChanged) 1(QmlObjectListModel *channelConfigs READ channelConfigs NOTIFY channelConfigsChanged) 1(ConfigParameter *primaryParam READ primaryParam CONSTANT) 1(QmlObjectListModel *configParams READ configParams CONSTANT) const QString &label() const
QmlObjectListModel * channelConfigs ()
void addChannelConfig (ChannelConfig *channelConfig)
QmlObjectListModel * channels ()
void addChannel (ActuatorOutputChannel *channel)
ConfigParameter * primaryParam () const
void addConfigParam (ConfigParameter *param)
QmlObjectListModel * configParams ()
const QList< ActuatorActions::Config > & actions () const
void addAction (const ActuatorActions::Config &action)
Detailed Description
Definition at line 136 of file ActuatorOutputs.h.
Constructor & Destructor Documentation
ActuatorOutputSubgroup()
ActuatorOutputs::ActuatorOutputSubgroup::ActuatorOutputSubgroup (QObject * parent, const QString & label) inline
Definition at line 140 of file ActuatorOutputs.h.
Member Function Documentation
actions()
const QList< ActuatorActions::Config > & ActuatorOutputs::ActuatorOutputSubgroup::actions () const inline
Definition at line 163 of file ActuatorOutputs.h.
addAction()
void ActuatorOutputs::ActuatorOutputSubgroup::addAction (const ActuatorActions::Config & action) inline
Definition at line 164 of file ActuatorOutputs.h.
addChannel()
void ActuatorOutputSubgroup::addChannel (ActuatorOutputChannel * channel)
Definition at line 45 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), and channelsChanged().
addChannelConfig()
void ActuatorOutputSubgroup::addChannelConfig (ChannelConfig * channelConfig)
Definition at line 39 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), and channelConfigsChanged().
addConfigParam()
void ActuatorOutputSubgroup::addConfigParam (ConfigParameter * param)
Definition at line 51 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), ActuatorOutputs::ConfigParameter::function(), and ActuatorOutputs::ConfigParameter::Primary.
channelConfigs()
QmlObjectListModel * ActuatorOutputs::ActuatorOutputSubgroup::channelConfigs () inline
Definition at line 152 of file ActuatorOutputs.h.
Referenced by Actuators::parametersChanged().
channelConfigsChanged
void ActuatorOutputs::ActuatorOutputSubgroup::channelConfigsChanged () signal
Referenced by addChannelConfig().
channels()
QmlObjectListModel * ActuatorOutputs::ActuatorOutputSubgroup::channels () inline
Definition at line 156 of file ActuatorOutputs.h.
Referenced by ActuatorOutputs::ActuatorOutput::forEachOutputFunction().
channelsChanged
void ActuatorOutputs::ActuatorOutputSubgroup::channelsChanged () signal
Referenced by addChannel().
configParams()
QmlObjectListModel * ActuatorOutputs::ActuatorOutputSubgroup::configParams () inline
Definition at line 161 of file ActuatorOutputs.h.
CONSTANT()
QString label READ label ActuatorOutputs::ActuatorOutputSubgroup::CONSTANT (QmlObjectListModel *channels READ channels NOTIFY channelsChanged) const & inline
Definition at line 143 of file ActuatorOutputs.h.
primaryParam()
ConfigParameter * ActuatorOutputs::ActuatorOutputSubgroup::primaryParam () const inline
Definition at line 159 of file ActuatorOutputs.h.
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/ActuatorOutputs.h
src/Vehicle/Actuators/ActuatorOutputs.cc