QGroundControl: Vehicle Class Reference
Vehicle Class Reference
#include <Vehicle.h>
Public Types
enum CheckList { CheckListNotSetup = 0 , CheckListPassed , CheckListFailed }
enum PIDTuningTelemetryMode { ModeDisabled , ModeRateAndAttitude , ModeVelocityAndPosition , ModeAltitudeAndAirspeed }
Public Types inherited from VehicleTypes
enum MavCmdResultFailureCode_t { MavCmdResultCommandResultOnly , MavCmdResultFailureNoResponseToCommand , MavCmdResultFailureDuplicateCommand }
enum RequestMessageResultHandlerFailureCode_t {
RequestMessageNoFailure , RequestMessageFailureCommandError , RequestMessageFailureCommandNotAcked , RequestMessageFailureMessageNotReceived ,
RequestMessageFailureDuplicate
}
typedef void(* MavCmdProgressHandler) (void *progressHandlerData, int compId, const mavlink_command_ack_t &ack)
Callback for sendMavCommandWithHandler which handles MAV_RESULT_IN_PROGRESS acks.
typedef void(* MavCmdResultHandler) (void *resultHandlerData, int compId, const mavlink_command_ack_t &ack, MavCmdResultFailureCode_t failureCode)
Callback for sendMavCommandWithHandler which handles all non-IN_PROGRESS acks.
typedef struct VehicleTypes::MavCmdAckHandlerInfo_s MavCmdAckHandlerInfo_t
Callback info bundle for sendMavCommandWithHandler.
typedef void(* RequestMessageResultHandler) (void *resultHandlerData, MAV_RESULT commandResult, RequestMessageResultHandlerFailureCode_t failureCode, const mavlink_message_t &message)
Callback for requestMessage — delivered when the ack/message pair resolves or a failure occurs.
Public Slots
void setVtolInFwdFlight (bool vtolInFwdFlight)
void _offlineFirmwareTypeSettingChanged (QVariant varFirmwareType)
void _offlineVehicleTypeSettingChanged (QVariant varVehicleType)
void sendGripperAction (GRIPPER_ACTIONS gripperOption)
Signals
void coordinateChanged (QGeoCoordinate coordinate)
void mavlinkMessageReceived (const mavlink_message_t &message)
void homePositionChanged (const QGeoCoordinate &homePosition)
void armedPositionChanged ()
void armedChanged (bool armed)
void flightModeChanged (const QString &flightMode)
void flyingChanged (bool flying)
void landingChanged (bool landing)
void guidedModeChanged (bool guidedMode)
void inFwdFlightChanged ()
void vtolInFwdFlightChanged (bool vtolInFwdFlight)
void prearmErrorChanged (const QString &prearmError)
void soloFirmwareChanged (bool soloFirmware)
void defaultCruiseSpeedChanged (double cruiseSpeed)
void defaultHoverSpeedChanged (double hoverSpeed)
void firmwareTypeChanged ()
void vehicleTypeChanged ()
void hobbsMeterChanged ()
void capabilitiesKnownChanged (bool capabilitiesKnown)
void initialPlanRequestCompleteChanged (bool initialPlanRequestComplete)
void capabilityBitsChanged (uint64_t capabilityBits)
void toolIndicatorsChanged ()
void checkListStateChanged ()
void longitudeChanged ()
void currentConfigChanged ()
void autoDisarmChanged ()
void flightModesChanged ()
void sensorsPresentBitsChanged (int sensorsPresentBits)
void sensorsEnabledBitsChanged (int sensorsEnabledBits)
void sensorsHealthBitsChanged (int sensorsHealthBits)
void sensorsUnhealthyBitsChanged (int sensorsUnhealthyBits)
void orbitActiveChanged (bool orbitActive)
void readyToFlyAvailableChanged (bool readyToFlyAvailable)
void readyToFlyChanged (bool readyToFy)
void allSensorsHealthyChanged (bool allSensorsHealthy)
void requiresGpsFixChanged ()
void haveMRSpeedLimChanged ()
void haveFWSpeedLimChanged ()
void hasGripperChanged ()
void firmwareVersionChanged ()
void firmwareCustomVersionChanged ()
void gitHashChanged (QString hash)
void vehicleUIDChanged ()
void loadProgressChanged (float value)
void rcChannelsRawChanged (QVector< int > channelValues)
void rcChannelsClampedChanged (QVector< int > channelValues)
void servoOutputsChanged (QVector< int > servoValues)
void mavlinkLogData (Vehicle *vehicle, uint8_t target_system, uint8_t target_component, uint16_t sequence, uint8_t first_message, QByteArray data, bool acked)
void mavCommandResult (int vehicleId, int targetComponent, int command, int ackResult, int failureCode)
void mavlinkSerialControl (uint8_t device, uint8_t flags, uint16_t timeout, uint32_t baudrate, QByteArray data)
void mavlinkStatusChanged ()
void mavlinkSigningChanged ()
void isROIEnabledChanged ()
void roiCoordChanged (const QGeoCoordinate &centerCoord)
void initialConnectComplete ()
void sensorsParametersResetAck (bool success)
void logEntry (uint32_t time_utc, uint32_t size, uint16_t id, uint16_t num_logs, uint16_t last_log_num)
void logData (uint32_t ofs, uint16_t id, uint8_t count, const uint8_t *data)
void mavlinkMsgIntervalsChanged (uint8_t compid, uint16_t msgId, int32_t rate)
void gcsControlStatusChanged ()
void requestOperatorControlReceived (int sysIdRequestingControl, int allowTakeover, int requestTimeoutSecs)
void sendControlRequestAllowedChanged (bool sendControlRequestAllowed)
void textMessageReceived (int sysid, int componentid, int severity, QString text, QString description)
void messagesReceivedChanged ()
void messagesSentChanged ()
void messagesLostChanged ()
void messageTypeChanged ()
void messageCountChanged ()
void formattedMessagesChanged ()
void newFormattedMessage (QString formattedMessage)
void flowImageIndexChanged ()
void mavlinkLogManagerChanged ()
void cameraManagerChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Public Member Functions
Vehicle (LinkInterface *link, int vehicleId, int defaultComponentId, MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType, QObject *parent=nullptr)
Vehicle (MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType, QObject *parent=nullptr)
~Vehicle ()
int id READ id CONSTANT (AutoPilotPlugin *autopilotPlugin MEMBER _autopilotPlugin CONSTANT) 1(QGeoCoordinate coordinate READ coordinate NOTIFY coordinateChanged) 1(QGeoCoordinate homePosition READ homePosition NOTIFY homePositionChanged) 1(QGeoCoordinate armedPosition READ armedPosition NOTIFY armedPositionChanged) 1(bool armed READ armed WRITE setArmedShowError NOTIFY armedChanged) 1(bool autoDisarm READ autoDisarm NOTIFY autoDisarmChanged) 1(bool flightModeSetAvailable READ flightModeSetAvailable CONSTANT) 1(QStringList flightModes READ flightModes NOTIFY flightModesChanged) 1(QString flightMode READ flightMode WRITE setFlightMode NOTIFY flightModeChanged) 1(TrajectoryPoints *trajectoryPoints MEMBER _trajectoryPoints CONSTANT) 1(QmlObjectListModel *cameraTriggerPoints READ cameraTriggerPoints CONSTANT) 1(float latitude READ latitude NOTIFY coordinateChanged) 1(float longitude READ longitude NOTIFY coordinateChanged) 1(bool px4Firmware READ px4Firmware NOTIFY firmwareTypeChanged) 1(bool apmFirmware READ apmFirmware NOTIFY firmwareTypeChanged) 1(bool soloFirmware READ soloFirmware WRITE setSoloFirmware NOTIFY soloFirmwareChanged) 1(bool genericFirmware READ genericFirmware CONSTANT) 1(uint messagesReceived READ messagesReceived NOTIFY messagesReceivedChanged) 1(uint messagesSent READ messagesSent NOTIFY messagesSentChanged) 1(uint messagesLost READ messagesLost NOTIFY messagesLostChanged) 1(bool airship READ airship NOTIFY vehicleTypeChanged) 1(bool fixedWing READ fixedWing NOTIFY vehicleTypeChanged) 1(bool multiRotor READ multiRotor NOTIFY vehicleTypeChanged) 1(bool vtol READ vtol NOTIFY vehicleTypeChanged) 1(bool rover READ rover NOTIFY vehicleTypeChanged) 1(bool sub READ sub NOTIFY vehicleTypeChanged) 1(VehicleSupports *supports READ supports CONSTANT) 1(QString prearmError READ prearmError WRITE setPrearmError NOTIFY prearmErrorChanged) 1(int motorCount READ motorCount CONSTANT) 1(bool coaxialMotors READ coaxialMotors CONSTANT) 1(bool xConfigMotors READ xConfigMotors CONSTANT) 1(bool isOfflineEditingVehicle READ isOfflineEditingVehicle CONSTANT) 1(int sensorsPresentBits READ sensorsPresentBits NOTIFY sensorsPresentBitsChanged) 1(int sensorsEnabledBits READ sensorsEnabledBits NOTIFY sensorsEnabledBitsChanged) 1(int sensorsHealthBits READ sensorsHealthBits NOTIFY sensorsHealthBitsChanged) 1(int sensorsUnhealthyBits READ sensorsUnhealthyBits NOTIFY sensorsUnhealthyBitsChanged) 1(QString missionFlightMode READ missionFlightMode CONSTANT) 1(QString pauseFlightMode READ pauseFlightMode CONSTANT) 1(QString rtlFlightMode READ rtlFlightMode CONSTANT) 1(QString smartRTLFlightMode READ smartRTLFlightMode CONSTANT) 1(QString landFlightMode READ landFlightMode CONSTANT) 1(QString takeControlFlightMode READ takeControlFlightMode CONSTANT) 1(QString followFlightMode READ followFlightMode CONSTANT) 1(QString motorDetectionFlightMode READ motorDetectionFlightMode CONSTANT) 1(QString stabilizedFlightMode READ stabilizedFlightMode CONSTANT) 1(QString firmwareTypeString READ firmwareTypeString NOTIFY firmwareTypeChanged) 1(QString vehicleTypeString READ vehicleTypeString NOTIFY vehicleTypeChanged) 1(QString vehicleImageOpaque READ vehicleImageOpaque CONSTANT) 1(QString vehicleImageOutline READ vehicleImageOutline CONSTANT) 1(QVariantList toolIndicators READ toolIndicators NOTIFY toolIndicatorsChanged) 1(bool initialPlanRequestComplete READ initialPlanRequestComplete NOTIFY initialPlanRequestCompleteChanged) 1(QString hobbsMeter READ hobbsMeter NOTIFY hobbsMeterChanged) 1(bool inFwdFlight READ inFwdFlight NOTIFY inFwdFlightChanged) 1(bool vtolInFwdFlight READ vtolInFwdFlight WRITE setVtolInFwdFlight NOTIFY vtolInFwdFlightChanged) 1(quint64 mavlinkSentCount READ mavlinkSentCount NOTIFY mavlinkStatusChanged) 1(quint64 mavlinkReceivedCount READ mavlinkReceivedCount NOTIFY mavlinkStatusChanged) 1(quint64 mavlinkLossCount READ mavlinkLossCount NOTIFY mavlinkStatusChanged) 1(float mavlinkLossPercent READ mavlinkLossPercent NOTIFY mavlinkStatusChanged) 1(GimbalController *gimbalController READ gimbalController CONSTANT) 1(bool hasGripper READ hasGripper NOTIFY hasGripperChanged) 1(bool isROIEnabled READ isROIEnabled NOTIFY isROIEnabledChanged) 1(CheckList checkListState READ checkListState WRITE setCheckListState NOTIFY checkListStateChanged) 1(bool readyToFlyAvailable READ readyToFlyAvailable NOTIFY readyToFlyAvailableChanged) 1(bool readyToFly READ readyToFly NOTIFY readyToFlyChanged) 1(QObject *sysStatusSensorInfo READ sysStatusSensorInfo CONSTANT) 1(bool allSensorsHealthy READ allSensorsHealthy NOTIFY allSensorsHealthyChanged) 1(bool requiresGpsFix READ requiresGpsFix NOTIFY requiresGpsFixChanged) 1(double loadProgress READ loadProgress NOTIFY loadProgressChanged) 1(bool initialConnectComplete READ isInitialConnectComplete NOTIFY initialConnectComplete) 1(bool orbitActive READ orbitActive NOTIFY orbitActiveChanged) 1(QGCMapCircle *orbitMapCircle READ orbitMapCircle CONSTANT) 1(bool flying READ flying NOTIFY flyingChanged) 1(bool landing READ landing NOTIFY landingChanged) 1(bool guidedMode READ guidedMode WRITE setGuidedMode NOTIFY guidedModeChanged) 1(QString gotoFlightMode READ gotoFlightMode CONSTANT) 1(bool haveMRSpeedLimits READ haveMRSpeedLimits NOTIFY haveMRSpeedLimChanged) 1(bool haveFWSpeedLimits READ haveFWSpeedLimits NOTIFY haveFWSpeedLimChanged) 1(ParameterManager *parameterManager READ parameterManager CONSTANT) 1(VehicleLinkManager *vehicleLinkManager READ vehicleLinkManager CONSTANT) 1(VehicleObjectAvoidance *objectAvoidance READ objectAvoidance CONSTANT) 1(Autotune *autotune READ autotune CONSTANT) 1(RemoteIDManager *remoteIDManager READ remoteIDManager CONSTANT) 1(FactGroup *vehicle READ vehicleFactGroup CONSTANT) 1(FactGroup *gps READ gpsFactGroup CONSTANT) 1(FactGroup *gps2 READ gps2FactGroup CONSTANT) 1(FactGroup *gpsAggregate READ gpsAggregateFactGroup CONSTANT) 1(FactGroup *wind READ windFactGroup CONSTANT) 1(FactGroup *vibration READ vibrationFactGroup CONSTANT) 1(FactGroup *temperature READ temperatureFactGroup CONSTANT) 1(FactGroup *clock READ clockFactGroup CONSTANT) 1(FactGroup *setpoint READ setpointFactGroup CONSTANT) 1(FactGroup *estimatorStatus READ estimatorStatusFactGroup CONSTANT) 1(FactGroup *terrain READ terrainFactGroup CONSTANT) 1(FactGroup *distanceSensors READ distanceSensorFactGroup CONSTANT) 1(FactGroup *localPosition READ localPositionFactGroup CONSTANT) 1(FactGroup *localPositionSetpoint READ localPositionSetpointFactGroup CONSTANT) 1(FactGroup *hygrometer READ hygrometerFactGroup CONSTANT) 1(FactGroup *generator READ generatorFactGroup CONSTANT) 1(FactGroup *efi READ efiFactGroup CONSTANT) 1(FactGroup *radioStatus READ radioStatusFactGroup CONSTANT) 1(Actuators *actuators READ actuators CONSTANT) 1(QmlObjectListModel *batteries READ batteries CONSTANT) 1(QmlObjectListModel *escs READ escs CONSTANT) 1(int firmwareMajorVersion READ firmwareMajorVersion NOTIFY firmwareVersionChanged) 1(int firmwareMinorVersion READ firmwareMinorVersion NOTIFY firmwareVersionChanged) 1(int firmwarePatchVersion READ firmwarePatchVersion NOTIFY firmwareVersionChanged) 1(int firmwareVersionType READ firmwareVersionType NOTIFY firmwareVersionChanged) 1(QString firmwareVersionTypeString READ firmwareVersionTypeString NOTIFY firmwareVersionChanged) 1(int firmwareCustomMajorVersion READ firmwareCustomMajorVersion NOTIFY firmwareCustomVersionChanged) 1(int firmwareCustomMinorVersion READ firmwareCustomMinorVersion NOTIFY firmwareCustomVersionChanged) 1(int firmwareCustomPatchVersion READ firmwareCustomPatchVersion NOTIFY firmwareCustomVersionChanged) 1(QString gitHash READ gitHash NOTIFY gitHashChanged) 1(quint64 vehicleUID READ vehicleUID NOTIFY vehicleUIDChanged) 1(QString vehicleUIDStr READ vehicleUIDStr NOTIFY vehicleUIDChanged) 1(bool mavlinkSigning READ mavlinkSigning NOTIFY mavlinkSigningChanged) 1(QString mavlinkSigningKeyName READ mavlinkSigningKeyName NOTIFY mavlinkSigningChanged) 1 void resetCounters()
< Combination of enabled and health
void virtualTabletJoystickValue (double roll, double pitch, double yaw, double thrust)
void guidedModeRTL (bool smartRTL)
Command vehicle to return to launch.
void guidedModeLand ()
Command vehicle to land at current location.
void guidedModeTakeoff (double altitudeRelative)
Command vehicle to takeoff from current location.
double minimumTakeoffAltitudeMeters ()
double maximumHorizontalSpeedMultirotorMetersSecond ()
double maximumEquivalentAirspeed ()
double minimumEquivalentAirspeed ()
bool guidedModeGotoLocation (const QGeoCoordinate &gotoCoord, double forwardFlightLoiterRadius=0.0f)
void guidedModeChangeAltitude (double altitudeChange, bool pauseVehicle)
void guidedModeChangeHeading (const QGeoCoordinate &headingCoord)
void guidedModeChangeGroundSpeedMetersSecond (double groundspeed)
void guidedModeChangeEquivalentAirspeedMetersSecond (double airspeed)
void guidedModeOrbit (const QGeoCoordinate &centerCoord, double radius, double amslAltitude)
void guidedModeROI (const QGeoCoordinate &centerCoord)
void stopGuidedModeROI ()
void pauseVehicle ()
void emergencyStop ()
Command vehicle to kill all motors no matter what state.
void abortLanding (double climbOutAltitude)
Command vehicle to abort landing.
void landingGearDeploy ()
Command vichecle to deploy landing gear.
void landingGearRetract ()
Command vichecle to retract landing gear.
void startTakeoff ()
void startMission ()
void setCurrentMissionSequence (int seq)
Alter the current mission item on the vehicle.
void rebootVehicle ()
Reboot vehicle.
void sendPlan (QString planFile)
void setEstimatorOrigin (const QGeoCoordinate &centerCoord)
int versionCompare (const QString &compare) const
Used to check if running current version is equal or higher than the one being compared.
int versionCompare (int major, int minor, int patch) const
void motorTest (int motor, int percent, int timeoutSecs, bool showError)
void setPIDTuningTelemetryMode (PIDTuningTelemetryMode mode)
void forceArm ()
void sendParamMapRC (const QString &paramName, double scale, double centerValue, int tuningID, double minValue, double maxValue)
Sends PARAM_MAP_RC message to vehicle.
void clearAllParamMapRC (void)
Clears all PARAM_MAP_RC settings from vehicle.
void closeVehicle ()
Removes the vehicle from the system.
void triggerSimpleCamera (void)
Trigger camera using MAV_CMD_DO_DIGICAM_CONTROL command.
void doSetHome (const QGeoCoordinate &coord)
Set home from flight map coordinate.
void sendSetupSigning (int keyIndex)
Send SETUP_SIGNING with the key at the given index in MAVLinkSigningKeys.
void sendDisableSigning ()
QVariant expandedToolbarIndicatorSource (const QString &indicatorName)
bool isInitialConnectComplete () const
QString gotoFlightMode () const
VehicleSupports * supports ()
bool hasGripper () const
bool haveMRSpeedLimits () const
bool haveFWSpeedLimits () const
QGeoCoordinate coordinate ()
QGeoCoordinate armedPosition ()
qreal getInitialGCSPressure () const
qreal getInitialGCSTemperature () const
void setInitialGCSPressure (qreal pressure)
void setInitialGCSTemperature (qreal temperature)
void updateFlightDistance (double distance)
void sendJoystickDataThreadSafe (float roll, float pitch, float yaw, float thrust, quint16 buttons, quint16 buttons2, float pitchExtension, float rollExtension, float aux1, float aux2, float aux3, float aux4, float aux5, float aux6)
int id () const
int compId () const
MAV_AUTOPILOT firmwareType () const
MAV_TYPE vehicleType () const
QGCMAVLink::VehicleClass_t vehicleClass (void) const
QString vehicleClassInternalName () const
bool sendMessageOnLinkThreadSafe (LinkInterface *link, mavlink_message_t message)
void sendMessageMultiple (mavlink_message_t message)
AutoPilotPlugin * autopilotPlugin ()
Provides access to AutoPilotPlugin for this vehicle.
FirmwarePlugin * firmwarePlugin ()
Provides access to the Firmware Plugin for this Vehicle.
QGeoCoordinate homePosition ()
bool armed () const
void setArmed (bool armed, bool showError)
void setArmedShowError (bool armed)
bool flightModeSetAvailable ()
QStringList flightModes ()
QString flightMode () const
void setFlightMode (const QString &flightMode)
bool airship () const
void pairRX (int rxType, int rxSubType)
bool fixedWing () const
bool multiRotor () const
bool vtol () const
bool rover () const
bool sub () const
bool spacecraft () const
void setGuidedMode (bool guidedMode)
QString prearmError () const
void setPrearmError (const QString &prearmError)
QmlObjectListModel * cameraTriggerPoints ()
void startMavlinkLog ()
void stopMavlinkLog ()
void requestDataStream (MAV_DATA_STREAM stream, uint16_t rate, bool sendMultiple=true)
void trackFirmwareVehicleTypeChanges (void)
void stopTrackingFirmwareVehicleTypeChanges (void)
float latitude ()
float longitude ()
bool px4Firmware () const
bool apmFirmware () const
bool genericFirmware () const
uint messagesReceived () const
uint messagesSent () const
uint messagesLost () const
bool flying () const
bool landing () const
bool guidedMode () const
bool inFwdFlight () const
bool vtolInFwdFlight () const
uint8_t baseMode () const
uint32_t customMode () const
uint32_t effectiveCustomMode () const
bool isOfflineEditingVehicle () const
int sensorsPresentBits () const
int sensorsEnabledBits () const
int sensorsHealthBits () const
int sensorsUnhealthyBits () const
QString missionFlightMode () const
QString pauseFlightMode () const
QString rtlFlightMode () const
QString smartRTLFlightMode () const
QString landFlightMode () const
QString takeControlFlightMode () const
QString followFlightMode () const
QString motorDetectionFlightMode () const
QString stabilizedFlightMode () const
double defaultCruiseSpeed () const
double defaultHoverSpeed () const
QString firmwareTypeString () const
QString vehicleTypeString () const
bool autoDisarm ()
bool orbitActive () const
QGCMapCircle * orbitMapCircle ()
bool readyToFlyAvailable () const
bool readyToFly () const
bool allSensorsHealthy () const
QObject * sysStatusSensorInfo ()
bool requiresGpsFix () const
bool hilMode () const
Actuators * actuators () const
bool mavlinkSigning () const
QString mavlinkSigningKeyName () const
void startCalibration (QGCMAVLink::CalibrationType calType)
void stopCalibration (bool showError)
void startUAVCANBusConfig (void)
void stopUAVCANBusConfig (void)
FactGroup * vehicleFactGroup ()
FactGroup * gpsFactGroup ()
FactGroup * gps2FactGroup ()
FactGroup * gpsAggregateFactGroup ()
FactGroup * windFactGroup ()
FactGroup * vibrationFactGroup ()
FactGroup * temperatureFactGroup ()
FactGroup * clockFactGroup ()
FactGroup * setpointFactGroup ()
FactGroup * distanceSensorFactGroup ()
FactGroup * localPositionFactGroup ()
FactGroup * localPositionSetpointFactGroup ()
FactGroup * estimatorStatusFactGroup ()
FactGroup * terrainFactGroup ()
FactGroup * hygrometerFactGroup ()
FactGroup * generatorFactGroup ()
FactGroup * efiFactGroup ()
FactGroup * radioStatusFactGroup ()
FactGroup * rpmFactGroup ()
QmlObjectListModel * batteries ()
QmlObjectListModel * escs ()
MissionManager * missionManager ()
GeoFenceManager * geoFenceManager ()
RallyPointManager * rallyPointManager ()
ParameterManager * parameterManager ()
ParameterManager * parameterManager () const
VehicleLinkManager * vehicleLinkManager ()
FTPManager * ftpManager ()
ComponentInformationManager * compInfoManager ()
VehicleObjectAvoidance * objectAvoidance ()
Autotune * autotune () const
RemoteIDManager * remoteIDManager ()
void sendMavCommand (int compId, MAV_CMD command, bool showError, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, float param5=0.0f, float param6=0.0f, float param7=0.0f)
void sendMavCommandDelayed (int compId, MAV_CMD command, bool showError, int milliseconds, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, float param5=0.0f, float param6=0.0f, float param7=0.0f)
void sendMavCommandInt (int compId, MAV_CMD command, MAV_FRAME frame, bool showError, float param1, float param2, float param3, float param4, double param5, double param6, float param7)
bool isMavCommandPending (int targetCompId, MAV_CMD command)
isMavCommandPending Query whether the specified MAV_CMD is in queue to be sent or has already been sent but whose reply has not yet been received and whose timeout has not yet expired.
void sendCommand (int compId, int command, bool showError, double param1=0.0, double param2=0.0, double param3=0.0, double param4=0.0, double param5=0.0, double param6=0.0, double param7=0.0)
Same as sendMavCommand but available from Qml.
void sendMavCommandWithHandler (const MavCmdAckHandlerInfo_t *ackHandlerInfo, int compId, MAV_CMD command, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, float param5=0.0f, float param6=0.0f, float param7=0.0f)
Sends the command and calls the callback with the result.
void sendMavCommandIntWithHandler (const MavCmdAckHandlerInfo_t *ackHandlerInfo, int compId, MAV_CMD command, MAV_FRAME frame, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, double param5=0.0f, double param6=0.0f, float param7=0.0f)
void sendMavCommandWithLambdaFallback (std::function< void()> lambda, int compId, MAV_CMD command, bool showError, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, float param5=0.0f, float param6=0.0f, float param7=0.0f)
void requestMessage (RequestMessageResultHandler resultHandler, void *resultHandlerData, int compId, int messageId, float param1=0.0f, float param2=0.0f, float param3=0.0f, float param4=0.0f, float param5=0.0f)
int firmwareMajorVersion () const
int firmwareMinorVersion () const
int firmwarePatchVersion () const
int firmwareVersionType () const
int firmwareCustomMajorVersion () const
int firmwareCustomMinorVersion () const
int firmwareCustomPatchVersion () const
int firmwareBoardVendorId () const
int firmwareBoardProductId () const
QString firmwareVersionTypeString () const
void setFirmwareVersion (int majorVersion, int minorVersion, int patchVersion, FIRMWARE_VERSION_TYPE versionType=FIRMWARE_VERSION_TYPE_OFFICIAL)
void setFirmwareCustomVersion (int majorVersion, int minorVersion, int patchVersion)
QString gitHash () const
quint64 vehicleUID () const
QString vehicleUIDStr ()
bool soloFirmware () const
void setSoloFirmware (bool soloFirmware)
int defaultComponentId () const
void setOfflineEditingDefaultComponentId (int defaultComponentId)
Sets the default component id for an offline editing vehicle.
int motorCount ()
bool coaxialMotors ()
bool xConfigMotors ()
class FirmwarePluginInstanceData * firmwarePluginInstanceData ()
void setFirmwarePluginInstanceData (FirmwarePluginInstanceData *firmwarePluginInstanceData)
QString vehicleImageOpaque () const
QString vehicleImageOutline () const
const QVariantList & toolIndicators ()
bool capabilitiesKnown () const
uint64_t capabilityBits () const
QString hobbsMeter ()
bool initialPlanRequestComplete () const
void forceInitialPlanRequestComplete ()
void _setFlying (bool flying)
void _setLanding (bool landing)
void _setHomePosition (QGeoCoordinate &homeCoord)
void prepareDelete ()
Vehicle is about to be deleted.
void deleteGimbalController ()
Delete gimbal controller, handy for RequestMessageTest.cc, otherwise gimbal controller message requests will mess with this test.
quint64 mavlinkSentCount () const
quint64 mavlinkReceivedCount () const
Calculated total number of messages sent to us.
quint64 mavlinkLossCount () const
Total number of sucessful messages received.
float mavlinkLossPercent () const
Total number of lost messages.
bool isROIEnabled () const
Running loss rate.
CheckList checkListState ()
void setCheckListState (CheckList cl)
double loadProgress () const
void setActuatorsMetadata (uint8_t compid, const QString &metadataJsonFileName)
GimbalController * gimbalController ()
int _findMavCommandListEntryIndex (int targetCompId, MAV_CMD command)
Test-only helper: forwards to MavCommandQueue::findEntryIndex.
int32_t getMessageRate (uint8_t compId, uint16_t msgId)
void setMessageRate (uint8_t compId, uint16_t msgId, int32_t rate)
void flashBootloader ()
void motorInterlock (bool enable)
Command vehicle to Enable/Disable Motor Interlock.
void startTimerRevertAllowTakeover ()
void requestOperatorControl (bool allowOverride, int requestTimeoutSecs=0)
uint32_t flowImageIndex () const
MAVLinkLogManager * mavlinkLogManager () const
HealthAndArmingCheckReport * healthAndArmingCheckReport ()
void setEventsMetadata (uint8_t compid, const QString &metadataJsonFileName)
Static Public Member Functions
static void showCommandAckError (const mavlink_command_ack_t &ack)
static QString mavCmdResultFailureCodeToString (MavCmdResultFailureCode_t failureCode)
static QString requestMessageResultHandlerFailureCodeToString (RequestMessageResultHandlerFailureCode_t failureCode)
Public Attributes
QMap< uint8_t, uint8_t > _lowestBatteryChargeStateAnnouncedMap
float _altitudeTuningOffset = qQNaN()
bool _multirotor_speed_limits_available = false
bool _fixed_wing_airspeed_limits_available = false
const QString _vehicleFactGroupName = QStringLiteral("vehicle")
const QString _gpsFactGroupName = QStringLiteral("gps")
const QString _gps2FactGroupName = QStringLiteral("gps2")
const QString _gpsAggregateFactGroupName = QStringLiteral("gpsAggregate")
const QString _windFactGroupName = QStringLiteral("wind")
const QString _vibrationFactGroupName = QStringLiteral("vibration")
const QString _temperatureFactGroupName = QStringLiteral("temperature")
const QString _clockFactGroupName = QStringLiteral("clock")
const QString _setpointFactGroupName = QStringLiteral("setpoint")
const QString _distanceSensorFactGroupName = QStringLiteral("distanceSensor")
const QString _localPositionFactGroupName = QStringLiteral("localPosition")
const QString _localPositionSetpointFactGroupName = QStringLiteral("localPositionSetpoint")
const QString _estimatorStatusFactGroupName = QStringLiteral("estimatorStatus")
const QString _terrainFactGroupName = QStringLiteral("terrain")
const QString _hygrometerFactGroupName = QStringLiteral("hygrometer")
const QString _generatorFactGroupName = QStringLiteral("generator")
const QString _efiFactGroupName = QStringLiteral("efi")
const QString _rpmFactGroupName = QStringLiteral("rpm")
const QString _radioStatusFactGroupName = QStringLiteral("radioStatus")
VehicleFactGroup * _vehicleFactGroup
VehicleGPSFactGroup * _gpsFactGroup = nullptr
VehicleGPS2FactGroup * _gps2FactGroup = nullptr
VehicleGPSAggregateFactGroup * _gpsAggregateFactGroup = nullptr
VehicleWindFactGroup * _windFactGroup = nullptr
VehicleVibrationFactGroup * _vibrationFactGroup = nullptr
VehicleTemperatureFactGroup * _temperatureFactGroup = nullptr
VehicleClockFactGroup * _clockFactGroup = nullptr
VehicleSetpointFactGroup * _setpointFactGroup = nullptr
VehicleDistanceSensorFactGroup * _distanceSensorFactGroup = nullptr
VehicleLocalPositionFactGroup * _localPositionFactGroup = nullptr
VehicleLocalPositionSetpointFactGroup * _localPositionSetpointFactGroup = nullptr
VehicleEstimatorStatusFactGroup * _estimatorStatusFactGroup = nullptr
VehicleHygrometerFactGroup * _hygrometerFactGroup = nullptr
VehicleGeneratorFactGroup * _generatorFactGroup = nullptr
VehicleEFIFactGroup * _efiFactGroup = nullptr
VehicleRPMFactGroup * _rpmFactGroup = nullptr
TerrainFactGroup * _terrainFactGroup = nullptr
RadioStatusFactGroup * _radioStatusFactGroup = nullptr
QVector< int > _servoOutputRawValues = QVector<int>(16, -1)
BatteryFactGroupListModel * _batteryFactGroupListModel = nullptr
EscStatusFactGroupListModel * _escStatusFactGroupListModel = nullptr
TerrainProtocolHandler * _terrainProtocolHandler = nullptr
MissionManager * _missionManager = nullptr
GeoFenceManager * _geoFenceManager = nullptr
RallyPointManager * _rallyPointManager = nullptr
VehicleLinkManager * _vehicleLinkManager = nullptr
FTPManager * _ftpManager = nullptr
InitialConnectStateMachine * _initialConnectStateMachine = nullptr
Actuators * _actuators = nullptr
RemoteIDManager * _remoteIDManager = nullptr
StandardModes * _standardModes = nullptr
TerrainQueryCoordinator * _terrainQueryCoordinator = nullptr
Static Public Attributes
static const MAV_AUTOPILOT MAV_AUTOPILOT_TRACK = MAV_AUTOPILOT_ENUM_END
static const MAV_TYPE MAV_TYPE_TRACK = MAV_TYPE_ENUM_END
static constexpr int _mavCommandMaxRetryCount = 3
static constexpr int kTestMavCommandAckTimeoutMs = 500
static constexpr int kTestMavCommandMaxWaitMs = kTestMavCommandAckTimeoutMs * _mavCommandMaxRetryCount * 2
Static Public Attributes inherited from VehicleTypes
static const int versionNotSetValue = -1
Friends
class InitialConnectStateMachine
class VehicleLinkManager
class FactGroupListModel
class GimbalController
Additional Inherited Members
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Protected Member Functions inherited from VehicleFactGroup
void _handleAttitude (Vehicle *vehicle, const mavlink_message_t &message)
void _handleAttitudeQuaternion (Vehicle *vehicle, const mavlink_message_t &message)
void _handleAltitude (const mavlink_message_t &message)
void _handleVfrHud (const mavlink_message_t &message)
void _handleRawImuTemp (const mavlink_message_t &message)
void _handleNavControllerOutput (const mavlink_message_t &message)
void _handleRangefinder (const mavlink_message_t &message)
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes inherited from VehicleFactGroup
Fact _rollFact = Fact(0, QStringLiteral("roll"), FactMetaData::valueTypeDouble)
Fact _pitchFact = Fact(0, QStringLiteral("pitch"), FactMetaData::valueTypeDouble)
Fact _headingFact = Fact(0, QStringLiteral("heading"), FactMetaData::valueTypeDouble)
Fact _rollRateFact = Fact(0, QStringLiteral("rollRate"), FactMetaData::valueTypeDouble)
Fact _pitchRateFact = Fact(0, QStringLiteral("pitchRate"), FactMetaData::valueTypeDouble)
Fact _yawRateFact = Fact(0, QStringLiteral("yawRate"), FactMetaData::valueTypeDouble)
Fact _groundSpeedFact = Fact(0, QStringLiteral("groundSpeed"), FactMetaData::valueTypeDouble)
Fact _airSpeedFact = Fact(0, QStringLiteral("airSpeed"), FactMetaData::valueTypeDouble)
Fact _airSpeedSetpointFact = Fact(0, QStringLiteral("airSpeedSetpoint"), FactMetaData::valueTypeDouble)
Fact _climbRateFact = Fact(0, QStringLiteral("climbRate"), FactMetaData::valueTypeDouble)
Fact _altitudeRelativeFact = Fact(0, QStringLiteral("altitudeRelative"), FactMetaData::valueTypeDouble)
Fact _altitudeAMSLFact = Fact(0, QStringLiteral("altitudeAMSL"), FactMetaData::valueTypeDouble)
Fact _altitudeAboveTerrFact = Fact(0, QStringLiteral("altitudeAboveTerr"), FactMetaData::valueTypeDouble)
Fact _altitudeTuningFact = Fact(0, QStringLiteral("altitudeTuning"), FactMetaData::valueTypeDouble)
Fact _altitudeTuningSetpointFact = Fact(0, QStringLiteral("altitudeTuningSetpoint"), FactMetaData::valueTypeDouble)
Fact _xTrackErrorFact = Fact(0, QStringLiteral("xTrackError"), FactMetaData::valueTypeDouble)
Fact _rangeFinderDistFact = Fact(0, QStringLiteral("rangeFinderDist"), FactMetaData::valueTypeFloat)
Fact _flightDistanceFact = Fact(0, QStringLiteral("flightDistance"), FactMetaData::valueTypeDouble)
Fact _flightTimeFact = Fact(0, QStringLiteral("flightTime"), FactMetaData::valueTypeElapsedTimeInSeconds)
Fact _distanceToHomeFact = Fact(0, QStringLiteral("distanceToHome"), FactMetaData::valueTypeDouble)
Fact _timeToHomeFact = Fact(0, QStringLiteral("timeToHome"), FactMetaData::valueTypeDouble)
Fact _missionItemIndexFact = Fact(0, QStringLiteral("missionItemIndex"), FactMetaData::valueTypeUint16)
Fact _headingToNextWPFact = Fact(0, QStringLiteral("headingToNextWP"), FactMetaData::valueTypeDouble)
Fact _distanceToNextWPFact = Fact(0, QStringLiteral("distanceToNextWP"), FactMetaData::valueTypeDouble)
Fact _headingToHomeFact = Fact(0, QStringLiteral("headingToHome"), FactMetaData::valueTypeDouble)
Fact _headingFromHomeFact = Fact(0, QStringLiteral("headingFromHome"),FactMetaData::valueTypeDouble)
Fact _headingFromGCSFact = Fact(0, QStringLiteral("headingFromGCS"),FactMetaData::valueTypeDouble)
Fact _distanceToGCSFact = Fact(0, QStringLiteral("distanceToGCS"), FactMetaData::valueTypeDouble)
Fact _hobbsFact = Fact(0, QStringLiteral("hobbs"), FactMetaData::valueTypeString)
Fact _throttlePctFact = Fact(0, QStringLiteral("throttlePct"), FactMetaData::valueTypeUint16)
Fact _imuTempFact = Fact(0, QStringLiteral("imuTemp"), FactMetaData::valueTypeInt16)
Fact _rcRSSIFact = Fact(0, QStringLiteral("rcRSSI"), FactMetaData::valueTypeUint8)
float _altitudeTuningOffset = qQNaN()
bool _altitudeMessageAvailable = false
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Definition at line 81 of file Vehicle.h.
Member Enumeration Documentation
CheckList
enum Vehicle::CheckList
Enumerator
CheckListNotSetup
CheckListPassed
CheckListFailed
Definition at line 133 of file Vehicle.h.
PIDTuningTelemetryMode
enum Vehicle::PIDTuningTelemetryMode
Enumerator
ModeDisabled
ModeRateAndAttitude
ModeVelocityAndPosition
ModeAltitudeAndAirspeed
Definition at line 367 of file Vehicle.h.
Constructor & Destructor Documentation
Vehicle() [1/2]
Vehicle::Vehicle (LinkInterface * link, int vehicleId, int defaultComponentId, MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType, QObject * parent = nullptr)
Definition at line 101 of file Vehicle.cc.
References _initialConnectStateMachine, MultiVehicleManager::activeVehicleChanged(), FirmwarePlugin::adjustMetaData(), armedChanged(), FirmwarePlugin::autopilotPlugin(), flightModeChanged(), flying(), flyingChanged(), FirmwarePlugin::initializeVehicle(), MAVLinkProtocol::instance(), QGCDeviceInfo::QGCPressure::instance(), VideoSettings::lowLatencyMode(), MAVLinkProtocol::mavlinkMessageStatus(), MAVLinkProtocol::messageReceived(), MultiVehicleManager::parameterReadyVehicleAvailableChanged(), QGC::runningUnitTests(), setInitialGCSPressure(), setInitialGCSTemperature(), InitialConnectStateMachine::start(), sub(), vehicleType(), VideoSettings::videoDisabled, VideoSettings::videoSource(), and VideoSettings::videoSourceUDPH264.
Vehicle() [2/2]
Vehicle::Vehicle (MAV_AUTOPILOT firmwareType, MAV_TYPE vehicleType, QObject * parent = nullptr)
Definition at line 178 of file Vehicle.cc.
References _offlineFirmwareTypeSettingChanged(), FirmwarePlugin::initializeVehicle(), MAV_AUTOPILOT_TRACK, Fact::rawValueChanged(), and trackFirmwareVehicleTypeChanges().
~Vehicle()
Vehicle::~Vehicle ()
Definition at line 387 of file Vehicle.cc.
References _missionManager, and MavCommandQueue::stop().
Member Function Documentation
_findMavCommandListEntryIndex()
int Vehicle::_findMavCommandListEntryIndex (int targetCompId, MAV_CMD command)
Test-only helper: forwards to MavCommandQueue::findEntryIndex.
Definition at line 2188 of file Vehicle.cc.
References MavCommandQueue::findEntryIndex().
_offlineFirmwareTypeSettingChanged
void Vehicle::_offlineFirmwareTypeSettingChanged (QVariant varFirmwareType) slot
Definition at line 473 of file Vehicle.cc.
References capabilityBitsChanged(), FirmwarePluginManager::firmwarePluginForAutopilot(), firmwareTypeChanged(), and FirmwarePluginManager::instance().
Referenced by stopTrackingFirmwareVehicleTypeChanges(), trackFirmwareVehicleTypeChanges(), and Vehicle().
_offlineVehicleTypeSettingChanged
void Vehicle::_offlineVehicleTypeSettingChanged (QVariant varVehicleType) slot
Definition at line 486 of file Vehicle.cc.
References vehicleTypeChanged().
Referenced by stopTrackingFirmwareVehicleTypeChanges(), and trackFirmwareVehicleTypeChanges().
_setFlying()
void Vehicle::_setFlying (bool flying)
Definition at line 1800 of file Vehicle.cc.
References flying(), and flyingChanged().
_setHomePosition()
void Vehicle::_setHomePosition (QGeoCoordinate & homeCoord)
Definition at line 1182 of file Vehicle.cc.
References homePositionChanged().
Referenced by PlanManager::_handleMissionItem().
_setLanding()
void Vehicle::_setLanding (bool landing)
Definition at line 1808 of file Vehicle.cc.
References armed(), landing(), and landingChanged().
abortLanding()
void Vehicle::abortLanding (double climbOutAltitude)
Command vehicle to abort landing.
Definition at line 2049 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
actuators()
Actuators * Vehicle::actuators () const inline
Definition at line 535 of file Vehicle.h.
References _actuators.
Referenced by PX4AutoPilotPlugin::vehicleComponents().
airship()
bool Vehicle::airship () const
Definition at line 1726 of file Vehicle.cc.
References QGCMAVLink::isAirship(), and vehicleType().
Referenced by SensorsComponent::SensorsComponent(), SensorsComponent::setupComplete(), and SensorsComponent::summaryQmlSource().
allSensorsHealthy()
bool Vehicle::allSensorsHealthy () const inline
Definition at line 531 of file Vehicle.h.
allSensorsHealthyChanged
void Vehicle::allSensorsHealthyChanged (bool allSensorsHealthy) signal
apmFirmware()
bool Vehicle::apmFirmware () const inline
Definition at line 493 of file Vehicle.h.
Referenced by LandingComplexItem::_createDoLandStartItem(), PlanManager::_handleMissionAck(), PlanManager::_handleMissionItem(), LandingComplexItem::_init(), LandingComplexItem::_scanForItem(), flashBootloader(), genericFirmware(), motorInterlock(), and GeoFenceController::paramCircularFence().
armed()
bool Vehicle::armed () const inline
Definition at line 447 of file Vehicle.h.
Referenced by FirmwarePlugin::_armVehicleAndValidate(), _setLanding(), MissionController::sendToVehiclePreCheck(), setArmed(), setArmedShowError(), APMFirmwarePlugin::startMission(), and APMFirmwarePlugin::startTakeoff().
armedChanged
void Vehicle::armedChanged (bool armed) signal
Referenced by Vehicle().
armedPosition()
QGeoCoordinate Vehicle::armedPosition () inline
Definition at line 411 of file Vehicle.h.
armedPositionChanged
void Vehicle::armedPositionChanged () signal
autoDisarm()
bool Vehicle::autoDisarm ()
Definition at line 2607 of file Vehicle.cc.
References FirmwarePlugin::autoDisarmParameter(), and ParameterManager::defaultComponentId.
autoDisarmChanged
void Vehicle::autoDisarmChanged () signal
autopilotPlugin()
AutoPilotPlugin * Vehicle::autopilotPlugin () inline
Provides access to AutoPilotPlugin for this vehicle.
Definition at line 439 of file Vehicle.h.
autotune()
Autotune * Vehicle::autotune () const inline
Definition at line 577 of file Vehicle.h.
baseMode()
uint8_t Vehicle::baseMode () const inline
Definition at line 503 of file Vehicle.h.
batteries()
QmlObjectListModel * Vehicle::batteries ()
Definition at line 429 of file Vehicle.cc.
References _batteryFactGroupListModel.
cameraManagerChanged
void Vehicle::cameraManagerChanged () signal
cameraTriggerPoints()
QmlObjectListModel * Vehicle::cameraTriggerPoints ()
Definition at line 433 of file Vehicle.cc.
capabilitiesKnown()
bool Vehicle::capabilitiesKnown () const inline
Definition at line 694 of file Vehicle.h.
capabilitiesKnownChanged
void Vehicle::capabilitiesKnownChanged (bool capabilitiesKnown) signal
capabilityBits()
uint64_t Vehicle::capabilityBits () const inline
Definition at line 695 of file Vehicle.h.
Referenced by PX4FirmwarePlugin::guidedModeGotoLocation(), guidedModeOrbit(), TerrainQueryCoordinator::sendROICommand(), stopGuidedModeROI(), GeoFenceManager::supported(), RallyPointManager::supported(), GeoFenceController::supported(), and RallyPointController::supported().
capabilityBitsChanged
void Vehicle::capabilityBitsChanged (uint64_t capabilityBits) signal
Referenced by _offlineFirmwareTypeSettingChanged().
checkListState()
CheckList Vehicle::checkListState () inline
Definition at line 722 of file Vehicle.h.
checkListStateChanged
void Vehicle::checkListStateChanged () signal
Referenced by setCheckListState().
clearAllParamMapRC()
void Vehicle::clearAllParamMapRC (void)
Clears all PARAM_MAP_RC settings from vehicle.
Definition at line 2962 of file Vehicle.cc.
References MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
clockFactGroup()
FactGroup * Vehicle::clockFactGroup ()
Definition at line 416 of file Vehicle.cc.
References _clockFactGroup.
closeVehicle()
void Vehicle::closeVehicle ()
Removes the vehicle from the system.
Definition at line 434 of file Vehicle.cc.
References _vehicleLinkManager, and VehicleLinkManager::closeVehicle().
coaxialMotors()
bool Vehicle::coaxialMotors ()
Returns
true: Motors are coaxial like an X8 config, false: Quadcopter for example
Definition at line 1413 of file Vehicle.cc.
References FirmwarePlugin::multiRotorCoaxialMotors().
compId()
int Vehicle::compId () const inline
Definition at line 424 of file Vehicle.h.
Referenced by VehicleFactGroup::_handleAttitude(), VehicleFactGroup::_handleAttitudeQuaternion(), VehicleObjectAvoidance::enabled(), getMessageRate(), RemoteIDManager::RemoteIDManager(), RequestMessageCoordinator::requestMessage(), requestMessage(), sendCommand(), sendMavCommand(), sendMavCommandDelayed(), sendMavCommandInt(), sendMavCommandIntWithHandler(), sendMavCommandWithHandler(), sendMavCommandWithLambdaFallback(), setMessageRate(), VehicleObjectAvoidance::stop(), and PX4AutoPilotPlugin::vehicleComponents().
compInfoManager()
ComponentInformationManager * Vehicle::compInfoManager () inline
Definition at line 575 of file Vehicle.h.
CONSTANT()
int id READ id Vehicle::CONSTANT (AutoPilotPlugin *autopilotPlugin MEMBER _autopilotPlugin CONSTANT)
< Combination of enabled and health
< true: readyToFly signalling is available on this vehicle < Vehicle is flying < Vehicle is in landing pattern (DO_LAND_START) < Vehicle is in Guided mode and can respond to guided commands < Flight mode vehicle is in while performing goto Resets link status counters
coordinate()
QGeoCoordinate Vehicle::coordinate () inline
Definition at line 410 of file Vehicle.h.
Referenced by APMFirmwarePlugin::guidedModeChangeHeading(), PX4FirmwarePlugin::guidedModeChangeHeading(), guidedModeGotoLocation(), and TerrainQueryCoordinator::updateAltAboveTerrain().
coordinateChanged
void Vehicle::coordinateChanged (QGeoCoordinate coordinate) signal
Referenced by TrajectoryPoints::start(), and TrajectoryPoints::stop().
currentConfigChanged
void Vehicle::currentConfigChanged () signal
customMode()
uint32_t Vehicle::customMode () const inline
Definition at line 504 of file Vehicle.h.
defaultComponentId()
int Vehicle::defaultComponentId () const inline
Definition at line 668 of file Vehicle.h.
Referenced by PX4FirmwarePlugin::_changeAltAfterPause(), FactPanelController::_reportMissingParameter(), abortLanding(), OnboardLogController::eraseAll(), flashBootloader(), APMFirmwarePlugin::guidedModeChangeAltitude(), PX4FirmwarePlugin::guidedModeChangeAltitude(), APMFirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), PX4FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), PX4FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), APMFirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), APMFirmwarePlugin::guidedModeChangeHeading(), PX4FirmwarePlugin::guidedModeChangeHeading(), APMFirmwarePlugin::guidedModeGotoLocation(), PX4FirmwarePlugin::guidedModeGotoLocation(), guidedModeOrbit(), PX4FirmwarePlugin::guidedModeTakeoff(), landingGearDeploy(), landingGearRetract(), motorInterlock(), PX4FirmwarePlugin::pauseVehicle(), SensorsComponentController::resetFactoryParameters(), sendDisableSigning(), TerrainQueryCoordinator::sendROICommand(), sendSetupSigning(), setCurrentMissionSequence(), setFlightMode(), setOfflineEditingDefaultComponentId(), startCalibration(), APMFirmwarePlugin::startMission(), startUAVCANBusConfig(), stopCalibration(), stopGuidedModeROI(), stopUAVCANBusConfig(), and MissionManager::writeArduPilotGuidedMissionItem().
defaultCruiseSpeed()
double Vehicle::defaultCruiseSpeed () const inline
Definition at line 522 of file Vehicle.h.
Referenced by MissionFlightStatusCalculator::reset(), MissionController::save(), and SpeedSection::SpeedSection().
defaultCruiseSpeedChanged
void Vehicle::defaultCruiseSpeedChanged (double cruiseSpeed) signal
defaultHoverSpeed()
double Vehicle::defaultHoverSpeed () const inline
Definition at line 523 of file Vehicle.h.
Referenced by MissionFlightStatusCalculator::reset(), MissionController::save(), and SpeedSection::SpeedSection().
defaultHoverSpeedChanged
void Vehicle::defaultHoverSpeedChanged (double hoverSpeed) signal
deleteGimbalController()
void Vehicle::deleteGimbalController ()
Delete gimbal controller, handy for RequestMessageTest.cc, otherwise gimbal controller message requests will mess with this test.
distanceSensorFactGroup()
FactGroup * Vehicle::distanceSensorFactGroup ()
Definition at line 418 of file Vehicle.cc.
References _distanceSensorFactGroup.
doSetHome()
void Vehicle::doSetHome (const QGeoCoordinate & coord)
Set home from flight map coordinate.
Definition at line 2874 of file Vehicle.cc.
References _terrainQueryCoordinator, and TerrainQueryCoordinator::doSetHomeWithTerrain().
effectiveCustomMode()
uint32_t Vehicle::effectiveCustomMode () const inline
Custom mode used for health/arming-check mode-group lookups: prefers the user-intention mode reported via CURRENT_MODE, falling back to HEARTBEAT.
Definition at line 507 of file Vehicle.h.
efiFactGroup()
FactGroup * Vehicle::efiFactGroup ()
Definition at line 425 of file Vehicle.cc.
References _efiFactGroup.
emergencyStop()
void Vehicle::emergencyStop ()
Command vehicle to kill all motors no matter what state.
Definition at line 2074 of file Vehicle.cc.
References sendMavCommand().
escs()
QmlObjectListModel * Vehicle::escs ()
Definition at line 430 of file Vehicle.cc.
References _escStatusFactGroupListModel.
estimatorStatusFactGroup()
FactGroup * Vehicle::estimatorStatusFactGroup ()
Definition at line 421 of file Vehicle.cc.
References _estimatorStatusFactGroup.
expandedToolbarIndicatorSource()
QVariant Vehicle::expandedToolbarIndicatorSource (const QString & indicatorName)
Definition at line 3258 of file Vehicle.cc.
References FirmwarePlugin::expandedToolbarIndicatorSource().
firmwareBoardProductId()
int Vehicle::firmwareBoardProductId () const inline
Definition at line 655 of file Vehicle.h.
firmwareBoardVendorId()
int Vehicle::firmwareBoardVendorId () const inline
Definition at line 654 of file Vehicle.h.
firmwareCustomMajorVersion()
int Vehicle::firmwareCustomMajorVersion () const inline
Definition at line 651 of file Vehicle.h.
firmwareCustomMinorVersion()
int Vehicle::firmwareCustomMinorVersion () const inline
Definition at line 652 of file Vehicle.h.
firmwareCustomPatchVersion()
int Vehicle::firmwareCustomPatchVersion () const inline
Definition at line 653 of file Vehicle.h.
firmwareCustomVersionChanged
void Vehicle::firmwareCustomVersionChanged () signal
Referenced by setFirmwareCustomVersion().
firmwareMajorVersion()
int Vehicle::firmwareMajorVersion () const inline
Definition at line 647 of file Vehicle.h.
Referenced by APMFirmwarePlugin::_internalParameterMetaDataFile(), FirmwarePlugin::_versionFileDownloadFinished(), SensorsComponent::SensorsComponent(), SensorsComponent::setupComplete(), FirmwarePlugin::versionCompare(), and ParameterManager::writeParametersToStream().
firmwareMinorVersion()
int Vehicle::firmwareMinorVersion () const inline
Definition at line 648 of file Vehicle.h.
Referenced by APMFirmwarePlugin::_internalParameterMetaDataFile(), FirmwarePlugin::_versionFileDownloadFinished(), SensorsComponent::SensorsComponent(), SensorsComponent::setupComplete(), FirmwarePlugin::versionCompare(), and ParameterManager::writeParametersToStream().
firmwarePatchVersion()
int Vehicle::firmwarePatchVersion () const inline
Definition at line 649 of file Vehicle.h.
Referenced by FirmwarePlugin::_versionFileDownloadFinished(), FirmwarePlugin::versionCompare(), and ParameterManager::writeParametersToStream().
firmwarePlugin()
FirmwarePlugin * Vehicle::firmwarePlugin () inline
Provides access to the Firmware Plugin for this Vehicle.
Definition at line 442 of file Vehicle.h.
Referenced by PlanManager::_handleMissionItem(), CameraSection::cameraModeSupported(), VehicleSupports::changeHeading(), MissionController::currentMissionIndex(), MissionManager::generateResumeMission(), StandardModes::gotMessage(), VehicleSupports::guidedMode(), VehicleSupports::guidedTakeoffWithAltitude(), VehicleSupports::guidedTakeoffWithoutAltitude(), MissionController::insertCancelROIMissionItem(), MissionController::insertROIMissionItem(), VehicleSupports::jsButton(), VehicleSupports::motorInterference(), VehicleSupports::negativeThrust(), VehicleSupports::orbitMode(), VehicleSupports::pauseVehicle(), VehicleSupports::radio(), MissionFlightStatusCalculator::reset(), MissionController::resumeMission(), MissionController::resumeMissionIndex(), VehicleSupports::roiMode(), MAVLinkEventManager::setMetadata(), VehicleSupports::smartRTL(), VehicleSupports::takeoffMissionCommand(), APMAutoPilotPlugin::vehicleComponents(), and PlanManager::writeMissionItems().
firmwarePluginInstanceData()
class FirmwarePluginInstanceData * Vehicle::firmwarePluginInstanceData () inline
Returns
Firmware plugin instance data associated with this Vehicle
Definition at line 683 of file Vehicle.h.
Referenced by _MAV_CMD_DO_REPOSITION_ResultHandler(), APMFirmwarePlugin::adjustIncomingMavlinkMessage(), APMFirmwarePlugin::guidedModeGotoLocation(), APMFirmwarePlugin::initializeStreamRates(), MavCommandQueue::sendCommandWithLambdaFallback(), and setFirmwarePluginInstanceData().
firmwareType()
MAV_AUTOPILOT Vehicle::firmwareType () const inline
Definition at line 425 of file Vehicle.h.
Referenced by MissionController::save(), and MissionController::sendToVehiclePreCheck().
firmwareTypeChanged
void Vehicle::firmwareTypeChanged () signal
Referenced by _offlineFirmwareTypeSettingChanged(), and VehicleSupports::VehicleSupports().
firmwareTypeString()
QString Vehicle::firmwareTypeString () const
Definition at line 504 of file Vehicle.cc.
References QGCMAVLink::firmwareClassToString().
Referenced by ParameterManager::writeParametersToStream().
firmwareVersionChanged
void Vehicle::firmwareVersionChanged () signal
Referenced by setFirmwareVersion().
firmwareVersionType()
int Vehicle::firmwareVersionType () const inline
Definition at line 650 of file Vehicle.h.
Referenced by FirmwarePlugin::_versionFileDownloadFinished().
firmwareVersionTypeString()
QString Vehicle::firmwareVersionTypeString () const
Definition at line 2282 of file Vehicle.cc.
References QGCMAVLink::firmwareVersionTypeToString().
Referenced by ParameterManager::writeParametersToStream().
fixedWing()
bool Vehicle::fixedWing () const
Definition at line 1731 of file Vehicle.cc.
References QGCMAVLink::isFixedWing(), and vehicleType().
Referenced by PX4FirmwarePlugin::flightModes(), inFwdFlight(), MissionController::insertLandItem(), APMFirmwarePlugin::isCapable(), PX4FirmwarePlugin::isCapable(), SpeedSection::scanForSection(), SensorsComponent::SensorsComponent(), SpeedSection::setAvailable(), SensorsComponent::setupComplete(), SimpleMissionItem::showLoiterRadius(), APMFirmwarePlugin::startMission(), and SensorsComponent::summaryQmlSource().
flashBootloader()
void Vehicle::flashBootloader ()
Definition at line 3277 of file Vehicle.cc.
References apmFirmware(), defaultComponentId(), and sendMavCommand().
flightMode()
QString Vehicle::flightMode () const
Definition at line 1462 of file Vehicle.cc.
References FirmwarePlugin::flightMode().
Referenced by FirmwarePlugin::_setFlightModeAndValidate(), APMFirmwarePlugin::isGuidedMode(), PX4FirmwarePlugin::isGuidedMode(), MissionController::sendToVehiclePreCheck(), and setFlightMode().
flightModeChanged
void Vehicle::flightModeChanged (const QString & flightMode) signal
Referenced by MAVLinkEventManager::MAVLinkEventManager(), and Vehicle().
flightModes()
QStringList Vehicle::flightModes ()
Definition at line 1456 of file Vehicle.cc.
References flightModes(), and FirmwarePlugin::flightModes().
Referenced by flightModes().
flightModesChanged
void Vehicle::flightModesChanged () signal
flightModeSetAvailable()
bool Vehicle::flightModeSetAvailable ()
Definition at line 1451 of file Vehicle.cc.
References FirmwarePlugin::isCapable(), and FirmwarePlugin::SetFlightModeCapability.
flowImageIndex()
uint32_t Vehicle::flowImageIndex () const
Definition at line 3477 of file Vehicle.cc.
References ImageProtocolManager::flowImageIndex().
flowImageIndexChanged
void Vehicle::flowImageIndexChanged () signal
flying()
bool Vehicle::flying () const inline
Definition at line 498 of file Vehicle.h.
Referenced by _setFlying(), APMFirmwarePlugin::startCompensatingBaro(), APMFirmwarePlugin::startMission(), APMFirmwarePlugin::startTakeoff(), and Vehicle().
flyingChanged
void Vehicle::flyingChanged (bool flying) signal
Referenced by _setFlying(), and Vehicle().
followFlightMode()
QString Vehicle::followFlightMode () const
Definition at line 2556 of file Vehicle.cc.
References FirmwarePlugin::followFlightMode().
forceArm()
void Vehicle::forceArm (void)
Definition at line 1442 of file Vehicle.cc.
References sendMavCommand().
forceInitialPlanRequestComplete()
void Vehicle::forceInitialPlanRequestComplete ()
Definition at line 2700 of file Vehicle.cc.
References initialPlanRequestCompleteChanged().
formattedMessagesChanged
void Vehicle::formattedMessagesChanged () signal
ftpManager()
FTPManager * Vehicle::ftpManager () inline
Definition at line 574 of file Vehicle.h.
References _ftpManager.
gcsControlStatusChanged
void Vehicle::gcsControlStatusChanged () signal
generatorFactGroup()
FactGroup * Vehicle::generatorFactGroup ()
Definition at line 424 of file Vehicle.cc.
References _generatorFactGroup.
genericFirmware()
bool Vehicle::genericFirmware () const inline
Definition at line 494 of file Vehicle.h.
References apmFirmware(), and px4Firmware().
geoFenceManager()
GeoFenceManager * Vehicle::geoFenceManager () inline
Definition at line 569 of file Vehicle.h.
References _geoFenceManager.
getInitialGCSPressure()
qreal Vehicle::getInitialGCSPressure () const inline
Definition at line 413 of file Vehicle.h.
Referenced by APMFirmwarePlugin::startCompensatingBaro().
getInitialGCSTemperature()
qreal Vehicle::getInitialGCSTemperature () const inline
Definition at line 414 of file Vehicle.h.
Referenced by APMFirmwarePlugin::startCompensatingBaro().
getMessageRate()
int32_t Vehicle::getMessageRate (uint8_t compId, uint16_t msgId)
Definition at line 3248 of file Vehicle.cc.
References compId(), and MessageIntervalManager::getMessageRate().
gimbalController()
GimbalController * Vehicle::gimbalController () inline
Definition at line 729 of file Vehicle.h.
gitHash()
QString Vehicle::gitHash () const inline
Definition at line 661 of file Vehicle.h.
Referenced by ParameterManager::writeParametersToStream().
gitHashChanged
void Vehicle::gitHashChanged (QString hash) signal
gotoFlightMode()
QString Vehicle::gotoFlightMode () const
Definition at line 1816 of file Vehicle.cc.
References FirmwarePlugin::gotoFlightMode().
gps2FactGroup()
FactGroup * Vehicle::gps2FactGroup ()
Definition at line 411 of file Vehicle.cc.
References _gps2FactGroup.
gpsAggregateFactGroup()
FactGroup * Vehicle::gpsAggregateFactGroup ()
Definition at line 412 of file Vehicle.cc.
References _gpsAggregateFactGroup.
gpsFactGroup()
FactGroup * Vehicle::gpsFactGroup ()
Definition at line 410 of file Vehicle.cc.
References _gpsFactGroup.
guidedMode()
bool Vehicle::guidedMode () const
Definition at line 2058 of file Vehicle.cc.
References FirmwarePlugin::isGuidedMode().
Referenced by setGuidedMode().
guidedModeChangeAltitude()
void Vehicle::guidedModeChangeAltitude (double altitudeChange, bool pauseVehicle)
Command vehicle to change altitude
Parameters
altitudeChange If > 0, go up by amount specified, if < 0, go down by amount specified
pauseVehicle true: pause vehicle prior to altitude change
Definition at line 1907 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeChangeAltitude(), pauseVehicle(), and QGC::showAppMessage().
guidedModeChanged
void Vehicle::guidedModeChanged (bool guidedMode) signal
guidedModeChangeEquivalentAirspeedMetersSecond()
void Vehicle::guidedModeChangeEquivalentAirspeedMetersSecond (double airspeed)
Command vehicle to change equivalent airspeed
Parameters
airspeed Target equivalent airspeed
Definition at line 1927 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), and QGC::showAppMessage().
guidedModeChangeGroundSpeedMetersSecond()
void Vehicle::guidedModeChangeGroundSpeedMetersSecond (double groundspeed)
Command vehicle to change groundspeed
Parameters
groundspeed Target horizontal groundspeed
Definition at line 1917 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), and QGC::showAppMessage().
guidedModeChangeHeading()
void Vehicle::guidedModeChangeHeading (const QGeoCoordinate & headingCoord)
Command vehicle to change yaw
Parameters
coordinate to rotate towards
Definition at line 2030 of file Vehicle.cc.
References VehicleSupports::changeHeading(), FirmwarePlugin::guidedModeChangeHeading(), and QGC::showAppMessage().
guidedModeGotoLocation()
bool Vehicle::guidedModeGotoLocation (const QGeoCoordinate & gotoCoord, double forwardFlightLoiterRadius = 0.0f)
Command vehicle to move to specified location (altitude is ignored)
Returns
true: goto command accepted, false: goto failed
Definition at line 1886 of file Vehicle.cc.
References FactMetaData::appSettingsHorizontalDistanceUnitsString(), coordinate(), guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeGotoLocation(), FlyViewSettings::maxGoToLocationDistance(), FactMetaData::metersToAppSettingsHorizontalDistanceUnits(), and QGC::showAppMessage().
guidedModeLand()
void Vehicle::guidedModeLand ()
Command vehicle to land at current location.
Definition at line 1830 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeLand(), and QGC::showAppMessage().
guidedModeOrbit()
void Vehicle::guidedModeOrbit (const QGeoCoordinate & centerCoord, double radius, double amslAltitude)
Command vehicle to orbit given center point
Parameters
centerCoord Orbit around this point
radius Distance from vehicle to centerCoord
amslAltitude Desired vehicle altitude
Definition at line 1936 of file Vehicle.cc.
References capabilityBits(), defaultComponentId(), VehicleSupports::orbitMode(), sendMavCommand(), sendMavCommandInt(), and QGC::showAppMessage().
guidedModeROI()
void Vehicle::guidedModeROI (const QGeoCoordinate & centerCoord)
Command vehicle to keep given point as ROI
Parameters
centerCoord ROI coordinates
Definition at line 1968 of file Vehicle.cc.
References _terrainQueryCoordinator, px4Firmware(), roiCoordChanged(), VehicleSupports::roiMode(), TerrainQueryCoordinator::roiWithTerrain(), TerrainQueryCoordinator::sendROICommand(), and QGC::showAppMessage().
guidedModeRTL()
void Vehicle::guidedModeRTL (bool smartRTL)
Command vehicle to return to launch.
Definition at line 1821 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeRTL(), and QGC::showAppMessage().
guidedModeTakeoff()
void Vehicle::guidedModeTakeoff (double altitudeRelative)
Command vehicle to takeoff from current location.
Definition at line 1839 of file Vehicle.cc.
References guided_mode_not_supported_by_vehicle, VehicleSupports::guidedMode(), FirmwarePlugin::guidedModeTakeoff(), and QGC::showAppMessage().
hasGripper()
bool Vehicle::hasGripper () const
Definition at line 1870 of file Vehicle.cc.
References FirmwarePlugin::hasGripper().
hasGripperChanged
void Vehicle::hasGripperChanged () signal
haveFWSpeedLimChanged
void Vehicle::haveFWSpeedLimChanged () signal
haveFWSpeedLimits()
bool Vehicle::haveFWSpeedLimits () const inline
Definition at line 406 of file Vehicle.h.
References _fixed_wing_airspeed_limits_available.
haveMRSpeedLimChanged
void Vehicle::haveMRSpeedLimChanged () signal
haveMRSpeedLimits()
bool Vehicle::haveMRSpeedLimits () const inline
Definition at line 405 of file Vehicle.h.
References _multirotor_speed_limits_available.
healthAndArmingCheckReport()
HealthAndArmingCheckReport * Vehicle::healthAndArmingCheckReport ()
Definition at line 3542 of file Vehicle.cc.
hilMode()
bool Vehicle::hilMode () const inline
Definition at line 534 of file Vehicle.h.
Referenced by PX4AutoPilotPlugin::vehicleComponents().
hobbsMeter()
QString Vehicle::hobbsMeter ()
Definition at line 2711 of file Vehicle.cc.
References FirmwarePlugin::getHobbsMeter().
hobbsMeterChanged
void Vehicle::hobbsMeterChanged () signal
homePosition()
QGeoCoordinate Vehicle::homePosition ()
Definition at line 1428 of file Vehicle.cc.
Referenced by PX4FirmwarePlugin::guidedModeChangeAltitude(), and APMFirmwarePlugin::sendGCSMotionReport().
homePositionChanged
void Vehicle::homePositionChanged (const QGeoCoordinate & homePosition) signal
Referenced by _setHomePosition(), and MissionSettingsItem::MissionSettingsItem().
hygrometerFactGroup()
FactGroup * Vehicle::hygrometerFactGroup ()
Definition at line 423 of file Vehicle.cc.
References _hygrometerFactGroup.
id()
int Vehicle::id () const inline
Definition at line 423 of file Vehicle.h.
Referenced by VehicleFactGroup::_handleAttitude(), VehicleFactGroup::_handleAttitudeQuaternion(), PlanManager::_handleMissionRequest(), VehicleCameraControl::_mavCommandResult(), QGCCameraManager::_mavlinkMessageReceived(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), PlanManager::_writeMissionCount(), APMFirmwarePlugin::adjustIncomingMavlinkMessage(), OnboardLogController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), MavCommandQueue::handleCommandAck(), QGCCameraParamIO::paramRequest(), ParameterManager::readParametersFromStream(), RemoteIDManager::RemoteIDManager(), requestDataStream(), sendDisableSigning(), sendSetupSigning(), MavCommandQueue::sendWorker(), MissionManager::writeArduPilotGuidedMissionItem(), and ParameterManager::writeParametersToStream().
inFwdFlight()
bool Vehicle::inFwdFlight () const
Definition at line 2068 of file Vehicle.cc.
References fixedWing().
inFwdFlightChanged
void Vehicle::inFwdFlightChanged () signal
initialConnectComplete
void Vehicle::initialConnectComplete () signal
initialPlanRequestComplete()
bool Vehicle::initialPlanRequestComplete () const inline
The vehicle is responsible for making the initial request for the Plan.
Returns
: true: initial request is complete, false: initial request is still in progress;
Definition at line 701 of file Vehicle.h.
Referenced by GeoFenceController::showPlanFromManagerVehicle(), MissionController::showPlanFromManagerVehicle(), and RallyPointController::showPlanFromManagerVehicle().
initialPlanRequestCompleteChanged
void Vehicle::initialPlanRequestCompleteChanged (bool initialPlanRequestComplete) signal
Referenced by forceInitialPlanRequestComplete().
isInitialConnectComplete()
bool Vehicle::isInitialConnectComplete () const
Definition at line 2811 of file Vehicle.cc.
References _initialConnectStateMachine.
isMavCommandPending()
bool Vehicle::isMavCommandPending (int targetCompId, MAV_CMD command)
isMavCommandPending Query whether the specified MAV_CMD is in queue to be sent or has already been sent but whose reply has not yet been received and whose timeout has not yet expired.
Or, said another way: if you call `sendMavCommand(compId, command, true, ...)`
will an error be shown because you (or another part of QGC) has already sent that command?
Parameters
targetCompId
command
Returns
Definition at line 2183 of file Vehicle.cc.
References MavCommandQueue::isPending().
isOfflineEditingVehicle()
bool Vehicle::isOfflineEditingVehicle () const inline
Definition at line 508 of file Vehicle.h.
Referenced by MissionManager::generateResumeMission(), APMFirmwarePlugin::initializeVehicle(), PlanManager::loadFromVehicle(), GeoFenceController::paramCircularFence(), MissionController::sendToVehiclePreCheck(), and PlanManager::writeMissionItems().
isROIEnabled()
bool Vehicle::isROIEnabled () const inline
Running loss rate.
Definition at line 720 of file Vehicle.h.
isROIEnabledChanged
void Vehicle::isROIEnabledChanged () signal
landFlightMode()
QString Vehicle::landFlightMode () const
Definition at line 2546 of file Vehicle.cc.
References FirmwarePlugin::landFlightMode().
landing()
bool Vehicle::landing () const inline
Definition at line 499 of file Vehicle.h.
Referenced by _setLanding().
landingChanged
void Vehicle::landingChanged (bool landing) signal
Referenced by _setLanding().
landingGearDeploy()
void Vehicle::landingGearDeploy ()
Command vichecle to deploy landing gear.
Definition at line 2084 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
landingGearRetract()
void Vehicle::landingGearRetract ()
Command vichecle to retract landing gear.
Definition at line 2094 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
latitude()
float Vehicle::latitude () inline
Definition at line 490 of file Vehicle.h.
loadProgress()
double Vehicle::loadProgress () const inline
Definition at line 725 of file Vehicle.h.
loadProgressChanged
void Vehicle::loadProgressChanged (float value) signal
localPositionFactGroup()
FactGroup * Vehicle::localPositionFactGroup ()
Definition at line 419 of file Vehicle.cc.
References _localPositionFactGroup.
localPositionSetpointFactGroup()
FactGroup * Vehicle::localPositionSetpointFactGroup ()
Definition at line 420 of file Vehicle.cc.
References _localPositionSetpointFactGroup.
logData
void Vehicle::logData (uint32_t ofs, uint16_t id, uint8_t count, const uint8_t * data) signal
logEntry
void Vehicle::logEntry (uint32_t time_utc, uint32_t size, uint16_t id, uint16_t num_logs, uint16_t last_log_num) signal
longitude()
float Vehicle::longitude () inline
Definition at line 491 of file Vehicle.h.
longitudeChanged
void Vehicle::longitudeChanged () signal
mavCmdResultFailureCodeToString()
QString Vehicle::mavCmdResultFailureCodeToString (MavCmdResultFailureCode_t failureCode) static
Definition at line 3268 of file Vehicle.cc.
References MavCommandQueue::failureCodeToString().
Referenced by _requestCameraInfoCommandResultHandler().
mavCommandResult
void Vehicle::mavCommandResult (int vehicleId, int targetComponent, int command, int ackResult, int failureCode) signal
Signalled in response to usage of sendMavCommand
Parameters
vehicleId Vehicle which command was sent to
targetComponent Component which command was sent to
command Command which was sent
ackResult MAV_RESULT returned in ack
failureCode More detailed failure code Vehicle::MavCmdResultFailureCode_t
Referenced by VehicleCameraControl::_initWhenReady(), SendMavlinkCommandState::connectWaitSignal(), SendMavlinkCommandState::disconnectWaitSignal(), and PX4FirmwarePlugin::guidedModeTakeoff().
mavlinkLogData
void Vehicle::mavlinkLogData (Vehicle * vehicle, uint8_t target_system, uint8_t target_component, uint16_t sequence, uint8_t first_message, QByteArray data, bool acked) signal
mavlinkLogManager()
MAVLinkLogManager * Vehicle::mavlinkLogManager () const
Definition at line 3492 of file Vehicle.cc.
mavlinkLogManagerChanged
void Vehicle::mavlinkLogManagerChanged () signal
mavlinkLossCount()
quint64 Vehicle::mavlinkLossCount () const inline
Total number of sucessful messages received.
Definition at line 717 of file Vehicle.h.
mavlinkLossPercent()
float Vehicle::mavlinkLossPercent () const inline
Total number of lost messages.
Definition at line 718 of file Vehicle.h.
mavlinkMessageReceived
void Vehicle::mavlinkMessageReceived (const mavlink_message_t & message) signal
Referenced by PlanManager::_connectToMavlink(), PlanManager::_disconnectFromMavlink(), WaitForMavlinkMessageState::connectWaitSignal(), WaitForParamResponseState::connectWaitSignal(), WaitForMavlinkMessageState::disconnectWaitSignal(), WaitForParamResponseState::disconnectWaitSignal(), and MissionManager::MissionManager().
mavlinkMsgIntervalsChanged
void Vehicle::mavlinkMsgIntervalsChanged (uint8_t compid, uint16_t msgId, int32_t rate) signal
mavlinkReceivedCount()
quint64 Vehicle::mavlinkReceivedCount () const inline
Calculated total number of messages sent to us.
Definition at line 716 of file Vehicle.h.
mavlinkSentCount()
quint64 Vehicle::mavlinkSentCount () const inline
Definition at line 715 of file Vehicle.h.
mavlinkSerialControl
void Vehicle::mavlinkSerialControl (uint8_t device, uint8_t flags, uint16_t timeout, uint32_t baudrate, QByteArray data) signal
mavlinkSigning()
bool Vehicle::mavlinkSigning () const inline
Definition at line 536 of file Vehicle.h.
mavlinkSigningChanged
void Vehicle::mavlinkSigningChanged () signal
Referenced by sendDisableSigning(), and sendSetupSigning().
mavlinkSigningKeyName()
QString Vehicle::mavlinkSigningKeyName () const inline
Definition at line 537 of file Vehicle.h.
mavlinkStatusChanged
void Vehicle::mavlinkStatusChanged () signal
maximumEquivalentAirspeed()
double Vehicle::maximumEquivalentAirspeed ()
Returns
Maximum equivalent airspeed.
Definition at line 1859 of file Vehicle.cc.
References FirmwarePlugin::maximumEquivalentAirspeed().
maximumHorizontalSpeedMultirotorMetersSecond()
double Vehicle::maximumHorizontalSpeedMultirotorMetersSecond ()
Returns
Maximum horizontal speed multirotor.
Definition at line 1853 of file Vehicle.cc.
References FirmwarePlugin::maximumHorizontalSpeedMultirotorMetersSecond().
messageCountChanged
void Vehicle::messageCountChanged () signal
messagesLost()
uint Vehicle::messagesLost () const inline
Definition at line 497 of file Vehicle.h.
messagesLostChanged
void Vehicle::messagesLostChanged () signal
messagesReceived()
uint Vehicle::messagesReceived () const inline
Definition at line 495 of file Vehicle.h.
messagesReceivedChanged
void Vehicle::messagesReceivedChanged () signal
messagesSent()
uint Vehicle::messagesSent () const inline
Definition at line 496 of file Vehicle.h.
messagesSentChanged
void Vehicle::messagesSentChanged () signal
Referenced by sendMessageOnLinkThreadSafe().
messageTypeChanged
void Vehicle::messageTypeChanged () signal
minimumEquivalentAirspeed()
double Vehicle::minimumEquivalentAirspeed ()
Returns
Minimum equivalent airspeed.
Definition at line 1865 of file Vehicle.cc.
References FirmwarePlugin::minimumEquivalentAirspeed().
minimumTakeoffAltitudeMeters()
double Vehicle::minimumTakeoffAltitudeMeters ()
Returns
The minimum takeoff altitude (relative) for guided takeoff.
Definition at line 1848 of file Vehicle.cc.
References FirmwarePlugin::minimumTakeoffAltitudeMeters().
missionFlightMode()
QString Vehicle::missionFlightMode () const
Definition at line 2526 of file Vehicle.cc.
References FirmwarePlugin::missionFlightMode().
Referenced by MissionController::sendToVehiclePreCheck(), and MAVLinkEventManager::setMetadata().
missionManager()
MissionManager * Vehicle::missionManager () inline
Definition at line 568 of file Vehicle.h.
References _missionManager.
Referenced by APMFirmwarePlugin::guidedModeGotoLocation(), MissionController::loadFromVehicle(), and MissionController::sendItemsToVehicle().
motorCount()
int Vehicle::motorCount ()
Returns
-1 = Unknown, Number of motors on vehicle
Definition at line 1404 of file Vehicle.cc.
References ParameterManager::getParameter(), QGCMAVLink::motorCount(), and parameterManager().
motorDetectionFlightMode()
QString Vehicle::motorDetectionFlightMode () const
Definition at line 2561 of file Vehicle.cc.
References FirmwarePlugin::motorDetectionFlightMode().
motorInterlock()
void Vehicle::motorInterlock (bool enable)
Command vehicle to Enable/Disable Motor Interlock.
Definition at line 3289 of file Vehicle.cc.
References apmFirmware(), defaultComponentId(), APM::MOTOR_INTERLOCK, and sendMavCommand().
motorTest()
void Vehicle::motorTest (int motor, int percent, int timeoutSecs, bool showError)
Test motor
Parameters
motor Motor number, 1-based
percent 0-no power, 100-full power
timeoutSec Disabled motor after this amount of time
Definition at line 2436 of file Vehicle.cc.
References sendMavCommand().
multiRotor()
bool Vehicle::multiRotor () const
Definition at line 1751 of file Vehicle.cc.
References QGCMAVLink::isMultiRotor(), and vehicleType().
Referenced by SpeedSection::appendSectionItems(), MissionController::complexMissionItemNames(), APMFirmwarePlugin::expandedToolbarIndicatorSource(), PX4FirmwarePlugin::flightModes(), TransectStyleComplexItem::hoverAndCaptureAllowed(), APMFirmwarePlugin::isCapable(), PX4FirmwarePlugin::isCapable(), MissionFlightStatusCalculator::recalc(), MissionFlightStatusCalculator::reset(), SpeedSection::scanForSection(), SpeedSection::setAvailable(), SpeedSection::SpeedSection(), startCalibration(), and APMAutoPilotPlugin::vehicleComponents().
newFormattedMessage
void Vehicle::newFormattedMessage (QString formattedMessage) signal
objectAvoidance()
VehicleObjectAvoidance * Vehicle::objectAvoidance () inline
Definition at line 576 of file Vehicle.h.
orbitActive()
bool Vehicle::orbitActive () const inline
Definition at line 527 of file Vehicle.h.
orbitActiveChanged
void Vehicle::orbitActiveChanged (bool orbitActive) signal
orbitMapCircle()
QGCMapCircle * Vehicle::orbitMapCircle () inline
Definition at line 528 of file Vehicle.h.
pairRX()
void Vehicle::pairRX (int rxType, int rxSubType)
Definition at line 3088 of file Vehicle.cc.
References sendMavCommand().
Referenced by RadioComponentController::crsfBindMode(), and RadioComponentController::spektrumBindMode().
parameterManager() [1/2]
ParameterManager * Vehicle::parameterManager () inline
Definition at line 571 of file Vehicle.h.
Referenced by FactPanelController::_allParametersExists(), APMSensorsComponent::accelSetupNeeded(), APMAirframeComponent::APMAirframeComponent(), APMRadioComponent::APMRadioComponent(), APMSensorsComponent::compassSetupNeeded(), VehicleObjectAvoidance::enabled(), APMFirmwarePlugin::fixedWingAirSpeedLimitsAvailable(), PX4FirmwarePlugin::fixedWingAirSpeedLimitsAvailable(), APMFirmwarePlugin::getHobbsMeter(), PX4FirmwarePlugin::getHobbsMeter(), APMFirmwarePlugin::guidedModeChangeHeading(), APMFirmwarePlugin::hasGripper(), PX4FirmwarePlugin::hasGripper(), Actuators::init(), APMFirmwarePlugin::maximumEquivalentAirspeed(), PX4FirmwarePlugin::maximumEquivalentAirspeed(), APMFirmwarePlugin::maximumHorizontalSpeedMultirotorMetersSecond(), PX4FirmwarePlugin::maximumHorizontalSpeedMultirotorMetersSecond(), APMFirmwarePlugin::minimumEquivalentAirspeed(), PX4FirmwarePlugin::minimumEquivalentAirspeed(), APMFirmwarePlugin::minimumTakeoffAltitudeMeters(), motorCount(), APMFirmwarePlugin::mulirotorSpeedLimitsAvailable(), PX4FirmwarePlugin::mulirotorSpeedLimitsAvailable(), ArduCopterFirmwarePlugin::multiRotorXConfig(), GeoFenceController::paramCircularFence(), PX4AutoPilotPlugin::parametersReadyPreChecks(), PX4AutoPilotPlugin::prerequisiteSetup(), PX4RadioComponent::requiresSetup(), SensorsComponent::sections(), SensorsComponent::sectionSetupComplete(), APMRadioComponent::setupComplete(), AirframeComponent::setupComplete(), PX4RadioComponent::setupComplete(), PowerComponent::setupComplete(), SensorsComponent::setupComplete(), VehicleObjectAvoidance::stop(), APMAutoPilotPlugin::vehicleComponents(), and PX4AutoPilotPlugin::vehicleComponents().
parameterManager() [2/2]
ParameterManager * Vehicle::parameterManager () const inline
Definition at line 572 of file Vehicle.h.
pauseFlightMode()
QString Vehicle::pauseFlightMode () const
Definition at line 2531 of file Vehicle.cc.
References FirmwarePlugin::pauseFlightMode().
pauseVehicle()
void Vehicle::pauseVehicle ()
Command vehicle to pause at current location. If vehicle supports guide mode, vehicle will be left in guided mode after pause.
Definition at line 2040 of file Vehicle.cc.
References VehicleSupports::pauseVehicle(), FirmwarePlugin::pauseVehicle(), and QGC::showAppMessage().
Referenced by guidedModeChangeAltitude().
prearmError()
QString Vehicle::prearmError () const inline
Definition at line 471 of file Vehicle.h.
Referenced by setPrearmError().
prearmErrorChanged
void Vehicle::prearmErrorChanged (const QString & prearmError) signal
Referenced by setPrearmError().
prepareDelete()
void Vehicle::prepareDelete ()
Vehicle is about to be deleted.
px4Firmware()
bool Vehicle::px4Firmware () const inline
Definition at line 492 of file Vehicle.h.
Referenced by genericFirmware(), guidedModeROI(), MavCommandQueue::handleCommandAck(), MissionController::multipleLandPatternsAllowed(), GeoFenceController::paramCircularFence(), VehicleSupports::terrainFrame(), ParameterManager::tryHashCheckCacheLoad(), and RadioComponentController::~RadioComponentController().
radioStatusFactGroup()
FactGroup * Vehicle::radioStatusFactGroup ()
Definition at line 427 of file Vehicle.cc.
References _radioStatusFactGroup.
rallyPointManager()
RallyPointManager * Vehicle::rallyPointManager () inline
Definition at line 570 of file Vehicle.h.
References _rallyPointManager.
rcChannelsClampedChanged
void Vehicle::rcChannelsClampedChanged (QVector< int > channelValues) signal
Filtered RC channel values coming from RC_CHANNELS message: clamped 1000:2000
Parameters
channelValues The clamped values for rc channels
Referenced by PX4SimpleFlightModesController::PX4SimpleFlightModesController(), and RadioComponentController::start().
rcChannelsRawChanged
void Vehicle::rcChannelsRawChanged (QVector< int > channelValues) signal
Raw RC channel values coming from RC_CHANNELS message
Parameters
channelValues The current raw values for rc channels
readyToFly()
bool Vehicle::readyToFly () const inline
Definition at line 530 of file Vehicle.h.
readyToFlyAvailable()
bool Vehicle::readyToFlyAvailable () const inline
Definition at line 529 of file Vehicle.h.
readyToFlyAvailableChanged
void Vehicle::readyToFlyAvailableChanged (bool readyToFlyAvailable) signal
readyToFlyChanged
void Vehicle::readyToFlyChanged (bool readyToFy) signal
rebootVehicle()
void Vehicle::rebootVehicle ()
Reboot vehicle.
Definition at line 2309 of file Vehicle.cc.
References VehicleTypes::MavCmdAckHandlerInfo_s::resultHandler, VehicleTypes::MavCmdAckHandlerInfo_s::resultHandlerData, and sendMavCommandWithHandler().
remoteIDManager()
RemoteIDManager * Vehicle::remoteIDManager () inline
Definition at line 578 of file Vehicle.h.
References _remoteIDManager.
requestDataStream()
void Vehicle::requestDataStream (MAV_DATA_STREAM stream, uint16_t rate, bool sendMultiple = true)
Requests the specified data stream from the vehicle
Parameters
stream Stream which is being requested
rate Rate at which to send stream in Hz
sendMultiple Send multiple time to guarantee Vehicle reception
Definition at line 1523 of file Vehicle.cc.
References MAVLinkProtocol::getComponentId(), id(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), sendMessageMultiple(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
Referenced by APMFirmwarePlugin::initializeStreamRates(), ArduSubFirmwarePlugin::initializeStreamRates(), and APMMavlinkStreamRateSettings::streamRateExtra3().
requestMessage()
void Vehicle::requestMessage (RequestMessageResultHandler resultHandler, void * resultHandlerData, int compId, int messageId, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, float param5 = 0.0f)
Requests the vehicle to send the specified message. Will retry a number of times.
Parameters
resultHandler Callback for result
resultHandlerData Opaque data passed back to resultHandler
Definition at line 2245 of file Vehicle.cc.
References compId(), and RequestMessageCoordinator::requestMessage().
Referenced by _requestCameraInfoHelper(), and RequestMessageState::onWaitEntered().
requestMessageResultHandlerFailureCodeToString()
QString Vehicle::requestMessageResultHandlerFailureCodeToString (RequestMessageResultHandlerFailureCode_t failureCode) static
Definition at line 3263 of file Vehicle.cc.
References RequestMessageCoordinator::failureCodeToString().
Referenced by _requestCameraInfoMessageResultHandler().
requestOperatorControl()
void Vehicle::requestOperatorControl (bool allowOverride, int requestTimeoutSecs = 0)
Definition at line 3113 of file Vehicle.cc.
References FlyViewSettings::requestControlTimeout(), and sendMavCommandWithHandler().
Referenced by startTimerRevertAllowTakeover().
requestOperatorControlReceived
void Vehicle::requestOperatorControlReceived (int sysIdRequestingControl, int allowTakeover, int requestTimeoutSecs) signal
requiresGpsFix()
bool Vehicle::requiresGpsFix () const inline
Definition at line 533 of file Vehicle.h.
requiresGpsFixChanged
void Vehicle::requiresGpsFixChanged () signal
roiCoordChanged
void Vehicle::roiCoordChanged (const QGeoCoordinate & centerCoord) signal
Referenced by guidedModeROI().
rover()
bool Vehicle::rover () const
Definition at line 1736 of file Vehicle.cc.
References QGCMAVLink::isRoverBoat(), and vehicleType().
Referenced by startCalibration().
rpmFactGroup()
FactGroup * Vehicle::rpmFactGroup ()
Definition at line 426 of file Vehicle.cc.
References _rpmFactGroup.
rtlFlightMode()
QString Vehicle::rtlFlightMode () const
Definition at line 2536 of file Vehicle.cc.
References FirmwarePlugin::rtlFlightMode().
sendCommand()
void Vehicle::sendCommand (int compId, int command, bool showError, double param1 = 0.0, double param2 = 0.0, double param3 = 0.0, double param4 = 0.0, double param5 = 0.0, double param6 = 0.0, double param7 = 0.0)
Same as sendMavCommand but available from Qml.
Definition at line 2149 of file Vehicle.cc.
References compId(), and sendMavCommand().
sendControlRequestAllowedChanged
void Vehicle::sendControlRequestAllowedChanged (bool sendControlRequestAllowed) signal
sendDisableSigning()
void Vehicle::sendDisableSigning ()
Definition at line 3430 of file Vehicle.cc.
References MAVLinkSigning::createDisableSigning(), defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::getSystemId(), id(), MAVLinkSigning::initSigning(), MAVLinkProtocol::instance(), mavlinkSigningChanged(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
sendGripperAction
void Vehicle::sendGripperAction (GRIPPER_ACTIONS gripperOption) slot
Definition at line 3055 of file Vehicle.cc.
References sendMavCommand().
sendJoystickDataThreadSafe()
void Vehicle::sendJoystickDataThreadSafe (float roll, float pitch, float yaw, float thrust, quint16 buttons, quint16 buttons2, float pitchExtension, float rollExtension, float aux1, float aux2, float aux3, float aux4, float aux5, float aux6)
Definition at line 2988 of file Vehicle.cc.
References MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
Referenced by virtualTabletJoystickValue().
sendMavCommand()
void Vehicle::sendMavCommand (int compId, MAV_CMD command, bool showError, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, float param5 = 0.0f, float param6 = 0.0f, float param7 = 0.0f)
Sends the specified MAV_CMD to the vehicle. If no Ack is received command will be retried. If a sendMavCommand is already in progress the command will be queued and sent when the previous command completes.
Parameters
compId Component to send to.
command MAV_CMD to send
showError true: Display error to user if command failed, false: no error shown Signals: mavCommandResult on success or failure
Definition at line 2139 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommand().
Referenced by PX4FirmwarePlugin::_changeAltAfterPause(), VehicleCameraControl::_requestCameraSettings(), VehicleCameraControl::_requestCaptureStatus(), VehicleCameraControl::_requestStorageInfo(), VehicleCameraControl::_requestStreamInfo(), VehicleCameraControl::_requestStreamStatus(), VehicleCameraControl::_requestTrackingStatus(), abortLanding(), emergencyStop(), flashBootloader(), forceArm(), VehicleCameraControl::formatCard(), APMFirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), PX4FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), PX4FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), APMFirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), APMFirmwarePlugin::guidedModeChangeHeading(), PX4FirmwarePlugin::guidedModeChangeHeading(), PX4FirmwarePlugin::guidedModeGotoLocation(), guidedModeOrbit(), PX4FirmwarePlugin::guidedModeTakeoff(), APMFirmwarePlugin::initializeStreamRates(), landingGearDeploy(), landingGearRetract(), motorInterlock(), motorTest(), SendMavlinkCommandState::onWaitEntered(), pairRX(), PX4FirmwarePlugin::pauseVehicle(), ParameterManager::resetAllParametersToDefaults(), SensorsComponentController::resetFactoryParameters(), VehicleCameraControl::resetSettings(), VehicleCameraControl::resumeStream(), sendCommand(), sendGripperAction(), TerrainQueryCoordinator::sendROICommand(), setArmed(), VehicleCameraControl::setCameraMode(), VehicleCameraControl::setCurrentStream(), setEventsMetadata(), setFlightMode(), VehicleCameraControl::setFocusLevel(), setVtolInFwdFlight(), VehicleCameraControl::setZoomLevel(), VehicleCameraControl::startFocus(), startMavlinkLog(), APMFirmwarePlugin::startMission(), VehicleCameraControl::startTrackingPoint(), VehicleCameraControl::startTrackingRect(), startUAVCANBusConfig(), VehicleCameraControl::startVideoRecording(), VehicleCameraControl::startZoom(), VehicleCameraControl::stepFocus(), VehicleCameraControl::stepZoom(), stopCalibration(), VehicleCameraControl::stopFocus(), stopGuidedModeROI(), stopMavlinkLog(), VehicleCameraControl::stopStream(), VehicleCameraControl::stopTakePhoto(), VehicleCameraControl::stopTracking(), stopUAVCANBusConfig(), VehicleCameraControl::stopVideoRecording(), VehicleCameraControl::stopZoom(), VehicleCameraControl::takePhoto(), and triggerSimpleCamera().
sendMavCommandDelayed()
void Vehicle::sendMavCommandDelayed (int compId, MAV_CMD command, bool showError, int milliseconds, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, float param5 = 0.0f, float param6 = 0.0f, float param7 = 0.0f)
Definition at line 2144 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommandDelayed().
sendMavCommandInt()
void Vehicle::sendMavCommandInt (int compId, MAV_CMD command, MAV_FRAME frame, bool showError, float param1, float param2, float param3, float param4, double param5, double param6, float param7)
Definition at line 2168 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommandInt().
Referenced by PX4FirmwarePlugin::guidedModeGotoLocation(), guidedModeOrbit(), TerrainQueryCoordinator::sendROICommand(), and stopGuidedModeROI().
sendMavCommandIntWithHandler()
void Vehicle::sendMavCommandIntWithHandler (const MavCmdAckHandlerInfo_t * ackHandlerInfo, int compId, MAV_CMD command, MAV_FRAME frame, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, double param5 = 0.0f, double param6 = 0.0f, float param7 = 0.0f)
Sends the command and calls the callback with the result
Parameters
resultHandler Callback for result, nullptr for no callback
resultHandleData Opaque data passed through callback
Parameters
compId
‍nullptr to signale no handlers
Definition at line 2173 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommandIntWithHandler().
Referenced by APMFirmwarePlugin::guidedModeGotoLocation().
sendMavCommandWithHandler()
void Vehicle::sendMavCommandWithHandler (const MavCmdAckHandlerInfo_t * ackHandlerInfo, int compId, MAV_CMD command, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, float param5 = 0.0f, float param6 = 0.0f, float param7 = 0.0f)
Sends the command and calls the callback with the result.
Parameters
compId
‍nullptr to signale no handlers
Definition at line 2163 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommandWithHandler().
Referenced by PX4FirmwarePlugin::guidedModeChangeAltitude(), rebootVehicle(), requestOperatorControl(), and Autotune::sendMavlinkRequest().
sendMavCommandWithLambdaFallback()
void Vehicle::sendMavCommandWithLambdaFallback (std::function< void()> lambda, int compId, MAV_CMD command, bool showError, float param1 = 0.0f, float param2 = 0.0f, float param3 = 0.0f, float param4 = 0.0f, float param5 = 0.0f, float param6 = 0.0f, float param7 = 0.0f)
Sends the command and calls the fallback lambda function in case the command is MAV_RESULT_UNSUPPORTED
Definition at line 2178 of file Vehicle.cc.
References compId(), and MavCommandQueue::sendCommandWithLambdaFallback().
Referenced by setCurrentMissionSequence().
sendMessageMultiple()
void Vehicle::sendMessageMultiple (mavlink_message_t message)
Sends the specified messages multiple times to the vehicle in order to attempt to guarantee that it makes it to the vehicle.
Definition at line 1581 of file Vehicle.cc.
Referenced by requestDataStream().
sendMessageOnLinkThreadSafe()
bool Vehicle::sendMessageOnLinkThreadSafe (LinkInterface * link, mavlink_message_t message)
Sends a message to the specified link
Returns
true: message sent, false: Link no longer connected
Definition at line 1383 of file Vehicle.cc.
References FirmwarePlugin::adjustOutgoingMavlinkMessageThreadSafe(), LinkInterface::isConnected(), messagesSentChanged(), and LinkInterface::writeBytesThreadSafe().
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), PlanManager::_writeMissionCount(), clearAllParamMapRC(), OnboardLogController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), QGCCameraParamIO::paramRequest(), requestDataStream(), sendDisableSigning(), APMFirmwarePlugin::sendGCSMotionReport(), FirmwarePlugin::sendGCSMotionReport(), sendJoystickDataThreadSafe(), sendParamMapRC(), sendSetupSigning(), setCurrentMissionSequence(), setEstimatorOrigin(), setFlightMode(), startCalibration(), and MissionManager::writeArduPilotGuidedMissionItem().
sendParamMapRC()
void Vehicle::sendParamMapRC (const QString & paramName, double scale, double centerValue, int tuningID, double minValue, double maxValue)
Sends PARAM_MAP_RC message to vehicle.
Definition at line 2928 of file Vehicle.cc.
References MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
sendPlan()
void Vehicle::sendPlan (QString planFile)
Definition at line 2706 of file Vehicle.cc.
References PlanMasterController::sendPlanToVehicle().
sendSetupSigning()
void Vehicle::sendSetupSigning (int keyIndex)
Send SETUP_SIGNING with the key at the given index in MAVLinkSigningKeys.
Definition at line 3387 of file Vehicle.cc.
References MAVLinkSigning::createSetupSigning(), defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::getSystemId(), id(), MAVLinkSigning::initSigning(), MAVLinkSigning::insecureConnectionAcceptUnsignedCallback(), MAVLinkProtocol::instance(), mavlinkSigningChanged(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
sensorsEnabledBits()
int Vehicle::sensorsEnabledBits () const inline
Definition at line 510 of file Vehicle.h.
sensorsEnabledBitsChanged
void Vehicle::sensorsEnabledBitsChanged (int sensorsEnabledBits) signal
sensorsHealthBits()
int Vehicle::sensorsHealthBits () const inline
Definition at line 511 of file Vehicle.h.
sensorsHealthBitsChanged
void Vehicle::sensorsHealthBitsChanged (int sensorsHealthBits) signal
sensorsParametersResetAck
void Vehicle::sensorsParametersResetAck (bool success) signal
Referenced by SensorsComponentController::SensorsComponentController().
sensorsPresentBits()
int Vehicle::sensorsPresentBits () const inline
Definition at line 509 of file Vehicle.h.
sensorsPresentBitsChanged
void Vehicle::sensorsPresentBitsChanged (int sensorsPresentBits) signal
sensorsUnhealthyBits()
int Vehicle::sensorsUnhealthyBits () const inline
Definition at line 512 of file Vehicle.h.
sensorsUnhealthyBitsChanged
void Vehicle::sensorsUnhealthyBitsChanged (int sensorsUnhealthyBits) signal
servoOutputsChanged
void Vehicle::servoOutputsChanged (QVector< int > servoValues) signal
New SERVO output values coming from SERVO_OUTPUT_RAW message
Parameters
servoValues The current servo output values in microseconds (0-15 -> SERVO1..SERVO16). Invalid values are -1.
setActuatorsMetadata()
void Vehicle::setActuatorsMetadata (uint8_t compid, const QString & metadataJsonFileName)
Definition at line 1259 of file Vehicle.cc.
References _actuators, and Actuators::load().
Referenced by CompInfoActuators::setJson().
setArmed()
void Vehicle::setArmed (bool armed, bool showError)
Definition at line 1433 of file Vehicle.cc.
References armed(), and sendMavCommand().
Referenced by FirmwarePlugin::_armVehicleAndValidate(), and setArmedShowError().
setArmedShowError()
void Vehicle::setArmedShowError (bool armed) inline
Definition at line 449 of file Vehicle.h.
References armed(), and setArmed().
setCheckListState()
void Vehicle::setCheckListState (CheckList cl) inline
Definition at line 723 of file Vehicle.h.
References checkListStateChanged().
setCurrentMissionSequence()
void Vehicle::setCurrentMissionSequence (int seq)
Alter the current mission item on the vehicle.
Definition at line 2104 of file Vehicle.cc.
References defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), FirmwarePlugin::sendHomePositionToVehicle(), sendMavCommandWithLambdaFallback(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
setEstimatorOrigin()
void Vehicle::setEstimatorOrigin (const QGeoCoordinate & centerCoord)
Definition at line 3065 of file Vehicle.cc.
References MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
setEventsMetadata()
void Vehicle::setEventsMetadata (uint8_t compid, const QString & metadataJsonFileName)
Definition at line 3547 of file Vehicle.cc.
References sendMavCommand().
Referenced by CompInfoEvents::setJson().
setFirmwareCustomVersion()
void Vehicle::setFirmwareCustomVersion (int majorVersion, int minorVersion, int patchVersion)
Definition at line 2274 of file Vehicle.cc.
References firmwareCustomVersionChanged().
setFirmwarePluginInstanceData()
void Vehicle::setFirmwarePluginInstanceData (FirmwarePluginInstanceData * firmwarePluginInstanceData)
Sets the firmware plugin instance data associated with this Vehicle. This object will be parented to the Vehicle and destroyed when the vehicle goes away.
Definition at line 2520 of file Vehicle.cc.
References firmwarePluginInstanceData().
Referenced by APMFirmwarePlugin::initializeStreamRates(), and PX4FirmwarePlugin::initializeVehicle().
setFirmwareVersion()
void Vehicle::setFirmwareVersion (int majorVersion, int minorVersion, int patchVersion, FIRMWARE_VERSION_TYPE versionType = FIRMWARE_VERSION_TYPE_OFFICIAL)
Definition at line 2265 of file Vehicle.cc.
References firmwareVersionChanged().
Referenced by APMFirmwarePlugin::initializeVehicle().
setFlightMode()
void Vehicle::setFlightMode (const QString & flightMode)
Definition at line 1472 of file Vehicle.cc.
References defaultComponentId(), flightMode(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), FirmwarePlugin::MAV_CMD_DO_SET_MODE_is_supported(), VehicleLinkManager::primaryLink(), sendMavCommand(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
Referenced by FirmwarePlugin::_setFlightModeAndValidate().
setGuidedMode()
void Vehicle::setGuidedMode (bool guidedMode)
Definition at line 2063 of file Vehicle.cc.
References guidedMode(), and FirmwarePlugin::setGuidedMode().
setInitialGCSPressure()
void Vehicle::setInitialGCSPressure (qreal pressure) inline
Definition at line 415 of file Vehicle.h.
Referenced by Vehicle().
setInitialGCSTemperature()
void Vehicle::setInitialGCSTemperature (qreal temperature) inline
Definition at line 416 of file Vehicle.h.
Referenced by Vehicle().
setMessageRate()
void Vehicle::setMessageRate (uint8_t compId, uint16_t msgId, int32_t rate)
Definition at line 3253 of file Vehicle.cc.
References compId(), and MessageIntervalManager::setMessageRate().
Referenced by MAVLinkInspectorController::setMessageInterval().
setOfflineEditingDefaultComponentId()
void Vehicle::setOfflineEditingDefaultComponentId (int defaultComponentId)
Sets the default component id for an offline editing vehicle.
Definition at line 2441 of file Vehicle.cc.
References defaultComponentId().
setPIDTuningTelemetryMode()
void Vehicle::setPIDTuningTelemetryMode (PIDTuningTelemetryMode mode)
Definition at line 2760 of file Vehicle.cc.
References VehicleFactGroup::_altitudeTuningFact, _altitudeTuningOffset, VehicleFactGroup::_altitudeTuningSetpointFact, _localPositionFactGroup, _localPositionSetpointFactGroup, _setpointFactGroup, ModeAltitudeAndAirspeed, ModeDisabled, ModeRateAndAttitude, and ModeVelocityAndPosition.
setpointFactGroup()
FactGroup * Vehicle::setpointFactGroup ()
Definition at line 417 of file Vehicle.cc.
References _setpointFactGroup.
Referenced by VehicleObjectAvoidance::update().
setPrearmError()
void Vehicle::setPrearmError (const QString & prearmError)
Definition at line 2251 of file Vehicle.cc.
References prearmError(), and prearmErrorChanged().
setSoloFirmware()
void Vehicle::setSoloFirmware (bool soloFirmware)
Definition at line 2428 of file Vehicle.cc.
References soloFirmware(), and soloFirmwareChanged().
setVtolInFwdFlight
void Vehicle::setVtolInFwdFlight (bool vtolInFwdFlight) slot
Definition at line 2450 of file Vehicle.cc.
References sendMavCommand(), and vtolInFwdFlight().
showCommandAckError()
void Vehicle::showCommandAckError (const mavlink_command_ack_t & ack) static
Definition at line 2193 of file Vehicle.cc.
References MavCommandQueue::showCommandAckError().
smartRTLFlightMode()
QString Vehicle::smartRTLFlightMode () const
Definition at line 2541 of file Vehicle.cc.
References FirmwarePlugin::smartRTLFlightMode().
soloFirmware()
bool Vehicle::soloFirmware () const inline
Definition at line 665 of file Vehicle.h.
Referenced by setSoloFirmware().
soloFirmwareChanged
void Vehicle::soloFirmwareChanged (bool soloFirmware) signal
Referenced by setSoloFirmware().
spacecraft()
bool Vehicle::spacecraft () const
Definition at line 1746 of file Vehicle.cc.
References QGCMAVLink::isSpacecraft(), and vehicleType().
stabilizedFlightMode()
QString Vehicle::stabilizedFlightMode () const
Definition at line 2566 of file Vehicle.cc.
References FirmwarePlugin::stabilizedFlightMode().
startCalibration()
void Vehicle::startCalibration (QGCMAVLink::CalibrationType calType)
Definition at line 2318 of file Vehicle.cc.
References QGCMAVLink::CalibrationAccel, QGCMAVLink::CalibrationAPMAccelSimple, QGCMAVLink::CalibrationAPMCompassMot, QGCMAVLink::CalibrationAPMPreFlight, QGCMAVLink::CalibrationAPMPressureAirspeed, QGCMAVLink::CalibrationCopyTrims, QGCMAVLink::CalibrationEsc, QGCMAVLink::CalibrationGyro, QGCMAVLink::CalibrationLevel, QGCMAVLink::CalibrationMag, QGCMAVLink::CalibrationNone, QGCMAVLink::CalibrationPX4Airspeed, QGCMAVLink::CalibrationPX4Pressure, QGCMAVLink::CalibrationRadio, defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), multiRotor(), VehicleLinkManager::primaryLink(), rover(), sendMessageOnLinkThreadSafe(), and vehicleLinkManager().
Referenced by SensorsComponentController::calibrateAccel(), SensorsComponentController::calibrateAirspeed(), PowerComponentController::calibrateEsc(), SensorsComponentController::calibrateGyro(), and SensorsComponentController::calibrateLevel().
startMavlinkLog()
void Vehicle::startMavlinkLog ()
Definition at line 2461 of file Vehicle.cc.
References sendMavCommand().
startMission()
void Vehicle::startMission ()
Definition at line 1881 of file Vehicle.cc.
References FirmwarePlugin::startMission().
startTakeoff()
void Vehicle::startTakeoff ()
Definition at line 1875 of file Vehicle.cc.
References FirmwarePlugin::startTakeoff().
startTimerRevertAllowTakeover()
void Vehicle::startTimerRevertAllowTakeover ()
Definition at line 3097 of file Vehicle.cc.
References MAVLinkProtocol::instance(), and requestOperatorControl().
startUAVCANBusConfig()
void Vehicle::startUAVCANBusConfig (void)
Definition at line 2412 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
Referenced by PowerComponentController::startBusConfigureActuators().
stopCalibration()
void Vehicle::stopCalibration (bool showError)
Definition at line 2398 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
Referenced by SensorsComponentController::cancelCalibration(), and RadioComponentController::~RadioComponentController().
stopGuidedModeROI()
void Vehicle::stopGuidedModeROI ()
Definition at line 1996 of file Vehicle.cc.
References capabilityBits(), defaultComponentId(), VehicleSupports::roiMode(), sendMavCommand(), sendMavCommandInt(), and QGC::showAppMessage().
stopMavlinkLog()
void Vehicle::stopMavlinkLog ()
Definition at line 2466 of file Vehicle.cc.
References sendMavCommand().
stopTrackingFirmwareVehicleTypeChanges()
void Vehicle::stopTrackingFirmwareVehicleTypeChanges (void)
Definition at line 221 of file Vehicle.cc.
References _offlineFirmwareTypeSettingChanged(), _offlineVehicleTypeSettingChanged(), and Fact::rawValueChanged().
stopUAVCANBusConfig()
void Vehicle::stopUAVCANBusConfig (void)
Definition at line 2420 of file Vehicle.cc.
References defaultComponentId(), and sendMavCommand().
Referenced by PowerComponentController::stopBusConfigureActuators().
sub()
bool Vehicle::sub () const
Definition at line 1741 of file Vehicle.cc.
References QGCMAVLink::isSub(), and vehicleType().
Referenced by APMFirmwarePlugin::isCapable(), Vehicle(), and APMAutoPilotPlugin::vehicleComponents().
supports()
VehicleSupports * Vehicle::supports () inline
Definition at line 403 of file Vehicle.h.
Referenced by MissionController::setCurrentPlanViewSeqNum(), and APMAutoPilotPlugin::vehicleComponents().
sysStatusSensorInfo()
QObject * Vehicle::sysStatusSensorInfo ()
Definition at line 432 of file Vehicle.cc.
takeControlFlightMode()
QString Vehicle::takeControlFlightMode () const
Definition at line 2551 of file Vehicle.cc.
References FirmwarePlugin::takeControlFlightMode().
temperatureFactGroup()
FactGroup * Vehicle::temperatureFactGroup ()
Definition at line 415 of file Vehicle.cc.
References _temperatureFactGroup.
terrainFactGroup()
FactGroup * Vehicle::terrainFactGroup ()
Definition at line 422 of file Vehicle.cc.
References _terrainFactGroup.
textMessageReceived
void Vehicle::textMessageReceived (int sysid, int componentid, int severity, QString text, QString description) signal
Referenced by PowerComponentController::calibrateEsc(), PowerComponentController::startBusConfigureActuators(), and PowerComponentController::stopBusConfigureActuators().
toolIndicators()
const QVariantList & Vehicle::toolIndicators ()
Definition at line 2587 of file Vehicle.cc.
References FirmwarePlugin::toolIndicators().
toolIndicatorsChanged
void Vehicle::toolIndicatorsChanged () signal
trackFirmwareVehicleTypeChanges()
void Vehicle::trackFirmwareVehicleTypeChanges (void)
Definition at line 212 of file Vehicle.cc.
References _offlineFirmwareTypeSettingChanged(), _offlineVehicleTypeSettingChanged(), and Fact::rawValueChanged().
Referenced by Vehicle().
triggerSimpleCamera()
void Vehicle::triggerSimpleCamera (void)
Trigger camera using MAV_CMD_DO_DIGICAM_CONTROL command.
Definition at line 3046 of file Vehicle.cc.
References sendMavCommand().
Referenced by SimulatedCameraControl::takePhoto().
updateFlightDistance()
void Vehicle::updateFlightDistance (double distance)
Definition at line 2923 of file Vehicle.cc.
References VehicleFactGroup::_flightDistanceFact.
vehicleClass()
QGCMAVLink::VehicleClass_t Vehicle::vehicleClass (void) const inline
Definition at line 427 of file Vehicle.h.
References QGCMAVLink::vehicleClass().
Referenced by MissionManager::generateResumeMission(), and vehicleClassInternalName().
vehicleClassInternalName()
QString Vehicle::vehicleClassInternalName () const
Definition at line 1766 of file Vehicle.cc.
References vehicleClass(), and QGCMAVLink::vehicleClassToInternalString().
vehicleFactGroup()
FactGroup * Vehicle::vehicleFactGroup () inline
Definition at line 545 of file Vehicle.h.
References _vehicleFactGroup.
vehicleImageOpaque()
QString Vehicle::vehicleImageOpaque () const
Definition at line 2571 of file Vehicle.cc.
References FirmwarePlugin::vehicleImageOpaque().
vehicleImageOutline()
QString Vehicle::vehicleImageOutline () const
Definition at line 2579 of file Vehicle.cc.
References FirmwarePlugin::vehicleImageOutline().
vehicleLinkManager()
VehicleLinkManager * Vehicle::vehicleLinkManager () inline
Definition at line 573 of file Vehicle.h.
References _vehicleLinkManager.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), PlanManager::_writeMissionCount(), clearAllParamMapRC(), OnboardLogController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), PlanMasterController::loadFromVehicle(), RequestMessageState::onWaitEntered(), QGCCameraParamIO::paramRequest(), requestDataStream(), sendDisableSigning(), APMFirmwarePlugin::sendGCSMotionReport(), FirmwarePlugin::sendGCSMotionReport(), sendJoystickDataThreadSafe(), sendParamMapRC(), sendSetupSigning(), PlanMasterController::sendToVehicle(), MavCommandQueue::sendWorker(), setCurrentMissionSequence(), setEstimatorOrigin(), setFlightMode(), VideoManager::setfullScreen(), startCalibration(), ParameterManager::tryHashCheckCacheLoad(), SensorsComponentController::usingUDPLink(), and MissionManager::writeArduPilotGuidedMissionItem().
vehicleType()
MAV_TYPE Vehicle::vehicleType () const inline
Definition at line 426 of file Vehicle.h.
Referenced by APMFirmwarePlugin::_internalParameterMetaDataFile(), airship(), APMAirframeComponent::APMAirframeComponent(), APMFailsafesComponent::description(), APMFlightSafetyComponent::description(), APMSafetyComponent::description(), fixedWing(), multiRotor(), rover(), MissionController::save(), MissionController::sendToVehiclePreCheck(), APMAdvancedTuningCopterComponent::setupSource(), APMFailsafesComponent::setupSource(), APMFlightSafetyComponent::setupSource(), APMMotorComponent::setupSource(), APMSafetyComponent::setupSource(), APMTuningComponent::setupSource(), PX4FlightBehavior::setupSource(), PX4TuningComponent::setupSource(), spacecraft(), sub(), APMFailsafesComponent::summaryQmlSource(), APMFlightSafetyComponent::summaryQmlSource(), APMSafetyComponent::summaryQmlSource(), PX4FirmwarePlugin::supportsNegativeThrust(), Vehicle(), APMAutoPilotPlugin::vehicleComponents(), and vtol().
vehicleTypeChanged
void Vehicle::vehicleTypeChanged () signal
Referenced by _offlineVehicleTypeSettingChanged().
vehicleTypeString()
QString Vehicle::vehicleTypeString () const
Definition at line 1761 of file Vehicle.cc.
References QGCMAVLink::mavTypeToString().
Referenced by ParameterManager::writeParametersToStream().
vehicleUID()
quint64 Vehicle::vehicleUID () const inline
Definition at line 662 of file Vehicle.h.
vehicleUIDChanged
void Vehicle::vehicleUIDChanged () signal
vehicleUIDStr()
QString Vehicle::vehicleUIDStr ()
Definition at line 1006 of file Vehicle.cc.
versionCompare() [1/2]
int Vehicle::versionCompare (const QString & compare) const
Used to check if running current version is equal or higher than the one being compared.
Definition at line 2750 of file Vehicle.cc.
References FirmwarePlugin::versionCompare().
Referenced by LandingComplexItem::_createDoLandStartItem(), FirmwarePlugin::_versionFileDownloadFinished(), and APMAutoPilotPlugin::vehicleComponents().
versionCompare() [2/2]
int Vehicle::versionCompare (int major, int minor, int patch) const
Definition at line 2755 of file Vehicle.cc.
References FirmwarePlugin::versionCompare().
vibrationFactGroup()
FactGroup * Vehicle::vibrationFactGroup ()
Definition at line 414 of file Vehicle.cc.
References _vibrationFactGroup.
virtualTabletJoystickValue()
void Vehicle::virtualTabletJoystickValue (double roll, double pitch, double yaw, double thrust)
Definition at line 1705 of file Vehicle.cc.
References sendJoystickDataThreadSafe().
vtol()
bool Vehicle::vtol () const
Definition at line 1756 of file Vehicle.cc.
References QGCMAVLink::isVTOL(), and vehicleType().
Referenced by MissionController::complexMissionItemNames(), TransectStyleComplexItem::hoverAndCaptureAllowed(), MissionController::insertLandItem(), MissionController::insertTakeoffItem(), APMFirmwarePlugin::isCapable(), PX4FirmwarePlugin::isCapable(), APMFirmwarePlugin::minimumTakeoffAltitudeMeters(), MissionFlightStatusCalculator::recalc(), MissionFlightStatusCalculator::reset(), SensorsComponent::SensorsComponent(), SensorsComponent::setupComplete(), SimpleMissionItem::showLoiterRadius(), and SensorsComponent::summaryQmlSource().
vtolInFwdFlight()
bool Vehicle::vtolInFwdFlight () const inline
Definition at line 502 of file Vehicle.h.
Referenced by setVtolInFwdFlight().
vtolInFwdFlightChanged
void Vehicle::vtolInFwdFlightChanged (bool vtolInFwdFlight) signal
windFactGroup()
FactGroup * Vehicle::windFactGroup ()
Definition at line 413 of file Vehicle.cc.
References _windFactGroup.
xConfigMotors()
bool Vehicle::xConfigMotors ()
Returns
true: X confiuration, false: Plus configuration
Definition at line 1418 of file Vehicle.cc.
References FirmwarePlugin::multiRotorXConfig().
Friends And Related Symbol Documentation
FactGroupListModel
friend class FactGroupListModel friend
Definition at line 103 of file Vehicle.h.
GimbalController
friend class GimbalController friend
Definition at line 110 of file Vehicle.h.
InitialConnectStateMachine
friend class InitialConnectStateMachine friend
Definition at line 101 of file Vehicle.h.
VehicleLinkManager
friend class VehicleLinkManager friend
Definition at line 102 of file Vehicle.h.
Member Data Documentation
_actuators
Actuators* Vehicle::_actuators = nullptr
Definition at line 1117 of file Vehicle.h.
Referenced by actuators(), and setActuatorsMetadata().
_altitudeTuningOffset
float Vehicle::_altitudeTuningOffset = qQNaN()
Definition at line 1054 of file Vehicle.h.
Referenced by setPIDTuningTelemetryMode().
_batteryFactGroupListModel
BatteryFactGroupListModel* Vehicle::_batteryFactGroupListModel = nullptr
Definition at line 1106 of file Vehicle.h.
Referenced by batteries().
_clockFactGroup
VehicleClockFactGroup* Vehicle::_clockFactGroup = nullptr
Definition at line 1089 of file Vehicle.h.
Referenced by clockFactGroup().
_clockFactGroupName
const QString Vehicle::_clockFactGroupName = QStringLiteral("clock")
Definition at line 1069 of file Vehicle.h.
_distanceSensorFactGroup
VehicleDistanceSensorFactGroup* Vehicle::_distanceSensorFactGroup = nullptr
Definition at line 1091 of file Vehicle.h.
Referenced by distanceSensorFactGroup().
_distanceSensorFactGroupName
const QString Vehicle::_distanceSensorFactGroupName = QStringLiteral("distanceSensor")
Definition at line 1071 of file Vehicle.h.
_efiFactGroup
VehicleEFIFactGroup* Vehicle::_efiFactGroup = nullptr
Definition at line 1097 of file Vehicle.h.
Referenced by efiFactGroup().
_efiFactGroupName
const QString Vehicle::_efiFactGroupName = QStringLiteral("efi")
Definition at line 1078 of file Vehicle.h.
_escStatusFactGroupListModel
EscStatusFactGroupListModel* Vehicle::_escStatusFactGroupListModel = nullptr
Definition at line 1107 of file Vehicle.h.
Referenced by escs().
_estimatorStatusFactGroup
VehicleEstimatorStatusFactGroup* Vehicle::_estimatorStatusFactGroup = nullptr
Definition at line 1094 of file Vehicle.h.
Referenced by estimatorStatusFactGroup().
_estimatorStatusFactGroupName
const QString Vehicle::_estimatorStatusFactGroupName = QStringLiteral("estimatorStatus")
Definition at line 1074 of file Vehicle.h.
_fixed_wing_airspeed_limits_available
bool Vehicle::_fixed_wing_airspeed_limits_available = false
Definition at line 1058 of file Vehicle.h.
Referenced by haveFWSpeedLimits().
_ftpManager
FTPManager* Vehicle::_ftpManager = nullptr
Definition at line 1115 of file Vehicle.h.
Referenced by ftpManager().
_generatorFactGroup
VehicleGeneratorFactGroup* Vehicle::_generatorFactGroup = nullptr
Definition at line 1096 of file Vehicle.h.
Referenced by generatorFactGroup().
_generatorFactGroupName
const QString Vehicle::_generatorFactGroupName = QStringLiteral("generator")
Definition at line 1077 of file Vehicle.h.
_geoFenceManager
GeoFenceManager* Vehicle::_geoFenceManager = nullptr
Definition at line 1112 of file Vehicle.h.
Referenced by geoFenceManager().
_gps2FactGroup
VehicleGPS2FactGroup* Vehicle::_gps2FactGroup = nullptr
Definition at line 1084 of file Vehicle.h.
Referenced by gps2FactGroup().
_gps2FactGroupName
const QString Vehicle::_gps2FactGroupName = QStringLiteral("gps2")
Definition at line 1064 of file Vehicle.h.
_gpsAggregateFactGroup
VehicleGPSAggregateFactGroup* Vehicle::_gpsAggregateFactGroup = nullptr
Definition at line 1085 of file Vehicle.h.
Referenced by gpsAggregateFactGroup().
_gpsAggregateFactGroupName
const QString Vehicle::_gpsAggregateFactGroupName = QStringLiteral("gpsAggregate")
Definition at line 1065 of file Vehicle.h.
_gpsFactGroup
VehicleGPSFactGroup* Vehicle::_gpsFactGroup = nullptr
Definition at line 1083 of file Vehicle.h.
Referenced by gpsFactGroup().
_gpsFactGroupName
const QString Vehicle::_gpsFactGroupName = QStringLiteral("gps")
Definition at line 1063 of file Vehicle.h.
_hygrometerFactGroup
VehicleHygrometerFactGroup* Vehicle::_hygrometerFactGroup = nullptr
Definition at line 1095 of file Vehicle.h.
Referenced by hygrometerFactGroup().
_hygrometerFactGroupName
const QString Vehicle::_hygrometerFactGroupName = QStringLiteral("hygrometer")
Definition at line 1076 of file Vehicle.h.
_initialConnectStateMachine
InitialConnectStateMachine* Vehicle::_initialConnectStateMachine = nullptr
Definition at line 1116 of file Vehicle.h.
Referenced by isInitialConnectComplete(), and Vehicle().
_localPositionFactGroup
VehicleLocalPositionFactGroup* Vehicle::_localPositionFactGroup = nullptr
Definition at line 1092 of file Vehicle.h.
Referenced by localPositionFactGroup(), and setPIDTuningTelemetryMode().
_localPositionFactGroupName
const QString Vehicle::_localPositionFactGroupName = QStringLiteral("localPosition")
Definition at line 1072 of file Vehicle.h.
_localPositionSetpointFactGroup
VehicleLocalPositionSetpointFactGroup* Vehicle::_localPositionSetpointFactGroup = nullptr
Definition at line 1093 of file Vehicle.h.
Referenced by localPositionSetpointFactGroup(), and setPIDTuningTelemetryMode().
_localPositionSetpointFactGroupName
const QString Vehicle::_localPositionSetpointFactGroupName = QStringLiteral("localPositionSetpoint")
Definition at line 1073 of file Vehicle.h.
_lowestBatteryChargeStateAnnouncedMap
QMap<uint8_t , uint8_t > Vehicle::_lowestBatteryChargeStateAnnouncedMap
Definition at line 1052 of file Vehicle.h.
_mavCommandMaxRetryCount
constexpr int Vehicle::_mavCommandMaxRetryCount = 3 static constexpr
Ack timeout used in unit tests — kept on Vehicle for source-compat with existing tests (mirrors MavCommandQueue::kTestAckTimeoutMs).
Definition at line 1045 of file Vehicle.h.
_missionManager
MissionManager* Vehicle::_missionManager = nullptr
Definition at line 1111 of file Vehicle.h.
Referenced by missionManager(), and ~Vehicle().
_multirotor_speed_limits_available
bool Vehicle::_multirotor_speed_limits_available = false
Definition at line 1057 of file Vehicle.h.
Referenced by haveMRSpeedLimits().
_radioStatusFactGroup
RadioStatusFactGroup* Vehicle::_radioStatusFactGroup = nullptr
Definition at line 1100 of file Vehicle.h.
Referenced by radioStatusFactGroup().
_radioStatusFactGroupName
const QString Vehicle::_radioStatusFactGroupName = QStringLiteral("radioStatus")
Definition at line 1080 of file Vehicle.h.
_rallyPointManager
RallyPointManager* Vehicle::_rallyPointManager = nullptr
Definition at line 1113 of file Vehicle.h.
Referenced by rallyPointManager().
_remoteIDManager
RemoteIDManager* Vehicle::_remoteIDManager = nullptr
Definition at line 1118 of file Vehicle.h.
Referenced by remoteIDManager().
_rpmFactGroup
VehicleRPMFactGroup* Vehicle::_rpmFactGroup = nullptr
Definition at line 1098 of file Vehicle.h.
Referenced by rpmFactGroup().
_rpmFactGroupName
const QString Vehicle::_rpmFactGroupName = QStringLiteral("rpm")
Definition at line 1079 of file Vehicle.h.
_servoOutputRawValues
QVector<int> Vehicle::_servoOutputRawValues = QVector<int>(16, -1)
Definition at line 1103 of file Vehicle.h.
_setpointFactGroup
VehicleSetpointFactGroup* Vehicle::_setpointFactGroup = nullptr
Definition at line 1090 of file Vehicle.h.
Referenced by setPIDTuningTelemetryMode(), and setpointFactGroup().
_setpointFactGroupName
const QString Vehicle::_setpointFactGroupName = QStringLiteral("setpoint")
Definition at line 1070 of file Vehicle.h.
_standardModes
StandardModes* Vehicle::_standardModes = nullptr
Definition at line 1119 of file Vehicle.h.
_temperatureFactGroup
VehicleTemperatureFactGroup* Vehicle::_temperatureFactGroup = nullptr
Definition at line 1088 of file Vehicle.h.
Referenced by temperatureFactGroup().
_temperatureFactGroupName
const QString Vehicle::_temperatureFactGroupName = QStringLiteral("temperature")
Definition at line 1068 of file Vehicle.h.
_terrainFactGroup
TerrainFactGroup* Vehicle::_terrainFactGroup = nullptr
Definition at line 1099 of file Vehicle.h.
Referenced by terrainFactGroup().
_terrainFactGroupName
const QString Vehicle::_terrainFactGroupName = QStringLiteral("terrain")
Definition at line 1075 of file Vehicle.h.
_terrainProtocolHandler
TerrainProtocolHandler* Vehicle::_terrainProtocolHandler = nullptr
Definition at line 1109 of file Vehicle.h.
_terrainQueryCoordinator
TerrainQueryCoordinator* Vehicle::_terrainQueryCoordinator = nullptr
Definition at line 1122 of file Vehicle.h.
Referenced by doSetHome(), and guidedModeROI().
_vehicleFactGroup
VehicleFactGroup* Vehicle::_vehicleFactGroup
Definition at line 1082 of file Vehicle.h.
Referenced by vehicleFactGroup().
_vehicleFactGroupName
const QString Vehicle::_vehicleFactGroupName = QStringLiteral("vehicle")
Definition at line 1062 of file Vehicle.h.
_vehicleLinkManager
VehicleLinkManager* Vehicle::_vehicleLinkManager = nullptr
Definition at line 1114 of file Vehicle.h.
Referenced by closeVehicle(), and vehicleLinkManager().
_vibrationFactGroup
VehicleVibrationFactGroup* Vehicle::_vibrationFactGroup = nullptr
Definition at line 1087 of file Vehicle.h.
Referenced by vibrationFactGroup().
_vibrationFactGroupName
const QString Vehicle::_vibrationFactGroupName = QStringLiteral("vibration")
Definition at line 1067 of file Vehicle.h.
_windFactGroup
VehicleWindFactGroup* Vehicle::_windFactGroup = nullptr
Definition at line 1086 of file Vehicle.h.
Referenced by windFactGroup().
_windFactGroupName
const QString Vehicle::_windFactGroupName = QStringLiteral("wind")
Definition at line 1066 of file Vehicle.h.
kTestMavCommandAckTimeoutMs
constexpr int Vehicle::kTestMavCommandAckTimeoutMs = 500 static constexpr
Definition at line 1046 of file Vehicle.h.
kTestMavCommandMaxWaitMs
constexpr int Vehicle::kTestMavCommandMaxWaitMs = kTestMavCommandAckTimeoutMs * _mavCommandMaxRetryCount * 2 static constexpr
Definition at line 1047 of file Vehicle.h.
MAV_AUTOPILOT_TRACK
const MAV_AUTOPILOT Vehicle::MAV_AUTOPILOT_TRACK = MAV_AUTOPILOT_ENUM_END static
Definition at line 123 of file Vehicle.h.
Referenced by Vehicle().
MAV_TYPE_TRACK
const MAV_TYPE Vehicle::MAV_TYPE_TRACK = MAV_TYPE_ENUM_END static
Definition at line 124 of file Vehicle.h.
The documentation for this class was generated from the following files:
src/Vehicle/Vehicle.h
src/Vehicle/Vehicle.cc