QGroundControl: OnboardLogController Class Reference
OnboardLogController Class Reference
#include <OnboardLogController.h>
Signals
void requestingListChanged ()
void downloadingLogsChanged ()
void selectionChanged ()
void compressLogsChanged ()
void compressingChanged ()
void compressionProgressChanged ()
void compressionComplete (const QString &outputPath, const QString &error)
Public Member Functions
OnboardLogController (QObject *parent=nullptr)
~OnboardLogController ()
void refresh ()
void download (const QString &path=QString())
void eraseAll ()
void cancel ()
bool compressLogs () const
void setCompressLogs (bool compress)
bool compressing () const
float compressionProgress () const
bool compressLogFile (const QString &logPath)
Compress a single log file.
void cancelCompression ()
Cancel compression.
Detailed Description
Definition at line 14 of file OnboardLogController.h.
Constructor & Destructor Documentation
OnboardLogController()
OnboardLogController::OnboardLogController (QObject * parent = nullptr) explicit
Definition at line 20 of file OnboardLogController.cc.
References MultiVehicleManager::activeVehicleChanged().
~OnboardLogController()
OnboardLogController::~OnboardLogController ()
Definition at line 35 of file OnboardLogController.cc.
Member Function Documentation
cancel()
void OnboardLogController::cancel ()
Definition at line 465 of file OnboardLogController.cc.
cancelCompression()
void OnboardLogController::cancelCompression ()
Cancel compression.
Definition at line 664 of file OnboardLogController.cc.
compressing()
bool OnboardLogController::compressing () const inline
Definition at line 41 of file OnboardLogController.h.
compressingChanged
void OnboardLogController::compressingChanged () signal
compressionComplete
void OnboardLogController::compressionComplete (const QString & outputPath, const QString & error) signal
compressionProgress()
float OnboardLogController::compressionProgress () const inline
Definition at line 42 of file OnboardLogController.h.
compressionProgressChanged
void OnboardLogController::compressionProgressChanged () signal
compressLogFile()
bool OnboardLogController::compressLogFile (const QString & logPath)
Compress a single log file.
Definition at line 657 of file OnboardLogController.cc.
compressLogs()
bool OnboardLogController::compressLogs () const inline
Definition at line 39 of file OnboardLogController.h.
compressLogsChanged
void OnboardLogController::compressLogsChanged () signal
Referenced by setCompressLogs().
download()
void OnboardLogController::download (const QString & path = QString())
Definition at line 40 of file OnboardLogController.cc.
References AppSettings::logSavePath().
downloadingLogsChanged
void OnboardLogController::downloadingLogsChanged () signal
eraseAll()
void OnboardLogController::eraseAll ()
Definition at line 503 of file OnboardLogController.cc.
References Vehicle::defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::getSystemId(), Vehicle::id(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), refresh(), Vehicle::sendMessageOnLinkThreadSafe(), and Vehicle::vehicleLinkManager().
refresh()
void OnboardLogController::refresh ()
Definition at line 442 of file OnboardLogController.cc.
References QmlObjectListModel::clearAndDeleteContents().
Referenced by eraseAll().
requestingListChanged
void OnboardLogController::requestingListChanged () signal
selectionChanged
void OnboardLogController::selectionChanged () signal
setCompressLogs()
void OnboardLogController::setCompressLogs (bool compress)
Definition at line 649 of file OnboardLogController.cc.
References compressLogsChanged().
The documentation for this class was generated from the following files:
src/AnalyzeView/OnboardLogs/OnboardLogController.h
src/AnalyzeView/OnboardLogs/OnboardLogController.cc