QGroundControl: PX4FirmwareUpgradeThreadController Class Reference
PX4FirmwareUpgradeThreadController Class Reference
Provides methods to interact with the bootloader. The commands themselves are signalled across to PX4FirmwareUpgradeThreadWorker so that they run on the separate thread.
#include <PX4FirmwareUpgradeThread.h>
Signals
void foundBoard (bool firstAttempt, const QGCSerialPortInfo &portInfo, int boardType, QString boardName)
void noBoardFound (void)
void boardGone (void)
void foundBoardInfo (int bootloaderVersion, int boardID, int flashSize)
void error (const QString &errorString)
void status (const QString &status)
void eraseStarted (void)
void eraseComplete (void)
void flashComplete (void)
void updateProgress (int curr, int total)
void _initThreadWorker (void)
void _startFindBoardLoopOnThread (void)
void _rebootOnThread (void)
void _flashOnThread (void)
void _cancel (void)
Public Member Functions
PX4FirmwareUpgradeThreadController (QObject *parent=nullptr)
~PX4FirmwareUpgradeThreadController (void)
void startFindBoardLoop (void)
Begins the process of searching for a supported board connected to any serial port. This will continue until cancelFind is called. Signals foundBoard and boardGone as boards come and go.
void cancel (void)
void reboot (void)
Sends a reboot command to the bootloader.
void flash (const FirmwareImage *image)
const FirmwareImage * image (void)
Detailed Description
Provides methods to interact with the bootloader. The commands themselves are signalled across to PX4FirmwareUpgradeThreadWorker so that they run on the separate thread.
Definition at line 64 of file PX4FirmwareUpgradeThread.h.
Constructor & Destructor Documentation
PX4FirmwareUpgradeThreadController()
PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController (QObject * parent = nullptr)
Definition at line 197 of file PX4FirmwareUpgradeThread.cc.
References _initThreadWorker(), PX4FirmwareUpgradeThreadWorker::boardGone(), PX4FirmwareUpgradeThreadWorker::eraseComplete(), PX4FirmwareUpgradeThreadWorker::eraseStarted(), PX4FirmwareUpgradeThreadWorker::error(), PX4FirmwareUpgradeThreadWorker::flashComplete(), PX4FirmwareUpgradeThreadWorker::foundBoard(), PX4FirmwareUpgradeThreadWorker::foundBoardInfo(), PX4FirmwareUpgradeThreadWorker::noBoardFound(), PX4FirmwareUpgradeThreadWorker::status(), and PX4FirmwareUpgradeThreadWorker::updateProgress().
~PX4FirmwareUpgradeThreadController()
PX4FirmwareUpgradeThreadController::~PX4FirmwareUpgradeThreadController (void)
Definition at line 220 of file PX4FirmwareUpgradeThread.cc.
Member Function Documentation
_cancel
void PX4FirmwareUpgradeThreadController::_cancel (void) signal
Referenced by cancel(), and PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker().
_flashOnThread
void PX4FirmwareUpgradeThreadController::_flashOnThread (void) signal
Referenced by flash(), and PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker().
_initThreadWorker
void PX4FirmwareUpgradeThreadController::_initThreadWorker (void) signal
Referenced by PX4FirmwareUpgradeThreadController(), and PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker().
_rebootOnThread
void PX4FirmwareUpgradeThreadController::_rebootOnThread (void) signal
Referenced by PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker(), and reboot().
_startFindBoardLoopOnThread
void PX4FirmwareUpgradeThreadController::_startFindBoardLoopOnThread (void) signal
Referenced by PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker(), and startFindBoardLoop().
boardGone
void PX4FirmwareUpgradeThreadController::boardGone (void) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
cancel()
void PX4FirmwareUpgradeThreadController::cancel (void)
Definition at line 234 of file PX4FirmwareUpgradeThread.cc.
References _cancel().
Referenced by FirmwareUpgradeController::cancel().
eraseComplete
void PX4FirmwareUpgradeThreadController::eraseComplete (void) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
eraseStarted
void PX4FirmwareUpgradeThreadController::eraseStarted (void) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
error
void PX4FirmwareUpgradeThreadController::error (const QString & errorString) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
flash()
void PX4FirmwareUpgradeThreadController::flash (const FirmwareImage * image)
Definition at line 240 of file PX4FirmwareUpgradeThread.cc.
References _flashOnThread(), and image().
flashComplete
void PX4FirmwareUpgradeThreadController::flashComplete (void) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
foundBoard
void PX4FirmwareUpgradeThreadController::foundBoard (bool firstAttempt, const QGCSerialPortInfo & portInfo, int boardType, QString boardName) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
foundBoardInfo
void PX4FirmwareUpgradeThreadController::foundBoardInfo (int bootloaderVersion, int boardID, int flashSize) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
image()
const FirmwareImage * PX4FirmwareUpgradeThreadController::image (void) inline
Definition at line 83 of file PX4FirmwareUpgradeThread.h.
Referenced by flash().
noBoardFound
void PX4FirmwareUpgradeThreadController::noBoardFound (void) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
reboot()
void PX4FirmwareUpgradeThreadController::reboot (void) inline
Sends a reboot command to the bootloader.
Definition at line 79 of file PX4FirmwareUpgradeThread.h.
References _rebootOnThread().
startFindBoardLoop()
void PX4FirmwareUpgradeThreadController::startFindBoardLoop (void)
Begins the process of searching for a supported board connected to any serial port. This will continue until cancelFind is called. Signals foundBoard and boardGone as boards come and go.
Definition at line 228 of file PX4FirmwareUpgradeThread.cc.
References _startFindBoardLoopOnThread().
status
void PX4FirmwareUpgradeThreadController::status (const QString & status) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
updateProgress
void PX4FirmwareUpgradeThreadController::updateProgress (int curr, int total) signal
Referenced by FirmwareUpgradeController::FirmwareUpgradeController().
The documentation for this class was generated from the following files:
src/Vehicle/VehicleSetup/PX4FirmwareUpgradeThread.h
src/Vehicle/VehicleSetup/PX4FirmwareUpgradeThread.cc