QGroundControl: QGCSerialPortInfo Class Reference
QGCSerialPortInfo Class Reference
#include <QGCSerialPortInfo.h>
Public Types
enum BoardType_t {
BoardTypePixhawk = 0 , BoardTypeSiKRadio , BoardTypeOpenPilot , BoardTypeRTKGPS ,
BoardTypeUnknown
}
Public Member Functions
QGCSerialPortInfo ()
QGCSerialPortInfo (const QSerialPort &port)
~QGCSerialPortInfo ()
bool getBoardInfo (BoardType_t &boardType, QString &name) const
bool canFlash () const
bool isBootloader () const
bool isBlackCube () const
Public Member Functions inherited from QSerialPortInfo
QSerialPortInfo ()
QSerialPortInfo (const QSerialPort &port)
QSerialPortInfo (const QString &name)
QSerialPortInfo (const QSerialPortInfo &other)
QSerialPortInfo (const QSerialPortInfoPrivate &dd)
~QSerialPortInfo ()
QSerialPortInfo & operator= (const QSerialPortInfo &other)
void swap (QSerialPortInfo &other)
QString portName () const
QString systemLocation () const
QString description () const
QString manufacturer () const
QString serialNumber () const
quint16 vendorIdentifier () const
quint16 productIdentifier () const
bool hasVendorIdentifier () const
bool hasProductIdentifier () const
bool isNull () const
Static Public Member Functions
static bool isSystemPort (const QSerialPortInfo &port)
static QList< QGCSerialPortInfo > availablePorts ()
Override of QSerialPortInfo::availablePorts.
Static Public Member Functions inherited from QSerialPortInfo
static QList< qint32 > standardBaudRates ()
static QList< QSerialPortInfo > availablePorts ()
Friends
class QGCSerialPortInfoTest
Detailed Description
QGC's version of Qt QSerialPortInfo. It provides additional information about board types that QGC cares about.
Definition at line 18 of file QGCSerialPortInfo.h.
Member Enumeration Documentation
BoardType_t
enum QGCSerialPortInfo::BoardType_t
Enumerator
BoardTypePixhawk
BoardTypeSiKRadio
BoardTypeOpenPilot
BoardTypeRTKGPS
BoardTypeUnknown
Definition at line 26 of file QGCSerialPortInfo.h.
Constructor & Destructor Documentation
QGCSerialPortInfo() [1/2]
QGCSerialPortInfo::QGCSerialPortInfo ()
Definition at line 19 of file QGCSerialPortInfo.cc.
QGCSerialPortInfo() [2/2]
QGCSerialPortInfo::QGCSerialPortInfo (const QSerialPort & port) explicit
Definition at line 25 of file QGCSerialPortInfo.cc.
~QGCSerialPortInfo()
QGCSerialPortInfo::~QGCSerialPortInfo ()
Definition at line 31 of file QGCSerialPortInfo.cc.
Member Function Documentation
availablePorts()
QList< QGCSerialPortInfo > QGCSerialPortInfo::availablePorts () static
Override of QSerialPortInfo::availablePorts.
Definition at line 257 of file QGCSerialPortInfo.cc.
References QSerialPortInfo::availablePorts(), availablePorts(), and isSystemPort().
Referenced by FirmwareUpgradeController::availableBoardsName(), and availablePorts().
canFlash()
bool QGCSerialPortInfo::canFlash () const
Returns
true: we can flash this board type
Definition at line 314 of file QGCSerialPortInfo.cc.
References BoardTypePixhawk, BoardTypeSiKRadio, and getBoardInfo().
getBoardInfo()
bool QGCSerialPortInfo::getBoardInfo (QGCSerialPortInfo::BoardType_t & boardType, QString & name) const
Definition at line 189 of file QGCSerialPortInfo.cc.
References BoardTypeUnknown, QSerialPortInfo::description(), QSerialPortInfo::isNull(), QSerialPortInfo::manufacturer(), QSerialPortInfo::productIdentifier(), and QSerialPortInfo::vendorIdentifier().
Referenced by canFlash(), and isBootloader().
isBlackCube()
bool QGCSerialPortInfo::isBlackCube () const
Returns
true: Board is BlackCube
Definition at line 285 of file QGCSerialPortInfo.cc.
References QSerialPortInfo::description().
isBootloader()
bool QGCSerialPortInfo::isBootloader () const
Returns
true: Board is currently in bootloader
Definition at line 274 of file QGCSerialPortInfo.cc.
References BoardTypePixhawk, QSerialPortInfo::description(), and getBoardInfo().
Referenced by SerialWorker::connectToPort().
isSystemPort()
bool QGCSerialPortInfo::isSystemPort (const QSerialPortInfo & port) static
Known operating system peripherals that are NEVER a peripheral that we should connect to.
Returns
true: Port is a system port and not an autopilot
Definition at line 290 of file QGCSerialPortInfo.cc.
References QSerialPortInfo::systemLocation().
Referenced by availablePorts().
Friends And Related Symbol Documentation
QGCSerialPortInfoTest
friend class QGCSerialPortInfoTest friend
Definition at line 20 of file QGCSerialPortInfo.h.
The documentation for this class was generated from the following files:
src/Comms/QGCSerialPortInfo.h
src/Comms/QGCSerialPortInfo.cc