QGroundControl: UDPWorker Class Reference
UDPWorker Class Reference
#include <UDPLink.h>
Public Slots
void setupSocket ()
void connectLink ()
void disconnectLink ()
void writeData (const QByteArray &data)
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &errorString)
void dataReceived (const QByteArray &data)
void dataSent (const QByteArray &data)
Public Member Functions
UDPWorker (const UDPConfiguration *config, QObject *parent=nullptr)
virtual ~UDPWorker ()
bool isConnected () const
Detailed Description
Definition at line 106 of file UDPLink.h.
Constructor & Destructor Documentation
UDPWorker()
UDPWorker::UDPWorker (const UDPConfiguration * config, QObject * parent = nullptr) explicit
Definition at line 256 of file UDPLink.cc.
~UDPWorker()
UDPWorker::~UDPWorker () virtual
Definition at line 263 of file UDPLink.cc.
References disconnectLink().
Member Function Documentation
connected
void UDPWorker::connected () signal
Referenced by UDPLink::UDPLink().
connectLink
void UDPWorker::connectLink () slot
Definition at line 314 of file UDPLink.cc.
References errorOccurred(), and isConnected().
dataReceived
void UDPWorker::dataReceived (const QByteArray & data) signal
Referenced by UDPLink::UDPLink().
dataSent
void UDPWorker::dataSent (const QByteArray & data) signal
Referenced by UDPLink::UDPLink(), and writeData().
disconnected
void UDPWorker::disconnected () signal
Referenced by UDPLink::UDPLink().
disconnectLink
void UDPWorker::disconnectLink () slot
Definition at line 352 of file UDPLink.cc.
References isConnected().
Referenced by ~UDPWorker().
errorOccurred
void UDPWorker::errorOccurred (const QString & errorString) signal
Referenced by connectLink(), UDPLink::UDPLink(), and writeData().
isConnected()
bool UDPWorker::isConnected () const
Definition at line 270 of file UDPLink.cc.
Referenced by connectLink(), disconnectLink(), UDPLink::isConnected(), and writeData().
setupSocket
void UDPWorker::setupSocket () slot
Definition at line 275 of file UDPLink.cc.
Referenced by UDPLink::UDPLink().
writeData
void UDPWorker::writeData (const QByteArray & data) slot
Definition at line 371 of file UDPLink.cc.
References dataSent(), errorOccurred(), and isConnected().
The documentation for this class was generated from the following files:
src/Comms/UDPLink.h
src/Comms/UDPLink.cc