QGroundControl: MavlinkCameraControl Class Reference
MavlinkCameraControl Class Reference abstract
Abstract base class for all camera controls: real and simulated.
#include <MavlinkCameraControl.h>
Public Types
enum CameraMode { CAM_MODE_UNDEFINED = -1 , CAM_MODE_PHOTO = 0 , CAM_MODE_VIDEO = 1 , CAM_MODE_SURVEY = 2 }
enum PhotoCaptureMode { PHOTO_CAPTURE_SINGLE = 0 , PHOTO_CAPTURE_TIMELAPSE }
enum CaptureVideoState { CaptureVideoStateDisabled = 0 , CaptureVideoStateIdle , CaptureVideoStateCapturing }
enum CapturePhotosState { CapturePhotosStateDisabled = 0 , CapturePhotosStateIdle , CapturePhotosStateCapturingSinglePhoto , CapturePhotosStateCapturingMultiplePhotos }
enum StorageStatus { STORAGE_EMPTY = STORAGE_STATUS_EMPTY , STORAGE_UNFORMATTED = STORAGE_STATUS_UNFORMATTED , STORAGE_READY = STORAGE_STATUS_READY , STORAGE_NOT_SUPPORTED = STORAGE_STATUS_NOT_SUPPORTED }
enum ThermalViewMode { THERMAL_OFF = 0 , THERMAL_BLEND , THERMAL_FULL , THERMAL_PIP }
enum TrackingStatus {
TRACKING_UNKNOWN = 0 , TRACKING_SUPPORTED = 1 , TRACKING_ENABLED = 2 , TRACKING_RECTANGLE = 4 ,
TRACKING_POINT = 8
}
Signals
void infoChanged ()
void videoCaptureStatusChanged ()
void photoCaptureStatusChanged ()
void photoCaptureModeChanged ()
void photoLapseChanged ()
void photoLapseCountChanged ()
void cameraModeChanged ()
void activeSettingsChanged ()
void storageFreeChanged ()
void storageTotalChanged ()
void batteryRemainingChanged ()
void dataReady (const QByteArray &data)
void parametersReady ()
void zoomLevelChanged ()
void focusLevelChanged ()
void streamsChanged ()
void currentStreamChanged ()
void thermalStreamChanged ()
void autoStreamChanged ()
void recordTimeChanged ()
void streamLabelsChanged ()
void trackingEnabledChanged ()
void trackingImageStatusChanged ()
void thermalModeChanged ()
void thermalOpacityChanged ()
void storageStatusChanged ()
void captureVideoStateChanged ()
void capturePhotosStateChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Public Member Functions
MavlinkCameraControl (Vehicle *vehicle, QObject *parent=nullptr)
virtual ~MavlinkCameraControl ()
virtual void setCameraModeVideo ()=0
virtual void setCameraModePhoto ()=0
virtual void toggleCameraMode ()=0
virtual bool takePhoto ()=0
virtual bool stopTakePhoto ()=0
virtual bool startVideoRecording ()=0
virtual bool stopVideoRecording ()=0
virtual bool toggleVideoRecording ()=0
virtual void resetSettings ()=0
virtual void formatCard (int id=1)=0
virtual void stepZoom (int direction)=0
virtual void startZoom (int direction)=0
virtual void stopZoom ()=0
virtual void stopStream ()=0
virtual void resumeStream ()=0
virtual void startTracking (QRectF rec)=0
virtual void startTracking (QPointF point, double radius)=0
virtual void stopTracking ()=0
virtual int version () const =0
virtual QString modelName () const =0
virtual QString vendor () const =0
virtual QString firmwareVersion () const =0
virtual qreal focalLength () const =0
virtual QSizeF sensorSize () const =0
virtual QSize resolution () const =0
virtual bool capturesVideo () const =0
virtual bool capturesPhotos () const =0
virtual bool hasModes () const =0
virtual bool hasZoom () const =0
virtual bool hasFocus () const =0
virtual bool hasTracking () const =0
virtual bool hasVideoStream () const =0
virtual bool photosInVideoMode () const =0
virtual bool videoInPhotoMode () const =0
virtual CaptureVideoState captureVideoState () const =0
virtual CapturePhotosState capturePhotosState () const =0
virtual int compID () const =0
virtual bool isBasic () const =0
virtual PhotoCaptureMode photoCaptureMode () const
virtual qreal photoLapse () const
virtual int photoLapseCount () const
virtual CameraMode cameraMode () const
virtual StorageStatus storageStatus () const =0
virtual QStringList activeSettings () const =0
virtual quint32 storageFree () const =0
virtual QString storageFreeStr () const =0
virtual quint32 storageTotal () const =0
virtual int batteryRemaining () const =0
virtual QString batteryRemainingStr () const =0
virtual bool paramComplete () const =0
virtual qreal zoomLevel () const =0
virtual qreal focusLevel () const =0
virtual QmlObjectListModel * streams ()=0
virtual QGCVideoStreamInfo * currentStreamInstance ()=0
virtual QGCVideoStreamInfo * thermalStreamInstance ()=0
virtual int currentStream () const =0
virtual void setCurrentStream (int stream)=0
virtual bool autoStream () const =0
virtual quint32 recordTime () const =0
virtual QString recordTimeStr () const =0
virtual Fact * exposureMode ()=0
virtual Fact * ev ()=0
virtual Fact * iso ()=0
virtual Fact * shutterSpeed ()=0
virtual Fact * aperture ()=0
virtual Fact * wb ()=0
virtual Fact * mode ()=0
virtual QStringList streamLabels () const =0
Stream names to show the user (for selection)
virtual ThermalViewMode thermalMode () const =0
virtual void setThermalMode (ThermalViewMode mode)=0
virtual double thermalOpacity () const =0
virtual void setThermalOpacity (double val)=0
virtual void setZoomLevel (qreal level)=0
virtual void setFocusLevel (qreal level)=0
virtual void setCameraMode (CameraMode cameraMode)=0
virtual void setPhotoCaptureMode (PhotoCaptureMode mode)=0
virtual void setPhotoLapse (qreal interval)=0
virtual void setPhotoLapseCount (int count)=0
virtual bool trackingEnabled () const =0
virtual void setTrackingEnabled (bool set)=0
virtual TrackingStatus trackingStatus () const =0
virtual bool trackingImageStatus () const =0
virtual QRectF trackingImageRect () const =0
virtual void factChanged (Fact *pFact)=0
Notify controller a parameter has changed.
virtual bool incomingParameter (Fact *pFact, QVariant &newValue)=0
Allow controller to modify or invalidate incoming parameter.
virtual bool validateParameter (Fact *pFact, QVariant &newValue)=0
Allow controller to modify or invalidate parameter change.
virtual void handleBatteryStatus (const mavlink_battery_status_t &bs)=0
virtual void handleCameraCaptureStatus (const mavlink_camera_capture_status_t &cameraCaptureStatus)=0
virtual void handleParamExtAck (const mavlink_param_ext_ack_t &paramExtAck)=0
virtual void handleParamExtValue (const mavlink_param_ext_value_t &paramExtValue)=0
virtual void handleCameraSettings (const mavlink_camera_settings_t &settings)=0
virtual void handleStorageInformation (const mavlink_storage_information_t &storageInformation)=0
virtual void handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t &trackingImageStatus)=0
virtual void handleVideoStreamInformation (const mavlink_video_stream_information_t &videoStreamInformation)=0
virtual void handleVideoStreamStatus (const mavlink_video_stream_status_t &videoStreamStatus)=0
QString cameraModeToStr (CameraMode mode)
QString captureImageStatusToStr (uint8_t image_status)
QString captureVideoStatusToStr (uint8_t video_status)
QString storageStatusToStr (uint8_t status)
Protected Types
enum VideoCaptureStatus { VIDEO_CAPTURE_STATUS_STOPPED = 0 , VIDEO_CAPTURE_STATUS_RUNNING , VIDEO_CAPTURE_STATUS_LAST , VIDEO_CAPTURE_STATUS_UNDEFINED = 255 }
enum PhotoCaptureStatus {
PHOTO_CAPTURE_IDLE = 0 , PHOTO_CAPTURE_IN_PROGRESS , PHOTO_CAPTURE_INTERVAL_IDLE , PHOTO_CAPTURE_INTERVAL_IN_PROGRESS ,
PHOTO_CAPTURE_LAST , PHOTO_CAPTURE_STATUS_UNDEFINED = 255
}
Protected Slots
virtual void _paramDone ()=0
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Protected Member Functions
VideoCaptureStatus _videoCaptureStatus () const
PhotoCaptureStatus _photoCaptureStatus () const
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
Vehicle * _vehicle = nullptr
CameraMode _cameraMode = CAM_MODE_UNDEFINED
VideoCaptureStatus _videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED
PhotoCaptureStatus _photoCaptureStatusValue = PHOTO_CAPTURE_IDLE
PhotoCaptureMode _photoCaptureMode = PHOTO_CAPTURE_SINGLE
qreal _photoLapse = 1.0
int _photoLapseCount = 0
QTimer _videoRecordTimeUpdateTimer
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Abstract base class for all camera controls: real and simulated.
Definition at line 22 of file MavlinkCameraControl.h.
Member Enumeration Documentation
CameraMode
enum MavlinkCameraControl::CameraMode
Enumerator
CAM_MODE_UNDEFINED
CAM_MODE_PHOTO
CAM_MODE_VIDEO
CAM_MODE_SURVEY
Definition at line 99 of file MavlinkCameraControl.h.
CapturePhotosState
enum MavlinkCameraControl::CapturePhotosState
Enumerator
CapturePhotosStateDisabled
CapturePhotosStateIdle
CapturePhotosStateCapturingSinglePhoto
CapturePhotosStateCapturingMultiplePhotos
Definition at line 120 of file MavlinkCameraControl.h.
CaptureVideoState
enum MavlinkCameraControl::CaptureVideoState
Enumerator
CaptureVideoStateDisabled
CaptureVideoStateIdle
CaptureVideoStateCapturing
Definition at line 113 of file MavlinkCameraControl.h.
PhotoCaptureMode
enum MavlinkCameraControl::PhotoCaptureMode
Enumerator
PHOTO_CAPTURE_SINGLE
PHOTO_CAPTURE_TIMELAPSE
Definition at line 107 of file MavlinkCameraControl.h.
PhotoCaptureStatus
enum MavlinkCameraControl::PhotoCaptureStatus protected
Enumerator
PHOTO_CAPTURE_IDLE
PHOTO_CAPTURE_IN_PROGRESS
PHOTO_CAPTURE_INTERVAL_IDLE
PHOTO_CAPTURE_INTERVAL_IN_PROGRESS
PHOTO_CAPTURE_LAST
PHOTO_CAPTURE_STATUS_UNDEFINED
Definition at line 307 of file MavlinkCameraControl.h.
StorageStatus
enum MavlinkCameraControl::StorageStatus
Enumerator
STORAGE_EMPTY
STORAGE_UNFORMATTED
STORAGE_READY
STORAGE_NOT_SUPPORTED
Definition at line 128 of file MavlinkCameraControl.h.
ThermalViewMode
enum MavlinkCameraControl::ThermalViewMode
Enumerator
THERMAL_OFF
THERMAL_BLEND
THERMAL_FULL
THERMAL_PIP
Definition at line 136 of file MavlinkCameraControl.h.
TrackingStatus
enum MavlinkCameraControl::TrackingStatus
Enumerator
TRACKING_UNKNOWN
TRACKING_SUPPORTED
TRACKING_ENABLED
TRACKING_RECTANGLE
TRACKING_POINT
Definition at line 144 of file MavlinkCameraControl.h.
VideoCaptureStatus
enum MavlinkCameraControl::VideoCaptureStatus protected
Enumerator
VIDEO_CAPTURE_STATUS_STOPPED
VIDEO_CAPTURE_STATUS_RUNNING
VIDEO_CAPTURE_STATUS_LAST
VIDEO_CAPTURE_STATUS_UNDEFINED
Definition at line 300 of file MavlinkCameraControl.h.
Constructor & Destructor Documentation
MavlinkCameraControl()
MavlinkCameraControl::MavlinkCameraControl (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 7 of file MavlinkCameraControl.cc.
~MavlinkCameraControl()
MavlinkCameraControl::~MavlinkCameraControl () virtual
Definition at line 14 of file MavlinkCameraControl.cc.
Member Function Documentation
_paramDone
virtual void MavlinkCameraControl::_paramDone () protected pure virtual slot
Referenced by QGCCameraParamIO::handleParamValue(), and QGCCameraParamIO::paramRequest().
_photoCaptureStatus()
PhotoCaptureStatus MavlinkCameraControl::_photoCaptureStatus () const inline protected
Definition at line 317 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::capturePhotosState(), SimulatedCameraControl::capturePhotosState(), VehicleCameraControl::captureVideoState(), SimulatedCameraControl::captureVideoState(), VehicleCameraControl::handleCameraCaptureStatus(), and SimulatedCameraControl::takePhoto().
_videoCaptureStatus()
VideoCaptureStatus MavlinkCameraControl::_videoCaptureStatus () const inline protected
Definition at line 316 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), VehicleCameraControl::captureVideoState(), SimulatedCameraControl::captureVideoState(), VehicleCameraControl::handleCameraCaptureStatus(), SimulatedCameraControl::startVideoRecording(), SimulatedCameraControl::stopVideoRecording(), and SimulatedCameraControl::toggleVideoRecording().
activeSettings()
virtual QStringList MavlinkCameraControl::activeSettings () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
activeSettingsChanged
void MavlinkCameraControl::activeSettingsChanged () signal
aperture()
virtual Fact * MavlinkCameraControl::aperture () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
autoStream()
virtual bool MavlinkCameraControl::autoStream () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
autoStreamChanged
void MavlinkCameraControl::autoStreamChanged () signal
Referenced by VehicleCameraControl::_streamInfoTimeout(), and VehicleCameraControl::handleVideoStreamInformation().
batteryRemaining()
virtual int MavlinkCameraControl::batteryRemaining () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
batteryRemainingChanged
void MavlinkCameraControl::batteryRemainingChanged () signal
Referenced by VehicleCameraControl::handleBatteryStatus().
batteryRemainingStr()
virtual QString MavlinkCameraControl::batteryRemainingStr () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
cameraMode()
virtual CameraMode MavlinkCameraControl::cameraMode () const inline virtual
Definition at line 196 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::setCameraMode(), and SimulatedCameraControl::setCameraMode().
cameraModeChanged
void MavlinkCameraControl::cameraModeChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setCameraMode(), and SimulatedCameraControl::SimulatedCameraControl().
cameraModeToStr()
QString MavlinkCameraControl::cameraModeToStr (CameraMode mode)
Definition at line 63 of file MavlinkCameraControl.cc.
References CAM_MODE_PHOTO, CAM_MODE_SURVEY, CAM_MODE_UNDEFINED, CAM_MODE_VIDEO, and mode().
Referenced by VehicleCameraControl::setCameraMode(), SimulatedCameraControl::setCameraMode(), and SimulatedCameraControl::takePhoto().
captureImageStatusToStr()
QString MavlinkCameraControl::captureImageStatusToStr (uint8_t image_status)
Definition at line 19 of file MavlinkCameraControl.cc.
References PHOTO_CAPTURE_IDLE, PHOTO_CAPTURE_IN_PROGRESS, PHOTO_CAPTURE_INTERVAL_IDLE, and PHOTO_CAPTURE_INTERVAL_IN_PROGRESS.
Referenced by VehicleCameraControl::handleCameraCaptureStatus().
capturePhotosState()
virtual CapturePhotosState MavlinkCameraControl::capturePhotosState () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
capturePhotosStateChanged
void MavlinkCameraControl::capturePhotosStateChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
capturesPhotos()
virtual bool MavlinkCameraControl::capturesPhotos () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
capturesVideo()
virtual bool MavlinkCameraControl::capturesVideo () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
captureVideoState()
virtual CaptureVideoState MavlinkCameraControl::captureVideoState () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
captureVideoStateChanged
void MavlinkCameraControl::captureVideoStateChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
captureVideoStatusToStr()
QString MavlinkCameraControl::captureVideoStatusToStr (uint8_t video_status)
Definition at line 35 of file MavlinkCameraControl.cc.
References VIDEO_CAPTURE_STATUS_RUNNING, and VIDEO_CAPTURE_STATUS_STOPPED.
Referenced by VehicleCameraControl::handleCameraCaptureStatus().
compID()
virtual int MavlinkCameraControl::compID () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraParamIO::paramRequest().
currentStream()
virtual int MavlinkCameraControl::currentStream () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepStream().
currentStreamChanged
void MavlinkCameraControl::currentStreamChanged () signal
Referenced by VehicleCameraControl::setCurrentStream().
currentStreamInstance()
virtual QGCVideoStreamInfo * MavlinkCameraControl::currentStreamInstance () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
dataReady
void MavlinkCameraControl::dataReady (const QByteArray & data) signal
Referenced by VehicleCameraControl::_downloadFinished(), and VehicleCameraControl::VehicleCameraControl().
ev()
virtual Fact * MavlinkCameraControl::ev () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
exposureMode()
virtual Fact * MavlinkCameraControl::exposureMode () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
factChanged()
virtual void MavlinkCameraControl::factChanged (Fact * pFact) pure virtual
Notify controller a parameter has changed.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamAck(), and QGCCameraParamIO::handleParamValue().
firmwareVersion()
virtual QString MavlinkCameraControl::firmwareVersion () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
focalLength()
virtual qreal MavlinkCameraControl::focalLength () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
focusLevel()
virtual qreal MavlinkCameraControl::focusLevel () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
focusLevelChanged
void MavlinkCameraControl::focusLevelChanged () signal
Referenced by VehicleCameraControl::handleCameraSettings().
formatCard()
virtual void MavlinkCameraControl::formatCard (int id = 1) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
handleBatteryStatus()
virtual void MavlinkCameraControl::handleBatteryStatus (const mavlink_battery_status_t & bs) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleCameraCaptureStatus()
virtual void MavlinkCameraControl::handleCameraCaptureStatus (const mavlink_camera_capture_status_t & cameraCaptureStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleCameraSettings()
virtual void MavlinkCameraControl::handleCameraSettings (const mavlink_camera_settings_t & settings) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleParamExtAck()
virtual void MavlinkCameraControl::handleParamExtAck (const mavlink_param_ext_ack_t & paramExtAck) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleParamExtValue()
virtual void MavlinkCameraControl::handleParamExtValue (const mavlink_param_ext_value_t & paramExtValue) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleStorageInformation()
virtual void MavlinkCameraControl::handleStorageInformation (const mavlink_storage_information_t & storageInformation) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleTrackingImageStatus()
virtual void MavlinkCameraControl::handleTrackingImageStatus (const mavlink_camera_tracking_image_status_t & trackingImageStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleVideoStreamInformation()
virtual void MavlinkCameraControl::handleVideoStreamInformation (const mavlink_video_stream_information_t & videoStreamInformation) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
handleVideoStreamStatus()
virtual void MavlinkCameraControl::handleVideoStreamStatus (const mavlink_video_stream_status_t & videoStreamStatus) pure virtual
Implemented in SimulatedCameraControl, and VehicleCameraControl.
hasFocus()
virtual bool MavlinkCameraControl::hasFocus () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
hasModes()
virtual bool MavlinkCameraControl::hasModes () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
hasTracking()
virtual bool MavlinkCameraControl::hasTracking () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
hasVideoStream()
virtual bool MavlinkCameraControl::hasVideoStream () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
hasZoom()
virtual bool MavlinkCameraControl::hasZoom () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
incomingParameter()
virtual bool MavlinkCameraControl::incomingParameter (Fact * pFact, QVariant & newValue) pure virtual
Allow controller to modify or invalidate incoming parameter.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamValue().
infoChanged
void MavlinkCameraControl::infoChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
isBasic()
virtual bool MavlinkCameraControl::isBasic () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
iso()
virtual Fact * MavlinkCameraControl::iso () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
mode()
virtual Fact * MavlinkCameraControl::mode () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by cameraModeToStr().
modelName()
virtual QString MavlinkCameraControl::modelName () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
paramComplete()
virtual bool MavlinkCameraControl::paramComplete () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
parametersReady
void MavlinkCameraControl::parametersReady () signal
Referenced by VehicleCameraControl::_initWhenReady(), and VehicleCameraControl::_paramDone().
photoCaptureMode()
virtual PhotoCaptureMode MavlinkCameraControl::photoCaptureMode () const inline virtual
Definition at line 193 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::handleCameraCaptureStatus(), SimulatedCameraControl::setPhotoCaptureMode(), and SimulatedCameraControl::takePhoto().
photoCaptureModeChanged
void MavlinkCameraControl::photoCaptureModeChanged () signal
Referenced by VehicleCameraControl::setPhotoCaptureMode(), and SimulatedCameraControl::setPhotoCaptureMode().
photoCaptureStatusChanged
void MavlinkCameraControl::photoCaptureStatusChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setPhotoCaptureStatus(), SimulatedCameraControl::SimulatedCameraControl(), and SimulatedCameraControl::takePhoto().
photoLapse()
virtual qreal MavlinkCameraControl::photoLapse () const inline virtual
Definition at line 194 of file MavlinkCameraControl.h.
photoLapseChanged
void MavlinkCameraControl::photoLapseChanged () signal
Referenced by VehicleCameraControl::setPhotoLapse().
photoLapseCount()
virtual int MavlinkCameraControl::photoLapseCount () const inline virtual
Definition at line 195 of file MavlinkCameraControl.h.
photoLapseCountChanged
void MavlinkCameraControl::photoLapseCountChanged () signal
Referenced by VehicleCameraControl::setPhotoLapseCount().
photosInVideoMode()
virtual bool MavlinkCameraControl::photosInVideoMode () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
recordTime()
virtual quint32 MavlinkCameraControl::recordTime () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
recordTimeChanged
void MavlinkCameraControl::recordTimeChanged () signal
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), VehicleCameraControl::_recTimerHandler(), VehicleCameraControl::_setVideoCaptureStatus(), VehicleCameraControl::handleCameraCaptureStatus(), and SimulatedCameraControl::SimulatedCameraControl().
recordTimeStr()
virtual QString MavlinkCameraControl::recordTimeStr () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
resetSettings()
virtual void MavlinkCameraControl::resetSettings () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
resolution()
virtual QSize MavlinkCameraControl::resolution () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
resumeStream()
virtual void MavlinkCameraControl::resumeStream () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
sensorSize()
virtual QSizeF MavlinkCameraControl::sensorSize () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setCameraMode()
virtual void MavlinkCameraControl::setCameraMode (CameraMode cameraMode) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setCameraModePhoto()
virtual void MavlinkCameraControl::setCameraModePhoto () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setCameraModeVideo()
virtual void MavlinkCameraControl::setCameraModeVideo () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setCurrentStream()
virtual void MavlinkCameraControl::setCurrentStream (int stream) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepStream().
setFocusLevel()
virtual void MavlinkCameraControl::setFocusLevel (qreal level) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setPhotoCaptureMode()
virtual void MavlinkCameraControl::setPhotoCaptureMode (PhotoCaptureMode mode) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setPhotoLapse()
virtual void MavlinkCameraControl::setPhotoLapse (qreal interval) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setPhotoLapseCount()
virtual void MavlinkCameraControl::setPhotoLapseCount (int count) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setThermalMode()
virtual void MavlinkCameraControl::setThermalMode (ThermalViewMode mode) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setThermalOpacity()
virtual void MavlinkCameraControl::setThermalOpacity (double val) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setTrackingEnabled()
virtual void MavlinkCameraControl::setTrackingEnabled (bool set) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
setZoomLevel()
virtual void MavlinkCameraControl::setZoomLevel (qreal level) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
shutterSpeed()
virtual Fact * MavlinkCameraControl::shutterSpeed () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
startTracking() [1/2]
virtual void MavlinkCameraControl::startTracking (QPointF point, double radius) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
startTracking() [2/2]
virtual void MavlinkCameraControl::startTracking (QRectF rec) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
startVideoRecording()
virtual bool MavlinkCameraControl::startVideoRecording () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_startVideoRecording().
startZoom()
virtual void MavlinkCameraControl::startZoom (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_startZoom().
stepZoom()
virtual void MavlinkCameraControl::stepZoom (int direction) pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepZoom().
stopStream()
virtual void MavlinkCameraControl::stopStream () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
stopTakePhoto()
virtual bool MavlinkCameraControl::stopTakePhoto () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
stopTracking()
virtual void MavlinkCameraControl::stopTracking () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
stopVideoRecording()
virtual bool MavlinkCameraControl::stopVideoRecording () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stopVideoRecording().
stopZoom()
virtual void MavlinkCameraControl::stopZoom () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stopZoom().
storageFree()
virtual quint32 MavlinkCameraControl::storageFree () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
storageFreeChanged
void MavlinkCameraControl::storageFreeChanged () signal
Referenced by VehicleCameraControl::handleCameraCaptureStatus(), and VehicleCameraControl::handleStorageInformation().
storageFreeStr()
virtual QString MavlinkCameraControl::storageFreeStr () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
storageStatus()
virtual StorageStatus MavlinkCameraControl::storageStatus () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
storageStatusChanged
void MavlinkCameraControl::storageStatusChanged () signal
Referenced by VehicleCameraControl::handleStorageInformation().
storageStatusToStr()
QString MavlinkCameraControl::storageStatusToStr (uint8_t status)
Definition at line 47 of file MavlinkCameraControl.cc.
Referenced by VehicleCameraControl::handleStorageInformation().
storageTotal()
virtual quint32 MavlinkCameraControl::storageTotal () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
storageTotalChanged
void MavlinkCameraControl::storageTotalChanged () signal
Referenced by VehicleCameraControl::handleStorageInformation().
streamLabels()
virtual QStringList MavlinkCameraControl::streamLabels () const pure virtual
Stream names to show the user (for selection)
Implemented in VehicleCameraControl, and SimulatedCameraControl.
streamLabelsChanged
void MavlinkCameraControl::streamLabelsChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
streams()
virtual QmlObjectListModel * MavlinkCameraControl::streams () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_stepStream().
streamsChanged
void MavlinkCameraControl::streamsChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
takePhoto()
virtual bool MavlinkCameraControl::takePhoto () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_triggerCamera().
thermalMode()
virtual ThermalViewMode MavlinkCameraControl::thermalMode () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
thermalModeChanged
void MavlinkCameraControl::thermalModeChanged () signal
Referenced by VehicleCameraControl::setThermalMode().
thermalOpacity()
virtual double MavlinkCameraControl::thermalOpacity () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
thermalOpacityChanged
void MavlinkCameraControl::thermalOpacityChanged () signal
Referenced by VehicleCameraControl::setThermalOpacity().
thermalStreamChanged
void MavlinkCameraControl::thermalStreamChanged () signal
Referenced by VehicleCameraControl::handleVideoStreamInformation().
thermalStreamInstance()
virtual QGCVideoStreamInfo * MavlinkCameraControl::thermalStreamInstance () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
toggleCameraMode()
virtual void MavlinkCameraControl::toggleCameraMode () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
toggleVideoRecording()
virtual bool MavlinkCameraControl::toggleVideoRecording () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
Referenced by QGCCameraManager::_toggleVideoRecording().
trackingEnabled()
virtual bool MavlinkCameraControl::trackingEnabled () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
trackingEnabledChanged
void MavlinkCameraControl::trackingEnabledChanged () signal
Referenced by VehicleCameraControl::setTrackingEnabled().
trackingImageRect()
virtual QRectF MavlinkCameraControl::trackingImageRect () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
trackingImageStatus()
virtual bool MavlinkCameraControl::trackingImageStatus () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
trackingImageStatusChanged
void MavlinkCameraControl::trackingImageStatusChanged () signal
Referenced by VehicleCameraControl::handleTrackingImageStatus().
trackingStatus()
virtual TrackingStatus MavlinkCameraControl::trackingStatus () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
validateParameter()
virtual bool MavlinkCameraControl::validateParameter (Fact * pFact, QVariant & newValue) pure virtual
Allow controller to modify or invalidate parameter change.
Implemented in SimulatedCameraControl, and VehicleCameraControl.
Referenced by QGCCameraParamIO::handleParamAck().
vendor()
virtual QString MavlinkCameraControl::vendor () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
version()
virtual int MavlinkCameraControl::version () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
videoCaptureStatusChanged
void MavlinkCameraControl::videoCaptureStatusChanged () signal
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_setVideoCaptureStatus(), and SimulatedCameraControl::SimulatedCameraControl().
videoInPhotoMode()
virtual bool MavlinkCameraControl::videoInPhotoMode () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
wb()
virtual Fact * MavlinkCameraControl::wb () pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
zoomLevel()
virtual qreal MavlinkCameraControl::zoomLevel () const pure virtual
Implemented in VehicleCameraControl, and SimulatedCameraControl.
zoomLevelChanged
void MavlinkCameraControl::zoomLevelChanged () signal
Referenced by VehicleCameraControl::handleCameraSettings().
Member Data Documentation
_cameraMode
CameraMode MavlinkCameraControl::_cameraMode = CAM_MODE_UNDEFINED protected
Definition at line 320 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_setCameraMode(), VehicleCameraControl::captureVideoState(), VehicleCameraControl::setCameraMode(), SimulatedCameraControl::startVideoRecording(), VehicleCameraControl::takePhoto(), SimulatedCameraControl::takePhoto(), VehicleCameraControl::toggleCameraMode(), and SimulatedCameraControl::toggleCameraMode().
_photoCaptureMode
PhotoCaptureMode MavlinkCameraControl::_photoCaptureMode = PHOTO_CAPTURE_SINGLE protected
Definition at line 323 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::setPhotoCaptureMode(), SimulatedCameraControl::setPhotoCaptureMode(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_photoCaptureStatusValue
PhotoCaptureStatus MavlinkCameraControl::_photoCaptureStatusValue = PHOTO_CAPTURE_IDLE protected
Definition at line 322 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_setPhotoCaptureStatus(), and SimulatedCameraControl::takePhoto().
_photoLapse
qreal MavlinkCameraControl::_photoLapse = 1.0 protected
Definition at line 324 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::setPhotoLapse(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_photoLapseCount
int MavlinkCameraControl::_photoLapseCount = 0 protected
Definition at line 325 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::setPhotoLapseCount(), VehicleCameraControl::takePhoto(), and VehicleCameraControl::VehicleCameraControl().
_vehicle
Vehicle* MavlinkCameraControl::_vehicle = nullptr protected
Definition at line 319 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_initWhenReady(), VehicleCameraControl::_mavCommandResult(), VehicleCameraControl::_requestAllParameters(), VehicleCameraControl::_requestCameraSettings(), VehicleCameraControl::_requestCaptureStatus(), VehicleCameraControl::_requestStorageInfo(), VehicleCameraControl::_requestStreamInfo(), VehicleCameraControl::_requestStreamStatus(), VehicleCameraControl::_requestTrackingStatus(), VehicleCameraControl::_streamInfoTimeout(), VehicleCameraControl::formatCard(), VehicleCameraControl::handleVideoStreamInformation(), VehicleCameraControl::resetSettings(), VehicleCameraControl::resumeStream(), VehicleCameraControl::setCameraMode(), VehicleCameraControl::setCurrentStream(), VehicleCameraControl::setFocusLevel(), VehicleCameraControl::setZoomLevel(), VehicleCameraControl::startTracking(), VehicleCameraControl::startTracking(), VehicleCameraControl::startVideoRecording(), VehicleCameraControl::startZoom(), VehicleCameraControl::stepZoom(), VehicleCameraControl::stopStream(), VehicleCameraControl::stopTakePhoto(), VehicleCameraControl::stopTracking(), VehicleCameraControl::stopVideoRecording(), VehicleCameraControl::stopZoom(), VehicleCameraControl::takePhoto(), and SimulatedCameraControl::takePhoto().
_videoCaptureStatusValue
VideoCaptureStatus MavlinkCameraControl::_videoCaptureStatusValue = VIDEO_CAPTURE_STATUS_STOPPED protected
Definition at line 321 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_setVideoCaptureStatus().
_videoRecordTimeUpdateTimer
QTimer MavlinkCameraControl::_videoRecordTimeUpdateTimer protected
Definition at line 326 of file MavlinkCameraControl.h.
Referenced by VehicleCameraControl::_onVideoManagerRecordingChanged(), VehicleCameraControl::_setVideoCaptureStatus(), SimulatedCameraControl::recordTime(), SimulatedCameraControl::startVideoRecording(), SimulatedCameraControl::stopVideoRecording(), VehicleCameraControl::VehicleCameraControl(), and VehicleCameraControl::~VehicleCameraControl().
The documentation for this class was generated from the following files:
src/Camera/MavlinkCameraControl.h
src/Camera/MavlinkCameraControl.cc