QGroundControl: CameraSpec Class Reference
CameraSpec Class Reference
#include <CameraSpec.h>
Signals
void dirtyChanged (bool dirty)
Public Member Functions
CameraSpec (const QString &settingsGroup, QObject *parent=nullptr)
const CameraSpec & operator= (const CameraSpec &other)
Fact *sensorWidth READ sensorWidth CONSTANT (Fact *sensorHeight READ sensorHeight CONSTANT) 1(Fact *imageWidth READ imageWidth CONSTANT) 1(Fact *imageHeight READ imageHeight CONSTANT) 1(Fact *focalLength READ focalLength CONSTANT) 1(Fact *landscape READ landscape CONSTANT) 1(Fact *fixedOrientation READ fixedOrientation CONSTANT) 1(Fact *minTriggerInterval READ minTriggerInterval CONSTANT) SettingsFact *sensorWidth(void)
< Sensor size in millimeters
SettingsFact * sensorHeight (void)
SettingsFact * imageWidth (void)
SettingsFact * imageHeight (void)
SettingsFact * focalLength (void)
SettingsFact * landscape (void)
SettingsFact * fixedOrientation (void)
SettingsFact * minTriggerInterval (void)
bool dirty (void) const
void setDirty (bool dirty)
void save (QJsonObject &json) const
bool load (const QJsonObject &json, QString &errorString)
Detailed Description
Definition at line 5 of file CameraSpec.h.
Constructor & Destructor Documentation
CameraSpec()
CameraSpec::CameraSpec (const QString & settingsGroup, QObject * parent = nullptr)
Definition at line 6 of file CameraSpec.cc.
Member Function Documentation
CONSTANT()
Fact *sensorWidth READ sensorWidth CameraSpec::CONSTANT (Fact *sensorHeight READ sensorHeight CONSTANT) inline
< Sensor size in millimeters
< Image size in pixels < Image size in pixels < Focal length in millimeters < true: camera is in landscape orientation < true: camera is in fixed orientation < Minimum time in seconds between each photo taken, 0 for not specified
Parameters
CONSTANT Sensor size in millimeters
Definition at line 15 of file CameraSpec.h.
dirty()
bool CameraSpec::dirty (void) const inline
Definition at line 33 of file CameraSpec.h.
Referenced by setDirty().
dirtyChanged
void CameraSpec::dirtyChanged (bool dirty) signal
Referenced by setDirty(), and TransectStyleComplexItem::TransectStyleComplexItem().
fixedOrientation()
SettingsFact * CameraSpec::fixedOrientation (void) inline
Definition at line 30 of file CameraSpec.h.
focalLength()
SettingsFact * CameraSpec::focalLength (void) inline
Definition at line 28 of file CameraSpec.h.
Referenced by CameraCalc::CameraCalc().
imageHeight()
SettingsFact * CameraSpec::imageHeight (void) inline
Definition at line 27 of file CameraSpec.h.
Referenced by CameraCalc::CameraCalc().
imageWidth()
SettingsFact * CameraSpec::imageWidth (void) inline
Definition at line 26 of file CameraSpec.h.
Referenced by CameraCalc::CameraCalc().
landscape()
SettingsFact * CameraSpec::landscape (void) inline
Definition at line 29 of file CameraSpec.h.
Referenced by CameraCalc::CameraCalc().
load()
bool CameraSpec::load (const QJsonObject & json, QString & errorString)
Definition at line 56 of file CameraSpec.cc.
References errorString, and JsonHelper::validateKeys().
Referenced by CameraCalc::load().
minTriggerInterval()
SettingsFact * CameraSpec::minTriggerInterval (void) inline
Definition at line 31 of file CameraSpec.h.
operator=()
const CameraSpec & CameraSpec::operator= (const CameraSpec & other)
Definition at line 22 of file CameraSpec.cc.
save()
void CameraSpec::save (QJsonObject & json) const
Definition at line 44 of file CameraSpec.cc.
Referenced by CameraCalc::save().
sensorHeight()
SettingsFact * CameraSpec::sensorHeight (void) inline
Definition at line 25 of file CameraSpec.h.
Referenced by CameraCalc::CameraCalc().
setDirty()
void CameraSpec::setDirty (bool dirty)
Definition at line 36 of file CameraSpec.cc.
References dirty(), and dirtyChanged().
Referenced by CameraCalc::CameraCalc(), and TransectStyleComplexItem::setDirty().
The documentation for this class was generated from the following files:
src/MissionManager/CameraSpec.h
src/MissionManager/CameraSpec.cc