QGroundControl: Viewer3DInstancing Class Reference
Viewer3DInstancing Class Reference
#include <Viewer3DInstancing.h>
Signals
void countChanged ()
void selectedIndexChanged ()
Public Member Functions
Viewer3DInstancing (QQuick3DObject *parent=nullptr)
void clear ()
void addEntry (const QVector3D &position, const QVector3D &scale, const QQuaternion &rotation, const QColor &color)
void addLineSegment (const QVector3D &p1, const QVector3D &p2, float lineWidth, const QColor &color)
int count () const
int selectedIndex () const
void setSelectedIndex (int index)
Protected Member Functions
QByteArray getInstanceBuffer (int *instanceCount) override
Detailed Description
Definition at line 9 of file Viewer3DInstancing.h.
Constructor & Destructor Documentation
Viewer3DInstancing()
Viewer3DInstancing::Viewer3DInstancing (QQuick3DObject * parent = nullptr) explicit
Definition at line 9 of file Viewer3DInstancing.cc.
Member Function Documentation
addEntry()
void Viewer3DInstancing::addEntry (const QVector3D & position, const QVector3D & scale, const QQuaternion & rotation, const QColor & color)
Definition at line 23 of file Viewer3DInstancing.cc.
References countChanged().
addLineSegment()
void Viewer3DInstancing::addLineSegment (const QVector3D & p1, const QVector3D & p2, float lineWidth, const QColor & color)
Definition at line 34 of file Viewer3DInstancing.cc.
References countChanged().
clear()
void Viewer3DInstancing::clear ()
Definition at line 14 of file Viewer3DInstancing.cc.
References countChanged().
count()
int Viewer3DInstancing::count () const
Definition at line 60 of file Viewer3DInstancing.cc.
countChanged
void Viewer3DInstancing::countChanged () signal
Referenced by addEntry(), addLineSegment(), and clear().
getInstanceBuffer()
QByteArray Viewer3DInstancing::getInstanceBuffer (int * instanceCount) override protected
Definition at line 79 of file Viewer3DInstancing.cc.
selectedIndex()
int Viewer3DInstancing::selectedIndex () const
Definition at line 65 of file Viewer3DInstancing.cc.
selectedIndexChanged
void Viewer3DInstancing::selectedIndexChanged () signal
Referenced by setSelectedIndex().
setSelectedIndex()
void Viewer3DInstancing::setSelectedIndex (int index)
Definition at line 70 of file Viewer3DInstancing.cc.
References selectedIndexChanged().
The documentation for this class was generated from the following files:
src/Viewer3D/Viewer3DInstancing.h
src/Viewer3D/Viewer3DInstancing.cc