QGroundControl: MotorAssignment Class Reference
MotorAssignment Class Reference
#include <MotorAssignment.h>
Signals
void activeChanged ()
void messageChanged ()
void onAbort ()
Public Member Functions
MotorAssignment (QObject *parent, Vehicle *vehicle, QmlObjectListModel *actuators)
virtual ~MotorAssignment ()=default
bool initAssignment (int selectedActuatorIdx, int firstMotorsFunction, int numMotors)
void start ()
void selectMotor (int motorIndex)
void spinCurrentMotor ()
void abort ()
bool active () const
const QString & message () const
Detailed Description
Handles automatic motor ordering assignment by spinning individual motors, and then having the user to select the corresponding motor.
Definition at line 20 of file MotorAssignment.h.
Constructor & Destructor Documentation
MotorAssignment()
MotorAssignment::MotorAssignment (QObject * parent, Vehicle * vehicle, QmlObjectListModel * actuators)
Definition at line 13 of file MotorAssignment.cc.
~MotorAssignment()
virtual MotorAssignment::~MotorAssignment () virtual default
Member Function Documentation
abort()
void MotorAssignment::abort ()
Definition at line 170 of file MotorAssignment.cc.
Referenced by Actuators::abortMotorAssignment().
active()
bool MotorAssignment::active () const inline
Definition at line 45 of file MotorAssignment.h.
Referenced by Actuators::motorAssignmentActive().
activeChanged
void MotorAssignment::activeChanged () signal
Referenced by Actuators::Actuators().
initAssignment()
bool MotorAssignment::initAssignment (int selectedActuatorIdx, int firstMotorsFunction, int numMotors)
Initialize assignment, and set the UI confirmation message to be shown to the user.
Returns
true on success, false on failure (message will contain the error message)
Definition at line 21 of file MotorAssignment.cc.
References QmlObjectListModel::count(), QmlObjectListModel::get(), and messageChanged().
Referenced by Actuators::initMotorAssignment().
message()
const QString & MotorAssignment::message () const inline
Definition at line 47 of file MotorAssignment.h.
Referenced by Actuators::motorAssignmentMessage().
messageChanged
void MotorAssignment::messageChanged () signal
Referenced by Actuators::Actuators(), and initAssignment().
onAbort
void MotorAssignment::onAbort () signal
Referenced by Actuators::Actuators().
selectMotor()
void MotorAssignment::selectMotor (int motorIndex)
Definition at line 131 of file MotorAssignment.cc.
spinCurrentMotor()
void MotorAssignment::spinCurrentMotor ()
Definition at line 161 of file MotorAssignment.cc.
Referenced by Actuators::spinCurrentMotor().
start()
void MotorAssignment::start ()
Start the assignment, called after confirming.
Definition at line 99 of file MotorAssignment.cc.
Referenced by Actuators::startMotorAssignment().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/MotorAssignment.h
src/Vehicle/Actuators/MotorAssignment.cc