QGroundControl: MavlinkSettings Class Reference
MavlinkSettings Class Reference
Application Settings.
#include <MavlinkSettings.h>
Public Member Functions
MavlinkSettings (QObject *parent=nullptr)
Fact *telemetrySave READ telemetrySave CONSTANT Fact * telemetrySave ()
Fact *telemetrySaveNotArmed READ telemetrySaveNotArmed CONSTANT Fact * telemetrySaveNotArmed ()
Fact *saveCsvTelemetry READ saveCsvTelemetry CONSTANT Fact * saveCsvTelemetry ()
Fact *forwardMavlink READ forwardMavlink CONSTANT Fact * forwardMavlink ()
Fact *forwardMavlinkHostName READ forwardMavlinkHostName CONSTANT Fact * forwardMavlinkHostName ()
Fact *forwardMavlinkAPMSupportHostName READ forwardMavlinkAPMSupportHostName CONSTANT Fact * forwardMavlinkAPMSupportHostName ()
Fact *mavlink2SigningKey READ mavlink2SigningKey CONSTANT Fact * mavlink2SigningKey ()
Fact *sendGCSHeartbeat READ sendGCSHeartbeat CONSTANT Fact * sendGCSHeartbeat ()
Fact *gcsMavlinkSystemID READ gcsMavlinkSystemID CONSTANT Fact * gcsMavlinkSystemID ()
Fact *apmStartMavlinkStreams READ apmStartMavlinkStreams CONSTANT Fact * apmStartMavlinkStreams ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "Mavlink"
static const char * settingsGroup = ""
static const char * telemetrySaveName = "telemetrySave"
static const char * telemetrySaveNotArmedName = "telemetrySaveNotArmed"
static const char * saveCsvTelemetryName = "saveCsvTelemetry"
static const char * forwardMavlinkName = "forwardMavlink"
static const char * forwardMavlinkHostNameName = "forwardMavlinkHostName"
static const char * forwardMavlinkAPMSupportHostNameName = "forwardMavlinkAPMSupportHostName"
static const char * mavlink2SigningKeyName = "mavlink2SigningKey"
static const char * sendGCSHeartbeatName = "sendGCSHeartbeat"
static const char * gcsMavlinkSystemIDName = "gcsMavlinkSystemID"
static const char * apmStartMavlinkStreamsName = "apmStartMavlinkStreams"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Application Settings.
Definition at line 8 of file MavlinkSettings.h.
Constructor & Destructor Documentation
MavlinkSettings()
MavlinkSettings::MavlinkSettings (QObject * parent = nullptr)
Definition at line 4 of file MavlinkSettings.cc.
Member Function Documentation
apmStartMavlinkStreams()
Fact * MavlinkSettings::apmStartMavlinkStreams ()
Definition at line 33 of file MavlinkSettings.cc.
forwardMavlink()
Fact * MavlinkSettings::forwardMavlink ()
Definition at line 35 of file MavlinkSettings.cc.
forwardMavlinkAPMSupportHostName()
Fact * MavlinkSettings::forwardMavlinkAPMSupportHostName ()
Definition at line 37 of file MavlinkSettings.cc.
forwardMavlinkHostName()
Fact * MavlinkSettings::forwardMavlinkHostName ()
Definition at line 36 of file MavlinkSettings.cc.
gcsMavlinkSystemID()
Fact * MavlinkSettings::gcsMavlinkSystemID ()
Definition at line 39 of file MavlinkSettings.cc.
Referenced by MAVLinkProtocol::getSystemId(), and QGCApplication::init().
mavlink2SigningKey()
Fact * MavlinkSettings::mavlink2SigningKey ()
Definition at line 41 of file MavlinkSettings.cc.
References Fact::rawValueChanged().
Referenced by LinkInterface::initMavlinkSigning().
saveCsvTelemetry()
Fact * MavlinkSettings::saveCsvTelemetry ()
Definition at line 34 of file MavlinkSettings.cc.
sendGCSHeartbeat()
Fact * MavlinkSettings::sendGCSHeartbeat ()
Definition at line 38 of file MavlinkSettings.cc.
telemetrySave()
Fact * MavlinkSettings::telemetrySave ()
Definition at line 31 of file MavlinkSettings.cc.
telemetrySaveNotArmed()
Fact * MavlinkSettings::telemetrySaveNotArmed ()
Definition at line 32 of file MavlinkSettings.cc.
Member Data Documentation
apmStartMavlinkStreamsName
const char * MavlinkSettings::apmStartMavlinkStreamsName = "apmStartMavlinkStreams" static
Definition at line 29 of file MavlinkSettings.h.
forwardMavlinkAPMSupportHostNameName
const char * MavlinkSettings::forwardMavlinkAPMSupportHostNameName = "forwardMavlinkAPMSupportHostName" static
Definition at line 23 of file MavlinkSettings.h.
forwardMavlinkHostNameName
const char * MavlinkSettings::forwardMavlinkHostNameName = "forwardMavlinkHostName" static
Definition at line 22 of file MavlinkSettings.h.
forwardMavlinkName
const char * MavlinkSettings::forwardMavlinkName = "forwardMavlink" static
Definition at line 21 of file MavlinkSettings.h.
gcsMavlinkSystemIDName
const char * MavlinkSettings::gcsMavlinkSystemIDName = "gcsMavlinkSystemID" static
Definition at line 26 of file MavlinkSettings.h.
mavlink2SigningKeyName
const char * MavlinkSettings::mavlink2SigningKeyName = "mavlink2SigningKey" static
Definition at line 24 of file MavlinkSettings.h.
name
const char * MavlinkSettings::name = "Mavlink" static
Definition at line 16 of file MavlinkSettings.h.
saveCsvTelemetryName
const char * MavlinkSettings::saveCsvTelemetryName = "saveCsvTelemetry" static
Definition at line 20 of file MavlinkSettings.h.
sendGCSHeartbeatName
const char * MavlinkSettings::sendGCSHeartbeatName = "sendGCSHeartbeat" static
Definition at line 25 of file MavlinkSettings.h.
settingsGroup
const char * MavlinkSettings::settingsGroup = "" static
Definition at line 16 of file MavlinkSettings.h.
telemetrySaveName
const char * MavlinkSettings::telemetrySaveName = "telemetrySave" static
Definition at line 18 of file MavlinkSettings.h.
telemetrySaveNotArmedName
const char * MavlinkSettings::telemetrySaveNotArmedName = "telemetrySaveNotArmed" static
Definition at line 19 of file MavlinkSettings.h.
The documentation for this class was generated from the following files:
src/Settings/MavlinkSettings.h
src/Settings/MavlinkSettings.cc