QGroundControl: APMSensorsComponent Class Reference
APMSensorsComponent Class Reference
#include <APMSensorsComponent.h>
Public Member Functions
APMSensorsComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
bool compassSetupNeeded () const
bool accelSetupNeeded () const
QStringList setupCompleteChangedTriggerList () const final
QString name () const final
QString description () const final
QString iconResource () const final
bool requiresSetup () const final
bool setupComplete () const final
QUrl setupSource () const final
QUrl summaryQmlSource () const final
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file APMSensorsComponent.h.
Constructor & Destructor Documentation
APMSensorsComponent()
APMSensorsComponent::APMSensorsComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr) explicit
Definition at line 5 of file APMSensorsComponent.cc.
Member Function Documentation
accelSetupNeeded()
bool APMSensorsComponent::accelSetupNeeded () const
Definition at line 64 of file APMSensorsComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), and Vehicle::parameterManager().
Referenced by setupComplete().
compassSetupNeeded()
bool APMSensorsComponent::compassSetupNeeded () const
Definition at line 25 of file APMSensorsComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), and Vehicle::parameterManager().
Referenced by setupComplete().
description()
QString APMSensorsComponent::description (void) const inline final virtual
Reimplemented from VehicleComponent.
Definition at line 18 of file APMSensorsComponent.h.
iconResource()
QString APMSensorsComponent::iconResource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 19 of file APMSensorsComponent.h.
name()
QString APMSensorsComponent::name (void) const inline final virtual
Implements VehicleComponent.
Definition at line 17 of file APMSensorsComponent.h.
requiresSetup()
bool APMSensorsComponent::requiresSetup (void) const inline final virtual
Implements VehicleComponent.
Definition at line 20 of file APMSensorsComponent.h.
setupComplete()
bool APMSensorsComponent::setupComplete (void) const inline final virtual
Implements VehicleComponent.
Definition at line 21 of file APMSensorsComponent.h.
References accelSetupNeeded(), and compassSetupNeeded().
setupCompleteChangedTriggerList()
QStringList APMSensorsComponent::setupCompleteChangedTriggerList () const final virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 11 of file APMSensorsComponent.cc.
setupSource()
QUrl APMSensorsComponent::setupSource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 22 of file APMSensorsComponent.h.
summaryQmlSource()
QUrl APMSensorsComponent::summaryQmlSource (void) const inline final virtual
Implements VehicleComponent.
Definition at line 23 of file APMSensorsComponent.h.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/APM/APMSensorsComponent.h
src/AutoPilotPlugins/APM/APMSensorsComponent.cc