QGroundControl: FactValueGrid Class Reference
FactValueGrid Class Reference
#include <FactValueGrid.h>
Public Types
enum FontSize { DefaultFontSize =0 , SmallFontSize , MediumFontSize , LargeFontSize }
Signals
void fontSizeChanged (FontSize fontSize)
void columnsChanged (QmlObjectListModel *model)
void rowCountChanged (int rowCount)
void settingsGroupChanged (QString settingsGroup)
void specificVehicleForCardChanged (Vehicle *vehicle)
Public Member Functions
FactValueGrid (QQuickItem *parent=nullptr)
~FactValueGrid ()
QmlObjectListModel *columns MEMBER _columns NOTIFY columnsChanged (int rowCount MEMBER _rowCount NOTIFY rowCountChanged) 1(QStringList iconNames READ iconNames CONSTANT) 1(FontSize fontSize READ fontSize WRITE setFontSize NOTIFY fontSizeChanged) 1(QStringList fontSizeNames MEMBER _fontSizeNames CONSTANT) 1(QString settingsGroup MEMBER _settingsGroup NOTIFY settingsGroupChanged REQUIRED) 1(Vehicle *specificVehicleForCard MEMBER _specificVehicleForCard NOTIFY specificVehicleForCardChanged REQUIRED) 1 void resetToDefaults(void)
< null means track active vehicle, set to specific vehicle to track a single vehicle and share settings with other cards
QmlObjectListModel * appendColumn (void)
void deleteLastColumn (void)
void appendRow (void)
void deleteLastRow (void)
QmlObjectListModel * columns (void) const
QString settingsGroup (void) const
FontSize fontSize (void) const
QStringList iconNames (void) const
QGCMAVLink::VehicleClass_t vehicleClass (void) const
Vehicle * currentVehicle (void) const
Vehicle * specificVehicleForCard (void) const
void setFontSize (FontSize fontSize)
void componentComplete (void) final
Protected Attributes
QString _settingsGroup
FontSize _fontSize = DefaultFontSize
bool _preventSaveSettings = false
QmlObjectListModel * _columns = nullptr
int _rowCount = 0
Vehicle * _specificVehicleForCard = nullptr
Vehicle * _activeVehicle = nullptr
Detailed Description
Definition at line 13 of file FactValueGrid.h.
Member Enumeration Documentation
FontSize
enum FactValueGrid::FontSize
Enumerator
DefaultFontSize
SmallFontSize
MediumFontSize
LargeFontSize
Definition at line 22 of file FactValueGrid.h.
Constructor & Destructor Documentation
FactValueGrid()
FactValueGrid::FactValueGrid (QQuickItem * parent = nullptr)
Definition at line 23 of file FactValueGrid.cc.
~FactValueGrid()
FactValueGrid::~FactValueGrid ()
Definition at line 88 of file FactValueGrid.cc.
Member Function Documentation
appendColumn()
QmlObjectListModel * FactValueGrid::appendColumn (void)
Definition at line 217 of file FactValueGrid.cc.
References _columns, _rowCount, QmlObjectListModel::append(), and rowCountChanged().
appendRow()
void FactValueGrid::appendRow (void)
Definition at line 191 of file FactValueGrid.cc.
References _columns, _rowCount, QmlObjectListModel::append(), QmlObjectListModel::count(), rowCountChanged(), and QmlObjectListModel::value().
columns()
QmlObjectListModel * FactValueGrid::columns (void) const inline
Definition at line 46 of file FactValueGrid.h.
References _columns.
Referenced by SubtitleWriter::startCapturingTelemetry().
columnsChanged() [1/2]
QmlObjectListModel *columns MEMBER _columns NOTIFY FactValueGrid::columnsChanged (int rowCount MEMBER _rowCount NOTIFY rowCountChanged)
< null means track active vehicle, set to specific vehicle to track a single vehicle and share settings with other cards
columnsChanged [2/2]
void FactValueGrid::columnsChanged (QmlObjectListModel * model) signal
componentComplete()
void FactValueGrid::componentComplete (void) final
Definition at line 33 of file FactValueGrid.cc.
References _activeVehicle, _specificVehicleForCard, MultiVehicleManager::activeVehicleChanged(), and fontSizeChanged().
Referenced by SubtitleWriter::startCapturingTelemetry().
currentVehicle()
Vehicle * FactValueGrid::currentVehicle (void) const inline
Definition at line 51 of file FactValueGrid.h.
References _activeVehicle, and _specificVehicleForCard.
Referenced by vehicleClass().
deleteLastColumn()
void FactValueGrid::deleteLastColumn (void)
Definition at line 238 of file FactValueGrid.cc.
References _columns, QmlObjectListModel::count(), and QmlObjectListModel::removeAt().
deleteLastRow()
void FactValueGrid::deleteLastRow (void)
Definition at line 203 of file FactValueGrid.cc.
References _columns, _rowCount, QmlObjectListModel::count(), QmlObjectListModel::removeAt(), rowCountChanged(), and QmlObjectListModel::value().
fontSize()
FontSize FactValueGrid::fontSize (void) const inline
Definition at line 48 of file FactValueGrid.h.
References _fontSize.
Referenced by setFontSize().
fontSizeChanged
void FactValueGrid::fontSizeChanged (FontSize fontSize) signal
Referenced by componentComplete(), and setFontSize().
iconNames()
QStringList FactValueGrid::iconNames (void) const inline
Definition at line 49 of file FactValueGrid.h.
Referenced by InstrumentValueData::addRangeValue().
rowCountChanged
void FactValueGrid::rowCountChanged (int rowCount) signal
Referenced by appendColumn(), appendRow(), and deleteLastRow().
setFontSize()
void FactValueGrid::setFontSize (FontSize fontSize)
Definition at line 110 of file FactValueGrid.cc.
References _fontSize, fontSize(), and fontSizeChanged().
settingsGroup()
QString FactValueGrid::settingsGroup (void) const inline
Definition at line 47 of file FactValueGrid.h.
References _settingsGroup.
settingsGroupChanged
void FactValueGrid::settingsGroupChanged (QString settingsGroup) signal
specificVehicleForCard()
Vehicle * FactValueGrid::specificVehicleForCard (void) const inline
Definition at line 52 of file FactValueGrid.h.
References _specificVehicleForCard.
specificVehicleForCardChanged
void FactValueGrid::specificVehicleForCardChanged (Vehicle * vehicle) signal
vehicleClass()
QGCMAVLink::VehicleClass_t FactValueGrid::vehicleClass (void) const
Definition at line 93 of file FactValueGrid.cc.
References currentVehicle(), and QGCMAVLink::vehicleClass().
Member Data Documentation
_activeVehicle
Vehicle* FactValueGrid::_activeVehicle = nullptr protected
Definition at line 75 of file FactValueGrid.h.
Referenced by componentComplete(), and currentVehicle().
_columns
QmlObjectListModel* FactValueGrid::_columns = nullptr protected
Definition at line 72 of file FactValueGrid.h.
Referenced by appendColumn(), appendRow(), columns(), deleteLastColumn(), and deleteLastRow().
_fontSize
FontSize FactValueGrid::_fontSize = DefaultFontSize protected
Definition at line 70 of file FactValueGrid.h.
Referenced by fontSize(), and setFontSize().
_preventSaveSettings
bool FactValueGrid::_preventSaveSettings = false protected
Definition at line 71 of file FactValueGrid.h.
_rowCount
int FactValueGrid::_rowCount = 0 protected
Definition at line 73 of file FactValueGrid.h.
Referenced by appendColumn(), appendRow(), and deleteLastRow().
_settingsGroup
QString FactValueGrid::_settingsGroup protected
Definition at line 69 of file FactValueGrid.h.
Referenced by settingsGroup().
_specificVehicleForCard
Vehicle* FactValueGrid::_specificVehicleForCard = nullptr protected
Definition at line 74 of file FactValueGrid.h.
Referenced by componentComplete(), currentVehicle(), and specificVehicleForCard().
The documentation for this class was generated from the following files:
src/QmlControls/FactValueGrid.h
src/QmlControls/FactValueGrid.cc