QGroundControl: QmlUnitsConversion Class Reference
QmlUnitsConversion Class Reference
#include <QmlUnitsConversion.h>
Public Member Functions
QmlUnitsConversion (QObject *parent=nullptr)
~QmlUnitsConversion ()=default
QString appSettingsHorizontalDistanceUnitsString READ appSettingsHorizontalDistanceUnitsString CONSTANT (QString appSettingsVerticalDistanceUnitsString READ appSettingsVerticalDistanceUnitsString CONSTANT) 1(QString appSettingsAreaUnitsString READ appSettingsAreaUnitsString CONSTANT) 1(QString appSettingsWeightUnitsString READ appSettingsWeightUnitsString CONSTANT) 1(QString appSettingsSpeedUnitsString READ appSettingsSpeedUnitsString CONSTANT) 1 QVariant metersToAppSettingsHorizontalDistanceUnits(const QVariant &meters) const
Converts from meters to the user specified distance unit.
QVariant appSettingsHorizontalDistanceUnitsToMeters (const QVariant &distance) const
Converts from user specified distance unit to meters.
QString appSettingsHorizontalDistanceUnitsString (void) const
QVariant metersToAppSettingsVerticalDistanceUnits (const QVariant &meters) const
Converts from meters to the user specified distance unit.
QVariant appSettingsVerticalDistanceUnitsToMeters (const QVariant &distance) const
Converts from user specified distance unit to meters.
QString appSettingsVerticalDistanceUnitsString (void) const
QVariant gramsToAppSettingsWeightUnits (const QVariant &meters) const
Converts from grams to the user specified weight unit.
QVariant appSettingsWeightUnitsToGrams (const QVariant &distance) const
Converts from user specified weight unit to grams.
QString appSettingsWeightUnitsString (void) const
QVariant squareMetersToAppSettingsAreaUnits (const QVariant &meters) const
Converts from square meters to the user specified area unit.
QVariant appSettingsAreaUnitsToSquareMeters (const QVariant &area) const
Converts from user specified area unit to square meters.
QString appSettingsAreaUnitsString (void) const
QVariant metersSecondToAppSettingsSpeedUnits (const QVariant &metersSecond) const
Converts from meters/second to the user specified speed unit.
QVariant appSettingsSpeedUnitsToMetersSecond (const QVariant &speed) const
Converts from user specified speed unit to meters/second.
QString appSettingsSpeedUnitsString ()
Returns the string for speed units which has configued by user.
double degreesToRadians (double degrees)
double radiansToDegrees (double radians)
Detailed Description
Definition at line 7 of file QmlUnitsConversion.h.
Constructor & Destructor Documentation
QmlUnitsConversion()
QmlUnitsConversion::QmlUnitsConversion (QObject * parent = nullptr) inline
Definition at line 11 of file QmlUnitsConversion.h.
~QmlUnitsConversion()
QmlUnitsConversion::~QmlUnitsConversion () default
Member Function Documentation
appSettingsAreaUnitsString()
QString QmlUnitsConversion::appSettingsAreaUnitsString (void) const inline
Definition at line 50 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsAreaUnitsString().
appSettingsAreaUnitsToSquareMeters()
QVariant QmlUnitsConversion::appSettingsAreaUnitsToSquareMeters (const QVariant & area) const inline
Converts from user specified area unit to square meters.
Definition at line 48 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsAreaUnitsToSquareMeters().
appSettingsHorizontalDistanceUnitsString()
QString QmlUnitsConversion::appSettingsHorizontalDistanceUnitsString (void) const inline
Definition at line 26 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsHorizontalDistanceUnitsString().
appSettingsHorizontalDistanceUnitsToMeters()
QVariant QmlUnitsConversion::appSettingsHorizontalDistanceUnitsToMeters (const QVariant & distance) const inline
Converts from user specified distance unit to meters.
Definition at line 24 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsHorizontalDistanceUnitsToMeters().
appSettingsSpeedUnitsString()
QString QmlUnitsConversion::appSettingsSpeedUnitsString () inline
Returns the string for speed units which has configued by user.
Definition at line 59 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsSpeedUnitsString().
appSettingsSpeedUnitsToMetersSecond()
QVariant QmlUnitsConversion::appSettingsSpeedUnitsToMetersSecond (const QVariant & speed) const inline
Converts from user specified speed unit to meters/second.
Definition at line 56 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsSpeedUnitsToMetersSecond().
appSettingsVerticalDistanceUnitsString()
QString QmlUnitsConversion::appSettingsVerticalDistanceUnitsString (void) const inline
Definition at line 34 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsVerticalDistanceUnitsString().
appSettingsVerticalDistanceUnitsToMeters()
QVariant QmlUnitsConversion::appSettingsVerticalDistanceUnitsToMeters (const QVariant & distance) const inline
Converts from user specified distance unit to meters.
Definition at line 32 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsVerticalDistanceUnitsToMeters().
appSettingsWeightUnitsString()
QString QmlUnitsConversion::appSettingsWeightUnitsString (void) const inline
Definition at line 42 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsWeightUnitsString().
appSettingsWeightUnitsToGrams()
QVariant QmlUnitsConversion::appSettingsWeightUnitsToGrams (const QVariant & distance) const inline
Converts from user specified weight unit to grams.
Definition at line 40 of file QmlUnitsConversion.h.
References FactMetaData::appSettingsWeightUnitsToGrams().
CONSTANT()
QString appSettingsHorizontalDistanceUnitsString READ appSettingsHorizontalDistanceUnitsString QmlUnitsConversion::CONSTANT (QString appSettingsVerticalDistanceUnitsString READ appSettingsVerticalDistanceUnitsString CONSTANT) const & inline
Converts from meters to the user specified distance unit.
Definition at line 14 of file QmlUnitsConversion.h.
References FactMetaData::metersToAppSettingsHorizontalDistanceUnits().
degreesToRadians()
double QmlUnitsConversion::degreesToRadians (double degrees) inline
Definition at line 61 of file QmlUnitsConversion.h.
gramsToAppSettingsWeightUnits()
QVariant QmlUnitsConversion::gramsToAppSettingsWeightUnits (const QVariant & meters) const inline
Converts from grams to the user specified weight unit.
Definition at line 37 of file QmlUnitsConversion.h.
References FactMetaData::gramsToAppSettingsWeightUnits().
metersSecondToAppSettingsSpeedUnits()
QVariant QmlUnitsConversion::metersSecondToAppSettingsSpeedUnits (const QVariant & metersSecond) const inline
Converts from meters/second to the user specified speed unit.
Definition at line 53 of file QmlUnitsConversion.h.
References FactMetaData::metersSecondToAppSettingsSpeedUnits().
metersToAppSettingsVerticalDistanceUnits()
QVariant QmlUnitsConversion::metersToAppSettingsVerticalDistanceUnits (const QVariant & meters) const inline
Converts from meters to the user specified distance unit.
Definition at line 29 of file QmlUnitsConversion.h.
References FactMetaData::metersToAppSettingsVerticalDistanceUnits().
radiansToDegrees()
double QmlUnitsConversion::radiansToDegrees (double radians) inline
Definition at line 62 of file QmlUnitsConversion.h.
squareMetersToAppSettingsAreaUnits()
QVariant QmlUnitsConversion::squareMetersToAppSettingsAreaUnits (const QVariant & meters) const inline
Converts from square meters to the user specified area unit.
Definition at line 45 of file QmlUnitsConversion.h.
References FactMetaData::squareMetersToAppSettingsAreaUnits().
The documentation for this class was generated from the following file:
src/QmlControls/QmlUnitsConversion.h