QGroundControl: LogDownloadController Class Reference
LogDownloadController Class Reference
#include <LogDownloadController.h>
Signals
void requestingListChanged ()
void downloadingLogsChanged ()
void selectionChanged ()
void compressLogsChanged ()
void compressingChanged ()
void compressionProgressChanged ()
void compressionComplete (const QString &outputPath, const QString &error)
Public Member Functions
LogDownloadController (QObject *parent=nullptr)
~LogDownloadController ()
void refresh ()
void download (const QString &path=QString())
void eraseAll ()
void cancel ()
bool compressLogs () const
void setCompressLogs (bool compress)
bool compressing () const
float compressionProgress () const
bool compressLogFile (const QString &logPath)
Compress a single log file.
void cancelCompression ()
Cancel compression.
Detailed Description
Definition at line 17 of file LogDownloadController.h.
Constructor & Destructor Documentation
LogDownloadController()
LogDownloadController::LogDownloadController (QObject * parent = nullptr) explicit
Definition at line 18 of file LogDownloadController.cc.
References MultiVehicleManager::activeVehicleChanged().
~LogDownloadController()
LogDownloadController::~LogDownloadController ()
Definition at line 33 of file LogDownloadController.cc.
Member Function Documentation
cancel()
void LogDownloadController::cancel ()
Definition at line 463 of file LogDownloadController.cc.
cancelCompression()
void LogDownloadController::cancelCompression ()
Cancel compression.
Definition at line 662 of file LogDownloadController.cc.
compressing()
bool LogDownloadController::compressing () const inline
Definition at line 44 of file LogDownloadController.h.
compressingChanged
void LogDownloadController::compressingChanged () signal
compressionComplete
void LogDownloadController::compressionComplete (const QString & outputPath, const QString & error) signal
compressionProgress()
float LogDownloadController::compressionProgress () const inline
Definition at line 45 of file LogDownloadController.h.
compressionProgressChanged
void LogDownloadController::compressionProgressChanged () signal
compressLogFile()
bool LogDownloadController::compressLogFile (const QString & logPath)
Compress a single log file.
Definition at line 655 of file LogDownloadController.cc.
compressLogs()
bool LogDownloadController::compressLogs () const inline
Definition at line 42 of file LogDownloadController.h.
compressLogsChanged
void LogDownloadController::compressLogsChanged () signal
Referenced by setCompressLogs().
download()
void LogDownloadController::download (const QString & path = QString())
Definition at line 38 of file LogDownloadController.cc.
References AppSettings::logSavePath().
downloadingLogsChanged
void LogDownloadController::downloadingLogsChanged () signal
eraseAll()
void LogDownloadController::eraseAll ()
Definition at line 501 of file LogDownloadController.cc.
References Vehicle::defaultComponentId(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::getSystemId(), Vehicle::id(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), refresh(), Vehicle::sendMessageOnLinkThreadSafe(), and Vehicle::vehicleLinkManager().
refresh()
void LogDownloadController::refresh ()
Definition at line 440 of file LogDownloadController.cc.
References QmlObjectListModel::clearAndDeleteContents().
Referenced by eraseAll().
requestingListChanged
void LogDownloadController::requestingListChanged () signal
selectionChanged
void LogDownloadController::selectionChanged () signal
setCompressLogs()
void LogDownloadController::setCompressLogs (bool compress)
Definition at line 647 of file LogDownloadController.cc.
References compressLogsChanged().
The documentation for this class was generated from the following files:
src/AnalyzeView/LogDownloadController.h
src/AnalyzeView/LogDownloadController.cc