QGroundControl: VehicleHygrometerFactGroup Class Reference
VehicleHygrometerFactGroup Class Reference
#include <VehicleHygrometerFactGroup.h>
Protected Member Functions
void _handleHygrometerSensor (const mavlink_message_t &message)
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes
Fact _hygroTempFact = Fact(0, QStringLiteral("temperature"), FactMetaData::valueTypeDouble)
Fact _hygroHumiFact = Fact(0, QStringLiteral("humidity"), FactMetaData::valueTypeDouble)
Fact _hygroIDFact = Fact(0, QStringLiteral("hygrometerid"), FactMetaData::valueTypeUint16)
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Additional Inherited Members
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Detailed Description
Definition at line 5 of file VehicleHygrometerFactGroup.h.
Member Function Documentation
_handleHygrometerSensor()
void VehicleHygrometerFactGroup::_handleHygrometerSensor (const mavlink_message_t & message) protected
Definition at line 29 of file VehicleHygrometerFactGroup.cc.
References _hygroHumiFact, _hygroIDFact, _hygroTempFact, and FactGroup::_setTelemetryAvailable().
Member Data Documentation
_hygroHumiFact
Fact VehicleHygrometerFactGroup::_hygroHumiFact = Fact(0, QStringLiteral("humidity"), FactMetaData::valueTypeDouble) protected
Definition at line 26 of file VehicleHygrometerFactGroup.h.
Referenced by _handleHygrometerSensor().
_hygroIDFact
Fact VehicleHygrometerFactGroup::_hygroIDFact = Fact(0, QStringLiteral("hygrometerid"), FactMetaData::valueTypeUint16) protected
Definition at line 27 of file VehicleHygrometerFactGroup.h.
Referenced by _handleHygrometerSensor().
_hygroTempFact
Fact VehicleHygrometerFactGroup::_hygroTempFact = Fact(0, QStringLiteral("temperature"), FactMetaData::valueTypeDouble) protected
Definition at line 25 of file VehicleHygrometerFactGroup.h.
Referenced by _handleHygrometerSensor().
The documentation for this class was generated from the following files:
src/Vehicle/FactGroups/VehicleHygrometerFactGroup.h
src/Vehicle/FactGroups/VehicleHygrometerFactGroup.cc