QGroundControl: ToolStripAction Class Reference
ToolStripAction Class Reference
#include <ToolStripAction.h>
Signals
void enabledChanged (bool enabled)
void visibleChanged (bool visible)
void checkableChanged (bool checkable)
void checkedChanged (bool checked)
void showAlternateIconChanged (bool showAlternateIcon)
void biColorIconChanged (bool biColorIcon)
void fullColorIconChanged (bool fullColorIcon)
void nonExclusiveChanged (bool nonExclusive)
void toolStripIndexChanged (int toolStripIndex)
void textChanged (QString text)
void iconSourceChanged (QString iconSource)
void alternateIconSourceChanged (QString alternateIconSource)
void triggered (QObject *source)
void dropPanelComponentChanged (void)
Public Member Functions
ToolStripAction (QObject *parent=nullptr)
bool enabled READ enabled WRITE setEnabled NOTIFY enabledChanged (bool visible READ visible WRITE setVisible NOTIFY visibleChanged) 1(bool checkable READ checkable WRITE setCheckable NOTIFY checkableChanged) 1(bool checked READ checked WRITE setChecked NOTIFY checkedChanged) 1(bool showAlternateIcon READ showAlternateIcon WRITE setShowAlternateIcon NOTIFY showAlternateIconChanged) 1(bool biColorIcon READ biColorIcon WRITE setbiColorIcon NOTIFY biColorIconChanged) 1(bool fullColorIcon READ fullColorIcon WRITE setfullColorIcon NOTIFY fullColorIconChanged) 1(bool nonExclusive READ nonExclusive WRITE setNonExclusive NOTIFY nonExclusiveChanged) 1(int toolStripIndex READ toolStripIndex WRITE setToolStripIndex NOTIFY toolStripIndexChanged) 1(QString text READ text WRITE setText NOTIFY textChanged) 1(QString iconSource READ iconSource WRITE setIconSource NOTIFY iconSourceChanged) 1(QString alternateIconSource READ alternateIconSource WRITE setAlternateIconSource NOTIFY alternateIconSourceChanged) 1(QQmlComponent *dropPanelComponent READ dropPanelComponent WRITE setDropPanelComponent NOTIFY dropPanelComponentChanged) bool enabled(void) const
bool visible (void) const
bool checkable (void) const
bool checked (void) const
bool showAlternateIcon (void) const
bool biColorIcon (void) const
bool fullColorIcon (void) const
bool nonExclusive (void) const
int toolStripIndex (void) const
QString text (void) const
QString iconSource (void) const
QString alternateIconSource (void) const
QQmlComponent * dropPanelComponent (void) const
void setEnabled (bool enabled)
void setVisible (bool visible)
void setCheckable (bool checkable)
void setChecked (bool checked)
void setShowAlternateIcon (bool showAlternateIcon)
void setbiColorIcon (bool biColorIcon)
void setfullColorIcon (bool fullColorIcon)
void setNonExclusive (bool nonExclusive)
void setToolStripIndex (int toolStripIndex)
void setText (const QString &text)
void setIconSource (const QString &iconSource)
void setAlternateIconSource (const QString &alternateIconSource)
void setDropPanelComponent (QQmlComponent *dropPanelComponent)
Protected Attributes
bool _enabled = true
bool _visible = true
bool _checkable = false
bool _checked = false
bool _showAlternateIcon = false
bool _biColorIcon = false
bool _fullColorIcon = false
bool _nonExclusive = false
int _toolStripIndex = -1
QString _text
QString _iconSource
QString _alternateIconSource
QQmlComponent * _dropPanelComponent = nullptr
Detailed Description
Definition at line 7 of file ToolStripAction.h.
Constructor & Destructor Documentation
ToolStripAction()
ToolStripAction::ToolStripAction (QObject * parent = nullptr)
Definition at line 3 of file ToolStripAction.cc.
Member Function Documentation
alternateIconSource()
QString ToolStripAction::alternateIconSource (void) const inline
Definition at line 40 of file ToolStripAction.h.
References _alternateIconSource.
Referenced by setAlternateIconSource().
alternateIconSourceChanged
void ToolStripAction::alternateIconSourceChanged (QString alternateIconSource) signal
Referenced by setAlternateIconSource().
biColorIcon()
bool ToolStripAction::biColorIcon (void) const inline
Definition at line 34 of file ToolStripAction.h.
References _biColorIcon.
Referenced by setbiColorIcon().
biColorIconChanged
void ToolStripAction::biColorIconChanged (bool biColorIcon) signal
Referenced by setbiColorIcon().
checkable()
bool ToolStripAction::checkable (void) const inline
Definition at line 31 of file ToolStripAction.h.
References _checkable.
Referenced by setCheckable().
checkableChanged
void ToolStripAction::checkableChanged (bool checkable) signal
Referenced by setCheckable().
checked()
bool ToolStripAction::checked (void) const inline
Definition at line 32 of file ToolStripAction.h.
References _checked.
Referenced by setChecked().
checkedChanged
void ToolStripAction::checkedChanged (bool checked) signal
Referenced by setChecked().
dropPanelComponent()
QQmlComponent * ToolStripAction::dropPanelComponent (void) const inline
Definition at line 41 of file ToolStripAction.h.
References _dropPanelComponent.
Referenced by setDropPanelComponent().
dropPanelComponentChanged
void ToolStripAction::dropPanelComponentChanged (void) signal
Referenced by setDropPanelComponent().
enabledChanged [1/2]
void ToolStripAction::enabledChanged (bool enabled) signal
enabledChanged() [2/2]
bool enabled READ enabled WRITE setEnabled NOTIFY ToolStripAction::enabledChanged (bool visible READ visible WRITE setVisible NOTIFY visibleChanged) const inline
Definition at line 15 of file ToolStripAction.h.
References _enabled.
Referenced by setEnabled().
fullColorIcon()
bool ToolStripAction::fullColorIcon (void) const inline
Definition at line 35 of file ToolStripAction.h.
References _fullColorIcon.
Referenced by setfullColorIcon().
fullColorIconChanged
void ToolStripAction::fullColorIconChanged (bool fullColorIcon) signal
Referenced by setfullColorIcon().
iconSource()
QString ToolStripAction::iconSource (void) const inline
Definition at line 39 of file ToolStripAction.h.
References _iconSource.
Referenced by setIconSource().
iconSourceChanged
void ToolStripAction::iconSourceChanged (QString iconSource) signal
Referenced by setIconSource().
nonExclusive()
bool ToolStripAction::nonExclusive (void) const inline
Definition at line 36 of file ToolStripAction.h.
References _nonExclusive.
Referenced by setNonExclusive().
nonExclusiveChanged
void ToolStripAction::nonExclusiveChanged (bool nonExclusive) signal
Referenced by setNonExclusive().
setAlternateIconSource()
void ToolStripAction::setAlternateIconSource (const QString & alternateIconSource)
Definition at line 107 of file ToolStripAction.cc.
References _alternateIconSource, alternateIconSource(), and alternateIconSourceChanged().
setbiColorIcon()
void ToolStripAction::setbiColorIcon (bool biColorIcon)
Definition at line 53 of file ToolStripAction.cc.
References _biColorIcon, biColorIcon(), and biColorIconChanged().
setCheckable()
void ToolStripAction::setCheckable (bool checkable)
Definition at line 26 of file ToolStripAction.cc.
References _checkable, checkable(), and checkableChanged().
setChecked()
void ToolStripAction::setChecked (bool checked)
Definition at line 35 of file ToolStripAction.cc.
References _checked, checked(), and checkedChanged().
setDropPanelComponent()
void ToolStripAction::setDropPanelComponent (QQmlComponent * dropPanelComponent)
Definition at line 115 of file ToolStripAction.cc.
References _dropPanelComponent, dropPanelComponent(), and dropPanelComponentChanged().
setEnabled()
void ToolStripAction::setEnabled (bool enabled)
Definition at line 9 of file ToolStripAction.cc.
References _enabled, and enabledChanged().
setfullColorIcon()
void ToolStripAction::setfullColorIcon (bool fullColorIcon)
Definition at line 62 of file ToolStripAction.cc.
References _fullColorIcon, fullColorIcon(), and fullColorIconChanged().
setIconSource()
void ToolStripAction::setIconSource (const QString & iconSource)
Definition at line 98 of file ToolStripAction.cc.
References _iconSource, iconSource(), and iconSourceChanged().
setNonExclusive()
void ToolStripAction::setNonExclusive (bool nonExclusive)
Definition at line 71 of file ToolStripAction.cc.
References _nonExclusive, nonExclusive(), and nonExclusiveChanged().
setShowAlternateIcon()
void ToolStripAction::setShowAlternateIcon (bool showAlternateIcon)
Definition at line 44 of file ToolStripAction.cc.
References _showAlternateIcon, showAlternateIcon(), and showAlternateIconChanged().
setText()
void ToolStripAction::setText (const QString & text)
Definition at line 89 of file ToolStripAction.cc.
References _text, text(), and textChanged().
setToolStripIndex()
void ToolStripAction::setToolStripIndex (int toolStripIndex)
Definition at line 80 of file ToolStripAction.cc.
References _toolStripIndex, toolStripIndex(), and toolStripIndexChanged().
setVisible()
void ToolStripAction::setVisible (bool visible)
Definition at line 17 of file ToolStripAction.cc.
References _visible, visible(), and visibleChanged().
showAlternateIcon()
bool ToolStripAction::showAlternateIcon (void) const inline
Definition at line 33 of file ToolStripAction.h.
References _showAlternateIcon.
Referenced by setShowAlternateIcon().
showAlternateIconChanged
void ToolStripAction::showAlternateIconChanged (bool showAlternateIcon) signal
Referenced by setShowAlternateIcon().
text()
QString ToolStripAction::text (void) const inline
Definition at line 38 of file ToolStripAction.h.
References _text.
Referenced by setText().
textChanged
void ToolStripAction::textChanged (QString text) signal
Referenced by setText().
toolStripIndex()
int ToolStripAction::toolStripIndex (void) const inline
Definition at line 37 of file ToolStripAction.h.
References _toolStripIndex.
Referenced by setToolStripIndex().
toolStripIndexChanged
void ToolStripAction::toolStripIndexChanged (int toolStripIndex) signal
Referenced by setToolStripIndex().
triggered
void ToolStripAction::triggered (QObject * source) signal
visible()
bool ToolStripAction::visible (void) const inline
Definition at line 30 of file ToolStripAction.h.
References _visible.
Referenced by setVisible().
visibleChanged
void ToolStripAction::visibleChanged (bool visible) signal
Referenced by setVisible().
Member Data Documentation
_alternateIconSource
QString ToolStripAction::_alternateIconSource protected
Definition at line 85 of file ToolStripAction.h.
Referenced by alternateIconSource(), and setAlternateIconSource().
_biColorIcon
bool ToolStripAction::_biColorIcon = false protected
Definition at line 79 of file ToolStripAction.h.
Referenced by biColorIcon(), and setbiColorIcon().
_checkable
bool ToolStripAction::_checkable = false protected
Definition at line 76 of file ToolStripAction.h.
Referenced by checkable(), and setCheckable().
_checked
bool ToolStripAction::_checked = false protected
Definition at line 77 of file ToolStripAction.h.
Referenced by checked(), and setChecked().
_dropPanelComponent
QQmlComponent* ToolStripAction::_dropPanelComponent = nullptr protected
Definition at line 86 of file ToolStripAction.h.
Referenced by dropPanelComponent(), and setDropPanelComponent().
_enabled
bool ToolStripAction::_enabled = true protected
Definition at line 74 of file ToolStripAction.h.
Referenced by enabledChanged(), and setEnabled().
_fullColorIcon
bool ToolStripAction::_fullColorIcon = false protected
Definition at line 80 of file ToolStripAction.h.
Referenced by fullColorIcon(), and setfullColorIcon().
_iconSource
QString ToolStripAction::_iconSource protected
Definition at line 84 of file ToolStripAction.h.
Referenced by iconSource(), and setIconSource().
_nonExclusive
bool ToolStripAction::_nonExclusive = false protected
Definition at line 81 of file ToolStripAction.h.
Referenced by nonExclusive(), and setNonExclusive().
_showAlternateIcon
bool ToolStripAction::_showAlternateIcon = false protected
Definition at line 78 of file ToolStripAction.h.
Referenced by setShowAlternateIcon(), and showAlternateIcon().
_text
QString ToolStripAction::_text protected
Definition at line 83 of file ToolStripAction.h.
Referenced by setText(), and text().
_toolStripIndex
int ToolStripAction::_toolStripIndex = -1 protected
Definition at line 82 of file ToolStripAction.h.
Referenced by setToolStripIndex(), and toolStripIndex().
_visible
bool ToolStripAction::_visible = true protected
Definition at line 75 of file ToolStripAction.h.
Referenced by setVisible(), and visible().
The documentation for this class was generated from the following files:
src/QmlControls/ToolStripAction.h
src/QmlControls/ToolStripAction.cc