QGroundControl: Autotune Class Reference
Autotune Class Reference
#include <Autotune.h>
Public Slots
void sendMavlinkRequest ()
Signals
void autotuneChanged ()
Public Member Functions
Autotune (Vehicle *vehicle)
bool autotuneInProgress READ autotuneInProgress NOTIFY autotuneChanged (float autotuneProgress READ autotuneProgress NOTIFY autotuneChanged) 1(QString autotuneStatus READ autotuneStatus NOTIFY autotuneChanged) 1 void autotuneRequest()
bool autotuneInProgress ()
float autotuneProgress ()
QString autotuneStatus ()
Static Public Member Functions
static void ackHandler (void *resultHandlerData, int compId, const mavlink_command_ack_t &ack, Vehicle::MavCmdResultFailureCode_t failureCode)
static void progressHandler (void *progressHandlerData, int compId, const mavlink_command_ack_t &ack)
Detailed Description
Definition at line 9 of file Autotune.h.
Constructor & Destructor Documentation
Autotune()
Autotune::Autotune (Vehicle * vehicle) explicit
Definition at line 5 of file Autotune.cpp.
References sendMavlinkRequest().
Member Function Documentation
ackHandler()
void Autotune::ackHandler (void * resultHandlerData, int compId, const mavlink_command_ack_t & ack, Vehicle::MavCmdResultFailureCode_t failureCode) static
Definition at line 29 of file Autotune.cpp.
References Vehicle::MavCmdResultCommandResultOnly.
Referenced by sendMavlinkRequest().
autotuneChanged [1/2]
void Autotune::autotuneChanged () signal
autotuneChanged() [2/2]
bool autotuneInProgress READ autotuneInProgress NOTIFY Autotune::autotuneChanged (float autotuneProgress READ autotuneProgress NOTIFY autotuneChanged)
autotuneInProgress()
bool Autotune::autotuneInProgress () inline
Definition at line 27 of file Autotune.h.
autotuneProgress()
float Autotune::autotuneProgress () inline
Definition at line 28 of file Autotune.h.
autotuneStatus()
QString Autotune::autotuneStatus () inline
Definition at line 29 of file Autotune.h.
progressHandler()
void Autotune::progressHandler (void * progressHandlerData, int compId, const mavlink_command_ack_t & ack) static
Definition at line 56 of file Autotune.cpp.
Referenced by sendMavlinkRequest().
sendMavlinkRequest
void Autotune::sendMavlinkRequest () slot
Definition at line 149 of file Autotune.cpp.
References ackHandler(), progressHandler(), Vehicle::MavCmdAckHandlerInfo_s::progressHandler, Vehicle::MavCmdAckHandlerInfo_s::progressHandlerData, Vehicle::MavCmdAckHandlerInfo_s::resultHandler, Vehicle::MavCmdAckHandlerInfo_s::resultHandlerData, and Vehicle::sendMavCommandWithHandler().
Referenced by Autotune().
The documentation for this class was generated from the following files:
src/Vehicle/Autotune.h
src/Vehicle/Autotune.cpp