QGroundControl: FlightPathSegment Class Reference
FlightPathSegment Class Reference
#include <FlightPathSegment.h>
Public Types
enum SegmentType { SegmentTypeTakeoff , SegmentTypeGeneric , SegmentTypeLand , SegmentTypeTerrainFrame }
Public Slots
void setCoordinate1 (const QGeoCoordinate &coordinate)
void setCoordinate2 (const QGeoCoordinate &coordinate)
void setCoord1AMSLAlt (double alt)
void setCoord2AMSLAlt (double alt)
Signals
void coordinate1Changed (QGeoCoordinate coordinate)
void coordinate2Changed (QGeoCoordinate coordinate)
void coord1AMSLAltChanged (void)
void coord2AMSLAltChanged (void)
void specialVisualChanged (bool specialVisual)
void amslTerrainHeightsChanged (void)
void distanceBetweenChanged (double distanceBetween)
void finalDistanceBetweenChanged (double finalDistanceBetween)
void totalDistanceChanged (double totalDistance)
void terrainCollisionChanged (bool terrainCollision)
Public Member Functions
FlightPathSegment (SegmentType segmentType, const QGeoCoordinate &coord1, double coord1AMSLAlt, const QGeoCoordinate &coord2, double coord2AMSLAlt, bool queryTerrainData, QObject *parent)
QGeoCoordinate coordinate1 MEMBER _coord1 NOTIFY coordinate1Changed (QGeoCoordinate coordinate2 MEMBER _coord2 NOTIFY coordinate2Changed) 1(double coord1AMSLAlt MEMBER _coord1AMSLAlt NOTIFY coord1AMSLAltChanged) 1(double coord2AMSLAlt MEMBER _coord2AMSLAlt NOTIFY coord2AMSLAltChanged) 1(bool specialVisual READ specialVisual WRITE setSpecialVisual NOTIFY specialVisualChanged) 1(QVariantList amslTerrainHeights MEMBER _amslTerrainHeights NOTIFY amslTerrainHeightsChanged) 1(double distanceBetween MEMBER _distanceBetween NOTIFY distanceBetweenChanged) 1(double final DistanceBetween MEMBER _finalDistanceBetween NOTIFY final DistanceBetweenChanged) 1(double totalDistance MEMBER _totalDistance NOTIFY totalDistanceChanged) 1(bool terrainCollision MEMBER _terrainCollision NOTIFY terrainCollisionChanged) 1(SegmentType segmentType MEMBER _segmentType CONSTANT) QGeoCoordinate coordinate1(void) const
QGeoCoordinate coordinate2 (void) const
double coord1AMSLAlt (void) const
double coord2AMSLAlt (void) const
const QVariantList & amslTerrainHeights (void) const
double distanceBetween (void) const
double finalDistanceBetween (void) const
double totalDistance (void) const
bool specialVisual (void) const
bool terrainCollision (void) const
SegmentType segmentType (void) const
void setSpecialVisual (bool specialVisual)
Detailed Description
Definition at line 14 of file FlightPathSegment.h.
Member Enumeration Documentation
SegmentType
enum FlightPathSegment::SegmentType
Enumerator
SegmentTypeTakeoff
SegmentTypeGeneric
SegmentTypeLand
SegmentTypeTerrainFrame
Definition at line 20 of file FlightPathSegment.h.
Constructor & Destructor Documentation
FlightPathSegment()
FlightPathSegment::FlightPathSegment (SegmentType segmentType, const QGeoCoordinate & coord1, double coord1AMSLAlt, const QGeoCoordinate & coord2, double coord2AMSLAlt, bool queryTerrainData, QObject * parent)
Definition at line 7 of file FlightPathSegment.cc.
Member Function Documentation
amslTerrainHeights()
const QVariantList & FlightPathSegment::amslTerrainHeights (void) const inline
Definition at line 46 of file FlightPathSegment.h.
Referenced by ComplexMissionItem::_appendFlightPathSegment().
amslTerrainHeightsChanged
void FlightPathSegment::amslTerrainHeightsChanged (void) signal
Referenced by ComplexMissionItem::_appendFlightPathSegment().
coord1AMSLAlt()
double FlightPathSegment::coord1AMSLAlt (void) const inline
Definition at line 44 of file FlightPathSegment.h.
coord1AMSLAltChanged
void FlightPathSegment::coord1AMSLAltChanged (void) signal
Referenced by setCoord1AMSLAlt().
coord2AMSLAlt()
double FlightPathSegment::coord2AMSLAlt (void) const inline
Definition at line 45 of file FlightPathSegment.h.
coord2AMSLAltChanged
void FlightPathSegment::coord2AMSLAltChanged (void) signal
Referenced by setCoord2AMSLAlt().
coordinate1Changed [1/2]
void FlightPathSegment::coordinate1Changed (QGeoCoordinate coordinate) signal
coordinate1Changed() [2/2]
QGeoCoordinate coordinate1 MEMBER _coord1 NOTIFY FlightPathSegment::coordinate1Changed (QGeoCoordinate coordinate2 MEMBER _coord2 NOTIFY coordinate2Changed) const inline final
Definition at line 30 of file FlightPathSegment.h.
Referenced by setCoordinate1().
coordinate2()
QGeoCoordinate FlightPathSegment::coordinate2 (void) const inline
Definition at line 43 of file FlightPathSegment.h.
coordinate2Changed
void FlightPathSegment::coordinate2Changed (QGeoCoordinate coordinate) signal
Referenced by setCoordinate2().
distanceBetween()
double FlightPathSegment::distanceBetween (void) const inline
Definition at line 47 of file FlightPathSegment.h.
distanceBetweenChanged
void FlightPathSegment::distanceBetweenChanged (double distanceBetween) signal
finalDistanceBetween()
double FlightPathSegment::finalDistanceBetween (void) const inline
Definition at line 48 of file FlightPathSegment.h.
finalDistanceBetweenChanged
void FlightPathSegment::finalDistanceBetweenChanged (double finalDistanceBetween) signal
segmentType()
SegmentType FlightPathSegment::segmentType (void) const inline
Definition at line 52 of file FlightPathSegment.h.
setCoord1AMSLAlt
void FlightPathSegment::setCoord1AMSLAlt (double alt) slot
Definition at line 46 of file FlightPathSegment.cc.
References coord1AMSLAltChanged(), and QGC::fuzzyCompare().
setCoord2AMSLAlt
void FlightPathSegment::setCoord2AMSLAlt (double alt) slot
Definition at line 55 of file FlightPathSegment.cc.
References coord2AMSLAltChanged(), and QGC::fuzzyCompare().
setCoordinate1
void FlightPathSegment::setCoordinate1 (const QGeoCoordinate & coordinate) slot
Definition at line 26 of file FlightPathSegment.cc.
References coordinate1Changed().
setCoordinate2
void FlightPathSegment::setCoordinate2 (const QGeoCoordinate & coordinate) slot
Definition at line 36 of file FlightPathSegment.cc.
References coordinate2Changed().
setSpecialVisual()
void FlightPathSegment::setSpecialVisual (bool specialVisual)
Definition at line 64 of file FlightPathSegment.cc.
References specialVisual(), and specialVisualChanged().
specialVisual()
bool FlightPathSegment::specialVisual (void) const inline
Definition at line 50 of file FlightPathSegment.h.
Referenced by setSpecialVisual().
specialVisualChanged
void FlightPathSegment::specialVisualChanged (bool specialVisual) signal
Referenced by setSpecialVisual().
terrainCollision()
bool FlightPathSegment::terrainCollision (void) const inline
Definition at line 51 of file FlightPathSegment.h.
Referenced by ComplexMissionItem::_appendFlightPathSegment().
terrainCollisionChanged
void FlightPathSegment::terrainCollisionChanged (bool terrainCollision) signal
Referenced by ComplexMissionItem::_appendFlightPathSegment().
totalDistance()
double FlightPathSegment::totalDistance (void) const inline
Definition at line 49 of file FlightPathSegment.h.
Referenced by TerrainProfile::updatePaintNode().
totalDistanceChanged
void FlightPathSegment::totalDistanceChanged (double totalDistance) signal
The documentation for this class was generated from the following files:
src/QmlControls/FlightPathSegment.h
src/QmlControls/FlightPathSegment.cc