QGroundControl: MAVLinkStreamConfig Class Reference
MAVLinkStreamConfig Class Reference
#include <MAVLinkStreamConfig.h>
Public Types
using SetMessageIntervalCb = std::function< void(int messageId, int rate)>
Public Member Functions
MAVLinkStreamConfig (const SetMessageIntervalCb &messageIntervalCb)
~MAVLinkStreamConfig ()
void setHighRateRateAndAttitude ()
void setHighRateVelAndPos ()
void setHighRateAltAirspeed ()
void restoreDefaults ()
void gotSetMessageIntervalAck ()
Detailed Description
Allows to configure a set of mavlink streams to a specific rate, and restore back to default. Note that only one set is active at a time.
Definition at line 11 of file MAVLinkStreamConfig.h.
Member Typedef Documentation
SetMessageIntervalCb
using MAVLinkStreamConfig::SetMessageIntervalCb = std::function<void(int messageId, int rate)>
Definition at line 14 of file MAVLinkStreamConfig.h.
Constructor & Destructor Documentation
MAVLinkStreamConfig()
MAVLinkStreamConfig::MAVLinkStreamConfig (const SetMessageIntervalCb & messageIntervalCb)
Definition at line 7 of file MAVLinkStreamConfig.cc.
~MAVLinkStreamConfig()
MAVLinkStreamConfig::~MAVLinkStreamConfig ()
Definition at line 13 of file MAVLinkStreamConfig.cc.
Member Function Documentation
gotSetMessageIntervalAck()
void MAVLinkStreamConfig::gotSetMessageIntervalAck ()
Definition at line 52 of file MAVLinkStreamConfig.cc.
restoreDefaults()
void MAVLinkStreamConfig::restoreDefaults ()
Definition at line 96 of file MAVLinkStreamConfig.cc.
Referenced by Vehicle::setPIDTuningTelemetryMode().
setHighRateAltAirspeed()
void MAVLinkStreamConfig::setHighRateAltAirspeed ()
Definition at line 42 of file MAVLinkStreamConfig.cc.
Referenced by Vehicle::setPIDTuningTelemetryMode().
setHighRateRateAndAttitude()
void MAVLinkStreamConfig::setHighRateRateAndAttitude ()
Definition at line 18 of file MAVLinkStreamConfig.cc.
Referenced by Vehicle::setPIDTuningTelemetryMode().
setHighRateVelAndPos()
void MAVLinkStreamConfig::setHighRateVelAndPos ()
Definition at line 32 of file MAVLinkStreamConfig.cc.
Referenced by Vehicle::setPIDTuningTelemetryMode().
The documentation for this class was generated from the following files:
src/MAVLink/MAVLinkStreamConfig.h
src/MAVLink/MAVLinkStreamConfig.cc