QGroundControl: TerrainPathQuery Class Reference
TerrainPathQuery Class Reference
#include <TerrainQuery.h>
Public Types
using PathHeightInfo_t = TerrainPathHeightInfo
Signals
void terrainDataReceived (bool success, const TerrainPathQuery::PathHeightInfo_t &pathHeightInfo)
Signalled when terrain data comes back from server.
Public Member Functions
TerrainPathQuery (bool autoDelete, QObject *parent=nullptr)
~TerrainPathQuery ()
void requestData (const QGeoCoordinate &fromCoord, const QGeoCoordinate &toCoord)
Detailed Description
Definition at line 101 of file TerrainQuery.h.
Member Typedef Documentation
PathHeightInfo_t
using TerrainPathQuery::PathHeightInfo_t = TerrainPathHeightInfo
Definition at line 115 of file TerrainQuery.h.
Constructor & Destructor Documentation
TerrainPathQuery()
TerrainPathQuery::TerrainPathQuery (bool autoDelete, QObject * parent = nullptr) explicit
Parameters
autoDelete true: object will delete itself after it signals results
Definition at line 197 of file TerrainQuery.cc.
References TerrainQueryInterface::pathHeightsReceived().
~TerrainPathQuery()
TerrainPathQuery::~TerrainPathQuery ()
Definition at line 208 of file TerrainQuery.cc.
Member Function Documentation
requestData()
void TerrainPathQuery::requestData (const QGeoCoordinate & fromCoord, const QGeoCoordinate & toCoord)
Async terrain query for terrain heights between two lat/lon coordinates. When the query is done, the terrainData() signal is emitted.
Parameters
coordinates to query
Definition at line 213 of file TerrainQuery.cc.
References TerrainQueryInterface::requestPathHeights().
Referenced by TerrainPolyPathQuery::requestData().
terrainDataReceived
void TerrainPathQuery::terrainDataReceived (bool success, const TerrainPathQuery::PathHeightInfo_t & pathHeightInfo) signal
Signalled when terrain data comes back from server.
Referenced by TerrainPolyPathQuery::TerrainPolyPathQuery().
The documentation for this class was generated from the following files:
src/Terrain/TerrainQuery.h
src/Terrain/TerrainQuery.cc