QGroundControl: QGeoTiledMapReplyQGC Class Reference
QGeoTiledMapReplyQGC Class Reference
#include <QGeoMapReplyQGC.h>
Public Member Functions
QGeoTiledMapReplyQGC (QNetworkAccessManager *networkManager, const QNetworkRequest &request, const QGeoTileSpec &spec, QObject *parent=nullptr)
~QGeoTiledMapReplyQGC ()
bool init ()
void abort () final
Detailed Description
Definition at line 13 of file QGeoMapReplyQGC.h.
Constructor & Destructor Documentation
QGeoTiledMapReplyQGC()
QGeoTiledMapReplyQGC::QGeoTiledMapReplyQGC (QNetworkAccessManager * networkManager, const QNetworkRequest & request, const QGeoTileSpec & spec, QObject * parent = nullptr) explicit
Definition at line 23 of file QGeoMapReplyQGC.cpp.
~QGeoTiledMapReplyQGC()
QGeoTiledMapReplyQGC::~QGeoTiledMapReplyQGC ()
Definition at line 31 of file QGeoMapReplyQGC.cpp.
Member Function Documentation
abort()
void QGeoTiledMapReplyQGC::abort () final
Definition at line 217 of file QGeoMapReplyQGC.cpp.
init()
bool QGeoTiledMapReplyQGC::init ()
Definition at line 36 of file QGeoMapReplyQGC.cpp.
References QGCMapEngine::addTask(), QGeoFileTileCacheQGC::createFetchTileTask(), QGCMapTask::error(), error, errorString, UrlFactory::getProviderTypeFromQtMapId(), getQGCMapEngine(), and QGCFetchTileTask::tileFetched().
Referenced by TerrainTileManager::getAltitudesForCoordinates().
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGeoMapReplyQGC.h
src/QtLocationPlugin/QGeoMapReplyQGC.cpp