QGroundControl: SimpleMissionItem Class Reference
SimpleMissionItem Class Reference
A SimpleMissionItem is used to represent a single MissionItem to the ui.
#include <SimpleMissionItem.h>
Signals
void commandChanged (int command)
void friendlyEditAllowedChanged (bool friendlyEditAllowed)
void headingDegreesChanged (double heading)
void rawEditChanged (bool rawEdit)
void cameraSectionChanged (QObject *cameraSection)
void speedSectionChanged (QObject *cameraSection)
void altitudeFrameChanged (void)
void isLoiterItemChanged (void)
void showLoiterRadiusChanged (void)
void loiterRadiusChanged (double loiterRadius)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
SimpleMissionItem (PlanMasterController *masterController, bool flyView, bool forLoad)
SimpleMissionItem (PlanMasterController *masterController, bool flyView, const MissionItem &missionItem)
~SimpleMissionItem ()
QString category READ category NOTIFY commandChanged (bool friendlyEditAllowed READ friendlyEditAllowed NOTIFY friendlyEditAllowedChanged) 1(bool rawEdit READ rawEdit WRITE setRawEdit NOTIFY rawEditChanged) 1(bool specifiesAltitude READ specifiesAltitude NOTIFY commandChanged) 1(Fact *altitude READ altitude CONSTANT) 1(QGroundControlQmlGlobal
< true: raw item editing with all params
bool scanForSections (QmlObjectListModel *visualItems, int scanIndex, PlanMasterController *masterController)
QString category (void) const
int command (void) const
MAV_CMD mavCommand (void) const
bool friendlyEditAllowed (void) const
bool rawEdit (void) const
bool specifiesAltitude (void) const
QGroundControlQmlGlobal::AltitudeFrame altitudeFrame (void) const
Fact * altitude (void)
Fact * amslAltAboveTerrain (void)
bool isLoiterItem (void) const
bool showLoiterRadius (void) const
double loiterRadius (void) const
CameraSection * cameraSection (void)
SpeedSection * speedSection (void)
QmlObjectListModel * textFieldFacts (void)
QmlObjectListModel * textFieldFactsAdvanced (void)
QmlObjectListModel * nanFacts (void)
QmlObjectListModel * nanFactsAdvanced (void)
QmlObjectListModel * comboboxFacts (void)
QmlObjectListModel * comboboxFactsAdvanced (void)
void setRawEdit (bool rawEdit)
void setAltitudeFrame (QGroundControlQmlGlobal::AltitudeFrame altitudeFrame)
void setCommandByIndex (int index)
void setCommand (int command)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setRadius (double loiterRadius)
virtual bool load (QTextStream &loadStream)
virtual bool load (const QJsonObject &json, int sequenceNumber, QString &errorString)
MissionItem & missionItem (void)
const MissionItem & missionItem (void) const
bool dirty (void) const override
bool isSimpleItem (void) const final
bool isStandaloneCoordinate (void) const final
bool isLandCommand (void) const final
bool specifiesCoordinate (void) const final
bool specifiesAltitudeOnly (void) const final
QString commandDescription (void) const final
QString commandName (void) const final
QString abbreviation (void) const final
QGeoCoordinate coordinate (void) const final
QGeoCoordinate entryCoordinate (void) const final
QGeoCoordinate exitCoordinate (void) const final
double editableAlt (void) const final
double amslEntryAlt (void) const final
double amslExitAlt (void) const final
int sequenceNumber (void) const final
double specifiedFlightSpeed (void) override
double specifiedGimbalYaw (void) override
double specifiedGimbalPitch (void) override
double specifiedVehicleYaw (void) override
QString mapVisualQML (void) const override
void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent) final
void applyNewAltitude (double newAltitude) final
Adjust the altitude of the item if appropriate to the new altitude.
void setMissionFlightStatus (MissionFlightStatus_t &missionFlightStatus) final
ReadyForSaveState readyForSaveState (void) const final
double additionalTimeDelay (void) const final
bool exitCoordinateSameAsEntry (void) const final
void setDirty (bool dirty) final
void setCoordinate (const QGeoCoordinate &coordinate) override
void setSequenceNumber (int sequenceNumber) final
int lastSequenceNumber (void) const final
void save (QJsonArray &missionItems) final
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool isTakeoffItem (void) const
virtual bool isSurveyItem (void) const
virtual QGCGeoBoundingCube * boundingCube (void)
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Detailed Description
A SimpleMissionItem is used to represent a single MissionItem to the ui.
Definition at line 11 of file SimpleMissionItem.h.
Constructor & Destructor Documentation
SimpleMissionItem() [1/2]
SimpleMissionItem::SimpleMissionItem (PlanMasterController * masterController, bool flyView, bool forLoad)
Definition at line 26 of file SimpleMissionItem.cc.
References VisualMissionItem::_editorQml, and setDirty().
SimpleMissionItem() [2/2]
SimpleMissionItem::SimpleMissionItem (PlanMasterController * masterController, bool flyView, const MissionItem & missionItem)
Definition at line 53 of file SimpleMissionItem.cc.
References VisualMissionItem::_editorQml, VisualMissionItem::_flyView, VisualMissionItem::_isCurrentItem, QGroundControlQmlGlobal::AltitudeFrameAbsolute, QGroundControlQmlGlobal::AltitudeFrameRelative, QGroundControlQmlGlobal::AltitudeFrameTerrain, coordinate(), VisualMissionItem::coordinateChanged(), MissionItem::frame(), MissionItem::isCurrentItem(), missionItem(), setDirty(), and specifiesAltitude().
~SimpleMissionItem()
SimpleMissionItem::~SimpleMissionItem ()
Definition at line 242 of file SimpleMissionItem.cc.
Member Function Documentation
abbreviation()
QString SimpleMissionItem::abbreviation (void) const final virtual
Implements VisualMissionItem.
Definition at line 374 of file SimpleMissionItem.cc.
References command().
additionalTimeDelay()
double SimpleMissionItem::additionalTimeDelay (void) const final virtual
Returns
Amount of additional time delay in seconds needed to fly this item
Implements VisualMissionItem.
Definition at line 1069 of file SimpleMissionItem.cc.
References command(), missionItem(), and MissionItem::param1().
altitude()
Fact * SimpleMissionItem::altitude (void) inline
Definition at line 68 of file SimpleMissionItem.h.
Referenced by MissionController::insertTakeoffItem().
altitudeFrame()
QGroundControlQmlGlobal::AltitudeFrame SimpleMissionItem::altitudeFrame (void) const inline
Definition at line 67 of file SimpleMissionItem.h.
Referenced by setAltitudeFrame().
altitudeFrameChanged
void SimpleMissionItem::altitudeFrameChanged (void) signal
Referenced by setAltitudeFrame().
amslAltAboveTerrain()
Fact * SimpleMissionItem::amslAltAboveTerrain (void) inline
Definition at line 69 of file SimpleMissionItem.h.
amslEntryAlt()
double SimpleMissionItem::amslEntryAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 1113 of file SimpleMissionItem.cc.
References VisualMissionItem::_masterController, VisualMissionItem::_terrainAltitude, QGroundControlQmlGlobal::AltitudeFrameAbsolute, QGroundControlQmlGlobal::AltitudeFrameCalcAboveTerrain, QGroundControlQmlGlobal::AltitudeFrameMixed, QGroundControlQmlGlobal::AltitudeFrameNone, QGroundControlQmlGlobal::AltitudeFrameRelative, QGroundControlQmlGlobal::AltitudeFrameTerrain, PlanMasterController::missionController(), MissionItem::param7(), and MissionController::plannedHomePosition().
Referenced by amslExitAlt().
amslExitAlt()
double SimpleMissionItem::amslExitAlt (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 118 of file SimpleMissionItem.h.
References amslEntryAlt().
appendMissionItems()
void SimpleMissionItem::appendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) final virtual
Returns the mission items associated with the complex item. Caller is responsible for freeing.
Parameters
items List to append to
missionItemParent Parent object for newly created MissionItems
Implements VisualMissionItem.
Definition at line 1014 of file SimpleMissionItem.cc.
References CameraSection::appendSectionItems(), SpeedSection::appendSectionItems(), missionItem(), and sequenceNumber().
Referenced by save().
applyNewAltitude()
void SimpleMissionItem::applyNewAltitude (double newAltitude) final virtual
Adjust the altitude of the item if appropriate to the new altitude.
Implements VisualMissionItem.
Definition at line 1025 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), MissionCommandUIInfo::specifiesAltitudeOnly(), and MissionCommandUIInfo::specifiesCoordinate().
cameraSection()
CameraSection * SimpleMissionItem::cameraSection (void) inline
Definition at line 74 of file SimpleMissionItem.h.
cameraSectionChanged
void SimpleMissionItem::cameraSectionChanged (QObject * cameraSection) signal
category()
QString SimpleMissionItem::category (void) const
Definition at line 871 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, MissionCommandUIInfo::category(), command(), MissionCommandTree::getUIInfo(), and MissionCommandTree::instance().
comboboxFacts()
QmlObjectListModel * SimpleMissionItem::comboboxFacts (void) inline
Definition at line 81 of file SimpleMissionItem.h.
comboboxFactsAdvanced()
QmlObjectListModel * SimpleMissionItem::comboboxFactsAdvanced (void) inline
Definition at line 82 of file SimpleMissionItem.h.
command()
int SimpleMissionItem::command (void) const inline
Definition at line 62 of file SimpleMissionItem.h.
Referenced by abbreviation(), additionalTimeDelay(), applyNewAltitude(), category(), commandDescription(), commandName(), friendlyEditAllowed(), isLandCommand(), isLoiterItem(), isStandaloneCoordinate(), TakeoffMissionItem::isTakeoffCommand(), loiterRadius(), mavCommand(), MissionFlightStatusCalculator::recalc(), CameraSection::scanStopTakingPhotos(), CameraSection::scanStopTakingVideo(), setCommand(), setRadius(), showLoiterRadius(), specifiedVehicleYaw(), specifiesAltitudeOnly(), and specifiesCoordinate().
commandChanged() [1/2]
QString category READ category NOTIFY SimpleMissionItem::commandChanged (bool friendlyEditAllowed READ friendlyEditAllowed NOTIFY friendlyEditAllowedChanged) inline
< true: raw item editing with all params
< Altitude as specified by altitudeFrame. Not necessarily true mission item altitude This should be called before changing the command. It is needed if the command changes from an item which does not include a coordinate to an item which requires a coordinate. It uses this value to set that new coordinate.
Definition at line 23 of file SimpleMissionItem.h.
commandChanged [2/2]
void SimpleMissionItem::commandChanged (int command) signal
commandDescription()
QString SimpleMissionItem::commandDescription (void) const final virtual
Implements VisualMissionItem.
Definition at line 352 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), commandName(), MissionCommandUIInfo::description(), MissionCommandTree::getUIInfo(), and MissionCommandTree::instance().
commandName()
QString SimpleMissionItem::commandName (void) const final virtual
Implements VisualMissionItem.
Definition at line 363 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandUIInfo::friendlyName(), MissionCommandTree::getUIInfo(), and MissionCommandTree::instance().
Referenced by commandDescription().
coordinate()
QGeoCoordinate SimpleMissionItem::coordinate (void) const final virtual
Implements VisualMissionItem.
Definition at line 1099 of file SimpleMissionItem.cc.
References MissionItem::param5(), and MissionItem::param6().
Referenced by entryCoordinate(), exitCoordinate(), setCoordinate(), TakeoffMissionItem::setCoordinate(), MissionController::setCurrentPlanViewSeqNum(), and SimpleMissionItem().
dirty()
bool SimpleMissionItem::dirty (void) const inline override virtual
Implements VisualMissionItem.
Definition at line 104 of file SimpleMissionItem.h.
Referenced by setDirty().
editableAlt()
double SimpleMissionItem::editableAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 1108 of file SimpleMissionItem.cc.
References MissionItem::param7().
entryCoordinate()
QGeoCoordinate SimpleMissionItem::entryCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 114 of file SimpleMissionItem.h.
References coordinate().
Referenced by MissionFlightStatusCalculator::recalc().
exitCoordinate()
QGeoCoordinate SimpleMissionItem::exitCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 115 of file SimpleMissionItem.h.
References coordinate().
exitCoordinateSameAsEntry()
bool SimpleMissionItem::exitCoordinateSameAsEntry (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 130 of file SimpleMissionItem.h.
friendlyEditAllowed()
bool SimpleMissionItem::friendlyEditAllowed (void) const
Definition at line 652 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, MissionItem::autoContinue(), command(), MissionItem::frame(), MissionCommandUIInfo::friendlyEdit(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), and specifiesAltitude().
Referenced by rawEdit().
friendlyEditAllowedChanged
void SimpleMissionItem::friendlyEditAllowedChanged (bool friendlyEditAllowed) signal
headingDegreesChanged
void SimpleMissionItem::headingDegreesChanged (double heading) signal
isLandCommand()
bool SimpleMissionItem::isLandCommand (void) const final virtual
Reimplemented from VisualMissionItem.
Definition at line 1094 of file SimpleMissionItem.cc.
References command(), MissionCommandTree::instance(), and MissionCommandTree::isLandCommand().
isLoiterItem()
bool SimpleMissionItem::isLoiterItem (void) const
Definition at line 551 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), and MissionCommandUIInfo::isLoiterCommand().
Referenced by loiterRadius(), setRadius(), and showLoiterRadius().
isLoiterItemChanged
void SimpleMissionItem::isLoiterItemChanged (void) signal
isSimpleItem()
bool SimpleMissionItem::isSimpleItem (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 105 of file SimpleMissionItem.h.
isStandaloneCoordinate()
bool SimpleMissionItem::isStandaloneCoordinate (void) const final virtual
Implements VisualMissionItem.
Definition at line 322 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), and MissionCommandUIInfo::isStandaloneCoordinate().
Referenced by MissionController::setCurrentPlanViewSeqNum().
lastSequenceNumber()
int SimpleMissionItem::lastSequenceNumber (void) const final virtual
Implements VisualMissionItem.
Definition at line 997 of file SimpleMissionItem.cc.
References CameraSection::itemCount(), SpeedSection::itemCount(), and sequenceNumber().
load() [1/2]
bool SimpleMissionItem::load (const QJsonObject & json, int sequenceNumber, QString & errorString) virtual
Reimplemented in TakeoffMissionItem.
Definition at line 287 of file SimpleMissionItem.cc.
References QGroundControlQmlGlobal::AltitudeFrameAbsolute, QGroundControlQmlGlobal::AltitudeFrameRelative, errorString, MissionItem::load(), JsonParsing::possibleNaNJsonValue(), MissionItem::relativeAltitude(), sequenceNumber(), setDirty(), specifiesAltitude(), and JsonHelper::validateKeys().
load() [2/2]
bool SimpleMissionItem::load (QTextStream & loadStream) virtual
Reimplemented in TakeoffMissionItem.
Definition at line 269 of file SimpleMissionItem.cc.
References QGroundControlQmlGlobal::AltitudeFrameAbsolute, QGroundControlQmlGlobal::AltitudeFrameRelative, MissionItem::load(), MissionItem::relativeAltitude(), setDirty(), and specifiesAltitude().
Referenced by TakeoffMissionItem::load(), and TakeoffMissionItem::load().
loiterRadius()
double SimpleMissionItem::loiterRadius (void) const
Definition at line 578 of file SimpleMissionItem.cc.
References command(), isLoiterItem(), missionItem(), MissionItem::param2(), and MissionItem::param3().
loiterRadiusChanged
void SimpleMissionItem::loiterRadiusChanged (double loiterRadius) signal
mapVisualQML()
QString SimpleMissionItem::mapVisualQML (void) const inline override virtual
Returns
The QML resource file which contains the control which visualizes the item on the map.
Implements VisualMissionItem.
Reimplemented in TakeoffMissionItem.
Definition at line 124 of file SimpleMissionItem.h.
mavCommand()
MAV_CMD SimpleMissionItem::mavCommand (void) const inline
Definition at line 63 of file SimpleMissionItem.h.
References command().
Referenced by MissionFlightStatusCalculator::recalc(), and MissionController::setCurrentPlanViewSeqNum().
missionItem() [1/2]
MissionItem & SimpleMissionItem::missionItem (void) inline
Definition at line 100 of file SimpleMissionItem.h.
Referenced by LandingComplexItem::_scanForItem(), additionalTimeDelay(), appendMissionItems(), MissionController::insertCancelROIMissionItem(), MissionController::insertROIMissionItem(), loiterRadius(), MissionFlightStatusCalculator::recalc(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), CameraSection::scanStopTakingVideo(), SimpleMissionItem(), specifiedFlightSpeed(), specifiedGimbalPitch(), specifiedGimbalYaw(), and specifiedVehicleYaw().
missionItem() [2/2]
const MissionItem & SimpleMissionItem::missionItem (void) const inline
Definition at line 101 of file SimpleMissionItem.h.
nanFacts()
QmlObjectListModel * SimpleMissionItem::nanFacts (void) inline
Definition at line 79 of file SimpleMissionItem.h.
nanFactsAdvanced()
QmlObjectListModel * SimpleMissionItem::nanFactsAdvanced (void) inline
Definition at line 80 of file SimpleMissionItem.h.
rawEdit()
bool SimpleMissionItem::rawEdit (void) const
Definition at line 678 of file SimpleMissionItem.cc.
References friendlyEditAllowed().
Referenced by setRawEdit().
rawEditChanged
void SimpleMissionItem::rawEditChanged (bool rawEdit) signal
Referenced by setRawEdit().
readyForSaveState()
SimpleMissionItem::ReadyForSaveState SimpleMissionItem::readyForSaveState (void) const final virtual
Returns
Returns whether the item is ready for save and if not, why
Reimplemented from VisualMissionItem.
Definition at line 790 of file SimpleMissionItem.cc.
References VisualMissionItem::_wizardMode, VisualMissionItem::NotReadyForSaveData, VisualMissionItem::NotReadyForSaveTerrain, VisualMissionItem::ReadyForSave, and specifiesAltitude().
save()
void SimpleMissionItem::save (QJsonArray & missionItems) final virtual
Save the item(s) in Json format
Parameters
missionItems Current set of mission items, new items should be appended to the end
Implements VisualMissionItem.
Definition at line 246 of file SimpleMissionItem.cc.
References appendMissionItems(), MissionItem::save(), and specifiesAltitude().
scanForSections()
bool SimpleMissionItem::scanForSections (QmlObjectListModel * visualItems, int scanIndex, PlanMasterController * masterController)
Scans the loaded items for additional section settings
Parameters
visualItems List of all visual items
scanIndex Index to start scanning from
vehicle Vehicle associated with this mission
Returns
true: section found, scanIndex updated
Definition at line 946 of file SimpleMissionItem.cc.
References CameraSection::available(), SpeedSection::available(), CameraSection::scanForSection(), and SpeedSection::scanForSection().
sequenceNumber()
int SimpleMissionItem::sequenceNumber (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 119 of file SimpleMissionItem.h.
References MissionItem::sequenceNumber().
Referenced by appendMissionItems(), MissionController::insertTakeoffItem(), lastSequenceNumber(), load(), TakeoffMissionItem::load(), and setSequenceNumber().
setAltDifference()
void SimpleMissionItem::setAltDifference (double altDifference)
setAltitudeFrame()
void SimpleMissionItem::setAltitudeFrame (QGroundControlQmlGlobal::AltitudeFrame altitudeFrame)
Definition at line 1061 of file SimpleMissionItem.cc.
References altitudeFrame(), and altitudeFrameChanged().
Referenced by MissionController::insertTakeoffItem().
setAltPercent()
void SimpleMissionItem::setAltPercent (double altPercent)
setAzimuth()
void SimpleMissionItem::setAzimuth (double azimuth)
setCommand()
void SimpleMissionItem::setCommand (int command)
Definition at line 877 of file SimpleMissionItem.cc.
References MissionItem::command(), command(), and MissionItem::setCommand().
Referenced by MissionController::insertCancelROIMissionItem(), MissionController::insertROIMissionItem(), and TakeoffMissionItem::TakeoffMissionItem().
setCommandByIndex()
void SimpleMissionItem::setCommandByIndex (int index)
setCoordinate()
void SimpleMissionItem::setCoordinate (const QGeoCoordinate & coordinate) override virtual
Implements VisualMissionItem.
Reimplemented in TakeoffMissionItem.
Definition at line 896 of file SimpleMissionItem.cc.
References coordinate(), MissionItem::param5(), MissionItem::param6(), MissionItem::setParam5(), and MissionItem::setParam6().
Referenced by TakeoffMissionItem::setCoordinate().
setDirty()
void SimpleMissionItem::setDirty (bool dirty) final virtual
Implements VisualMissionItem.
Definition at line 691 of file SimpleMissionItem.cc.
References VisualMissionItem::_homePositionSpecialCase, dirty(), VisualMissionItem::dirtyChanged(), CameraSection::setDirty(), and SpeedSection::setDirty().
Referenced by load(), load(), SimpleMissionItem(), and SimpleMissionItem().
setDistance()
void SimpleMissionItem::setDistance (double distance)
setMissionFlightStatus()
void SimpleMissionItem::setMissionFlightStatus (MissionFlightStatus_t & missionFlightStatus) final virtual
Update item to mission flight status at point where this item appears in mission. IMPORTANT: Overrides must call base class implementation
Reimplemented from VisualMissionItem.
Definition at line 1043 of file SimpleMissionItem.cc.
References CameraSection::available(), SpeedSection::available(), SpeedSection::flightSpeed(), QGC::fuzzyCompare(), CameraSection::gimbalPitch(), MissionFlightStatus_t::gimbalPitch, CameraSection::gimbalYaw(), MissionFlightStatus_t::gimbalYaw, VisualMissionItem::setMissionFlightStatus(), and MissionFlightStatus_t::vehicleSpeed.
setRadius()
void SimpleMissionItem::setRadius (double loiterRadius)
Definition at line 885 of file SimpleMissionItem.cc.
References command(), isLoiterItem(), MissionItem::setParam2(), and MissionItem::setParam3().
setRawEdit()
void SimpleMissionItem::setRawEdit (bool rawEdit)
Definition at line 683 of file SimpleMissionItem.cc.
References rawEdit(), and rawEditChanged().
setSequenceNumber()
void SimpleMissionItem::setSequenceNumber (int sequenceNumber) final virtual
Implements VisualMissionItem.
Definition at line 905 of file SimpleMissionItem.cc.
References VisualMissionItem::abbreviationChanged(), MissionItem::sequenceNumber(), sequenceNumber(), VisualMissionItem::sequenceNumberChanged(), and MissionItem::setSequenceNumber().
Referenced by MissionController::insertTakeoffItem().
showLoiterRadius()
bool SimpleMissionItem::showLoiterRadius (void) const
Definition at line 561 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), Vehicle::fixedWing(), MissionCommandUIInfo::getParamInfo(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), isLoiterItem(), specifiesCoordinate(), and Vehicle::vtol().
showLoiterRadiusChanged
void SimpleMissionItem::showLoiterRadiusChanged (void) signal
specifiedFlightSpeed()
double SimpleMissionItem::specifiedFlightSpeed (void) override virtual
Implements VisualMissionItem.
Reimplemented in TakeoffMissionItem.
Definition at line 915 of file SimpleMissionItem.cc.
References SpeedSection::flightSpeed(), missionItem(), and MissionItem::specifiedFlightSpeed().
specifiedGimbalPitch()
double SimpleMissionItem::specifiedGimbalPitch (void) override virtual
Implements VisualMissionItem.
Reimplemented in TakeoffMissionItem.
Definition at line 929 of file SimpleMissionItem.cc.
References CameraSection::available(), missionItem(), CameraSection::specifiedGimbalPitch(), and MissionItem::specifiedGimbalPitch().
specifiedGimbalYaw()
double SimpleMissionItem::specifiedGimbalYaw (void) override virtual
Implements VisualMissionItem.
Reimplemented in TakeoffMissionItem.
Definition at line 924 of file SimpleMissionItem.cc.
References CameraSection::available(), missionItem(), CameraSection::specifiedGimbalYaw(), and MissionItem::specifiedGimbalYaw().
specifiedVehicleYaw()
double SimpleMissionItem::specifiedVehicleYaw (void) override virtual
Reimplemented from VisualMissionItem.
Definition at line 934 of file SimpleMissionItem.cc.
References command(), missionItem(), and MissionItem::param4().
Referenced by MissionFlightStatusCalculator::recalc().
specifiesAltitude()
bool SimpleMissionItem::specifiesAltitude (void) const
Definition at line 546 of file SimpleMissionItem.cc.
References specifiesAltitudeOnly(), and specifiesCoordinate().
Referenced by friendlyEditAllowed(), MissionController::insertTakeoffItem(), load(), load(), readyForSaveState(), save(), and SimpleMissionItem().
specifiesAltitudeOnly()
bool SimpleMissionItem::specifiesAltitudeOnly (void) const final virtual
Implements VisualMissionItem.
Definition at line 342 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), and MissionCommandUIInfo::specifiesAltitudeOnly().
Referenced by specifiesAltitude().
specifiesCoordinate()
bool SimpleMissionItem::specifiesCoordinate (void) const final virtual
Implements VisualMissionItem.
Definition at line 332 of file SimpleMissionItem.cc.
References VisualMissionItem::_controllerVehicle, VisualMissionItem::_previousVTOLMode, command(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), and MissionCommandUIInfo::specifiesCoordinate().
Referenced by MissionController::setCurrentPlanViewSeqNum(), showLoiterRadius(), and specifiesAltitude().
speedSection()
SpeedSection * SimpleMissionItem::speedSection (void) inline
Definition at line 75 of file SimpleMissionItem.h.
speedSectionChanged
void SimpleMissionItem::speedSectionChanged (QObject * cameraSection) signal
textFieldFacts()
QmlObjectListModel * SimpleMissionItem::textFieldFacts (void) inline
Definition at line 77 of file SimpleMissionItem.h.
textFieldFactsAdvanced()
QmlObjectListModel * SimpleMissionItem::textFieldFactsAdvanced (void) inline
Definition at line 78 of file SimpleMissionItem.h.
The documentation for this class was generated from the following files:
src/MissionManager/SimpleMissionItem.h
src/MissionManager/SimpleMissionItem.cc