QGroundControl: ArduPlaneFirmwarePlugin Class Reference
ArduPlaneFirmwarePlugin Class Reference
#include <ArduPlaneFirmwarePlugin.h>
Public Member Functions
ArduPlaneFirmwarePlugin (QObject *parent=nullptr)
~ArduPlaneFirmwarePlugin ()
QString offlineEditingParamFile (Vehicle *vehicle) const override
Return the resource file which contains the set of params loaded for offline editing.
QString autoDisarmParameter (Vehicle *vehicle) const override
int remapParamNameHigestMinorVersionNumber (int majorVersionNumber) const override
Returns the highest major version number that is known to the remap for this specified major version.
const FirmwarePlugin::remapParamNameMajorVersionMap_t & paramNameRemapMajorVersionMap () const override
Returns the mapping structure which is used to map from one parameter name to another based on firmware version.
QString pauseFlightMode () const override
Returns The flight mode which indicates the vehicle is paused.
QString takeOffFlightMode () const override
Returns the flight mode for TakeOff.
QString stabilizedFlightMode () const override
Returns the flight mode for Stabilized.
void updateAvailableFlightModes (FlightModeList &modeList) override
Update Available flight modes recieved from vehicle.
Public Member Functions inherited from APMFirmwarePlugin
QList< MAV_CMD > supportedMissionCommands (QGCMAVLink::VehicleClass_t vehicleClass) const override
List of supported mission commands. Empty list for all commands supported.
AutoPilotPlugin * autopilotPlugin (Vehicle *vehicle) const override
bool isCapable (const Vehicle *vehicle, FirmwareCapabilities capabilities) const override
void setGuidedMode (Vehicle *vehicle, bool guidedMode) const override
Set guided flight mode.
void guidedModeTakeoff (Vehicle *vehicle, double altitudeRel) const override
Command vehicle to takeoff from current location to the specified height.
void guidedModeGotoLocation (Vehicle *vehicle, const QGeoCoordinate &gotoCoord, double forwardFlightLoiterRadius) const override
Command vehicle to move to specified location (altitude is included and relative)
double minimumTakeoffAltitudeMeters (Vehicle *vehicle) const override
void startTakeoff (Vehicle *vehicle) const override
Command the vehicle to start a takeoff.
void startMission (Vehicle *vehicle) const override
Command the vehicle to start the mission.
QStringList flightModes (Vehicle *vehicle) const override
QString flightMode (uint8_t base_mode, uint32_t custom_mode) const override
bool setFlightMode (const QString &flightMode, uint8_t *base_mode, uint32_t *custom_mode) const override
bool MAV_CMD_DO_SET_MODE_is_supported () const override
returns true if this flight stack supports MAV_CMD_DO_SET_MODE
bool isGuidedMode (const Vehicle *vehicle) const override
Returns whether the vehicle is in guided mode or not.
QString gotoFlightMode () const override
Returns the flight mode which the vehicle will be in if it is performing a goto location.
QString rtlFlightMode () const override
Returns the flight mode for RTL.
QString smartRTLFlightMode () const override
Returns the flight mode for Smart RTL.
QString missionFlightMode () const override
Returns the flight mode for running missions.
virtual QString guidedFlightMode () const
void pauseVehicle (Vehicle *vehicle) const override
void guidedModeRTL (Vehicle *vehicle, bool smartRTL) const override
Command vehicle to return to launch.
void guidedModeChangeAltitude (Vehicle *vehicle, double altitudeChange, bool pauseVehicle) override
void guidedModeChangeHeading (Vehicle *vehicle, const QGeoCoordinate &headingCoord) const override
Command vehicle to rotate towards specified location.
bool adjustIncomingMavlinkMessage (Vehicle *vehicle, mavlink_message_t *message) override
void adjustOutgoingMavlinkMessageThreadSafe (Vehicle *vehicle, LinkInterface *outgoingLink, mavlink_message_t *message) override
virtual void initializeStreamRates (Vehicle *vehicle)
void initializeVehicle (Vehicle *vehicle) override
Called when Vehicle is first created to perform any firmware specific setup.
bool sendHomePositionToVehicle () const override
QString missionCommandOverrides (QGCMAVLink::VehicleClass_t vehicleClass) const override
QString _internalParameterMetaDataFile (const Vehicle *vehicle) const override
FactMetaData * _getMetaDataForFact (QObject *parameterMetaData, const QString &name, FactMetaData::ValueType_t type, MAV_TYPE vehicleType) const override
void _getParameterMetaDataVersionInfo (const QString &metaDataFile, int &majorVersion, int &minorVersion) const override
QObject * _loadParameterMetaData (const QString &metaDataFile) override
QString brandImageIndoor (const Vehicle *vehicle) const override
Return the resource file which contains the brand image for the vehicle for Indoor theme.
QString brandImageOutdoor (const Vehicle *vehicle) const override
Return the resource file which contains the brand image for the vehicle for Outdoor theme.
QString getHobbsMeter (Vehicle *vehicle) const override
gets hobbs meter from autopilot. This should be reimplmeented for each firmware
bool hasGripper (const Vehicle *vehicle) const override
const QVariantList & toolIndicators (const Vehicle *vehicle) override
double maximumEquivalentAirspeed (Vehicle *vehicle) const override
double minimumEquivalentAirspeed (Vehicle *vehicle) const override
bool fixedWingAirSpeedLimitsAvailable (Vehicle *vehicle) const override
void guidedModeChangeEquivalentAirspeedMetersSecond (Vehicle *vehicle, double airspeed_equiv) const override
void sendGCSMotionReport (Vehicle *vehicle, const FollowMe::GCSMotionReport &motionReport, uint8_t estimatationCapabilities) const override
Sends the appropriate mavlink message for follow me support.
QVariant expandedToolbarIndicatorSource (const Vehicle *vehicle, const QString &indicatorName) const override
bool mulirotorSpeedLimitsAvailable (Vehicle *vehicle) const override
double maximumHorizontalSpeedMultirotor (Vehicle *vehicle) const override
void guidedModeChangeGroundSpeedMetersSecond (Vehicle *vehicle, double speed) const override
Public Member Functions inherited from FirmwarePlugin
FirmwarePlugin (QObject *parent=nullptr)
virtual ~FirmwarePlugin ()
virtual bool supportsSmartRTL () const
virtual QString landFlightMode () const
Returns the flight mode for Land.
virtual QString motorDetectionFlightMode () const
Returns the flight mode for Motor Detection.
virtual QString takeControlFlightMode () const
Returns the flight mode to use when the operator wants to take back control from autonomouse flight.
virtual QString followFlightMode () const
Returns the flight mode which the vehicle will be for follow me.
virtual void guidedModeLand (Vehicle *vehicle) const
Command vehicle to land at current location.
virtual int defaultJoystickTXMode () const
virtual bool supportsThrottleModeCenterZero () const
virtual bool supportsNegativeThrust (Vehicle *) const
virtual bool supportsRadio () const
virtual bool supportsJSButton () const
virtual bool supportsMotorInterference () const
virtual bool multiRotorCoaxialMotors (Vehicle *) const
virtual bool multiRotorXConfig (Vehicle *) const
virtual QString vehicleImageOpaque (const Vehicle *) const
Return the resource file which contains the vehicle icon used in the flight view when the view is dark (Satellite for instance)
virtual QString vehicleImageOutline (const Vehicle *) const
Return the resource file which contains the vehicle icon used in the flight view when the view is light (Map for instance)
virtual QGCCameraManager * createCameraManager (Vehicle *vehicle) const
Creates vehicle camera manager.
virtual MavlinkCameraControl * createCameraControl (const mavlink_camera_information_t *info, Vehicle *vehicle, int compID, QObject *parent=nullptr) const
Camera control.
virtual QMap< QString, FactGroup * > * factGroups ()
Returns a pointer to a dictionary of firmware-specific FactGroups.
virtual void batteryConsumptionData (Vehicle *vehicle, int &mAhBattery, double &hoverAmps, double &cruiseAmps) const
virtual bool hasGimbal (Vehicle *vehicle, bool &rollSupported, bool &pitchSupported, bool &yawSupported) const
virtual uint32_t highLatencyCustomModeTo32Bits (uint16_t hlCustomMode) const
Convert from HIGH_LATENCY2.custom_mode value to correct 32 bit value.
virtual void checkIfIsLatestStable (Vehicle *vehicle) const
Used to check if running firmware is latest stable version.
int versionCompare (const Vehicle *vehicle, const QString &compare) const
int versionCompare (const Vehicle *vehicle, int major, int minor, int patch) const
virtual void adjustMetaData (MAV_TYPE, FactMetaData *)
virtual Autotune * createAutotune (Vehicle *vehicle) const
Creates Autotune object.
Protected Member Functions
uint32_t _convertToCustomFlightModeEnum (uint32_t val) const override
Protected Member Functions inherited from APMFirmwarePlugin
APMFirmwarePlugin (QObject *parent=nullptr)
All access to singleton is through stack specific implementation.
virtual ~APMFirmwarePlugin ()
void setSupportedModes (QList< APMCustomMode > supportedModes)
Protected Member Functions inherited from FirmwarePlugin
bool _armVehicleAndValidate (Vehicle *vehicle) const
bool _setFlightModeAndValidate (Vehicle *vehicle, const QString &flightMode) const
virtual void _versionFileDownloadFinished (const QString &remoteFile, const QString &localFile, const Vehicle *vehicle) const
Callback to process file with latest release information.
void _setModeEnumToModeStringMapping (FlightModeCustomModeMap enumToString)
void _updateFlightModeList (FlightModeList &flightModeList)
void _addNewFlightMode (FirmwareFlightMode &flightMode)
Protected Attributes
const QString _manualFlightMode = tr("Manual")
const QString _circleFlightMode = tr("Circle")
const QString _stabilizeFlightMode = tr("Stabilize")
const QString _trainingFlightMode = tr("Training")
const QString _acroFlightMode = tr("Acro")
const QString _flyByWireAFlightMode = tr("FBW A")
const QString _flyByWireBFlightMode = tr("FBW B")
const QString _cruiseFlightMode = tr("Cruise")
const QString _autoTuneFlightMode = tr("Autotune")
const QString _autoFlightMode = tr("Auto")
const QString _rtlFlightMode = tr("RTL")
const QString _loiterFlightMode = tr("Loiter")
const QString _takeoffFlightMode = tr("Takeoff")
const QString _avoidADSBFlightMode = tr("Avoid ADSB")
const QString _guidedFlightMode = tr("Guided")
const QString _initializingFlightMode = tr("Initializing")
const QString _qStabilizeFlightMode = tr("QuadPlane Stabilize")
const QString _qHoverFlightMode = tr("QuadPlane Hover")
const QString _qLoiterFlightMode = tr("QuadPlane Loiter")
const QString _qLandFlightMode = tr("QuadPlane Land")
const QString _qRTLFlightMode = tr("QuadPlane RTL")
const QString _qAutotuneFlightMode = tr("QuadPlane AutoTune")
const QString _qAcroFlightMode = tr("QuadPlane Acro")
const QString _thermalFlightMode = tr("Thermal")
const QString _loiter2qlandFlightMode = tr("Loiter to QLand")
const QString _autolandFlightMode = tr("Autoland")
Protected Attributes inherited from APMFirmwarePlugin
bool _coaxialMotors = false
const QString _guidedFlightMode = tr("Guided")
const QString _rtlFlightMode = tr("RTL")
const QString _smartRtlFlightMode = tr("Smart RTL")
const QString _autoFlightMode = tr("Auto")
Protected Attributes inherited from FirmwarePlugin
FlightModeList _flightModeList
FlightModeCustomModeMap _modeEnumToString
QVariantList _toolIndicatorList
QVariantList _modeIndicatorList
Additional Inherited Members
Public Types inherited from FirmwarePlugin
enum FirmwareCapabilities {
SetFlightModeCapability = 1 << 0 , PauseVehicleCapability = 1 << 1 , GuidedModeCapability = 1 << 2 , OrbitModeCapability = 1 << 3 ,
TakeoffVehicleCapability = 1 << 4 , ROIModeCapability = 1 << 5 , ChangeHeadingCapability = 1 << 6 , GuidedTakeoffCapability = 1 << 7
}
Set of optional capabilites which firmware may support.
typedef QMap< QString, QString > remapParamNameMap_t
typedef QMap< int, remapParamNameMap_t > remapParamNameMinorVersionRemapMap_t
typedef QMap< int, remapParamNameMinorVersionRemapMap_t > remapParamNameMajorVersionMap_t
Signals inherited from FirmwarePlugin
void toolIndicatorsChanged ()
Static Public Member Functions inherited from APMFirmwarePlugin
static QPair< QMetaObject::Connection, QMetaObject::Connection > startCompensatingBaro (Vehicle *vehicle)
static bool stopCompensatingBaro (const Vehicle *vehicle, QPair< QMetaObject::Connection, QMetaObject::Connection > updaters)
static qreal calcAltOffsetPT (uint32_t atmospheric1, qreal temperature1, uint32_t atmospheric2, qreal temperature2)
static qreal calcAltOffsetP (uint32_t atmospheric1, uint32_t atmospheric2)
Detailed Description
Definition at line 38 of file ArduPlaneFirmwarePlugin.h.
Constructor & Destructor Documentation
ArduPlaneFirmwarePlugin()
ArduPlaneFirmwarePlugin::ArduPlaneFirmwarePlugin (QObject * parent = nullptr) explicit
Definition at line 7 of file ArduPlaneFirmwarePlugin.cc.
References _acroFlightMode, _autoFlightMode, _autolandFlightMode, _autoTuneFlightMode, _avoidADSBFlightMode, _circleFlightMode, _cruiseFlightMode, _flyByWireAFlightMode, _flyByWireBFlightMode, _guidedFlightMode, _initializingFlightMode, _loiter2qlandFlightMode, _loiterFlightMode, _manualFlightMode, _qAcroFlightMode, _qAutotuneFlightMode, _qHoverFlightMode, _qLandFlightMode, _qLoiterFlightMode, _qRTLFlightMode, _qStabilizeFlightMode, _rtlFlightMode, FirmwarePlugin::_setModeEnumToModeStringMapping(), _stabilizeFlightMode, _takeoffFlightMode, _thermalFlightMode, _trainingFlightMode, APMPlaneMode::ACRO, APMPlaneMode::AUTO, APMPlaneMode::AUTOLAND, APMPlaneMode::AUTOTUNE, APMPlaneMode::AVOID_ADSB, APMPlaneMode::CIRCLE, APMPlaneMode::CRUISE, APMPlaneMode::FLY_BY_WIRE_A, APMPlaneMode::FLY_BY_WIRE_B, APMPlaneMode::GUIDED, APMPlaneMode::INITIALIZING, APMPlaneMode::LOITER, APMPlaneMode::LOITER2QLAND, APMPlaneMode::MANUAL, APMPlaneMode::QACRO, APMPlaneMode::QAUTOTUNE, APMPlaneMode::QHOVER, APMPlaneMode::QLAND, APMPlaneMode::QLOITER, APMPlaneMode::QRTL, APMPlaneMode::QSTABILIZE, APMPlaneMode::RTL, APMPlaneMode::STABILIZE, APMPlaneMode::TAKEOFF, APMPlaneMode::THERMAL, APMPlaneMode::TRAINING, and updateAvailableFlightModes().
~ArduPlaneFirmwarePlugin()
ArduPlaneFirmwarePlugin::~ArduPlaneFirmwarePlugin ()
Definition at line 83 of file ArduPlaneFirmwarePlugin.cc.
Member Function Documentation
_convertToCustomFlightModeEnum()
uint32_t ArduPlaneFirmwarePlugin::_convertToCustomFlightModeEnum (uint32_t val) const override protected virtual
Reimplemented from FirmwarePlugin.
Definition at line 119 of file ArduPlaneFirmwarePlugin.cc.
References APMCustomMode::AUTO, APMPlaneMode::AUTO, APMCustomMode::GUIDED, APMPlaneMode::GUIDED, APMCustomMode::RTL, APMPlaneMode::RTL, and APMCustomMode::SMART_RTL.
autoDisarmParameter()
QString ArduPlaneFirmwarePlugin::autoDisarmParameter (Vehicle * vehicle) const inline override virtual
Reimplemented from FirmwarePlugin.
Definition at line 47 of file ArduPlaneFirmwarePlugin.h.
offlineEditingParamFile()
QString ArduPlaneFirmwarePlugin::offlineEditingParamFile (Vehicle *) const inline override virtual
Return the resource file which contains the set of params loaded for offline editing.
Reimplemented from FirmwarePlugin.
Definition at line 46 of file ArduPlaneFirmwarePlugin.h.
paramNameRemapMajorVersionMap()
const FirmwarePlugin::remapParamNameMajorVersionMap_t & ArduPlaneFirmwarePlugin::paramNameRemapMajorVersionMap (void) const inline override virtual
Returns the mapping structure which is used to map from one parameter name to another based on firmware version.
Reimplemented from FirmwarePlugin.
Definition at line 49 of file ArduPlaneFirmwarePlugin.h.
pauseFlightMode()
QString ArduPlaneFirmwarePlugin::pauseFlightMode (void) const override virtual
Returns The flight mode which indicates the vehicle is paused.
Reimplemented from FirmwarePlugin.
Definition at line 104 of file ArduPlaneFirmwarePlugin.cc.
References _loiterFlightMode, FirmwarePlugin::_modeEnumToString, and APMPlaneMode::LOITER.
remapParamNameHigestMinorVersionNumber()
int ArduPlaneFirmwarePlugin::remapParamNameHigestMinorVersionNumber (int) const override virtual
Returns the highest major version number that is known to the remap for this specified major version.
Reimplemented from FirmwarePlugin.
Definition at line 88 of file ArduPlaneFirmwarePlugin.cc.
References Vehicle::versionNotSetValue.
stabilizedFlightMode()
QString ArduPlaneFirmwarePlugin::stabilizedFlightMode (void) const override virtual
Returns the flight mode for Stabilized.
Reimplemented from FirmwarePlugin.
Definition at line 99 of file ArduPlaneFirmwarePlugin.cc.
References FirmwarePlugin::_modeEnumToString, _stabilizeFlightMode, and APMPlaneMode::STABILIZE.
takeOffFlightMode()
QString ArduPlaneFirmwarePlugin::takeOffFlightMode (void) const override virtual
Returns the flight mode for TakeOff.
Reimplemented from FirmwarePlugin.
Definition at line 94 of file ArduPlaneFirmwarePlugin.cc.
References FirmwarePlugin::_modeEnumToString, _takeoffFlightMode, and APMPlaneMode::TAKEOFF.
updateAvailableFlightModes()
void ArduPlaneFirmwarePlugin::updateAvailableFlightModes (FlightModeList & flightModeList) override virtual
Update Available flight modes recieved from vehicle.
Reimplemented from FirmwarePlugin.
Definition at line 109 of file ArduPlaneFirmwarePlugin.cc.
References FirmwarePlugin::_updateFlightModeList().
Referenced by ArduPlaneFirmwarePlugin().
Member Data Documentation
_acroFlightMode
const QString ArduPlaneFirmwarePlugin::_acroFlightMode = tr("Acro") protected
Definition at line 62 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_autoFlightMode
const QString ArduPlaneFirmwarePlugin::_autoFlightMode = tr("Auto") protected
Definition at line 67 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_autolandFlightMode
const QString ArduPlaneFirmwarePlugin::_autolandFlightMode = tr("Autoland") protected
Definition at line 83 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_autoTuneFlightMode
const QString ArduPlaneFirmwarePlugin::_autoTuneFlightMode = tr("Autotune") protected
Definition at line 66 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_avoidADSBFlightMode
const QString ArduPlaneFirmwarePlugin::_avoidADSBFlightMode = tr("Avoid ADSB") protected
Definition at line 71 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_circleFlightMode
const QString ArduPlaneFirmwarePlugin::_circleFlightMode = tr("Circle") protected
Definition at line 59 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_cruiseFlightMode
const QString ArduPlaneFirmwarePlugin::_cruiseFlightMode = tr("Cruise") protected
Definition at line 65 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_flyByWireAFlightMode
const QString ArduPlaneFirmwarePlugin::_flyByWireAFlightMode = tr("FBW A") protected
Definition at line 63 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_flyByWireBFlightMode
const QString ArduPlaneFirmwarePlugin::_flyByWireBFlightMode = tr("FBW B") protected
Definition at line 64 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_guidedFlightMode
const QString ArduPlaneFirmwarePlugin::_guidedFlightMode = tr("Guided") protected
Definition at line 72 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_initializingFlightMode
const QString ArduPlaneFirmwarePlugin::_initializingFlightMode = tr("Initializing") protected
Definition at line 73 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_loiter2qlandFlightMode
const QString ArduPlaneFirmwarePlugin::_loiter2qlandFlightMode = tr("Loiter to QLand") protected
Definition at line 82 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_loiterFlightMode
const QString ArduPlaneFirmwarePlugin::_loiterFlightMode = tr("Loiter") protected
Definition at line 69 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin(), and pauseFlightMode().
_manualFlightMode
const QString ArduPlaneFirmwarePlugin::_manualFlightMode = tr("Manual") protected
Definition at line 58 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qAcroFlightMode
const QString ArduPlaneFirmwarePlugin::_qAcroFlightMode = tr("QuadPlane Acro") protected
Definition at line 80 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qAutotuneFlightMode
const QString ArduPlaneFirmwarePlugin::_qAutotuneFlightMode = tr("QuadPlane AutoTune") protected
Definition at line 79 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qHoverFlightMode
const QString ArduPlaneFirmwarePlugin::_qHoverFlightMode = tr("QuadPlane Hover") protected
Definition at line 75 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qLandFlightMode
const QString ArduPlaneFirmwarePlugin::_qLandFlightMode = tr("QuadPlane Land") protected
Definition at line 77 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qLoiterFlightMode
const QString ArduPlaneFirmwarePlugin::_qLoiterFlightMode = tr("QuadPlane Loiter") protected
Definition at line 76 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qRTLFlightMode
const QString ArduPlaneFirmwarePlugin::_qRTLFlightMode = tr("QuadPlane RTL") protected
Definition at line 78 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_qStabilizeFlightMode
const QString ArduPlaneFirmwarePlugin::_qStabilizeFlightMode = tr("QuadPlane Stabilize") protected
Definition at line 74 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_rtlFlightMode
const QString ArduPlaneFirmwarePlugin::_rtlFlightMode = tr("RTL") protected
Definition at line 68 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_stabilizeFlightMode
const QString ArduPlaneFirmwarePlugin::_stabilizeFlightMode = tr("Stabilize") protected
Definition at line 60 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin(), and stabilizedFlightMode().
_takeoffFlightMode
const QString ArduPlaneFirmwarePlugin::_takeoffFlightMode = tr("Takeoff") protected
Definition at line 70 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin(), and takeOffFlightMode().
_thermalFlightMode
const QString ArduPlaneFirmwarePlugin::_thermalFlightMode = tr("Thermal") protected
Definition at line 81 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
_trainingFlightMode
const QString ArduPlaneFirmwarePlugin::_trainingFlightMode = tr("Training") protected
Definition at line 61 of file ArduPlaneFirmwarePlugin.h.
Referenced by ArduPlaneFirmwarePlugin().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.h
src/FirmwarePlugin/APM/ArduPlaneFirmwarePlugin.cc