QGroundControl: TerrainPolyPathQuery Class Reference
TerrainPolyPathQuery Class Reference
#include <TerrainQuery.h>
Signals
void terrainDataReceived (bool success, const QList< TerrainPathQuery::PathHeightInfo_t > &rgPathHeightInfo)
Signalled when terrain data comes back from server.
Public Member Functions
TerrainPolyPathQuery (bool autoDelete, QObject *parent=nullptr)
~TerrainPolyPathQuery ()
void requestData (const QVariantList &polyPath)
void requestData (const QList< QGeoCoordinate > &polyPath)
Detailed Description
Definition at line 166 of file TerrainQuery.h.
Constructor & Destructor Documentation
TerrainPolyPathQuery()
TerrainPolyPathQuery::TerrainPolyPathQuery (bool autoDelete, QObject * parent = nullptr) explicit
Parameters
autoDelete true: object will delete itself after it signals results
Definition at line 267 of file TerrainQuery.cc.
References TerrainPathQuery::terrainDataReceived().
~TerrainPolyPathQuery()
TerrainPolyPathQuery::~TerrainPolyPathQuery ()
Definition at line 278 of file TerrainQuery.cc.
Member Function Documentation
requestData() [1/2]
void TerrainPolyPathQuery::requestData (const QList< QGeoCoordinate > & polyPath)
Definition at line 294 of file TerrainQuery.cc.
References TerrainPathQuery::requestData(), and terrainDataReceived().
requestData() [2/2]
void TerrainPolyPathQuery::requestData (const QVariantList & polyPath)
Async terrain query for terrain heights for the paths between each specified QGeoCoordinate. When the query is done, the terrainData() signal is emitted.
Parameters
polyPath List of QGeoCoordinate
Definition at line 283 of file TerrainQuery.cc.
References requestData().
Referenced by requestData().
terrainDataReceived
void TerrainPolyPathQuery::terrainDataReceived (bool success, const QList< TerrainPathQuery::PathHeightInfo_t > & rgPathHeightInfo) signal
Signalled when terrain data comes back from server.
Referenced by requestData().
The documentation for this class was generated from the following files:
src/Terrain/TerrainQuery.h
src/Terrain/TerrainQuery.cc