QGroundControl: AppSettings Class Reference
AppSettings Class Reference
Application Settings.
#include <AppSettings.h>
Signals
void savePathsChanged ()
Signals inherited from SettingsGroup
void visibleChanged ()
Public Member Functions
AppSettings (QObject *parent=nullptr)
Fact *offlineEditingFirmwareClass READ offlineEditingFirmwareClass CONSTANT Fact * offlineEditingFirmwareClass ()
Fact *offlineEditingVehicleClass READ offlineEditingVehicleClass CONSTANT Fact * offlineEditingVehicleClass ()
Fact *offlineEditingCruiseSpeed READ offlineEditingCruiseSpeed CONSTANT Fact * offlineEditingCruiseSpeed ()
Fact *offlineEditingHoverSpeed READ offlineEditingHoverSpeed CONSTANT Fact * offlineEditingHoverSpeed ()
Fact *offlineEditingAscentSpeed READ offlineEditingAscentSpeed CONSTANT Fact * offlineEditingAscentSpeed ()
Fact *offlineEditingDescentSpeed READ offlineEditingDescentSpeed CONSTANT Fact * offlineEditingDescentSpeed ()
Fact *batteryPercentRemainingAnnounce READ batteryPercentRemainingAnnounce CONSTANT Fact * batteryPercentRemainingAnnounce ()
Fact *defaultMissionItemAltitude READ defaultMissionItemAltitude CONSTANT Fact * defaultMissionItemAltitude ()
Fact *audioMuted READ audioMuted CONSTANT Fact * audioMuted ()
Fact *virtualJoystick READ virtualJoystick CONSTANT Fact * virtualJoystick ()
Fact *virtualJoystickAutoCenterThrottle READ virtualJoystickAutoCenterThrottle CONSTANT Fact * virtualJoystickAutoCenterThrottle ()
Fact *virtualJoystickLeftHandedMode READ virtualJoystickLeftHandedMode CONSTANT Fact * virtualJoystickLeftHandedMode ()
Fact *appFontPointSize READ appFontPointSize CONSTANT Fact * appFontPointSize ()
Fact *indoorPalette READ indoorPalette CONSTANT Fact * indoorPalette ()
Fact *savePath READ savePath CONSTANT Fact * savePath ()
Fact *androidDontSaveToSDCard READ androidDontSaveToSDCard CONSTANT Fact * androidDontSaveToSDCard ()
Fact *useChecklist READ useChecklist CONSTANT Fact * useChecklist ()
Fact *enforceChecklist READ enforceChecklist CONSTANT Fact * enforceChecklist ()
Fact *enableMultiVehiclePanel READ enableMultiVehiclePanel CONSTANT Fact * enableMultiVehiclePanel ()
Fact *tiandituToken READ tiandituToken CONSTANT Fact * tiandituToken ()
Fact *mapboxToken READ mapboxToken CONSTANT Fact * mapboxToken ()
Fact *mapboxAccount READ mapboxAccount CONSTANT Fact * mapboxAccount ()
Fact *mapboxStyle READ mapboxStyle CONSTANT Fact * mapboxStyle ()
Fact *esriToken READ esriToken CONSTANT Fact * esriToken ()
Fact *customURL READ customURL CONSTANT Fact * customURL ()
Fact *vworldToken READ vworldToken CONSTANT Fact * vworldToken ()
Fact *openaipToken READ openaipToken CONSTANT Fact * openaipToken ()
Fact *gstDebugLevel READ gstDebugLevel CONSTANT Fact * gstDebugLevel ()
Fact *followTarget READ followTarget CONSTANT Fact * followTarget ()
Fact *qLocaleLanguage READ qLocaleLanguage CONSTANT Fact * qLocaleLanguage ()
Fact *disableAllPersistence READ disableAllPersistence CONSTANT Fact * disableAllPersistence ()
Fact *firstRunPromptIdsShown READ firstRunPromptIdsShown CONSTANT Fact * firstRunPromptIdsShown ()
QString missionSavePath READ missionSavePath NOTIFY savePathsChanged (QString parameterSavePath READ parameterSavePath NOTIFY savePathsChanged) 1(QString telemetrySavePath READ telemetrySavePath NOTIFY savePathsChanged) 1(QString logSavePath READ logSavePath NOTIFY savePathsChanged) 1(QString videoSavePath READ videoSavePath NOTIFY savePathsChanged) 1(QString photoSavePath READ photoSavePath NOTIFY savePathsChanged) 1(QString crashSavePath READ crashSavePath NOTIFY savePathsChanged) 1(QString mavlinkActionsSavePath READ mavlinkActionsSavePath NOTIFY savePathsChanged) 1(QString settingsSavePath READ settingsSavePath NOTIFY savePathsChanged) 1(QString planFileExtension MEMBER planFileExtension CONSTANT) 1(QString waypointsFileExtension MEMBER waypointsFileExtension CONSTANT) 1(QString parameterFileExtension MEMBER parameterFileExtension CONSTANT) 1(QString telemetryFileExtension MEMBER telemetryFileExtension CONSTANT) 1(QString kmlFileExtension MEMBER kmlFileExtension CONSTANT) 1(QString shpFileExtension MEMBER shpFileExtension CONSTANT) 1(QString logFileExtension MEMBER logFileExtension CONSTANT) 1(QString tilesetFileExtension MEMBER tilesetFileExtension CONSTANT) 1(QString settingsFileExtension MEMBER settingsFileExtension CONSTANT) QString missionSavePath()
QString parameterSavePath ()
QString telemetrySavePath ()
QString logSavePath ()
QString videoSavePath ()
QString photoSavePath ()
QString crashSavePath ()
QString mavlinkActionsSavePath ()
QString settingsSavePath ()
void firstRunPromptIdsMarkIdAsShown (int id)
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Member Functions
static QList< int > firstRunPromptsIdsVariantToList (const QVariant &firstRunPromptIds)
static QVariant firstRunPromptsIdsListToVariant (const QList< int > &rgIds)
Static Public Attributes
static const char * name = "App"
static const char * settingsGroup = ""
static const char * offlineEditingFirmwareClassName = "offlineEditingFirmwareClass"
static const char * offlineEditingVehicleClassName = "offlineEditingVehicleClass"
static const char * offlineEditingCruiseSpeedName = "offlineEditingCruiseSpeed"
static const char * offlineEditingHoverSpeedName = "offlineEditingHoverSpeed"
static const char * offlineEditingAscentSpeedName = "offlineEditingAscentSpeed"
static const char * offlineEditingDescentSpeedName = "offlineEditingDescentSpeed"
static const char * batteryPercentRemainingAnnounceName = "batteryPercentRemainingAnnounce"
static const char * defaultMissionItemAltitudeName = "defaultMissionItemAltitude"
static const char * audioMutedName = "audioMuted"
static const char * virtualJoystickName = "virtualJoystick"
static const char * virtualJoystickAutoCenterThrottleName = "virtualJoystickAutoCenterThrottle"
static const char * virtualJoystickLeftHandedModeName = "virtualJoystickLeftHandedMode"
static const char * appFontPointSizeName = "appFontPointSize"
static const char * indoorPaletteName = "indoorPalette"
static const char * savePathName = "savePath"
static const char * androidDontSaveToSDCardName = "androidDontSaveToSDCard"
static const char * useChecklistName = "useChecklist"
static const char * enforceChecklistName = "enforceChecklist"
static const char * enableMultiVehiclePanelName = "enableMultiVehiclePanel"
static const char * tiandituTokenName = "tiandituToken"
static const char * mapboxTokenName = "mapboxToken"
static const char * mapboxAccountName = "mapboxAccount"
static const char * mapboxStyleName = "mapboxStyle"
static const char * esriTokenName = "esriToken"
static const char * customURLName = "customURL"
static const char * vworldTokenName = "vworldToken"
static const char * openaipTokenName = "openaipToken"
static const char * gstDebugLevelName = "gstDebugLevel"
static const char * followTargetName = "followTarget"
static const char * qLocaleLanguageName = "qLocaleLanguage"
static const char * disableAllPersistenceName = "disableAllPersistence"
static const char * firstRunPromptIdsShownName = "firstRunPromptIdsShown"
static constexpr const char * parameterFileExtension = "params"
static constexpr const char * planFileExtension = "plan"
static constexpr const char * waypointsFileExtension = "waypoints"
static constexpr const char * telemetryFileExtension = "tlog"
static constexpr const char * kmlFileExtension = "kml"
static constexpr const char * shpFileExtension = "shp"
static constexpr const char * logFileExtension = "ulg"
static constexpr const char * tilesetFileExtension = "qgctiledb"
static constexpr const char * settingsFileExtension = "settings"
static constexpr const char * parameterDirectory = QT_TRANSLATE_NOOP("AppSettings", "Parameters")
static constexpr const char * telemetryDirectory = QT_TRANSLATE_NOOP("AppSettings", "Telemetry")
static constexpr const char * missionDirectory = QT_TRANSLATE_NOOP("AppSettings", "Missions")
static constexpr const char * logDirectory = QT_TRANSLATE_NOOP("AppSettings", "Logs")
static constexpr const char * videoDirectory = QT_TRANSLATE_NOOP("AppSettings", "Video")
static constexpr const char * photoDirectory = QT_TRANSLATE_NOOP("AppSettings", "Photo")
static constexpr const char * crashDirectory = QT_TRANSLATE_NOOP("AppSettings", "CrashLogs")
static constexpr const char * mavlinkActionsDirectory = QT_TRANSLATE_NOOP("AppSettings", "MavlinkActions")
static constexpr const char * settingsDirectory = QT_TRANSLATE_NOOP("AppSettings", "Settings")
Friends
class QGCApplication
Additional Inherited Members
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Application Settings.
Definition at line 8 of file AppSettings.h.
Constructor & Destructor Documentation
AppSettings()
AppSettings::AppSettings (QObject * parent = nullptr)
Definition at line 56 of file AppSettings.cc.
References QGCPalette::Dark, AndroidInterface::getSDCardPath(), QGCPalette::Light, qgcApp, Fact::rawValueChanged(), savePathsChanged(), and QGCPalette::setGlobalTheme().
Member Function Documentation
androidDontSaveToSDCard()
Fact * AppSettings::androidDontSaveToSDCard ()
Definition at line 124 of file AppSettings.cc.
Referenced by AndroidInterface::jniStoragePermissionsResult().
appFontPointSize()
Fact * AppSettings::appFontPointSize ()
Definition at line 122 of file AppSettings.cc.
audioMuted()
Fact * AppSettings::audioMuted ()
Definition at line 118 of file AppSettings.cc.
batteryPercentRemainingAnnounce()
Fact * AppSettings::batteryPercentRemainingAnnounce ()
Definition at line 116 of file AppSettings.cc.
crashSavePath()
QString AppSettings::crashSavePath (void)
Definition at line 266 of file AppSettings.cc.
References crashDirectory.
customURL()
Fact * AppSettings::customURL ()
Definition at line 133 of file AppSettings.cc.
defaultMissionItemAltitude()
Fact * AppSettings::defaultMissionItemAltitude ()
Definition at line 117 of file AppSettings.cc.
Referenced by MissionController::applyDefaultMissionAltitude().
disableAllPersistence()
Fact * AppSettings::disableAllPersistence ()
Definition at line 138 of file AppSettings.cc.
Referenced by QGeoFileTileCacheQGC::cacheTile().
enableMultiVehiclePanel()
Fact * AppSettings::enableMultiVehiclePanel ()
Definition at line 127 of file AppSettings.cc.
enforceChecklist()
Fact * AppSettings::enforceChecklist ()
Definition at line 126 of file AppSettings.cc.
esriToken()
Fact * AppSettings::esriToken ()
Definition at line 132 of file AppSettings.cc.
Referenced by EsriMapProvider::getToken().
firstRunPromptIdsMarkIdAsShown()
void AppSettings::firstRunPromptIdsMarkIdAsShown (int id)
Definition at line 302 of file AppSettings.cc.
References firstRunPromptIdsShown(), firstRunPromptsIdsListToVariant(), and firstRunPromptsIdsVariantToList().
firstRunPromptIdsShown()
Fact * AppSettings::firstRunPromptIdsShown ()
Definition at line 139 of file AppSettings.cc.
Referenced by firstRunPromptIdsMarkIdAsShown().
firstRunPromptsIdsListToVariant()
QVariant AppSettings::firstRunPromptsIdsListToVariant (const QList< int > & rgIds) static
Definition at line 293 of file AppSettings.cc.
Referenced by firstRunPromptIdsMarkIdAsShown().
firstRunPromptsIdsVariantToList()
QList< int > AppSettings::firstRunPromptsIdsVariantToList (const QVariant & firstRunPromptIds) static
Definition at line 281 of file AppSettings.cc.
Referenced by firstRunPromptIdsMarkIdAsShown().
followTarget()
Fact * AppSettings::followTarget ()
Definition at line 137 of file AppSettings.cc.
Referenced by FollowMe::init().
gstDebugLevel()
Fact * AppSettings::gstDebugLevel ()
Definition at line 136 of file AppSettings.cc.
indoorPalette()
Fact * AppSettings::indoorPalette ()
Definition at line 141 of file AppSettings.cc.
References Fact::rawValueChanged().
logSavePath()
QString AppSettings::logSavePath (void)
Definition at line 251 of file AppSettings.cc.
References logDirectory.
Referenced by LogDownloadController::download().
mapboxAccount()
Fact * AppSettings::mapboxAccount ()
Definition at line 130 of file AppSettings.cc.
mapboxStyle()
Fact * AppSettings::mapboxStyle ()
Definition at line 131 of file AppSettings.cc.
mapboxToken()
Fact * AppSettings::mapboxToken ()
Definition at line 129 of file AppSettings.cc.
mavlinkActionsSavePath()
QString AppSettings::mavlinkActionsSavePath (void)
Definition at line 271 of file AppSettings.cc.
References mavlinkActionsDirectory.
offlineEditingAscentSpeed()
Fact * AppSettings::offlineEditingAscentSpeed ()
Definition at line 114 of file AppSettings.cc.
offlineEditingCruiseSpeed()
Fact * AppSettings::offlineEditingCruiseSpeed ()
Definition at line 112 of file AppSettings.cc.
offlineEditingDescentSpeed()
Fact * AppSettings::offlineEditingDescentSpeed ()
Definition at line 115 of file AppSettings.cc.
offlineEditingFirmwareClass()
Fact * AppSettings::offlineEditingFirmwareClass ()
Definition at line 110 of file AppSettings.cc.
offlineEditingHoverSpeed()
Fact * AppSettings::offlineEditingHoverSpeed ()
Definition at line 113 of file AppSettings.cc.
offlineEditingVehicleClass()
Fact * AppSettings::offlineEditingVehicleClass ()
Definition at line 111 of file AppSettings.cc.
openaipToken()
Fact * AppSettings::openaipToken ()
Definition at line 135 of file AppSettings.cc.
parameterSavePath()
QString AppSettings::parameterSavePath (void)
Definition at line 241 of file AppSettings.cc.
References parameterDirectory.
photoSavePath()
QString AppSettings::photoSavePath (void)
Definition at line 261 of file AppSettings.cc.
References photoDirectory.
qLocaleLanguage()
Fact * AppSettings::qLocaleLanguage ()
Definition at line 150 of file AppSettings.cc.
References Fact::rawValueChanged(), and FactMetaData::setEnumInfo().
savePath()
Fact * AppSettings::savePath ()
Definition at line 123 of file AppSettings.cc.
Referenced by QGCFileDialogController::fullFolderPathToShortMobilePath(), VehicleCameraControl::handleCameraCaptureStatus(), and AndroidInterface::jniStoragePermissionsResult().
savePathsChanged [1/2]
void AppSettings::savePathsChanged () signal
Referenced by AppSettings().
savePathsChanged() [2/2]
QString missionSavePath READ missionSavePath NOTIFY AppSettings::savePathsChanged (QString parameterSavePath READ parameterSavePath NOTIFY savePathsChanged)
settingsSavePath()
QString AppSettings::settingsSavePath (void)
Definition at line 276 of file AppSettings.cc.
References settingsDirectory.
telemetrySavePath()
QString AppSettings::telemetrySavePath (void)
Definition at line 246 of file AppSettings.cc.
References telemetryDirectory.
tiandituToken()
Fact * AppSettings::tiandituToken ()
Definition at line 128 of file AppSettings.cc.
useChecklist()
Fact * AppSettings::useChecklist ()
Definition at line 125 of file AppSettings.cc.
videoSavePath()
QString AppSettings::videoSavePath (void)
Definition at line 256 of file AppSettings.cc.
References videoDirectory.
virtualJoystick()
Fact * AppSettings::virtualJoystick ()
Definition at line 119 of file AppSettings.cc.
virtualJoystickAutoCenterThrottle()
Fact * AppSettings::virtualJoystickAutoCenterThrottle ()
Definition at line 120 of file AppSettings.cc.
virtualJoystickLeftHandedMode()
Fact * AppSettings::virtualJoystickLeftHandedMode ()
Definition at line 121 of file AppSettings.cc.
vworldToken()
Fact * AppSettings::vworldToken ()
Definition at line 134 of file AppSettings.cc.
Friends And Related Symbol Documentation
QGCApplication
friend class QGCApplication friend
Definition at line 131 of file AppSettings.h.
Member Data Documentation
androidDontSaveToSDCardName
const char * AppSettings::androidDontSaveToSDCardName = "androidDontSaveToSDCard" static
Definition at line 33 of file AppSettings.h.
appFontPointSizeName
const char * AppSettings::appFontPointSizeName = "appFontPointSize" static
Definition at line 30 of file AppSettings.h.
audioMutedName
const char * AppSettings::audioMutedName = "audioMuted" static
Definition at line 26 of file AppSettings.h.
batteryPercentRemainingAnnounceName
const char * AppSettings::batteryPercentRemainingAnnounceName = "batteryPercentRemainingAnnounce" static
Definition at line 24 of file AppSettings.h.
crashDirectory
constexpr const char* AppSettings::crashDirectory = QT_TRANSLATE_NOOP("AppSettings", "CrashLogs") static constexpr
Definition at line 105 of file AppSettings.h.
Referenced by crashSavePath().
customURLName
const char * AppSettings::customURLName = "customURL" static
Definition at line 42 of file AppSettings.h.
defaultMissionItemAltitudeName
const char * AppSettings::defaultMissionItemAltitudeName = "defaultMissionItemAltitude" static
Definition at line 25 of file AppSettings.h.
disableAllPersistenceName
const char * AppSettings::disableAllPersistenceName = "disableAllPersistence" static
Definition at line 48 of file AppSettings.h.
enableMultiVehiclePanelName
const char * AppSettings::enableMultiVehiclePanelName = "enableMultiVehiclePanel" static
Definition at line 36 of file AppSettings.h.
enforceChecklistName
const char * AppSettings::enforceChecklistName = "enforceChecklist" static
Definition at line 35 of file AppSettings.h.
esriTokenName
const char * AppSettings::esriTokenName = "esriToken" static
Definition at line 41 of file AppSettings.h.
firstRunPromptIdsShownName
const char * AppSettings::firstRunPromptIdsShownName = "firstRunPromptIdsShown" static
Definition at line 49 of file AppSettings.h.
followTargetName
const char * AppSettings::followTargetName = "followTarget" static
Definition at line 46 of file AppSettings.h.
gstDebugLevelName
const char * AppSettings::gstDebugLevelName = "gstDebugLevel" static
Definition at line 45 of file AppSettings.h.
Referenced by GStreamer::initialize().
indoorPaletteName
const char * AppSettings::indoorPaletteName = "indoorPalette" static
Definition at line 31 of file AppSettings.h.
kmlFileExtension
constexpr const char* AppSettings::kmlFileExtension = "kml" static constexpr
Definition at line 92 of file AppSettings.h.
Referenced by PlanMasterController::kmlFileExtension().
logDirectory
constexpr const char* AppSettings::logDirectory = QT_TRANSLATE_NOOP("AppSettings", "Logs") static constexpr
Definition at line 102 of file AppSettings.h.
Referenced by logSavePath().
logFileExtension
constexpr const char* AppSettings::logFileExtension = "ulg" static constexpr
Definition at line 94 of file AppSettings.h.
mapboxAccountName
const char * AppSettings::mapboxAccountName = "mapboxAccount" static
Definition at line 39 of file AppSettings.h.
mapboxStyleName
const char * AppSettings::mapboxStyleName = "mapboxStyle" static
Definition at line 40 of file AppSettings.h.
mapboxTokenName
const char * AppSettings::mapboxTokenName = "mapboxToken" static
Definition at line 38 of file AppSettings.h.
mavlinkActionsDirectory
constexpr const char* AppSettings::mavlinkActionsDirectory = QT_TRANSLATE_NOOP("AppSettings", "MavlinkActions") static constexpr
Definition at line 106 of file AppSettings.h.
Referenced by mavlinkActionsSavePath().
missionDirectory
constexpr const char* AppSettings::missionDirectory = QT_TRANSLATE_NOOP("AppSettings", "Missions") static constexpr
Definition at line 101 of file AppSettings.h.
name
const char * AppSettings::name = "App" static
Definition at line 16 of file AppSettings.h.
offlineEditingAscentSpeedName
const char * AppSettings::offlineEditingAscentSpeedName = "offlineEditingAscentSpeed" static
Definition at line 22 of file AppSettings.h.
offlineEditingCruiseSpeedName
const char * AppSettings::offlineEditingCruiseSpeedName = "offlineEditingCruiseSpeed" static
Definition at line 20 of file AppSettings.h.
offlineEditingDescentSpeedName
const char * AppSettings::offlineEditingDescentSpeedName = "offlineEditingDescentSpeed" static
Definition at line 23 of file AppSettings.h.
offlineEditingFirmwareClassName
const char * AppSettings::offlineEditingFirmwareClassName = "offlineEditingFirmwareClass" static
Definition at line 18 of file AppSettings.h.
offlineEditingHoverSpeedName
const char * AppSettings::offlineEditingHoverSpeedName = "offlineEditingHoverSpeed" static
Definition at line 21 of file AppSettings.h.
offlineEditingVehicleClassName
const char * AppSettings::offlineEditingVehicleClassName = "offlineEditingVehicleClass" static
Definition at line 19 of file AppSettings.h.
openaipTokenName
const char * AppSettings::openaipTokenName = "openaipToken" static
Definition at line 44 of file AppSettings.h.
parameterDirectory
constexpr const char* AppSettings::parameterDirectory = QT_TRANSLATE_NOOP("AppSettings", "Parameters") static constexpr
Definition at line 99 of file AppSettings.h.
Referenced by parameterSavePath().
parameterFileExtension
constexpr const char* AppSettings::parameterFileExtension = "params" static constexpr
Definition at line 88 of file AppSettings.h.
Referenced by QGroundControlQmlGlobal::parameterFileExtension().
photoDirectory
constexpr const char* AppSettings::photoDirectory = QT_TRANSLATE_NOOP("AppSettings", "Photo") static constexpr
Definition at line 104 of file AppSettings.h.
Referenced by photoSavePath().
planFileExtension
constexpr const char* AppSettings::planFileExtension = "plan" static constexpr
Definition at line 89 of file AppSettings.h.
Referenced by PlanMasterController::fileExtension(), PlanMasterController::loadFromFile(), and PlanMasterController::loadNameFilters().
qLocaleLanguageName
const char * AppSettings::qLocaleLanguageName = "qLocaleLanguage" static
Definition at line 47 of file AppSettings.h.
savePathName
const char * AppSettings::savePathName = "savePath" static
Definition at line 32 of file AppSettings.h.
settingsDirectory
constexpr const char* AppSettings::settingsDirectory = QT_TRANSLATE_NOOP("AppSettings", "Settings") static constexpr
Definition at line 107 of file AppSettings.h.
Referenced by settingsSavePath().
settingsFileExtension
constexpr const char* AppSettings::settingsFileExtension = "settings" static constexpr
Definition at line 96 of file AppSettings.h.
settingsGroup
const char * AppSettings::settingsGroup = "" static
Definition at line 16 of file AppSettings.h.
shpFileExtension
constexpr const char* AppSettings::shpFileExtension = "shp" static constexpr
Definition at line 93 of file AppSettings.h.
telemetryDirectory
constexpr const char* AppSettings::telemetryDirectory = QT_TRANSLATE_NOOP("AppSettings", "Telemetry") static constexpr
Definition at line 100 of file AppSettings.h.
Referenced by telemetrySavePath().
telemetryFileExtension
constexpr const char* AppSettings::telemetryFileExtension = "tlog" static constexpr
Definition at line 91 of file AppSettings.h.
Referenced by QGroundControlQmlGlobal::telemetryFileExtension().
tiandituTokenName
const char * AppSettings::tiandituTokenName = "tiandituToken" static
Definition at line 37 of file AppSettings.h.
tilesetFileExtension
constexpr const char* AppSettings::tilesetFileExtension = "qgctiledb" static constexpr
Definition at line 95 of file AppSettings.h.
useChecklistName
const char * AppSettings::useChecklistName = "useChecklist" static
Definition at line 34 of file AppSettings.h.
videoDirectory
constexpr const char* AppSettings::videoDirectory = QT_TRANSLATE_NOOP("AppSettings", "Video") static constexpr
Definition at line 103 of file AppSettings.h.
Referenced by videoSavePath().
virtualJoystickAutoCenterThrottleName
const char * AppSettings::virtualJoystickAutoCenterThrottleName = "virtualJoystickAutoCenterThrottle" static
Definition at line 28 of file AppSettings.h.
virtualJoystickLeftHandedModeName
const char * AppSettings::virtualJoystickLeftHandedModeName = "virtualJoystickLeftHandedMode" static
Definition at line 29 of file AppSettings.h.
virtualJoystickName
const char * AppSettings::virtualJoystickName = "virtualJoystick" static
Definition at line 27 of file AppSettings.h.
vworldTokenName
const char * AppSettings::vworldTokenName = "vworldToken" static
Definition at line 43 of file AppSettings.h.
waypointsFileExtension
constexpr const char* AppSettings::waypointsFileExtension = "waypoints" static constexpr
Definition at line 90 of file AppSettings.h.
Referenced by PlanMasterController::loadFromFile(), and PlanMasterController::loadNameFilters().
The documentation for this class was generated from the following files:
src/Settings/AppSettings.h
src/Settings/AppSettings.cc