QGroundControl: TransactionGuard Class Reference
TransactionGuard Class Reference
Public Member Functions
TransactionGuard (QSqlDatabase db)
~TransactionGuard ()
TransactionGuard (const TransactionGuard &)=delete
TransactionGuard & operator= (const TransactionGuard &)=delete
bool begin ()
bool commit ()
Detailed Description
Definition at line 22 of file QGCTileCacheDatabase.cpp.
Constructor & Destructor Documentation
TransactionGuard() [1/2]
TransactionGuard::TransactionGuard (QSqlDatabase db) inline explicit
Definition at line 24 of file QGCTileCacheDatabase.cpp.
~TransactionGuard()
TransactionGuard::~TransactionGuard () inline
Definition at line 25 of file QGCTileCacheDatabase.cpp.
TransactionGuard() [2/2]
TransactionGuard::TransactionGuard (const TransactionGuard &) delete
Member Function Documentation
begin()
bool TransactionGuard::begin () inline
Definition at line 28 of file QGCTileCacheDatabase.cpp.
Referenced by QGCTileCacheDatabase::createTileSet(), QGCTileCacheDatabase::deleteBingNoTileTiles(), QGCTileCacheDatabase::deleteTileSet(), QGCTileCacheDatabase::exportSets(), QGCTileCacheDatabase::getTileDownloadList(), QGCTileCacheDatabase::importSetsMerge(), QGCTileCacheDatabase::pruneCache(), QGCTileCacheDatabase::resetDatabase(), and QGCTileCacheDatabase::saveTile().
commit()
bool TransactionGuard::commit () inline
Definition at line 29 of file QGCTileCacheDatabase.cpp.
Referenced by QGCTileCacheDatabase::createTileSet(), QGCTileCacheDatabase::deleteBingNoTileTiles(), QGCTileCacheDatabase::deleteTileSet(), QGCTileCacheDatabase::exportSets(), QGCTileCacheDatabase::getTileDownloadList(), QGCTileCacheDatabase::importSetsMerge(), QGCTileCacheDatabase::pruneCache(), QGCTileCacheDatabase::resetDatabase(), and QGCTileCacheDatabase::saveTile().
operator=()
TransactionGuard & TransactionGuard::operator= (const TransactionGuard &) delete
The documentation for this class was generated from the following file:
src/QtLocationPlugin/QGCTileCacheDatabase.cpp