QGroundControl: GstVideoReceiver Class Reference
GstVideoReceiver Class Reference
#include <GstVideoReceiver.h>
Public Slots
void start (uint32_t timeout) override
void stop () override
void startDecoding (void *sink) override
void stopDecoding () override
void startRecording (const QString &videoFile, FILE_FORMAT format) override
void stopRecording () override
void takeScreenshot (const QString &imageFile) override
Public Slots inherited from VideoReceiver
virtual void start (uint32_t timeout)=0
virtual void stop ()=0
virtual void startDecoding (void *sink)=0
virtual void stopDecoding ()=0
virtual void startRecording (const QString &videoFile, FILE_FORMAT format)=0
virtual void stopRecording ()=0
virtual void takeScreenshot (const QString &imageFile)=0
Public Member Functions
GstVideoReceiver (QObject *parent=nullptr)
~GstVideoReceiver ()
Public Member Functions inherited from VideoReceiver
VideoReceiver (QObject *parent=nullptr)
bool isThermal () const
void * sink ()
QQuickItem * widget ()
QString name () const
QString uri () const
bool started () const
bool lowLatency () const
QGCVideoStreamInfo * videoStreamInfo ()
QString recordingOutput () const
virtual void setSink (void *sink)
virtual void setWidget (QQuickItem *widget)
void setName (const QString &name)
void setUri (const QString &uri)
void setStarted (bool started)
void setLowLatency (bool lowLatency)
void setVideoStreamInfo (QGCVideoStreamInfo *videoStreamInfo)
Additional Inherited Members
Public Types inherited from VideoReceiver
enum FILE_FORMAT {
FILE_FORMAT_MIN = 0 , FILE_FORMAT_MKV = FILE_FORMAT_MIN , FILE_FORMAT_MOV , FILE_FORMAT_MP4 ,
FILE_FORMAT_MAX = FILE_FORMAT_MP4
}
enum STATUS {
STATUS_MIN = 0 , STATUS_OK = STATUS_MIN , STATUS_FAIL , STATUS_INVALID_STATE ,
STATUS_INVALID_URL , STATUS_NOT_IMPLEMENTED , STATUS_MAX = STATUS_NOT_IMPLEMENTED
}
Signals inherited from VideoReceiver
void timeout ()
void streamingChanged (bool active)
void decodingChanged (bool active)
void recordingChanged (bool active)
void recordingStarted (const QString &filename)
void videoSizeChanged (QSize size)
void sinkChanged (void *sink)
void nameChanged (const QString &name)
void uriChanged (const QString &uri)
void startedChanged (bool started)
void lowLatencyChanged (bool lowLatency)
void videoStreamInfoChanged ()
void widgetChanged (QQuickItem *widget)
void onStartComplete (STATUS status)
void onStopComplete (STATUS status)
void onStartDecodingComplete (STATUS status)
void onStopDecodingComplete (STATUS status)
void onStartRecordingComplete (STATUS status)
void onStopRecordingComplete (STATUS status)
void onTakeScreenshotComplete (STATUS status)
Static Public Member Functions inherited from VideoReceiver
static bool isValidFileFormat (FILE_FORMAT format)
static bool isValidStatus (STATUS status)
Protected Attributes inherited from VideoReceiver
void * _sink = nullptr
QQuickItem * _widget = nullptr
QGCVideoStreamInfo * _videoStreamInfo = nullptr
QString _name
QString _uri
bool _started = false
bool _decoding = false
bool _recording = false
bool _streaming = false
bool _lowLatency = false
bool _resetVideoSink = false
bool _endOfStream = false
bool _removingDecoder = false
bool _removingRecorder = false
int _buffer = 0
qint64 _lastSourceFrameTime = 0
qint64 _lastVideoFrameTime = 0
QTimer _watchdogTimer
uint32_t _signalDepth = 0
uint32_t _timeout = 0
QString _recordingOutput
Detailed Description
Definition at line 46 of file GstVideoReceiver.h.
Constructor & Destructor Documentation
GstVideoReceiver()
GstVideoReceiver::GstVideoReceiver (QObject * parent = nullptr) explicit
Definition at line 23 of file GstVideoReceiver.cc.
References VideoReceiver::start().
~GstVideoReceiver()
GstVideoReceiver::~GstVideoReceiver ()
Definition at line 34 of file GstVideoReceiver.cc.
References GstVideoWorker::shutdown(), and stop().
Member Function Documentation
start
void GstVideoReceiver::start (uint32_t timeout) override slot
Definition at line 42 of file GstVideoReceiver.cc.
References VideoReceiver::_buffer, VideoReceiver::_endOfStream, VideoReceiver::_lastSourceFrameTime, VideoReceiver::_timeout, VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::lowLatency(), VideoReceiver::onStartComplete(), start(), VideoReceiver::STATUS_FAIL, VideoReceiver::STATUS_INVALID_STATE, VideoReceiver::STATUS_INVALID_URL, VideoReceiver::STATUS_OK, and VideoReceiver::timeout().
Referenced by start().
startDecoding
void GstVideoReceiver::startDecoding (void * sink) override slot
Definition at line 316 of file GstVideoReceiver.cc.
References VideoReceiver::_decoding, VideoReceiver::_lastVideoFrameTime, VideoReceiver::_removingDecoder, VideoReceiver::_resetVideoSink, VideoReceiver::_streaming, VideoReceiver::_uri, VideoReceiver::_widget, GstVideoWorker::dispatch(), VideoReceiver::onStartDecodingComplete(), VideoReceiver::sink(), startDecoding(), VideoReceiver::STATUS_FAIL, VideoReceiver::STATUS_INVALID_STATE, and VideoReceiver::STATUS_OK.
Referenced by startDecoding().
startRecording
void GstVideoReceiver::startRecording (const QString & videoFile, FILE_FORMAT format) override slot
Definition at line 416 of file GstVideoReceiver.cc.
References VideoReceiver::_recording, VideoReceiver::_recordingOutput, VideoReceiver::_removingRecorder, VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::onStartRecordingComplete(), VideoReceiver::recordingChanged(), startRecording(), VideoReceiver::STATUS_FAIL, VideoReceiver::STATUS_INVALID_STATE, and VideoReceiver::STATUS_OK.
Referenced by startRecording().
stop
void GstVideoReceiver::stop () override slot
Definition at line 218 of file GstVideoReceiver.cc.
References VideoReceiver::_lastSourceFrameTime, VideoReceiver::_streaming, VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::onStopComplete(), VideoReceiver::STATUS_OK, stop(), and VideoReceiver::streamingChanged().
Referenced by stop(), and ~GstVideoReceiver().
stopDecoding
void GstVideoReceiver::stopDecoding () override slot
Definition at line 388 of file GstVideoReceiver.cc.
References VideoReceiver::_decoding, VideoReceiver::_removingDecoder, VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::onStopDecodingComplete(), VideoReceiver::STATUS_FAIL, VideoReceiver::STATUS_INVALID_STATE, VideoReceiver::STATUS_OK, and stopDecoding().
Referenced by stopDecoding().
stopRecording
void GstVideoReceiver::stopRecording () override slot
Definition at line 489 of file GstVideoReceiver.cc.
References VideoReceiver::_recording, VideoReceiver::_removingRecorder, VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::onStopRecordingComplete(), VideoReceiver::STATUS_FAIL, VideoReceiver::STATUS_INVALID_STATE, VideoReceiver::STATUS_OK, and stopRecording().
Referenced by stopRecording().
takeScreenshot
void GstVideoReceiver::takeScreenshot (const QString & imageFile) override slot
Definition at line 517 of file GstVideoReceiver.cc.
References VideoReceiver::_uri, GstVideoWorker::dispatch(), VideoReceiver::onTakeScreenshotComplete(), VideoReceiver::STATUS_NOT_IMPLEMENTED, and takeScreenshot().
Referenced by takeScreenshot().
The documentation for this class was generated from the following files:
src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.h
src/VideoManager/VideoReceiver/GStreamer/GstVideoReceiver.cc