QGroundControl: QGeoFileTileCacheQGC Class Reference
QGeoFileTileCacheQGC Class Reference
#include <QGeoFileTileCacheQGC.h>
Public Member Functions
QGeoFileTileCacheQGC (const QVariantMap &parameters, QObject *parent=nullptr)
~QGeoFileTileCacheQGC ()
Static Public Member Functions
static quint32 getMaxDiskCacheSetting ()
static void cacheTile (const QString &type, int x, int y, int z, const QByteArray &image, const QString &format, qulonglong set=UINT64_MAX)
static void cacheTile (const QString &type, const QString &hash, const QByteArray &image, const QString &format, qulonglong set=UINT64_MAX)
static QGCFetchTileTask * createFetchTileTask (const QString &type, int x, int y, int z)
static QString getDatabaseFilePath ()
static QString getCachePath ()
Detailed Description
Definition at line 12 of file QGeoFileTileCacheQGC.h.
Constructor & Destructor Documentation
QGeoFileTileCacheQGC()
QGeoFileTileCacheQGC::QGeoFileTileCacheQGC (const QVariantMap & parameters, QObject * parent = nullptr) explicit
Definition at line 23 of file QGeoFileTileCacheQGC.cpp.
~QGeoFileTileCacheQGC()
QGeoFileTileCacheQGC::~QGeoFileTileCacheQGC ()
Definition at line 44 of file QGeoFileTileCacheQGC.cpp.
Member Function Documentation
cacheTile() [1/2]
void QGeoFileTileCacheQGC::cacheTile (const QString & type, const QString & hash, const QByteArray & image, const QString & format, qulonglong set = UINT64_MAX) static
Definition at line 94 of file QGeoFileTileCacheQGC.cpp.
References AppSettings::disableAllPersistence(), and getQGCMapEngine().
cacheTile() [2/2]
void QGeoFileTileCacheQGC::cacheTile (const QString & type, int x, int y, int z, const QByteArray & image, const QString & format, qulonglong set = UINT64_MAX) static
Definition at line 88 of file QGeoFileTileCacheQGC.cpp.
References cacheTile(), and UrlFactory::getTileHash().
Referenced by cacheTile().
createFetchTileTask()
QGCFetchTileTask * QGeoFileTileCacheQGC::createFetchTileTask (const QString & type, int x, int y, int z) static
Definition at line 106 of file QGeoFileTileCacheQGC.cpp.
References UrlFactory::getTileHash().
Referenced by QGeoTiledMapReplyQGC::init().
getCachePath()
static QString QGeoFileTileCacheQGC::getCachePath () inline static
Definition at line 25 of file QGeoFileTileCacheQGC.h.
getDatabaseFilePath()
static QString QGeoFileTileCacheQGC::getDatabaseFilePath () inline static
Definition at line 24 of file QGeoFileTileCacheQGC.h.
Referenced by QGeoTiledMappingManagerEngineQGC::QGeoTiledMappingManagerEngineQGC().
getMaxDiskCacheSetting()
quint32 QGeoFileTileCacheQGC::getMaxDiskCacheSetting () static
Definition at line 83 of file QGeoFileTileCacheQGC.cpp.
References MapsSettings::maxCacheDiskSize().
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGeoFileTileCacheQGC.h
src/QtLocationPlugin/QGeoFileTileCacheQGC.cpp