QGroundControl: QGCMapEngine Class Reference
QGCMapEngine Class Reference
#include <QGCMapEngine.h>
Signals
void updateTotals (quint32 totaltiles, quint64 totalsize, quint32 defaulttiles, quint64 defaultsize)
Public Member Functions
QGCMapEngine (QObject *parent=nullptr)
~QGCMapEngine ()
void init (const QString &databasePath)
bool addTask (QGCMapTask *task)
Static Public Member Functions
static QGCMapEngine * instance ()
Detailed Description
Definition at line 9 of file QGCMapEngine.h.
Constructor & Destructor Documentation
QGCMapEngine()
QGCMapEngine::QGCMapEngine (QObject * parent = nullptr) explicit
Definition at line 23 of file QGCMapEngine.cpp.
~QGCMapEngine()
QGCMapEngine::~QGCMapEngine ()
Definition at line 38 of file QGCMapEngine.cpp.
References QGCCacheWorker::stop().
Member Function Documentation
addTask()
bool QGCMapEngine::addTask (QGCMapTask * task)
Definition at line 73 of file QGCMapEngine.cpp.
References QGCCacheWorker::enqueueTask().
Referenced by QGeoTiledMapReplyQGC::init(), and init().
init()
void QGCMapEngine::init (const QString & databasePath)
Definition at line 54 of file QGCMapEngine.cpp.
References addTask(), QGCCacheWorker::setDatabaseFile(), QGCMapTask::taskInit, and QGCCacheWorker::updateTotals().
Referenced by QGeoTiledMappingManagerEngineQGC::QGeoTiledMappingManagerEngineQGC().
instance()
QGCMapEngine * QGCMapEngine::instance () static
Definition at line 49 of file QGCMapEngine.cpp.
Referenced by getQGCMapEngine().
updateTotals
void QGCMapEngine::updateTotals (quint32 totaltiles, quint64 totalsize, quint32 defaulttiles, quint64 defaultsize) signal
The documentation for this class was generated from the following files:
src/QtLocationPlugin/QGCMapEngine.h
src/QtLocationPlugin/QGCMapEngine.cpp