QGroundControl: PX4ParameterMetaData Class Reference
PX4ParameterMetaData Class Reference
Loads and holds parameter fact meta data for PX4 stack.
#include <PX4ParameterMetaData.h>
Public Member Functions
PX4ParameterMetaData (QObject *parent=nullptr)
void loadParameterFactMetaDataFile (const QString &metaDataFile)
FactMetaData * getMetaDataForFact (const QString &name, MAV_TYPE vehicleType, FactMetaData::ValueType_t type)
Static Public Member Functions
static void getParameterMetaDataVersionInfo (const QString &metaDataFile, int &majorVersion, int &minorVersion)
Detailed Description
Loads and holds parameter fact meta data for PX4 stack.
Definition at line 15 of file PX4ParameterMetaData.h.
Constructor & Destructor Documentation
PX4ParameterMetaData()
PX4ParameterMetaData::PX4ParameterMetaData (QObject * parent = nullptr)
Definition at line 11 of file PX4ParameterMetaData.cc.
Member Function Documentation
getMetaDataForFact()
FactMetaData * PX4ParameterMetaData::getMetaDataForFact (const QString & name, MAV_TYPE vehicleType, FactMetaData::ValueType_t type)
Definition at line 481 of file PX4ParameterMetaData.cc.
Referenced by PX4FirmwarePlugin::_getMetaDataForFact().
getParameterMetaDataVersionInfo()
void PX4ParameterMetaData::getParameterMetaDataVersionInfo (const QString & metaDataFile, int & majorVersion, int & minorVersion) static
Definition at line 494 of file PX4ParameterMetaData.cc.
References errorString.
Referenced by PX4FirmwarePlugin::_getParameterMetaDataVersionInfo().
loadParameterFactMetaDataFile()
void PX4ParameterMetaData::loadParameterFactMetaDataFile (const QString & metaDataFile)
Definition at line 66 of file PX4ParameterMetaData.cc.
References FactMetaData::addBitmaskInfo(), FactMetaData::addEnumInfo(), FactMetaData::convertAndValidateRaw(), FactMetaData::defaultValueAvailable(), errorString, FactMetaData::name(), FactMetaData::rawDefaultValue(), FactMetaData::setCategory(), FactMetaData::setDecimalPlaces(), FactMetaData::setGroup(), FactMetaData::setLongDescription(), FactMetaData::setName(), FactMetaData::setRawDefaultValue(), FactMetaData::setRawIncrement(), FactMetaData::setRawMax(), FactMetaData::setRawMin(), FactMetaData::setRawUnits(), FactMetaData::setReadOnly(), FactMetaData::setShortDescription(), FactMetaData::setVehicleRebootRequired(), FactMetaData::setVolatileValue(), FactMetaData::stringToType(), and FactMetaData::type().
Referenced by PX4FirmwarePlugin::_loadParameterMetaData().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/PX4/PX4ParameterMetaData.h
src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc