QGroundControl: ImageProtocolManager Class Reference
ImageProtocolManager Class Reference
#include <ImageProtocolManager.h>
Public Slots
void mavlinkMessageReceived (const mavlink_message_t &message)
Signals
void imageReady (const QImage &image)
void flowImageIndexChanged (uint32_t index)
Public Member Functions
ImageProtocolManager (QObject *parent=nullptr)
~ImageProtocolManager ()
uint32_t flowImageIndex () const
bool requestImage (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t &message)
void cancelRequest (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t &message)
Detailed Description
Supports the Mavlink image transmission protocol (https://mavlink.io/en/services/image_transmission.html). Mainly used by optical flow cameras.
Definition at line 14 of file ImageProtocolManager.h.
Constructor & Destructor Documentation
ImageProtocolManager()
ImageProtocolManager::ImageProtocolManager (QObject * parent = nullptr)
Definition at line 6 of file ImageProtocolManager.cc.
~ImageProtocolManager()
ImageProtocolManager::~ImageProtocolManager ()
Definition at line 12 of file ImageProtocolManager.cc.
Member Function Documentation
cancelRequest()
void ImageProtocolManager::cancelRequest (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t & message)
Definition at line 35 of file ImageProtocolManager.cc.
flowImageIndex()
uint32_t ImageProtocolManager::flowImageIndex () const inline
Definition at line 22 of file ImageProtocolManager.h.
Referenced by Vehicle::flowImageIndex().
flowImageIndexChanged
void ImageProtocolManager::flowImageIndexChanged (uint32_t index) signal
Referenced by mavlinkMessageReceived().
imageReady
void ImageProtocolManager::imageReady (const QImage & image) signal
Referenced by mavlinkMessageReceived().
mavlinkMessageReceived
void ImageProtocolManager::mavlinkMessageReceived (const mavlink_message_t & message) slot
Definition at line 41 of file ImageProtocolManager.cc.
References flowImageIndexChanged(), and imageReady().
requestImage()
bool ImageProtocolManager::requestImage (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t & message)
Definition at line 17 of file ImageProtocolManager.cc.
The documentation for this class was generated from the following files:
src/MAVLink/ImageProtocolManager.h
src/MAVLink/ImageProtocolManager.cc