QGroundControl: QGCCameraManager Class Reference
QGCCameraManager Class Reference
Camera Manager.
#include <QGCCameraManager.h>
Signals
void camerasChanged ()
void cameraLabelsChanged ()
void currentCameraChanged ()
void streamChanged ()
void currentZoomLevelChanged ()
Protected Slots
void _vehicleReady (bool ready)
void _mavlinkMessageReceived (const mavlink_message_t &message)
void _activeJoystickChanged (Joystick *joystick)
void _stepZoom (int direction)
void _startZoom (int direction)
void _stopZoom ()
void _stepCamera (int direction)
void _stepStream (int direction)
void _checkForLostCameras ()
void _triggerCamera ()
void _startVideoRecording ()
void _stopVideoRecording ()
void _toggleVideoRecording ()
Detailed Description
Camera Manager.
Definition at line 26 of file QGCCameraManager.h.
Member Function Documentation
_activeJoystickChanged
void QGCCameraManager::_activeJoystickChanged (Joystick * joystick) protected slot
Definition at line 611 of file QGCCameraManager.cc.
References _startVideoRecording(), _startZoom(), _stepCamera(), _stepStream(), _stepZoom(), _stopVideoRecording(), _stopZoom(), _toggleVideoRecording(), _triggerCamera(), Joystick::startContinuousZoom(), Joystick::startVideoRecord(), Joystick::stepCamera(), Joystick::stepStream(), Joystick::stepZoom(), Joystick::stopContinuousZoom(), Joystick::stopVideoRecord(), Joystick::toggleVideoRecord(), and Joystick::triggerCamera().
Referenced by _vehicleReady().
_checkForLostCameras
void QGCCameraManager::_checkForLostCameras () protected slot
Definition at line 345 of file QGCCameraManager.cc.
References cameraLabelsChanged(), camerasChanged(), QGCMAVLink::compIdToString(), currentCameraChanged(), QmlObjectListModel::indexOf(), QmlObjectListModel::isEmpty(), QmlObjectListModel::removeAt(), and streamChanged().
_mavlinkMessageReceived
void QGCCameraManager::_mavlinkMessageReceived (const mavlink_message_t & message) protected slot
Definition at line 140 of file QGCCameraManager.cc.
_startVideoRecording
void QGCCameraManager::_startVideoRecording () protected slot
Definition at line 649 of file QGCCameraManager.cc.
References MavlinkCameraControl::startVideoRecording().
Referenced by _activeJoystickChanged().
_startZoom
void QGCCameraManager::_startZoom (int direction) protected slot
Definition at line 685 of file QGCCameraManager.cc.
References MavlinkCameraControl::startZoom().
Referenced by _activeJoystickChanged().
_stepCamera
void QGCCameraManager::_stepCamera (int direction) protected slot
Definition at line 703 of file QGCCameraManager.cc.
References QmlObjectListModel::count().
Referenced by _activeJoystickChanged().
_stepStream
void QGCCameraManager::_stepStream (int direction) protected slot
Definition at line 718 of file QGCCameraManager.cc.
References QmlObjectListModel::count(), MavlinkCameraControl::currentStream(), MavlinkCameraControl::setCurrentStream(), and MavlinkCameraControl::streams().
Referenced by _activeJoystickChanged().
_stepZoom
void QGCCameraManager::_stepZoom (int direction) protected slot
Definition at line 673 of file QGCCameraManager.cc.
References MavlinkCameraControl::stepZoom().
Referenced by _activeJoystickChanged().
_stopVideoRecording
void QGCCameraManager::_stopVideoRecording () protected slot
Definition at line 657 of file QGCCameraManager.cc.
References MavlinkCameraControl::stopVideoRecording().
Referenced by _activeJoystickChanged().
_stopZoom
void QGCCameraManager::_stopZoom () protected slot
Definition at line 694 of file QGCCameraManager.cc.
References MavlinkCameraControl::stopZoom().
Referenced by _activeJoystickChanged().
_toggleVideoRecording
void QGCCameraManager::_toggleVideoRecording () protected slot
Definition at line 665 of file QGCCameraManager.cc.
References MavlinkCameraControl::toggleVideoRecording().
Referenced by _activeJoystickChanged().
_triggerCamera
void QGCCameraManager::_triggerCamera () protected slot
Definition at line 641 of file QGCCameraManager.cc.
References MavlinkCameraControl::takePhoto().
Referenced by _activeJoystickChanged().
_vehicleReady
void QGCCameraManager::_vehicleReady (bool ready) protected slot
Definition at line 125 of file QGCCameraManager.cc.
References _activeJoystickChanged(), and JoystickManager::activeJoystickChanged().
cameraLabelsChanged
void QGCCameraManager::cameraLabelsChanged () signal
Referenced by _checkForLostCameras().
camerasChanged
void QGCCameraManager::camerasChanged () signal
Referenced by _checkForLostCameras().
currentCameraChanged
void QGCCameraManager::currentCameraChanged () signal
Referenced by _checkForLostCameras().
currentZoomLevelChanged
void QGCCameraManager::currentZoomLevelChanged () signal
streamChanged
void QGCCameraManager::streamChanged () signal
Referenced by _checkForLostCameras().
The documentation for this class was generated from the following files:
src/Camera/QGCCameraManager.h
src/Camera/QGCCameraManager.cc