QGroundControl: VehicleObjectAvoidance Class Reference
VehicleObjectAvoidance Class Reference
#include <VehicleObjectAvoidance.h>
Signals
void objectAvoidanceChanged ()
Public Member Functions
VehicleObjectAvoidance (Vehicle *vehicle, QObject *parent=nullptr)
bool available READ available NOTIFY objectAvoidanceChanged (bool enabled READ enabled NOTIFY objectAvoidanceChanged) 1(QList< int > distances READ distances NOTIFY objectAvoidanceChanged) 1(qreal increment READ increment NOTIFY objectAvoidanceChanged) 1(int minDistance READ minDistance NOTIFY objectAvoidanceChanged) 1(int maxDistance READ maxDistance NOTIFY objectAvoidanceChanged) 1(qreal angleOffset READ angleOffset NOTIFY objectAvoidanceChanged) 1(int gridSize READ gridSize NOTIFY objectAvoidanceChanged) 1 void start(int minDistance)
void stop ()
QPointF grid (int i)
qreal distance (int i)
bool available ()
bool enabled ()
QList< int > distances ()
qreal increment () const
int minDistance () const
int maxDistance () const
qreal angleOffset () const
int gridSize ()
void update (mavlink_obstacle_distance_t *message)
Detailed Description
Definition at line 12 of file VehicleObjectAvoidance.h.
Constructor & Destructor Documentation
VehicleObjectAvoidance()
VehicleObjectAvoidance::VehicleObjectAvoidance (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 6 of file VehicleObjectAvoidance.cc.
Member Function Documentation
angleOffset()
qreal VehicleObjectAvoidance::angleOffset () const inline
Definition at line 43 of file VehicleObjectAvoidance.h.
available()
bool VehicleObjectAvoidance::available () inline
Definition at line 37 of file VehicleObjectAvoidance.h.
distance()
qreal VehicleObjectAvoidance::distance (int i)
Definition at line 99 of file VehicleObjectAvoidance.cc.
distances()
QList< int > VehicleObjectAvoidance::distances () inline
Definition at line 39 of file VehicleObjectAvoidance.h.
enabled()
bool VehicleObjectAvoidance::enabled ()
Definition at line 56 of file VehicleObjectAvoidance.cc.
References Vehicle::compId(), ParameterManager::getParameter(), ParameterManager::parameterExists(), and Vehicle::parameterManager().
grid()
QPointF VehicleObjectAvoidance::grid (int i)
Definition at line 89 of file VehicleObjectAvoidance.cc.
gridSize()
int VehicleObjectAvoidance::gridSize () inline
Definition at line 44 of file VehicleObjectAvoidance.h.
increment()
qreal VehicleObjectAvoidance::increment () const inline
Definition at line 40 of file VehicleObjectAvoidance.h.
maxDistance()
int VehicleObjectAvoidance::maxDistance () const inline
Definition at line 42 of file VehicleObjectAvoidance.h.
minDistance()
int VehicleObjectAvoidance::minDistance () const inline
Definition at line 41 of file VehicleObjectAvoidance.h.
objectAvoidanceChanged [1/2]
void VehicleObjectAvoidance::objectAvoidanceChanged () signal
Referenced by stop(), and update().
objectAvoidanceChanged() [2/2]
bool available READ available NOTIFY VehicleObjectAvoidance::objectAvoidanceChanged (bool enabled READ enabled NOTIFY objectAvoidanceChanged)
stop()
void VehicleObjectAvoidance::stop ()
Definition at line 78 of file VehicleObjectAvoidance.cc.
References Vehicle::compId(), ParameterManager::getParameter(), objectAvoidanceChanged(), ParameterManager::parameterExists(), and Vehicle::parameterManager().
update()
void VehicleObjectAvoidance::update (mavlink_obstacle_distance_t * message)
Definition at line 14 of file VehicleObjectAvoidance.cc.
References objectAvoidanceChanged(), and Vehicle::setpointFactGroup().
The documentation for this class was generated from the following files:
src/Vehicle/VehicleObjectAvoidance.h
src/Vehicle/VehicleObjectAvoidance.cc