QGroundControl: FirmwareUpgradeController Class Reference
FirmwareUpgradeController Class Reference
Supported firmware types. If you modify these you will need to update the qml file as well.
#include <FirmwareUpgradeController.h>
Classes
class FirmwareIdentifier
Public Types
enum AutoPilotStackType_t { AutoPilotStackPX4 = 0 , AutoPilotStackAPM , SiKRadio , SingleFirmwareMode }
enum FirmwareBuildType_t { StableFirmware = 0 , BetaFirmware , DeveloperFirmware , CustomFirmware }
enum FirmwareVehicleType_t {
CopterFirmware = 0 , HeliFirmware , PlaneFirmware , RoverFirmware ,
SubFirmware , DefaultVehicleFirmware
}
Signals
void boardFound (void)
void showFirmwareSelectDlg (void)
void noBoardFound (void)
void boardGone (void)
void flashComplete (void)
void flashCancelled (void)
void error (void)
void selectedFirmwareBuildTypeChanged (FirmwareBuildType_t firmwareType)
void apmFirmwareNamesChanged (void)
void px4StableVersionChanged (const QString &px4StableVersion)
void px4BetaVersionChanged (const QString &px4BetaVersion)
void downloadingFirmwareListChanged (bool downloadingFirmwareList)
Public Member Functions
FirmwareUpgradeController (void)
@Brief Constructs a new FirmwareUpgradeController Widget. This widget is used within the PX4VehicleConfig set of screens.
~FirmwareUpgradeController ()
bool downloadingFirmwareList MEMBER _downloadingFirmwareList NOTIFY downloadingFirmwareListChanged (QString boardPort READ boardPort NOTIFY boardFound) 1(QString boardDescription READ boardDescription NOTIFY boardFound) 1(QString boardType MEMBER _boardTypeName NOTIFY boardFound) 1(bool pixhawkBoard READ pixhawkBoard NOTIFY boardFound) 1(FirmwareBuildType_t selectedFirmwareBuildType READ selectedFirmwareBuildType WRITE setSelectedFirmwareBuildType NOTIFY selectedFirmwareBuildTypeChanged) 1(QStringList apmFirmwareNames MEMBER _apmFirmwareNames NOTIFY apmFirmwareNamesChanged) 1(int apmFirmwareNamesBestIndex MEMBER _apmFirmwareNamesBestIndex NOTIFY apmFirmwareNamesChanged) 1(QStringList apmFirmwareUrls MEMBER _apmFirmwareUrls NOTIFY apmFirmwareNamesChanged) 1(QString px4StableVersion READ px4StableVersion NOTIFY px4StableVersionChanged) 1(QString px4BetaVersion READ px4BetaVersion NOTIFY px4BetaVersionChanged) 1(QQuickItem *statusLog READ statusLog WRITE setStatusLog) 1(QQuickItem *progressBar READ progressBar WRITE setProgressBar) 1 void startBoardSearch(void)
TextArea for log output.
void cancel (void)
Cancels whatever state the upgrade worker thread is in.
void flash (AutoPilotStackType_t stackType, FirmwareBuildType_t firmwareType=StableFirmware, FirmwareVehicleType_t vehicleType=DefaultVehicleFirmware)
Called when the firmware type has been selected by the user to continue the flash process.
void flashFirmwareUrl (QString firmwareUrl)
void flashSingleFirmwareMode (FirmwareBuildType_t firmwareType)
Called to flash when upgrade is running in singleFirmwareMode.
FirmwareVehicleType_t vehicleTypeFromFirmwareSelectionIndex (int index)
void flash (const FirmwareIdentifier &firmwareId)
QQuickItem * progressBar (void)
void setProgressBar (QQuickItem *progressBar)
QQuickItem * statusLog (void)
void setStatusLog (QQuickItem *statusLog)
QString boardPort (void)
QString boardDescription (void)
FirmwareBuildType_t selectedFirmwareBuildType (void)
void setSelectedFirmwareBuildType (FirmwareBuildType_t firmwareType)
QString firmwareTypeAsString (FirmwareBuildType_t type) const
returns firmware type as a string
QString px4StableVersion (void)
QString px4BetaVersion (void)
bool pixhawkBoard (void) const
QStringList availableBoardsName (void)
Return a human friendly string of available boards.
Detailed Description
Supported firmware types. If you modify these you will need to update the qml file as well.
Definition at line 19 of file FirmwareUpgradeController.h.
Member Enumeration Documentation
AutoPilotStackType_t
enum FirmwareUpgradeController::AutoPilotStackType_t
Enumerator
AutoPilotStackPX4
AutoPilotStackAPM
SiKRadio
SingleFirmwareMode
Definition at line 27 of file FirmwareUpgradeController.h.
FirmwareBuildType_t
enum FirmwareUpgradeController::FirmwareBuildType_t
Enumerator
StableFirmware
BetaFirmware
DeveloperFirmware
CustomFirmware
Definition at line 34 of file FirmwareUpgradeController.h.
FirmwareVehicleType_t
enum FirmwareUpgradeController::FirmwareVehicleType_t
Enumerator
CopterFirmware
HeliFirmware
PlaneFirmware
RoverFirmware
SubFirmware
DefaultVehicleFirmware
Definition at line 41 of file FirmwareUpgradeController.h.
Constructor & Destructor Documentation
FirmwareUpgradeController()
FirmwareUpgradeController::FirmwareUpgradeController (void)
@Brief Constructs a new FirmwareUpgradeController Widget. This widget is used within the PX4VehicleConfig set of screens.
Definition at line 105 of file FirmwareUpgradeController.cc.
References BetaFirmware, PX4FirmwareUpgradeThreadController::boardGone(), CopterFirmware, DeveloperFirmware, PX4FirmwareUpgradeThreadController::eraseComplete(), PX4FirmwareUpgradeThreadController::eraseStarted(), PX4FirmwareUpgradeThreadController::error(), PX4FirmwareUpgradeThreadController::flashComplete(), PX4FirmwareUpgradeThreadController::foundBoard(), PX4FirmwareUpgradeThreadController::foundBoardInfo(), HeliFirmware, PX4FirmwareUpgradeThreadController::noBoardFound(), PlaneFirmware, Fact::rawValueChanged(), RoverFirmware, StableFirmware, PX4FirmwareUpgradeThreadController::status(), SubFirmware, and PX4FirmwareUpgradeThreadController::updateProgress().
~FirmwareUpgradeController()
FirmwareUpgradeController::~FirmwareUpgradeController ()
Definition at line 155 of file FirmwareUpgradeController.cc.
Member Function Documentation
apmFirmwareNamesChanged
void FirmwareUpgradeController::apmFirmwareNamesChanged (void) signal
availableBoardsName()
QStringList FirmwareUpgradeController::availableBoardsName (void)
Return a human friendly string of available boards.
Returns
availableBoardNames
Definition at line 218 of file FirmwareUpgradeController.cc.
References QGCSerialPortInfo::availablePorts().
boardDescription()
QString FirmwareUpgradeController::boardDescription (void) inline
Definition at line 126 of file FirmwareUpgradeController.h.
References QSerialPortInfo::description().
boardFound
void FirmwareUpgradeController::boardFound (void) signal
boardGone
void FirmwareUpgradeController::boardGone (void) signal
boardPort()
QString FirmwareUpgradeController::boardPort (void) inline
Definition at line 125 of file FirmwareUpgradeController.h.
References QSerialPortInfo::portName().
cancel()
void FirmwareUpgradeController::cancel (void)
Cancels whatever state the upgrade worker thread is in.
Definition at line 212 of file FirmwareUpgradeController.cc.
References PX4FirmwareUpgradeThreadController::cancel().
downloadingFirmwareListChanged [1/2]
void FirmwareUpgradeController::downloadingFirmwareListChanged (bool downloadingFirmwareList) signal
downloadingFirmwareListChanged() [2/2]
bool downloadingFirmwareList MEMBER _downloadingFirmwareList NOTIFY FirmwareUpgradeController::downloadingFirmwareListChanged (QString boardPort READ boardPort NOTIFY boardFound)
TextArea for log output.
Progress bar for you know what Starts searching for boards on the background thread
error
void FirmwareUpgradeController::error (void) signal
firmwareTypeAsString()
QString FirmwareUpgradeController::firmwareTypeAsString (FirmwareBuildType_t type) const
returns firmware type as a string
Definition at line 417 of file FirmwareUpgradeController.cc.
References BetaFirmware, DeveloperFirmware, and StableFirmware.
flash() [1/2]
void FirmwareUpgradeController::flash (AutoPilotStackType_t stackType, FirmwareBuildType_t firmwareType = StableFirmware, FirmwareVehicleType_t vehicleType = DefaultVehicleFirmware)
Called when the firmware type has been selected by the user to continue the flash process.
Definition at line 175 of file FirmwareUpgradeController.cc.
Referenced by flash(), and flashSingleFirmwareMode().
flash() [2/2]
void FirmwareUpgradeController::flash (const FirmwareIdentifier & firmwareId)
Definition at line 202 of file FirmwareUpgradeController.cc.
References FirmwareUpgradeController::FirmwareIdentifier::autopilotStackType, FirmwareUpgradeController::FirmwareIdentifier::firmwareType, FirmwareUpgradeController::FirmwareIdentifier::firmwareVehicleType, and flash().
flashCancelled
void FirmwareUpgradeController::flashCancelled (void) signal
flashComplete
void FirmwareUpgradeController::flashComplete (void) signal
flashFirmwareUrl()
void FirmwareUpgradeController::flashFirmwareUrl (QString firmwareUrl)
Definition at line 191 of file FirmwareUpgradeController.cc.
flashSingleFirmwareMode()
void FirmwareUpgradeController::flashSingleFirmwareMode (FirmwareBuildType_t firmwareType)
Called to flash when upgrade is running in singleFirmwareMode.
Definition at line 207 of file FirmwareUpgradeController.cc.
References DefaultVehicleFirmware, flash(), and SingleFirmwareMode.
noBoardFound
void FirmwareUpgradeController::noBoardFound (void) signal
pixhawkBoard()
bool FirmwareUpgradeController::pixhawkBoard (void) const inline
Definition at line 135 of file FirmwareUpgradeController.h.
References QGCSerialPortInfo::BoardTypePixhawk.
progressBar()
QQuickItem * FirmwareUpgradeController::progressBar (void) inline
Definition at line 119 of file FirmwareUpgradeController.h.
Referenced by setProgressBar().
px4BetaVersion()
QString FirmwareUpgradeController::px4BetaVersion (void) inline
Definition at line 133 of file FirmwareUpgradeController.h.
px4BetaVersionChanged
void FirmwareUpgradeController::px4BetaVersionChanged (const QString & px4BetaVersion) signal
px4StableVersion()
QString FirmwareUpgradeController::px4StableVersion (void) inline
Definition at line 132 of file FirmwareUpgradeController.h.
px4StableVersionChanged
void FirmwareUpgradeController::px4StableVersionChanged (const QString & px4StableVersion) signal
selectedFirmwareBuildType()
FirmwareBuildType_t FirmwareUpgradeController::selectedFirmwareBuildType (void) inline
Definition at line 128 of file FirmwareUpgradeController.h.
selectedFirmwareBuildTypeChanged
void FirmwareUpgradeController::selectedFirmwareBuildTypeChanged (FirmwareBuildType_t firmwareType) signal
Referenced by setSelectedFirmwareBuildType().
setProgressBar()
void FirmwareUpgradeController::setProgressBar (QQuickItem * progressBar) inline
Definition at line 120 of file FirmwareUpgradeController.h.
References progressBar().
setSelectedFirmwareBuildType()
void FirmwareUpgradeController::setSelectedFirmwareBuildType (FirmwareBuildType_t firmwareType)
Definition at line 513 of file FirmwareUpgradeController.cc.
References selectedFirmwareBuildTypeChanged().
setStatusLog()
void FirmwareUpgradeController::setStatusLog (QQuickItem * statusLog) inline
Definition at line 123 of file FirmwareUpgradeController.h.
References statusLog().
showFirmwareSelectDlg
void FirmwareUpgradeController::showFirmwareSelectDlg (void) signal
statusLog()
QQuickItem * FirmwareUpgradeController::statusLog (void) inline
Definition at line 122 of file FirmwareUpgradeController.h.
Referenced by setStatusLog().
vehicleTypeFromFirmwareSelectionIndex()
FirmwareUpgradeController::FirmwareVehicleType_t FirmwareUpgradeController::vehicleTypeFromFirmwareSelectionIndex (int index)
Definition at line 575 of file FirmwareUpgradeController.cc.
References CopterFirmware.
The documentation for this class was generated from the following files:
src/Vehicle/VehicleSetup/FirmwareUpgradeController.h
src/Vehicle/VehicleSetup/FirmwareUpgradeController.cc