QGroundControl: RallyPoint Class Reference
RallyPoint Class Reference
#include <RallyPoint.h>
Signals
void coordinateChanged (const QGeoCoordinate &coordinate)
void dirtyChanged (bool dirty)
Public Member Functions
RallyPoint (const QGeoCoordinate &coordinate, QObject *parent=nullptr)
RallyPoint (const RallyPoint &other, QObject *parent=nullptr)
~RallyPoint ()
const RallyPoint & operator= (const RallyPoint &other)
QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(QVariantList textFieldFacts MEMBER _textFieldFacts CONSTANT) QGeoCoordinate coordinate(void) const
void setCoordinate (const QGeoCoordinate &coordinate)
bool dirty (void) const
void setDirty (bool dirty)
Static Public Member Functions
static double getDefaultFactAltitude ()
Detailed Description
This class is used to encapsulate the QGeoCoordinate associated with a Rally Point into a QObject such that it can be used in a QmlObjectListMode for Qml.
Definition at line 10 of file RallyPoint.h.
Constructor & Destructor Documentation
RallyPoint() [1/2]
RallyPoint::RallyPoint (const QGeoCoordinate & coordinate, QObject * parent = nullptr)
Definition at line 5 of file RallyPoint.cc.
References setCoordinate().
RallyPoint() [2/2]
RallyPoint::RallyPoint (const RallyPoint & other, QObject * parent = nullptr)
Definition at line 17 of file RallyPoint.cc.
~RallyPoint()
RallyPoint::~RallyPoint ()
Definition at line 42 of file RallyPoint.cc.
Member Function Documentation
coordinateChanged() [1/2]
QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY RallyPoint::coordinateChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) const
Referenced by operator=(), and setCoordinate().
coordinateChanged [2/2]
void RallyPoint::coordinateChanged (const QGeoCoordinate & coordinate) signal
dirty()
bool RallyPoint::dirty (void) const inline
Definition at line 29 of file RallyPoint.h.
Referenced by setDirty().
dirtyChanged
void RallyPoint::dirtyChanged (bool dirty) signal
Referenced by setDirty().
getDefaultFactAltitude()
double RallyPoint::getDefaultFactAltitude () static
Definition at line 89 of file RallyPoint.cc.
operator=()
const RallyPoint & RallyPoint::operator= (const RallyPoint & other)
Definition at line 31 of file RallyPoint.cc.
References coordinateChanged().
setCoordinate()
void RallyPoint::setCoordinate (const QGeoCoordinate & coordinate)
Definition at line 70 of file RallyPoint.cc.
References coordinateChanged(), and setDirty().
Referenced by RallyPoint().
setDirty()
void RallyPoint::setDirty (bool dirty)
Definition at line 81 of file RallyPoint.cc.
References dirty(), and dirtyChanged().
Referenced by setCoordinate().
The documentation for this class was generated from the following files:
src/MissionManager/RallyPoint.h
src/MissionManager/RallyPoint.cc