QGroundControl: TakeoffMissionItem Class Reference
TakeoffMissionItem Class Reference
#include <TakeoffMissionItem.h>
Signals
void launchCoordinateChanged (const QGeoCoordinate &launchCoordinate)
void launchTakeoffAtSameLocationChanged (bool launchTakeoffAtSameLocation)
Signals inherited from SimpleMissionItem
void commandChanged (int command)
void friendlyEditAllowedChanged (bool friendlyEditAllowed)
void headingDegreesChanged (double heading)
void rawEditChanged (bool rawEdit)
void cameraSectionChanged (QObject *cameraSection)
void speedSectionChanged (QObject *cameraSection)
void altitudeFrameChanged (void)
void isLoiterItemChanged (void)
void showLoiterRadiusChanged (void)
void loiterRadiusChanged (double loiterRadius)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
TakeoffMissionItem (PlanMasterController *masterController, bool flyView, MissionSettingsItem *settingsItem, bool forLoad)
TakeoffMissionItem (MAV_CMD takeoffCmd, PlanMasterController *masterController, bool flyView, MissionSettingsItem *settingsItem, bool forLoad)
TakeoffMissionItem (const MissionItem &missionItem, PlanMasterController *masterController, bool flyView, MissionSettingsItem *settingsItem, bool forLoad)
QGeoCoordinate launchCoordinate READ launchCoordinate WRITE _setLaunchCoordinate NOTIFY launchCoordinateChanged (bool launchTakeoffAtSameLocation READ launchTakeoffAtSameLocation WRITE _setLaunchTakeoffAtSameLocation NOTIFY launchTakeoffAtSameLocationChanged) QGeoCoordinate launchCoordinate(void) const
bool launchTakeoffAtSameLocation (void) const
~TakeoffMissionItem ()
void setCoordinate (const QGeoCoordinate &coordinate) override
bool isTakeoffItem (void) const final
double specifiedFlightSpeed (void) final
double specifiedGimbalYaw (void) final
double specifiedGimbalPitch (void) final
QString mapVisualQML (void) const override
bool load (QTextStream &loadStream) final
bool load (const QJsonObject &json, int sequenceNumber, QString &errorString) final
Public Member Functions inherited from SimpleMissionItem
SimpleMissionItem (PlanMasterController *masterController, bool flyView, bool forLoad)
SimpleMissionItem (PlanMasterController *masterController, bool flyView, const MissionItem &missionItem)
~SimpleMissionItem ()
QString category READ category NOTIFY commandChanged (bool friendlyEditAllowed READ friendlyEditAllowed NOTIFY friendlyEditAllowedChanged) 1(bool rawEdit READ rawEdit WRITE setRawEdit NOTIFY rawEditChanged) 1(bool specifiesAltitude READ specifiesAltitude NOTIFY commandChanged) 1(Fact *altitude READ altitude CONSTANT) 1(QGroundControlQmlGlobal
< true: raw item editing with all params
bool scanForSections (QmlObjectListModel *visualItems, int scanIndex, PlanMasterController *masterController)
QString category (void) const
int command (void) const
MAV_CMD mavCommand (void) const
bool friendlyEditAllowed (void) const
bool rawEdit (void) const
bool specifiesAltitude (void) const
QGroundControlQmlGlobal::AltitudeFrame altitudeFrame (void) const
Fact * altitude (void)
Fact * amslAltAboveTerrain (void)
bool isLoiterItem (void) const
bool showLoiterRadius (void) const
double loiterRadius (void) const
CameraSection * cameraSection (void)
SpeedSection * speedSection (void)
QmlObjectListModel * textFieldFacts (void)
QmlObjectListModel * textFieldFactsAdvanced (void)
QmlObjectListModel * nanFacts (void)
QmlObjectListModel * nanFactsAdvanced (void)
QmlObjectListModel * comboboxFacts (void)
QmlObjectListModel * comboboxFactsAdvanced (void)
void setRawEdit (bool rawEdit)
void setAltitudeFrame (QGroundControlQmlGlobal::AltitudeFrame altitudeFrame)
void setCommandByIndex (int index)
void setCommand (int command)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setRadius (double loiterRadius)
MissionItem & missionItem (void)
const MissionItem & missionItem (void) const
bool dirty (void) const override
bool isSimpleItem (void) const final
bool isStandaloneCoordinate (void) const final
bool isLandCommand (void) const final
bool specifiesCoordinate (void) const final
bool specifiesAltitudeOnly (void) const final
QString commandDescription (void) const final
QString commandName (void) const final
QString abbreviation (void) const final
QGeoCoordinate coordinate (void) const final
QGeoCoordinate entryCoordinate (void) const final
QGeoCoordinate exitCoordinate (void) const final
double editableAlt (void) const final
double amslEntryAlt (void) const final
double amslExitAlt (void) const final
int sequenceNumber (void) const final
double specifiedVehicleYaw (void) override
void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent) final
void applyNewAltitude (double newAltitude) final
Adjust the altitude of the item if appropriate to the new altitude.
void setMissionFlightStatus (MissionController::MissionFlightStatus_t &missionFlightStatus) final
ReadyForSaveState readyForSaveState (void) const final
double additionalTimeDelay (void) const final
bool exitCoordinateSameAsEntry (void) const final
void setDirty (bool dirty) final
void setSequenceNumber (int sequenceNumber) final
int lastSequenceNumber (void) const final
void save (QJsonArray &missionItems) final
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool isSurveyItem (void) const
virtual QGCGeoBoundingCube * boundingCube (void)
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Static Public Member Functions
static bool isTakeoffCommand (MAV_CMD command)
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Detailed Description
Takeoff mission item is a special case of a SimpleMissionItem which supports Launch Location display/editing which is tied to home position.
Definition at line 10 of file TakeoffMissionItem.h.
Constructor & Destructor Documentation
TakeoffMissionItem() [1/3]
TakeoffMissionItem::TakeoffMissionItem (PlanMasterController * masterController, bool flyView, MissionSettingsItem * settingsItem, bool forLoad)
Definition at line 11 of file TakeoffMissionItem.cc.
TakeoffMissionItem() [2/3]
TakeoffMissionItem::TakeoffMissionItem (MAV_CMD takeoffCmd, PlanMasterController * masterController, bool flyView, MissionSettingsItem * settingsItem, bool forLoad)
Definition at line 18 of file TakeoffMissionItem.cc.
References SimpleMissionItem::setCommand().
TakeoffMissionItem() [3/3]
TakeoffMissionItem::TakeoffMissionItem (const MissionItem & missionItem, PlanMasterController * masterController, bool flyView, MissionSettingsItem * settingsItem, bool forLoad)
Definition at line 26 of file TakeoffMissionItem.cc.
~TakeoffMissionItem()
TakeoffMissionItem::~TakeoffMissionItem ()
Definition at line 33 of file TakeoffMissionItem.cc.
Member Function Documentation
isTakeoffCommand()
bool TakeoffMissionItem::isTakeoffCommand (MAV_CMD command) static
Definition at line 107 of file TakeoffMissionItem.cc.
References SimpleMissionItem::command(), MissionCommandTree::instance(), and MissionCommandTree::isTakeoffCommand().
isTakeoffItem()
bool TakeoffMissionItem::isTakeoffItem (void) const inline final virtual
Reimplemented from VisualMissionItem.
Definition at line 32 of file TakeoffMissionItem.h.
launchCoordinateChanged() [1/2]
QGeoCoordinate launchCoordinate READ launchCoordinate WRITE _setLaunchCoordinate NOTIFY TakeoffMissionItem::launchCoordinateChanged (bool launchTakeoffAtSameLocation READ launchTakeoffAtSameLocation WRITE _setLaunchTakeoffAtSameLocation NOTIFY launchTakeoffAtSameLocationChanged) const
launchCoordinateChanged [2/2]
void TakeoffMissionItem::launchCoordinateChanged (const QGeoCoordinate & launchCoordinate) signal
launchTakeoffAtSameLocation()
bool TakeoffMissionItem::launchTakeoffAtSameLocation (void) const inline
Definition at line 24 of file TakeoffMissionItem.h.
launchTakeoffAtSameLocationChanged
void TakeoffMissionItem::launchTakeoffAtSameLocationChanged (bool launchTakeoffAtSameLocation) signal
load() [1/2]
bool TakeoffMissionItem::load (const QJsonObject & json, int sequenceNumber, QString & errorString) final virtual
Reimplemented from SimpleMissionItem.
Definition at line 143 of file TakeoffMissionItem.cc.
References VisualMissionItem::_wizardMode, errorString, SimpleMissionItem::load(), and SimpleMissionItem::sequenceNumber().
load() [2/2]
bool TakeoffMissionItem::load (QTextStream & loadStream) final virtual
Reimplemented from SimpleMissionItem.
Definition at line 133 of file TakeoffMissionItem.cc.
References VisualMissionItem::_wizardMode, and SimpleMissionItem::load().
mapVisualQML()
QString TakeoffMissionItem::mapVisualQML (void) const inline override virtual
Returns
The QML resource file which contains the control which visualizes the item on the map.
Reimplemented from SimpleMissionItem.
Definition at line 36 of file TakeoffMissionItem.h.
setCoordinate()
void TakeoffMissionItem::setCoordinate (const QGeoCoordinate & coordinate) override virtual
Reimplemented from SimpleMissionItem.
Definition at line 97 of file TakeoffMissionItem.cc.
References SimpleMissionItem::coordinate(), MissionSettingsItem::setCoordinate(), and SimpleMissionItem::setCoordinate().
specifiedFlightSpeed()
double TakeoffMissionItem::specifiedFlightSpeed (void) inline final virtual
Reimplemented from SimpleMissionItem.
Definition at line 33 of file TakeoffMissionItem.h.
specifiedGimbalPitch()
double TakeoffMissionItem::specifiedGimbalPitch (void) inline final virtual
Reimplemented from SimpleMissionItem.
Definition at line 35 of file TakeoffMissionItem.h.
specifiedGimbalYaw()
double TakeoffMissionItem::specifiedGimbalYaw (void) inline final virtual
Reimplemented from SimpleMissionItem.
Definition at line 34 of file TakeoffMissionItem.h.
The documentation for this class was generated from the following files:
src/MissionManager/TakeoffMissionItem.h
src/MissionManager/TakeoffMissionItem.cc