QGroundControl: Bootloader Class Reference
Bootloader Class Reference
Bootloader Utility routines. Works with PX4 and 3DR Radio bootloaders.
#include <Bootloader.h>
Signals
void updateProgress (int curr, int total)
Signals progress indicator for long running bootloader utility routines.
Public Member Functions
Bootloader (bool sikRadio, QObject *parent=0)
This class manages interactions with the bootloader.
QString errorString (void)
bool open (const QString portName)
void close (void)
bool getBoardInfo (uint32_t &bootloaderVersion, uint32_t &boardID, uint32_t &flashSize)
bool initFlashSequence (void)
bool erase (void)
bool program (const FirmwareImage *image)
bool verify (const FirmwareImage *image)
bool reboot (void)
Static Public Attributes
static const int boardIDSiKRadio1000 = 78
Original radio based on SI1000 chip.
static const int boardIDSiKRadio1060 = 80
Newer radio based on SI1060 chip.
static const int boardIDPX4FMUV2 = 9
PX4 V2 board, as from USB PID.
static const int boardIDPX4FMUV3 = 255
Detailed Description
Bootloader Utility routines. Works with PX4 and 3DR Radio bootloaders.
Definition at line 18 of file Bootloader.h.
Constructor & Destructor Documentation
Bootloader()
Bootloader::Bootloader (bool sikRadio, QObject * parent = 0) explicit
This class manages interactions with the bootloader.
Definition at line 14 of file Bootloader.cc.
Member Function Documentation
close()
void Bootloader::close (void) inline
Definition at line 28 of file Bootloader.h.
References QSerialPort::close().
erase()
bool Bootloader::erase (void)
Definition at line 170 of file Bootloader.cc.
errorString()
QString Bootloader::errorString (void) inline
Definition at line 25 of file Bootloader.h.
getBoardInfo()
bool Bootloader::getBoardInfo (uint32_t & bootloaderVersion, uint32_t & boardID, uint32_t & flashSize)
Definition at line 68 of file Bootloader.cc.
References QSerialPort::Baud57600, boardIDPX4FMUV2, boardIDPX4FMUV3, QSerialPort::setBaudRate(), and QSerialPort::waitForReadyRead().
initFlashSequence()
bool Bootloader::initFlashSequence (void)
Definition at line 153 of file Bootloader.cc.
References QSerialPort::Baud115200, QSerialPort::setBaudRate(), and QSerialPort::waitForReadyRead().
open()
bool Bootloader::open (const QString portName)
Definition at line 21 of file Bootloader.cc.
References QSerialPort::Baud115200, QSerialPort::Data8, QSerialPort::NoFlowControl, QSerialPort::NoParity, QSerialPort::OneStop, QSerialPort::open(), QSerialPort::setBaudRate(), QSerialPort::setDataBits(), QSerialPort::setFlowControl(), QSerialPort::setParity(), QSerialPort::setPortName(), and QSerialPort::setStopBits().
program()
bool Bootloader::program (const FirmwareImage * image)
Definition at line 189 of file Bootloader.cc.
References FirmwareImage::imageIsBinFormat().
reboot()
bool Bootloader::reboot (void)
Definition at line 198 of file Bootloader.cc.
References QSerialPort::flush().
Referenced by verify().
updateProgress
void Bootloader::updateProgress (int curr, int total) signal
Signals progress indicator for long running bootloader utility routines.
verify()
bool Bootloader::verify (const FirmwareImage * image)
Definition at line 486 of file Bootloader.cc.
References FirmwareImage::imageIsBinFormat(), and reboot().
Member Data Documentation
boardIDPX4FMUV2
const int Bootloader::boardIDPX4FMUV2 = 9 static
PX4 V2 board, as from USB PID.
Simulated board id for V3 which is a V2 board which supports larger flash space IMPORTANT: Make sure this id does not conflict with any newly added real board ids
Definition at line 41 of file Bootloader.h.
Referenced by getBoardInfo().
boardIDPX4FMUV3
const int Bootloader::boardIDPX4FMUV3 = 255 static
Definition at line 42 of file Bootloader.h.
Referenced by getBoardInfo(), and FirmwareImage::isCompatible().
boardIDSiKRadio1000
const int Bootloader::boardIDSiKRadio1000 = 78 static
Original radio based on SI1000 chip.
Definition at line 36 of file Bootloader.h.
boardIDSiKRadio1060
const int Bootloader::boardIDSiKRadio1060 = 80 static
Newer radio based on SI1060 chip.
Definition at line 37 of file Bootloader.h.
The documentation for this class was generated from the following files:
src/Vehicle/VehicleSetup/Bootloader.h
src/Vehicle/VehicleSetup/Bootloader.cc