QGroundControl: TerrainProfile Class Reference
TerrainProfile Class Reference
#include <TerrainProfile.h>
Signals
void missionControllerChanged (void)
void visibleWidthChanged (void)
void pixelsPerMeterChanged (void)
void minAMSLAltChanged (void)
void maxAMSLAltChanged (void)
void _updateSignal (void)
Public Member Functions
TerrainProfile (QQuickItem *parent=nullptr)
double visibleWidth MEMBER _visibleWidth NOTIFY visibleWidthChanged (MissionController *missionController READ missionController WRITE setMissionController NOTIFY missionControllerChanged) 1(double pixelsPerMeter MEMBER _pixelsPerMeter NOTIFY pixelsPerMeterChanged) 1(double minAMSLAlt MEMBER _minAMSLAlt NOTIFY minAMSLAltChanged) 1(double maxAMSLAlt MEMBER _maxAMSLAlt NOTIFY maxAMSLAltChanged) MissionController *missionController(void)
void setMissionController (MissionController *missionController)
QSGNode * updatePaintNode (QSGNode *oldNode, QQuickItem::UpdatePaintNodeData *updatePaintNodeData)
void componentComplete (void) final
Detailed Description
Definition at line 17 of file TerrainProfile.h.
Constructor & Destructor Documentation
TerrainProfile()
TerrainProfile::TerrainProfile (QQuickItem * parent = nullptr)
Definition at line 13 of file TerrainProfile.cc.
References _updateSignal(), qgcApp, and visibleWidthChanged().
Member Function Documentation
_updateSignal
void TerrainProfile::_updateSignal (void) signal
Referenced by setMissionController(), and TerrainProfile().
componentComplete()
void TerrainProfile::componentComplete (void) final
Definition at line 26 of file TerrainProfile.cc.
maxAMSLAltChanged
void TerrainProfile::maxAMSLAltChanged (void) signal
Referenced by updatePaintNode().
minAMSLAltChanged
void TerrainProfile::minAMSLAltChanged (void) signal
Referenced by updatePaintNode().
missionControllerChanged
void TerrainProfile::missionControllerChanged (void) signal
Referenced by setMissionController().
pixelsPerMeterChanged
void TerrainProfile::pixelsPerMeterChanged (void) signal
Referenced by updatePaintNode().
setMissionController()
void TerrainProfile::setMissionController (MissionController * missionController)
Definition at line 31 of file TerrainProfile.cc.
References _updateSignal(), missionControllerChanged(), MissionController::recalcTerrainProfile(), visibleWidthChanged(), MissionController::visualItems(), and MissionController::visualItemsChanged().
updatePaintNode()
QSGNode * TerrainProfile::updatePaintNode (QSGNode * oldNode, QQuickItem::UpdatePaintNodeData * updatePaintNodeData)
Definition at line 203 of file TerrainProfile.cc.
References ComplexMissionItem::complexDistance(), QmlObjectListModel::count(), maxAMSLAltChanged(), MissionController::maxAMSLAltitude(), minAMSLAltChanged(), MissionController::minAMSLAltitude(), MissionController::missionTotalDistance(), pixelsPerMeterChanged(), VisualMissionItem::simpleFlightPathSegment(), FlightPathSegment::totalDistance(), and QmlObjectListModel::value().
visibleWidthChanged() [1/2]
double visibleWidth MEMBER _visibleWidth NOTIFY TerrainProfile::visibleWidthChanged (MissionController *missionController READ missionController WRITE setMissionController NOTIFY missionControllerChanged) inline
Definition at line 25 of file TerrainProfile.h.
visibleWidthChanged [2/2]
void TerrainProfile::visibleWidthChanged (void) signal
Referenced by setMissionController(), and TerrainProfile().
The documentation for this class was generated from the following files:
src/QmlControls/TerrainProfile.h
src/QmlControls/TerrainProfile.cc