QGroundControl: MissionItem Class Reference
MissionItem Class Reference
#include <MissionItem.h>
Signals
void isCurrentItemChanged (bool isCurrentItem)
void sequenceNumberChanged (int sequenceNumber)
void specifiedFlightSpeedChanged (double flightSpeed)
void specifiedGimbalYawChanged (double gimbalYaw)
void specifiedGimbalPitchChanged (double gimbalPitch)
Public Member Functions
MissionItem (QObject *parent=nullptr)
MissionItem (int sequenceNumber, MAV_CMD command, MAV_FRAME frame, double param1, double param2, double param3, double param4, double param5, double param6, double param7, bool autoContinue, bool isCurrentItem, QObject *parent=nullptr)
MissionItem (const MissionItem &other, QObject *parent=nullptr)
~MissionItem ()
const MissionItem & operator= (const MissionItem &other)
MAV_CMD command (void) const
bool isCurrentItem (void) const
int sequenceNumber (void) const
MAV_FRAME frame (void) const
bool autoContinue (void) const
double param1 (void) const
double param2 (void) const
double param3 (void) const
double param4 (void) const
double param5 (void) const
double param6 (void) const
double param7 (void) const
QGeoCoordinate coordinate (void) const
int doJumpId (void) const
double specifiedFlightSpeed (void) const
double specifiedGimbalYaw (void) const
double specifiedGimbalPitch (void) const
void setCommand (MAV_CMD command)
void setSequenceNumber (int sequenceNumber)
void setIsCurrentItem (bool isCurrentItem)
void setFrame (MAV_FRAME frame)
void setAutoContinue (bool autoContinue)
void setParam1 (double param1)
void setParam2 (double param2)
void setParam3 (double param3)
void setParam4 (double param4)
void setParam5 (double param5)
void setParam6 (double param6)
void setParam7 (double param7)
void save (QJsonObject &json) const
bool load (QTextStream &loadStream)
bool load (const QJsonObject &json, int sequenceNumber, QString &errorString)
bool relativeAltitude (void) const
Friends
class SurveyComplexItem
class SimpleMissionItem
class MissionController
Detailed Description
Definition at line 21 of file MissionItem.h.
Constructor & Destructor Documentation
MissionItem() [1/3]
MissionItem::MissionItem (QObject * parent = nullptr)
Definition at line 9 of file MissionItem.cc.
References Fact::rawValueChanged(), and setAutoContinue().
MissionItem() [2/3]
MissionItem::MissionItem (int sequenceNumber, MAV_CMD command, MAV_FRAME frame, double param1, double param2, double param3, double param4, double param5, double param6, double param7, bool autoContinue, bool isCurrentItem, QObject * parent = nullptr)
Definition at line 36 of file MissionItem.cc.
References autoContinue(), command(), frame(), param1(), param2(), param3(), param4(), param5(), param6(), param7(), Fact::rawValueChanged(), setAutoContinue(), setCommand(), and setFrame().
MissionItem() [3/3]
MissionItem::MissionItem (const MissionItem & other, QObject * parent = nullptr)
Definition at line 83 of file MissionItem.cc.
References Fact::rawValueChanged().
~MissionItem()
MissionItem::~MissionItem ()
Definition at line 129 of file MissionItem.cc.
Member Function Documentation
autoContinue()
bool MissionItem::autoContinue (void) const inline
Definition at line 53 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), SimpleMissionItem::friendlyEditAllowed(), MissionItem(), operator=(), save(), and setAutoContinue().
command()
MAV_CMD MissionItem::command (void) const inline
Definition at line 49 of file MissionItem.h.
Referenced by PlanManager::_handleMissionItem(), PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslExitAlt(), MissionManager::generateResumeMission(), MissionItem(), operator=(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), SimpleMissionItem::setCommand(), setCommand(), and PlanManager::writeMissionItems().
coordinate()
QGeoCoordinate MissionItem::coordinate (void) const
Definition at line 388 of file MissionItem.cc.
References param5(), param6(), and param7().
doJumpId()
int MissionItem::doJumpId (void) const inline
Definition at line 62 of file MissionItem.h.
frame()
MAV_FRAME MissionItem::frame (void) const inline
Definition at line 52 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), SimpleMissionItem::friendlyEditAllowed(), MissionItem(), operator=(), relativeAltitude(), save(), setFrame(), and SimpleMissionItem::SimpleMissionItem().
isCurrentItem()
bool MissionItem::isCurrentItem (void) const inline
Definition at line 50 of file MissionItem.h.
Referenced by setIsCurrentItem(), and SimpleMissionItem::SimpleMissionItem().
isCurrentItemChanged
void MissionItem::isCurrentItemChanged (bool isCurrentItem) signal
Referenced by setIsCurrentItem().
load() [1/2]
bool MissionItem::load (const QJsonObject & json, int sequenceNumber, QString & errorString)
Definition at line 238 of file MissionItem.cc.
References errorString, VisualMissionItem::jsonTypeKey, VisualMissionItem::jsonTypeSimpleItemValue, JsonParsing::possibleNaNJsonValue(), sequenceNumber(), setAutoContinue(), setCommand(), setFrame(), setIsCurrentItem(), setParam1(), setParam2(), setParam3(), setParam4(), setParam5(), setParam6(), setParam7(), setSequenceNumber(), and JsonHelper::validateKeys().
load() [2/2]
bool MissionItem::load (QTextStream & loadStream)
Definition at line 146 of file MissionItem.cc.
References setAutoContinue(), setCommand(), setFrame(), setIsCurrentItem(), setParam1(), setParam2(), setParam3(), setParam4(), setParam5(), setParam6(), setParam7(), and setSequenceNumber().
Referenced by TransectStyleComplexItem::_load(), SimpleMissionItem::load(), and SimpleMissionItem::load().
operator=()
const MissionItem & MissionItem::operator= (const MissionItem & other)
Definition at line 108 of file MissionItem.cc.
References autoContinue(), command(), frame(), setAutoContinue(), setCommand(), setFrame(), setIsCurrentItem(), and setSequenceNumber().
param1()
double MissionItem::param1 (void) const inline
Definition at line 54 of file MissionItem.h.
Referenced by PlanManager::_handleMissionItem(), PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), SimpleMissionItem::additionalTimeDelay(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), CameraSection::scanStopTakingVideo(), setParam1(), and PlanManager::writeMissionItems().
param2()
double MissionItem::param2 (void) const inline
Definition at line 55 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), SimpleMissionItem::loiterRadius(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), and setParam2().
param3()
double MissionItem::param3 (void) const inline
Definition at line 56 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), MissionManager::generateResumeMission(), SimpleMissionItem::loiterRadius(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), and setParam3().
param4()
double MissionItem::param4 (void) const inline
Definition at line 57 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), setParam4(), and SimpleMissionItem::specifiedVehicleYaw().
param5()
double MissionItem::param5 (void) const inline
Definition at line 58 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), coordinate(), SimpleMissionItem::coordinate(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), SimpleMissionItem::setCoordinate(), and setParam5().
param6()
double MissionItem::param6 (void) const inline
Definition at line 59 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), coordinate(), SimpleMissionItem::coordinate(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), SimpleMissionItem::setCoordinate(), and setParam6().
param7()
double MissionItem::param7 (void) const inline
Definition at line 60 of file MissionItem.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_lastMissionReqestString(), LandingComplexItem::_scanForItem(), SimpleMissionItem::amslEntryAlt(), TransectStyleComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslExitAlt(), coordinate(), SimpleMissionItem::editableAlt(), MissionItem(), save(), SpeedSection::scanForSection(), CameraSection::scanStopTakingPhotos(), and setParam7().
relativeAltitude()
bool MissionItem::relativeAltitude (void) const inline
Definition at line 90 of file MissionItem.h.
References frame().
Referenced by SimpleMissionItem::load(), and SimpleMissionItem::load().
save()
void MissionItem::save (QJsonObject & json) const
Definition at line 134 of file MissionItem.cc.
References autoContinue(), command(), frame(), VisualMissionItem::jsonTypeKey, VisualMissionItem::jsonTypeSimpleItemValue, param1(), param2(), param3(), param4(), param5(), param6(), and param7().
Referenced by MissionSettingsItem::save(), SimpleMissionItem::save(), and MissionController::save().
sequenceNumber()
int MissionItem::sequenceNumber (void) const inline
Definition at line 51 of file MissionItem.h.
Referenced by load(), SimpleMissionItem::sequenceNumber(), setSequenceNumber(), SimpleMissionItem::setSequenceNumber(), and PlanManager::writeMissionItems().
sequenceNumberChanged
void MissionItem::sequenceNumberChanged (int sequenceNumber) signal
Referenced by setSequenceNumber().
setAutoContinue()
void MissionItem::setAutoContinue (bool autoContinue)
Definition at line 324 of file MissionItem.cc.
References autoContinue().
Referenced by load(), load(), MissionItem(), MissionItem(), and operator=().
setCommand()
void MissionItem::setCommand (MAV_CMD command)
Definition at line 310 of file MissionItem.cc.
References command().
Referenced by load(), load(), MissionItem(), operator=(), and SimpleMissionItem::setCommand().
setFrame()
void MissionItem::setFrame (MAV_FRAME frame)
Definition at line 317 of file MissionItem.cc.
References frame().
Referenced by load(), load(), MissionItem(), and operator=().
setIsCurrentItem()
void MissionItem::setIsCurrentItem (bool isCurrentItem)
Definition at line 331 of file MissionItem.cc.
References isCurrentItem(), and isCurrentItemChanged().
Referenced by MissionManager::generateResumeMission(), load(), load(), operator=(), and PlanManager::writeMissionItems().
setParam1()
void MissionItem::setParam1 (double param1)
Definition at line 339 of file MissionItem.cc.
References param1().
Referenced by PlanManager::_handleMissionItem(), MissionController::insertCancelROIMissionItem(), MissionController::insertROIMissionItem(), load(), load(), and PlanManager::writeMissionItems().
setParam2()
void MissionItem::setParam2 (double param2)
Definition at line 346 of file MissionItem.cc.
References param2().
Referenced by load(), load(), and SimpleMissionItem::setRadius().
setParam3()
void MissionItem::setParam3 (double param3)
Definition at line 353 of file MissionItem.cc.
References param3().
Referenced by load(), load(), and SimpleMissionItem::setRadius().
setParam4()
void MissionItem::setParam4 (double param4)
Definition at line 360 of file MissionItem.cc.
References param4().
Referenced by load(), and load().
setParam5()
void MissionItem::setParam5 (double param5)
Definition at line 367 of file MissionItem.cc.
References param5().
Referenced by load(), load(), and SimpleMissionItem::setCoordinate().
setParam6()
void MissionItem::setParam6 (double param6)
Definition at line 374 of file MissionItem.cc.
References param6().
Referenced by load(), load(), and SimpleMissionItem::setCoordinate().
setParam7()
void MissionItem::setParam7 (double param7)
Definition at line 381 of file MissionItem.cc.
References param7().
Referenced by load(), and load().
setSequenceNumber()
void MissionItem::setSequenceNumber (int sequenceNumber)
Definition at line 302 of file MissionItem.cc.
References sequenceNumber(), and sequenceNumberChanged().
Referenced by TransectStyleComplexItem::_appendLoadedMissionItems(), MissionManager::generateResumeMission(), load(), load(), operator=(), SimpleMissionItem::setSequenceNumber(), and PlanManager::writeMissionItems().
specifiedFlightSpeed()
double MissionItem::specifiedFlightSpeed (void) const
Returns
Flight speed change value if this item supports it. If not it returns NaN.
Definition at line 397 of file MissionItem.cc.
Referenced by SimpleMissionItem::specifiedFlightSpeed().
specifiedFlightSpeedChanged
void MissionItem::specifiedFlightSpeedChanged (double flightSpeed) signal
specifiedGimbalPitch()
double MissionItem::specifiedGimbalPitch (void) const
Returns
Flight gimbal pitch change value if this item supports it. If not it returns NaN.
Definition at line 419 of file MissionItem.cc.
Referenced by SimpleMissionItem::specifiedGimbalPitch().
specifiedGimbalPitchChanged
void MissionItem::specifiedGimbalPitchChanged (double gimbalPitch) signal
specifiedGimbalYaw()
double MissionItem::specifiedGimbalYaw (void) const
Returns
Flight gimbal yaw change value if this item supports it. If not it returns NaN.
Definition at line 408 of file MissionItem.cc.
Referenced by SimpleMissionItem::specifiedGimbalYaw().
specifiedGimbalYawChanged
void MissionItem::specifiedGimbalYawChanged (double gimbalYaw) signal
Friends And Related Symbol Documentation
MissionController
friend class MissionController friend
Definition at line 141 of file MissionItem.h.
SimpleMissionItem
friend class SimpleMissionItem friend
Definition at line 140 of file MissionItem.h.
SurveyComplexItem
friend class SurveyComplexItem friend
Definition at line 139 of file MissionItem.h.
The documentation for this class was generated from the following files:
src/MissionManager/MissionItem.h
src/MissionManager/MissionItem.cc