QGroundControl: KMLSchemaValidator Class Reference
KMLSchemaValidator Class Reference
#include <KMLSchemaValidator.h>
Classes
struct ValidationResult
Public Member Functions
ValidationResult validate (const QDomDocument &doc) const
Validate a KML document.
ValidationResult validateFile (const QString &kmlFile) const
Validate a KML file.
bool isValidEnumValue (const QString &enumTypeName, const QString &value) const
Check if a value is valid for a given XSD enum type (e.g., "altitudeModeEnumType")
QStringList validEnumValues (const QString &enumTypeName) const
Get all valid values for an enum type.
bool isValidElement (const QString &elementName) const
Check if an element name is defined in the schema.
QStringList validElements () const
Get all valid KML element names.
Static Public Member Functions
static KMLSchemaValidator * instance ()
Detailed Description
Validates KML documents against rules extracted from the OGC KML 2.2 XSD schema. This provides schema-driven validation without requiring a full XML Schema processor.
Definition at line 15 of file KMLSchemaValidator.h.
Member Function Documentation
instance()
KMLSchemaValidator * KMLSchemaValidator::instance () static
Definition at line 18 of file KMLSchemaValidator.cc.
Referenced by KMLHelper::_checkAltitudeMode().
isValidElement()
bool KMLSchemaValidator::isValidElement (const QString & elementName) const
Check if an element name is defined in the schema.
Definition at line 121 of file KMLSchemaValidator.cc.
isValidEnumValue()
bool KMLSchemaValidator::isValidEnumValue (const QString & enumTypeName, const QString & value) const
Check if a value is valid for a given XSD enum type (e.g., "altitudeModeEnumType")
Definition at line 107 of file KMLSchemaValidator.cc.
validate()
KMLSchemaValidator::ValidationResult KMLSchemaValidator::validate (const QDomDocument & doc) const
Validate a KML document.
Definition at line 153 of file KMLSchemaValidator.cc.
References KMLSchemaValidator::ValidationResult::addError(), KMLSchemaValidator::ValidationResult::addWarning(), and KMLDomDocument::kmlNamespace.
Referenced by validateFile().
validateFile()
KMLSchemaValidator::ValidationResult KMLSchemaValidator::validateFile (const QString & kmlFile) const
Validate a KML file.
Definition at line 131 of file KMLSchemaValidator.cc.
References KMLSchemaValidator::ValidationResult::addError(), and validate().
validElements()
QStringList KMLSchemaValidator::validElements () const
Get all valid KML element names.
Definition at line 126 of file KMLSchemaValidator.cc.
validEnumValues()
QStringList KMLSchemaValidator::validEnumValues (const QString & enumTypeName) const
Get all valid values for an enum type.
Definition at line 116 of file KMLSchemaValidator.cc.
The documentation for this class was generated from the following files:
src/Utilities/Geo/KMLSchemaValidator.h
src/Utilities/Geo/KMLSchemaValidator.cc