QGroundControl: RadioComponentController Class Reference
RadioComponentController Class Reference
Controller class for RC Transmitter calibration.
#include <RadioComponentController.h>
Public Types
enum BindModes { DSM2 , DSMX7 , DSMX8 }
Signals
void throttleReversedCalFailure ()
Signalled to indicate cal failure due to reversed throttle.
Signals inherited from RemoteControlCalibrationController
void channelCountChanged (int channelCount)
void rawChannelValueChanged (int channel, int value)
void rollChannelMappedChanged (bool mapped)
void pitchChannelMappedChanged (bool mapped)
void rollExtensionChannelMappedChanged (bool mapped)
void pitchExtensionChannelMappedChanged (bool mapped)
void aux1ExtensionChannelMappedChanged (bool mapped)
void aux2ExtensionChannelMappedChanged (bool mapped)
void aux3ExtensionChannelMappedChanged (bool mapped)
void aux4ExtensionChannelMappedChanged (bool mapped)
void aux5ExtensionChannelMappedChanged (bool mapped)
void aux6ExtensionChannelMappedChanged (bool mapped)
void yawChannelMappedChanged (bool mapped)
void throttleChannelMappedChanged (bool mapped)
void pitchExtensionEnabledChanged (bool enabled)
void rollExtensionEnabledChanged (bool enabled)
void aux1ExtensionEnabledChanged (bool enabled)
void aux2ExtensionEnabledChanged (bool enabled)
void aux3ExtensionEnabledChanged (bool enabled)
void aux4ExtensionEnabledChanged (bool enabled)
void aux5ExtensionEnabledChanged (bool enabled)
void aux6ExtensionEnabledChanged (bool enabled)
void anyExtensionEnabledChanged (bool enabled)
void adjustedRollChannelValueChanged (int rcValue)
void adjustedPitchChannelValueChanged (int rcValue)
void adjustedYawChannelValueChanged (int rcValue)
void adjustedThrottleChannelValueChanged (int rcValue)
void adjustedRollExtensionChannelValueChanged (int rcValue)
void adjustedPitchExtensionChannelValueChanged (int rcValue)
void adjustedAux1ExtensionChannelValueChanged (int rcValue)
void adjustedAux2ExtensionChannelValueChanged (int rcValue)
void adjustedAux3ExtensionChannelValueChanged (int rcValue)
void adjustedAux4ExtensionChannelValueChanged (int rcValue)
void adjustedAux5ExtensionChannelValueChanged (int rcValue)
void adjustedAux6ExtensionChannelValueChanged (int rcValue)
void rollChannelReversedChanged (bool reversed)
void pitchChannelReversedChanged (bool reversed)
void rollExtensionChannelReversedChanged (bool reversed)
void pitchExtensionChannelReversedChanged (bool reversed)
void aux1ExtensionChannelReversedChanged (bool reversed)
void aux2ExtensionChannelReversedChanged (bool reversed)
void aux3ExtensionChannelReversedChanged (bool reversed)
void aux4ExtensionChannelReversedChanged (bool reversed)
void aux5ExtensionChannelReversedChanged (bool reversed)
void aux6ExtensionChannelReversedChanged (bool reversed)
void yawChannelReversedChanged (bool reversed)
void throttleChannelReversedChanged (bool reversed)
void rollDeadbandChanged (int deadband)
void pitchDeadbandChanged (int deadband)
void rollExtensionDeadbandChanged (int deadband)
void pitchExtensionDeadbandChanged (int deadband)
void aux1ExtensionDeadbandChanged (int deadband)
void aux2ExtensionDeadbandChanged (int deadband)
void aux3ExtensionDeadbandChanged (int deadband)
void aux4ExtensionDeadbandChanged (int deadband)
void aux5ExtensionDeadbandChanged (int deadband)
void aux6ExtensionDeadbandChanged (int deadband)
void yawDeadbandChanged (int deadband)
void throttleDeadbandChanged (int deadband)
void transmitterModeChanged ()
void stickDisplayPositionsChanged ()
void centeredThrottleChanged (bool centeredThrottle)
void joystickModeChanged (bool joystickMode)
void calibratingChanged (bool calibrating)
void singleStickDisplayChanged (bool singleStickDisplay)
void calibrationCompleted ()
Signals inherited from FactPanelController
void missingParametersAvailable ()
Public Member Functions
RadioComponentController (QObject *parent=nullptr)
~RadioComponentController ()
void spektrumBindMode (int mode)
void crsfBindMode ()
void start () final override
Additional Inherited Members
Public Slots inherited from RemoteControlCalibrationController
void rawChannelValuesChanged (QVector< int > channelValues)
Protected Member Functions inherited from RemoteControlCalibrationController
void _validateAndAdjustCalibrationValues ()
QString _stickFunctionToString (StickFunction stickFunction)
void _signalAllAttitudeValueChanges ()
void _resetInternalCalibrationValues ()
Resets internal calibration values to their initial state in preparation for a new calibration sequence.
virtual bool _stickFunctionEnabled (StickFunction stickFunction)
Returns true if the stick function is enabled.
Protected Member Functions inherited from FactPanelController
bool _allParametersExists (int componentId, const QStringList &names) const
void _reportMissingParameter (int componentId, const QString &name) const
Report a missing parameter.
Protected Attributes inherited from RemoteControlCalibrationController
ChannelInfo _rgChannelInfo [_chanMax]
Information associated with each rc channel.
int _calValidMinValue
Largest valid minimum channel range value.
int _calValidMaxValue
Smallest valid maximum channel range value.
int _calCenterPoint
Center point for calibration.
int _calDefaultMinValue
Default value for Min if not set.
int _calDefaultMaxValue
Default value for Max if not set.
int _calRoughCenterDelta
Delta around center point which is considered to be roughly centered.
int _calMoveDelta
Amount of delta past center which is considered stick movement.
int _calSettleDelta
Amount of delta which is considered no stick movement.
int _stickDetectSettleMSecs = 1000
Time in ms stick must be stable before detection completes.
int _chanCount = 0
Number of actual rc channels available.
int _rgFunctionChannelMapping [stickFunctionMax]
Maps from StickFunction to channel index. _chanMax indicates channel not set for this function.
Protected Attributes inherited from FactPanelController
Vehicle * _vehicle = nullptr
Static Protected Attributes inherited from RemoteControlCalibrationController
static constexpr int _chanMax = QGCMAVLink::maxRcChannels
A set of information associated with a radio channel.
static constexpr int _chanMinimum = 4
Minimum numner of channels required to run.
Detailed Description
Controller class for RC Transmitter calibration.
Definition at line 11 of file RadioComponentController.h.
Member Enumeration Documentation
BindModes
enum RadioComponentController::BindModes
Enumerator
DSM2
DSMX7
DSMX8
Definition at line 22 of file RadioComponentController.h.
Constructor & Destructor Documentation
RadioComponentController()
RadioComponentController::RadioComponentController (QObject * parent = nullptr)
Definition at line 13 of file RadioComponentController.cc.
References QGCMAVLink::CalibrationRadio, and ParameterManager::defaultComponentId.
~RadioComponentController()
RadioComponentController::~RadioComponentController ()
Definition at line 46 of file RadioComponentController.cc.
References FactPanelController::_vehicle, Vehicle::px4Firmware(), and Vehicle::stopCalibration().
Member Function Documentation
crsfBindMode()
void RadioComponentController::crsfBindMode ()
Definition at line 68 of file RadioComponentController.cc.
References FactPanelController::_vehicle, and Vehicle::pairRX().
spektrumBindMode()
void RadioComponentController::spektrumBindMode (int mode)
Definition at line 63 of file RadioComponentController.cc.
References FactPanelController::_vehicle, and Vehicle::pairRX().
start()
void RadioComponentController::start (void) final override virtual
Reimplemented from RemoteControlCalibrationController.
Definition at line 56 of file RadioComponentController.cc.
References FactPanelController::_vehicle, RemoteControlCalibrationController::rawChannelValuesChanged(), and Vehicle::rcChannelsChanged().
throttleReversedCalFailure
void RadioComponentController::throttleReversedCalFailure () signal
Signalled to indicate cal failure due to reversed throttle.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/Common/RadioComponentController.h
src/AutoPilotPlugins/Common/RadioComponentController.cc