QGroundControl: RTCMParser Class Reference
RTCMParser Class Reference
#include <RTCMParser.h>
Public Member Functions
RTCMParser ()
void reset ()
bool addByte (uint8_t byte)
uint8_t * message ()
uint16_t messageLength () const
uint16_t messageId () const
const uint8_t * crcBytes () const
bool validateCrc () const
Static Public Member Functions
static uint32_t crc24q (const uint8_t *data, size_t len)
Static Public Attributes
static constexpr int kCrcSize = 3
Detailed Description
Definition at line 8 of file RTCMParser.h.
Constructor & Destructor Documentation
RTCMParser()
RTCMParser::RTCMParser ()
Definition at line 3 of file RTCMParser.cc.
References reset().
Member Function Documentation
addByte()
bool RTCMParser::addByte (uint8_t byte)
Definition at line 17 of file RTCMParser.cc.
References kCrcSize, reset(), and RTCM3_PREAMBLE.
crc24q()
uint32_t RTCMParser::crc24q (const uint8_t * data, size_t len) static
Definition at line 70 of file RTCMParser.cc.
Referenced by validateCrc().
crcBytes()
const uint8_t * RTCMParser::crcBytes () const inline
Definition at line 17 of file RTCMParser.h.
message()
uint8_t * RTCMParser::message () inline
Definition at line 14 of file RTCMParser.h.
messageId()
uint16_t RTCMParser::messageId () const
Definition at line 62 of file RTCMParser.cc.
messageLength()
uint16_t RTCMParser::messageLength () const inline
Definition at line 15 of file RTCMParser.h.
reset()
void RTCMParser::reset ()
Definition at line 8 of file RTCMParser.cc.
Referenced by addByte(), and RTCMParser().
validateCrc()
bool RTCMParser::validateCrc () const
Definition at line 86 of file RTCMParser.cc.
References crc24q().
Member Data Documentation
kCrcSize
constexpr int RTCMParser::kCrcSize = 3 static constexpr
Definition at line 18 of file RTCMParser.h.
Referenced by addByte().
The documentation for this class was generated from the following files:
src/GPS/NTRIP/RTCMParser.h
src/GPS/NTRIP/RTCMParser.cc