QGroundControl: TCPWorker Class Reference
TCPWorker Class Reference
#include <TCPLink.h>
Public Slots
void setupSocket ()
void connectToHost ()
void disconnectFromHost ()
void writeData (const QByteArray &data)
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &errorString)
void dataReceived (const QByteArray &data)
void dataSent (const QByteArray &data)
Public Member Functions
TCPWorker (const TCPConfiguration *config, QObject *parent=nullptr)
~TCPWorker () override
bool isConnected () const
Detailed Description
Definition at line 52 of file TCPLink.h.
Constructor & Destructor Documentation
TCPWorker()
TCPWorker::TCPWorker (const TCPConfiguration * config, QObject * parent = nullptr) explicit
Definition at line 88 of file TCPLink.cc.
~TCPWorker()
TCPWorker::~TCPWorker () override
Definition at line 95 of file TCPLink.cc.
References disconnectFromHost().
Member Function Documentation
connected
void TCPWorker::connected () signal
Referenced by TCPLink::TCPLink().
connectToHost
void TCPWorker::connectToHost () slot
Definition at line 135 of file TCPLink.cc.
References errorOccurred(), and isConnected().
dataReceived
void TCPWorker::dataReceived (const QByteArray & data) signal
Referenced by TCPLink::TCPLink().
dataSent
void TCPWorker::dataSent (const QByteArray & data) signal
Referenced by TCPLink::TCPLink(), and writeData().
disconnected
void TCPWorker::disconnected () signal
Referenced by TCPLink::TCPLink().
disconnectFromHost
void TCPWorker::disconnectFromHost () slot
Definition at line 165 of file TCPLink.cc.
References isConnected().
Referenced by ~TCPWorker().
errorOccurred
void TCPWorker::errorOccurred (const QString & errorString) signal
Referenced by connectToHost(), TCPLink::TCPLink(), and writeData().
isConnected()
bool TCPWorker::isConnected () const
Definition at line 102 of file TCPLink.cc.
Referenced by connectToHost(), disconnectFromHost(), TCPLink::isConnected(), and writeData().
setupSocket
void TCPWorker::setupSocket () slot
Definition at line 107 of file TCPLink.cc.
Referenced by TCPLink::TCPLink().
writeData
void TCPWorker::writeData (const QByteArray & data) slot
Definition at line 181 of file TCPLink.cc.
References dataSent(), errorOccurred(), and isConnected().
The documentation for this class was generated from the following files:
src/Comms/TCPLink.h
src/Comms/TCPLink.cc