QGroundControl: Mixer::Mixers Class Reference
Mixer::Mixers Class Reference
#include <Mixer.h>
Classes
struct OutputFunction
Public Slots
void update ()
Signals
void groupsChanged ()
void paramChanged ()
void geometryParamChanged ()
Public Member Functions
Mixers (ParameterManager *parameterManager)
void reset (const ActuatorTypes &actuatorTypes, const MixerOptions &mixerOptions, const QMap< int, OutputFunction > &functions, const Rules &rules)
QmlObjectListModel *groups READ groups NOTIFY groupsChanged (QString title READ title NOTIFY groupsChanged) 1(QString helpUrl READ helpUrl NOTIFY groupsChanged) QmlObjectListModel *groups()
QString title () const
QString helpUrl () const
const ActuatorTypes & actuatorTypes () const
QString getSpecificLabelForFunction (int function) const
QSet< int > getFunctions (bool requiredOnly) const
QString configuredType () const
const QMap< int, OutputFunction > & functions () const
Detailed Description
Definition at line 349 of file Mixer.h.
Constructor & Destructor Documentation
Mixers()
Mixer::Mixers::Mixers (ParameterManager * parameterManager) inline
Definition at line 353 of file Mixer.h.
Member Function Documentation
actuatorTypes()
const ActuatorTypes & Mixer::Mixers::actuatorTypes () const inline
Definition at line 378 of file Mixer.h.
Referenced by Actuators::initMotorAssignment(), Actuators::parametersChanged(), and reset().
configuredType()
QString Mixers::configuredType () const
Definition at line 603 of file Mixer.cc.
Referenced by Actuators::isMultirotor().
functions()
const QMap< int, OutputFunction > & Mixer::Mixers::functions () const inline
Definition at line 396 of file Mixer.h.
Referenced by Actuators::parametersChanged(), and reset().
geometryParamChanged
void Mixer::Mixers::geometryParamChanged () signal
Referenced by Actuators::Actuators().
getFunctions()
QSet< int > Mixers::getFunctions (bool requiredOnly) const
Get the set of all (required) actuator functions
Definition at line 585 of file Mixer.cc.
References Mixer::MixerChannel::actuatorFunction(), Mixer::MixerConfigGroup::channels(), QmlObjectListModel::count(), Mixer::MixerConfigGroup::group(), Mixer::MixerOption::ActuatorGroup::required, and QmlObjectListModel::value().
Referenced by Actuators::parametersChanged().
getSpecificLabelForFunction()
QString Mixers::getSpecificLabelForFunction (int function) const
Get the mixer-specific label for a certain output function and the current configuration, combined with the generic label. E.g. 'Front Left Tilt (Servo 1)' for the 'Servo 1' function.
Parameters
function actuator output function
Returns
empty string if there's no such function
Definition at line 542 of file Mixer.cc.
References Mixer::MixerChannel::actuatorFunction(), Mixer::MixerConfigGroup::channels(), QmlObjectListModel::count(), Mixer::MixerChannel::getFact(), Mixer::Type, and QmlObjectListModel::value().
Referenced by Actuators::parametersChanged().
groupsChanged [1/2]
void Mixer::Mixers::groupsChanged () signal
Referenced by update().
groupsChanged() [2/2]
QmlObjectListModel *groups READ groups NOTIFY Mixer::Mixers::groupsChanged (QString title READ title NOTIFY groupsChanged) inline
Definition at line 369 of file Mixer.h.
helpUrl()
QString Mixers::helpUrl () const
Definition at line 618 of file Mixer.cc.
paramChanged
void Mixer::Mixers::paramChanged () signal
Referenced by Actuators::Actuators().
reset()
void Mixers::reset (const ActuatorTypes & actuatorTypes, const MixerOptions & mixerOptions, const QMap< int, OutputFunction > & functions, const Rules & rules)
Definition at line 390 of file Mixer.cc.
References actuatorTypes(), QmlObjectListModel::clearAndDeleteContents(), functions(), and update().
title()
QString Mixers::title () const
Definition at line 611 of file Mixer.cc.
update
void Mixers::update () slot
Call this on param update(s)
Definition at line 406 of file Mixer.cc.
References Mixer::MixerConfigGroup::addChannel(), Mixer::MixerConfigGroup::addChannelConfig(), Mixer::MixerConfigGroup::addConfigParam(), QmlObjectListModel::append(), Mixer::AxisX, Mixer::AxisY, Mixer::AxisZ, Mixer::MixerConfigGroup::channelConfigs(), QmlObjectListModel::clearAndDeleteContents(), Mixer::ChannelConfig::config(), QmlObjectListModel::count(), Mixer::MixerParameter::function, groupsChanged(), QmlObjectListModel::insert(), Mixer::MixerParameter::param, Mixer::Rule::selectIdentifier, Mixer::MixerConfigGroup::setCountParam(), Mixer::Type, Mixer::Unspecified, and QmlObjectListModel::value().
Referenced by Actuators::parametersChanged(), and reset().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Mixer.h
src/Vehicle/Actuators/Mixer.cc