QGroundControl: LoggingCategoryTreeModel Class Reference
LoggingCategoryTreeModel Class Reference
#include <LoggingCategoryModel.h>
Public Types
enum class Roles { ShortNameRole = Qt::UserRole + 1 , FullNameRole , EnabledRole , LogLevelRole }
Public Member Functions
LoggingCategoryTreeModel (QObject *parent=nullptr)
~LoggingCategoryTreeModel () override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
QModelIndex parent (const QModelIndex &child) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
QHash< int, QByteArray > roleNames () const override
bool hasChildren (const QModelIndex &parent=QModelIndex()) const override
void insertCategory (const QStringList &pathSegments, const QString &fullCategory, QGCLoggingCategoryItem *item)
Detailed Description
Definition at line 90 of file LoggingCategoryModel.h.
Member Enumeration Documentation
Roles
enum class LoggingCategoryTreeModel::Roles strong
Enumerator
ShortNameRole
FullNameRole
EnabledRole
LogLevelRole
Definition at line 97 of file LoggingCategoryModel.h.
Constructor & Destructor Documentation
LoggingCategoryTreeModel()
LoggingCategoryTreeModel::LoggingCategoryTreeModel (QObject * parent = nullptr) explicit
Definition at line 122 of file LoggingCategoryModel.cc.
~LoggingCategoryTreeModel()
LoggingCategoryTreeModel::~LoggingCategoryTreeModel () override default
Member Function Documentation
columnCount()
int LoggingCategoryTreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 166 of file LoggingCategoryModel.cc.
References index(), and parent().
data()
QVariant LoggingCategoryTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 177 of file LoggingCategoryModel.cc.
References EnabledRole, FullNameRole, index(), LoggingCategoryTreeNode::item, LogLevelRole, and ShortNameRole.
flags()
Qt::ItemFlags LoggingCategoryTreeModel::flags (const QModelIndex & index) const override
Definition at line 235 of file LoggingCategoryModel.cc.
References index().
hasChildren()
bool LoggingCategoryTreeModel::hasChildren (const QModelIndex & parent = QModelIndex()) const override
Definition at line 172 of file LoggingCategoryModel.cc.
References LoggingCategoryTreeNode::children, and parent().
index()
QModelIndex LoggingCategoryTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override
Definition at line 134 of file LoggingCategoryModel.cc.
References index(), and parent().
Referenced by columnCount(), data(), flags(), index(), insertCategory(), parent(), roleNames(), and setData().
insertCategory()
void LoggingCategoryTreeModel::insertCategory (const QStringList & pathSegments, const QString & fullCategory, QGCLoggingCategoryItem * item)
Definition at line 304 of file LoggingCategoryModel.cc.
References LoggingCategoryTreeNode::children, EnabledRole, index(), LoggingCategoryTreeNode::item, QGCLoggingCategoryItem::logLevelChanged(), and LogLevelRole.
parent()
QModelIndex LoggingCategoryTreeModel::parent (const QModelIndex & child) const override
Definition at line 146 of file LoggingCategoryModel.cc.
References LoggingCategoryTreeNode::children, index(), and LoggingCategoryTreeNode::parent.
Referenced by columnCount(), hasChildren(), index(), and rowCount().
roleNames()
QHash< int, QByteArray > LoggingCategoryTreeModel::roleNames () const override
Definition at line 244 of file LoggingCategoryModel.cc.
References EnabledRole, FullNameRole, index(), LogLevelRole, and ShortNameRole.
rowCount()
int LoggingCategoryTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 161 of file LoggingCategoryModel.cc.
References LoggingCategoryTreeNode::children, and parent().
setData()
bool LoggingCategoryTreeModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 206 of file LoggingCategoryModel.cc.
References EnabledRole, index(), LoggingCategoryTreeNode::item, LogLevelRole, and QGCLoggingCategoryItem::setEnabled().
The documentation for this class was generated from the following files:
src/Utilities/Logging/LoggingCategoryModel.h
src/Utilities/Logging/LoggingCategoryModel.cc