QGroundControl: QGCAbstractState Class Reference
QGCAbstractState Class Reference
#include <QGCAbstractState.h>
Public Types
using EntryCallback = std::function< void()>
using ExitCallback = std::function< void()>
using EventHandler = std::function< bool(QEvent *)>
Signals
void advance ()
void error ()
Public Member Functions
QGCAbstractState (const QString &stateName, QState *parent)
QGCStateMachine * machine () const
Vehicle * vehicle () const
QString stateName () const
class StateContext * context () const
void setOnEntry (EntryCallback callback)
Set a callback to be invoked when the state is entered.
void setOnExit (ExitCallback callback)
Set a callback to be invoked when the state is exited.
void setCallbacks (EntryCallback onEntry, ExitCallback onExit=nullptr)
Set both entry and exit callbacks.
void setEventHandler (EventHandler handler)
Set a custom event handler for this state.
Protected Member Functions
virtual void onEnter ()
Override to perform actions on state entry.
virtual void onLeave ()
Override to perform actions on state exit.
void onEntry (QEvent *event) override
void onExit (QEvent *event) override
bool event (QEvent *event) override
Detailed Description
Lightweight base class for simple states.
When to use QGCAbstractState vs QGCState
Use QGCAbstractState when:
You want callback-driven entry/exit behavior
You want a lighter API surface than QGCState
Use QGCState when:
You need to add outgoing transitions using addTransition()
You need child states (hierarchical state machine)
You need local error state handling (setLocalErrorState())
You need property assignment support
Notes
Local error-state helpers are not provided; use registerState() for global error handling.
Definition at line 27 of file QGCAbstractState.h.
Member Typedef Documentation
EntryCallback
using QGCAbstractState::EntryCallback = std::function<void()>
Definition at line 33 of file QGCAbstractState.h.
EventHandler
using QGCAbstractState::EventHandler = std::function<bool(QEvent*)>
Definition at line 35 of file QGCAbstractState.h.
ExitCallback
using QGCAbstractState::ExitCallback = std::function<void()>
Definition at line 34 of file QGCAbstractState.h.
Constructor & Destructor Documentation
QGCAbstractState()
QGCAbstractState::QGCAbstractState (const QString & stateName, QState * parent)
Definition at line 5 of file QGCAbstractState.cc.
References stateName().
Member Function Documentation
advance
void QGCAbstractState::advance () signal
Referenced by DelayState::DelayState(), FunctionState::FunctionState(), ErrorHandlers::logAndContinue(), CircuitBreakerState::onEnter(), ProgressState::onEnter(), RollbackState::onEnter(), ParallelState::onEntry(), ShowAppMessageState::ShowAppMessageState(), and WaitStateBase::waitComplete().
context()
StateContext * QGCAbstractState::context () const
Get the state machine's context for inter-state data passing
Returns
Pointer to the context, or nullptr if not in a QGCStateMachine
Definition at line 21 of file QGCAbstractState.cc.
References machine().
error
void QGCAbstractState::error () signal
Referenced by CircuitBreakerState::onEnter(), RollbackState::onEnter(), SubMachineState::onEntry(), QGCState::setLocalErrorState(), and WaitStateBase::waitFailed().
event()
bool QGCAbstractState::event (QEvent * event) override protected
Definition at line 65 of file QGCAbstractState.cc.
References event().
Referenced by event(), ParallelState::onEntry(), onEntry(), SubMachineState::onEntry(), ParallelState::onExit(), onExit(), and SubMachineState::onExit().
machine()
QGCStateMachine * QGCAbstractState::machine () const
Definition at line 11 of file QGCAbstractState.cc.
Referenced by EventQueuedState::connectWaitSignal(), context(), WaitStateBase::restartWait(), stateName(), and vehicle().
onEnter()
virtual void QGCAbstractState::onEnter () inline protected virtual
Override to perform actions on state entry.
Reimplemented in ErrorRecoveryState, CircuitBreakerState, FallbackChainState, LoopState< T >, ProgressState, RetryState, RollbackState, and SequenceState.
Definition at line 73 of file QGCAbstractState.h.
Referenced by onEntry().
onEntry()
void QGCAbstractState::onEntry (QEvent * event) override protected
Definition at line 41 of file QGCAbstractState.cc.
References event(), onEnter(), and stateName().
Referenced by ParallelState::onEntry(), SubMachineState::onEntry(), and setCallbacks().
onExit()
void QGCAbstractState::onExit (QEvent * event) override protected
Definition at line 53 of file QGCAbstractState.cc.
References event(), onLeave(), and stateName().
Referenced by ParallelState::onExit(), SubMachineState::onExit(), and setCallbacks().
onLeave()
virtual void QGCAbstractState::onLeave () inline protected virtual
Override to perform actions on state exit.
Definition at line 76 of file QGCAbstractState.h.
Referenced by onExit().
setCallbacks()
void QGCAbstractState::setCallbacks (EntryCallback onEntry, ExitCallback onExit = nullptr)
Set both entry and exit callbacks.
Definition at line 35 of file QGCAbstractState.cc.
References onEntry(), and onExit().
setEventHandler()
void QGCAbstractState::setEventHandler (EventHandler handler) inline
Set a custom event handler for this state.
Definition at line 65 of file QGCAbstractState.h.
setOnEntry()
void QGCAbstractState::setOnEntry (EntryCallback callback) inline
Set a callback to be invoked when the state is entered.
Definition at line 52 of file QGCAbstractState.h.
setOnExit()
void QGCAbstractState::setOnExit (ExitCallback callback) inline
Set a callback to be invoked when the state is exited.
Definition at line 55 of file QGCAbstractState.h.
stateName()
QString QGCAbstractState::stateName () const
Definition at line 26 of file QGCAbstractState.cc.
References machine().
Referenced by DelayState::DelayState(), CircuitBreakerState::onEnter(), RollbackState::onEnter(), ParallelState::onEntry(), onEntry(), SubMachineState::onEntry(), ParallelState::onExit(), onExit(), SubMachineState::onExit(), AsyncFunctionState::onWaitEntered(), EventQueuedState::onWaitEntered(), RequestMessageState::onWaitEntered(), RetryableRequestMessageState::onWaitEntered(), SkippableAsyncState::onWaitEntered(), RequestMessageState::onWaitTimeout(), RetryableRequestMessageState::onWaitTimeout(), QGCAbstractState(), CircuitBreakerState::reset(), QGCState::setLocalErrorState(), and ShowAppMessageState::ShowAppMessageState().
vehicle()
Vehicle * QGCAbstractState::vehicle () const
Definition at line 16 of file QGCAbstractState.cc.
References machine().
Referenced by SendMavlinkCommandState::connectWaitSignal(), WaitForMavlinkMessageState::connectWaitSignal(), SendMavlinkCommandState::disconnectWaitSignal(), WaitForMavlinkMessageState::disconnectWaitSignal(), RequestMessageState::onWaitEntered(), and SendMavlinkCommandState::onWaitEntered().
The documentation for this class was generated from the following files:
src/Utilities/StateMachine/States/QGCAbstractState.h
src/Utilities/StateMachine/States/QGCAbstractState.cc