QGroundControl: VehicleLinkManager Class Reference
VehicleLinkManager Class Reference
#include <VehicleLinkManager.h>
Signals
void primaryLinkChanged ()
void allLinksRemoved (Vehicle *vehicle)
void communicationLostChanged (bool communicationLost)
void communicationLostEnabledChanged (bool communicationLostEnabled)
void linkNamesChanged ()
void linkStatusesChanged ()
void autoDisconnectChanged (bool autoDisconnect)
Public Member Functions
VehicleLinkManager (Vehicle *vehicle)
~VehicleLinkManager ()
void mavlinkMessageReceived (LinkInterface *link, const mavlink_message_t &message)
bool containsLink (LinkInterface *link)
WeakLinkInterfacePtr primaryLink () const
QString primaryLinkName () const
QStringList linkNames () const
QStringList linkStatuses () const
bool communicationLost () const
bool communicationLostEnabled () const
void setPrimaryLinkByName (const QString &name)
void setCommunicationLostEnabled (bool communicationLostEnabled)
void closeVehicle ()
Static Public Attributes
static constexpr int kTestHeartbeatTimeoutMs = 500
Heartbeat timeout used in unit tests (much shorter for faster tests)
static constexpr int kTestCommLostDetectionTimeoutMs = _commLostCheckTimeoutMSecs + kTestHeartbeatTimeoutMs + 500
Detailed Description
Definition at line 17 of file VehicleLinkManager.h.
Constructor & Destructor Documentation
VehicleLinkManager()
VehicleLinkManager::VehicleLinkManager (Vehicle * vehicle)
Definition at line 13 of file VehicleLinkManager.cc.
References linkNamesChanged(), and linkStatusesChanged().
~VehicleLinkManager()
VehicleLinkManager::~VehicleLinkManager ()
Definition at line 27 of file VehicleLinkManager.cc.
Member Function Documentation
allLinksRemoved
void VehicleLinkManager::allLinksRemoved (Vehicle * vehicle) signal
Referenced by closeVehicle().
autoDisconnectChanged
void VehicleLinkManager::autoDisconnectChanged (bool autoDisconnect) signal
closeVehicle()
void VehicleLinkManager::closeVehicle ()
Definition at line 353 of file VehicleLinkManager.cc.
References allLinksRemoved().
communicationLost()
bool VehicleLinkManager::communicationLost () const inline
Definition at line 45 of file VehicleLinkManager.h.
communicationLostChanged
void VehicleLinkManager::communicationLostChanged (bool communicationLost) signal
communicationLostEnabled()
bool VehicleLinkManager::communicationLostEnabled () const inline
Definition at line 46 of file VehicleLinkManager.h.
Referenced by setCommunicationLostEnabled().
communicationLostEnabledChanged
void VehicleLinkManager::communicationLostEnabledChanged (bool communicationLostEnabled) signal
Referenced by setCommunicationLostEnabled().
containsLink()
bool VehicleLinkManager::containsLink (LinkInterface * link)
Definition at line 379 of file VehicleLinkManager.cc.
linkNames()
QStringList VehicleLinkManager::linkNames () const
Definition at line 403 of file VehicleLinkManager.cc.
linkNamesChanged
void VehicleLinkManager::linkNamesChanged () signal
Referenced by VehicleLinkManager().
linkStatuses()
QStringList VehicleLinkManager::linkStatuses () const
Definition at line 414 of file VehicleLinkManager.cc.
linkStatusesChanged
void VehicleLinkManager::linkStatusesChanged () signal
Referenced by VehicleLinkManager().
mavlinkMessageReceived()
void VehicleLinkManager::mavlinkMessageReceived (LinkInterface * link, const mavlink_message_t & message)
Definition at line 32 of file VehicleLinkManager.cc.
primaryLink()
WeakLinkInterfacePtr VehicleLinkManager::primaryLink () const inline
Definition at line 41 of file VehicleLinkManager.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), Vehicle::_sendMavCommandFromList(), Vehicle::_sendMavCommandWorker(), PlanManager::_writeMissionCount(), Vehicle::clearAllParamMapRC(), LogDownloadController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), PlanMasterController::loadFromVehicle(), RequestMessageState::onWaitEntered(), QGCCameraParamIO::paramRequest(), ParameterManager::refreshAllParameters(), Vehicle::requestDataStream(), APMFirmwarePlugin::sendGCSMotionReport(), FirmwarePlugin::sendGCSMotionReport(), Vehicle::sendJoystickDataThreadSafe(), Vehicle::sendParamMapRC(), Vehicle::sendSetupSigning(), PlanMasterController::sendToVehicle(), Vehicle::setCurrentMissionSequence(), Vehicle::setEstimatorOrigin(), Vehicle::setFlightMode(), Vehicle::startCalibration(), SensorsComponentController::usingUDPLink(), and MissionManager::writeArduPilotGuidedMissionItem().
primaryLinkChanged
void VehicleLinkManager::primaryLinkChanged () signal
Referenced by setPrimaryLinkByName().
primaryLinkName()
QString VehicleLinkManager::primaryLinkName () const
Definition at line 384 of file VehicleLinkManager.cc.
setCommunicationLostEnabled()
void VehicleLinkManager::setCommunicationLostEnabled (bool communicationLostEnabled)
Definition at line 371 of file VehicleLinkManager.cc.
References communicationLostEnabled(), and communicationLostEnabledChanged().
setPrimaryLinkByName()
void VehicleLinkManager::setPrimaryLinkByName (const QString & name)
Definition at line 393 of file VehicleLinkManager.cc.
References primaryLinkChanged().
Member Data Documentation
kTestCommLostDetectionTimeoutMs
constexpr int VehicleLinkManager::kTestCommLostDetectionTimeoutMs = _commLostCheckTimeoutMSecs + kTestHeartbeatTimeoutMs + 500 static constexpr
Full comm loss detection timeout for tests: accounts for timer interval + heartbeat timeout + margin. Use this in tests waiting for communicationLostChanged or linkStatusesChanged signals.
Definition at line 96 of file VehicleLinkManager.h.
kTestHeartbeatTimeoutMs
constexpr int VehicleLinkManager::kTestHeartbeatTimeoutMs = 500 static constexpr
Heartbeat timeout used in unit tests (much shorter for faster tests)
Definition at line 92 of file VehicleLinkManager.h.
The documentation for this class was generated from the following files:
src/Vehicle/VehicleLinkManager.h
src/Vehicle/VehicleLinkManager.cc