QGroundControl: RallyPointController Class Reference
RallyPointController Class Reference
#include <RallyPointController.h>
Signals
void currentRallyPointChanged (QObject *rallyPoint)
void loadComplete (void)
Signals inherited from PlanElementController
void supportedChanged (bool supported)
void containsItemsChanged ()
void syncInProgressChanged (bool syncInProgress)
void dirtyChanged (bool dirty)
void sendComplete (void)
void removeAllComplete (void)
Public Member Functions
RallyPointController (PlanMasterController *masterController, QObject *parent=nullptr)
~RallyPointController ()
QmlObjectListModel *points READ points CONSTANT (QString editorQml READ editorQml CONSTANT) 1(QObject *currentRallyPoint READ currentRallyPoint WRITE setCurrentRallyPoint NOTIFY currentRallyPointChanged) 1 void addPoint(QGeoCoordinate point)
void removePoint (QObject *rallyPoint)
void start (bool flyView) final
Should be called immediately upon Component.onCompleted.
bool supported (void) const final
true: controller is waiting for the current load to complete
void save (QJsonObject &json) final
bool load (const QJsonObject &json, QString &errorString) final
void loadFromVehicle (void) final
void sendToVehicle (void) final
void removeAll (void) final
Removes all from controller only.
void removeAllFromVehicle (void) final
bool syncInProgress (void) const final
bool dirty (void) const final
void setDirty (bool dirty) final
bool containsItems (void) const final
bool showPlanFromManagerVehicle (void) final
QmlObjectListModel * points (void)
QString editorQml (void) const
QObject * currentRallyPoint (void) const
void setCurrentRallyPoint (QObject *rallyPoint)
bool isEmpty (void) const
Public Member Functions inherited from PlanElementController
PlanElementController (PlanMasterController *masterController, QObject *parent=nullptr)
~PlanElementController ()
PlanMasterController *masterController READ masterController CONSTANT (bool supported READ supported NOTIFY supportedChanged) 1(bool containsItems READ containsItems NOTIFY containsItemsChanged) 1(bool syncInProgress READ syncInProgress NOTIFY syncInProgressChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) PlanMasterController *masterController(void)
< true: Elemement is non-empty
Additional Inherited Members
Protected Attributes inherited from PlanElementController
PlanMasterController * _masterController
bool _flyView
Detailed Description
Definition at line 16 of file RallyPointController.h.
Constructor & Destructor Documentation
RallyPointController()
RallyPointController::RallyPointController (PlanMasterController * masterController, QObject * parent = nullptr) explicit
Definition at line 16 of file RallyPointController.cc.
References PlanElementController::containsItemsChanged(), and ObjectItemModelBase::countChanged().
~RallyPointController()
RallyPointController::~RallyPointController ()
Definition at line 24 of file RallyPointController.cc.
Member Function Documentation
CONSTANT()
QmlObjectListModel *points READ points RallyPointController::CONSTANT (QString editorQml READ editorQml CONSTANT)
containsItems()
bool RallyPointController::containsItems (void) const final virtual
Implements PlanElementController.
Definition at line 284 of file RallyPointController.cc.
References QmlObjectListModel::count().
Referenced by PlanMasterController::containsItems().
currentRallyPoint()
QObject * RallyPointController::currentRallyPoint (void) const inline
Definition at line 48 of file RallyPointController.h.
currentRallyPointChanged
void RallyPointController::currentRallyPointChanged (QObject * rallyPoint) signal
Referenced by setCurrentRallyPoint().
dirty()
bool RallyPointController::dirty (void) const inline final virtual
Implements PlanElementController.
Definition at line 41 of file RallyPointController.h.
Referenced by setDirty().
editorQml()
QString RallyPointController::editorQml (void) const
Definition at line 186 of file RallyPointController.cc.
References RallyPointManager::editorQml().
isEmpty()
bool RallyPointController::isEmpty (void) const
Definition at line 313 of file RallyPointController.cc.
References QmlObjectListModel::count().
Referenced by PlanMasterController::isEmpty().
load()
bool RallyPointController::load (const QJsonObject & json, QString & errorString) final virtual
Implements PlanElementController.
Definition at line 68 of file RallyPointController.cc.
References errorString, JsonHelper::jsonVersionKey, JsonHelper::loadGeoCoordinateArray(), removeAll(), setDirty(), QmlObjectListModel::swapObjectList(), and JsonHelper::validateKeys().
Referenced by PlanMasterController::loadFromFile().
loadComplete
void RallyPointController::loadComplete (void) signal
loadFromVehicle()
void RallyPointController::loadFromVehicle (void) final virtual
Implements PlanElementController.
Definition at line 144 of file RallyPointController.cc.
References PlanElementController::_masterController, PlanManager::loadFromVehicle(), PlanMasterController::offline(), and syncInProgress().
points()
QmlObjectListModel * RallyPointController::points (void) inline
Definition at line 46 of file RallyPointController.h.
removeAll()
void RallyPointController::removeAll (void) final virtual
Removes all from controller only.
Implements PlanElementController.
Definition at line 126 of file RallyPointController.cc.
References QmlObjectListModel::clearAndDeleteContents(), setCurrentRallyPoint(), and setDirty().
Referenced by load(), and PlanMasterController::removeAll().
removeAllFromVehicle()
void RallyPointController::removeAllFromVehicle (void) final virtual
Removes all from vehicle and controller Signals removeAllComplete when done
Implements PlanElementController.
Definition at line 133 of file RallyPointController.cc.
References PlanElementController::_masterController, PlanMasterController::offline(), RallyPointManager::removeAll(), and syncInProgress().
Referenced by PlanMasterController::removeAllFromVehicle().
removePoint()
void RallyPointController::removePoint (QObject * rallyPoint)
Definition at line 252 of file RallyPointController.cc.
References QmlObjectListModel::count(), QmlObjectListModel::removeOne(), and setCurrentRallyPoint().
save()
void RallyPointController::save (QJsonObject & json) final virtual
Implements PlanElementController.
Definition at line 113 of file RallyPointController.cc.
References QmlObjectListModel::count(), JsonHelper::jsonVersionKey, and JsonHelper::saveGeoCoordinate().
Referenced by PlanMasterController::saveToJson().
sendToVehicle()
void RallyPointController::sendToVehicle (void) final virtual
Sends the current plan element to the vehicle Signals sendComplete when done
Implements PlanElementController.
Definition at line 156 of file RallyPointController.cc.
References PlanElementController::_masterController, QmlObjectListModel::count(), PlanMasterController::offline(), RallyPointManager::sendToVehicle(), setDirty(), and syncInProgress().
setCurrentRallyPoint()
void RallyPointController::setCurrentRallyPoint (QObject * rallyPoint)
Definition at line 271 of file RallyPointController.cc.
References currentRallyPointChanged().
Referenced by removeAll(), and removePoint().
setDirty()
void RallyPointController::setDirty (bool dirty) final virtual
Implements PlanElementController.
Definition at line 178 of file RallyPointController.cc.
References dirty(), and PlanElementController::dirtyChanged().
Referenced by load(), PlanMasterController::removeAll(), removeAll(), and sendToVehicle().
showPlanFromManagerVehicle()
bool RallyPointController::showPlanFromManagerVehicle (void) final virtual
Implements PlanElementController.
Definition at line 289 of file RallyPointController.cc.
References PlanElementController::_flyView, PlanElementController::_masterController, Vehicle::initialPlanRequestComplete(), PlanMasterController::offline(), and syncInProgress().
start()
void RallyPointController::start (bool flyView) final virtual
Should be called immediately upon Component.onCompleted.
Reimplemented from PlanElementController.
Definition at line 29 of file RallyPointController.cc.
References PlanElementController::_masterController, PlanMasterController::managerVehicle(), PlanMasterController::managerVehicleChanged(), and PlanElementController::start().
Referenced by PlanMasterController::startStaticActiveVehicle().
supported()
bool RallyPointController::supported (void) const final virtual
true: controller is waiting for the current load to complete
Implements PlanElementController.
Definition at line 247 of file RallyPointController.cc.
References Vehicle::capabilityBits().
Referenced by PlanMasterController::removeAllFromVehicle().
syncInProgress()
bool RallyPointController::syncInProgress (void) const final virtual
Implements PlanElementController.
Definition at line 173 of file RallyPointController.cc.
References PlanManager::inProgress().
Referenced by loadFromVehicle(), removeAllFromVehicle(), sendToVehicle(), showPlanFromManagerVehicle(), and PlanMasterController::syncInProgress().
The documentation for this class was generated from the following files:
src/MissionManager/RallyPointController.h
src/MissionManager/RallyPointController.cc