QGroundControl: TerrainAtCoordinateBatchManager Class Reference
TerrainAtCoordinateBatchManager Class Reference
#include <TerrainQuery.h>
Public Member Functions
TerrainAtCoordinateBatchManager (QObject *parent=nullptr)
~TerrainAtCoordinateBatchManager ()
void addQuery (TerrainAtCoordinateQuery *terrainAtCoordinateQuery, const QList< QGeoCoordinate > &coordinates)
void setTerrainQueryInterface (TerrainQueryInterface *terrainQuery)
Set custom terrain query interface (for testing). Takes ownership.
Static Public Member Functions
static TerrainAtCoordinateBatchManager * instance ()
Detailed Description
Definition at line 30 of file TerrainQuery.h.
Constructor & Destructor Documentation
TerrainAtCoordinateBatchManager()
TerrainAtCoordinateBatchManager::TerrainAtCoordinateBatchManager (QObject * parent = nullptr) explicit
Definition at line 13 of file TerrainQuery.cc.
References TerrainQueryInterface::coordinateHeightsReceived().
~TerrainAtCoordinateBatchManager()
TerrainAtCoordinateBatchManager::~TerrainAtCoordinateBatchManager ()
Definition at line 27 of file TerrainQuery.cc.
Member Function Documentation
addQuery()
void TerrainAtCoordinateBatchManager::addQuery (TerrainAtCoordinateQuery * terrainAtCoordinateQuery, const QList< QGeoCoordinate > & coordinates)
Definition at line 37 of file TerrainQuery.cc.
Referenced by TerrainAtCoordinateQuery::requestData().
instance()
TerrainAtCoordinateBatchManager * TerrainAtCoordinateBatchManager::instance () static
Definition at line 32 of file TerrainQuery.cc.
Referenced by TerrainAtCoordinateQuery::requestData().
setTerrainQueryInterface()
void TerrainAtCoordinateBatchManager::setTerrainQueryInterface (TerrainQueryInterface * terrainQuery)
Set custom terrain query interface (for testing). Takes ownership.
Definition at line 54 of file TerrainQuery.cc.
References TerrainQueryInterface::coordinateHeightsReceived().
The documentation for this class was generated from the following files:
src/Terrain/TerrainQuery.h
src/Terrain/TerrainQuery.cc