QGroundControl: ComplexMissionItem Class Reference
ComplexMissionItem Class Reference abstract
#include <ComplexMissionItem.h>
Signals
void patternNameChanged (void)
void complexDistanceChanged (void)
void boundingCubeChanged (void)
void greatestDistanceToChanged (void)
void presetNamesChanged (void)
void isIncompleteChanged (void)
void minAMSLAltitudeChanged (void)
void maxAMSLAltitudeChanged (void)
void terrainCollisionChanged (bool terrainCollision)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
ComplexMissionItem (PlanMasterController *masterController, bool flyView)
const ComplexMissionItem & operator= (const ComplexMissionItem &other)
QString patternName READ patternName NOTIFY patternNameChanged (double complexDistance READ complexDistance NOTIFY complexDistanceChanged) 1(bool presetsSupported READ presetsSupported CONSTANT) 1(QStringList presetNames READ presetNames NOTIFY presetNamesChanged) 1(bool isIncomplete READ isIncomplete NOTIFY isIncompleteChanged) 1(double minAMSLAltitude READ minAMSLAltitude NOTIFY minAMSLAltitudeChanged) 1(double maxAMSLAltitude READ maxAMSLAltitude NOTIFY maxAMSLAltitudeChanged) 1(bool isSingleItem READ isSingleItem CONSTANT) 1(QmlObjectListModel *flightPathSegments READ flightPathSegments CONSTANT) 1(bool terrainCollision READ terrainCollision NOTIFY terrainCollisionChanged) QmlObjectListModel *flightPathSegments(void)
< Minimum altitude of all coordinates in item
virtual QString patternName (void) const =0
virtual bool terrainCollision (void) const
virtual double minAMSLAltitude (void) const =0
virtual double maxAMSLAltitude (void) const =0
virtual double complexDistance (void) const =0
virtual bool load (const QJsonObject &complexObject, int sequenceNumber, QString &errorString)=0
virtual bool isSingleItem (void) const
virtual void loadPreset (const QString &name)
virtual void savePreset (const QString &name)
void deletePreset (const QString &name)
virtual double greatestDistanceTo (const QGeoCoordinate &other) const =0
virtual QStringList presetNames (void)
virtual QString presetsSettingsGroup (void)
virtual void addKMLVisuals (KMLPlanDomDocument &domDocument)
bool presetsSupported (void)
bool isIncomplete (void) const
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool dirty (void) const =0
virtual bool isSimpleItem (void) const =0
virtual bool isTakeoffItem (void) const
virtual bool isLandCommand (void) const
virtual bool isSurveyItem (void) const
virtual bool isStandaloneCoordinate (void) const =0
virtual bool specifiesCoordinate (void) const =0
virtual bool specifiesAltitudeOnly (void) const =0
virtual QString commandDescription (void) const =0
virtual QString commandName (void) const =0
virtual QString abbreviation (void) const =0
virtual QGeoCoordinate coordinate (void) const =0
virtual QGeoCoordinate entryCoordinate (void) const =0
virtual QGeoCoordinate exitCoordinate (void) const =0
virtual double editableAlt (void) const =0
virtual double amslEntryAlt (void) const =0
virtual double amslExitAlt (void) const =0
virtual int sequenceNumber (void) const =0
virtual double specifiedFlightSpeed (void)=0
virtual double specifiedGimbalYaw (void)=0
virtual double specifiedGimbalPitch (void)=0
virtual double specifiedVehicleYaw (void)
virtual QGCGeoBoundingCube * boundingCube (void)
virtual void setMissionFlightStatus (MissionController::MissionFlightStatus_t &missionFlightStatus)
virtual bool exitCoordinateSameAsEntry (void) const =0
virtual void setDirty (bool dirty)=0
virtual void setCoordinate (const QGeoCoordinate &coordinate)=0
virtual void setSequenceNumber (int sequenceNumber)=0
virtual int lastSequenceNumber (void) const =0
virtual ReadyForSaveState readyForSaveState (void) const
virtual void save (QJsonArray &missionItems)=0
virtual QString mapVisualQML (void) const =0
virtual void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent)=0
virtual void applyNewAltitude (double newAltitude)=0
Adjust the altitude of the item if appropriate to the new altitude.
virtual double additionalTimeDelay (void) const =0
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Static Public Attributes
static constexpr const char * jsonComplexItemTypeKey = "complexItemType"
This mission item attribute specifies the type of the complex item.
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Slots
virtual void _segmentTerrainCollisionChanged (bool terrainCollision)
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions
void _savePresetJson (const QString &name, QJsonObject &presetObject)
QJsonObject _loadPresetJson (const QString &name)
void _appendFlightPathSegment (FlightPathSegment::SegmentType segmentType, const QGeoCoordinate &coord1, double coord1AMSLAlt, const QGeoCoordinate &coord2, double coord2AMSLAlt)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Protected Attributes
bool _isIncomplete = true
int _cTerrainCollisionSegments = 0
QmlObjectListModel _flightPathSegments
QMap< QString, FactMetaData * > _metaDataMap
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Static Protected Attributes
static constexpr const char * _presetSettingsKey = "_presets"
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Detailed Description
Definition at line 11 of file ComplexMissionItem.h.
Constructor & Destructor Documentation
ComplexMissionItem()
ComplexMissionItem::ComplexMissionItem (PlanMasterController * masterController, bool flyView)
Definition at line 14 of file ComplexMissionItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::_amslExitAltChanged(), VisualMissionItem::_missionController, maxAMSLAltitudeChanged(), minAMSLAltitudeChanged(), and MissionController::plannedHomePositionChanged().
Member Function Documentation
_appendFlightPathSegment()
void ComplexMissionItem::_appendFlightPathSegment (FlightPathSegment::SegmentType segmentType, const QGeoCoordinate & coord1, double coord1AMSLAlt, const QGeoCoordinate & coord2, double coord2AMSLAlt) protected
Definition at line 109 of file ComplexMissionItem.cc.
References _flightPathSegments, VisualMissionItem::_missionController, _segmentTerrainCollisionChanged(), FlightPathSegment::amslTerrainHeights(), FlightPathSegment::amslTerrainHeightsChanged(), QmlObjectListModel::append(), MissionController::recalcTerrainProfile(), FlightPathSegment::terrainCollision(), and FlightPathSegment::terrainCollisionChanged().
_loadPresetJson()
QJsonObject ComplexMissionItem::_loadPresetJson (const QString & name) protected
Definition at line 96 of file ComplexMissionItem.cc.
References _presetSettingsKey, and presetsSettingsGroup().
Referenced by CorridorScanComplexItem::loadPreset(), and SurveyComplexItem::loadPreset().
_savePresetJson()
void ComplexMissionItem::_savePresetJson (const QString & name, QJsonObject & presetObject) protected
Definition at line 67 of file ComplexMissionItem.cc.
References _presetSettingsKey, presetNamesChanged(), and presetsSettingsGroup().
Referenced by CorridorScanComplexItem::savePreset(), and SurveyComplexItem::savePreset().
_segmentTerrainCollisionChanged
void ComplexMissionItem::_segmentTerrainCollisionChanged (bool terrainCollision) protected virtual slot
Definition at line 129 of file ComplexMissionItem.cc.
References _cTerrainCollisionSegments, terrainCollision(), and terrainCollisionChanged().
Referenced by _appendFlightPathSegment().
addKMLVisuals()
void ComplexMissionItem::addKMLVisuals (KMLPlanDomDocument & domDocument) virtual
Reimplemented in TransectStyleComplexItem.
Definition at line 104 of file ComplexMissionItem.cc.
boundingCubeChanged
void ComplexMissionItem::boundingCubeChanged (void) signal
complexDistance()
virtual double ComplexMissionItem::complexDistance (void) const pure virtual
Returns
The distance covered the complex mission item in meters. Signals complexDistanceChanged
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::recalc(), and TerrainProfile::updatePaintNode().
complexDistanceChanged
void ComplexMissionItem::complexDistanceChanged (void) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_recalcComplexDistance(), and TransectStyleComplexItem::TransectStyleComplexItem().
deletePreset()
void ComplexMissionItem::deletePreset (const QString & name)
Definition at line 53 of file ComplexMissionItem.cc.
References _presetSettingsKey, presetNamesChanged(), presetsSettingsGroup(), and qgcApp.
greatestDistanceTo()
virtual double ComplexMissionItem::greatestDistanceTo (const QGeoCoordinate & other) const pure virtual
Get the point of complex mission item furthest away from a coordinate
Parameters
other QGeoCoordinate to which distance is calculated
Returns
the greatest distance from any point of the complex item to some coordinate Signals greatestDistanceToChanged
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::recalc().
greatestDistanceToChanged
void ComplexMissionItem::greatestDistanceToChanged (void) signal
Referenced by TransectStyleComplexItem::TransectStyleComplexItem().
isIncomplete()
bool ComplexMissionItem::isIncomplete (void) const inline
Definition at line 86 of file ComplexMissionItem.h.
References _isIncomplete.
isIncompleteChanged
void ComplexMissionItem::isIncompleteChanged (void) signal
Referenced by TransectStyleComplexItem::_rebuildTransects().
isSingleItem()
virtual bool ComplexMissionItem::isSingleItem (void) const inline virtual
Returns
true: Represents a single coordinate (ex: MissionSettingsItem), false: Represents multiple items (ex: Survey)
Reimplemented in MissionSettingsItem.
Definition at line 56 of file ComplexMissionItem.h.
load()
virtual bool ComplexMissionItem::load (const QJsonObject & complexObject, int sequenceNumber, QString & errorString) pure virtual
Load the complex mission item from Json
Parameters
complexObject Complex mission item json object
sequenceNumber Sequence number for first MISSION_ITEM in survey
[out] errorString Error if load fails
Returns
true: load success, false: load failed, errorString set
Implemented in CorridorScanComplexItem, FixedWingLandingComplexItem, MissionSettingsItem, StructureScanComplexItem, SurveyComplexItem, VTOLLandingComplexItem, and TransectStyleComplexItem.
loadPreset()
void ComplexMissionItem::loadPreset (const QString & name) virtual
Loads the specified preset into the complex item.
Parameters
name Preset name.
Reimplemented in CorridorScanComplexItem, and SurveyComplexItem.
Definition at line 41 of file ComplexMissionItem.cc.
References qgcApp.
maxAMSLAltitude()
virtual double ComplexMissionItem::maxAMSLAltitude (void) const pure virtual
Returns
Maximum altitude for the items within this complex items.
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::recalc().
maxAMSLAltitudeChanged
void ComplexMissionItem::maxAMSLAltitudeChanged (void) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), ComplexMissionItem(), MissionSettingsItem::MissionSettingsItem(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
minAMSLAltitude()
virtual double ComplexMissionItem::minAMSLAltitude (void) const pure virtual
Returns
Minimum altitude for the items within this complex items.
Implemented in LandingComplexItem, MissionSettingsItem, StructureScanComplexItem, and TransectStyleComplexItem.
Referenced by MissionFlightStatusCalculator::recalc().
minAMSLAltitudeChanged
void ComplexMissionItem::minAMSLAltitudeChanged (void) signal
Referenced by LandingComplexItem::_init(), TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), ComplexMissionItem(), MissionSettingsItem::MissionSettingsItem(), StructureScanComplexItem::StructureScanComplexItem(), and TransectStyleComplexItem::TransectStyleComplexItem().
operator=()
const ComplexMissionItem & ComplexMissionItem::operator= (const ComplexMissionItem & other)
Definition at line 23 of file ComplexMissionItem.cc.
References VisualMissionItem::operator=().
patternName()
virtual QString ComplexMissionItem::patternName (void) const pure virtual
Implemented in CorridorScanComplexItem, FixedWingLandingComplexItem, MissionSettingsItem, StructureScanComplexItem, SurveyComplexItem, and VTOLLandingComplexItem.
patternNameChanged() [1/2]
QString patternName READ patternName NOTIFY ComplexMissionItem::patternNameChanged (double complexDistance READ complexDistance NOTIFY complexDistanceChanged) inline
< Minimum altitude of all coordinates in item
< Maximum altitude of all coordinates in item
Definition at line 20 of file ComplexMissionItem.h.
References _flightPathSegments.
patternNameChanged [2/2]
void ComplexMissionItem::patternNameChanged (void) signal
Referenced by LandingComplexItem::_init().
presetNames()
QStringList ComplexMissionItem::presetNames (void) virtual
Returns the list of currently saved presets for this complex item type.
Parameters
name User visible name for preset. Will replace existing preset if already exists.
Definition at line 30 of file ComplexMissionItem.cc.
References _presetSettingsKey, and presetsSettingsGroup().
presetNamesChanged
void ComplexMissionItem::presetNamesChanged (void) signal
Referenced by _savePresetJson(), and deletePreset().
presetsSettingsGroup()
virtual QString ComplexMissionItem::presetsSettingsGroup (void) inline virtual
Returns the name of the settings group for presets. Empty string signals no support for presets.
Reimplemented in CorridorScanComplexItem, and SurveyComplexItem.
Definition at line 81 of file ComplexMissionItem.h.
Referenced by _loadPresetJson(), _savePresetJson(), deletePreset(), presetNames(), and presetsSupported().
presetsSupported()
bool ComplexMissionItem::presetsSupported (void) inline
Definition at line 85 of file ComplexMissionItem.h.
References presetsSettingsGroup().
savePreset()
void ComplexMissionItem::savePreset (const QString & name) virtual
Saves the current state of the complex item as the named preset.
Parameters
name User visible name for preset. Will replace existing preset if already exists.
Reimplemented in CorridorScanComplexItem, and SurveyComplexItem.
Definition at line 47 of file ComplexMissionItem.cc.
References qgcApp.
terrainCollision()
virtual bool ComplexMissionItem::terrainCollision (void) const inline virtual
Returns
true: This complex item is colliding with terrain
Reimplemented in MissionSettingsItem.
Definition at line 36 of file ComplexMissionItem.h.
References _cTerrainCollisionSegments.
Referenced by _segmentTerrainCollisionChanged().
terrainCollisionChanged
void ComplexMissionItem::terrainCollisionChanged (bool terrainCollision) signal
Referenced by _segmentTerrainCollisionChanged().
Member Data Documentation
_cTerrainCollisionSegments
int ComplexMissionItem::_cTerrainCollisionSegments = 0 protected
Definition at line 111 of file ComplexMissionItem.h.
Referenced by _segmentTerrainCollisionChanged(), and terrainCollision().
_flightPathSegments
QmlObjectListModel ComplexMissionItem::_flightPathSegments protected
Definition at line 112 of file ComplexMissionItem.h.
Referenced by _appendFlightPathSegment(), and patternNameChanged().
_isIncomplete
bool ComplexMissionItem::_isIncomplete = true protected
Definition at line 110 of file ComplexMissionItem.h.
Referenced by TransectStyleComplexItem::_load(), TransectStyleComplexItem::_rebuildTransects(), and isIncomplete().
_metaDataMap
QMap<QString, FactMetaData*> ComplexMissionItem::_metaDataMap protected
Definition at line 114 of file ComplexMissionItem.h.
_presetSettingsKey
constexpr const char* ComplexMissionItem::_presetSettingsKey = "_presets" static constexpr protected
Definition at line 116 of file ComplexMissionItem.h.
Referenced by _loadPresetJson(), _savePresetJson(), deletePreset(), and presetNames().
jsonComplexItemTypeKey
constexpr const char* ComplexMissionItem::jsonComplexItemTypeKey = "complexItemType" static constexpr
This mission item attribute specifies the type of the complex item.
Definition at line 89 of file ComplexMissionItem.h.
Referenced by LandingComplexItem::_load(), StructureScanComplexItem::load(), SurveyComplexItem::load(), FixedWingLandingComplexItem::save(), StructureScanComplexItem::save(), and VTOLLandingComplexItem::save().
The documentation for this class was generated from the following files:
src/MissionManager/ComplexMissionItem.h
src/MissionManager/ComplexMissionItem.cc