QGroundControl: RTKSettings Class Reference
RTKSettings Class Reference
#include <RTKSettings.h>
Public Member Functions
RTKSettings (QObject *parent=nullptr)
Fact *baseReceiverManufacturers READ baseReceiverManufacturers CONSTANT Fact * baseReceiverManufacturers ()
Fact *surveyInAccuracyLimit READ surveyInAccuracyLimit CONSTANT Fact * surveyInAccuracyLimit ()
Fact *surveyInMinObservationDuration READ surveyInMinObservationDuration CONSTANT Fact * surveyInMinObservationDuration ()
Fact *useFixedBasePosition READ useFixedBasePosition CONSTANT Fact * useFixedBasePosition ()
Fact *fixedBasePositionLatitude READ fixedBasePositionLatitude CONSTANT Fact * fixedBasePositionLatitude ()
Fact *fixedBasePositionLongitude READ fixedBasePositionLongitude CONSTANT Fact * fixedBasePositionLongitude ()
Fact *fixedBasePositionAltitude READ fixedBasePositionAltitude CONSTANT Fact * fixedBasePositionAltitude ()
Fact *fixedBasePositionAccuracy READ fixedBasePositionAccuracy CONSTANT Fact * fixedBasePositionAccuracy ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "RTK"
static const char * settingsGroup = "RTK"
static const char * baseReceiverManufacturersName = "baseReceiverManufacturers"
static const char * surveyInAccuracyLimitName = "surveyInAccuracyLimit"
static const char * surveyInMinObservationDurationName = "surveyInMinObservationDuration"
static const char * useFixedBasePositionName = "useFixedBasePosition"
static const char * fixedBasePositionLatitudeName = "fixedBasePositionLatitude"
static const char * fixedBasePositionLongitudeName = "fixedBasePositionLongitude"
static const char * fixedBasePositionAltitudeName = "fixedBasePositionAltitude"
static const char * fixedBasePositionAccuracyName = "fixedBasePositionAccuracy"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 24 of file RTKSettings.h.
Constructor & Destructor Documentation
RTKSettings()
RTKSettings::RTKSettings (QObject * parent = nullptr)
Definition at line 3 of file RTKSettings.cc.
Member Function Documentation
baseReceiverManufacturers()
Fact * RTKSettings::baseReceiverManufacturers ()
Definition at line 5 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
fixedBasePositionAccuracy()
Fact * RTKSettings::fixedBasePositionAccuracy ()
Definition at line 12 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
fixedBasePositionAltitude()
Fact * RTKSettings::fixedBasePositionAltitude ()
Definition at line 11 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
fixedBasePositionLatitude()
Fact * RTKSettings::fixedBasePositionLatitude ()
Definition at line 9 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
fixedBasePositionLongitude()
Fact * RTKSettings::fixedBasePositionLongitude ()
Definition at line 10 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
surveyInAccuracyLimit()
Fact * RTKSettings::surveyInAccuracyLimit ()
Definition at line 6 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
surveyInMinObservationDuration()
Fact * RTKSettings::surveyInMinObservationDuration ()
Definition at line 7 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
useFixedBasePosition()
Fact * RTKSettings::useFixedBasePosition ()
Definition at line 8 of file RTKSettings.cc.
Referenced by GPSRtk::connectGPS().
Member Data Documentation
baseReceiverManufacturersName
const char * RTKSettings::baseReceiverManufacturersName = "baseReceiverManufacturers" static
Definition at line 32 of file RTKSettings.h.
fixedBasePositionAccuracyName
const char * RTKSettings::fixedBasePositionAccuracyName = "fixedBasePositionAccuracy" static
Definition at line 39 of file RTKSettings.h.
fixedBasePositionAltitudeName
const char * RTKSettings::fixedBasePositionAltitudeName = "fixedBasePositionAltitude" static
Definition at line 38 of file RTKSettings.h.
fixedBasePositionLatitudeName
const char * RTKSettings::fixedBasePositionLatitudeName = "fixedBasePositionLatitude" static
Definition at line 36 of file RTKSettings.h.
fixedBasePositionLongitudeName
const char * RTKSettings::fixedBasePositionLongitudeName = "fixedBasePositionLongitude" static
Definition at line 37 of file RTKSettings.h.
name
const char * RTKSettings::name = "RTK" static
Definition at line 31 of file RTKSettings.h.
settingsGroup
const char * RTKSettings::settingsGroup = "RTK" static
Definition at line 31 of file RTKSettings.h.
surveyInAccuracyLimitName
const char * RTKSettings::surveyInAccuracyLimitName = "surveyInAccuracyLimit" static
Definition at line 33 of file RTKSettings.h.
surveyInMinObservationDurationName
const char * RTKSettings::surveyInMinObservationDurationName = "surveyInMinObservationDuration" static
Definition at line 34 of file RTKSettings.h.
useFixedBasePositionName
const char * RTKSettings::useFixedBasePositionName = "useFixedBasePosition" static
Definition at line 35 of file RTKSettings.h.
The documentation for this class was generated from the following files:
src/Settings/RTKSettings.h
src/Settings/RTKSettings.cc