QGroundControl: StandardModes Class Reference
StandardModes Class Reference
#include <StandardModes.h>
Classes
struct Mode
Signals
void modesUpdated ()
void requestCompleted ()
Public Member Functions
StandardModes (QObject *parent, Vehicle *vehicle)
void request ()
void availableModesMonitorReceived (uint8_t seq)
void gotMessage (MAV_RESULT result, const mavlink_message_t &message)
Detailed Description
Definition at line 16 of file StandardModes.h.
Constructor & Destructor Documentation
StandardModes()
StandardModes::StandardModes (QObject * parent, Vehicle * vehicle)
Definition at line 15 of file StandardModes.cc.
Member Function Documentation
availableModesMonitorReceived()
void StandardModes::availableModesMonitorReceived (uint8_t seq)
Definition at line 135 of file StandardModes.cc.
References request().
gotMessage()
void StandardModes::gotMessage (MAV_RESULT result, const mavlink_message_t & message)
Definition at line 20 of file StandardModes.cc.
References Vehicle::firmwarePlugin(), modesUpdated(), request(), requestCompleted(), FirmwareFlightMode::standard_mode, and FirmwarePlugin::updateAvailableFlightModes().
Referenced by requestMessageResultHandler().
modesUpdated
void StandardModes::modesUpdated () signal
Referenced by gotMessage().
request()
void StandardModes::request ()
Definition at line 111 of file StandardModes.cc.
Referenced by availableModesMonitorReceived(), and gotMessage().
requestCompleted
void StandardModes::requestCompleted () signal
Referenced by gotMessage().
The documentation for this class was generated from the following files:
src/Vehicle/StandardModes.h
src/Vehicle/StandardModes.cc