QGroundControl: NTRIPHttpTransport Class Reference
NTRIPHttpTransport Class Reference
#include <NTRIPHttpTransport.h>
Classes
struct HttpStatus
Signals
void connected ()
void error (const QString &errorMsg)
void RTCMDataUpdate (const QByteArray &message)
void finished ()
Public Member Functions
NTRIPHttpTransport (const NTRIPTransportConfig &config, QObject *parent=nullptr)
~NTRIPHttpTransport () override
void start ()
void stop ()
void sendNMEA (const QByteArray &nmea)
Static Public Attributes
static constexpr int kConnectTimeoutMs = 10000
static constexpr int kDataWatchdogMs = 30000
static constexpr int kMaxHttpHeaderSize = 32768
Static Protected Member Functions
static HttpStatus parseHttpStatusLine (const QString &line)
static QByteArray repairNmeaChecksum (const QByteArray &sentence)
static bool isHttpSuccess (int code)
Friends
class NTRIPHttpTransportTest
Detailed Description
Definition at line 31 of file NTRIPHttpTransport.h.
Constructor & Destructor Documentation
NTRIPHttpTransport()
NTRIPHttpTransport::NTRIPHttpTransport (const NTRIPTransportConfig & config, QObject * parent = nullptr) explicit
Definition at line 11 of file NTRIPHttpTransport.cc.
References error.
~NTRIPHttpTransport()
NTRIPHttpTransport::~NTRIPHttpTransport () override
Definition at line 46 of file NTRIPHttpTransport.cc.
References stop().
Member Function Documentation
connected
void NTRIPHttpTransport::connected () signal
error
void NTRIPHttpTransport::error (const QString & errorMsg) signal
finished
void NTRIPHttpTransport::finished () signal
Referenced by stop().
isHttpSuccess()
static bool NTRIPHttpTransport::isHttpSuccess (int code) inline static protected
Definition at line 63 of file NTRIPHttpTransport.h.
parseHttpStatusLine()
NTRIPHttpTransport::HttpStatus NTRIPHttpTransport::parseHttpStatusLine (const QString & line) static protected
Definition at line 354 of file NTRIPHttpTransport.cc.
repairNmeaChecksum()
QByteArray NTRIPHttpTransport::repairNmeaChecksum (const QByteArray & sentence) static protected
Definition at line 370 of file NTRIPHttpTransport.cc.
Referenced by sendNMEA().
RTCMDataUpdate
void NTRIPHttpTransport::RTCMDataUpdate (const QByteArray & message) signal
sendNMEA()
void NTRIPHttpTransport::sendNMEA (const QByteArray & nmea)
Definition at line 339 of file NTRIPHttpTransport.cc.
References repairNmeaChecksum().
start()
void NTRIPHttpTransport::start ()
Definition at line 51 of file NTRIPHttpTransport.cc.
stop()
void NTRIPHttpTransport::stop ()
Definition at line 57 of file NTRIPHttpTransport.cc.
References finished().
Referenced by ~NTRIPHttpTransport().
Friends And Related Symbol Documentation
NTRIPHttpTransportTest
friend class NTRIPHttpTransportTest friend
Definition at line 34 of file NTRIPHttpTransport.h.
Member Data Documentation
kConnectTimeoutMs
constexpr int NTRIPHttpTransport::kConnectTimeoutMs = 10000 static constexpr
Definition at line 37 of file NTRIPHttpTransport.h.
kDataWatchdogMs
constexpr int NTRIPHttpTransport::kDataWatchdogMs = 30000 static constexpr
Definition at line 38 of file NTRIPHttpTransport.h.
kMaxHttpHeaderSize
constexpr int NTRIPHttpTransport::kMaxHttpHeaderSize = 32768 static constexpr
Definition at line 39 of file NTRIPHttpTransport.h.
The documentation for this class was generated from the following files:
src/GPS/NTRIP/NTRIPHttpTransport.h
src/GPS/NTRIP/NTRIPHttpTransport.cc