QGroundControl: ObjectItemModelBase Class Reference
ObjectItemModelBase Class Reference abstract
#include <ObjectItemModelBase.h>
Signals
void countChanged (int count)
void dirtyChanged (bool dirty)
Public Member Functions
ObjectItemModelBase (QObject *parent=nullptr)
~ObjectItemModelBase () override
int count READ count NOTIFY countChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) bool dirty() const
void beginResetModel ()
Depth-counted beginResetModel — only the outermost call has effect.
void endResetModel ()
Depth-counted endResetModel — only the outermost call has effect.
virtual int count () const =0
virtual bool isEmpty () const
virtual void setDirty (bool dirty)=0
virtual void clear ()=0
Protected Slots
void _childDirtyChanged (bool dirty)
Protected Member Functions
QHash< int, QByteArray > roleNames () const override
void _signalCountChangedIfNotNested ()
Protected Attributes
bool _dirty = false
uint _resetModelNestingCount = 0
Static Protected Attributes
static constexpr int ObjectRole = Qt::UserRole
static constexpr int TextRole = Qt::UserRole + 1
Detailed Description
Common base for QObject*-based item models (flat lists and trees). Provides: dirty tracking, depth-counted begin/endResetModel, shared role constants, roleNames.
Definition at line 20 of file ObjectItemModelBase.h.
Constructor & Destructor Documentation
ObjectItemModelBase()
ObjectItemModelBase::ObjectItemModelBase (QObject * parent = nullptr) explicit
Definition at line 17 of file ObjectItemModelBase.cc.
~ObjectItemModelBase()
ObjectItemModelBase::~ObjectItemModelBase () override
Definition at line 23 of file ObjectItemModelBase.cc.
References _resetModelNestingCount.
Member Function Documentation
_childDirtyChanged
void ObjectItemModelBase::_childDirtyChanged (bool dirty) protected slot
Definition at line 38 of file ObjectItemModelBase.cc.
References _dirty, and dirtyChanged().
_signalCountChangedIfNotNested()
void ObjectItemModelBase::_signalCountChangedIfNotNested () protected
Definition at line 69 of file ObjectItemModelBase.cc.
References _resetModelNestingCount, count(), and countChanged().
Referenced by QmlObjectTreeModel::insertItem(), QmlObjectListModel::insertRows(), QmlObjectTreeModel::removeChildren(), QmlObjectTreeModel::removeItem(), and QmlObjectListModel::removeRows().
beginResetModel()
void ObjectItemModelBase::beginResetModel ()
Depth-counted beginResetModel — only the outermost call has effect.
Definition at line 44 of file ObjectItemModelBase.cc.
References _resetModelNestingCount.
Referenced by QGCMapPolygon::beginReset(), QGCMapPolyline::beginReset(), QmlObjectTreeModel::clear(), QmlObjectListModel::clear(), QmlObjectTreeModel::clearAndDeleteContents(), and QmlObjectListModel::swapObjectList().
clear()
virtual void ObjectItemModelBase::clear () pure virtual
Implemented in QmlObjectTreeModel, and QmlObjectListModel.
count()
virtual int ObjectItemModelBase::count () const pure virtual
Implemented in QmlObjectTreeModel, and QmlObjectListModel.
Referenced by _signalCountChangedIfNotNested(), and endResetModel().
countChanged() [1/2]
int count READ count NOTIFY ObjectItemModelBase::countChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) const inline
Definition at line 28 of file ObjectItemModelBase.h.
Referenced by _signalCountChangedIfNotNested(), endResetModel(), GeoFenceController::GeoFenceController(), and RallyPointController::RallyPointController().
countChanged [2/2]
void ObjectItemModelBase::countChanged (int count) signal
dirtyChanged
void ObjectItemModelBase::dirtyChanged (bool dirty) signal
Referenced by _childDirtyChanged(), GeoFenceController::GeoFenceController(), QmlObjectTreeModel::setDirty(), and QmlObjectListModel::setDirty().
endResetModel()
void ObjectItemModelBase::endResetModel ()
Depth-counted endResetModel — only the outermost call has effect.
Definition at line 54 of file ObjectItemModelBase.cc.
References _resetModelNestingCount, count(), and countChanged().
Referenced by QmlObjectTreeModel::clear(), QmlObjectListModel::clear(), QmlObjectTreeModel::clearAndDeleteContents(), QGCMapPolygon::endReset(), QGCMapPolyline::endReset(), and QmlObjectListModel::swapObjectList().
isEmpty()
virtual bool ObjectItemModelBase::isEmpty () const inline virtual
Reimplemented in QmlObjectListModel.
Definition at line 40 of file ObjectItemModelBase.h.
roleNames()
QHash< int, QByteArray > ObjectItemModelBase::roleNames () const override protected
Definition at line 30 of file ObjectItemModelBase.cc.
References ObjectRole, and TextRole.
Referenced by QmlObjectTreeModel::roleNames().
setDirty()
virtual void ObjectItemModelBase::setDirty (bool dirty) pure virtual
Implemented in QmlObjectTreeModel, and QmlObjectListModel.
Member Data Documentation
_dirty
bool ObjectItemModelBase::_dirty = false protected
Definition at line 55 of file ObjectItemModelBase.h.
Referenced by _childDirtyChanged(), QmlObjectTreeModel::setDirty(), and QmlObjectListModel::setDirty().
_resetModelNestingCount
uint ObjectItemModelBase::_resetModelNestingCount = 0 protected
Definition at line 56 of file ObjectItemModelBase.h.
Referenced by _signalCountChangedIfNotNested(), beginResetModel(), endResetModel(), QmlObjectTreeModel::insertItem(), QmlObjectListModel::insertRows(), QmlObjectTreeModel::removeChildren(), QmlObjectTreeModel::removeItem(), QmlObjectListModel::removeRows(), and ~ObjectItemModelBase().
ObjectRole
constexpr int ObjectItemModelBase::ObjectRole = Qt::UserRole static constexpr protected
Definition at line 58 of file ObjectItemModelBase.h.
Referenced by QmlObjectListModel::data(), QmlObjectTreeModel::data(), roleNames(), QmlObjectListModel::setData(), and QmlObjectTreeModel::setData().
TextRole
constexpr int ObjectItemModelBase::TextRole = Qt::UserRole + 1 static constexpr protected
Definition at line 59 of file ObjectItemModelBase.h.
Referenced by QmlObjectListModel::data(), QmlObjectTreeModel::data(), and roleNames().
The documentation for this class was generated from the following files:
src/QmlControls/ObjectItemModelBase.h
src/QmlControls/ObjectItemModelBase.cc