QGroundControl: HealthAndArmingCheckProblem Class Reference
HealthAndArmingCheckProblem Class Reference
#include <HealthAndArmingCheckReport.h>
Signals
void expandedChanged ()
Public Member Functions
HealthAndArmingCheckProblem (const QString &message, const QString &description, const QString &severity)
QString message READ message CONSTANT (QString description READ description CONSTANT) 1(QString severity READ severity CONSTANT) 1(bool expanded READ expanded WRITE setExpanded NOTIFY expandedChanged) const QString &message() const
const QString & description () const
const QString & severity () const
bool expanded () const
void setExpanded (bool expanded)
Detailed Description
Definition at line 10 of file HealthAndArmingCheckReport.h.
Constructor & Destructor Documentation
HealthAndArmingCheckProblem()
HealthAndArmingCheckProblem::HealthAndArmingCheckProblem (const QString & message, const QString & description, const QString & severity) inline
Definition at line 14 of file HealthAndArmingCheckReport.h.
Member Function Documentation
CONSTANT()
QString message READ message HealthAndArmingCheckProblem::CONSTANT (QString description READ description CONSTANT) const & inline
Definition at line 17 of file HealthAndArmingCheckReport.h.
description()
const QString & HealthAndArmingCheckProblem::description () const inline
Definition at line 23 of file HealthAndArmingCheckReport.h.
expanded()
bool HealthAndArmingCheckProblem::expanded () const inline
Definition at line 26 of file HealthAndArmingCheckReport.h.
Referenced by setExpanded().
expandedChanged
void HealthAndArmingCheckProblem::expandedChanged () signal
Referenced by setExpanded().
setExpanded()
void HealthAndArmingCheckProblem::setExpanded (bool expanded) inline
Definition at line 27 of file HealthAndArmingCheckReport.h.
References expanded(), and expandedChanged().
severity()
const QString & HealthAndArmingCheckProblem::severity () const inline
Definition at line 24 of file HealthAndArmingCheckReport.h.
The documentation for this class was generated from the following file:
src/MAVLink/LibEvents/HealthAndArmingCheckReport.h