QGroundControl: QGCLoggingCategoryManager Class Reference
QGCLoggingCategoryManager Class Reference
#include <QGCLoggingCategory.h>
Public Slots
void setCategoryLoggingOn (const QString &fullCategoryName, bool enable)
Turns on/off logging for the specified category. State is saved in app settings.
Public Member Functions
void registerCategory (const QString &category)
Registers the specified logging category to the system.
QmlObjectListModel * treeCategoryModel ()
Returns the hierarchical list of available logging category names.
QmlObjectListModel * flatCategoryModel ()
Returns the flat list of available logging category names.
void setFilterRulesFromSettings (const QString &commandLineLoggingOptions)
void disableAllCategories ()
Static Public Member Functions
static QGCLoggingCategoryManager * instance ()
static bool categoryLoggingOn (const QString &fullCategroryName)
Returns true if logging is turned on for the specified category.
Detailed Description
Definition at line 22 of file QGCLoggingCategory.h.
Member Function Documentation
categoryLoggingOn()
bool QGCLoggingCategoryManager::categoryLoggingOn (const QString & fullCategroryName) static
Returns true if logging is turned on for the specified category.
Definition at line 83 of file QGCLoggingCategory.cc.
Referenced by QGroundControlQmlGlobal::categoryLoggingOn().
disableAllCategories()
void QGCLoggingCategoryManager::disableAllCategories ()
Definition at line 152 of file QGCLoggingCategory.cc.
References QmlObjectListModel::count(), QmlObjectListModel::get(), and setFilterRulesFromSettings().
Referenced by QGroundControlQmlGlobal::disableAllLoggingCategories().
flatCategoryModel()
QmlObjectListModel * QGCLoggingCategoryManager::flatCategoryModel () inline
Returns the flat list of available logging category names.
Definition at line 36 of file QGCLoggingCategory.h.
Referenced by QGroundControlQmlGlobal::flatLoggingCategoriesModel().
instance()
QGCLoggingCategoryManager * QGCLoggingCategoryManager::instance () static
Definition at line 10 of file QGCLoggingCategory.cc.
References _QGCLoggingCategoryManagerInstance.
Referenced by QGroundControlQmlGlobal::disableAllLoggingCategories(), QGroundControlQmlGlobal::flatLoggingCategoriesModel(), QGCApplication::QGCApplication(), QGCLoggingCategory::QGCLoggingCategory(), QGroundControlQmlGlobal::setCategoryLoggingOn(), and QGroundControlQmlGlobal::treeLoggingCategoriesModel().
registerCategory()
void QGCLoggingCategoryManager::registerCategory (const QString & category)
Registers the specified logging category to the system.
Definition at line 27 of file QGCLoggingCategory.cc.
References QmlObjectListModel::indexOf().
Referenced by QGCLoggingCategory::QGCLoggingCategory().
setCategoryLoggingOn
void QGCLoggingCategoryManager::setCategoryLoggingOn (const QString & fullCategoryName, bool enable) slot
Turns on/off logging for the specified category. State is saved in app settings.
Definition at line 68 of file QGCLoggingCategory.cc.
References setFilterRulesFromSettings().
Referenced by QGroundControlQmlGlobal::setCategoryLoggingOn().
setFilterRulesFromSettings()
void QGCLoggingCategoryManager::setFilterRulesFromSettings (const QString & commandLineLoggingOptions)
Sets the logging filters rules from saved settings.
Parameters
commandLineLogggingOptions Logging options which were specified on the command line
Definition at line 91 of file QGCLoggingCategory.cc.
Referenced by disableAllCategories(), QGCApplication::QGCApplication(), and setCategoryLoggingOn().
treeCategoryModel()
QmlObjectListModel * QGCLoggingCategoryManager::treeCategoryModel () inline
Returns the hierarchical list of available logging category names.
Definition at line 33 of file QGCLoggingCategory.h.
Referenced by QGroundControlQmlGlobal::treeLoggingCategoriesModel().
The documentation for this class was generated from the following files:
src/Utilities/QGCLoggingCategory.h
src/Utilities/QGCLoggingCategory.cc