QGroundControl: MapProvider Class Reference
MapProvider Class Reference abstract
#include <MapProvider.h>
Public Types
enum MapStyle {
NoMap = 0 , StreetMap , SatelliteMapDay , SatelliteMapNight ,
TerrainMap , HybridMap , TransitMap , GrayStreetMap ,
PedestrianMap , CarNavigationMap , CycleMap , CustomMap = 100
}
Public Member Functions
MapProvider (const QString &mapName, const QString &referrer, const QString &imageFormat, quint32 averageSize=QGC_AVERAGE_TILE_SIZE, MapStyle mapStyle=CustomMap)
virtual ~MapProvider ()
QUrl getTileURL (int x, int y, int zoom) const
QString getImageFormat (QByteArrayView image) const
quint32 getAverageSize () const
MapStyle getMapStyle () const
const QString & getMapName () const
int getMapId () const
const QString & getReferrer () const
virtual QByteArray getToken () const
virtual int long2tileX (double lon, int z) const
virtual int lat2tileY (double lat, int z) const
virtual double tileX2long (int x, int z) const
virtual double tileY2lat (int y, int z) const
virtual bool isElevationProvider () const
virtual bool isBingProvider () const
virtual QGCTileSet getTileCount (int zoom, double topleftLon, double topleftLat, double bottomRightLon, double bottomRightLat) const
Protected Member Functions
QString _tileXYToQuadKey (int tileX, int tileY, int levelOfDetail) const
int _getServerNum (int x, int y, int max) const
virtual QString _getURL (int x, int y, int zoom) const =0
Protected Attributes
const QString _mapName
const QString _referrer
const QString _imageFormat
const quint32 _averageSize
const MapStyle _mapStyle
const QString _language
const int _mapId
Detailed Description
Definition at line 12 of file MapProvider.h.
Member Enumeration Documentation
MapStyle
enum MapProvider::MapStyle
Enumerator
NoMap
StreetMap
SatelliteMapDay
SatelliteMapNight
TerrainMap
HybridMap
TransitMap
GrayStreetMap
PedestrianMap
CarNavigationMap
CycleMap
CustomMap
Definition at line 18 of file MapProvider.h.
Constructor & Destructor Documentation
MapProvider()
MapProvider::MapProvider (const QString & mapName, const QString & referrer, const QString & imageFormat, quint32 averageSize = QGC_AVERAGE_TILE_SIZE, MapStyle mapStyle = CustomMap)
Definition at line 29 of file MapProvider.cpp.
~MapProvider()
MapProvider::~MapProvider () virtual
Definition at line 46 of file MapProvider.cpp.
Member Function Documentation
_getServerNum()
int MapProvider::_getServerNum (int x, int y, int max) const protected
Definition at line 100 of file MapProvider.cpp.
_getURL()
virtual QString MapProvider::_getURL (int x, int y, int zoom) const protected pure virtual
Referenced by getTileURL().
_tileXYToQuadKey()
QString MapProvider::_tileXYToQuadKey (int tileX, int tileY, int levelOfDetail) const protected
Definition at line 80 of file MapProvider.cpp.
getAverageSize()
quint32 MapProvider::getAverageSize () const inline
Definition at line 42 of file MapProvider.h.
References _averageSize.
Referenced by getTileCount(), and CopernicusElevationProvider::getTileCount().
getImageFormat()
QString MapProvider::getImageFormat (QByteArrayView image) const
Definition at line 56 of file MapProvider.cpp.
References _imageFormat.
getMapId()
int MapProvider::getMapId () const inline
Definition at line 46 of file MapProvider.h.
References _mapId.
getMapName()
const QString & MapProvider::getMapName () const inline
Definition at line 45 of file MapProvider.h.
References _mapName.
getMapStyle()
MapStyle MapProvider::getMapStyle () const inline
Definition at line 44 of file MapProvider.h.
References _mapStyle.
getReferrer()
const QString & MapProvider::getReferrer () const inline
Definition at line 47 of file MapProvider.h.
References _referrer.
getTileCount()
QGCTileSet MapProvider::getTileCount (int zoom, double topleftLon, double topleftLat, double bottomRightLon, double bottomRightLat) const virtual
Reimplemented in CopernicusElevationProvider.
Definition at line 126 of file MapProvider.cpp.
References getAverageSize(), lat2tileY(), long2tileX(), QGCTileSet::tileCount, QGCTileSet::tileSize, QGCTileSet::tileX0, QGCTileSet::tileX1, QGCTileSet::tileY0, and QGCTileSet::tileY1.
getTileURL()
QUrl MapProvider::getTileURL (int x, int y, int zoom) const
Definition at line 51 of file MapProvider.cpp.
References _getURL().
getToken()
virtual QByteArray MapProvider::getToken () const inline virtual
Reimplemented in EsriMapProvider.
Definition at line 48 of file MapProvider.h.
isBingProvider()
virtual bool MapProvider::isBingProvider () const inline virtual
Reimplemented in BingMapProvider.
Definition at line 56 of file MapProvider.h.
isElevationProvider()
virtual bool MapProvider::isElevationProvider () const inline virtual
Reimplemented in ElevationProvider.
Definition at line 55 of file MapProvider.h.
lat2tileY()
int MapProvider::lat2tileY (double lat, int z) const virtual
Reimplemented in CopernicusElevationProvider.
Definition at line 110 of file MapProvider.cpp.
Referenced by getTileCount().
long2tileX()
int MapProvider::long2tileX (double lon, int z) const virtual
Reimplemented in CopernicusElevationProvider.
Definition at line 105 of file MapProvider.cpp.
Referenced by getTileCount().
tileX2long()
double MapProvider::tileX2long (int x, int z) const virtual
Definition at line 115 of file MapProvider.cpp.
tileY2lat()
double MapProvider::tileY2lat (int y, int z) const virtual
Definition at line 120 of file MapProvider.cpp.
Member Data Documentation
_averageSize
const quint32 MapProvider::_averageSize protected
Definition at line 71 of file MapProvider.h.
Referenced by getAverageSize().
_imageFormat
const QString MapProvider::_imageFormat protected
Definition at line 70 of file MapProvider.h.
Referenced by getImageFormat().
_language
const QString MapProvider::_language protected
Definition at line 73 of file MapProvider.h.
_mapId
const int MapProvider::_mapId protected
Definition at line 74 of file MapProvider.h.
Referenced by getMapId().
_mapName
const QString MapProvider::_mapName protected
Definition at line 68 of file MapProvider.h.
Referenced by getMapName().
_mapStyle
const MapStyle MapProvider::_mapStyle protected
Definition at line 72 of file MapProvider.h.
Referenced by getMapStyle().
_referrer
const QString MapProvider::_referrer protected
Definition at line 69 of file MapProvider.h.
Referenced by getReferrer().
The documentation for this class was generated from the following files:
src/QtLocationPlugin/Providers/MapProvider.h
src/QtLocationPlugin/Providers/MapProvider.cpp