QGroundControl: GstQSG6OpenGLNode Class Reference
GstQSG6OpenGLNode Class Reference
#include <gstqsg6glnode.h>
Public Member Functions
GstQSG6OpenGLNode (QQuickItem *item)
~GstQSG6OpenGLNode ()
QSGTexture * texture () const override
void setCaps (GstCaps *caps)
void setBuffer (GstBuffer *buffer)
GstBuffer * getBuffer ()
void updateQSGTexture ()
Detailed Description
Definition at line 33 of file gstqsg6glnode.h.
Constructor & Destructor Documentation
GstQSG6OpenGLNode()
GstQSG6OpenGLNode::GstQSG6OpenGLNode (QQuickItem * item)
Definition at line 31 of file gstqsg6glnode.cc.
References GST_CAT_DEFAULT.
~GstQSG6OpenGLNode()
GstQSG6OpenGLNode::~GstQSG6OpenGLNode ()
Definition at line 50 of file gstqsg6glnode.cc.
Member Function Documentation
getBuffer()
GstBuffer * GstQSG6OpenGLNode::getBuffer ()
Definition at line 79 of file gstqsg6glnode.cc.
Referenced by Qt6GLVideoItem::updatePaintNode().
setBuffer()
void GstQSG6OpenGLNode::setBuffer (GstBuffer * buffer)
Definition at line 91 of file gstqsg6glnode.cc.
References texture().
Referenced by Qt6GLVideoItem::updatePaintNode().
setCaps()
void GstQSG6OpenGLNode::setCaps (GstCaps * caps)
Definition at line 67 of file gstqsg6glnode.cc.
Referenced by Qt6GLVideoItem::updatePaintNode().
texture()
QSGTexture * GstQSG6OpenGLNode::texture () const override
Definition at line 60 of file gstqsg6glnode.cc.
Referenced by setBuffer().
updateQSGTexture()
void GstQSG6OpenGLNode::updateQSGTexture ()
The documentation for this class was generated from the following files:
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/qt6/gstqsg6glnode.h
src/VideoManager/VideoReceiver/GStreamer/gstqml6gl/qt6/gstqsg6glnode.cc