QGroundControl: SettingsGroup Class Reference
SettingsGroup Class Reference
#include <SettingsGroup.h>
Signals
void userVisibleChanged ()
Public Member Functions
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool userVisible READ userVisible WRITE setUserVisible NOTIFY virtual userVisibleChanged bool userVisible ()
virtual void setUserVisible (bool vis)
QString settingsGroup () const
Protected Member Functions
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes
bool _userVisible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Provides access to group of settings. The group is named and has a userVisible property that controls whether the entire group is shown in the UI. Custom builds can hide groups via QGCCorePlugin::overrideSettingsGroupVisibility.
Definition at line 42 of file SettingsGroup.h.
Constructor & Destructor Documentation
SettingsGroup()
SettingsGroup::SettingsGroup (const QString & name, const QString & settingsGroup, QObject * parent = nullptr)
Parameters
name Name for this Settings group
settingsGroup Group to place settings in for QSettings::beingGroup
Definition at line 6 of file SettingsGroup.cc.
References _nameToMetaDataMap, and FactMetaData::createMapFromJsonFile().
Member Function Documentation
_createSettingsFact()
SettingsFact * SettingsGroup::_createSettingsFact (const QString & factName) protected
Definition at line 17 of file SettingsGroup.cc.
References _name, _nameToMetaDataMap, _settingsGroup, and FactMetaData::label().
settingsGroup()
QString SettingsGroup::settingsGroup () const inline
Definition at line 58 of file SettingsGroup.h.
References _settingsGroup.
Referenced by Joystick::setButtonAction(), and Joystick::setButtonRepeat().
setUserVisible()
virtual void SettingsGroup::setUserVisible (bool vis) inline virtual
Definition at line 56 of file SettingsGroup.h.
References _userVisible, and userVisibleChanged().
userVisible()
bool userVisible READ userVisible WRITE setUserVisible NOTIFY virtual userVisibleChanged bool SettingsGroup::userVisible () inline virtual
Whether this settings group should be shown in the UI. Custom builds can override this via QGCCorePlugin::overrideSettingsGroupVisibility.
Definition at line 55 of file SettingsGroup.h.
References _userVisible.
userVisibleChanged
void SettingsGroup::userVisibleChanged () signal
Referenced by setUserVisible().
Member Data Documentation
_name
QString SettingsGroup::_name protected
Definition at line 67 of file SettingsGroup.h.
Referenced by _createSettingsFact().
_nameToMetaDataMap
QMap<QString, FactMetaData*> SettingsGroup::_nameToMetaDataMap protected
Definition at line 70 of file SettingsGroup.h.
Referenced by _createSettingsFact(), and SettingsGroup().
_settingsGroup
QString SettingsGroup::_settingsGroup protected
Definition at line 68 of file SettingsGroup.h.
Referenced by _createSettingsFact(), and settingsGroup().
_userVisible
bool SettingsGroup::_userVisible protected
Definition at line 66 of file SettingsGroup.h.
Referenced by setUserVisible(), and userVisible().
The documentation for this class was generated from the following files:
src/Settings/SettingsGroup.h
src/Settings/SettingsGroup.cc