QGroundControl: APMParameterMetaData Class Reference
APMParameterMetaData Class Reference
#include <APMParameterMetaData.h>
Public Member Functions
APMParameterMetaData (QObject *parent=nullptr)
~APMParameterMetaData () override
Public Member Functions inherited from ParameterMetaData
ParameterMetaData (QObject *parent=nullptr)
~ParameterMetaData () override
void loadParameterFactMetaDataFile (const QString &metaDataFile)
FactMetaData * getMetaDataForFact (const QString &name, FactMetaData::ValueType_t type)
Protected Member Functions
void parseParameterJson (const QJsonObject &json) override
FactMetaData * _lookupMetaData (const QString &name, FactMetaData::ValueType_t type) override
FactMetaData * _createDefaultMetaData (const QString &name, FactMetaData::ValueType_t type) override
void _postProcessMetaData (const QString &name, FactMetaData *metaData) override
Additional Inherited Members
Static Public Member Functions inherited from ParameterMetaData
static QVersionNumber versionFromMetaDataFile (const QString &metaDataFile)
static QVersionNumber versionFromJsonData (const QByteArray &jsonData)
static QVersionNumber versionFromJsonData (const QByteArray &jsonData, bool *validJson)
static QVersionNumber versionFromFileName (const QString &fileName)
Static Public Attributes inherited from ParameterMetaData
static const FactMetaData::DefineMap_t kEmptyDefines
Static Protected Member Functions inherited from ParameterMetaData
static bool textToBool (QStringView text)
static bool jsonToBool (const QJsonValue &value)
static bool setRawConvertedValue (FactMetaData *metaData, const QString &rawText, void(FactMetaData::*setter)(const QVariant &))
static void setEnumFromPairs (FactMetaData *metaData, const QList< ValueDescPair > &pairs)
static void setBitmaskFromPairs (FactMetaData *metaData, const QList< ValueDescPair > &pairs)
Protected Attributes inherited from ParameterMetaData
FactMetaData::NameToMetaDataMap_t _cachedMetaData
bool _parameterMetaDataLoaded = false
Detailed Description
Definition at line 7 of file APMParameterMetaData.h.
Constructor & Destructor Documentation
APMParameterMetaData()
APMParameterMetaData::APMParameterMetaData (QObject * parent = nullptr) explicit
Definition at line 13 of file APMParameterMetaData.cc.
~APMParameterMetaData()
APMParameterMetaData::~APMParameterMetaData () override
Definition at line 19 of file APMParameterMetaData.cc.
Member Function Documentation
_createDefaultMetaData()
FactMetaData * APMParameterMetaData::_createDefaultMetaData (const QString & name, FactMetaData::ValueType_t type) override protected virtual
Reimplemented from ParameterMetaData.
Definition at line 188 of file APMParameterMetaData.cc.
References FactMetaData::setCategory(), and FactMetaData::setGroup().
_lookupMetaData()
FactMetaData * APMParameterMetaData::_lookupMetaData (const QString & name, FactMetaData::ValueType_t type) override protected virtual
Reimplemented from ParameterMetaData.
Definition at line 73 of file APMParameterMetaData.cc.
References ParameterMetaData::jsonToBool(), ParameterMetaData::setRawConvertedValue(), FactMetaData::setRawMax(), FactMetaData::setRawMin(), FactMetaData::setRawUserMax(), and FactMetaData::setRawUserMin().
_postProcessMetaData()
void APMParameterMetaData::_postProcessMetaData (const QString & name, FactMetaData * metaData) override protected virtual
Reimplemented from ParameterMetaData.
Definition at line 196 of file APMParameterMetaData.cc.
References FactMetaData::setDecimalPlaces(), FactMetaData::type(), FactMetaData::valueTypeDouble, and FactMetaData::valueTypeFloat.
parseParameterJson()
void APMParameterMetaData::parseParameterJson (const QJsonObject & json) override protected virtual
Implements ParameterMetaData.
Definition at line 31 of file APMParameterMetaData.cc.
The documentation for this class was generated from the following files:
src/FirmwarePlugin/APM/APMParameterMetaData.h
src/FirmwarePlugin/APM/APMParameterMetaData.cc