QGroundControl: StatusTextHandler Class Reference
StatusTextHandler Class Reference
#include <StatusTextHandler.h>
Signals
void newFormattedMessage (QString message)
void textMessageReceived (MAV_COMPONENT componentid, MAV_SEVERITY severity, QString text, QString description)
void messageCountChanged (uint32_t newCount)
void messageTypeChanged ()
void newErrorMessage (QString message)
Public Member Functions
StatusTextHandler (QObject *parent=nullptr)
~StatusTextHandler ()
void mavlinkMessageReceived (const mavlink_message_t &message)
void handleHTMLEscapedTextMessage (MAV_COMPONENT componentid, MAV_SEVERITY severity, const QString &text, const QString &description)
void clearMessages ()
void resetAllMessages ()
void resetErrorLevelMessages ()
const QList< StatusText * > & messages () const
QString formattedMessages () const
bool messageTypeNone () const
bool messageTypeNormal () const
bool messageTypeWarning () const
bool messageTypeError () const
uint32_t getErrorCount () const
uint32_t getErrorCountTotal () const
uint32_t getWarningCount () const
uint32_t getNormalCount () const
uint32_t messageCount () const
Static Public Member Functions
static QString getMessageText (const mavlink_message_t &message)
Detailed Description
Definition at line 33 of file StatusTextHandler.h.
Constructor & Destructor Documentation
StatusTextHandler()
StatusTextHandler::StatusTextHandler (QObject * parent = nullptr) explicit
Definition at line 32 of file StatusTextHandler.cc.
~StatusTextHandler()
StatusTextHandler::~StatusTextHandler ()
Definition at line 43 of file StatusTextHandler.cc.
References clearMessages().
Member Function Documentation
clearMessages()
void StatusTextHandler::clearMessages ()
Definition at line 75 of file StatusTextHandler.cc.
Referenced by ~StatusTextHandler().
formattedMessages()
QString StatusTextHandler::formattedMessages () const
Definition at line 65 of file StatusTextHandler.cc.
References messages().
getErrorCount()
uint32_t StatusTextHandler::getErrorCount () const inline
Definition at line 63 of file StatusTextHandler.h.
Referenced by resetErrorLevelMessages().
getErrorCountTotal()
uint32_t StatusTextHandler::getErrorCountTotal () const inline
Definition at line 64 of file StatusTextHandler.h.
getMessageText()
QString StatusTextHandler::getMessageText (const mavlink_message_t & message) static
Definition at line 50 of file StatusTextHandler.cc.
getNormalCount()
uint32_t StatusTextHandler::getNormalCount () const inline
Definition at line 66 of file StatusTextHandler.h.
Referenced by resetErrorLevelMessages().
getWarningCount()
uint32_t StatusTextHandler::getWarningCount () const inline
Definition at line 65 of file StatusTextHandler.h.
Referenced by resetErrorLevelMessages().
handleHTMLEscapedTextMessage()
void StatusTextHandler::handleHTMLEscapedTextMessage (MAV_COMPONENT componentid, MAV_SEVERITY severity, const QString & text, const QString & description)
Definition at line 132 of file StatusTextHandler.cc.
References StatusText::getText(), newErrorMessage(), newFormattedMessage(), StatusText::setFormatedText(), and StatusText::severityIsError().
mavlinkMessageReceived()
void StatusTextHandler::mavlinkMessageReceived (const mavlink_message_t & message)
Definition at line 246 of file StatusTextHandler.cc.
messageCount()
uint32_t StatusTextHandler::messageCount () const inline
Definition at line 67 of file StatusTextHandler.h.
Referenced by resetAllMessages(), and resetErrorLevelMessages().
messageCountChanged
void StatusTextHandler::messageCountChanged (uint32_t newCount) signal
Referenced by resetAllMessages(), and resetErrorLevelMessages().
messages()
const QList< StatusText * > & StatusTextHandler::messages () const inline
Definition at line 55 of file StatusTextHandler.h.
Referenced by formattedMessages().
messageTypeChanged
void StatusTextHandler::messageTypeChanged () signal
Referenced by resetAllMessages(), and resetErrorLevelMessages().
messageTypeError()
bool StatusTextHandler::messageTypeError () const inline
Definition at line 61 of file StatusTextHandler.h.
messageTypeNone()
bool StatusTextHandler::messageTypeNone () const inline
Definition at line 58 of file StatusTextHandler.h.
messageTypeNormal()
bool StatusTextHandler::messageTypeNormal () const inline
Definition at line 59 of file StatusTextHandler.h.
messageTypeWarning()
bool StatusTextHandler::messageTypeWarning () const inline
Definition at line 60 of file StatusTextHandler.h.
newErrorMessage
void StatusTextHandler::newErrorMessage (QString message) signal
Referenced by handleHTMLEscapedTextMessage().
newFormattedMessage
void StatusTextHandler::newFormattedMessage (QString message) signal
Referenced by handleHTMLEscapedTextMessage().
resetAllMessages()
void StatusTextHandler::resetAllMessages ()
Definition at line 87 of file StatusTextHandler.cc.
References messageCount(), messageCountChanged(), and messageTypeChanged().
resetErrorLevelMessages()
void StatusTextHandler::resetErrorLevelMessages ()
Definition at line 107 of file StatusTextHandler.cc.
References getErrorCount(), getNormalCount(), getWarningCount(), messageCount(), messageCountChanged(), and messageTypeChanged().
textMessageReceived
void StatusTextHandler::textMessageReceived (MAV_COMPONENT componentid, MAV_SEVERITY severity, QString text, QString description) signal
The documentation for this class was generated from the following files:
src/MAVLink/StatusTextHandler.h
src/MAVLink/StatusTextHandler.cc