QGroundControl: Mixer::MixerConfigGroup Class Reference
Mixer::MixerConfigGroup Class Reference
#include <Mixer.h>
Signals
void channelsChanged ()
void channelConfigsChanged ()
Public Member Functions
MixerConfigGroup (QObject *parent, const MixerOption::ActuatorGroup &group)
QString label READ label CONSTANT (QmlObjectListModel *channels READ channels NOTIFY channelsChanged) 1(QmlObjectListModel *channelConfigs READ channelConfigs NOTIFY channelConfigsChanged) 1(ConfigParameter *countParam READ countParam CONSTANT) 1(QmlObjectListModel *configParams READ configParams CONSTANT) const QString &label() const
QmlObjectListModel * channelConfigs ()
void addChannelConfig (ChannelConfig *channelConfig)
QmlObjectListModel * channels ()
void addChannel (MixerChannel *channel)
ConfigParameter * countParam () const
void addConfigParam (ConfigParameter *param)
QmlObjectListModel * configParams ()
void setCountParam (ConfigParameter *param)
const MixerOption::ActuatorGroup & group () const
Detailed Description
Definition at line 306 of file Mixer.h.
Constructor & Destructor Documentation
MixerConfigGroup()
Mixer::MixerConfigGroup::MixerConfigGroup (QObject * parent, const MixerOption::ActuatorGroup & group) inline
Definition at line 310 of file Mixer.h.
Member Function Documentation
addChannel()
void MixerConfigGroup::addChannel (MixerChannel * channel)
Definition at line 376 of file Mixer.cc.
References QmlObjectListModel::append(), and channelsChanged().
Referenced by Mixer::Mixers::update().
addChannelConfig()
void MixerConfigGroup::addChannelConfig (ChannelConfig * channelConfig)
Definition at line 370 of file Mixer.cc.
References QmlObjectListModel::append(), and channelConfigsChanged().
Referenced by Mixer::Mixers::update().
addConfigParam()
void MixerConfigGroup::addConfigParam (ConfigParameter * param)
Definition at line 382 of file Mixer.cc.
References QmlObjectListModel::append().
Referenced by Mixer::Mixers::update().
channelConfigs()
QmlObjectListModel * Mixer::MixerConfigGroup::channelConfigs () inline
Definition at line 322 of file Mixer.h.
Referenced by Mixer::Mixers::update().
channelConfigsChanged
void Mixer::MixerConfigGroup::channelConfigsChanged () signal
Referenced by addChannelConfig().
channels()
QmlObjectListModel * Mixer::MixerConfigGroup::channels () inline
Definition at line 325 of file Mixer.h.
Referenced by Mixer::Mixers::getFunctions(), and Mixer::Mixers::getSpecificLabelForFunction().
channelsChanged
void Mixer::MixerConfigGroup::channelsChanged () signal
Referenced by addChannel().
configParams()
QmlObjectListModel * Mixer::MixerConfigGroup::configParams () inline
Definition at line 330 of file Mixer.h.
CONSTANT()
QString label READ label Mixer::MixerConfigGroup::CONSTANT (QmlObjectListModel *channels READ channels NOTIFY channelsChanged) const & inline
Definition at line 313 of file Mixer.h.
References Mixer::MixerOption::ActuatorGroup::groupLabel.
countParam()
ConfigParameter * Mixer::MixerConfigGroup::countParam () const inline
Definition at line 328 of file Mixer.h.
group()
const MixerOption::ActuatorGroup & Mixer::MixerConfigGroup::group () const inline
Definition at line 334 of file Mixer.h.
Referenced by Mixer::Mixers::getFunctions().
setCountParam()
void Mixer::MixerConfigGroup::setCountParam (ConfigParameter * param) inline
Definition at line 332 of file Mixer.h.
Referenced by Mixer::Mixers::update().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Mixer.h
src/Vehicle/Actuators/Mixer.cc