QGroundControl: QGCDeviceInfo::QGCCompass Class Reference
QGCDeviceInfo::QGCCompass Class Reference
#include <DeviceInfo.h>
Signals
void compassUpdated (qreal azimuth)
void positionUpdated (QGeoPositionInfo update)
Public Member Functions
QGCCompass (QObject *parent=nullptr)
~QGCCompass ()
bool init ()
void quit ()
Static Public Member Functions
static QGCCompass * instance ()
Detailed Description
Definition at line 114 of file DeviceInfo.h.
Constructor & Destructor Documentation
QGCCompass()
QGCDeviceInfo::QGCCompass::QGCCompass (QObject * parent = nullptr)
Definition at line 255 of file DeviceInfo.cc.
References error, and init().
~QGCCompass()
QGCDeviceInfo::QGCCompass::~QGCCompass ()
Definition at line 271 of file DeviceInfo.cc.
Member Function Documentation
compassUpdated
void QGCDeviceInfo::QGCCompass::compassUpdated (qreal azimuth) signal
Referenced by init().
init()
bool QGCDeviceInfo::QGCCompass::init ()
Definition at line 276 of file DeviceInfo.cc.
References compassUpdated(), and positionUpdated().
Referenced by QGCCompass().
instance()
QGCCompass * QGCDeviceInfo::QGCCompass::instance () static
Definition at line 250 of file DeviceInfo.cc.
positionUpdated
void QGCDeviceInfo::QGCCompass::positionUpdated (QGeoPositionInfo update) signal
Referenced by init().
quit()
void QGCDeviceInfo::QGCCompass::quit ()
Definition at line 338 of file DeviceInfo.cc.
The documentation for this class was generated from the following files:
src/Utilities/DeviceInfo.h
src/Utilities/DeviceInfo.cc