QGroundControl: ParallelState Class Reference
ParallelState Class Reference
#include <ParallelState.h>
Signals
void allComplete ()
Emitted when all parallel child states have completed.
Signals inherited from QGCAbstractState
void advance ()
void error ()
Public Member Functions
ParallelState (const QString &stateName, QState *parent)
void addParallelState (QAbstractState *state)
Public Member Functions inherited from QGCState
QGCState (const QString &stateName, QState *parentState)
template<typename PointerToMemberFunction >
QSignalTransition * addThisTransition (PointerToMemberFunction signal, QAbstractState *target)
Simpler version of QState::addTransition which assumes the sender is this.
void setLocalErrorState (QAbstractState *errorState)
QAbstractState * localErrorState () const
Get the per-state error state (nullptr if using global)
void setProperty (QObject *object, const char *name, const QVariant &value)
void setEnabled (QObject *object, bool enabled)
Convenience overload for setting enabled state on widgets/controls.
void setVisible (QObject *object, bool visible)
Convenience overload for setting visible state on widgets/controls.
Public Member Functions inherited from QGCAbstractState
QGCAbstractState (const QString &stateName, QState *parent)
QGCStateMachine * machine () const
Vehicle * vehicle () const
QString stateName () const
class StateContext * context () const
void setOnEntry (EntryCallback callback)
Set a callback to be invoked when the state is entered.
void setOnExit (ExitCallback callback)
Set a callback to be invoked when the state is exited.
void setCallbacks (EntryCallback onEntry, ExitCallback onExit=nullptr)
Set both entry and exit callbacks.
void setEventHandler (EventHandler handler)
Set a custom event handler for this state.
Protected Member Functions
void onEntry (QEvent *event) override
void onExit (QEvent *event) override
Protected Member Functions inherited from QGCAbstractState
virtual void onEnter ()
Override to perform actions on state entry.
virtual void onLeave ()
Override to perform actions on state exit.
void onEntry (QEvent *event) override
void onExit (QEvent *event) override
bool event (QEvent *event) override
Additional Inherited Members
Public Types inherited from QGCAbstractState
using EntryCallback = std::function< void()>
using ExitCallback = std::function< void()>
using EventHandler = std::function< bool(QEvent *)>
Detailed Description
State that executes all child states in parallel When entered, all child states are activated simultaneously. The state completes when all child states have finished.
Definition at line 8 of file ParallelState.h.
Constructor & Destructor Documentation
ParallelState()
ParallelState::ParallelState (const QString & stateName, QState * parent)
Create a parallel state
Parameters
stateName Name for debugging
parent Parent state or machine
Definition at line 6 of file ParallelState.cc.
Member Function Documentation
addParallelState()
void ParallelState::addParallelState (QAbstractState * state)
Add a child state to execute in parallel
Parameters
state The state to add as a parallel child
Definition at line 12 of file ParallelState.cc.
allComplete
void ParallelState::allComplete () signal
Emitted when all parallel child states have completed.
Referenced by onEntry().
onEntry()
void ParallelState::onEntry (QEvent * event) override protected
Definition at line 17 of file ParallelState.cc.
References QGCAbstractState::advance(), allComplete(), QGCAbstractState::event(), QGCAbstractState::onEntry(), and QGCAbstractState::stateName().
onExit()
void ParallelState::onExit (QEvent * event) override protected
Definition at line 43 of file ParallelState.cc.
References QGCAbstractState::event(), QGCAbstractState::onExit(), and QGCAbstractState::stateName().
The documentation for this class was generated from the following files:
src/Utilities/StateMachine/States/ParallelState.h
src/Utilities/StateMachine/States/ParallelState.cc