QGroundControl: TCPLink Class Reference
TCPLink Class Reference
#include <TCPLink.h>
Public Member Functions
TCPLink (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
~TCPLink () override
bool isConnected () const override
void disconnect () override
bool isSecureConnection () const override
Returns true if the connection is secure (e.g. USB, wired ethernet)
Public Member Functions inherited from LinkInterface
virtual ~LinkInterface ()
virtual bool isLogReplay () const
SharedLinkConfigurationPtr linkConfiguration ()
const SharedLinkConfigurationPtr linkConfiguration () const
uint8_t mavlinkChannel () const
bool mavlinkChannelIsSet () const
bool decodedFirstMavlinkPacket () const
void setDecodedFirstMavlinkPacket (bool decodedFirstMavlinkPacket)
void writeBytesThreadSafe (const char *bytes, int length)
void addVehicleReference ()
void removeVehicleReference ()
bool initMavlinkSigning ()
void setSigningSignatureFailure (bool failure)
void reportMavlinkV1Traffic ()
Additional Inherited Members
Signals inherited from LinkInterface
void bytesReceived (LinkInterface *link, const QByteArray &data)
void bytesSent (LinkInterface *link, const QByteArray &data)
void connected ()
void disconnected ()
void communicationError (const QString &title, const QString &error)
Protected Member Functions inherited from LinkInterface
LinkInterface (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
Links are only created by LinkManager so constructor is not public.
virtual bool _allocateMavlinkChannel ()
virtual void _freeMavlinkChannel ()
void _connectionRemoved ()
Protected Attributes inherited from LinkInterface
SharedLinkConfigurationPtr _config
Detailed Description
Definition at line 93 of file TCPLink.h.
Constructor & Destructor Documentation
TCPLink()
TCPLink::TCPLink (SharedLinkConfigurationPtr & config, QObject * parent = nullptr) explicit
Definition at line 248 of file TCPLink.cc.
References TCPWorker::connected(), TCPWorker::dataReceived(), TCPWorker::dataSent(), TCPWorker::disconnected(), TCPWorker::errorOccurred(), and TCPWorker::setupSocket().
~TCPLink()
TCPLink::~TCPLink () override
Definition at line 272 of file TCPLink.cc.
References isConnected().
Member Function Documentation
disconnect()
void TCPLink::disconnect () override virtual
Implements LinkInterface.
Definition at line 297 of file TCPLink.cc.
References isConnected().
isConnected()
bool TCPLink::isConnected () const override virtual
Implements LinkInterface.
Definition at line 287 of file TCPLink.cc.
References TCPWorker::isConnected().
Referenced by disconnect(), and ~TCPLink().
isSecureConnection()
bool TCPLink::isSecureConnection () const override virtual
Returns true if the connection is secure (e.g. USB, wired ethernet)
Reimplemented from LinkInterface.
Definition at line 338 of file TCPLink.cc.
References QGCNetworkHelper::isNetworkEthernet().
The documentation for this class was generated from the following files:
src/Comms/TCPLink.h
src/Comms/TCPLink.cc