QGroundControl: TerrainTileManager Class Reference
TerrainTileManager Class Reference
#include <TerrainTileManager.h>
Public Member Functions
TerrainTileManager (QObject *parent=nullptr)
~TerrainTileManager ()
bool getAltitudesForCoordinates (const QList< QGeoCoordinate > &coordinates, QList< double > &altitudes, bool &error)
void addCoordinateQuery (TerrainQueryInterface *terrainQueryInterface, const QList< QGeoCoordinate > &coordinates)
void addPathQuery (TerrainQueryInterface *terrainQueryInterface, const QGeoCoordinate &startPoint, const QGeoCoordinate &endPoint)
void addCarpetQuery (TerrainQueryInterface *terrainQueryInterface, const QGeoCoordinate &swCoord, const QGeoCoordinate &neCoord, bool statsOnly)
Static Public Member Functions
static TerrainTileManager * instance ()
Friends
class UnitTestTerrainQuery
Detailed Description
Definition at line 17 of file TerrainTileManager.h.
Constructor & Destructor Documentation
TerrainTileManager()
TerrainTileManager::TerrainTileManager (QObject * parent = nullptr) explicit
Definition at line 34 of file TerrainTileManager.cc.
References QGCNetworkHelper::configureProxy().
~TerrainTileManager()
TerrainTileManager::~TerrainTileManager ()
Definition at line 43 of file TerrainTileManager.cc.
Member Function Documentation
addCarpetQuery()
void TerrainTileManager::addCarpetQuery (TerrainQueryInterface * terrainQueryInterface, const QGeoCoordinate & swCoord, const QGeoCoordinate & neCoord, bool statsOnly)
Definition at line 170 of file TerrainTileManager.cc.
References error, getAltitudesForCoordinates(), TerrainTileCopernicus::kTileValueSpacingDegrees, TerrainQuery::QueryModeCarpet, and TerrainQueryInterface::signalCarpetHeights().
Referenced by TerrainOfflineQuery::requestCarpetHeights().
addCoordinateQuery()
void TerrainTileManager::addCoordinateQuery (TerrainQueryInterface * terrainQueryInterface, const QList< QGeoCoordinate > & coordinates)
Definition at line 98 of file TerrainTileManager.cc.
References error, getAltitudesForCoordinates(), TerrainQuery::QueryModeCoordinates, and TerrainQueryInterface::signalCoordinateHeights().
Referenced by TerrainOfflineQuery::requestCoordinateHeights().
addPathQuery()
void TerrainTileManager::addPathQuery (TerrainQueryInterface * terrainQueryInterface, const QGeoCoordinate & startPoint, const QGeoCoordinate & endPoint)
Definition at line 135 of file TerrainTileManager.cc.
References error, getAltitudesForCoordinates(), TerrainQuery::QueryModePath, and TerrainQueryInterface::signalPathHeights().
Referenced by TerrainOfflineQuery::requestPathHeights().
getAltitudesForCoordinates()
bool TerrainTileManager::getAltitudesForCoordinates (const QList< QGeoCoordinate > & coordinates, QList< double > & altitudes, bool & error)
Either returns altitudes from cache or queues database request
Parameters
[out] error true: altitude not returned due to error, false: altitudes returned
Returns
true: altitude returned (check error as well), false: database query queued (altitudes not returned)
Definition at line 50 of file TerrainTileManager.cc.
References TerrainQuery::Downloading, TerrainTile::elevation(), FlightMapSettings::elevationMapProvider(), error, UrlFactory::getMapProviderFromProviderType(), QGeoTileFetcherQGC::getNetworkRequest(), UrlFactory::getTileHash(), and QGeoTiledMapReplyQGC::init().
Referenced by addCarpetQuery(), addCoordinateQuery(), addPathQuery(), and TerrainAtCoordinateQuery::getAltitudesForCoordinates().
instance()
TerrainTileManager * TerrainTileManager::instance () static
Definition at line 29 of file TerrainTileManager.cc.
Referenced by TerrainAtCoordinateQuery::getAltitudesForCoordinates(), TerrainOfflineQuery::requestCarpetHeights(), TerrainOfflineQuery::requestCoordinateHeights(), and TerrainOfflineQuery::requestPathHeights().
Friends And Related Symbol Documentation
UnitTestTerrainQuery
friend class UnitTestTerrainQuery friend
Definition at line 21 of file TerrainTileManager.h.
The documentation for this class was generated from the following files:
src/Terrain/TerrainTileManager.h
src/Terrain/TerrainTileManager.cc