QGroundControl: MissionController Class Reference
MissionController Class Reference
#include <MissionController.h>
Public Types
enum SendToVehiclePreCheckState { SendToVehiclePreCheckStateOk , SendToVehiclePreCheckStateNoActiveVehicle , SendToVehiclePreCheckStateFirwmareVehicleMismatch , SendToVehiclePreCheckStateActiveMission }
using MissionFlightStatus_t = ::MissionFlightStatus_t
Signals
void visualItemsReset (void)
void splitSegmentChanged (void)
void newItemsFromVehicle (void)
void missionTotalDistanceChanged (double missionTotalDistance)
void missionPlannedDistanceChanged (double missionPlannedDistance)
void missionTimeChanged (void)
void missionHoverDistanceChanged (double missionHoverDistance)
void missionHoverTimeChanged (void)
void missionCruiseDistanceChanged (double missionCruiseDistance)
void missionCruiseTimeChanged (void)
void missionMaxTelemetryChanged (double missionMaxTelemetry)
void complexMissionItemNamesChanged (void)
void resumeMissionIndexChanged (void)
void resumeMissionReady (void)
void resumeMissionUploadFail (void)
void batteryChangePointChanged (int batteryChangePoint)
void batteriesRequiredChanged (int batteriesRequired)
void plannedHomePositionChanged (QGeoCoordinate plannedHomePosition)
void homePositionSetChanged (void)
void progressPctChanged (double progressPct)
void currentMissionIndexChanged (int currentMissionIndex)
void planViewStateChanged (void)
All plan-view properties are recomputed together in setCurrentPlanViewSeqNum, so one signal covers them all.
void takeoffMissionItemChanged (void)
void missionBoundingCubeChanged (void)
void hasLandItemChanged (void)
void multipleLandPatternsAllowedChanged (void)
void minAMSLAltitudeChanged (double minAMSLAltitude)
void maxAMSLAltitudeChanged (double maxAMSLAltitude)
void recalcTerrainProfile (void)
void _recalcMissionFlightStatusSignal (void)
void _recalcFlightPathSegmentsSignal (void)
void globalAltitudeFrameChanged (void)
Signals inherited from PlanElementController
void supportedChanged (bool supported)
void containsItemsChanged ()
void syncInProgressChanged (bool syncInProgress)
void dirtyChanged (bool dirty)
void sendComplete (void)
void removeAllComplete (void)
Public Member Functions
MissionController (PlanMasterController *masterController, QObject *parent=nullptr)
~MissionController ()
void setHomePosition (QGeoCoordinate coordinate)
Set the planned home position from a map click.
VisualMissionItem * insertSimpleMissionItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertTakeoffItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertLandItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertROIMissionItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertCancelROIMissionItem (int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertComplexMissionItem (QString itemName, QGeoCoordinate mapCenterCoordinate, int visualItemIndex, bool makeCurrentItem=false)
VisualMissionItem * insertComplexMissionItemFromKMLOrSHP (QString itemName, QString file, int visualItemIndex, bool makeCurrentItem=false)
void resumeMission (int resumeIndex)
void applyDefaultMissionAltitude (void)
Updates the altitudes of the items in the current mission to the new default altitude.
void setCurrentPlanViewSeqNum (int sequenceNumber, bool force)
void repositionMission (const QGeoCoordinate &newHome, bool repositionTakeoffItems=true, bool repositionLandingItems=true)
void offsetMission (double eastMeters, double northMeters, double upMeters=0.0, bool offsetTakeoffItems=false, bool offsetLandingItems=false)
void rotateMission (double degreesCW, bool rotateTakeoffItems=false, bool rotateLandingItems=false)
SendToVehiclePreCheckState sendToVehiclePreCheck (void)
int readyForSaveState (void) const
bool loadTextFile (QFile &file, QString &errorString)
QGCGeoBoundingCube * travelBoundingCube ()
QGeoCoordinate takeoffCoordinate ()
bool supported (void) const final
true: controller is waiting for the current load to complete
void start (bool flyView) final
Should be called immediately upon Component.onCompleted.
void save (QJsonObject &json) final
bool load (const QJsonObject &json, QString &errorString) final
void loadFromVehicle (void) final
void sendToVehicle (void) final
void removeAll (void) final
Removes all from controller only.
void removeAllFromVehicle (void) final
bool syncInProgress (void) const final
bool dirty (void) const final
void setDirty (bool dirty) final
bool containsItems (void) const final
bool showPlanFromManagerVehicle (void) final
void addMissionToKML (KMLPlanDomDocument &planKML)
QmlObjectListModel * visualItems (void)
QmlObjectTreeModel * visualItemsTree (void)
QPersistentModelIndex planFileGroupIndex (void) const
QPersistentModelIndex defaultsGroupIndex (void) const
QPersistentModelIndex missionGroupIndex (void) const
QPersistentModelIndex fenceGroupIndex (void) const
QPersistentModelIndex rallyGroupIndex (void) const
QPersistentModelIndex transformGroupIndex (void) const
QmlObjectListModel * simpleFlightPathSegments (void)
QmlObjectListModel * directionArrows (void)
QStringList complexMissionItemNames (void) const
QGeoCoordinate plannedHomePosition (void) const
bool homePositionSet (void) const
VisualMissionItem * currentPlanViewItem (void) const
TakeoffMissionItem * takeoffMissionItem (void) const
double progressPct (void) const
QString surveyComplexItemName (void) const
QString corridorScanComplexItemName (void) const
QString structureScanComplexItemName (void) const
bool isInsertTakeoffValid (void) const
bool multipleLandPatternsAllowed (void) const
double minAMSLAltitude (void) const
double maxAMSLAltitude (void) const
int currentMissionIndex (void) const
int resumeMissionIndex (void) const
int currentPlanViewSeqNum (void) const
int currentPlanViewVIIndex (void) const
double missionTotalDistance (void) const
double missionPlannedDistance (void) const
double missionTime (void) const
double missionHoverDistance (void) const
double missionHoverTime (void) const
double missionCruiseDistance (void) const
double missionCruiseTime (void) const
double missionMaxTelemetry (void) const
int batteryChangePoint (void) const
-1 for not supported, 0 for not needed
int batteriesRequired (void) const
-1 for not supported
bool isFirstLandingComplexItem (const LandingComplexItem *item) const
bool isEmpty (void) const
QGroundControlQmlGlobal::AltitudeFrame globalAltitudeFrame (void)
QGroundControlQmlGlobal::AltitudeFrame globalAltitudeFrameDefault (void)
void setGlobalAltitudeFrame (QGroundControlQmlGlobal::AltitudeFrame altFrame)
Public Member Functions inherited from PlanElementController
PlanElementController (PlanMasterController *masterController, QObject *parent=nullptr)
~PlanElementController ()
PlanMasterController *masterController READ masterController CONSTANT (bool supported READ supported NOTIFY supportedChanged) 1(bool containsItems READ containsItems NOTIFY containsItemsChanged) 1(bool syncInProgress READ syncInProgress NOTIFY syncInProgressChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) PlanMasterController *masterController(void)
< true: Elemement is non-empty
Static Public Member Functions
static void sendItemsToVehicle (Vehicle *vehicle, QmlObjectListModel *visualMissionItems)
Sends the mission items to the specified vehicle.
Public Attributes
QmlObjectListModel *visualItems READ visualItems NOTIFY visualItemsReset(QmlObjectTreeModel *visualItemsTree READ visualItemsTree CONSTANT) 1(QPersistentModelIndex planFileGroupIndex READ planFileGroupIndex CONSTANT) 1(QPersistentModelIndex defaultsGroupIndex READ defaultsGroupIndex CONSTANT) 1(QPersistentModelIndex missionGroupIndex READ missionGroupIndex CONSTANT) 1(QPersistentModelIndex fenceGroupIndex READ fenceGroupIndex CONSTANT) 1(QPersistentModelIndex rallyGroupIndex READ rallyGroupIndex CONSTANT) 1(QPersistentModelIndex transformGroupIndex READ transformGroupIndex CONSTANT) 1(QmlObjectListModel *simpleFlightPathSegments READ simpleFlightPathSegments CONSTANT) 1(QmlObjectListModel *directionArrows READ directionArrows CONSTANT) 1(QStringList complexMissionItemNames READ complexMissionItemNames NOTIFY complexMissionItemNamesChanged) 1(QGeoCoordinate plannedHomePosition READ plannedHomePosition NOTIFY plannedHomePositionChanged) 1(bool homePositionSet READ homePositionSet NOTIFY homePositionSetChanged) 1(QGeoCoordinate previousCoordinate MEMBER _previousCoordinate NOTIFY planViewStateChanged) 1(FlightPathSegment *splitSegment MEMBER _splitSegment NOTIFY splitSegmentChanged) 1(double progressPct READ progressPct NOTIFY progressPctChanged) 1(int currentMissionIndex READ currentMissionIndex NOTIFY currentMissionIndexChanged) 1(int resumeMissionIndex READ resumeMissionIndex NOTIFY resumeMissionIndexChanged) 1(int currentPlanViewSeqNum READ currentPlanViewSeqNum NOTIFY planViewStateChanged) 1(int currentPlanViewVIIndex READ currentPlanViewVIIndex NOTIFY planViewStateChanged) 1(VisualMissionItem *currentPlanViewItem READ currentPlanViewItem NOTIFY planViewStateChanged) 1(TakeoffMissionItem *takeoffMissionItem READ takeoffMissionItem NOTIFY takeoffMissionItemChanged) 1(double missionTotalDistance READ missionTotalDistance NOTIFY missionTotalDistanceChanged) 1(double missionPlannedDistance READ missionPlannedDistance NOTIFY missionPlannedDistanceChanged) 1(double missionTime READ missionTime NOTIFY missionTimeChanged) 1(double missionHoverDistance READ missionHoverDistance NOTIFY missionHoverDistanceChanged) 1(double missionCruiseDistance READ missionCruiseDistance NOTIFY missionCruiseDistanceChanged) 1(double missionHoverTime READ missionHoverTime NOTIFY missionHoverTimeChanged) 1(double missionCruiseTime READ missionCruiseTime NOTIFY missionCruiseTimeChanged) 1(double missionMaxTelemetry READ missionMaxTelemetry NOTIFY missionMaxTelemetryChanged) 1(int batteryChangePoint READ batteryChangePoint NOTIFY batteryChangePointChanged) 1(int batteriesRequired READ batteriesRequired NOTIFY batteriesRequiredChanged) 1(QGCGeoBoundingCube *travelBoundingCube READ travelBoundingCube NOTIFY missionBoundingCubeChanged) 1(QString surveyComplexItemName READ surveyComplexItemName CONSTANT) 1(QString corridorScanComplexItemName READ corridorScanComplexItemName CONSTANT) 1(QString structureScanComplexItemName READ structureScanComplexItemName CONSTANT) 1(bool onlyInsertTakeoffValid MEMBER _onlyInsertTakeoffValid NOTIFY planViewStateChanged) 1(bool isInsertTakeoffValid MEMBER _isInsertTakeoffValid NOTIFY planViewStateChanged) 1(bool isInsertLandValid MEMBER _isInsertLandValid NOTIFY planViewStateChanged) 1(bool hasLandItem MEMBER _hasLandItem NOTIFY hasLandItemChanged) 1(bool multipleLandPatternsAllowed READ multipleLandPatternsAllowed NOTIFY multipleLandPatternsAllowedChanged) 1(bool isROIActive MEMBER _isROIActive NOTIFY planViewStateChanged) 1(bool isROIBeginCurrentItem MEMBER _isROIBeginCurrentItem NOTIFY planViewStateChanged) 1(bool flyThroughCommandsAllowed MEMBER _flyThroughCommandsAllowed NOTIFY planViewStateChanged) 1(double minAMSLAltitude MEMBER _minAMSLAltitude NOTIFY minAMSLAltitudeChanged) 1(double maxAMSLAltitude MEMBER _maxAMSLAltitude NOTIFY maxAMSLAltitudeChanged) 1(QGroundControlQmlGlobal in visualItemIndexForObject)(QObject *object) const
< Used by Plan view only for interactive editing
Static Public Attributes
static constexpr int kPlanFileGroupRow = 0
static constexpr int kDefaultsGroupRow = 1
static constexpr int kMissionGroupRow = 2
static constexpr int kFenceGroupRow = 3
static constexpr int kRallyGroupRow = 4
static constexpr int kTransformGroupRow = 5
static constexpr int kGroupCount = 6
Additional Inherited Members
Protected Attributes inherited from PlanElementController
PlanMasterController * _masterController
bool _flyView
Detailed Description
Definition at line 35 of file MissionController.h.
Member Typedef Documentation
MissionFlightStatus_t
using MissionController::MissionFlightStatus_t = ::MissionFlightStatus_t
Definition at line 49 of file MissionController.h.
Member Enumeration Documentation
SendToVehiclePreCheckState
enum MissionController::SendToVehiclePreCheckState
Enumerator
SendToVehiclePreCheckStateOk
SendToVehiclePreCheckStateNoActiveVehicle
SendToVehiclePreCheckStateFirwmareVehicleMismatch
SendToVehiclePreCheckStateActiveMission
Definition at line 211 of file MissionController.h.
Constructor & Destructor Documentation
MissionController()
MissionController::MissionController (PlanMasterController * masterController, QObject * parent = nullptr)
Definition at line 37 of file MissionController.cc.
References _recalcFlightPathSegmentsSignal(), _recalcMissionFlightStatusSignal(), PlanMasterController::managerVehicleChanged(), missionPlannedDistanceChanged(), multipleLandPatternsAllowedChanged(), qgcApp, Fact::rawValueChanged(), and recalcTerrainProfile().
~MissionController()
MissionController::~MissionController ()
Definition at line 65 of file MissionController.cc.
Member Function Documentation
_recalcFlightPathSegmentsSignal
void MissionController::_recalcFlightPathSegmentsSignal (void) signal
Referenced by LandingComplexItem::_init(), and MissionController().
_recalcMissionFlightStatusSignal
void MissionController::_recalcMissionFlightStatusSignal (void) signal
Referenced by MissionController().
addMissionToKML()
void MissionController::addMissionToKML (KMLPlanDomDocument & planKML)
Definition at line 233 of file MissionController.cc.
References KMLPlanDomDocument::addMission().
Referenced by PlanMasterController::saveToKml().
applyDefaultMissionAltitude()
void MissionController::applyDefaultMissionAltitude (void)
Updates the altitudes of the items in the current mission to the new default altitude.
Definition at line 1912 of file MissionController.cc.
References VisualMissionItem::applyNewAltitude(), QmlObjectListModel::count(), AppSettings::defaultMissionItemAltitude(), and QmlObjectListModel::value().
batteriesRequired()
int MissionController::batteriesRequired (void) const inline
-1 for not supported
Definition at line 293 of file MissionController.h.
References MissionFlightStatus_t::batteriesRequired.
batteriesRequiredChanged
void MissionController::batteriesRequiredChanged (int batteriesRequired) signal
batteryChangePoint()
int MissionController::batteryChangePoint (void) const inline
-1 for not supported, 0 for not needed
Definition at line 292 of file MissionController.h.
References MissionFlightStatus_t::batteryChangePoint.
batteryChangePointChanged
void MissionController::batteryChangePointChanged (int batteryChangePoint) signal
complexMissionItemNames()
QStringList MissionController::complexMissionItemNames (void) const
Definition at line 1868 of file MissionController.cc.
References Vehicle::multiRotor(), CorridorScanComplexItem::name, StructureScanComplexItem::name, SurveyComplexItem::name, and Vehicle::vtol().
complexMissionItemNamesChanged
void MissionController::complexMissionItemNamesChanged (void) signal
containsItems()
bool MissionController::containsItems (void) const final virtual
Implements PlanElementController.
Definition at line 1851 of file MissionController.cc.
References QmlObjectListModel::count().
Referenced by PlanMasterController::containsItems().
corridorScanComplexItemName()
QString MissionController::corridorScanComplexItemName (void) const
Definition at line 2434 of file MissionController.cc.
References CorridorScanComplexItem::name.
currentMissionIndex()
int MissionController::currentMissionIndex (void) const
Definition at line 1772 of file MissionController.cc.
References PlanElementController::_flyView, MissionManager::currentIndex(), Vehicle::firmwarePlugin(), and FirmwarePlugin::sendHomePositionToVehicle().
currentMissionIndexChanged
void MissionController::currentMissionIndexChanged (int currentMissionIndex) signal
currentPlanViewItem()
VisualMissionItem * MissionController::currentPlanViewItem (void) const inline
Definition at line 267 of file MissionController.h.
currentPlanViewSeqNum()
int MissionController::currentPlanViewSeqNum (void) const inline
Definition at line 280 of file MissionController.h.
currentPlanViewVIIndex()
int MissionController::currentPlanViewVIIndex (void) const inline
Definition at line 281 of file MissionController.h.
defaultsGroupIndex()
QPersistentModelIndex MissionController::defaultsGroupIndex (void) const inline
Definition at line 257 of file MissionController.h.
directionArrows()
QmlObjectListModel * MissionController::directionArrows (void) inline
Definition at line 263 of file MissionController.h.
dirty()
bool MissionController::dirty (void) const final virtual
Implements PlanElementController.
Definition at line 1805 of file MissionController.cc.
Referenced by setDirty().
fenceGroupIndex()
QPersistentModelIndex MissionController::fenceGroupIndex (void) const inline
Definition at line 259 of file MissionController.h.
globalAltitudeFrame()
QGroundControlQmlGlobal::AltitudeFrame MissionController::globalAltitudeFrame (void)
Definition at line 2472 of file MissionController.cc.
Referenced by insertComplexMissionItem().
globalAltitudeFrameChanged
void MissionController::globalAltitudeFrameChanged (void) signal
Referenced by setGlobalAltitudeFrame().
globalAltitudeFrameDefault()
QGroundControlQmlGlobal::AltitudeFrame MissionController::globalAltitudeFrameDefault (void)
Definition at line 2477 of file MissionController.cc.
References QGroundControlQmlGlobal::AltitudeFrameMixed, and QGroundControlQmlGlobal::AltitudeFrameRelative.
hasLandItemChanged
void MissionController::hasLandItemChanged (void) signal
Referenced by setCurrentPlanViewSeqNum().
homePositionSet()
bool MissionController::homePositionSet (void) const
Definition at line 1900 of file MissionController.cc.
References MissionSettingsItem::coordinate().
homePositionSetChanged
void MissionController::homePositionSetChanged (void) signal
insertCancelROIMissionItem()
VisualMissionItem * MissionController::insertCancelROIMissionItem (int visualItemIndex, bool makeCurrentItem = false)
Add a new Cancel ROI mission item to the list
Parameters
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 378 of file MissionController.cc.
References Vehicle::firmwarePlugin(), SimpleMissionItem::missionItem(), SimpleMissionItem::setCommand(), MissionItem::setParam1(), FirmwarePlugin::supportedMissionCommands(), and QGCMAVLinkTypes::VehicleClassGeneric.
insertComplexMissionItem()
VisualMissionItem * MissionController::insertComplexMissionItem (QString itemName, QGeoCoordinate mapCenterCoordinate, int visualItemIndex, bool makeCurrentItem = false)
Add a new complex mission item to the list
Parameters
itemName Name of complex item to create (from complexMissionItemNames)
mapCenterCoordinate coordinate for current center of map
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 389 of file MissionController.cc.
References PlanElementController::_flyView, PlanElementController::_masterController, QGroundControlQmlGlobal::AltitudeFrameMixed, globalAltitudeFrame(), CorridorScanComplexItem::name, FixedWingLandingComplexItem::name, StructureScanComplexItem::name, SurveyComplexItem::name, VTOLLandingComplexItem::name, and VisualMissionItem::setCoordinate().
Referenced by CorridorScanPlanCreator::createPlan(), StructureScanPlanCreator::createPlan(), SurveyPlanCreator::createPlan(), and insertLandItem().
insertComplexMissionItemFromKMLOrSHP()
VisualMissionItem * MissionController::insertComplexMissionItemFromKMLOrSHP (QString itemName, QString file, int visualItemIndex, bool makeCurrentItem = false)
Add a new complex mission item to the list
Parameters
itemName Name of complex item to create (from complexMissionItemNames)
file kml or shp file to load from shape from
coordinate Coordinate for item
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 423 of file MissionController.cc.
References PlanElementController::_flyView, PlanElementController::_masterController, CorridorScanComplexItem::name, StructureScanComplexItem::name, and SurveyComplexItem::name.
insertLandItem()
VisualMissionItem * MissionController::insertLandItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem = false)
Add a new land item to the list
Parameters
coordinate Coordinate for item
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 354 of file MissionController.cc.
References Vehicle::fixedWing(), insertComplexMissionItem(), FixedWingLandingComplexItem::name, VTOLLandingComplexItem::name, and Vehicle::vtol().
Referenced by CorridorScanPlanCreator::createPlan(), StructureScanPlanCreator::createPlan(), and SurveyPlanCreator::createPlan().
insertROIMissionItem()
VisualMissionItem * MissionController::insertROIMissionItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem = false)
Add a new ROI mission item to the list
Parameters
coordinate Coordinate for item
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 367 of file MissionController.cc.
References Vehicle::firmwarePlugin(), SimpleMissionItem::missionItem(), SimpleMissionItem::setCommand(), MissionItem::setParam1(), FirmwarePlugin::supportedMissionCommands(), and QGCMAVLinkTypes::VehicleClassGeneric.
insertSimpleMissionItem()
VisualMissionItem * MissionController::insertSimpleMissionItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem = false)
Add a new simple mission item to the list
Parameters
coordinate Coordinate for item
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 308 of file MissionController.cc.
insertTakeoffItem()
VisualMissionItem * MissionController::insertTakeoffItem (QGeoCoordinate coordinate, int visualItemIndex, bool makeCurrentItem = false)
Add a new takeoff item to the list
Parameters
coordinate Coordinate for item
visualItemIndex index to insert at, -1 for end of list
makeCurrentItem true: Make this item the current item
Returns
Newly created item
Definition at line 313 of file MissionController.cc.
References PlanElementController::_flyView, PlanElementController::_masterController, SimpleMissionItem::altitude(), QmlObjectListModel::append(), QmlObjectListModel::insert(), SimpleMissionItem::sequenceNumber(), SimpleMissionItem::setAltitudeFrame(), setCurrentPlanViewSeqNum(), SimpleMissionItem::setSequenceNumber(), SimpleMissionItem::specifiesAltitude(), and Vehicle::vtol().
Referenced by CorridorScanPlanCreator::createPlan(), StructureScanPlanCreator::createPlan(), and SurveyPlanCreator::createPlan().
isEmpty()
bool MissionController::isEmpty (void) const
Definition at line 2418 of file MissionController.cc.
References QmlObjectListModel::count().
Referenced by PlanMasterController::isEmpty().
isFirstLandingComplexItem()
bool MissionController::isFirstLandingComplexItem (const LandingComplexItem * item) const
Definition at line 2403 of file MissionController.cc.
References QmlObjectListModel::count(), and QmlObjectListModel::get().
Referenced by FixedWingLandingComplexItem::patternName(), and VTOLLandingComplexItem::patternName().
isInsertTakeoffValid()
bool MissionController::isInsertTakeoffValid (void) const
load()
bool MissionController::load (const QJsonObject & json, QString & errorString) final virtual
Implements PlanElementController.
Definition at line 875 of file MissionController.cc.
References errorString.
Referenced by PlanMasterController::loadFromFile().
loadFromVehicle()
void MissionController::loadFromVehicle (void) final virtual
Implements PlanElementController.
Definition at line 169 of file MissionController.cc.
References PlanElementController::_masterController, PlanManager::loadFromVehicle(), Vehicle::missionManager(), PlanMasterController::offline(), and syncInProgress().
Referenced by PlanMasterController::loadFromVehicle().
loadTextFile()
bool MissionController::loadTextFile (QFile & file, QString & errorString)
Definition at line 890 of file MissionController.cc.
References QGroundControlQmlGlobal::AltitudeFrameMixed, errorString, and setGlobalAltitudeFrame().
Referenced by PlanMasterController::loadFromFile().
maxAMSLAltitude()
double MissionController::maxAMSLAltitude (void) const inline
Definition at line 276 of file MissionController.h.
Referenced by TerrainProfile::updatePaintNode().
maxAMSLAltitudeChanged
void MissionController::maxAMSLAltitudeChanged (double maxAMSLAltitude) signal
minAMSLAltitude()
double MissionController::minAMSLAltitude (void) const inline
Definition at line 275 of file MissionController.h.
Referenced by TerrainProfile::updatePaintNode().
minAMSLAltitudeChanged
void MissionController::minAMSLAltitudeChanged (double minAMSLAltitude) signal
missionBoundingCubeChanged
void MissionController::missionBoundingCubeChanged (void) signal
missionCruiseDistance()
double MissionController::missionCruiseDistance (void) const inline
Definition at line 288 of file MissionController.h.
References MissionFlightStatus_t::cruiseDistance.
missionCruiseDistanceChanged
void MissionController::missionCruiseDistanceChanged (double missionCruiseDistance) signal
missionCruiseTime()
double MissionController::missionCruiseTime (void) const inline
Definition at line 289 of file MissionController.h.
References MissionFlightStatus_t::cruiseTime.
missionCruiseTimeChanged
void MissionController::missionCruiseTimeChanged (void) signal
missionGroupIndex()
QPersistentModelIndex MissionController::missionGroupIndex (void) const inline
Definition at line 258 of file MissionController.h.
missionHoverDistance()
double MissionController::missionHoverDistance (void) const inline
Definition at line 286 of file MissionController.h.
References MissionFlightStatus_t::hoverDistance.
missionHoverDistanceChanged
void MissionController::missionHoverDistanceChanged (double missionHoverDistance) signal
missionHoverTime()
double MissionController::missionHoverTime (void) const inline
Definition at line 287 of file MissionController.h.
References MissionFlightStatus_t::hoverTime.
missionHoverTimeChanged
void MissionController::missionHoverTimeChanged (void) signal
missionMaxTelemetry()
double MissionController::missionMaxTelemetry (void) const inline
Definition at line 290 of file MissionController.h.
References MissionFlightStatus_t::maxTelemetryDistance.
missionMaxTelemetryChanged
void MissionController::missionMaxTelemetryChanged (double missionMaxTelemetry) signal
missionPlannedDistance()
double MissionController::missionPlannedDistance (void) const inline
Definition at line 284 of file MissionController.h.
References MissionFlightStatus_t::plannedDistance.
missionPlannedDistanceChanged
void MissionController::missionPlannedDistanceChanged (double missionPlannedDistance) signal
Referenced by MissionController().
missionTime()
double MissionController::missionTime (void) const inline
Definition at line 285 of file MissionController.h.
References MissionFlightStatus_t::totalTime.
missionTimeChanged
void MissionController::missionTimeChanged (void) signal
missionTotalDistance()
double MissionController::missionTotalDistance (void) const inline
Definition at line 283 of file MissionController.h.
References MissionFlightStatus_t::totalDistance.
Referenced by TerrainProfile::updatePaintNode().
missionTotalDistanceChanged
void MissionController::missionTotalDistanceChanged (double missionTotalDistance) signal
multipleLandPatternsAllowed()
bool MissionController::multipleLandPatternsAllowed (void) const
Definition at line 346 of file MissionController.cc.
References PlanElementController::_masterController, PlanViewSettings::allowMultipleLandingPatterns(), PlanMasterController::managerVehicle(), and Vehicle::px4Firmware().
Referenced by setCurrentPlanViewSeqNum().
multipleLandPatternsAllowedChanged
void MissionController::multipleLandPatternsAllowedChanged (void) signal
Referenced by MissionController().
newItemsFromVehicle
void MissionController::newItemsFromVehicle (void) signal
offsetMission()
void MissionController::offsetMission (double eastMeters, double northMeters, double upMeters = 0.0, bool offsetTakeoffItems = false, bool offsetLandingItems = false)
Offsets all mission items which specify a coordinate by the specified ENU amounts in meters. Home altitude remains unchanged.
Parameters
eastMeters Distance to offset items to the east, in meters
northMeters Distance to offset items to the north, in meters
upMeters Distance to offset items upwards, in meters
offsetTakeoffItems If true, items identified as takeoff items (isTakeoffItem) will be offset
offsetLandingItems If true, items identified as landing items (isLandCommand) will be offset
Definition at line 2209 of file MissionController.cc.
References VisualMissionItem::applyNewAltitude(), VisualMissionItem::coordinate(), QmlObjectListModel::count(), VisualMissionItem::editableAlt(), QmlObjectListModel::get(), VisualMissionItem::isLandCommand(), VisualMissionItem::isStandaloneCoordinate(), VisualMissionItem::isTakeoffItem(), VisualMissionItem::setCoordinate(), setDirty(), VisualMissionItem::specifiesAltitudeOnly(), and VisualMissionItem::specifiesCoordinate().
planFileGroupIndex()
QPersistentModelIndex MissionController::planFileGroupIndex (void) const inline
Definition at line 256 of file MissionController.h.
plannedHomePosition()
QGeoCoordinate MissionController::plannedHomePosition (void) const
Definition at line 1891 of file MissionController.cc.
References MissionSettingsItem::coordinate().
Referenced by LandingComplexItem::amslEntryAlt(), SimpleMissionItem::amslEntryAlt(), StructureScanComplexItem::amslEntryAlt(), TransectStyleComplexItem::amslEntryAlt(), LandingComplexItem::amslExitAlt(), StructureScanComplexItem::maxAMSLAltitude(), TransectStyleComplexItem::maxAMSLAltitude(), StructureScanComplexItem::minAMSLAltitude(), and TransectStyleComplexItem::minAMSLAltitude().
plannedHomePositionChanged
void MissionController::plannedHomePositionChanged (QGeoCoordinate plannedHomePosition) signal
Referenced by LandingComplexItem::_init(), ComplexMissionItem::ComplexMissionItem(), and StructureScanComplexItem::StructureScanComplexItem().
planViewStateChanged
void MissionController::planViewStateChanged (void) signal
All plan-view properties are recomputed together in setCurrentPlanViewSeqNum, so one signal covers them all.
Referenced by setCurrentPlanViewSeqNum().
progressPct()
double MissionController::progressPct (void) const inline
Definition at line 269 of file MissionController.h.
progressPctChanged
void MissionController::progressPctChanged (double progressPct) signal
rallyGroupIndex()
QPersistentModelIndex MissionController::rallyGroupIndex (void) const inline
Definition at line 260 of file MissionController.h.
readyForSaveState()
int MissionController::readyForSaveState (void) const
Determines if the mission has all data needed to be saved or sent to the vehicle. IMPORTANT NOTE: The return value is a VisualMissionItem::ReadForSaveState value. It is an int here to work around a nightmare of circular header dependency problems.
Definition at line 910 of file MissionController.cc.
References QmlObjectListModel::count(), QmlObjectListModel::get(), VisualMissionItem::ReadyForSave, and VisualMissionItem::readyForSaveState().
Referenced by PlanMasterController::readyForSaveState().
recalcTerrainProfile
void MissionController::recalcTerrainProfile (void) signal
Referenced by ComplexMissionItem::_appendFlightPathSegment(), MissionController(), TerrainProfile::setMissionController(), and TransectStyleComplexItem::TransectStyleComplexItem().
removeAll()
void MissionController::removeAll (void) final virtual
Removes all from controller only.
Implements PlanElementController.
Definition at line 598 of file MissionController.cc.
References setDirty().
Referenced by PlanMasterController::removeAll().
removeAllFromVehicle()
void MissionController::removeAllFromVehicle (void) final virtual
Removes all from vehicle and controller Signals removeAllComplete when done
Implements PlanElementController.
Definition at line 1856 of file MissionController.cc.
References PlanElementController::_masterController, PlanMasterController::offline(), PlanManager::removeAll(), and syncInProgress().
Referenced by PlanMasterController::removeAllFromVehicle().
repositionMission()
void MissionController::repositionMission (const QGeoCoordinate & newHome, bool repositionTakeoffItems = true, bool repositionLandingItems = true)
Repositions all mission items which specify a coordinate around a new home coordinate. Requires a valid planned home position; otherwise the mission is not modified and a warning is logged.
Parameters
newHome New coordinate for the home item
repositionTakeoffItems If true, items identified as takeoff items (isTakeoffItem) will be repositioned
repositionLandingItems If true, items identified as landing items (isLandCommand) will be repositioned
Definition at line 2167 of file MissionController.cc.
References VisualMissionItem::coordinate(), MissionSettingsItem::coordinate(), QmlObjectListModel::count(), QmlObjectListModel::get(), VisualMissionItem::isLandCommand(), VisualMissionItem::isStandaloneCoordinate(), VisualMissionItem::isTakeoffItem(), VisualMissionItem::setCoordinate(), setDirty(), and VisualMissionItem::specifiesCoordinate().
resumeMission()
void MissionController::resumeMission (int resumeIndex)
Definition at line 1883 of file MissionController.cc.
References Vehicle::firmwarePlugin(), MissionManager::generateResumeMission(), and FirmwarePlugin::sendHomePositionToVehicle().
resumeMissionIndex()
int MissionController::resumeMissionIndex (void) const
Definition at line 1754 of file MissionController.cc.
References PlanElementController::_flyView, QmlObjectListModel::count(), Vehicle::firmwarePlugin(), MissionManager::lastCurrentIndex(), FirmwarePlugin::sendHomePositionToVehicle(), VisualMissionItem::sequenceNumber(), and QmlObjectListModel::value().
resumeMissionIndexChanged
void MissionController::resumeMissionIndexChanged (void) signal
resumeMissionReady
void MissionController::resumeMissionReady (void) signal
resumeMissionUploadFail
void MissionController::resumeMissionUploadFail (void) signal
rotateMission()
void MissionController::rotateMission (double degreesCW, bool rotateTakeoffItems = false, bool rotateLandingItems = false)
Rotates all mission items which specify a coordinate around the up axis of the home position. Complex items are rotated by moving their reference coordinate: their geometry and orientation are not modified. Requires a valid planned home position; otherwise the mission is not modified and a warning is logged.
Parameters
degreesCW Angle to rotate items by, in degrees clockwise
rotateTakeoffItems If true, items identified as takeoff items (isTakeoffItem) will be rotated
rotateLandingItems If true, items identified as landing items (isLandCommand) will be rotated
Definition at line 2270 of file MissionController.cc.
References VisualMissionItem::coordinate(), MissionSettingsItem::coordinate(), QmlObjectListModel::count(), QmlObjectListModel::get(), VisualMissionItem::isLandCommand(), VisualMissionItem::isStandaloneCoordinate(), VisualMissionItem::isTakeoffItem(), VisualMissionItem::setCoordinate(), setDirty(), and VisualMissionItem::specifiesCoordinate().
save()
void MissionController::save (QJsonObject & json) final virtual
Implements PlanElementController.
Definition at line 922 of file MissionController.cc.
References MissionSettingsItem::coordinate(), QmlObjectListModel::count(), Vehicle::defaultCruiseSpeed(), Vehicle::defaultHoverSpeed(), Vehicle::firmwareType(), QmlObjectListModel::get(), JsonHelper::jsonVersionKey, VisualMissionItem::save(), MissionItem::save(), JsonHelper::saveGeoCoordinate(), QmlObjectListModel::value(), and Vehicle::vehicleType().
Referenced by PlanMasterController::saveToJson().
sendItemsToVehicle()
void MissionController::sendItemsToVehicle (Vehicle * vehicle, QmlObjectListModel * visualMissionItems) static
Sends the mission items to the specified vehicle.
Definition at line 243 of file MissionController.cc.
References Vehicle::missionManager(), and PlanManager::writeMissionItems().
Referenced by sendToVehicle().
sendToVehicle()
void MissionController::sendToVehicle (void) final virtual
Sends the current plan element to the vehicle Signals sendComplete when done
Implements PlanElementController.
Definition at line 181 of file MissionController.cc.
References PlanElementController::_masterController, QmlObjectListModel::count(), PlanMasterController::offline(), sendItemsToVehicle(), setDirty(), and syncInProgress().
Referenced by PlanMasterController::sendToVehicle().
sendToVehiclePreCheck()
MissionController::SendToVehiclePreCheckState MissionController::sendToVehiclePreCheck (void)
Definition at line 2458 of file MissionController.cc.
References Vehicle::armed(), Vehicle::firmwareType(), Vehicle::flightMode(), Vehicle::isOfflineEditingVehicle(), Vehicle::missionFlightMode(), SendToVehiclePreCheckStateActiveMission, SendToVehiclePreCheckStateFirwmareVehicleMismatch, SendToVehiclePreCheckStateNoActiveVehicle, SendToVehiclePreCheckStateOk, QGCMAVLink::vehicleClass(), and Vehicle::vehicleType().
setCurrentPlanViewSeqNum()
void MissionController::setCurrentPlanViewSeqNum (int sequenceNumber, bool force)
Sets a new current mission item (PlanView).
Parameters
sequenceNumber - index for new item, -1 to clear current item
force - true: reset internals even if specified item is already selected
Definition at line 1992 of file MissionController.cc.
References PlanElementController::_masterController, PlanMasterController::controllerVehicle(), SimpleMissionItem::coordinate(), QmlObjectListModel::count(), QmlObjectListModel::get(), hasLandItemChanged(), VisualMissionItem::isStandaloneCoordinate(), SimpleMissionItem::isStandaloneCoordinate(), SimpleMissionItem::mavCommand(), multipleLandPatternsAllowed(), VisualMissionItem::parentItem(), planViewStateChanged(), VisualMissionItem::sequenceNumber(), VisualMissionItem::setHasCurrentChildItem(), VisualMissionItem::setIsCurrentItem(), VisualMissionItem::specifiesCoordinate(), SimpleMissionItem::specifiesCoordinate(), splitSegmentChanged(), Vehicle::supports(), PlanViewSettings::takeoffItemNotRequired(), and VehicleSupports::takeoffMissionCommand().
Referenced by CorridorScanPlanCreator::createPlan(), StructureScanPlanCreator::createPlan(), SurveyPlanCreator::createPlan(), and insertTakeoffItem().
setDirty()
void MissionController::setDirty (bool dirty) final virtual
Implements PlanElementController.
Definition at line 1811 of file MissionController.cc.
References dirty(), and QmlObjectListModel::setDirty().
Referenced by offsetMission(), PlanMasterController::removeAll(), removeAll(), repositionMission(), rotateMission(), and sendToVehicle().
setGlobalAltitudeFrame()
void MissionController::setGlobalAltitudeFrame (QGroundControlQmlGlobal::AltitudeFrame altFrame)
Definition at line 2486 of file MissionController.cc.
References globalAltitudeFrameChanged().
Referenced by loadTextFile().
setHomePosition()
void MissionController::setHomePosition (QGeoCoordinate coordinate)
Set the planned home position from a map click.
Definition at line 1905 of file MissionController.cc.
References MissionSettingsItem::setCoordinate().
showPlanFromManagerVehicle()
bool MissionController::showPlanFromManagerVehicle (void) final virtual
Implements PlanElementController.
Definition at line 1936 of file MissionController.cc.
References PlanElementController::_flyView, PlanElementController::_masterController, Vehicle::initialPlanRequestComplete(), PlanMasterController::offline(), and syncInProgress().
simpleFlightPathSegments()
QmlObjectListModel * MissionController::simpleFlightPathSegments (void) inline
Definition at line 262 of file MissionController.h.
splitSegmentChanged
void MissionController::splitSegmentChanged (void) signal
Referenced by setCurrentPlanViewSeqNum().
start()
void MissionController::start (bool flyView) final virtual
Should be called immediately upon Component.onCompleted.
Reimplemented from PlanElementController.
Definition at line 86 of file MissionController.cc.
References PlanElementController::_masterController, PlanMasterController::managerVehicleChanged(), and PlanElementController::start().
Referenced by PlanMasterController::startStaticActiveVehicle().
structureScanComplexItemName()
QString MissionController::structureScanComplexItemName (void) const
Definition at line 2439 of file MissionController.cc.
References StructureScanComplexItem::name.
supported()
bool MissionController::supported (void) const inline final virtual
true: controller is waiting for the current load to complete
Implements PlanElementController.
Definition at line 235 of file MissionController.h.
surveyComplexItemName()
QString MissionController::surveyComplexItemName (void) const
Definition at line 2429 of file MissionController.cc.
References SurveyComplexItem::name.
syncInProgress()
bool MissionController::syncInProgress (void) const final virtual
Implements PlanElementController.
Definition at line 1800 of file MissionController.cc.
References PlanManager::inProgress().
Referenced by loadFromVehicle(), removeAllFromVehicle(), sendToVehicle(), showPlanFromManagerVehicle(), and PlanMasterController::syncInProgress().
takeoffCoordinate()
QGeoCoordinate MissionController::takeoffCoordinate () inline
Definition at line 232 of file MissionController.h.
takeoffMissionItem()
TakeoffMissionItem * MissionController::takeoffMissionItem (void) const inline
Definition at line 268 of file MissionController.h.
takeoffMissionItemChanged
void MissionController::takeoffMissionItemChanged (void) signal
transformGroupIndex()
QPersistentModelIndex MissionController::transformGroupIndex (void) const inline
Definition at line 261 of file MissionController.h.
travelBoundingCube()
QGCGeoBoundingCube * MissionController::travelBoundingCube () inline
Definition at line 231 of file MissionController.h.
visualItems()
QmlObjectListModel * MissionController::visualItems (void) inline
Definition at line 254 of file MissionController.h.
Referenced by TerrainProfile::setMissionController().
visualItemsReset
void MissionController::visualItemsReset (void) signal
Referenced by TerrainProfile::setMissionController().
visualItemsTree()
QmlObjectTreeModel * MissionController::visualItemsTree (void) inline
Definition at line 255 of file MissionController.h.
Member Data Documentation
kDefaultsGroupRow
constexpr int MissionController::kDefaultsGroupRow = 1 static constexpr
Definition at line 304 of file MissionController.h.
kFenceGroupRow
constexpr int MissionController::kFenceGroupRow = 3 static constexpr
Definition at line 306 of file MissionController.h.
kGroupCount
constexpr int MissionController::kGroupCount = 6 static constexpr
Definition at line 309 of file MissionController.h.
kMissionGroupRow
constexpr int MissionController::kMissionGroupRow = 2 static constexpr
Definition at line 305 of file MissionController.h.
kPlanFileGroupRow
constexpr int MissionController::kPlanFileGroupRow = 0 static constexpr
Definition at line 303 of file MissionController.h.
kRallyGroupRow
constexpr int MissionController::kRallyGroupRow = 4 static constexpr
Definition at line 307 of file MissionController.h.
kTransformGroupRow
constexpr int MissionController::kTransformGroupRow = 5 static constexpr
Definition at line 308 of file MissionController.h.
visualItemIndexForObject
int MissionController::visualItemIndexForObject
< Used by Plan view only for interactive editing
< Includes AMSL altitude < true: Home position has been set by the user < Segment which show show + split ui element < Returns the item index two which a mission should be resumed. -1 indicates resume mission not available. < Minimum altitude associated with this mission. Used to calculate percentages for terrain status. < Maximum altitude associated with this mission. Used to calculate percentages for terrain status. Returns the visual item index for the given VisualMissionItem object, or -1 if not found
Definition at line 104 of file MissionController.h.
The documentation for this class was generated from the following files:
src/MissionManager/MissionController.h
src/MissionManager/MissionController.cc