QGroundControl: LandingComplexItem Class Reference
LandingComplexItem Class Reference abstract
#include <LandingComplexItem.h>
Signals
void finalApproachCoordinateChanged (QGeoCoordinate coordinate)
void slopeStartCoordinateChanged (QGeoCoordinate coordinate)
void landingCoordinateChanged (QGeoCoordinate coordinate)
void landingCoordSetChanged (bool landingCoordSet)
void altitudesAreRelativeChanged (bool altitudesAreRelative)
void _updateFlightPathSegmentsSignal (void)
Signals inherited from ComplexMissionItem
void patternNameChanged (void)
void complexDistanceChanged (void)
void boundingCubeChanged (void)
void greatestDistanceToChanged (void)
void presetNamesChanged (void)
void isIncompleteChanged (void)
void minAMSLAltitudeChanged (void)
void maxAMSLAltitudeChanged (void)
void terrainCollisionChanged (bool terrainCollision)
Signals inherited from VisualMissionItem
void altDifferenceChanged (double altDifference)
void altPercentChanged (double altPercent)
void terrainPercentChanged (double terrainPercent)
void terrainCollisionChanged (bool terrainCollision)
void azimuthChanged (double azimuth)
void commandDescriptionChanged (void)
void commandNameChanged (void)
void abbreviationChanged (void)
void coordinateChanged (const QGeoCoordinate &coordinate)
void entryCoordinateChanged (const QGeoCoordinate &entryCoordinate)
void exitCoordinateChanged (const QGeoCoordinate &exitCoordinate)
void dirtyChanged (bool dirty)
void distanceChanged (double distance)
void distanceFromStartChanged (double distanceFromStart)
void isCurrentItemChanged (bool isCurrentItem)
void hasCurrentChildItemChanged (bool hasCurrentChildItem)
void sequenceNumberChanged (int sequenceNumber)
void isSimpleItemChanged (bool isSimpleItem)
void isTakeoffItemChanged (bool isTakeoffItem)
void isLandCommandChanged (void)
void specifiesCoordinateChanged (void)
void isStandaloneCoordinateChanged (void)
void specifiesAltitudeOnlyChanged (void)
void specifiedFlightSpeedChanged (void)
void specifiedGimbalYawChanged (void)
void specifiedGimbalPitchChanged (void)
void specifiedVehicleYawChanged (void)
void lastSequenceNumberChanged (int sequenceNumber)
void missionGimbalYawChanged (double missionGimbalYaw)
void missionVehicleYawChanged (double missionVehicleYaw)
void terrainAltitudeChanged (double terrainAltitude)
void terrainQueryFailedChanged (bool terrainQueryFailed)
void additionalTimeDelayChanged (void)
void boundingCubeChanged (void)
void readyForSaveStateChanged (void)
void wizardModeChanged (bool wizardMode)
void parentItemChanged (VisualMissionItem *parentItem)
void amslEntryAltChanged (double alt)
void amslExitAltChanged (double alt)
void previousVTOLModeChanged (void)
void currentVTOLModeChanged (void)
Signals that this item has changed the VTOL mode (MAV_CMD_DO_VTOL_TRANSITION)
void exitCoordinateSameAsEntryChanged (bool exitCoordinateSameAsEntry)
Public Member Functions
LandingComplexItem (PlanMasterController *masterController, bool flyView)
Fact *finalApproachAltitude READ finalApproachAltitude CONSTANT (Fact *useDoChangeSpeed READ useDoChangeSpeed CONSTANT) 1(Fact *final ApproachSpeed READ final ApproachSpeed CONSTANT) 1(Fact *loiterRadius READ loiterRadius CONSTANT) 1(Fact *landingAltitude READ landingAltitude CONSTANT) 1(Fact *landingHeading READ landingHeading CONSTANT) 1(Fact *landingDistance READ landingDistance CONSTANT) 1(Fact *loiterClockwise READ loiterClockwise CONSTANT) 1(Fact *useLoiterToAlt READ useLoiterToAlt CONSTANT) 1(Fact *stopTakingPhotos READ stopTakingPhotos CONSTANT) 1(Fact *stopTakingVideo READ stopTakingVideo CONSTANT) 1(QGeoCoordinate final ApproachCoordinate READ final ApproachCoordinate WRITE setFinalApproachCoordinate NOTIFY final ApproachCoordinateChanged) 1(QGeoCoordinate slopeStartCoordinate READ slopeStartCoordinate NOTIFY slopeStartCoordinateChanged) 1(QGeoCoordinate landingCoordinate READ landingCoordinate WRITE setLandingCoordinate NOTIFY landingCoordinateChanged) 1(bool altitudesAreRelative READ altitudesAreRelative WRITE setAltitudesAreRelative NOTIFY altitudesAreRelativeChanged) 1(bool landingCoordSet READ landingCoordSet NOTIFY landingCoordSetChanged) 1 void setLandingHeadingToTakeoffHeading()
const Fact * finalApproachAltitude (void) const
const Fact * useDoChangeSpeed (void) const
const Fact * finalApproachSpeed (void) const
const Fact * loiterRadius (void) const
const Fact * loiterClockwise (void) const
const Fact * landingAltitude (void) const
const Fact * landingDistance (void) const
const Fact * landingHeading (void) const
const Fact * useLoiterToAlt (void) const
const Fact * stopTakingPhotos (void) const
const Fact * stopTakingVideo (void) const
Fact * finalApproachAltitude (void)
Fact * useDoChangeSpeed (void)
Fact * finalApproachSpeed (void)
Fact * loiterRadius (void)
Fact * loiterClockwise (void)
Fact * landingAltitude (void)
Fact * landingDistance (void)
Fact * landingHeading (void)
Fact * useLoiterToAlt (void)
Fact * stopTakingPhotos (void)
Fact * stopTakingVideo (void)
bool altitudesAreRelative (void) const
bool landingCoordSet (void) const
QGeoCoordinate landingCoordinate (void) const
QGeoCoordinate finalApproachCoordinate (void) const
QGeoCoordinate slopeStartCoordinate (void) const
void setLandingCoordinate (const QGeoCoordinate &coordinate)
void setFinalApproachCoordinate (const QGeoCoordinate &coordinate)
void setAltitudesAreRelative (bool altitudesAreRelative)
double complexDistance (void) const final
double greatestDistanceTo (const QGeoCoordinate &other) const final
int lastSequenceNumber (void) const final
bool dirty (void) const final
bool isSimpleItem (void) const final
bool isLandCommand (void) const final
bool isStandaloneCoordinate (void) const final
bool specifiesCoordinate (void) const final
bool specifiesAltitudeOnly (void) const final
QString commandDescription (void) const final
QString commandName (void) const final
QString abbreviation (void) const final
QGeoCoordinate coordinate (void) const final
QGeoCoordinate entryCoordinate (void) const final
QGeoCoordinate exitCoordinate (void) const final
int sequenceNumber (void) const final
double specifiedFlightSpeed (void) final
double specifiedGimbalYaw (void) final
double specifiedGimbalPitch (void) final
void appendMissionItems (QList< MissionItem * > &items, QObject *missionItemParent) final
void applyNewAltitude (double newAltitude) final
Adjust the altitude of the item if appropriate to the new altitude.
double additionalTimeDelay (void) const final
ReadyForSaveState readyForSaveState (void) const final
bool exitCoordinateSameAsEntry (void) const final
void setDirty (bool dirty) final
void setCoordinate (const QGeoCoordinate &coordinate) final
void setSequenceNumber (int sequenceNumber) final
double editableAlt (void) const final
double amslEntryAlt (void) const final
double amslExitAlt (void) const final
double minAMSLAltitude (void) const final
double maxAMSLAltitude (void) const final
Public Member Functions inherited from ComplexMissionItem
ComplexMissionItem (PlanMasterController *masterController, bool flyView)
const ComplexMissionItem & operator= (const ComplexMissionItem &other)
QString patternName READ patternName NOTIFY patternNameChanged (double complexDistance READ complexDistance NOTIFY complexDistanceChanged) 1(bool presetsSupported READ presetsSupported CONSTANT) 1(QStringList presetNames READ presetNames NOTIFY presetNamesChanged) 1(bool isIncomplete READ isIncomplete NOTIFY isIncompleteChanged) 1(double minAMSLAltitude READ minAMSLAltitude NOTIFY minAMSLAltitudeChanged) 1(double maxAMSLAltitude READ maxAMSLAltitude NOTIFY maxAMSLAltitudeChanged) 1(bool isSingleItem READ isSingleItem CONSTANT) 1(QmlObjectListModel *flightPathSegments READ flightPathSegments CONSTANT) 1(bool terrainCollision READ terrainCollision NOTIFY terrainCollisionChanged) QmlObjectListModel *flightPathSegments(void)
< Minimum altitude of all coordinates in item
virtual QString patternName (void) const =0
virtual bool terrainCollision (void) const
virtual bool load (const QJsonObject &complexObject, int sequenceNumber, QString &errorString)=0
virtual bool isSingleItem (void) const
virtual void loadPreset (const QString &name)
virtual void savePreset (const QString &name)
void deletePreset (const QString &name)
virtual QStringList presetNames (void)
virtual QString presetsSettingsGroup (void)
virtual void addKMLVisuals (KMLPlanDomDocument &domDocument)
bool presetsSupported (void)
bool isIncomplete (void) const
Public Member Functions inherited from VisualMissionItem
VisualMissionItem (PlanMasterController *masterController, bool flyView)
VisualMissionItem (const VisualMissionItem &other, bool flyView)
~VisualMissionItem ()
const VisualMissionItem & operator= (const VisualMissionItem &other)
bool homePosition READ homePosition CONSTANT (QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged) 1(double amslEntryAlt READ amslEntryAlt NOTIFY amslEntryAltChanged) 1(double terrainAltitude READ terrainAltitude NOTIFY terrainAltitudeChanged) 1(bool terrainQueryFailed READ terrainQueryFailed NOTIFY terrainQueryFailedChanged) 1(QGeoCoordinate entryCoordinate READ entryCoordinate NOTIFY entryCoordinateChanged) 1(QGeoCoordinate exitCoordinate READ exitCoordinate NOTIFY exitCoordinateChanged) 1(double amslExitAlt READ amslExitAlt NOTIFY amslExitAltChanged) 1(bool exitCoordinateSameAsEntry READ exitCoordinateSameAsEntry NOTIFY exitCoordinateSameAsEntryChanged) 1(QString commandDescription READ commandDescription NOTIFY commandDescriptionChanged) 1(QString commandName READ commandName NOTIFY commandNameChanged) 1(QString abbreviation READ abbreviation NOTIFY abbreviationChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) 1(bool isCurrentItem READ isCurrentItem WRITE setIsCurrentItem NOTIFY isCurrentItemChanged) 1(bool hasCurrentChildItem READ hasCurrentChildItem WRITE setHasCurrentChildItem NOTIFY hasCurrentChildItemChanged) 1(int sequenceNumber READ sequenceNumber WRITE setSequenceNumber NOTIFY sequenceNumberChanged) 1(int lastSequenceNumber READ lastSequenceNumber NOTIFY lastSequenceNumberChanged) 1(bool specifiesCoordinate READ specifiesCoordinate NOTIFY specifiesCoordinateChanged) 1(bool isStandaloneCoordinate READ isStandaloneCoordinate NOTIFY isStandaloneCoordinateChanged) 1(bool specifiesAltitudeOnly READ specifiesAltitudeOnly NOTIFY specifiesAltitudeOnlyChanged) 1(bool isSimpleItem READ isSimpleItem NOTIFY isSimpleItemChanged) 1(bool isTakeoffItem READ isTakeoffItem NOTIFY isTakeoffItemChanged) 1(bool isLandCommand READ isLandCommand NOTIFY isLandCommandChanged) 1(bool isSurveyItem READ isSurveyItem) 1(QString editorQml MEMBER _editorQml CONSTANT) 1(QString mapVisualQML READ mapVisualQML CONSTANT) 1(double specifiedFlightSpeed READ specifiedFlightSpeed NOTIFY specifiedFlightSpeedChanged) 1(double specifiedGimbalYaw READ specifiedGimbalYaw NOTIFY specifiedGimbalYawChanged) 1(double specifiedGimbalPitch READ specifiedGimbalPitch NOTIFY specifiedGimbalPitchChanged) 1(double specifiedVehicleYaw READ specifiedVehicleYaw NOTIFY specifiedVehicleYawChanged) 1(double missionGimbalYaw READ missionGimbalYaw NOTIFY missionGimbalYawChanged) 1(double missionVehicleYaw READ missionVehicleYaw NOTIFY missionVehicleYawChanged) 1(bool flyView READ flyView CONSTANT) 1(bool wizardMode READ wizardMode WRITE setWizardMode NOTIFY wizardModeChanged) 1(int previousVTOLMode MEMBER _previousVTOLMode NOTIFY previousVTOLModeChanged) 1(PlanMasterController *masterController READ masterController CONSTANT) 1(ReadyForSaveState readyForSaveState READ readyForSaveState NOTIFY readyForSaveStateChanged) 1(VisualMissionItem *parentItem READ parentItem WRITE setParentItem NOTIFY parentItemChanged) 1(QmlObjectListModel *childItems READ childItems CONSTANT) 1(QGCGeoBoundingCube *boundingCube READ boundingCube NOTIFY boundingCubeChanged) 1(double altDifference READ altDifference WRITE setAltDifference NOTIFY altDifferenceChanged) 1(double altPercent READ altPercent WRITE setAltPercent NOTIFY altPercentChanged) 1(double terrainPercent READ terrainPercent WRITE setTerrainPercent NOTIFY terrainPercentChanged) 1(bool terrainCollision READ terrainCollision WRITE setTerrainCollision NOTIFY terrainCollisionChanged) 1(double azimuth READ azimuth WRITE setAzimuth NOTIFY azimuthChanged) 1(double distance READ distance WRITE setDistance NOTIFY distanceChanged) 1(double distanceFromStart READ distanceFromStart WRITE setDistanceFromStart NOTIFY distanceFromStartChanged) bool homePosition(void) const
< true: This item is being used as a home position indicator
double altDifference (void) const
double altPercent (void) const
double terrainPercent (void) const
bool terrainCollision (void) const
double azimuth (void) const
double distance (void) const
double distanceFromStart (void) const
bool isCurrentItem (void) const
bool hasCurrentChildItem (void) const
double terrainAltitude (void) const
bool terrainQueryFailed (void) const
bool flyView (void) const
bool wizardMode (void) const
VisualMissionItem * parentItem (void)
QmlObjectListModel * childItems (void)
void setIsCurrentItem (bool isCurrentItem)
void setHasCurrentChildItem (bool hasCurrentChildItem)
void setAltDifference (double altDifference)
void setAltPercent (double altPercent)
void setTerrainPercent (double terrainPercent)
void setTerrainCollision (bool terrainCollision)
void setAzimuth (double azimuth)
void setDistance (double distance)
void setDistanceFromStart (double distanceFromStart)
void setWizardMode (bool wizardMode)
void setParentItem (VisualMissionItem *parentItem)
void setHomePositionSpecialCase (bool homePositionSpecialCase)
FlightPathSegment * simpleFlightPathSegment (void)
void setSimpleFlighPathSegment (FlightPathSegment *segment)
void clearSimpleFlighPathSegment (void)
PlanMasterController * masterController (void)
virtual bool isTakeoffItem (void) const
virtual bool isSurveyItem (void) const
virtual double specifiedVehicleYaw (void)
virtual QGCGeoBoundingCube * boundingCube (void)
virtual void setMissionFlightStatus (MissionController::MissionFlightStatus_t &missionFlightStatus)
virtual void save (QJsonArray &missionItems)=0
virtual QString mapVisualQML (void) const =0
double missionGimbalYaw (void) const
double missionVehicleYaw (void) const
void setMissionVehicleYaw (double vehicleYaw)
Static Public Attributes
static constexpr const char * finalApproachToLandDistanceName = "LandingDistance"
static constexpr const char * landingHeadingName = "LandingHeading"
static constexpr const char * finalApproachAltitudeName = "FinalApproachAltitude"
static constexpr const char * useDoChangeSpeedName = "UseDoChangeSpeed"
static constexpr const char * finalApproachSpeedName = "FinalApproachSpeed"
static constexpr const char * loiterRadiusName = "LoiterRadius"
static constexpr const char * loiterClockwiseName = "LoiterClockwise"
static constexpr const char * landingAltitudeName = "LandingAltitude"
static constexpr const char * useLoiterToAltName = "UseLoiterToAlt"
static constexpr const char * stopTakingPhotosName = "StopTakingPhotos"
static constexpr const char * stopTakingVideoName = "StopTakingVideo"
Static Public Attributes inherited from ComplexMissionItem
static constexpr const char * jsonComplexItemTypeKey = "complexItemType"
This mission item attribute specifies the type of the complex item.
Static Public Attributes inherited from VisualMissionItem
static constexpr const char * jsonTypeKey = "type"
Json file attribute which specifies the item type.
static constexpr const char * jsonTypeSimpleItemValue = "SimpleItem"
Item type is MISSION_ITEM.
static constexpr const char * jsonTypeComplexItemValue = "ComplexItem"
Item type is Complex Item.
Protected Types
typedef bool(* IsLandItemFunc) (const MissionItem &missionItem)
typedef LandingComplexItem *(* CreateItemFunc) (PlanMasterController *masterController, bool flyView)
Protected Slots
virtual void _updateFlightPathSegmentsDontCallDirectly (void)=0
void _recalcFromHeadingAndDistanceChange (void)
void _recalcFromCoordinateChange (void)
void _setDirty (void)
Protected Slots inherited from ComplexMissionItem
virtual void _segmentTerrainCollisionChanged (bool terrainCollision)
Protected Slots inherited from VisualMissionItem
void _amslEntryAltChanged (void)
void _amslExitAltChanged (void)
Protected Member Functions
virtual const Fact * _finalApproachAltitude (void) const =0
virtual const Fact * _useDoChangeSpeed (void) const =0
virtual const Fact * _finalApproachSpeed (void) const =0
virtual const Fact * _loiterRadius (void) const =0
virtual const Fact * _loiterClockwise (void) const =0
virtual const Fact * _landingAltitude (void) const =0
virtual const Fact * _landingDistance (void) const =0
virtual const Fact * _landingHeading (void) const =0
virtual const Fact * _useLoiterToAlt (void) const =0
virtual const Fact * _stopTakingPhotos (void) const =0
virtual const Fact * _stopTakingVideo (void) const =0
virtual void _calcGlideSlope (void)=0
virtual MissionItem * _createLandItem (int seqNum, bool altRel, double lat, double lon, double alt, QObject *parent)=0
void _init (void)
QPointF _rotatePoint (const QPointF &point, const QPointF &origin, double angle)
MissionItem * _createDoLandStartItem (int seqNum, QObject *parent)
MissionItem * _createDoChangeSpeedItem (int speedType, int speedValue, int throttlePercentage, int seqNum, QObject *parent)
MissionItem * _createFinalApproachItem (int seqNum, QObject *parent)
QJsonObject _save (void)
bool _load (const QJsonObject &complexObject, int sequenceNumber, const QString &jsonComplexItemTypeValue, bool useDeprecatedRelAltKeys, QString &errorString)
Protected Member Functions inherited from ComplexMissionItem
void _savePresetJson (const QString &name, QJsonObject &presetObject)
QJsonObject _loadPresetJson (const QString &name)
void _appendFlightPathSegment (FlightPathSegment::SegmentType segmentType, const QGeoCoordinate &coord1, double coord1AMSLAlt, const QGeoCoordinate &coord2, double coord2AMSLAlt)
Protected Member Functions inherited from VisualMissionItem
void _setBoundingCube (QGCGeoBoundingCube bc)
Static Protected Member Functions
static bool _scanForItems (QmlObjectListModel *visualItems, bool flyView, PlanMasterController *masterController, IsLandItemFunc isLandItemFunc, CreateItemFunc createItemFunc)
static bool _scanForItem (QmlObjectListModel *visualItems, int &startIndex, bool flyView, PlanMasterController *masterController, IsLandItemFunc isLandItemFunc, CreateItemFunc createItemFunc)
Protected Attributes
int _sequenceNumber = 0
bool _dirty = false
QGeoCoordinate _finalApproachCoordinate
QGeoCoordinate _slopeStartCoordinate
QGeoCoordinate _landingCoordinate
bool _landingCoordSet = false
bool _ignoreRecalcSignals = false
bool _altitudesAreRelative = true
Protected Attributes inherited from ComplexMissionItem
bool _isIncomplete = true
int _cTerrainCollisionSegments = 0
QmlObjectListModel _flightPathSegments
QMap< QString, FactMetaData * > _metaDataMap
Protected Attributes inherited from VisualMissionItem
bool _flyView = false
bool _isCurrentItem = false
bool _hasCurrentChildItem = false
bool _dirty = false
bool _homePositionSpecialCase = false
true: This item is being used as a ui home position indicator
bool _wizardMode = false
true: Item editor is showing wizard completion panel
double _terrainAltitude = qQNaN()
Altitude of terrain at coordinate position, NaN for not known.
bool _terrainQueryFailed = false
true: Last terrain query failed
double _altDifference = 0
Difference in altitude from previous waypoint.
double _altPercent = 0
Percent of total altitude change in mission.
double _terrainPercent = qQNaN()
Percent of terrain altitude for coordinate.
bool _terrainCollision = false
true: item collides with terrain
double _azimuth = 0
Azimuth to previous waypoint.
double _distance = 0
Distance to previous waypoint.
double _distanceFromStart = 0
Flight path cumalative horizontal distance from home point to this item.
QString _editorQml
Qml resource for editing item.
double _missionGimbalYaw = qQNaN()
double _missionVehicleYaw = qQNaN()
QGCMAVLinkTypes::VehicleClass_t _previousVTOLMode = QGCMAVLinkTypes::VehicleClassGeneric
Generic == unknown.
PlanMasterController * _masterController = nullptr
MissionController * _missionController = nullptr
Vehicle * _controllerVehicle = nullptr
FlightPathSegment * _simpleFlightPathSegment = nullptr
The simple item flight segment (if any) which starts with this visual item.
VisualMissionItem * _parentItem = nullptr
QGCGeoBoundingCube _boundingCube
The bounding "cube" of this element.
QmlObjectListModel _childItems
This is used to reference any subsequent mission items which do not specify a coordinate.
Static Protected Attributes
static constexpr const char * _jsonDeprecatedLandingAltitudeRelativeKey = "landAltitudeRelative"
static constexpr const char * _jsonDeprecatedLoiterAltitudeRelativeKey = "loiterAltitudeRelative"
static constexpr const char * _jsonDeprecatedLoiterCoordinateKey = "loiterCoordinate"
static constexpr const char * _jsonFinalApproachCoordinateKey = "landingApproachCoordinate"
static constexpr const char * _jsonUseDoChangeSpeedKey = "useDoChangeSpeed"
static constexpr const char * _jsonFinalApproachSpeedKey = "finalApproachSpeed"
static constexpr const char * _jsonLoiterRadiusKey = "loiterRadius"
static constexpr const char * _jsonLoiterClockwiseKey = "loiterClockwise"
static constexpr const char * _jsonLandingCoordinateKey = "landCoordinate"
static constexpr const char * _jsonAltitudesAreRelativeKey = "altitudesAreRelative"
static constexpr const char * _jsonUseLoiterToAltKey = "useLoiterToAlt"
static constexpr const char * _jsonStopTakingPhotosKey = "stopTakingPhotos"
static constexpr const char * _jsonStopTakingVideoKey = "stopVideoPhotos"
Static Protected Attributes inherited from ComplexMissionItem
static constexpr const char * _presetSettingsKey = "_presets"
Additional Inherited Members
Public Types inherited from VisualMissionItem
enum ReadyForSaveState { ReadyForSave , NotReadyForSaveTerrain , NotReadyForSaveData }
Detailed Description
Definition at line 15 of file LandingComplexItem.h.
Member Typedef Documentation
CreateItemFunc
typedef LandingComplexItem *(* LandingComplexItem::CreateItemFunc) (PlanMasterController *masterController, bool flyView) protected
Definition at line 164 of file LandingComplexItem.h.
IsLandItemFunc
typedef bool(* LandingComplexItem::IsLandItemFunc) (const MissionItem &missionItem) protected
Definition at line 163 of file LandingComplexItem.h.
Constructor & Destructor Documentation
LandingComplexItem()
LandingComplexItem::LandingComplexItem (PlanMasterController * masterController, bool flyView)
Definition at line 18 of file LandingComplexItem.cc.
References _updateFlightPathSegmentsDontCallDirectly(), _updateFlightPathSegmentsSignal(), and qgcApp.
Member Function Documentation
_calcGlideSlope()
virtual void LandingComplexItem::_calcGlideSlope (void) protected pure virtual
Referenced by _load(), _recalcFromCoordinateChange(), and _recalcFromHeadingAndDistanceChange().
_createDoChangeSpeedItem()
MissionItem * LandingComplexItem::_createDoChangeSpeedItem (int speedType, int speedValue, int throttlePercentage, int seqNum, QObject * parent) protected
Definition at line 386 of file LandingComplexItem.cc.
Referenced by appendMissionItems().
_createDoLandStartItem()
MissionItem * LandingComplexItem::_createDoLandStartItem (int seqNum, QObject * parent) protected
Definition at line 348 of file LandingComplexItem.cc.
References _altitudesAreRelative, VisualMissionItem::_controllerVehicle, _finalApproachAltitude(), _finalApproachCoordinate, VisualMissionItem::_masterController, VisualMissionItem::_previousVTOLMode, Vehicle::apmFirmware(), MissionCommandTree::getUIInfo(), MissionCommandTree::instance(), PlanMasterController::managerVehicle(), MissionCommandUIInfo::specifiesCoordinate(), and Vehicle::versionCompare().
Referenced by appendMissionItems().
_createFinalApproachItem()
MissionItem * LandingComplexItem::_createFinalApproachItem (int seqNum, QObject * parent) protected
Definition at line 398 of file LandingComplexItem.cc.
References _altitudesAreRelative, _finalApproachAltitude(), _finalApproachCoordinate, _loiterClockwise(), loiterRadius(), and useLoiterToAlt().
Referenced by appendMissionItems().
_createLandItem()
virtual MissionItem * LandingComplexItem::_createLandItem (int seqNum, bool altRel, double lat, double lon, double alt, QObject * parent) protected pure virtual
Referenced by appendMissionItems().
_finalApproachAltitude()
virtual const Fact * LandingComplexItem::_finalApproachAltitude (void) const protected pure virtual
Referenced by _createDoLandStartItem(), _createFinalApproachItem(), finalApproachAltitude(), and finalApproachAltitude().
_finalApproachSpeed()
virtual const Fact * LandingComplexItem::_finalApproachSpeed (void) const protected pure virtual
Referenced by finalApproachSpeed(), and finalApproachSpeed().
_init()
void LandingComplexItem::_init (void) protected
Definition at line 28 of file LandingComplexItem.cc.
References VisualMissionItem::_amslEntryAltChanged(), VisualMissionItem::_amslExitAltChanged(), VisualMissionItem::_masterController, VisualMissionItem::_missionController, MissionController::_recalcFlightPathSegmentsSignal(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _setDirty(), _updateFlightPathSegmentsSignal(), altitudesAreRelativeChanged(), VisualMissionItem::amslEntryAltChanged(), VisualMissionItem::amslExitAltChanged(), Vehicle::apmFirmware(), ComplexMissionItem::complexDistanceChanged(), PlanMasterController::controllerVehicle(), VisualMissionItem::coordinateChanged(), VisualMissionItem::entryCoordinateChanged(), VisualMissionItem::exitCoordinateChanged(), finalApproachAltitude(), finalApproachCoordinateChanged(), finalApproachSpeed(), landingAltitude(), landingCoordinateChanged(), landingCoordSetChanged(), landingDistance(), landingHeading(), loiterClockwise(), loiterRadius(), ComplexMissionItem::maxAMSLAltitudeChanged(), ComplexMissionItem::minAMSLAltitudeChanged(), ComplexMissionItem::patternNameChanged(), MissionController::plannedHomePositionChanged(), Fact::rawValueChanged(), VisualMissionItem::readyForSaveStateChanged(), slopeStartCoordinateChanged(), stopTakingPhotos(), stopTakingVideo(), useDoChangeSpeed(), useLoiterToAlt(), Fact::valueChanged(), and VisualMissionItem::wizardModeChanged().
_landingAltitude()
virtual const Fact * LandingComplexItem::_landingAltitude (void) const protected pure virtual
Referenced by landingAltitude(), and landingAltitude().
_landingDistance()
virtual const Fact * LandingComplexItem::_landingDistance (void) const protected pure virtual
Referenced by landingDistance(), and landingDistance().
_landingHeading()
virtual const Fact * LandingComplexItem::_landingHeading (void) const protected pure virtual
Referenced by landingHeading(), and landingHeading().
_load()
bool LandingComplexItem::_load (const QJsonObject & complexObject, int sequenceNumber, const QString & jsonComplexItemTypeValue, bool useDeprecatedRelAltKeys, QString & errorString) protected
Definition at line 727 of file LandingComplexItem.cc.
References _altitudesAreRelative, _calcGlideSlope(), _finalApproachCoordinate, _ignoreRecalcSignals, _jsonAltitudesAreRelativeKey, _jsonDeprecatedLandingAltitudeRelativeKey, _jsonDeprecatedLoiterAltitudeRelativeKey, _jsonDeprecatedLoiterCoordinateKey, _jsonFinalApproachCoordinateKey, _jsonFinalApproachSpeedKey, _jsonLandingCoordinateKey, _jsonLoiterClockwiseKey, _jsonLoiterRadiusKey, _jsonStopTakingPhotosKey, _jsonStopTakingVideoKey, _jsonUseDoChangeSpeedKey, _jsonUseLoiterToAltKey, _landingCoordinate, _landingCoordSet, _recalcFromCoordinateChange(), coordinate(), errorString, finalApproachAltitude(), finalApproachCoordinateChanged(), finalApproachSpeed(), ComplexMissionItem::jsonComplexItemTypeKey, VisualMissionItem::jsonTypeComplexItemValue, VisualMissionItem::jsonTypeKey, JsonHelper::jsonVersionKey, landingAltitude(), landingCoordinateChanged(), JsonHelper::loadGeoCoordinate(), loiterClockwise(), loiterRadius(), qgcApp, sequenceNumber(), setSequenceNumber(), stopTakingPhotos(), stopTakingVideo(), useDoChangeSpeed(), useLoiterToAlt(), and JsonHelper::validateKeys().
Referenced by FixedWingLandingComplexItem::load(), and VTOLLandingComplexItem::load().
_loiterClockwise()
virtual const Fact * LandingComplexItem::_loiterClockwise (void) const protected pure virtual
Referenced by _createFinalApproachItem(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), loiterClockwise(), and loiterClockwise().
_loiterRadius()
virtual const Fact * LandingComplexItem::_loiterRadius (void) const protected pure virtual
Referenced by loiterRadius(), and loiterRadius().
_recalcFromCoordinateChange
void LandingComplexItem::_recalcFromCoordinateChange (void) protected slot
Definition at line 261 of file LandingComplexItem.cc.
References _calcGlideSlope(), _finalApproachCoordinate, _ignoreRecalcSignals, _landingCoordinate, _landingCoordSet, _loiterClockwise(), _slopeStartCoordinate, VisualMissionItem::distance(), landingDistance(), landingHeading(), loiterRadius(), slopeStartCoordinateChanged(), and useLoiterToAlt().
Referenced by _init(), _load(), and _scanForItem().
_recalcFromHeadingAndDistanceChange
void LandingComplexItem::_recalcFromHeadingAndDistanceChange (void) protected slot
Definition at line 149 of file LandingComplexItem.cc.
References _calcGlideSlope(), _finalApproachCoordinate, _ignoreRecalcSignals, _landingCoordinate, _landingCoordSet, _loiterClockwise(), _slopeStartCoordinate, VisualMissionItem::distance(), finalApproachAltitude(), finalApproachCoordinateChanged(), landingDistance(), landingHeading(), loiterRadius(), slopeStartCoordinateChanged(), and useLoiterToAlt().
Referenced by _init(), setCoordinate(), and setLandingCoordinate().
_rotatePoint()
QPointF LandingComplexItem::_rotatePoint (const QPointF & point, const QPointF & origin, double angle) protected
Definition at line 138 of file LandingComplexItem.cc.
_save()
QJsonObject LandingComplexItem::_save (void) protected
Definition at line 697 of file LandingComplexItem.cc.
References _altitudesAreRelative, _finalApproachCoordinate, _jsonAltitudesAreRelativeKey, _jsonFinalApproachCoordinateKey, _jsonFinalApproachSpeedKey, _jsonLandingCoordinateKey, _jsonLoiterClockwiseKey, _jsonLoiterRadiusKey, _jsonStopTakingPhotosKey, _jsonStopTakingVideoKey, _jsonUseDoChangeSpeedKey, _jsonUseLoiterToAltKey, _landingCoordinate, coordinate(), finalApproachAltitude(), finalApproachSpeed(), landingAltitude(), loiterClockwise(), loiterRadius(), JsonHelper::saveGeoCoordinate(), stopTakingPhotos(), stopTakingVideo(), useDoChangeSpeed(), and useLoiterToAlt().
Referenced by FixedWingLandingComplexItem::save(), and VTOLLandingComplexItem::save().
_scanForItem()
bool LandingComplexItem::_scanForItem (QmlObjectListModel * visualItems, int & startIndex, bool flyView, PlanMasterController * masterController, IsLandItemFunc isLandItemFunc, CreateItemFunc createItemFunc) static protected
Definition at line 454 of file LandingComplexItem.cc.
References _altitudesAreRelative, _ignoreRecalcSignals, _landingCoordinate, _landingCoordSet, _recalcFromCoordinateChange(), Vehicle::apmFirmware(), MissionItem::command(), QmlObjectListModel::count(), finalApproachAltitude(), finalApproachSpeed(), VisualMissionItem::flyView(), MissionItem::frame(), QmlObjectListModel::insert(), landingAltitude(), loiterClockwise(), loiterRadius(), PlanMasterController::managerVehicle(), VisualMissionItem::masterController(), SimpleMissionItem::missionItem(), MissionItem::param1(), MissionItem::param2(), MissionItem::param3(), MissionItem::param4(), MissionItem::param5(), MissionItem::param6(), MissionItem::param7(), QmlObjectListModel::removeAt(), CameraSection::scanStopTakingPhotos(), CameraSection::scanStopTakingVideo(), setDirty(), setFinalApproachCoordinate(), stopTakingPhotos(), CameraSection::stopTakingPhotosCommandCount(), stopTakingVideo(), CameraSection::stopTakingVideoCommandCount(), useDoChangeSpeed(), useLoiterToAlt(), and QmlObjectListModel::value().
Referenced by _scanForItems().
_scanForItems()
bool LandingComplexItem::_scanForItems (QmlObjectListModel * visualItems, bool flyView, PlanMasterController * masterController, IsLandItemFunc isLandItemFunc, CreateItemFunc createItemFunc) static protected
Definition at line 431 of file LandingComplexItem.cc.
References _scanForItem(), QmlObjectListModel::count(), VisualMissionItem::flyView(), and VisualMissionItem::masterController().
Referenced by FixedWingLandingComplexItem::scanForItems(), and VTOLLandingComplexItem::scanForItems().
_setDirty
void LandingComplexItem::_setDirty (void) protected slot
Definition at line 632 of file LandingComplexItem.cc.
References setDirty().
Referenced by _init(), and FixedWingLandingComplexItem::FixedWingLandingComplexItem().
_stopTakingPhotos()
virtual const Fact * LandingComplexItem::_stopTakingPhotos (void) const protected pure virtual
Referenced by stopTakingPhotos(), and stopTakingPhotos().
_stopTakingVideo()
virtual const Fact * LandingComplexItem::_stopTakingVideo (void) const protected pure virtual
Referenced by stopTakingVideo(), and stopTakingVideo().
_updateFlightPathSegmentsDontCallDirectly
virtual void LandingComplexItem::_updateFlightPathSegmentsDontCallDirectly (void) protected pure virtual slot
Referenced by LandingComplexItem().
_updateFlightPathSegmentsSignal
void LandingComplexItem::_updateFlightPathSegmentsSignal (void) signal
Referenced by _init(), and LandingComplexItem().
_useDoChangeSpeed()
virtual const Fact * LandingComplexItem::_useDoChangeSpeed (void) const protected pure virtual
Referenced by useDoChangeSpeed(), and useDoChangeSpeed().
_useLoiterToAlt()
virtual const Fact * LandingComplexItem::_useLoiterToAlt (void) const protected pure virtual
Referenced by useLoiterToAlt(), and useLoiterToAlt().
abbreviation()
QString LandingComplexItem::abbreviation (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 91 of file LandingComplexItem.h.
additionalTimeDelay()
double LandingComplexItem::additionalTimeDelay (void) const inline final virtual
Returns
Amount of additional time delay in seconds needed to fly this item
Implements VisualMissionItem.
Definition at line 101 of file LandingComplexItem.h.
altitudesAreRelative()
bool LandingComplexItem::altitudesAreRelative (void) const inline
Definition at line 67 of file LandingComplexItem.h.
References _altitudesAreRelative.
Referenced by setAltitudesAreRelative().
altitudesAreRelativeChanged
void LandingComplexItem::altitudesAreRelativeChanged (bool altitudesAreRelative) signal
Referenced by _init(), and setAltitudesAreRelative().
amslEntryAlt()
double LandingComplexItem::amslEntryAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 664 of file LandingComplexItem.cc.
References _altitudesAreRelative, VisualMissionItem::_missionController, finalApproachAltitude(), and MissionController::plannedHomePosition().
Referenced by maxAMSLAltitude().
amslExitAlt()
double LandingComplexItem::amslExitAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 669 of file LandingComplexItem.cc.
References _altitudesAreRelative, VisualMissionItem::_missionController, landingAltitude(), and MissionController::plannedHomePosition().
Referenced by minAMSLAltitude().
appendMissionItems()
void LandingComplexItem::appendMissionItems (QList< MissionItem * > & items, QObject * missionItemParent) final virtual
Returns the mission items associated with the complex item. Caller is responsible for freeing.
Parameters
items List to append to
missionItemParent Parent object for newly created MissionItems
Implements VisualMissionItem.
Definition at line 316 of file LandingComplexItem.cc.
References _altitudesAreRelative, _createDoChangeSpeedItem(), _createDoLandStartItem(), _createFinalApproachItem(), _createLandItem(), _landingCoordinate, _sequenceNumber, CameraSection::appendStopTakingPhotos(), CameraSection::appendStopTakingVideo(), finalApproachSpeed(), landingAltitude(), stopTakingPhotos(), stopTakingVideo(), and useDoChangeSpeed().
applyNewAltitude()
void LandingComplexItem::applyNewAltitude (double newAltitude) final virtual
Adjust the altitude of the item if appropriate to the new altitude.
Implements VisualMissionItem.
Definition at line 614 of file LandingComplexItem.cc.
References finalApproachAltitude().
commandDescription()
QString LandingComplexItem::commandDescription (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 89 of file LandingComplexItem.h.
commandName()
QString LandingComplexItem::commandName (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 90 of file LandingComplexItem.h.
complexDistance()
double LandingComplexItem::complexDistance (void) const final virtual
Returns
The distance covered the complex mission item in meters. Signals complexDistanceChanged
Implements ComplexMissionItem.
Definition at line 108 of file LandingComplexItem.cc.
References finalApproachCoordinate(), landingCoordinate(), and slopeStartCoordinate().
CONSTANT()
Fact *finalApproachAltitude READ finalApproachAltitude LandingComplexItem::CONSTANT (Fact *useDoChangeSpeed READ useDoChangeSpeed CONSTANT) final
coordinate()
QGeoCoordinate LandingComplexItem::coordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 92 of file LandingComplexItem.h.
References exitCoordinate().
Referenced by _load(), _save(), setCoordinate(), setFinalApproachCoordinate(), and setLandingCoordinate().
dirty()
bool LandingComplexItem::dirty (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 83 of file LandingComplexItem.h.
References _dirty.
Referenced by setDirty().
editableAlt()
double LandingComplexItem::editableAlt (void) const final virtual
Implements VisualMissionItem.
Definition at line 659 of file LandingComplexItem.cc.
References finalApproachAltitude().
entryCoordinate()
QGeoCoordinate LandingComplexItem::entryCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 93 of file LandingComplexItem.h.
References _finalApproachCoordinate.
exitCoordinate()
QGeoCoordinate LandingComplexItem::exitCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 94 of file LandingComplexItem.h.
References _landingCoordinate.
Referenced by coordinate().
exitCoordinateSameAsEntry()
bool LandingComplexItem::exitCoordinateSameAsEntry (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 103 of file LandingComplexItem.h.
finalApproachAltitude() [1/2]
Fact * LandingComplexItem::finalApproachAltitude (void) inline
Definition at line 55 of file LandingComplexItem.h.
References _finalApproachAltitude().
finalApproachAltitude() [2/2]
const Fact * LandingComplexItem::finalApproachAltitude (void) const inline
Definition at line 43 of file LandingComplexItem.h.
References _finalApproachAltitude().
Referenced by _init(), _load(), _recalcFromHeadingAndDistanceChange(), _save(), _scanForItem(), amslEntryAlt(), applyNewAltitude(), and editableAlt().
finalApproachCoordinate()
QGeoCoordinate LandingComplexItem::finalApproachCoordinate (void) const inline
Definition at line 70 of file LandingComplexItem.h.
References _finalApproachCoordinate.
Referenced by complexDistance().
finalApproachCoordinateChanged
void LandingComplexItem::finalApproachCoordinateChanged (QGeoCoordinate coordinate) signal
Referenced by _init(), _load(), _recalcFromHeadingAndDistanceChange(), and setFinalApproachCoordinate().
finalApproachSpeed() [1/2]
Fact * LandingComplexItem::finalApproachSpeed (void) inline
Definition at line 57 of file LandingComplexItem.h.
References _finalApproachSpeed().
finalApproachSpeed() [2/2]
const Fact * LandingComplexItem::finalApproachSpeed (void) const inline
Definition at line 45 of file LandingComplexItem.h.
References _finalApproachSpeed().
Referenced by _init(), _load(), _save(), _scanForItem(), and appendMissionItems().
greatestDistanceTo()
double LandingComplexItem::greatestDistanceTo (const QGeoCoordinate & other) const final virtual
Get the point of complex mission item furthest away from a coordinate
Parameters
other QGeoCoordinate to which distance is calculated
Returns
the greatest distance from any point of the complex item to some coordinate Signals greatestDistanceToChanged
Implements ComplexMissionItem.
Definition at line 692 of file LandingComplexItem.cc.
References _finalApproachCoordinate, and _landingCoordinate.
isLandCommand()
bool LandingComplexItem::isLandCommand (void) const inline final virtual
Reimplemented from VisualMissionItem.
Definition at line 85 of file LandingComplexItem.h.
isSimpleItem()
bool LandingComplexItem::isSimpleItem (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 84 of file LandingComplexItem.h.
isStandaloneCoordinate()
bool LandingComplexItem::isStandaloneCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 86 of file LandingComplexItem.h.
landingAltitude() [1/2]
Fact * LandingComplexItem::landingAltitude (void) inline
Definition at line 60 of file LandingComplexItem.h.
References _landingAltitude().
landingAltitude() [2/2]
const Fact * LandingComplexItem::landingAltitude (void) const inline
Definition at line 48 of file LandingComplexItem.h.
References _landingAltitude().
Referenced by _init(), _load(), _save(), _scanForItem(), amslExitAlt(), and appendMissionItems().
landingCoordinate()
QGeoCoordinate LandingComplexItem::landingCoordinate (void) const inline
Definition at line 69 of file LandingComplexItem.h.
References _landingCoordinate.
Referenced by complexDistance().
landingCoordinateChanged
void LandingComplexItem::landingCoordinateChanged (QGeoCoordinate coordinate) signal
Referenced by _init(), _load(), and setLandingCoordinate().
landingCoordSet()
bool LandingComplexItem::landingCoordSet (void) const inline
Definition at line 68 of file LandingComplexItem.h.
References _landingCoordSet.
landingCoordSetChanged
void LandingComplexItem::landingCoordSetChanged (bool landingCoordSet) signal
Referenced by _init(), and setLandingCoordinate().
landingDistance() [1/2]
Fact * LandingComplexItem::landingDistance (void) inline
Definition at line 61 of file LandingComplexItem.h.
References _landingDistance().
landingDistance() [2/2]
const Fact * LandingComplexItem::landingDistance (void) const inline
Definition at line 49 of file LandingComplexItem.h.
References _landingDistance().
Referenced by _init(), _recalcFromCoordinateChange(), and _recalcFromHeadingAndDistanceChange().
landingHeading() [1/2]
Fact * LandingComplexItem::landingHeading (void) inline
Definition at line 62 of file LandingComplexItem.h.
References _landingHeading().
landingHeading() [2/2]
const Fact * LandingComplexItem::landingHeading (void) const inline
Definition at line 50 of file LandingComplexItem.h.
References _landingHeading().
Referenced by _init(), _recalcFromCoordinateChange(), and _recalcFromHeadingAndDistanceChange().
lastSequenceNumber()
int LandingComplexItem::lastSequenceNumber (void) const final virtual
Implements VisualMissionItem.
Definition at line 307 of file LandingComplexItem.cc.
References _sequenceNumber, stopTakingPhotos(), and stopTakingVideo().
Referenced by setSequenceNumber().
loiterClockwise() [1/2]
Fact * LandingComplexItem::loiterClockwise (void) inline
Definition at line 59 of file LandingComplexItem.h.
References _loiterClockwise().
loiterClockwise() [2/2]
const Fact * LandingComplexItem::loiterClockwise (void) const inline
Definition at line 47 of file LandingComplexItem.h.
References _loiterClockwise().
Referenced by _init(), _load(), _save(), and _scanForItem().
loiterRadius() [1/2]
Fact * LandingComplexItem::loiterRadius (void) inline
Definition at line 58 of file LandingComplexItem.h.
References _loiterRadius().
loiterRadius() [2/2]
const Fact * LandingComplexItem::loiterRadius (void) const inline
Definition at line 46 of file LandingComplexItem.h.
References _loiterRadius().
Referenced by _createFinalApproachItem(), _init(), _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _save(), and _scanForItem().
maxAMSLAltitude()
double LandingComplexItem::maxAMSLAltitude (void) const inline final virtual
Returns
Maximum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 111 of file LandingComplexItem.h.
References amslEntryAlt().
minAMSLAltitude()
double LandingComplexItem::minAMSLAltitude (void) const inline final virtual
Returns
Minimum altitude for the items within this complex items.
Implements ComplexMissionItem.
Definition at line 110 of file LandingComplexItem.h.
References amslExitAlt().
readyForSaveState()
LandingComplexItem::ReadyForSaveState LandingComplexItem::readyForSaveState (void) const final virtual
Returns
Returns whether the item is ready for save and if not, why
Reimplemented from VisualMissionItem.
Definition at line 619 of file LandingComplexItem.cc.
References _landingCoordSet, VisualMissionItem::_wizardMode, VisualMissionItem::NotReadyForSaveData, and VisualMissionItem::ReadyForSave.
sequenceNumber()
int LandingComplexItem::sequenceNumber (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 95 of file LandingComplexItem.h.
References _sequenceNumber.
Referenced by _load(), FixedWingLandingComplexItem::load(), VTOLLandingComplexItem::load(), and setSequenceNumber().
setAltitudesAreRelative()
void LandingComplexItem::setAltitudesAreRelative (bool altitudesAreRelative)
Definition at line 836 of file LandingComplexItem.cc.
References _altitudesAreRelative, altitudesAreRelative(), and altitudesAreRelativeChanged().
setCoordinate()
void LandingComplexItem::setCoordinate (const QGeoCoordinate & coordinate) final virtual
Implements VisualMissionItem.
Definition at line 637 of file LandingComplexItem.cc.
References _ignoreRecalcSignals, _landingCoordSet, _recalcFromHeadingAndDistanceChange(), coordinate(), and setLandingCoordinate().
setDirty()
void LandingComplexItem::setDirty (bool dirty) final virtual
Implements VisualMissionItem.
Definition at line 624 of file LandingComplexItem.cc.
References _dirty, dirty(), and VisualMissionItem::dirtyChanged().
Referenced by _scanForItem(), and _setDirty().
setFinalApproachCoordinate()
void LandingComplexItem::setFinalApproachCoordinate (const QGeoCoordinate & coordinate)
Definition at line 130 of file LandingComplexItem.cc.
References _finalApproachCoordinate, coordinate(), and finalApproachCoordinateChanged().
Referenced by _scanForItem().
setLandingCoordinate()
void LandingComplexItem::setLandingCoordinate (const QGeoCoordinate & coordinate)
Definition at line 113 of file LandingComplexItem.cc.
References _ignoreRecalcSignals, _landingCoordinate, _landingCoordSet, _recalcFromHeadingAndDistanceChange(), coordinate(), landingCoordinateChanged(), and landingCoordSetChanged().
Referenced by setCoordinate().
setSequenceNumber()
void LandingComplexItem::setSequenceNumber (int sequenceNumber) final virtual
Implements VisualMissionItem.
Definition at line 650 of file LandingComplexItem.cc.
References _sequenceNumber, lastSequenceNumber(), VisualMissionItem::lastSequenceNumberChanged(), sequenceNumber(), and VisualMissionItem::sequenceNumberChanged().
Referenced by _load().
slopeStartCoordinate()
QGeoCoordinate LandingComplexItem::slopeStartCoordinate (void) const inline
Definition at line 71 of file LandingComplexItem.h.
References _slopeStartCoordinate.
Referenced by complexDistance().
slopeStartCoordinateChanged
void LandingComplexItem::slopeStartCoordinateChanged (QGeoCoordinate coordinate) signal
Referenced by _init(), _recalcFromCoordinateChange(), and _recalcFromHeadingAndDistanceChange().
specifiedFlightSpeed()
double LandingComplexItem::specifiedFlightSpeed (void) inline final virtual
Implements VisualMissionItem.
Definition at line 96 of file LandingComplexItem.h.
specifiedGimbalPitch()
double LandingComplexItem::specifiedGimbalPitch (void) inline final virtual
Implements VisualMissionItem.
Definition at line 98 of file LandingComplexItem.h.
specifiedGimbalYaw()
double LandingComplexItem::specifiedGimbalYaw (void) inline final virtual
Implements VisualMissionItem.
Definition at line 97 of file LandingComplexItem.h.
specifiesAltitudeOnly()
bool LandingComplexItem::specifiesAltitudeOnly (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 88 of file LandingComplexItem.h.
specifiesCoordinate()
bool LandingComplexItem::specifiesCoordinate (void) const inline final virtual
Implements VisualMissionItem.
Definition at line 87 of file LandingComplexItem.h.
stopTakingPhotos() [1/2]
Fact * LandingComplexItem::stopTakingPhotos (void) inline
Definition at line 64 of file LandingComplexItem.h.
References _stopTakingPhotos().
stopTakingPhotos() [2/2]
const Fact * LandingComplexItem::stopTakingPhotos (void) const inline
Definition at line 52 of file LandingComplexItem.h.
References _stopTakingPhotos().
Referenced by _init(), _load(), _save(), _scanForItem(), appendMissionItems(), and lastSequenceNumber().
stopTakingVideo() [1/2]
Fact * LandingComplexItem::stopTakingVideo (void) inline
Definition at line 65 of file LandingComplexItem.h.
References _stopTakingVideo().
stopTakingVideo() [2/2]
const Fact * LandingComplexItem::stopTakingVideo (void) const inline
Definition at line 53 of file LandingComplexItem.h.
References _stopTakingVideo().
Referenced by _init(), _load(), _save(), _scanForItem(), appendMissionItems(), and lastSequenceNumber().
useDoChangeSpeed() [1/2]
Fact * LandingComplexItem::useDoChangeSpeed (void) inline
Definition at line 56 of file LandingComplexItem.h.
References _useDoChangeSpeed().
useDoChangeSpeed() [2/2]
const Fact * LandingComplexItem::useDoChangeSpeed (void) const inline
Definition at line 44 of file LandingComplexItem.h.
References _useDoChangeSpeed().
Referenced by _init(), _load(), _save(), _scanForItem(), and appendMissionItems().
useLoiterToAlt() [1/2]
Fact * LandingComplexItem::useLoiterToAlt (void) inline
Definition at line 63 of file LandingComplexItem.h.
References _useLoiterToAlt().
useLoiterToAlt() [2/2]
const Fact * LandingComplexItem::useLoiterToAlt (void) const inline
Definition at line 51 of file LandingComplexItem.h.
References _useLoiterToAlt().
Referenced by _createFinalApproachItem(), _init(), _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _save(), and _scanForItem().
Member Data Documentation
_altitudesAreRelative
bool LandingComplexItem::_altitudesAreRelative = true protected
Definition at line 176 of file LandingComplexItem.h.
Referenced by _createDoLandStartItem(), _createFinalApproachItem(), _load(), _save(), _scanForItem(), altitudesAreRelative(), amslEntryAlt(), amslExitAlt(), appendMissionItems(), and setAltitudesAreRelative().
_dirty
bool LandingComplexItem::_dirty = false protected
Definition at line 170 of file LandingComplexItem.h.
Referenced by dirty(), and setDirty().
_finalApproachCoordinate
QGeoCoordinate LandingComplexItem::_finalApproachCoordinate protected
Definition at line 171 of file LandingComplexItem.h.
Referenced by _createDoLandStartItem(), _createFinalApproachItem(), _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _save(), entryCoordinate(), finalApproachCoordinate(), greatestDistanceTo(), and setFinalApproachCoordinate().
_ignoreRecalcSignals
bool LandingComplexItem::_ignoreRecalcSignals = false protected
Definition at line 175 of file LandingComplexItem.h.
Referenced by _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _scanForItem(), FixedWingLandingComplexItem::load(), VTOLLandingComplexItem::load(), setCoordinate(), and setLandingCoordinate().
_jsonAltitudesAreRelativeKey
constexpr const char* LandingComplexItem::_jsonAltitudesAreRelativeKey = "altitudesAreRelative" static constexpr protected
Definition at line 193 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonDeprecatedLandingAltitudeRelativeKey
constexpr const char* LandingComplexItem::_jsonDeprecatedLandingAltitudeRelativeKey = "landAltitudeRelative" static constexpr protected
Definition at line 180 of file LandingComplexItem.h.
Referenced by _load().
_jsonDeprecatedLoiterAltitudeRelativeKey
constexpr const char* LandingComplexItem::_jsonDeprecatedLoiterAltitudeRelativeKey = "loiterAltitudeRelative" static constexpr protected
Definition at line 181 of file LandingComplexItem.h.
Referenced by _load().
_jsonDeprecatedLoiterCoordinateKey
constexpr const char* LandingComplexItem::_jsonDeprecatedLoiterCoordinateKey = "loiterCoordinate" static constexpr protected
Definition at line 185 of file LandingComplexItem.h.
Referenced by _load().
_jsonFinalApproachCoordinateKey
constexpr const char* LandingComplexItem::_jsonFinalApproachCoordinateKey = "landingApproachCoordinate" static constexpr protected
Definition at line 187 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonFinalApproachSpeedKey
constexpr const char* LandingComplexItem::_jsonFinalApproachSpeedKey = "finalApproachSpeed" static constexpr protected
Definition at line 189 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonLandingCoordinateKey
constexpr const char* LandingComplexItem::_jsonLandingCoordinateKey = "landCoordinate" static constexpr protected
Definition at line 192 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonLoiterClockwiseKey
constexpr const char* LandingComplexItem::_jsonLoiterClockwiseKey = "loiterClockwise" static constexpr protected
Definition at line 191 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonLoiterRadiusKey
constexpr const char* LandingComplexItem::_jsonLoiterRadiusKey = "loiterRadius" static constexpr protected
Definition at line 190 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonStopTakingPhotosKey
constexpr const char* LandingComplexItem::_jsonStopTakingPhotosKey = "stopTakingPhotos" static constexpr protected
Definition at line 195 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonStopTakingVideoKey
constexpr const char* LandingComplexItem::_jsonStopTakingVideoKey = "stopVideoPhotos" static constexpr protected
Definition at line 196 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonUseDoChangeSpeedKey
constexpr const char* LandingComplexItem::_jsonUseDoChangeSpeedKey = "useDoChangeSpeed" static constexpr protected
Definition at line 188 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_jsonUseLoiterToAltKey
constexpr const char* LandingComplexItem::_jsonUseLoiterToAltKey = "useLoiterToAlt" static constexpr protected
Definition at line 194 of file LandingComplexItem.h.
Referenced by _load(), and _save().
_landingCoordinate
QGeoCoordinate LandingComplexItem::_landingCoordinate protected
Definition at line 173 of file LandingComplexItem.h.
Referenced by _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _save(), _scanForItem(), appendMissionItems(), exitCoordinate(), greatestDistanceTo(), landingCoordinate(), and setLandingCoordinate().
_landingCoordSet
bool LandingComplexItem::_landingCoordSet = false protected
Definition at line 174 of file LandingComplexItem.h.
Referenced by _load(), _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), _scanForItem(), landingCoordSet(), readyForSaveState(), setCoordinate(), and setLandingCoordinate().
_sequenceNumber
int LandingComplexItem::_sequenceNumber = 0 protected
Definition at line 169 of file LandingComplexItem.h.
Referenced by appendMissionItems(), lastSequenceNumber(), sequenceNumber(), and setSequenceNumber().
_slopeStartCoordinate
QGeoCoordinate LandingComplexItem::_slopeStartCoordinate protected
Definition at line 172 of file LandingComplexItem.h.
Referenced by _recalcFromCoordinateChange(), _recalcFromHeadingAndDistanceChange(), and slopeStartCoordinate().
finalApproachAltitudeName
constexpr const char* LandingComplexItem::finalApproachAltitudeName = "FinalApproachAltitude" static constexpr
Definition at line 115 of file LandingComplexItem.h.
finalApproachSpeedName
constexpr const char* LandingComplexItem::finalApproachSpeedName = "FinalApproachSpeed" static constexpr
Definition at line 117 of file LandingComplexItem.h.
finalApproachToLandDistanceName
constexpr const char* LandingComplexItem::finalApproachToLandDistanceName = "LandingDistance" static constexpr
Definition at line 113 of file LandingComplexItem.h.
landingAltitudeName
constexpr const char* LandingComplexItem::landingAltitudeName = "LandingAltitude" static constexpr
Definition at line 120 of file LandingComplexItem.h.
landingHeadingName
constexpr const char* LandingComplexItem::landingHeadingName = "LandingHeading" static constexpr
Definition at line 114 of file LandingComplexItem.h.
loiterClockwiseName
constexpr const char* LandingComplexItem::loiterClockwiseName = "LoiterClockwise" static constexpr
Definition at line 119 of file LandingComplexItem.h.
loiterRadiusName
constexpr const char* LandingComplexItem::loiterRadiusName = "LoiterRadius" static constexpr
Definition at line 118 of file LandingComplexItem.h.
stopTakingPhotosName
constexpr const char* LandingComplexItem::stopTakingPhotosName = "StopTakingPhotos" static constexpr
Definition at line 122 of file LandingComplexItem.h.
stopTakingVideoName
constexpr const char* LandingComplexItem::stopTakingVideoName = "StopTakingVideo" static constexpr
Definition at line 123 of file LandingComplexItem.h.
useDoChangeSpeedName
constexpr const char* LandingComplexItem::useDoChangeSpeedName = "UseDoChangeSpeed" static constexpr
Definition at line 116 of file LandingComplexItem.h.
useLoiterToAltName
constexpr const char* LandingComplexItem::useLoiterToAltName = "UseLoiterToAlt" static constexpr
Definition at line 121 of file LandingComplexItem.h.
The documentation for this class was generated from the following files:
src/MissionManager/LandingComplexItem.h
src/MissionManager/LandingComplexItem.cc