QGroundControl: SpeedSection Class Reference
SpeedSection Class Reference
#include <SpeedSection.h>
Signals
void specifyFlightSpeedChanged (bool specifyFlightSpeed)
void specifiedFlightSpeedChanged (double flightSpeed)
Signals inherited from Section
void availableChanged (bool available)
void settingsSpecifiedChanged (bool settingsSpecified)
void dirtyChanged (bool dirty)
void itemCountChanged (int itemCount)
Public Member Functions
SpeedSection (PlanMasterController *masterController, QObject *parent=nullptr)
bool specifyFlightSpeed READ specifyFlightSpeed WRITE setSpecifyFlightSpeed NOTIFY specifyFlightSpeedChanged (Fact *flightSpeed READ flightSpeed CONSTANT) bool specifyFlightSpeed(void) const
Fact * flightSpeed (void)
void setSpecifyFlightSpeed (bool specifyFlightSpeed)
double specifiedFlightSpeed (void) const
bool available (void) const override
bool dirty (void) const override
void setAvailable (bool available) override
void setDirty (bool dirty) override
bool scanForSection (QmlObjectListModel *visualItems, int scanIndex) override
void appendSectionItems (QList< MissionItem * > &items, QObject *missionItemParent, int &seqNum) override
int itemCount (void) const override
bool settingsSpecified (void) const override
Public Member Functions inherited from Section
Section (PlanMasterController *masterController, QObject *parent=nullptr)
bool available READ available WRITE setAvailable NOTIFY availableChanged (bool settingsSpecified READ settingsSpecified NOTIFY settingsSpecifiedChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY availableChanged) virtual bool available(void) const =0
Additional Inherited Members
Protected Attributes inherited from Section
PlanMasterController * _masterController = nullptr
Detailed Description
Definition at line 9 of file SpeedSection.h.
Constructor & Destructor Documentation
SpeedSection()
SpeedSection::SpeedSection (PlanMasterController * masterController, QObject * parent = nullptr)
Definition at line 11 of file SpeedSection.cc.
References Section::_masterController, PlanMasterController::controllerVehicle(), FactMetaData::createMapFromJsonFile(), Vehicle::defaultCruiseSpeed(), Vehicle::defaultHoverSpeed(), flightSpeed(), Vehicle::multiRotor(), Section::settingsSpecifiedChanged(), specifyFlightSpeedChanged(), and Fact::valueChanged().
Member Function Documentation
appendSectionItems()
void SpeedSection::appendSectionItems (QList< MissionItem * > & items, QObject * missionItemParent, int & nextSequenceNumber) override virtual
Appends the mission items associated with this section
Parameters
items List to append to
missionItemParent QObject parent for created MissionItems
nextSequenceNumber[in,out] Sequence number for first item, updated as items are added
Implements Section.
Definition at line 78 of file SpeedSection.cc.
References Section::_masterController, PlanMasterController::controllerVehicle(), and Vehicle::multiRotor().
Referenced by MissionSettingsItem::appendMissionItems(), and SimpleMissionItem::appendMissionItems().
available()
bool SpeedSection::available (void) const inline override
Definition at line 28 of file SpeedSection.h.
Referenced by SimpleMissionItem::scanForSections(), setAvailable(), and SimpleMissionItem::setMissionFlightStatus().
dirty()
bool SpeedSection::dirty (void) const inline override virtual
Implements Section.
Definition at line 29 of file SpeedSection.h.
Referenced by setDirty().
flightSpeed()
Fact * SpeedSection::flightSpeed (void) inline
Definition at line 20 of file SpeedSection.h.
Referenced by SimpleMissionItem::setMissionFlightStatus(), MissionSettingsItem::specifiedFlightSpeed(), SimpleMissionItem::specifiedFlightSpeed(), and SpeedSection().
itemCount()
int SpeedSection::itemCount (void) const override virtual
Returns the number of mission items represented by this section. Signals: itemCountChanged
Implements Section.
Definition at line 73 of file SpeedSection.cc.
Referenced by MissionSettingsItem::lastSequenceNumber(), SimpleMissionItem::lastSequenceNumber(), and setSpecifyFlightSpeed().
scanForSection()
bool SpeedSection::scanForSection (QmlObjectListModel * visualItems, int scanIndex) override virtual
Scans the loaded items for the section items
Parameters
visualItems Item list
scanIndex Index to start scanning from
Returns
true: section found, items added, scanIndex updated
Implements Section.
Definition at line 98 of file SpeedSection.cc.
References Section::_masterController, MissionItem::command(), PlanMasterController::controllerVehicle(), QmlObjectListModel::count(), Vehicle::fixedWing(), SimpleMissionItem::missionItem(), Vehicle::multiRotor(), MissionItem::param1(), MissionItem::param2(), MissionItem::param3(), MissionItem::param4(), MissionItem::param5(), MissionItem::param6(), MissionItem::param7(), QmlObjectListModel::removeAt(), setSpecifyFlightSpeed(), and QmlObjectListModel::value().
Referenced by MissionSettingsItem::scanForMissionSettings(), and SimpleMissionItem::scanForSections().
setAvailable()
void SpeedSection::setAvailable (bool available) override virtual
Implements Section.
Definition at line 45 of file SpeedSection.cc.
References Section::_masterController, available(), Section::availableChanged(), PlanMasterController::controllerVehicle(), Vehicle::fixedWing(), and Vehicle::multiRotor().
setDirty()
void SpeedSection::setDirty (bool dirty) override virtual
Implements Section.
Definition at line 55 of file SpeedSection.cc.
References dirty(), and Section::dirtyChanged().
Referenced by MissionSettingsItem::setDirty(), SimpleMissionItem::setDirty(), and setSpecifyFlightSpeed().
setSpecifyFlightSpeed()
void SpeedSection::setSpecifyFlightSpeed (bool specifyFlightSpeed)
Signals specifiedFlightSpeedChanged
Returns
The flight speed specified by this item, NaN if not specified
Definition at line 63 of file SpeedSection.cc.
References itemCount(), Section::itemCountChanged(), setDirty(), and specifyFlightSpeedChanged().
Referenced by scanForSection().
settingsSpecified()
bool SpeedSection::settingsSpecified (void) const override virtual
Implements Section.
Definition at line 40 of file SpeedSection.cc.
specifiedFlightSpeed()
double SpeedSection::specifiedFlightSpeed (void) const
Definition at line 129 of file SpeedSection.cc.
specifiedFlightSpeedChanged
void SpeedSection::specifiedFlightSpeedChanged (double flightSpeed) signal
Referenced by MissionSettingsItem::MissionSettingsItem().
specifyFlightSpeedChanged [1/2]
void SpeedSection::specifyFlightSpeedChanged (bool specifyFlightSpeed) signal
specifyFlightSpeedChanged() [2/2]
bool specifyFlightSpeed READ specifyFlightSpeed WRITE setSpecifyFlightSpeed NOTIFY SpeedSection::specifyFlightSpeedChanged (Fact *flightSpeed READ flightSpeed CONSTANT) const inline
Definition at line 16 of file SpeedSection.h.
Referenced by setSpecifyFlightSpeed(), and SpeedSection().
The documentation for this class was generated from the following files:
src/MissionManager/SpeedSection.h
src/MissionManager/SpeedSection.cc