QGroundControl: RunGuard Class Reference
RunGuard Class Reference
#include <RunGuard.h>
Public Member Functions
RunGuard (const QString &key)
~RunGuard ()
bool isAnotherRunning ()
bool tryToRun ()
void release ()
bool isLocked () const
Detailed Description
Definition at line 6 of file RunGuard.h.
Constructor & Destructor Documentation
RunGuard()
RunGuard::RunGuard (const QString & key) explicit
Definition at line 7 of file RunGuard.cc.
~RunGuard()
RunGuard::~RunGuard ()
Definition at line 16 of file RunGuard.cc.
References release().
Member Function Documentation
isAnotherRunning()
bool RunGuard::isAnotherRunning ()
Definition at line 21 of file RunGuard.cc.
isLocked()
bool RunGuard::isLocked () const inline
Definition at line 22 of file RunGuard.h.
release()
void RunGuard::release ()
Definition at line 55 of file RunGuard.cc.
Referenced by ~RunGuard().
tryToRun()
bool RunGuard::tryToRun ()
Definition at line 50 of file RunGuard.cc.
Referenced by Platform::checkSingleInstance().
The documentation for this class was generated from the following files:
src/Utilities/Platform/RunGuard.h
src/Utilities/Platform/RunGuard.cc