QGroundControl: GPSRtk Class Reference
GPSRtk Class Reference
#include <GPSRtk.h>
Public Member Functions
GPSRtk (QObject *parent=nullptr)
~GPSRtk ()
void connectGPS (const QString &device, QStringView gps_type)
void disconnectGPS ()
bool connected () const
FactGroup * gpsRtkFactGroup ()
Detailed Description
Definition at line 15 of file GPSRtk.h.
Constructor & Destructor Documentation
GPSRtk()
GPSRtk::GPSRtk (QObject * parent = nullptr) explicit
Definition at line 11 of file GPSRtk.cc.
~GPSRtk()
GPSRtk::~GPSRtk ()
Definition at line 22 of file GPSRtk.cc.
References disconnectGPS().
Member Function Documentation
connected()
bool GPSRtk::connected () const
Definition at line 130 of file GPSRtk.cc.
connectGPS()
void GPSRtk::connectGPS (const QString & device, QStringView gps_type)
Definition at line 50 of file GPSRtk.cc.
References RTKSettings::baseReceiverManufacturers(), disconnectGPS(), GPSProvider::femto, RTKSettings::fixedBasePositionAccuracy(), RTKSettings::fixedBasePositionAltitude(), RTKSettings::fixedBasePositionLatitude(), RTKSettings::fixedBasePositionLongitude(), GPSProvider::RTCMDataUpdate(), RTCMMavlink::RTCMDataUpdate(), GPSProvider::satelliteInfoUpdate(), GPSProvider::sensorGpsUpdate(), GPSProvider::septentrio, RTKSettings::surveyInAccuracyLimit(), RTKSettings::surveyInMinObservationDuration(), GPSProvider::surveyInStatus(), GPSProvider::trimble, GPSProvider::u_blox, and RTKSettings::useFixedBasePosition().
disconnectGPS()
void GPSRtk::disconnectGPS ()
Definition at line 112 of file GPSRtk.cc.
Referenced by connectGPS(), and ~GPSRtk().
gpsRtkFactGroup()
FactGroup * GPSRtk::gpsRtkFactGroup ()
Definition at line 135 of file GPSRtk.cc.
The documentation for this class was generated from the following files:
src/GPS/GPSRtk.h
src/GPS/GPSRtk.cc