QGroundControl: ComponentInformationManager Class Reference
ComponentInformationManager Class Reference
#include <ComponentInformationManager.h>
Public Types
typedef void(* RequestAllCompleteFn) (void *requestAllCompleteFnData)
Signals
void progressUpdate (float progress)
Signals inherited from QGCStateMachine
void error ()
void progressUpdate (float progress)
void machineEvent (const QString &eventName)
void currentStateNameChanged ()
Emitted when the current state changes (for QML binding)
void runningChanged ()
Emitted when the running state changes (for QML binding)
void stateHistoryChanged ()
Emitted when the state history changes (for QML binding)
Public Member Functions
ComponentInformationManager (Vehicle *vehicle, QObject *parent=nullptr)
~ComponentInformationManager () override
void requestAllComponentInformation (RequestAllCompleteFn requestAllCompletFn, void *requestAllCompleteFnData)
CompInfoParam * compInfoParam (uint8_t compId)
CompInfoGeneral * compInfoGeneral (uint8_t compId)
ComponentInformationCache & fileCache ()
ComponentInformationTranslation * translation ()
float progress () const
Static Public Attributes
static constexpr int cachedFileMaxAgeSec = 3 * 24 * 3600
3 days
Friends
class RequestMetaDataTypeStateMachine
Additional Inherited Members
Public Slots inherited from QGCStateMachine
void start ()
Start the state machine with debug logging.
Protected Member Functions inherited from QGCStateMachine
virtual void onEnter ()
Override to perform actions when machine starts.
virtual void onLeave ()
Override to perform actions when machine stops.
void onEntry (QEvent *event) override
void onExit (QEvent *event) override
bool event (QEvent *event) override
Detailed Description
Definition at line 23 of file ComponentInformationManager.h.
Member Typedef Documentation
RequestAllCompleteFn
typedef void(* ComponentInformationManager::RequestAllCompleteFn) (void *requestAllCompleteFnData)
Definition at line 31 of file ComponentInformationManager.h.
Constructor & Destructor Documentation
ComponentInformationManager()
ComponentInformationManager::ComponentInformationManager (Vehicle * vehicle, QObject * parent = nullptr) explicit
Definition at line 16 of file ComponentInformationManager.cc.
~ComponentInformationManager()
ComponentInformationManager::~ComponentInformationManager () override
Definition at line 38 of file ComponentInformationManager.cc.
Member Function Documentation
compInfoGeneral()
CompInfoGeneral * ComponentInformationManager::compInfoGeneral (uint8_t compId)
Definition at line 262 of file ComponentInformationManager.cc.
compInfoParam()
CompInfoParam * ComponentInformationManager::compInfoParam (uint8_t compId)
Definition at line 253 of file ComponentInformationManager.cc.
fileCache()
ComponentInformationCache & ComponentInformationManager::fileCache () inline
Definition at line 37 of file ComponentInformationManager.h.
progress()
float ComponentInformationManager::progress () const
Definition at line 167 of file ComponentInformationManager.cc.
Referenced by requestAllComponentInformation().
progressUpdate
void ComponentInformationManager::progressUpdate (float progress) signal
Referenced by requestAllComponentInformation().
requestAllComponentInformation()
void ComponentInformationManager::requestAllComponentInformation (RequestAllCompleteFn requestAllCompletFn, void * requestAllCompleteFnData)
Definition at line 175 of file ComponentInformationManager.cc.
References progress(), progressUpdate(), and QGCStateMachine::start().
translation()
ComponentInformationTranslation * ComponentInformationManager::translation () inline
Definition at line 38 of file ComponentInformationManager.h.
Friends And Related Symbol Documentation
RequestMetaDataTypeStateMachine
friend class RequestMetaDataTypeStateMachine friend
Definition at line 90 of file ComponentInformationManager.h.
Member Data Documentation
cachedFileMaxAgeSec
constexpr int ComponentInformationManager::cachedFileMaxAgeSec = 3 * 24 * 3600 static constexpr
3 days
Definition at line 42 of file ComponentInformationManager.h.
The documentation for this class was generated from the following files:
src/Vehicle/ComponentInformation/ComponentInformationManager.h
src/Vehicle/ComponentInformation/ComponentInformationManager.cc