QGroundControl: QGCImportTileTask Class Reference
QGCImportTileTask Class Reference
#include <QGCMapTasks.h>
Signals
void actionCompleted ()
void actionProgress (int percentage)
Signals inherited from QGCMapTask
void error (QGCMapTask::TaskType type, const QString &errorString)
Public Member Functions
QGCImportTileTask (const QString &path, bool replace, QObject *parent=nullptr)
~QGCImportTileTask ()=default
QString path () const
bool replace () const
int progress () const
void setImportCompleted ()
void setProgress (int percentage)
Public Member Functions inherited from QGCMapTask
Q_ENUM (TaskType)
QGCMapTask (TaskType type, QObject *parent=nullptr)
virtual ~QGCMapTask ()=default
TaskType type () const
void setError (const QString &errorString=QString())
Additional Inherited Members
Public Types inherited from QGCMapTask
enum class TaskType {
taskInit , taskCacheTile , taskFetchTile , taskFetchTileSets ,
taskCreateTileSet , taskGetTileDownloadList , taskUpdateTileDownloadState , taskDeleteTileSet ,
taskRenameTileSet , taskPruneCache , taskReset , taskExport ,
taskImport
}
Detailed Description
Definition at line 350 of file QGCMapTasks.h.
Constructor & Destructor Documentation
QGCImportTileTask()
QGCImportTileTask::QGCImportTileTask (const QString & path, bool replace, QObject * parent = nullptr) inline
Definition at line 355 of file QGCMapTasks.h.
~QGCImportTileTask()
QGCImportTileTask::~QGCImportTileTask () default
Member Function Documentation
actionCompleted
void QGCImportTileTask::actionCompleted () signal
Referenced by setImportCompleted().
actionProgress
void QGCImportTileTask::actionProgress (int percentage) signal
Referenced by setProgress().
path()
QString QGCImportTileTask::path () const inline
Definition at line 362 of file QGCMapTasks.h.
progress()
int QGCImportTileTask::progress () const inline
Definition at line 364 of file QGCMapTasks.h.
replace()
bool QGCImportTileTask::replace () const inline
Definition at line 363 of file QGCMapTasks.h.
setImportCompleted()
void QGCImportTileTask::setImportCompleted () inline
Definition at line 366 of file QGCMapTasks.h.
References actionCompleted().
setProgress()
void QGCImportTileTask::setProgress (int percentage) inline
Definition at line 371 of file QGCMapTasks.h.
References actionProgress().
The documentation for this class was generated from the following file:
src/QtLocationPlugin/QGCMapTasks.h