QGroundControl: TerrainOfflineQuery Class Reference
TerrainOfflineQuery Class Reference
#include <TerrainQueryInterface.h>
Public Member Functions
TerrainOfflineQuery (QObject *parent=nullptr)
~TerrainOfflineQuery ()
void requestCoordinateHeights (const QList< QGeoCoordinate > &coordinates) override
void requestPathHeights (const QGeoCoordinate &fromCoord, const QGeoCoordinate &toCoord) override
void requestCarpetHeights (const QGeoCoordinate &swCoord, const QGeoCoordinate &neCoord, bool statsOnly) override
Public Member Functions inherited from TerrainQueryInterface
TerrainQueryInterface (QObject *parent=nullptr)
virtual ~TerrainQueryInterface ()
void signalCoordinateHeights (bool success, const QList< double > &heights)
void signalPathHeights (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > &heights)
void signalCarpetHeights (bool success, double minHeight, double maxHeight, const QList< QList< double > > &carpet)
Additional Inherited Members
Signals inherited from TerrainQueryInterface
void coordinateHeightsReceived (bool success, const QList< double > &heights)
void pathHeightsReceived (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > &heights)
void carpetHeightsReceived (bool success, double minHeight, double maxHeight, const QList< QList< double > > &carpet)
Protected Member Functions inherited from TerrainQueryInterface
virtual void _requestFailed ()
Protected Attributes inherited from TerrainQueryInterface
TerrainQuery::QueryMode _queryMode = TerrainQuery::QueryMode::QueryModeNone
Detailed Description
Definition at line 71 of file TerrainQueryInterface.h.
Constructor & Destructor Documentation
TerrainOfflineQuery()
TerrainOfflineQuery::TerrainOfflineQuery (QObject * parent = nullptr) explicit
Definition at line 79 of file TerrainQueryInterface.cc.
~TerrainOfflineQuery()
TerrainOfflineQuery::~TerrainOfflineQuery ()
Definition at line 85 of file TerrainQueryInterface.cc.
Member Function Documentation
requestCarpetHeights()
void TerrainOfflineQuery::requestCarpetHeights (const QGeoCoordinate & swCoord, const QGeoCoordinate & neCoord, bool statsOnly) override virtual
Request terrain heights for the rectangular area specified. Signals: carpetHeights when data is available
Parameters
swCoord South-West bound of rectangular area to query
neCoord North-East bound of rectangular area to query
statsOnly true: Return only stats, no carpet data
Reimplemented from TerrainQueryInterface.
Definition at line 106 of file TerrainQueryInterface.cc.
References TerrainQueryInterface::_queryMode, TerrainTileManager::addCarpetQuery(), TerrainTileManager::instance(), and TerrainQuery::QueryModeCarpet.
requestCoordinateHeights()
void TerrainOfflineQuery::requestCoordinateHeights (const QList< QGeoCoordinate > & coordinates) override virtual
Request terrain heights for specified coodinates. Signals: coordinateHeights when data is available
Parameters
coordinates to query
Reimplemented from TerrainQueryInterface.
Definition at line 90 of file TerrainQueryInterface.cc.
References TerrainQueryInterface::_queryMode, TerrainTileManager::addCoordinateQuery(), TerrainTileManager::instance(), and TerrainQuery::QueryModeCoordinates.
requestPathHeights()
void TerrainOfflineQuery::requestPathHeights (const QGeoCoordinate & fromCoord, const QGeoCoordinate & toCoord) override virtual
Requests terrain heights along the path specified by the two coordinates. Signals: pathHeights
Parameters
coordinates to query
Reimplemented from TerrainQueryInterface.
Definition at line 100 of file TerrainQueryInterface.cc.
References TerrainQueryInterface::_queryMode, TerrainTileManager::addPathQuery(), TerrainTileManager::instance(), and TerrainQuery::QueryModePath.
The documentation for this class was generated from the following files:
src/Terrain/TerrainQueryInterface.h
src/Terrain/TerrainQueryInterface.cc