QGroundControl: AudioOutput Class Reference
AudioOutput Class Reference
The AudioOutput class provides functionality for audio output using text-to-speech.
#include <AudioOutput.h>
Public Types
enum class TextMod { None = 0 , Translate = 1 << 0 }
Enumeration for text modification options.
Public Member Functions
AudioOutput (QObject *parent=nullptr)
~AudioOutput ()
Destructor for the AudioOutput class.
void init (Fact *volumeFact, Fact *mutedFact)
Initialize the Singleton.
void say (const QString &text, TextMods textMods=TextMod::None)
void testAudioOutput ()
Tests the audio output. Will stop current output before test.
Static Public Member Functions
static AudioOutput * instance ()
Detailed Description
The AudioOutput class provides functionality for audio output using text-to-speech.
Definition at line 13 of file AudioOutput.h.
Member Enumeration Documentation
TextMod
enum class AudioOutput::TextMod strong
Enumeration for text modification options.
Enumerator
None
Translate
Definition at line 21 of file AudioOutput.h.
Constructor & Destructor Documentation
AudioOutput()
AudioOutput::AudioOutput (QObject * parent = nullptr) explicit
Constructs an AudioOutput object.
Parameters
parent The parent QObject.
Definition at line 39 of file AudioOutput.cc.
~AudioOutput()
AudioOutput::~AudioOutput ()
Destructor for the AudioOutput class.
Definition at line 46 of file AudioOutput.cc.
Member Function Documentation
init()
void AudioOutput::init (Fact * volumeFact, Fact * mutedFact)
Initialize the Singleton.
Definition at line 56 of file AudioOutput.cc.
References errorString, and Fact::valueChanged().
instance()
AudioOutput * AudioOutput::instance () static
Gets the singleton instance of AudioOutput.
Returns
The singleton instance.
Definition at line 51 of file AudioOutput.cc.
Referenced by QGroundControlQmlGlobal::testAudioOutput().
say()
void AudioOutput::say (const QString & text, TextMods textMods = TextMod::None)
Reads the specified text with optional text modifications.
Parameters
text The text to be read.
textMods The text modifications to apply.
Definition at line 158 of file AudioOutput.cc.
References qgcApp, and Translate.
Referenced by testAudioOutput().
testAudioOutput()
void AudioOutput::testAudioOutput ()
Tests the audio output. Will stop current output before test.
Definition at line 199 of file AudioOutput.cc.
References say().
Referenced by QGroundControlQmlGlobal::testAudioOutput().
The documentation for this class was generated from the following files:
src/Utilities/Audio/AudioOutput.h
src/Utilities/Audio/AudioOutput.cc