QGroundControl: SerialWorker Class Reference
SerialWorker Class Reference
#include <SerialLink.h>
Public Slots
void setupPort ()
void connectToPort ()
void disconnectFromPort ()
void writeData (const QByteArray &data)
Signals
void connected ()
void disconnected ()
void dataReceived (const QByteArray &data)
void dataSent (const QByteArray &data)
void errorOccurred (const QString &errorString)
Public Member Functions
SerialWorker (const SerialConfiguration *config, QObject *parent=nullptr)
~SerialWorker ()
bool isConnected () const
const QSerialPort * port () const
Detailed Description
Definition at line 103 of file SerialLink.h.
Constructor & Destructor Documentation
SerialWorker()
SerialWorker::SerialWorker (const SerialConfiguration * config, QObject * parent = nullptr) explicit
Definition at line 179 of file SerialLink.cc.
~SerialWorker()
SerialWorker::~SerialWorker ()
Definition at line 188 of file SerialLink.cc.
References disconnectFromPort().
Member Function Documentation
connected
void SerialWorker::connected () signal
Referenced by SerialLink::SerialLink().
connectToPort
void SerialWorker::connectToPort () slot
Definition at line 221 of file SerialLink.cc.
References QSerialPort::error(), errorOccurred(), QGCSerialPortInfo::isBootloader(), isConnected(), QSerialPort::open(), QSerialPort::PermissionError, QSerialPort::portName(), and QSerialPort::setPortName().
dataReceived
void SerialWorker::dataReceived (const QByteArray & data) signal
Referenced by SerialLink::SerialLink().
dataSent
void SerialWorker::dataSent (const QByteArray & data) signal
Referenced by SerialLink::SerialLink(), and writeData().
disconnected
void SerialWorker::disconnected () signal
Referenced by SerialLink::SerialLink().
disconnectFromPort
void SerialWorker::disconnectFromPort () slot
Definition at line 258 of file SerialLink.cc.
References QSerialPort::close(), isConnected(), and QSerialPort::portName().
Referenced by ~SerialWorker().
errorOccurred
void SerialWorker::errorOccurred (const QString & errorString) signal
Referenced by connectToPort(), SerialLink::SerialLink(), and writeData().
isConnected()
bool SerialWorker::isConnected () const
Definition at line 195 of file SerialLink.cc.
Referenced by connectToPort(), disconnectFromPort(), SerialLink::isConnected(), and writeData().
port()
const QSerialPort * SerialWorker::port () const inline
Definition at line 112 of file SerialLink.h.
Referenced by SerialLink::port().
setupPort
void SerialWorker::setupPort () slot
Definition at line 200 of file SerialLink.cc.
References QSerialPort::errorOccurred().
Referenced by SerialLink::SerialLink().
writeData
void SerialWorker::writeData (const QByteArray & data) slot
Definition at line 270 of file SerialLink.cc.
References dataSent(), errorOccurred(), and isConnected().
The documentation for this class was generated from the following files:
src/Comms/SerialLink.h
src/Comms/SerialLink.cc