QGroundControl: RemoteIDSettings Class Reference
RemoteIDSettings Class Reference
#include <RemoteIDSettings.h>
Public Types
enum class RegionOperation { FAA , EU }
enum class LocationType { TAKEOFF , LIVE , FIXED }
enum class ClassificationType { UNDEFINED , EU }
Public Member Functions
RemoteIDSettings (QObject *parent=nullptr)
Fact *operatorID READ operatorID CONSTANT Fact * operatorID ()
Fact *operatorIDValid READ operatorIDValid CONSTANT Fact * operatorIDValid ()
Fact *operatorIDType READ operatorIDType CONSTANT Fact * operatorIDType ()
Fact *sendOperatorID READ sendOperatorID CONSTANT Fact * sendOperatorID ()
Fact *selfIDFree READ selfIDFree CONSTANT Fact * selfIDFree ()
Fact *selfIDEmergency READ selfIDEmergency CONSTANT Fact * selfIDEmergency ()
Fact *selfIDExtended READ selfIDExtended CONSTANT Fact * selfIDExtended ()
Fact *selfIDType READ selfIDType CONSTANT Fact * selfIDType ()
Fact *sendSelfID READ sendSelfID CONSTANT Fact * sendSelfID ()
Fact *basicID READ basicID CONSTANT Fact * basicID ()
Fact *basicIDType READ basicIDType CONSTANT Fact * basicIDType ()
Fact *basicIDUaType READ basicIDUaType CONSTANT Fact * basicIDUaType ()
Fact *sendBasicID READ sendBasicID CONSTANT Fact * sendBasicID ()
Fact *region READ region CONSTANT Fact * region ()
Fact *locationType READ locationType CONSTANT Fact * locationType ()
Fact *latitudeFixed READ latitudeFixed CONSTANT Fact * latitudeFixed ()
Fact *longitudeFixed READ longitudeFixed CONSTANT Fact * longitudeFixed ()
Fact *altitudeFixed READ altitudeFixed CONSTANT Fact * altitudeFixed ()
Fact *classificationType READ classificationType CONSTANT Fact * classificationType ()
Fact *categoryEU READ categoryEU CONSTANT Fact * categoryEU ()
Fact *classEU READ classEU CONSTANT Fact * classEU ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "RemoteID"
static const char * settingsGroup = "RemoteID"
static const char * operatorIDName = "operatorID"
static const char * operatorIDValidName = "operatorIDValid"
static const char * operatorIDTypeName = "operatorIDType"
static const char * sendOperatorIDName = "sendOperatorID"
static const char * selfIDFreeName = "selfIDFree"
static const char * selfIDEmergencyName = "selfIDEmergency"
static const char * selfIDExtendedName = "selfIDExtended"
static const char * selfIDTypeName = "selfIDType"
static const char * sendSelfIDName = "sendSelfID"
static const char * basicIDName = "basicID"
static const char * basicIDTypeName = "basicIDType"
static const char * basicIDUaTypeName = "basicIDUaType"
static const char * sendBasicIDName = "sendBasicID"
static const char * regionName = "region"
static const char * locationTypeName = "locationType"
static const char * latitudeFixedName = "latitudeFixed"
static const char * longitudeFixedName = "longitudeFixed"
static const char * altitudeFixedName = "altitudeFixed"
static const char * classificationTypeName = "classificationType"
static const char * categoryEUName = "categoryEU"
static const char * classEUName = "classEU"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file RemoteIDSettings.h.
Member Enumeration Documentation
ClassificationType
enum class RemoteIDSettings::ClassificationType strong
Enumerator
UNDEFINED
EU
Definition at line 27 of file RemoteIDSettings.h.
LocationType
enum class RemoteIDSettings::LocationType strong
Enumerator
TAKEOFF
LIVE
FIXED
Definition at line 20 of file RemoteIDSettings.h.
RegionOperation
enum class RemoteIDSettings::RegionOperation strong
Enumerator
FAA
EU
Definition at line 14 of file RemoteIDSettings.h.
Constructor & Destructor Documentation
RemoteIDSettings()
RemoteIDSettings::RemoteIDSettings (QObject * parent = nullptr)
Definition at line 3 of file RemoteIDSettings.cc.
Member Function Documentation
altitudeFixed()
Fact * RemoteIDSettings::altitudeFixed ()
Definition at line 24 of file RemoteIDSettings.cc.
basicID()
Fact * RemoteIDSettings::basicID ()
Definition at line 16 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager().
basicIDType()
Fact * RemoteIDSettings::basicIDType ()
Definition at line 17 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager().
basicIDUaType()
Fact * RemoteIDSettings::basicIDUaType ()
Definition at line 18 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager().
categoryEU()
Fact * RemoteIDSettings::categoryEU ()
Definition at line 26 of file RemoteIDSettings.cc.
classEU()
Fact * RemoteIDSettings::classEU ()
Definition at line 27 of file RemoteIDSettings.cc.
classificationType()
Fact * RemoteIDSettings::classificationType ()
Definition at line 25 of file RemoteIDSettings.cc.
latitudeFixed()
Fact * RemoteIDSettings::latitudeFixed ()
Definition at line 22 of file RemoteIDSettings.cc.
locationType()
Fact * RemoteIDSettings::locationType ()
Definition at line 21 of file RemoteIDSettings.cc.
longitudeFixed()
Fact * RemoteIDSettings::longitudeFixed ()
Definition at line 23 of file RemoteIDSettings.cc.
operatorID()
Fact * RemoteIDSettings::operatorID ()
Definition at line 7 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager(), and RemoteIDManager::setOperatorID().
operatorIDType()
Fact * RemoteIDSettings::operatorIDType ()
Definition at line 9 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::setOperatorID().
operatorIDValid()
Fact * RemoteIDSettings::operatorIDValid ()
Definition at line 8 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager(), and RemoteIDManager::setOperatorID().
region()
Fact * RemoteIDSettings::region ()
Definition at line 20 of file RemoteIDSettings.cc.
Referenced by RemoteIDManager::RemoteIDManager(), and RemoteIDManager::setOperatorID().
selfIDEmergency()
Fact * RemoteIDSettings::selfIDEmergency ()
Definition at line 12 of file RemoteIDSettings.cc.
selfIDExtended()
Fact * RemoteIDSettings::selfIDExtended ()
Definition at line 13 of file RemoteIDSettings.cc.
selfIDFree()
Fact * RemoteIDSettings::selfIDFree ()
Definition at line 11 of file RemoteIDSettings.cc.
selfIDType()
Fact * RemoteIDSettings::selfIDType ()
Definition at line 14 of file RemoteIDSettings.cc.
sendBasicID()
Fact * RemoteIDSettings::sendBasicID ()
Definition at line 19 of file RemoteIDSettings.cc.
sendOperatorID()
Fact * RemoteIDSettings::sendOperatorID ()
Definition at line 10 of file RemoteIDSettings.cc.
sendSelfID()
Fact * RemoteIDSettings::sendSelfID ()
Definition at line 15 of file RemoteIDSettings.cc.
Member Data Documentation
altitudeFixedName
const char * RemoteIDSettings::altitudeFixedName = "altitudeFixed" static
Definition at line 53 of file RemoteIDSettings.h.
basicIDName
const char * RemoteIDSettings::basicIDName = "basicID" static
Definition at line 45 of file RemoteIDSettings.h.
basicIDTypeName
const char * RemoteIDSettings::basicIDTypeName = "basicIDType" static
Definition at line 46 of file RemoteIDSettings.h.
basicIDUaTypeName
const char * RemoteIDSettings::basicIDUaTypeName = "basicIDUaType" static
Definition at line 47 of file RemoteIDSettings.h.
categoryEUName
const char * RemoteIDSettings::categoryEUName = "categoryEU" static
Definition at line 55 of file RemoteIDSettings.h.
classEUName
const char * RemoteIDSettings::classEUName = "classEU" static
Definition at line 56 of file RemoteIDSettings.h.
classificationTypeName
const char * RemoteIDSettings::classificationTypeName = "classificationType" static
Definition at line 54 of file RemoteIDSettings.h.
latitudeFixedName
const char * RemoteIDSettings::latitudeFixedName = "latitudeFixed" static
Definition at line 51 of file RemoteIDSettings.h.
locationTypeName
const char * RemoteIDSettings::locationTypeName = "locationType" static
Definition at line 50 of file RemoteIDSettings.h.
longitudeFixedName
const char * RemoteIDSettings::longitudeFixedName = "longitudeFixed" static
Definition at line 52 of file RemoteIDSettings.h.
name
const char * RemoteIDSettings::name = "RemoteID" static
Definition at line 34 of file RemoteIDSettings.h.
operatorIDName
const char * RemoteIDSettings::operatorIDName = "operatorID" static
Definition at line 36 of file RemoteIDSettings.h.
operatorIDTypeName
const char * RemoteIDSettings::operatorIDTypeName = "operatorIDType" static
Definition at line 38 of file RemoteIDSettings.h.
operatorIDValidName
const char * RemoteIDSettings::operatorIDValidName = "operatorIDValid" static
Definition at line 37 of file RemoteIDSettings.h.
regionName
const char * RemoteIDSettings::regionName = "region" static
Definition at line 49 of file RemoteIDSettings.h.
selfIDEmergencyName
const char * RemoteIDSettings::selfIDEmergencyName = "selfIDEmergency" static
Definition at line 41 of file RemoteIDSettings.h.
selfIDExtendedName
const char * RemoteIDSettings::selfIDExtendedName = "selfIDExtended" static
Definition at line 42 of file RemoteIDSettings.h.
selfIDFreeName
const char * RemoteIDSettings::selfIDFreeName = "selfIDFree" static
Definition at line 40 of file RemoteIDSettings.h.
selfIDTypeName
const char * RemoteIDSettings::selfIDTypeName = "selfIDType" static
Definition at line 43 of file RemoteIDSettings.h.
sendBasicIDName
const char * RemoteIDSettings::sendBasicIDName = "sendBasicID" static
Definition at line 48 of file RemoteIDSettings.h.
sendOperatorIDName
const char * RemoteIDSettings::sendOperatorIDName = "sendOperatorID" static
Definition at line 39 of file RemoteIDSettings.h.
sendSelfIDName
const char * RemoteIDSettings::sendSelfIDName = "sendSelfID" static
Definition at line 44 of file RemoteIDSettings.h.
settingsGroup
const char * RemoteIDSettings::settingsGroup = "RemoteID" static
Definition at line 34 of file RemoteIDSettings.h.
The documentation for this class was generated from the following files:
src/Settings/RemoteIDSettings.h
src/Settings/RemoteIDSettings.cc