QGroundControl: MultiVehicleManager Class Reference
MultiVehicleManager Class Reference
#include <MultiVehicleManager.h>
Signals
void vehicleAdded (Vehicle *vehicle)
void vehicleRemoved (Vehicle *vehicle)
void activeVehicleAvailableChanged (bool activeVehicleAvailable)
void parameterReadyVehicleAvailableChanged (bool parameterReadyVehicleAvailable)
void activeVehicleChanged (Vehicle *activeVehicle)
Detailed Description
Definition at line 14 of file MultiVehicleManager.h.
Member Function Documentation
activeVehicleAvailableChanged
void MultiVehicleManager::activeVehicleAvailableChanged (bool activeVehicleAvailable) signal
activeVehicleChanged
void MultiVehicleManager::activeVehicleChanged (Vehicle * activeVehicle) signal
Referenced by FactValueGrid::componentComplete(), VideoManager::init(), MAVLinkConsoleController::MAVLinkConsoleController(), MAVLinkInspectorController::MAVLinkInspectorController(), OnboardLogController::OnboardLogController(), Q_APPLICATION_STATIC(), and Vehicle::Vehicle().
parameterReadyVehicleAvailableChanged
void MultiVehicleManager::parameterReadyVehicleAvailableChanged (bool parameterReadyVehicleAvailable) signal
Referenced by Vehicle::Vehicle().
vehicleAdded
void MultiVehicleManager::vehicleAdded (Vehicle * vehicle) signal
Referenced by MAVLinkInspectorController::MAVLinkInspectorController(), and SimulatedPosition::SimulatedPosition().
vehicleRemoved
void MultiVehicleManager::vehicleRemoved (Vehicle * vehicle) signal
Referenced by MAVLinkProtocol::init(), and MAVLinkInspectorController::MAVLinkInspectorController().
The documentation for this class was generated from the following files:
src/Vehicle/MultiVehicleManager.h
src/Vehicle/MultiVehicleManager.cc