QGroundControl: MAVLinkInspectorController Class Reference
MAVLinkInspectorController Class Reference
MAVLink message inspector controller (provides the logic for UI display)
#include <MAVLinkInspectorController.h>
Signals
void activeSystemChanged ()
void rangeListChanged ()
void systemsChanged ()
void timeScalesChanged ()
Public Member Functions
MAVLinkInspectorController (QObject *parent=nullptr)
~MAVLinkInspectorController ()
void setActiveSystem (int systemId)
void setMessageInterval (int32_t rate) const
QmlObjectListModel * systems () const
QGCMAVLinkSystem * activeSystem () const
QStringList systemNames () const
QStringList timeScales ()
QStringList rangeList ()
const QList< TimeScale_st * > & timeScaleSt () const
const QList< Range_st * > & rangeSt () const
Detailed Description
MAVLink message inspector controller (provides the logic for UI display)
Definition at line 17 of file MAVLinkInspectorController.h.
Constructor & Destructor Documentation
MAVLinkInspectorController()
MAVLinkInspectorController::MAVLinkInspectorController (QObject * parent = nullptr) explicit
Definition at line 33 of file MAVLinkInspectorController.cc.
References MultiVehicleManager::activeVehicleChanged(), MAVLinkProtocol::instance(), MAVLinkProtocol::messageReceived(), rangeListChanged(), timeScalesChanged(), MultiVehicleManager::vehicleAdded(), and MultiVehicleManager::vehicleRemoved().
~MAVLinkInspectorController()
MAVLinkInspectorController::~MAVLinkInspectorController ()
Definition at line 72 of file MAVLinkInspectorController.cc.
References QmlObjectListModel::clearAndDeleteContents().
Member Function Documentation
activeSystem()
QGCMAVLinkSystem * MAVLinkInspectorController::activeSystem () const inline
Definition at line 56 of file MAVLinkInspectorController.h.
activeSystemChanged
void MAVLinkInspectorController::activeSystemChanged () signal
Referenced by setActiveSystem().
rangeList()
QStringList MAVLinkInspectorController::rangeList ()
Definition at line 92 of file MAVLinkInspectorController.cc.
rangeListChanged
void MAVLinkInspectorController::rangeListChanged () signal
Referenced by MAVLinkInspectorController().
rangeSt()
const QList< Range_st * > & MAVLinkInspectorController::rangeSt () const inline
Definition at line 62 of file MAVLinkInspectorController.h.
setActiveSystem()
void MAVLinkInspectorController::setActiveSystem (int systemId)
Definition at line 218 of file MAVLinkInspectorController.cc.
References activeSystemChanged().
setMessageInterval()
void MAVLinkInspectorController::setMessageInterval (int32_t rate) const
Definition at line 227 of file MAVLinkInspectorController.cc.
References Vehicle::setMessageRate().
systemNames()
QStringList MAVLinkInspectorController::systemNames () const inline
Definition at line 57 of file MAVLinkInspectorController.h.
systems()
QmlObjectListModel * MAVLinkInspectorController::systems () const inline
Definition at line 55 of file MAVLinkInspectorController.h.
systemsChanged
void MAVLinkInspectorController::systemsChanged () signal
timeScales()
QStringList MAVLinkInspectorController::timeScales ()
Definition at line 81 of file MAVLinkInspectorController.cc.
timeScalesChanged
void MAVLinkInspectorController::timeScalesChanged () signal
Referenced by MAVLinkInspectorController().
timeScaleSt()
const QList< TimeScale_st * > & MAVLinkInspectorController::timeScaleSt () const inline
Definition at line 61 of file MAVLinkInspectorController.h.
The documentation for this class was generated from the following files:
src/AnalyzeView/MAVLinkInspector/MAVLinkInspectorController.h
src/AnalyzeView/MAVLinkInspector/MAVLinkInspectorController.cc