QGroundControl: LinkInterface Class Reference
LinkInterface Class Reference abstract
The link interface defines the interface for all links used to communicate with the ground station application.
#include <LinkInterface.h>
Signals
void bytesReceived (LinkInterface *link, const QByteArray &data)
void bytesSent (LinkInterface *link, const QByteArray &data)
void connected ()
void disconnected ()
void communicationError (const QString &title, const QString &error)
Public Member Functions
virtual ~LinkInterface ()
virtual void disconnect ()=0
virtual bool isConnected () const =0
virtual bool isLogReplay () const
virtual bool isSecureConnection () const
Returns true if the connection is secure (e.g. USB, wired ethernet)
SharedLinkConfigurationPtr linkConfiguration ()
const SharedLinkConfigurationPtr linkConfiguration () const
uint8_t mavlinkChannel () const
bool mavlinkChannelIsSet () const
bool decodedFirstMavlinkPacket () const
void setDecodedFirstMavlinkPacket (bool decodedFirstMavlinkPacket)
void writeBytesThreadSafe (const char *bytes, int length)
void addVehicleReference ()
void removeVehicleReference ()
bool initMavlinkSigning ()
void setSigningSignatureFailure (bool failure)
void reportMavlinkV1Traffic ()
Protected Member Functions
LinkInterface (SharedLinkConfigurationPtr &config, QObject *parent=nullptr)
Links are only created by LinkManager so constructor is not public.
virtual bool _allocateMavlinkChannel ()
virtual void _freeMavlinkChannel ()
void _connectionRemoved ()
Protected Attributes
SharedLinkConfigurationPtr _config
Friends
class LinkManager
Detailed Description
The link interface defines the interface for all links used to communicate with the ground station application.
Definition at line 10 of file LinkInterface.h.
Constructor & Destructor Documentation
~LinkInterface()
LinkInterface::~LinkInterface () virtual
Definition at line 20 of file LinkInterface.cc.
References _config.
LinkInterface()
LinkInterface::LinkInterface (SharedLinkConfigurationPtr & config, QObject * parent = nullptr) explicit protected
Links are only created by LinkManager so constructor is not public.
Definition at line 13 of file LinkInterface.cc.
Member Function Documentation
_allocateMavlinkChannel()
bool LinkInterface::_allocateMavlinkChannel () protected virtual
Called by the LinkManager during LinkInterface construction instructing the link to setup channels. Default implementation allocates a single channel. But some link types (such as MockLink) need more than one.
Definition at line 60 of file LinkInterface.cc.
References initMavlinkSigning(), and mavlinkChannelIsSet().
_connectionRemoved()
void LinkInterface::_connectionRemoved () protected
Definition at line 112 of file LinkInterface.cc.
References disconnect().
Referenced by removeVehicleReference(), and MockLink::simulateConnectionRemoved().
_freeMavlinkChannel()
void LinkInterface::_freeMavlinkChannel () protected virtual
Definition at line 84 of file LinkInterface.cc.
References mavlinkChannelIsSet().
addVehicleReference()
void LinkInterface::addVehicleReference () inline
Definition at line 33 of file LinkInterface.h.
bytesReceived
void LinkInterface::bytesReceived (LinkInterface * link, const QByteArray & data) signal
Referenced by MockLink::respondWithMavlinkMessage().
bytesSent
void LinkInterface::bytesSent (LinkInterface * link, const QByteArray & data) signal
communicationError
void LinkInterface::communicationError (const QString & title, const QString & error) signal
Referenced by setSigningSignatureFailure().
connected
void LinkInterface::connected () signal
decodedFirstMavlinkPacket()
bool LinkInterface::decodedFirstMavlinkPacket () const inline
Definition at line 30 of file LinkInterface.h.
Referenced by setDecodedFirstMavlinkPacket().
disconnect()
virtual void LinkInterface::disconnect () pure virtual
Implemented in MockLink, BluetoothLink, LogReplayLink, TCPLink, and UDPLink.
Referenced by _connectionRemoved().
disconnected
void LinkInterface::disconnected () signal
Referenced by MockLink::disconnect(), and LogReplayLink::LogReplayLink().
initMavlinkSigning()
bool LinkInterface::initMavlinkSigning ()
Definition at line 43 of file LinkInterface.cc.
References MAVLinkSigning::initSigning(), and isSecureConnection().
Referenced by _allocateMavlinkChannel().
isConnected()
virtual bool LinkInterface::isConnected () const pure virtual
Implemented in MockLink, BluetoothLink, LogReplayLink, SerialLink, TCPLink, and UDPLink.
Referenced by Vehicle::sendMessageOnLinkThreadSafe().
isLogReplay()
virtual bool LinkInterface::isLogReplay () const inline virtual
Reimplemented in LogReplayLink.
Definition at line 23 of file LinkInterface.h.
isSecureConnection()
virtual bool LinkInterface::isSecureConnection () const inline virtual
Returns true if the connection is secure (e.g. USB, wired ethernet)
Reimplemented in SerialLink, TCPLink, and UDPLink.
Definition at line 24 of file LinkInterface.h.
Referenced by initMavlinkSigning().
linkConfiguration() [1/2]
SharedLinkConfigurationPtr LinkInterface::linkConfiguration () inline
Definition at line 26 of file LinkInterface.h.
References _config.
Referenced by reportMavlinkV1Traffic(), MockLink::run10HzTasks(), MockLink::run1HzTasks(), and MockLink::run500HzTasks().
linkConfiguration() [2/2]
const SharedLinkConfigurationPtr LinkInterface::linkConfiguration () const inline
Definition at line 27 of file LinkInterface.h.
References _config.
mavlinkChannel()
uint8_t LinkInterface::mavlinkChannel () const
Definition at line 29 of file LinkInterface.cc.
References mavlinkChannelIsSet().
Referenced by MAVLinkProtocol::receiveBytes(), MAVLinkProtocol::resetMetadataForLink(), MockLinkCamera::sendCameraHeartbeats(), and MockLink::sendUnexpectedCommandAck().
mavlinkChannelIsSet()
bool LinkInterface::mavlinkChannelIsSet () const
Definition at line 38 of file LinkInterface.cc.
Referenced by _allocateMavlinkChannel(), _freeMavlinkChannel(), mavlinkChannel(), MockLink::run10HzTasks(), MockLink::run1HzTasks(), and MockLink::run500HzTasks().
removeVehicleReference()
void LinkInterface::removeVehicleReference ()
Definition at line 102 of file LinkInterface.cc.
References _connectionRemoved().
reportMavlinkV1Traffic()
void LinkInterface::reportMavlinkV1Traffic ()
Definition at line 132 of file LinkInterface.cc.
References linkConfiguration(), qgcApp, and QGC::showAppMessage().
Referenced by MAVLinkProtocol::receiveBytes().
setDecodedFirstMavlinkPacket()
void LinkInterface::setDecodedFirstMavlinkPacket (bool decodedFirstMavlinkPacket) inline
Definition at line 31 of file LinkInterface.h.
References decodedFirstMavlinkPacket().
Referenced by MAVLinkProtocol::resetMetadataForLink().
setSigningSignatureFailure()
void LinkInterface::setSigningSignatureFailure (bool failure)
Definition at line 122 of file LinkInterface.cc.
References communicationError().
writeBytesThreadSafe()
void LinkInterface::writeBytesThreadSafe (const char * bytes, int length)
Definition at line 96 of file LinkInterface.cc.
Referenced by Vehicle::sendMessageOnLinkThreadSafe().
Friends And Related Symbol Documentation
LinkManager
friend class LinkManager friend
Definition at line 15 of file LinkInterface.h.
Member Data Documentation
_config
SharedLinkConfigurationPtr LinkInterface::_config protected
Definition at line 58 of file LinkInterface.h.
Referenced by linkConfiguration(), linkConfiguration(), and ~LinkInterface().
The documentation for this class was generated from the following files:
src/Comms/LinkInterface.h
src/Comms/LinkInterface.cc