QGroundControl: QGCHistoryState Class Reference
QGCHistoryState Class Reference
#include <QGCHistoryState.h>
Public Member Functions
QGCHistoryState (const QString &stateName, QState *parent, HistoryType historyType=ShallowHistory)
QGCStateMachine * machine () const
Vehicle * vehicle () const
QString stateName () const
Detailed Description
QGroundControl wrapper around QHistoryState for consistency with other QGC state classes History states remember which child state was active and return to it
Definition at line 13 of file QGCHistoryState.h.
Constructor & Destructor Documentation
QGCHistoryState()
QGCHistoryState::QGCHistoryState (const QString & stateName, QState * parent, HistoryType historyType = ShallowHistory)
Parameters
stateName Name for this state (for logging)
parent Parent state
historyType ShallowHistory (default) remembers immediate child, DeepHistory remembers entire nested configuration
Definition at line 4 of file QGCHistoryState.cc.
References stateName().
Member Function Documentation
machine()
QGCStateMachine * QGCHistoryState::machine () const
Definition at line 17 of file QGCHistoryState.cc.
Referenced by stateName(), and vehicle().
stateName()
QString QGCHistoryState::stateName () const
Definition at line 28 of file QGCHistoryState.cc.
References machine().
Referenced by QGCHistoryState().
vehicle()
Vehicle * QGCHistoryState::vehicle () const
Definition at line 22 of file QGCHistoryState.cc.
References machine().
The documentation for this class was generated from the following files:
src/Utilities/StateMachine/States/QGCHistoryState.h
src/Utilities/StateMachine/States/QGCHistoryState.cc