QGroundControl: ActuatorOutputs::ActuatorOutput Class Reference
ActuatorOutputs::ActuatorOutput Class Reference
#include <ActuatorOutputs.h>
Signals
void subgroupsChanged ()
void groupsVisibleChanged ()
void notesChanged ()
Public Member Functions
ActuatorOutput (QObject *parent, const QString &label, const Condition &groupVisibilityCondition)
QString label READ label CONSTANT (bool groupsVisible READ groupsVisible NOTIFY groupsVisibleChanged) 1(QmlObjectListModel *subgroups READ subgroups NOTIFY subgroupsChanged) 1(ConfigParameter *enableParam READ enableParam CONSTANT) 1(QmlObjectListModel *configParams READ configParams CONSTANT) 1(QStringList notes READ notes NOTIFY notesChanged) const QString &label() const
QmlObjectListModel * subgroups ()
bool groupsVisible () const
ConfigParameter * enableParam () const
QmlObjectListModel * configParams ()
void addSubgroup (ActuatorOutputSubgroup *subgroup)
void addConfigParam (ConfigParameter *param)
void getAllChannelFunctions (QList< Fact * > &allFunctions) const
bool hasExistingOutputFunctionParams () const
void addNote (const QString &note)
void clearNotes ()
const QStringList & notes () const
void forEachOutputFunction (std::function< void(ActuatorOutputSubgroup *, ChannelConfigInstance *, Fact *)> callback) const
Detailed Description
Definition at line 181 of file ActuatorOutputs.h.
Constructor & Destructor Documentation
ActuatorOutput()
ActuatorOutput::ActuatorOutput (QObject * parent, const QString & label, const Condition & groupVisibilityCondition)
Definition at line 61 of file ActuatorOutputs.cc.
References Condition::fact(), groupsVisibleChanged(), and Fact::rawValueChanged().
Member Function Documentation
addConfigParam()
void ActuatorOutput::addConfigParam (ConfigParameter * param)
Definition at line 75 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), ActuatorOutputs::ConfigParameter::Enable, and ActuatorOutputs::ConfigParameter::function().
addNote()
void ActuatorOutputs::ActuatorOutput::addNote (const QString & note) inline
Definition at line 209 of file ActuatorOutputs.h.
References notesChanged().
Referenced by Actuators::parametersChanged().
addSubgroup()
void ActuatorOutput::addSubgroup (ActuatorOutputSubgroup * subgroup)
Definition at line 69 of file ActuatorOutputs.cc.
References QmlObjectListModel::append(), and subgroupsChanged().
clearNotes()
void ActuatorOutputs::ActuatorOutput::clearNotes () inline
Definition at line 210 of file ActuatorOutputs.h.
References notesChanged().
Referenced by Actuators::parametersChanged().
configParams()
QmlObjectListModel * ActuatorOutputs::ActuatorOutput::configParams () inline
Definition at line 199 of file ActuatorOutputs.h.
CONSTANT()
QString label READ label ActuatorOutputs::ActuatorOutput::CONSTANT (bool groupsVisible READ groupsVisible NOTIFY groupsVisibleChanged) const & inline
Definition at line 187 of file ActuatorOutputs.h.
enableParam()
ConfigParameter * ActuatorOutputs::ActuatorOutput::enableParam () const inline
Definition at line 198 of file ActuatorOutputs.h.
Referenced by Actuators::init().
forEachOutputFunction()
void ActuatorOutput::forEachOutputFunction (std::function< void(ActuatorOutputSubgroup *, ChannelConfigInstance *, Fact *)> callback) const
Definition at line 100 of file ActuatorOutputs.cc.
References ActuatorOutputs::ChannelConfigInstance::channelConfig(), ActuatorOutputs::ActuatorOutputSubgroup::channels(), ActuatorOutputs::ActuatorOutputChannel::configInstances(), QmlObjectListModel::count(), ActuatorOutputs::ChannelConfig::function(), QmlObjectListModel::get(), and ActuatorOutputs::ChannelConfig::OutputFunction.
Referenced by getAllChannelFunctions(), and hasExistingOutputFunctionParams().
getAllChannelFunctions()
void ActuatorOutput::getAllChannelFunctions (QList< Fact * > & allFunctions) const
Definition at line 85 of file ActuatorOutputs.cc.
References forEachOutputFunction().
Referenced by Actuators::parametersChanged().
groupsVisible()
bool ActuatorOutputs::ActuatorOutput::groupsVisible () const inline
Definition at line 197 of file ActuatorOutputs.h.
References Condition::evaluate().
groupsVisibleChanged
void ActuatorOutputs::ActuatorOutput::groupsVisibleChanged () signal
Referenced by ActuatorOutput().
hasExistingOutputFunctionParams()
bool ActuatorOutput::hasExistingOutputFunctionParams () const
Definition at line 92 of file ActuatorOutputs.cc.
References forEachOutputFunction().
Referenced by Actuators::init().
notes()
const QStringList & ActuatorOutputs::ActuatorOutput::notes () const inline
Definition at line 211 of file ActuatorOutputs.h.
notesChanged
void ActuatorOutputs::ActuatorOutput::notesChanged () signal
Referenced by addNote(), and clearNotes().
subgroups()
QmlObjectListModel * ActuatorOutputs::ActuatorOutput::subgroups () inline
Definition at line 196 of file ActuatorOutputs.h.
Referenced by Actuators::parametersChanged().
subgroupsChanged
void ActuatorOutputs::ActuatorOutput::subgroupsChanged () signal
Referenced by addSubgroup().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/ActuatorOutputs.h
src/Vehicle/Actuators/ActuatorOutputs.cc