QGroundControl: VideoManager Class Reference
VideoManager Class Reference
#include <VideoManager.h>
Signals
void aspectRatioChanged ()
void autoStreamConfiguredChanged ()
void decodingChanged ()
void fullScreenChanged ()
void hasVideoChanged ()
void imageFileChanged (const QString &filename)
void isAutoStreamChanged ()
void isStreamSourceChanged ()
void isUvcChanged ()
void recordingChanged (bool recording)
void recordingStarted (const QString &filename)
void streamingChanged ()
void uvcVideoSourceIDChanged ()
void videoSizeChanged ()
Public Member Functions
VideoManager (QObject *parent=nullptr)
~VideoManager ()
void grabImage (const QString &imageFile=QString())
void startRecording (const QString &videoFile=QString())
void startVideo ()
void stopRecording ()
void stopVideo ()
void init (QQuickWindow *mainWindow)
void startGStreamerInit ()
bool waitForGStreamerInit (int timeoutMs=60000)
void cleanup ()
bool autoStreamConfigured () const
bool decoding () const
bool fullScreen () const
bool hasThermal () const
bool hasVideo () const
bool isStreamSource () const
bool isUvc () const
bool recording () const
bool streaming () const
double aspectRatio () const
double hfov () const
double thermalAspectRatio () const
double thermalHfov () const
QSize videoSize () const
QString imageFile () const
QString uvcVideoSourceID () const
void setfullScreen (bool on)
Static Public Member Functions
static VideoManager * instance ()
static bool gstreamerEnabled ()
static bool gstreamerD3D11Sink ()
static bool gstreamerAppleSink ()
static bool qtmultimediaEnabled ()
static bool uvcEnabled ()
Detailed Description
Definition at line 21 of file VideoManager.h.
Constructor & Destructor Documentation
VideoManager()
VideoManager::VideoManager (QObject * parent = nullptr) explicit
Definition at line 59 of file VideoManager.cc.
References gstQml6D3D11RegisterQmlTypes(), and gstQml6GLRegisterQmlTypes().
~VideoManager()
VideoManager::~VideoManager ()
Definition at line 97 of file VideoManager.cc.
Member Function Documentation
aspectRatio()
double VideoManager::aspectRatio () const
Definition at line 427 of file VideoManager.cc.
References VideoSettings::aspectRatio(), VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
aspectRatioChanged
void VideoManager::aspectRatioChanged () signal
Referenced by init().
autoStreamConfigured()
bool VideoManager::autoStreamConfigured () const
Definition at line 630 of file VideoManager.cc.
References VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
Referenced by isStreamSource().
autoStreamConfiguredChanged
void VideoManager::autoStreamConfiguredChanged () signal
Referenced by init().
cleanup()
void VideoManager::cleanup ()
Definition at line 327 of file VideoManager.cc.
References VideoReceiver::sink().
Referenced by QGCApplication::shutdown().
decoding()
bool VideoManager::decoding () const inline
Definition at line 69 of file VideoManager.h.
Referenced by SimulatedCameraControl::hasVideoStream().
decodingChanged
void VideoManager::decodingChanged () signal
Referenced by SimulatedCameraControl::SimulatedCameraControl().
fullScreen()
bool VideoManager::fullScreen () const inline
Definition at line 70 of file VideoManager.h.
fullScreenChanged
void VideoManager::fullScreenChanged () signal
Referenced by setfullScreen().
grabImage()
void VideoManager::grabImage (const QString & imageFile = QString())
Definition at line 410 of file VideoManager.cc.
References imageFile(), imageFileChanged(), AppSettings::photoSavePath(), and VideoReceiver::takeScreenshot().
Referenced by VehicleCameraControl::handleCameraCaptureStatus(), and VehicleCameraControl::takePhoto().
gstreamerAppleSink()
bool VideoManager::gstreamerAppleSink () static
Definition at line 516 of file VideoManager.cc.
gstreamerD3D11Sink()
bool VideoManager::gstreamerD3D11Sink () static
Definition at line 507 of file VideoManager.cc.
gstreamerEnabled()
bool VideoManager::gstreamerEnabled () static
Definition at line 498 of file VideoManager.cc.
hasThermal()
bool VideoManager::hasThermal () const
Definition at line 476 of file VideoManager.cc.
References VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
hasVideo()
bool VideoManager::hasVideo () const
Definition at line 488 of file VideoManager.cc.
References VideoSettings::streamEnabled().
Referenced by SimulatedCameraControl::capturesVideo(), isUvc(), and startVideo().
hasVideoChanged
void VideoManager::hasVideoChanged () signal
Referenced by SimulatedCameraControl::SimulatedCameraControl().
hfov()
double VideoManager::hfov () const
Definition at line 452 of file VideoManager.cc.
References VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
imageFile()
QString VideoManager::imageFile () const inline
Definition at line 82 of file VideoManager.h.
Referenced by grabImage().
imageFileChanged
void VideoManager::imageFileChanged (const QString & filename) signal
Referenced by grabImage().
init()
void VideoManager::init (QQuickWindow * mainWindow)
Definition at line 189 of file VideoManager.cc.
References MultiVehicleManager::activeVehicleChanged(), VideoSettings::aspectRatio(), aspectRatioChanged(), autoStreamConfiguredChanged(), AppSettings::gstDebugLevel(), VideoSettings::lowLatencyMode(), Fact::rawValueChanged(), VideoSettings::rtspUrl(), GStreamer::setDebugLevel(), startGStreamerInit(), VideoSettings::tcpUrl(), VideoSettings::udpUrl(), and VideoSettings::videoSource().
instance()
VideoManager * VideoManager::instance () static
Definition at line 102 of file VideoManager.cc.
Referenced by VehicleCameraControl::_initWhenReady(), SimulatedCameraControl::capturesVideo(), VehicleCameraControl::captureVideoState(), SimulatedCameraControl::captureVideoState(), VehicleCameraControl::handleCameraCaptureStatus(), SimulatedCameraControl::hasVideoStream(), QGCApplication::shutdown(), SimulatedCameraControl::SimulatedCameraControl(), VehicleCameraControl::startVideoRecording(), SimulatedCameraControl::startVideoRecording(), VehicleCameraControl::stopVideoRecording(), SimulatedCameraControl::stopVideoRecording(), and VehicleCameraControl::takePhoto().
isAutoStreamChanged
void VideoManager::isAutoStreamChanged () signal
isStreamSource()
bool VideoManager::isStreamSource () const
Definition at line 549 of file VideoManager.cc.
References autoStreamConfigured(), VideoSettings::videoSource(), VideoSettings::videoSource3DRSolo, VideoSettings::videoSourceHerelinkAirUnit, VideoSettings::videoSourceHerelinkHotspot, VideoSettings::videoSourceMPEGTS, VideoSettings::videoSourceParrotDiscovery, VideoSettings::videoSourceRTSP, VideoSettings::videoSourceTCP, VideoSettings::videoSourceUDPH264, VideoSettings::videoSourceUDPH265, and VideoSettings::videoSourceYuneecMantisG.
isStreamSourceChanged
void VideoManager::isStreamSourceChanged () signal
isUvc()
bool VideoManager::isUvc () const
Definition at line 493 of file VideoManager.cc.
References hasVideo(), and uvcEnabled().
isUvcChanged
void VideoManager::isUvcChanged () signal
qtmultimediaEnabled()
bool VideoManager::qtmultimediaEnabled () static
Definition at line 530 of file VideoManager.cc.
References QtMultimediaReceiver::enabled().
recording()
bool VideoManager::recording () const inline
Definition at line 75 of file VideoManager.h.
recordingChanged
void VideoManager::recordingChanged (bool recording) signal
Referenced by VehicleCameraControl::_initWhenReady(), and SimulatedCameraControl::SimulatedCameraControl().
recordingStarted
void VideoManager::recordingStarted (const QString & filename) signal
setfullScreen()
void VideoManager::setfullScreen (bool on)
Definition at line 535 of file VideoManager.cc.
References VehicleLinkManager::communicationLost(), fullScreenChanged(), and Vehicle::vehicleLinkManager().
startGStreamerInit()
void VideoManager::startGStreamerInit ()
Definition at line 107 of file VideoManager.cc.
References GStreamer::initialize(), and GStreamer::prepareEnvironment().
Referenced by init(), and waitForGStreamerInit().
startRecording()
void VideoManager::startRecording (const QString & videoFile = QString())
Definition at line 371 of file VideoManager.cc.
References VideoReceiver::isValidFileFormat(), kFileExtension, VideoReceiver::name(), qgcApp, VideoSettings::recordingFormat(), VideoReceiver::started(), VideoReceiver::startRecording(), and AppSettings::videoSavePath().
Referenced by VehicleCameraControl::startVideoRecording(), and SimulatedCameraControl::startVideoRecording().
startVideo()
void VideoManager::startVideo ()
Definition at line 1025 of file VideoManager.cc.
References hasVideo().
stopRecording()
void VideoManager::stopRecording ()
Definition at line 403 of file VideoManager.cc.
References VideoReceiver::stopRecording().
Referenced by VehicleCameraControl::stopVideoRecording(), and SimulatedCameraControl::stopVideoRecording().
stopVideo()
void VideoManager::stopVideo ()
Definition at line 861 of file VideoManager.cc.
streaming()
bool VideoManager::streaming () const inline
Definition at line 76 of file VideoManager.h.
streamingChanged
void VideoManager::streamingChanged () signal
thermalAspectRatio()
double VideoManager::thermalAspectRatio () const
Definition at line 440 of file VideoManager.cc.
References VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
thermalHfov()
double VideoManager::thermalHfov () const
Definition at line 464 of file VideoManager.cc.
References VideoSettings::aspectRatio(), VideoReceiver::isThermal(), and VideoReceiver::videoStreamInfo().
uvcEnabled()
bool VideoManager::uvcEnabled () static
Definition at line 525 of file VideoManager.cc.
References UVCReceiver::enabled().
Referenced by isUvc().
uvcVideoSourceID()
QString VideoManager::uvcVideoSourceID () const inline
Definition at line 83 of file VideoManager.h.
uvcVideoSourceIDChanged
void VideoManager::uvcVideoSourceIDChanged () signal
videoSize()
QSize VideoManager::videoSize () const inline
Definition at line 81 of file VideoManager.h.
videoSizeChanged
void VideoManager::videoSizeChanged () signal
waitForGStreamerInit()
bool VideoManager::waitForGStreamerInit (int timeoutMs = 60000)
Definition at line 134 of file VideoManager.cc.
References startGStreamerInit().
The documentation for this class was generated from the following files:
src/VideoManager/VideoManager.h
src/VideoManager/VideoManager.cc