QGroundControl: CompInfoParam Class Reference
CompInfoParam Class Reference
#include <CompInfoParam.h>
Public Member Functions
CompInfoParam (uint8_t compId_, Vehicle *vehicle_, QObject *parent=nullptr)
FactMetaData * factMetaDataForName (const QString &name, FactMetaData::ValueType_t valueType)
void setJson (const QString &metadataJsonFileName) override
Public Member Functions inherited from CompInfo
CompInfo (COMP_METADATA_TYPE type_, uint8_t compId_, Vehicle *vehicle_, QObject *parent=nullptr)
const QString & uriMetaData () const
const QString & uriMetaDataFallback () const
const QString & uriTranslation () const
uint32_t crcMetaData () const
uint32_t crcMetaDataFallback () const
bool crcMetaDataValid () const
bool crcMetaDataFallbackValid () const
void setUriMetaData (const QString &uri, uint32_t crc)
bool available () const
Additional Inherited Members
Public Attributes inherited from CompInfo
const COMP_METADATA_TYPE type
Vehicle *const vehicle = nullptr
const uint8_t compId = MAV_COMP_ID_ALL
Detailed Description
Definition at line 13 of file CompInfoParam.h.
Constructor & Destructor Documentation
CompInfoParam()
CompInfoParam::CompInfoParam (uint8_t compId_, Vehicle * vehicle_, QObject * parent = nullptr)
Definition at line 15 of file CompInfoParam.cc.
Member Function Documentation
factMetaDataForName()
FactMetaData * CompInfoParam::factMetaDataForName (const QString & name, FactMetaData::ValueType_t valueType)
Definition at line 72 of file CompInfoParam.cc.
setJson()
void CompInfoParam::setJson (const QString & metadataJsonFileName) override virtual
Implements CompInfo.
Definition at line 20 of file CompInfoParam.cc.
References CompInfo::compId, FactMetaData::createFromJsonObject(), errorString, JsonParsing::isJsonFile(), JsonHelper::jsonVersionKey, ParameterMetaData::kEmptyDefines, FactMetaData::name(), and JsonHelper::validateKeys().
The documentation for this class was generated from the following files:
src/Vehicle/ComponentInformation/CompInfoParam.h
src/Vehicle/ComponentInformation/CompInfoParam.cc