QGroundControl: TerrainTile Class Reference
TerrainTile Class Reference
#include <TerrainTile.h>
Classes
struct TileInfo_t
Public Member Functions
TerrainTile (const QByteArray &byteArray)
virtual ~TerrainTile ()
bool isValid () const
double elevation (const QGeoCoordinate &coordinate) const
double minElevation () const
double maxElevation () const
double avgElevation () const
Protected Attributes
struct TerrainTile::TileInfo_t Q_PACKED
Friends
class TerrainTileTest
Detailed Description
Definition at line 7 of file TerrainTile.h.
Constructor & Destructor Documentation
TerrainTile()
TerrainTile::TerrainTile (const QByteArray & byteArray) explicit
Constructor from serialized elevation data (either from file or web)
Parameters
document
Definition at line 9 of file TerrainTile.cc.
References TerrainTile::TileInfo_t::avgElevation, TerrainTile::TileInfo_t::gridSizeLat, TerrainTile::TileInfo_t::gridSizeLon, TerrainTile::TileInfo_t::maxElevation, TerrainTile::TileInfo_t::minElevation, TerrainTile::TileInfo_t::neLat, TerrainTile::TileInfo_t::neLon, TerrainTile::TileInfo_t::swLat, and TerrainTile::TileInfo_t::swLon.
~TerrainTile()
TerrainTile::~TerrainTile () virtual
Definition at line 70 of file TerrainTile.cc.
Member Function Documentation
avgElevation()
double TerrainTile::avgElevation () const inline
Accessor for the average elevation of the tile
Returns
average elevation
Definition at line 36 of file TerrainTile.h.
References TerrainTile::TileInfo_t::avgElevation.
elevation()
double TerrainTile::elevation (const QGeoCoordinate & coordinate) const
Evaluates the elevation at the given coordinate
Parameters
coordinate
Returns
elevation
Definition at line 75 of file TerrainTile.cc.
References elevation(), TerrainTile::TileInfo_t::gridSizeLat, TerrainTile::TileInfo_t::gridSizeLon, TerrainTile::TileInfo_t::maxElevation, TerrainTile::TileInfo_t::minElevation, TerrainTile::TileInfo_t::swLat, and TerrainTile::TileInfo_t::swLon.
Referenced by elevation(), and TerrainTileManager::getAltitudesForCoordinates().
isValid()
bool TerrainTile::isValid () const inline
Check whether valid data is loaded
Returns
true if data is valid
Definition at line 19 of file TerrainTile.h.
maxElevation()
double TerrainTile::maxElevation () const inline
Accessor for the maximum elevation of the tile
Returns
maximum elevation
Definition at line 32 of file TerrainTile.h.
References TerrainTile::TileInfo_t::maxElevation.
minElevation()
double TerrainTile::minElevation () const inline
Accessor for the minimum elevation of the tile
Returns
minimum elevation
Definition at line 28 of file TerrainTile.h.
References TerrainTile::TileInfo_t::minElevation.
Friends And Related Symbol Documentation
TerrainTileTest
friend class TerrainTileTest friend
Definition at line 9 of file TerrainTile.h.
Member Data Documentation
Q_PACKED
struct TerrainTile::TileInfo_t TerrainTile::Q_PACKED protected
The documentation for this class was generated from the following files:
src/Terrain/TerrainTile.h
src/Terrain/TerrainTile.cc