QGroundControl: PX4RadioComponent Class Reference
PX4RadioComponent Class Reference
#include <PX4RadioComponent.h>
Public Member Functions
PX4RadioComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
virtual QStringList setupCompleteChangedTriggerList (void) const
virtual QString name (void) const
virtual QString description (void) const
virtual QString iconResource (void) const
virtual bool requiresSetup (void) const
virtual bool setupComplete (void) const
virtual QUrl setupSource (void) const
virtual QUrl summaryQmlSource (void) const
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file PX4RadioComponent.h.
Constructor & Destructor Documentation
PX4RadioComponent()
PX4RadioComponent::PX4RadioComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr)
Definition at line 5 of file PX4RadioComponent.cc.
Member Function Documentation
description()
QString PX4RadioComponent::description (void) const virtual
Reimplemented from VehicleComponent.
Definition at line 16 of file PX4RadioComponent.cc.
iconResource()
QString PX4RadioComponent::iconResource (void) const virtual
Implements VehicleComponent.
Definition at line 22 of file PX4RadioComponent.cc.
name()
QString PX4RadioComponent::name (void) const virtual
Implements VehicleComponent.
Definition at line 11 of file PX4RadioComponent.cc.
Referenced by PX4AutoPilotPlugin::prerequisiteSetup().
requiresSetup()
bool PX4RadioComponent::requiresSetup (void) const virtual
Implements VehicleComponent.
Definition at line 27 of file PX4RadioComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::getParameter(), and Vehicle::parameterManager().
setupComplete()
bool PX4RadioComponent::setupComplete (void) const virtual
Implements VehicleComponent.
Definition at line 32 of file PX4RadioComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), and Vehicle::parameterManager().
Referenced by PX4AutoPilotPlugin::prerequisiteSetup().
setupCompleteChangedTriggerList()
QStringList PX4RadioComponent::setupCompleteChangedTriggerList (void) const virtual
Returns an list of parameter names for which a change should cause the setupCompleteChanged signal to be emitted.
Implements VehicleComponent.
Definition at line 47 of file PX4RadioComponent.cc.
setupSource()
QUrl PX4RadioComponent::setupSource (void) const virtual
Implements VehicleComponent.
Definition at line 52 of file PX4RadioComponent.cc.
summaryQmlSource()
QUrl PX4RadioComponent::summaryQmlSource (void) const virtual
Implements VehicleComponent.
Definition at line 57 of file PX4RadioComponent.cc.
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/PX4RadioComponent.h
src/AutoPilotPlugins/PX4/PX4RadioComponent.cc