QGroundControl: UnitsSettings Class Reference
UnitsSettings Class Reference
#include <UnitsSettings.h>
Public Types
enum HorizontalDistanceUnits { HorizontalDistanceUnitsFeet = 0 , HorizontalDistanceUnitsMeters }
enum VerticalDistanceUnits { VerticalDistanceUnitsFeet = 0 , VerticalDistanceUnitsMeters }
enum AreaUnits {
AreaUnitsSquareFeet = 0 , AreaUnitsSquareMeters , AreaUnitsSquareKilometers , AreaUnitsHectares ,
AreaUnitsAcres , AreaUnitsSquareMiles
}
enum SpeedUnits {
SpeedUnitsFeetPerSecond = 0 , SpeedUnitsMetersPerSecond , SpeedUnitsMilesPerHour , SpeedUnitsKilometersPerHour ,
SpeedUnitsKnots
}
enum TemperatureUnits { TemperatureUnitsCelsius = 0 , TemperatureUnitsFarenheit }
enum WeightUnits { WeightUnitsGrams = 0 , WeightUnitsKg , WeightUnitsOz , WeightUnitsLbs }
Public Member Functions
UnitsSettings (QObject *parent=nullptr)
Fact *horizontalDistanceUnits READ horizontalDistanceUnits CONSTANT Fact * horizontalDistanceUnits ()
Fact *verticalDistanceUnits READ verticalDistanceUnits CONSTANT Fact * verticalDistanceUnits ()
Fact *areaUnits READ areaUnits CONSTANT Fact * areaUnits ()
Fact *speedUnits READ speedUnits CONSTANT Fact * speedUnits ()
Fact *temperatureUnits READ temperatureUnits CONSTANT Fact * temperatureUnits ()
Fact *weightUnits READ weightUnits CONSTANT Fact * weightUnits ()
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool visible READ visible WRITE setVisible NOTIFY virtual visibleChanged bool visible ()
virtual void setVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "Units"
static const char * settingsGroup = "Units"
static const char * horizontalDistanceUnitsName = "horizontalDistanceUnits"
static const char * verticalDistanceUnitsName = "verticalDistanceUnits"
static const char * areaUnitsName = "areaUnits"
static const char * speedUnitsName = "speedUnits"
static const char * temperatureUnitsName = "temperatureUnits"
static const char * weightUnitsName = "weightUnits"
Additional Inherited Members
Signals inherited from SettingsGroup
void visibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _visible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file UnitsSettings.h.
Member Enumeration Documentation
AreaUnits
enum UnitsSettings::AreaUnits
Enumerator
AreaUnitsSquareFeet
AreaUnitsSquareMeters
AreaUnitsSquareKilometers
AreaUnitsHectares
AreaUnitsAcres
AreaUnitsSquareMiles
Definition at line 25 of file UnitsSettings.h.
HorizontalDistanceUnits
enum UnitsSettings::HorizontalDistanceUnits
Enumerator
HorizontalDistanceUnitsFeet
HorizontalDistanceUnitsMeters
Definition at line 15 of file UnitsSettings.h.
SpeedUnits
enum UnitsSettings::SpeedUnits
Enumerator
SpeedUnitsFeetPerSecond
SpeedUnitsMetersPerSecond
SpeedUnitsMilesPerHour
SpeedUnitsKilometersPerHour
SpeedUnitsKnots
Definition at line 34 of file UnitsSettings.h.
TemperatureUnits
enum UnitsSettings::TemperatureUnits
Enumerator
TemperatureUnitsCelsius
TemperatureUnitsFarenheit
Definition at line 42 of file UnitsSettings.h.
VerticalDistanceUnits
enum UnitsSettings::VerticalDistanceUnits
Enumerator
VerticalDistanceUnitsFeet
VerticalDistanceUnitsMeters
Definition at line 20 of file UnitsSettings.h.
WeightUnits
enum UnitsSettings::WeightUnits
Enumerator
WeightUnitsGrams
WeightUnitsKg
WeightUnitsOz
WeightUnitsLbs
Definition at line 47 of file UnitsSettings.h.
Constructor & Destructor Documentation
UnitsSettings()
UnitsSettings::UnitsSettings (QObject * parent = nullptr)
Definition at line 3 of file UnitsSettings.cc.
Member Function Documentation
areaUnits()
Fact * UnitsSettings::areaUnits ()
Definition at line 68 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
horizontalDistanceUnits()
Fact * UnitsSettings::horizontalDistanceUnits ()
Definition at line 7 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
speedUnits()
Fact * UnitsSettings::speedUnits ()
Definition at line 104 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
temperatureUnits()
Fact * UnitsSettings::temperatureUnits ()
Definition at line 139 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
verticalDistanceUnits()
Fact * UnitsSettings::verticalDistanceUnits ()
Definition at line 38 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
weightUnits()
Fact * UnitsSettings::weightUnits ()
Definition at line 169 of file UnitsSettings.cc.
References FactMetaData::setEnumInfo(), FactMetaData::setName(), FactMetaData::setQGCRebootRequired(), FactMetaData::setRawDefaultValue(), FactMetaData::setShortDescription(), and FactMetaData::valueTypeUint32.
Member Data Documentation
areaUnitsName
const char * UnitsSettings::areaUnitsName = "areaUnits" static
Definition at line 65 of file UnitsSettings.h.
horizontalDistanceUnitsName
const char * UnitsSettings::horizontalDistanceUnitsName = "horizontalDistanceUnits" static
Definition at line 63 of file UnitsSettings.h.
name
const char * UnitsSettings::name = "Units" static
Definition at line 61 of file UnitsSettings.h.
settingsGroup
const char * UnitsSettings::settingsGroup = "Units" static
Definition at line 61 of file UnitsSettings.h.
speedUnitsName
const char * UnitsSettings::speedUnitsName = "speedUnits" static
Definition at line 66 of file UnitsSettings.h.
temperatureUnitsName
const char * UnitsSettings::temperatureUnitsName = "temperatureUnits" static
Definition at line 67 of file UnitsSettings.h.
verticalDistanceUnitsName
const char * UnitsSettings::verticalDistanceUnitsName = "verticalDistanceUnits" static
Definition at line 64 of file UnitsSettings.h.
weightUnitsName
const char * UnitsSettings::weightUnitsName = "weightUnits" static
Definition at line 68 of file UnitsSettings.h.
The documentation for this class was generated from the following files:
src/Settings/UnitsSettings.h
src/Settings/UnitsSettings.cc