QGroundControl: FirmwarePluginInstanceData Class Reference
FirmwarePluginInstanceData Class Reference
#include <FirmwarePlugin.h>
Public Types
enum class CommandSupportedResult : uint8_t { SUPPORTED = 23 , UNSUPPORTED = 24 , UNKNOWN = 25 }
Public Member Functions
virtual CommandSupportedResult anyVersionSupportsCommand (MAV_CMD) const
void setCommandSupported (MAV_CMD cmd, CommandSupportedResult status)
CommandSupportedResult getCommandSupported (MAV_CMD cmd) const
Detailed Description
Definition at line 437 of file FirmwarePlugin.h.
Member Enumeration Documentation
CommandSupportedResult
enum class FirmwarePluginInstanceData::CommandSupportedResult : uint8_t strong
Enumerator
SUPPORTED
UNSUPPORTED
UNKNOWN
Definition at line 446 of file FirmwarePlugin.h.
Member Function Documentation
anyVersionSupportsCommand()
virtual CommandSupportedResult FirmwarePluginInstanceData::anyVersionSupportsCommand (MAV_CMD) const inline virtual
Reimplemented in APMFirmwarePluginInstanceData, and PX4FirmwarePluginInstanceData.
Definition at line 454 of file FirmwarePlugin.h.
References UNKNOWN.
Referenced by getCommandSupported().
getCommandSupported()
FirmwarePluginInstanceData::CommandSupportedResult FirmwarePluginInstanceData::getCommandSupported (MAV_CMD cmd) const
Definition at line 605 of file FirmwarePlugin.cc.
References anyVersionSupportsCommand(), UNKNOWN, and UNSUPPORTED.
setCommandSupported()
void FirmwarePluginInstanceData::setCommandSupported (MAV_CMD cmd, CommandSupportedResult status) inline
Definition at line 458 of file FirmwarePlugin.h.
Referenced by _sendMavCommandWithLambdaFallbackHandler().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc