QGroundControl: Mixer::MixerChannel Class Reference
Mixer::MixerChannel Class Reference
#include <Mixer.h>
Public Slots
void applyRule (bool noConstraints=false)
Signals
void configInstancesChanged ()
Public Member Functions
MixerChannel (QObject *parent, const QString &label, int actuatorFunction, int paramIndex, int actuatorTypeIndex, QmlObjectListModel &channelConfigs, ParameterManager *parameterManager, const Rule *rule, std::function< void(Function, Fact *)> factAddedCb)
QString label READ label CONSTANT (QmlObjectListModel *configInstances READ configInstances NOTIFY configInstancesChanged) const QString &label() const
int actuatorFunction () const
QmlObjectListModel * configInstances ()
bool getGeometry (const ActuatorTypes &actuatorTypes, const MixerOption::ActuatorGroup &group, ActuatorGeometry &geometry) const
Fact * getFact (Function function) const
Detailed Description
Definition at line 265 of file Mixer.h.
Constructor & Destructor Documentation
MixerChannel()
MixerChannel::MixerChannel (QObject * parent, const QString & label, int actuatorFunction, int paramIndex, int actuatorTypeIndex, QmlObjectListModel & channelConfigs, ParameterManager * parameterManager, const Rule * rule, std::function< void(Function, Fact *)> factAddedCb)
Definition at line 217 of file Mixer.cc.
References Mixer::ChannelConfigInstance::allInstancesInitialized(), QmlObjectListModel::append(), Mixer::Rule::applyIdentifiers, applyRule(), QmlObjectListModel::count(), Fact::rawValueChanged(), Mixer::Rule::selectIdentifier, and QmlObjectListModel::value().
Member Function Documentation
actuatorFunction()
int Mixer::MixerChannel::actuatorFunction () const inline
Definition at line 277 of file Mixer.h.
Referenced by Mixer::Mixers::getFunctions(), and Mixer::Mixers::getSpecificLabelForFunction().
applyRule
void MixerChannel::applyRule (bool noConstraints = false) slot
Definition at line 260 of file Mixer.cc.
References QmlObjectListModel::count(), Mixer::Rule::RuleItem::defaultVal, Mixer::Rule::RuleItem::disabled, Mixer::ChannelConfigInstance::fact(), Mixer::Rule::RuleItem::hasDefault, Mixer::Rule::RuleItem::hasMax, Mixer::Rule::RuleItem::hasMin, Mixer::Rule::RuleItem::hidden, Mixer::Rule::items, Mixer::Rule::RuleItem::max, Mixer::Rule::RuleItem::min, Mixer::ChannelConfigInstance::ruleApplyIdentifierIdx(), Mixer::ChannelConfigInstance::setEnabledRule(), Mixer::ChannelConfigInstance::setVisibleRule(), QmlObjectListModel::value(), and FactMetaData::valueTypeInt32.
Referenced by MixerChannel().
configInstances()
QmlObjectListModel * Mixer::MixerChannel::configInstances () inline
Definition at line 279 of file Mixer.h.
configInstancesChanged
void Mixer::MixerChannel::configInstancesChanged () signal
CONSTANT()
QString label READ label Mixer::MixerChannel::CONSTANT (QmlObjectListModel *configInstances READ configInstances NOTIFY configInstancesChanged) const & inline
Definition at line 273 of file Mixer.h.
getFact()
Fact * MixerChannel::getFact (Function function) const
Definition at line 359 of file Mixer.cc.
References QmlObjectListModel::count(), Mixer::ChannelConfigInstance::fact(), Mixer::Type, and QmlObjectListModel::value().
Referenced by Mixer::Mixers::getSpecificLabelForFunction().
getGeometry()
bool MixerChannel::getGeometry (const ActuatorTypes & actuatorTypes, const MixerOption::ActuatorGroup & group, ActuatorGeometry & geometry) const
Definition at line 313 of file Mixer.cc.
References Mixer::MixerOption::ActuatorGroup::actuatorType, Mixer::AxisX, Mixer::AxisY, Mixer::AxisZ, ActuatorGeometry::ClockWise, QmlObjectListModel::count(), ActuatorGeometry::CounterClockWise, Mixer::ChannelConfigInstance::fact(), ActuatorGeometry::index, ActuatorGeometry::labelIndexOffset, ActuatorGeometry::position, Mixer::PositionX, Mixer::PositionY, Mixer::PositionZ, ActuatorGeometry::spinDirection, Mixer::SpinDirection, ActuatorGeometry::type, Mixer::Type, ActuatorGeometry::typeFromStr(), Mixer::Unspecified, and QmlObjectListModel::value().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Mixer.h
src/Vehicle/Actuators/Mixer.cc