QGroundControl: PX4FirmwareUpgradeThreadWorker Class Reference
PX4FirmwareUpgradeThreadWorker Class Reference
Used to run bootloader commands on a separate thread. These routines are mainly meant to to be called internally by the PX4FirmwareUpgradeThreadController. Clients should call the various public methods exposed by PX4FirmwareUpgradeThreadController.
#include <PX4FirmwareUpgradeThread.h>
Signals
void updateProgress (int curr, int total)
void foundBoard (bool firstAttempt, const QGCSerialPortInfo &portInfo, int type, QString boardName)
void noBoardFound (void)
void boardGone (void)
void foundBoardInfo (int bootloaderVersion, int boardID, int flashSize)
void error (const QString &errorString)
void status (const QString &statusText)
void eraseStarted (void)
void eraseComplete (void)
void flashComplete (void)
Public Member Functions
PX4FirmwareUpgradeThreadWorker (PX4FirmwareUpgradeThreadController *controller)
~PX4FirmwareUpgradeThreadWorker ()
Detailed Description
Used to run bootloader commands on a separate thread. These routines are mainly meant to to be called internally by the PX4FirmwareUpgradeThreadController. Clients should call the various public methods exposed by PX4FirmwareUpgradeThreadController.
Definition at line 18 of file PX4FirmwareUpgradeThread.h.
Constructor & Destructor Documentation
PX4FirmwareUpgradeThreadWorker()
PX4FirmwareUpgradeThreadWorker::PX4FirmwareUpgradeThreadWorker (PX4FirmwareUpgradeThreadController * controller)
Definition at line 12 of file PX4FirmwareUpgradeThread.cc.
References PX4FirmwareUpgradeThreadController::_cancel(), PX4FirmwareUpgradeThreadController::_flashOnThread(), PX4FirmwareUpgradeThreadController::_initThreadWorker(), PX4FirmwareUpgradeThreadController::_rebootOnThread(), and PX4FirmwareUpgradeThreadController::_startFindBoardLoopOnThread().
~PX4FirmwareUpgradeThreadWorker()
PX4FirmwareUpgradeThreadWorker::~PX4FirmwareUpgradeThreadWorker ()
Definition at line 22 of file PX4FirmwareUpgradeThread.cc.
Member Function Documentation
boardGone
void PX4FirmwareUpgradeThreadWorker::boardGone (void) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
eraseComplete
void PX4FirmwareUpgradeThreadWorker::eraseComplete (void) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
eraseStarted
void PX4FirmwareUpgradeThreadWorker::eraseStarted (void) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
error
void PX4FirmwareUpgradeThreadWorker::error (const QString & errorString) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
flashComplete
void PX4FirmwareUpgradeThreadWorker::flashComplete (void) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
foundBoard
void PX4FirmwareUpgradeThreadWorker::foundBoard (bool firstAttempt, const QGCSerialPortInfo & portInfo, int type, QString boardName) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
foundBoardInfo
void PX4FirmwareUpgradeThreadWorker::foundBoardInfo (int bootloaderVersion, int boardID, int flashSize) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
noBoardFound
void PX4FirmwareUpgradeThreadWorker::noBoardFound (void) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
status
void PX4FirmwareUpgradeThreadWorker::status (const QString & statusText) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
updateProgress
void PX4FirmwareUpgradeThreadWorker::updateProgress (int curr, int total) signal
Referenced by PX4FirmwareUpgradeThreadController::PX4FirmwareUpgradeThreadController().
The documentation for this class was generated from the following files:
src/Vehicle/VehicleSetup/PX4FirmwareUpgradeThread.h
src/Vehicle/VehicleSetup/PX4FirmwareUpgradeThread.cc