QGroundControl: GeometryImage::VehicleGeometryImageProvider Class Reference
GeometryImage::VehicleGeometryImageProvider Class Reference
#include <GeometryImage.h>
Classes
struct ImagePosition
Public Member Functions
void drawAxisIndicator (QPainter &p, const QPointF &origin, float fontSize, const QColor &color)
QPixmap requestPixmap (const QString &id, QSize *size, const QSize &requestedSize) override
int getHighlightedMotorIndexAtPos (const QSizeF &displaySize, const QPointF &position)
QList< ActuatorGeometry > & actuators ()
int numMotors () const
Static Public Member Functions
static VehicleGeometryImageProvider * instance ()
Detailed Description
Renders an image of an airframe geometry (currently only multirotor)
Definition at line 17 of file GeometryImage.h.
Member Function Documentation
actuators()
QList< ActuatorGeometry > & GeometryImage::VehicleGeometryImageProvider::actuators () inline
Definition at line 36 of file GeometryImage.h.
Referenced by requestPixmap().
drawAxisIndicator()
void VehicleGeometryImageProvider::drawAxisIndicator (QPainter & p, const QPointF & origin, float fontSize, const QColor & color)
Definition at line 102 of file GeometryImage.cc.
Referenced by requestPixmap().
getHighlightedMotorIndexAtPos()
int VehicleGeometryImageProvider::getHighlightedMotorIndexAtPos (const QSizeF & displaySize, const QPointF & position)
Definition at line 392 of file GeometryImage.cc.
References ActuatorGeometry::Motor.
instance()
VehicleGeometryImageProvider * VehicleGeometryImageProvider::instance () static
Definition at line 383 of file GeometryImage.cc.
References instance().
Referenced by ActuatorComponent::ActuatorComponent(), Actuators::initMotorAssignment(), and instance().
numMotors()
int VehicleGeometryImageProvider::numMotors () const
Definition at line 422 of file GeometryImage.cc.
References ActuatorGeometry::Motor, and numMotors().
Referenced by Actuators::initMotorAssignment(), and numMotors().
requestPixmap()
QPixmap VehicleGeometryImageProvider::requestPixmap (const QString & id, QSize * size, const QSize & requestedSize) override
Definition at line 156 of file GeometryImage.cc.
References actuators(), ActuatorGeometry::ClockWise, drawAxisIndicator(), QGCPalette::globalTheme(), QGCPalette::Light, ActuatorGeometry::Motor, and GeometryImage::VehicleGeometryImageProvider::ImagePosition::type.
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/GeometryImage.h
src/Vehicle/Actuators/GeometryImage.cc