QGroundControl: Fact Class Reference
Fact Class Reference
A Fact is used to hold a single value within the system.
#include <Fact.h>
Signals
void bitmaskStringsChanged ()
void bitmaskValuesChanged ()
void enumsChanged ()
void sendValueChangedSignalsChanged (bool sendValueChangedSignals)
void valueChanged (const QVariant &value)
This signal is only meant for use by the QT property system. It should not be connected to by client code.
void rawValueChanged (const QVariant &value)
void vehicleUpdated (const QVariant &value)
Signalled when the param write ack comes back from the vehicle.
void containerRawValueChanged (const QVariant &value)
This signal is meant for use by Fact container implementations. Used to send changed values to vehicle.
Protected Member Functions
QString _variantToString (const QVariant &variant, int decimalPlaces) const
void _sendValueChangedSignal (const QVariant &value)
Protected Attributes
QString _name
int _componentId = -1
QVariant _rawValue {0}
QRecursiveMutex _rawValueMutex
FactMetaData::ValueType_t _type = FactMetaData::valueTypeInt32
FactMetaData * _metaData = nullptr
bool _sendValueChangedSignals = true
bool _deferredValueChangeSignal = false
FactValueSliderListModel * _valueSliderModel = nullptr
Static Protected Attributes
static constexpr const char * kMissingMetadata = "Meta data pointer missing"
Detailed Description
A Fact is used to hold a single value within the system.
Definition at line 18 of file Fact.h.
Member Function Documentation
_sendValueChangedSignal()
void Fact::_sendValueChangedSignal (const QVariant & value) protected
Definition at line 765 of file Fact.cc.
References _deferredValueChangeSignal, _sendValueChangedSignals, and valueChanged().
_variantToString()
QString Fact::_variantToString (const QVariant & variant, int decimalPlaces) const protected
Definition at line 353 of file Fact.cc.
References FactMetaData::valueTypeBool, FactMetaData::valueTypeDouble, FactMetaData::valueTypeElapsedTimeInSeconds, and FactMetaData::valueTypeFloat.
bitmaskStringsChanged
void Fact::bitmaskStringsChanged () signal
bitmaskValuesChanged
void Fact::bitmaskValuesChanged () signal
containerRawValueChanged
void Fact::containerRawValueChanged (const QVariant & value) signal
This signal is meant for use by Fact container implementations. Used to send changed values to vehicle.
Referenced by QGCCameraParamIO::QGCCameraParamIO().
enumsChanged
void Fact::enumsChanged () signal
rawValueChanged
void Fact::rawValueChanged (const QVariant & value) signal
Referenced by LandingComplexItem::_init(), ActuatorOutputs::ActuatorOutput::ActuatorOutput(), ADSBVehicleManager::ADSBVehicleManager(), Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), APMMavlinkStreamRateSettings::APMMavlinkStreamRateSettings(), AppSettings::AppSettings(), CameraCalc::CameraCalc(), FactBitset::FactBitset(), FactFloatAsBool::FactFloatAsBool(), FirmwareUpgradeController::FirmwareUpgradeController(), GeoFenceController::GeoFenceController(), QGCCameraParamIO::handleParamValue(), AppSettings::indoorPalette(), FollowMe::init(), QGCApplication::init(), VideoManager::init(), MissionController::MissionController(), MissionItem::MissionItem(), MissionItem::MissionItem(), MissionItem::MissionItem(), MissionSettingsItem::MissionSettingsItem(), Mixer::MixerChannel::MixerChannel(), Q_APPLICATION_STATIC(), QGCCameraParamIO::QGCCameraParamIO(), AppSettings::qLocaleLanguage(), RemoteIDManager::RemoteIDManager(), SettingsFact::SettingsFact(), SimulatedCameraControl::SimulatedCameraControl(), Vehicle::stopTrackingFirmwareVehicleTypeChanges(), BatteryIndicatorSettings::threshold1(), BatteryIndicatorSettings::threshold2(), Vehicle::trackFirmwareVehicleTypeChanges(), TransectStyleComplexItem::TransectStyleComplexItem(), Vehicle::Vehicle(), and Viewer3DTerrainGeometry::Viewer3DTerrainGeometry().
sendValueChangedSignalsChanged
void Fact::sendValueChangedSignalsChanged (bool sendValueChangedSignals) signal
valueChanged
void Fact::valueChanged (const QVariant & value) signal
This signal is only meant for use by the QT property system. It should not be connected to by client code.
Referenced by LandingComplexItem::_init(), _sendValueChangedSignal(), APMRadioComponent::APMRadioComponent(), CameraCalc::CameraCalc(), CameraSection::CameraSection(), CorridorScanComplexItem::CorridorScanComplexItem(), FixedWingLandingComplexItem::FixedWingLandingComplexItem(), VideoSettings::forceVideoDecoder(), QGCCameraParamIO::handleParamValue(), AudioOutput::init(), VideoSettings::lowLatencyMode(), VideoSettings::rtspTimeout(), VideoSettings::rtspUrl(), SpeedSection::SpeedSection(), StructureScanComplexItem::StructureScanComplexItem(), SurveyComplexItem::SurveyComplexItem(), VideoSettings::tcpUrl(), TransectStyleComplexItem::TransectStyleComplexItem(), VideoSettings::udpUrl(), and VideoSettings::videoSource().
vehicleUpdated
void Fact::vehicleUpdated (const QVariant & value) signal
Signalled when the param write ack comes back from the vehicle.
Member Data Documentation
_componentId
int Fact::_componentId = -1 protected
Definition at line 205 of file Fact.h.
_deferredValueChangeSignal
bool Fact::_deferredValueChangeSignal = false protected
Definition at line 211 of file Fact.h.
Referenced by _sendValueChangedSignal().
_metaData
FactMetaData* Fact::_metaData = nullptr protected
Definition at line 209 of file Fact.h.
_name
QString Fact::_name protected
Definition at line 204 of file Fact.h.
Referenced by SettingsFact::SettingsFact().
_rawValue
QVariant Fact::_rawValue {0} protected
Definition at line 206 of file Fact.h.
Referenced by SettingsFact::SettingsFact().
_rawValueMutex
QRecursiveMutex Fact::_rawValueMutex mutable protected
Definition at line 207 of file Fact.h.
Referenced by SettingsFact::SettingsFact().
_sendValueChangedSignals
bool Fact::_sendValueChangedSignals = true protected
Definition at line 210 of file Fact.h.
Referenced by _sendValueChangedSignal().
_type
FactMetaData::ValueType_t Fact::_type = FactMetaData::valueTypeInt32 protected
Definition at line 208 of file Fact.h.
_valueSliderModel
FactValueSliderListModel* Fact::_valueSliderModel = nullptr protected
Definition at line 212 of file Fact.h.
kMissingMetadata
constexpr const char* Fact::kMissingMetadata = "Meta data pointer missing" static constexpr protected
Definition at line 214 of file Fact.h.
The documentation for this class was generated from the following files:
src/FactSystem/Fact.h
src/FactSystem/Fact.cc