QGroundControl: MAVLinkProtocol Class Reference
MAVLinkProtocol Class Reference
#include <MAVLinkProtocol.h>
Public Slots
void receiveBytes (LinkInterface *link, const QByteArray &data)
void logSentBytes (const LinkInterface *link, const QByteArray &data)
static void deleteTempLogFiles ()
Deletes any log files which are in the temp directory.
Signals
void vehicleHeartbeatInfo (LinkInterface *link, int vehicleId, int componentId, int vehicleFirmwareType, int vehicleType)
Heartbeat received on link.
void messageReceived (LinkInterface *link, const mavlink_message_t &message)
Message received and directly copied via signal.
void mavlinkMessageStatus (int sysid, uint64_t totalSent, uint64_t totalReceived, uint64_t totalLoss, float lossPercent)
Public Member Functions
MAVLinkProtocol (QObject *parent=nullptr)
~MAVLinkProtocol ()
Destructor for the MAVLinkProtocol class.
void init ()
int getSystemId () const
Get the system id of this application.
void resetMetadataForLink (LinkInterface *link)
Reset the counters for all metadata for this link.
void suspendLogForReplay (bool suspend)
Suspend/Restart logging during replay.
void checkForLostLogFiles ()
Static Public Member Functions
static MAVLinkProtocol * instance ()
static QString getName ()
Get the human-friendly name of this protocol.
static int getComponentId ()
Get the component id of this application.
Detailed Description
MAVLink micro air vehicle protocol reference implementation. MAVLink is a generic communication protocol for micro air vehicles. for more information, please see the official website: https://mavlink.io
Definition at line 16 of file MAVLinkProtocol.h.
Constructor & Destructor Documentation
MAVLinkProtocol()
MAVLinkProtocol::MAVLinkProtocol (QObject * parent = nullptr) explicit
Constructs an MAVLinkProtocol object.
Parameters
parent The parent QObject.
Definition at line 26 of file MAVLinkProtocol.cc.
~MAVLinkProtocol()
MAVLinkProtocol::~MAVLinkProtocol ()
Destructor for the MAVLinkProtocol class.
Definition at line 33 of file MAVLinkProtocol.cc.
Member Function Documentation
checkForLostLogFiles()
void MAVLinkProtocol::checkForLostLogFiles ()
Checks the temp directory for log files which may have been left there. This could happen if QGC crashes without the temp log file being saved. Give the user an option to save these orphaned files.
Definition at line 348 of file MAVLinkProtocol.cc.
deleteTempLogFiles
void MAVLinkProtocol::deleteTempLogFiles () static slot
Deletes any log files which are in the temp directory.
Definition at line 367 of file MAVLinkProtocol.cc.
getComponentId()
static int MAVLinkProtocol::getComponentId () inline static
Get the component id of this application.
Definition at line 41 of file MAVLinkProtocol.h.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), PlanManager::_writeMissionCount(), Vehicle::clearAllParamMapRC(), OnboardLogController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), QGCCameraParamIO::paramRequest(), Vehicle::requestDataStream(), Vehicle::sendDisableSigning(), APMFirmwarePlugin::sendGCSMotionReport(), FirmwarePlugin::sendGCSMotionReport(), Vehicle::sendJoystickDataThreadSafe(), Vehicle::sendParamMapRC(), Vehicle::sendSetupSigning(), Vehicle::setCurrentMissionSequence(), Vehicle::setEstimatorOrigin(), Vehicle::setFlightMode(), Vehicle::startCalibration(), and MissionManager::writeArduPilotGuidedMissionItem().
getName()
static QString MAVLinkProtocol::getName () inline static
Get the human-friendly name of this protocol.
Definition at line 35 of file MAVLinkProtocol.h.
Referenced by logSentBytes().
getSystemId()
int MAVLinkProtocol::getSystemId () const
Get the system id of this application.
Definition at line 484 of file MAVLinkProtocol.cc.
References MavlinkSettings::gcsMavlinkSystemID().
Referenced by OnboardLogController::eraseAll(), QGCCameraParamIO::paramRequest(), Vehicle::sendDisableSigning(), APMFirmwarePlugin::sendGCSMotionReport(), and Vehicle::sendSetupSigning().
init()
void MAVLinkProtocol::init ()
Definition at line 45 of file MAVLinkProtocol.cc.
References MultiVehicleManager::vehicleRemoved().
instance()
MAVLinkProtocol * MAVLinkProtocol::instance () static
Gets the singleton instance of MAVLinkProtocol.
Returns
The singleton instance.
Definition at line 40 of file MAVLinkProtocol.cc.
Referenced by PlanManager::_handleMissionRequest(), PlanManager::_readTransactionComplete(), PlanManager::_removeAllWorker(), VehicleCameraControl::_requestAllParameters(), PlanManager::_requestList(), PlanManager::_requestNextMissionItem(), PlanManager::_writeMissionCount(), Vehicle::clearAllParamMapRC(), OnboardLogController::eraseAll(), APMFirmwarePlugin::guidedModeChangeAltitude(), MAVLinkInspectorController::MAVLinkInspectorController(), QGCCameraParamIO::paramRequest(), LogReplayWorker::pause(), LogReplayWorker::play(), Vehicle::requestDataStream(), Vehicle::sendDisableSigning(), APMFirmwarePlugin::sendGCSMotionReport(), FirmwarePlugin::sendGCSMotionReport(), Vehicle::sendJoystickDataThreadSafe(), Vehicle::sendParamMapRC(), Vehicle::sendSetupSigning(), Vehicle::setCurrentMissionSequence(), Vehicle::setEstimatorOrigin(), Vehicle::setFlightMode(), Vehicle::startCalibration(), Vehicle::startTimerRevertAllowTakeover(), Vehicle::Vehicle(), and MissionManager::writeArduPilotGuidedMissionItem().
logSentBytes
void MAVLinkProtocol::logSentBytes (const LinkInterface * link, const QByteArray & data) slot
Log bytes sent from a communication interface and logs a MAVLink packet. It can handle multiple links in parallel, as each link has it's own buffer/parsing state machine.
Parameters
link The interface to read from
Definition at line 66 of file MAVLinkProtocol.cc.
References getName(), and QGC::showAppMessage().
mavlinkMessageStatus
void MAVLinkProtocol::mavlinkMessageStatus (int sysid, uint64_t totalSent, uint64_t totalReceived, uint64_t totalLoss, float lossPercent) signal
Referenced by Vehicle::Vehicle().
messageReceived
void MAVLinkProtocol::messageReceived (LinkInterface * link, const mavlink_message_t & message) signal
Message received and directly copied via signal.
Referenced by MAVLinkInspectorController::MAVLinkInspectorController(), and Vehicle::Vehicle().
receiveBytes
void MAVLinkProtocol::receiveBytes (LinkInterface * link, const QByteArray & data) slot
Receive bytes from a communication interface and constructs a MAVLink packet
Parameters
link The interface to read from
Definition at line 89 of file MAVLinkProtocol.cc.
References LinkInterface::mavlinkChannel(), and LinkInterface::reportMavlinkV1Traffic().
resetMetadataForLink()
void MAVLinkProtocol::resetMetadataForLink (LinkInterface * link)
Reset the counters for all metadata for this link.
Definition at line 56 of file MAVLinkProtocol.cc.
References LinkInterface::mavlinkChannel(), and LinkInterface::setDecodedFirstMavlinkPacket().
suspendLogForReplay()
void MAVLinkProtocol::suspendLogForReplay (bool suspend) inline
Suspend/Restart logging during replay.
Definition at line 47 of file MAVLinkProtocol.h.
Referenced by LogReplayWorker::pause(), and LogReplayWorker::play().
vehicleHeartbeatInfo
void MAVLinkProtocol::vehicleHeartbeatInfo (LinkInterface * link, int vehicleId, int componentId, int vehicleFirmwareType, int vehicleType) signal
Heartbeat received on link.
The documentation for this class was generated from the following files:
src/Comms/MAVLinkProtocol.h
src/Comms/MAVLinkProtocol.cc