QGroundControl: FirmwarePlugin Class Reference
FirmwarePlugin Class Reference
#include <FirmwarePlugin.h>
Public Types
enum FirmwareCapabilities {
SetFlightModeCapability = 1 << 0 , PauseVehicleCapability = 1 << 1 , GuidedModeCapability = 1 << 2 , OrbitModeCapability = 1 << 3 ,
TakeoffVehicleCapability = 1 << 4 , ROIModeCapability = 1 << 5 , ChangeHeadingCapability = 1 << 6 , GuidedTakeoffCapability = 1 << 7
}
Set of optional capabilites which firmware may support.
typedef QMap< QString, QString > remapParamNameMap_t
typedef QMap< int, remapParamNameMap_t > remapParamNameMinorVersionRemapMap_t
typedef QMap< int, remapParamNameMinorVersionRemapMap_t > remapParamNameMajorVersionMap_t
Signals
void toolIndicatorsChanged ()
Public Member Functions
FirmwarePlugin (QObject *parent=nullptr)
virtual ~FirmwarePlugin ()
virtual AutoPilotPlugin * autopilotPlugin (Vehicle *vehicle) const
virtual void initializeVehicle (Vehicle *)
Called when Vehicle is first created to perform any firmware specific setup.
virtual bool isCapable (const Vehicle *, FirmwareCapabilities) const
virtual QStringList flightModes (Vehicle *) const
virtual QString flightMode (uint8_t base_mode, uint32_t custom_mode) const
virtual bool setFlightMode (const QString &flightMode, uint8_t *base_mode, uint32_t *custom_mode) const
virtual bool MAV_CMD_DO_SET_MODE_is_supported () const
returns true if this flight stack supports MAV_CMD_DO_SET_MODE
virtual QString pauseFlightMode () const
Returns The flight mode which indicates the vehicle is paused.
virtual QString missionFlightMode () const
Returns the flight mode for running missions.
virtual QString rtlFlightMode () const
Returns the flight mode for RTL.
virtual QString smartRTLFlightMode () const
Returns the flight mode for Smart RTL.
virtual bool supportsSmartRTL () const
virtual QString landFlightMode () const
Returns the flight mode for Land.
virtual QString takeOffFlightMode () const
Returns the flight mode for TakeOff.
virtual QString motorDetectionFlightMode () const
Returns the flight mode for Motor Detection.
virtual QString stabilizedFlightMode () const
Returns the flight mode for Stabilized.
virtual QString takeControlFlightMode () const
Returns the flight mode to use when the operator wants to take back control from autonomouse flight.
virtual bool isGuidedMode (const Vehicle *) const
Returns whether the vehicle is in guided mode or not.
virtual QString gotoFlightMode () const
Returns the flight mode which the vehicle will be in if it is performing a goto location.
virtual QString followFlightMode () const
Returns the flight mode which the vehicle will be for follow me.
virtual void setGuidedMode (Vehicle *vehicle, bool guidedMode) const
Set guided flight mode.
virtual void pauseVehicle (Vehicle *vehicle) const
virtual void guidedModeRTL (Vehicle *vehicle, bool smartRTL) const
Command vehicle to return to launch.
virtual void guidedModeLand (Vehicle *vehicle) const
Command vehicle to land at current location.
virtual void guidedModeTakeoff (Vehicle *vehicle, double takeoffAltRel) const
Command vehicle to takeoff from current location to the specified height.
virtual void guidedModeChangeHeading (Vehicle *vehicle, const QGeoCoordinate &headingCoord) const
Command vehicle to rotate towards specified location.
virtual double minimumTakeoffAltitudeMeters (Vehicle *) const
virtual double maximumHorizontalSpeedMultirotor (Vehicle *) const
virtual double maximumEquivalentAirspeed (Vehicle *) const
virtual double minimumEquivalentAirspeed (Vehicle *) const
virtual bool hasGripper (const Vehicle *) const
virtual bool mulirotorSpeedLimitsAvailable (Vehicle *) const
virtual bool fixedWingAirSpeedLimitsAvailable (Vehicle *) const
virtual void startTakeoff (Vehicle *vehicle) const
Command the vehicle to start a takeoff.
virtual void startMission (Vehicle *vehicle) const
Command the vehicle to start the mission.
virtual void guidedModeGotoLocation (Vehicle *vehicle, const QGeoCoordinate &gotoCoord, double forwardFlightLoiterRadius=0.0) const
Command vehicle to move to specified location (altitude is included and relative)
virtual void guidedModeChangeAltitude (Vehicle *vehicle, double altitudeChange, bool pauseVehicle)
virtual void guidedModeChangeGroundSpeedMetersSecond (Vehicle *vehicle, double groundspeed) const
virtual void guidedModeChangeEquivalentAirspeedMetersSecond (Vehicle *vehicle, double airspeed_equiv) const
virtual int defaultJoystickTXMode () const
virtual bool supportsThrottleModeCenterZero () const
virtual bool supportsNegativeThrust (Vehicle *) const
virtual bool supportsRadio () const
virtual bool supportsJSButton () const
virtual bool supportsMotorInterference () const
virtual bool adjustIncomingMavlinkMessage (Vehicle *, mavlink_message_t *)
virtual void adjustOutgoingMavlinkMessageThreadSafe (Vehicle *, LinkInterface *, mavlink_message_t *)
virtual bool sendHomePositionToVehicle () const
virtual void _getParameterMetaDataVersionInfo (const QString &metaDataFile, int &majorVersion, int &minorVersion) const
virtual QString _internalParameterMetaDataFile (const Vehicle *) const
virtual QObject * _loadParameterMetaData (const QString &)
virtual FactMetaData * _getMetaDataForFact (QObject *, const QString &, FactMetaData::ValueType_t, MAV_TYPE) const
virtual QList< MAV_CMD > supportedMissionCommands (QGCMAVLink::VehicleClass_t) const
List of supported mission commands. Empty list for all commands supported.
virtual QString missionCommandOverrides (QGCMAVLink::VehicleClass_t vehicleClass) const
virtual const remapParamNameMajorVersionMap_t & paramNameRemapMajorVersionMap () const
Returns the mapping structure which is used to map from one parameter name to another based on firmware version.
virtual int remapParamNameHigestMinorVersionNumber (int) const
Returns the highest major version number that is known to the remap for this specified major version.
virtual bool multiRotorCoaxialMotors (Vehicle *) const
virtual bool multiRotorXConfig (Vehicle *) const
virtual QString offlineEditingParamFile (Vehicle *) const
Return the resource file which contains the set of params loaded for offline editing.
virtual QString brandImageIndoor (const Vehicle *) const
Return the resource file which contains the brand image for the vehicle for Indoor theme.
virtual QString brandImageOutdoor (const Vehicle *) const
Return the resource file which contains the brand image for the vehicle for Outdoor theme.
virtual QString vehicleImageOpaque (const Vehicle *) const
Return the resource file which contains the vehicle icon used in the flight view when the view is dark (Satellite for instance)
virtual QString vehicleImageOutline (const Vehicle *) const
Return the resource file which contains the vehicle icon used in the flight view when the view is light (Map for instance)
virtual QVariant expandedToolbarIndicatorSource (const Vehicle *, const QString &) const
virtual const QVariantList & toolIndicators (const Vehicle *vehicle)
virtual QGCCameraManager * createCameraManager (Vehicle *vehicle) const
Creates vehicle camera manager.
virtual MavlinkCameraControl * createCameraControl (const mavlink_camera_information_t *info, Vehicle *vehicle, int compID, QObject *parent=nullptr) const
Camera control.
virtual QMap< QString, FactGroup * > * factGroups ()
Returns a pointer to a dictionary of firmware-specific FactGroups.
virtual void batteryConsumptionData (Vehicle *vehicle, int &mAhBattery, double &hoverAmps, double &cruiseAmps) const
virtual QString autoDisarmParameter (Vehicle *) const
virtual bool hasGimbal (Vehicle *vehicle, bool &rollSupported, bool &pitchSupported, bool &yawSupported) const
virtual uint32_t highLatencyCustomModeTo32Bits (uint16_t hlCustomMode) const
Convert from HIGH_LATENCY2.custom_mode value to correct 32 bit value.
virtual void checkIfIsLatestStable (Vehicle *vehicle) const
Used to check if running firmware is latest stable version.
int versionCompare (const Vehicle *vehicle, const QString &compare) const
int versionCompare (const Vehicle *vehicle, int major, int minor, int patch) const
virtual void adjustMetaData (MAV_TYPE, FactMetaData *)
virtual void sendGCSMotionReport (Vehicle *vehicle, const FollowMe::GCSMotionReport &motionReport, uint8_t estimationCapabilities) const
Sends the appropriate mavlink message for follow me support.
virtual QString getHobbsMeter (Vehicle *vehicle) const
gets hobbs meter from autopilot. This should be reimplmeented for each firmware
virtual Autotune * createAutotune (Vehicle *vehicle) const
Creates Autotune object.
virtual void updateAvailableFlightModes (FlightModeList &flightModeList)
Update Available flight modes recieved from vehicle.
Protected Member Functions
bool _armVehicleAndValidate (Vehicle *vehicle) const
bool _setFlightModeAndValidate (Vehicle *vehicle, const QString &flightMode) const
virtual QString _getLatestVersionFileUrl (Vehicle *) const
returns url with latest firmware release information.
virtual void _versionFileDownloadFinished (const QString &remoteFile, const QString &localFile, const Vehicle *vehicle) const
Callback to process file with latest release information.
virtual QString _versionRegex () const
Returns regex QString to extract version information from text.
void _setModeEnumToModeStringMapping (FlightModeCustomModeMap enumToString)
virtual uint32_t _convertToCustomFlightModeEnum (uint32_t val) const
void _updateFlightModeList (FlightModeList &flightModeList)
void _addNewFlightMode (FirmwareFlightMode &flightMode)
Protected Attributes
FlightModeList _flightModeList
FlightModeCustomModeMap _modeEnumToString
QVariantList _toolIndicatorList
QVariantList _modeIndicatorList
Detailed Description
The FirmwarePlugin class represents the methods and objects which are specific to a certain Firmware flight stack. This is the only place where flight stack specific code should reside in QGroundControl. The remainder of the QGroundControl source is generic to a common mavlink implementation. The implementation in the base class supports mavlink generic firmware. Override the base clase virtuals to create your own firmware specific plugin.
Definition at line 65 of file FirmwarePlugin.h.
Member Typedef Documentation
remapParamNameMajorVersionMap_t
typedef QMap<int, remapParamNameMinorVersionRemapMap_t> FirmwarePlugin::remapParamNameMajorVersionMap_t
Maps from firmware major version number to remapParamNameMinorVersionRemapMap_t entry key: firmware major version value: remapParamNameMinorVersionRemapMap_t entry
Definition at line 98 of file FirmwarePlugin.h.
remapParamNameMap_t
typedef QMap<QString, QString> FirmwarePlugin::remapParamNameMap_t
Maps from on parameter name to another key: parameter name to translate from value: mapped parameter name
Definition at line 88 of file FirmwarePlugin.h.
remapParamNameMinorVersionRemapMap_t
typedef QMap<int, remapParamNameMap_t> FirmwarePlugin::remapParamNameMinorVersionRemapMap_t
Maps from firmware minor version to remapParamNameMap_t entry key: firmware minor version value: remapParamNameMap_t entry
Definition at line 93 of file FirmwarePlugin.h.
Member Enumeration Documentation
FirmwareCapabilities
enum FirmwarePlugin::FirmwareCapabilities
Set of optional capabilites which firmware may support.
Enumerator
SetFlightModeCapability
FirmwarePlugin::setFlightMode method is supported.
PauseVehicleCapability
Vehicle supports pausing at current location.
GuidedModeCapability
Vehicle supports guided mode commands.
OrbitModeCapability
Vehicle supports orbit mode.
TakeoffVehicleCapability
Vehicle supports taking off.
ROIModeCapability
Vehicle supports ROI (both in Fly guided mode and from Plan creation)
ChangeHeadingCapability
Vehicle supports changing heading at current location.
GuidedTakeoffCapability
Vehicle supports guided takeoff.
Definition at line 74 of file FirmwarePlugin.h.
Constructor & Destructor Documentation
FirmwarePlugin()
FirmwarePlugin::FirmwarePlugin (QObject * parent = nullptr) explicit
Definition at line 20 of file FirmwarePlugin.cc.
~FirmwarePlugin()
FirmwarePlugin::~FirmwarePlugin () virtual
Definition at line 26 of file FirmwarePlugin.cc.
Member Function Documentation
_addNewFlightMode()
void FirmwarePlugin::_addNewFlightMode (FirmwareFlightMode & flightMode) protected
Definition at line 447 of file FirmwarePlugin.cc.
References _flightModeList, FirmwareFlightMode::custom_mode, and FirmwareFlightMode::mode_name.
Referenced by _updateFlightModeList().
_armVehicleAndValidate()
bool FirmwarePlugin::_armVehicleAndValidate (Vehicle * vehicle) const protected
Arms the vehicle with validation and retries
Returns
: true - vehicle armed, false - vehicle failed to arm
Definition at line 217 of file FirmwarePlugin.cc.
References Vehicle::armed(), and Vehicle::setArmed().
Referenced by APMFirmwarePlugin::startMission(), PX4FirmwarePlugin::startMission(), APMFirmwarePlugin::startTakeoff(), and PX4FirmwarePlugin::startTakeoff().
_convertToCustomFlightModeEnum()
virtual uint32_t FirmwarePlugin::_convertToCustomFlightModeEnum (uint32_t val) const inline protected virtual
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, and ArduSubFirmwarePlugin.
Definition at line 419 of file FirmwarePlugin.h.
Referenced by APMFirmwarePlugin::guidedFlightMode(), APMFirmwarePlugin::missionFlightMode(), APMFirmwarePlugin::rtlFlightMode(), and APMFirmwarePlugin::smartRTLFlightMode().
_getLatestVersionFileUrl()
virtual QString FirmwarePlugin::_getLatestVersionFileUrl (Vehicle *) const inline protected virtual
returns url with latest firmware release information.
Definition at line 407 of file FirmwarePlugin.h.
Referenced by checkIfIsLatestStable().
_getMetaDataForFact()
virtual FactMetaData * FirmwarePlugin::_getMetaDataForFact (QObject * , const QString & , FactMetaData::ValueType_t , MAV_TYPE) const inline virtual
Returns the FactMetaData associated with the parameter name
Parameters
opaqueParameterMetaData Opaque pointer returned from loadParameterMetaData Important: Only CompInfoParam code should use this method
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 298 of file FirmwarePlugin.h.
Referenced by CompInfoParam::factMetaDataForName().
_getParameterMetaDataVersionInfo()
void FirmwarePlugin::_getParameterMetaDataVersionInfo (const QString & metaDataFile, int & majorVersion, int & minorVersion) const virtual
Returns the parameter set version info pulled from inside the meta data file. -1 if not found. Note: The implementation for this must not vary by vehicle type. Important: Only CompInfoParam code should use this method
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 104 of file FirmwarePlugin.cc.
Referenced by CompInfoParam::_cachePX4MetaDataFile().
_internalParameterMetaDataFile()
virtual QString FirmwarePlugin::_internalParameterMetaDataFile (const Vehicle *) const inline virtual
Returns the internal resource parameter meta date file. Important: Only CompInfoParam code should use this method
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 287 of file FirmwarePlugin.h.
_loadParameterMetaData()
virtual QObject * FirmwarePlugin::_loadParameterMetaData (const QString &) inline virtual
Loads the specified parameter meta data file.
Returns
Opaque parameter meta data information which must be stored with Vehicle. Vehicle is responsible to call deleteParameterMetaData when no longer needed. Important: Only CompInfoParam code should use this method
Reimplemented in PX4FirmwarePlugin, and APMFirmwarePlugin.
Definition at line 293 of file FirmwarePlugin.h.
_setFlightModeAndValidate()
bool FirmwarePlugin::_setFlightModeAndValidate (Vehicle * vehicle, const QString & flightMode) const protected
Sets the vehicle to the specified flight mode with validation and retries
Returns
: true - vehicle in specified flight mode, false - flight mode change failed
Definition at line 241 of file FirmwarePlugin.cc.
References Vehicle::flightMode(), flightMode(), and Vehicle::setFlightMode().
Referenced by APMFirmwarePlugin::guidedModeChangeAltitude(), ArduCopterFirmwarePlugin::guidedModeLand(), PX4FirmwarePlugin::guidedModeLand(), APMFirmwarePlugin::guidedModeRTL(), PX4FirmwarePlugin::guidedModeRTL(), APMFirmwarePlugin::pauseVehicle(), APMFirmwarePlugin::setGuidedMode(), PX4FirmwarePlugin::setGuidedMode(), APMFirmwarePlugin::startMission(), PX4FirmwarePlugin::startMission(), APMFirmwarePlugin::startTakeoff(), and PX4FirmwarePlugin::startTakeoff().
_setModeEnumToModeStringMapping()
void FirmwarePlugin::_setModeEnumToModeStringMapping (FlightModeCustomModeMap enumToString) inline protected
Definition at line 416 of file FirmwarePlugin.h.
References _modeEnumToString.
Referenced by ArduCopterFirmwarePlugin::ArduCopterFirmwarePlugin(), ArduPlaneFirmwarePlugin::ArduPlaneFirmwarePlugin(), ArduRoverFirmwarePlugin::ArduRoverFirmwarePlugin(), ArduSubFirmwarePlugin::ArduSubFirmwarePlugin(), and PX4FirmwarePlugin::PX4FirmwarePlugin().
_updateFlightModeList()
void FirmwarePlugin::_updateFlightModeList (FlightModeList & flightModeList) protected
Definition at line 432 of file FirmwarePlugin.cc.
References _addNewFlightMode(), _flightModeList, _modeEnumToString, and flightMode().
Referenced by updateAvailableFlightModes(), ArduCopterFirmwarePlugin::updateAvailableFlightModes(), ArduPlaneFirmwarePlugin::updateAvailableFlightModes(), ArduRoverFirmwarePlugin::updateAvailableFlightModes(), ArduSubFirmwarePlugin::updateAvailableFlightModes(), and PX4FirmwarePlugin::updateAvailableFlightModes().
_versionFileDownloadFinished()
void FirmwarePlugin::_versionFileDownloadFinished (const QString & remoteFile, const QString & localFile, const Vehicle * vehicle) const protected virtual
Callback to process file with latest release information.
Definition at line 324 of file FirmwarePlugin.cc.
References _versionRegex(), Vehicle::firmwareMajorVersion(), Vehicle::firmwareMinorVersion(), Vehicle::firmwarePatchVersion(), Vehicle::firmwareVersionType(), qgcApp, and Vehicle::versionCompare().
Referenced by checkIfIsLatestStable().
_versionRegex()
virtual QString FirmwarePlugin::_versionRegex () const inline protected virtual
Returns regex QString to extract version information from text.
Definition at line 413 of file FirmwarePlugin.h.
Referenced by _versionFileDownloadFinished().
adjustIncomingMavlinkMessage()
virtual bool FirmwarePlugin::adjustIncomingMavlinkMessage (Vehicle * , mavlink_message_t *) inline virtual
Called before any mavlink message is processed by Vehicle such that the firmwre plugin can adjust any message characteristics. This is handy to adjust or differences in mavlink spec implementations such that the base code can remain mavlink generic.
Parameters
vehicle Vehicle message came from
message[in,out] Mavlink message to adjust if needed.
Returns
false: skip message, true: process message
Reimplemented in APMFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 257 of file FirmwarePlugin.h.
adjustMetaData()
virtual void FirmwarePlugin::adjustMetaData (MAV_TYPE , FactMetaData *) inline virtual
Allows the Firmware plugin to override the facts meta data.
Parameters
vehicleType - Type of current vehicle
metaData - MetaData for fact
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 380 of file FirmwarePlugin.h.
Referenced by Vehicle::Vehicle().
adjustOutgoingMavlinkMessageThreadSafe()
virtual void FirmwarePlugin::adjustOutgoingMavlinkMessageThreadSafe (Vehicle * , LinkInterface * , mavlink_message_t *) inline virtual
Called before any mavlink message is sent to the Vehicle so plugin can adjust any message characteristics. This is handy to adjust or differences in mavlink spec implementations such that the base code can remain mavlink generic.
This method must be thread safe.
@param vehicle Vehicle message came from
@param outgoingLink Link that messae is going out on
@param message[in,out] Mavlink message to adjust if needed.
Reimplemented in APMFirmwarePlugin.
Definition at line 268 of file FirmwarePlugin.h.
Referenced by Vehicle::sendMessageOnLinkThreadSafe().
autoDisarmParameter()
virtual QString FirmwarePlugin::autoDisarmParameter (Vehicle *) const inline virtual
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 357 of file FirmwarePlugin.h.
Referenced by Vehicle::autoDisarm().
autopilotPlugin()
AutoPilotPlugin * FirmwarePlugin::autopilotPlugin (Vehicle * vehicle) const virtual
Returns
The AutoPilotPlugin associated with this firmware plugin. Must be overridden.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 31 of file FirmwarePlugin.cc.
Referenced by Vehicle::Vehicle().
batteryConsumptionData()
void FirmwarePlugin::batteryConsumptionData (Vehicle * vehicle, int & mAhBattery, double & hoverAmps, double & cruiseAmps) const virtual
Returns the data needed to do battery consumption calculations
Parameters
[out] mAhBattery Battery milliamp-hours rating (0 for no battery data available)
[out] hoverAmps Current draw in amps during hover
[out] cruiseAmps Current draw in amps during cruise
Definition at line 272 of file FirmwarePlugin.cc.
brandImageIndoor()
virtual QString FirmwarePlugin::brandImageIndoor (const Vehicle *) const inline virtual
Return the resource file which contains the brand image for the vehicle for Indoor theme.
Reimplemented in APMFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 323 of file FirmwarePlugin.h.
Referenced by Vehicle::brandImageIndoor().
brandImageOutdoor()
virtual QString FirmwarePlugin::brandImageOutdoor (const Vehicle *) const inline virtual
Return the resource file which contains the brand image for the vehicle for Outdoor theme.
Reimplemented in APMFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 326 of file FirmwarePlugin.h.
Referenced by Vehicle::brandImageOutdoor().
checkIfIsLatestStable()
void FirmwarePlugin::checkIfIsLatestStable (Vehicle * vehicle) const virtual
Used to check if running firmware is latest stable version.
Definition at line 299 of file FirmwarePlugin.cc.
References _getLatestVersionFileUrl(), _versionFileDownloadFinished(), QGCFileDownload::finished(), qgcApp, and QGCFileDownload::start().
createAutotune()
Autotune * FirmwarePlugin::createAutotune (Vehicle * vehicle) const virtual
Creates Autotune object.
Definition at line 427 of file FirmwarePlugin.cc.
createCameraControl()
MavlinkCameraControl * FirmwarePlugin::createCameraControl (const mavlink_camera_information_t * info, Vehicle * vehicle, int compID, QObject * parent = nullptr) const virtual
Camera control.
Definition at line 294 of file FirmwarePlugin.cc.
createCameraManager()
QGCCameraManager * FirmwarePlugin::createCameraManager (Vehicle * vehicle) const virtual
Creates vehicle camera manager.
Definition at line 289 of file FirmwarePlugin.cc.
defaultJoystickTXMode()
virtual int FirmwarePlugin::defaultJoystickTXMode () const inline virtual
Default tx mode to apply to joystick axes TX modes are as outlined here: http://www.rc-airplane-world.com/rc-transmitter-modes.html
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 228 of file FirmwarePlugin.h.
expandedToolbarIndicatorSource()
virtual QVariant FirmwarePlugin::expandedToolbarIndicatorSource (const Vehicle * , const QString &) const inline virtual
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 334 of file FirmwarePlugin.h.
Referenced by Vehicle::expandedToolbarIndicatorSource().
factGroups()
virtual QMap< QString, FactGroup * > * FirmwarePlugin::factGroups () inline virtual
Returns a pointer to a dictionary of firmware-specific FactGroups.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 348 of file FirmwarePlugin.h.
fixedWingAirSpeedLimitsAvailable()
virtual bool FirmwarePlugin::fixedWingAirSpeedLimitsAvailable (Vehicle *) const inline virtual
Returns
Return true if we have received the airspeed limits for fixed wing.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 202 of file FirmwarePlugin.h.
flightMode()
QString FirmwarePlugin::flightMode (uint8_t base_mode, uint32_t custom_mode) const virtual
Returns the name for this flight mode. Flight mode names must be human readable as well as audio speakable.
Parameters
base_mode Base mode from mavlink HEARTBEAT message
custom_mode Custom mode from mavlink HEARTBEAT message
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 36 of file FirmwarePlugin.cc.
References _modeEnumToString, and flightMode().
Referenced by _setFlightModeAndValidate(), _updateFlightModeList(), Vehicle::flightMode(), flightMode(), and setFlightMode().
flightModes()
virtual QStringList FirmwarePlugin::flightModes (Vehicle *) const inline virtual
Returns the list of available flight modes for the Fly View dropdown. This may or may not be the full list available from the firmware. Call will be made again if advanced mode changes.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 111 of file FirmwarePlugin.h.
Referenced by Vehicle::flightModes().
followFlightMode()
virtual QString FirmwarePlugin::followFlightMode (void) const inline virtual
Returns the flight mode which the vehicle will be for follow me.
Reimplemented in ArduCopterFirmwarePlugin, ArduRoverFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 162 of file FirmwarePlugin.h.
Referenced by Vehicle::followFlightMode().
getHobbsMeter()
virtual QString FirmwarePlugin::getHobbsMeter (Vehicle * vehicle) const inline virtual
gets hobbs meter from autopilot. This should be reimplmeented for each firmware
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 386 of file FirmwarePlugin.h.
Referenced by Vehicle::hobbsMeter().
gotoFlightMode()
virtual QString FirmwarePlugin::gotoFlightMode (void) const inline virtual
Returns the flight mode which the vehicle will be in if it is performing a goto location.
Reimplemented in APMFirmwarePlugin, ArduCopterFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 159 of file FirmwarePlugin.h.
Referenced by Vehicle::gotoFlightMode().
guidedModeChangeAltitude()
void FirmwarePlugin::guidedModeChangeAltitude (Vehicle * vehicle, double altitudeChange, bool pauseVehicle) virtual
Command vehicle to change altitude
Parameters
altitudeChange If > 0, go up by amount specified, if < 0, go down by amount specified
pauseVehicle true: pause vehicle prior to altitude change
Reimplemented in APMFirmwarePlugin, ArduRoverFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 152 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, pauseVehicle(), and qgcApp.
Referenced by Vehicle::guidedModeChangeAltitude().
guidedModeChangeEquivalentAirspeedMetersSecond()
void FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond (Vehicle * vehicle, double airspeed_equiv) const virtual
Command vehicle to change equivalent airspeed
Parameters
airspeed_equiv Equivalent airspeed in m/s
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 163 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeChangeEquivalentAirspeedMetersSecond().
guidedModeChangeGroundSpeedMetersSecond()
void FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond (Vehicle * vehicle, double groundspeed) const virtual
Command vehicle to change groundspeed
Parameters
groundspeed Groundspeed in m/s
Reimplemented in PX4FirmwarePlugin, and APMFirmwarePlugin.
Definition at line 158 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeChangeGroundSpeedMetersSecond().
guidedModeChangeHeading()
void FirmwarePlugin::guidedModeChangeHeading (Vehicle * vehicle, const QGeoCoordinate & headingCoord) const virtual
Command vehicle to rotate towards specified location.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 168 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeChangeHeading().
guidedModeGotoLocation()
void FirmwarePlugin::guidedModeGotoLocation (Vehicle * vehicle, const QGeoCoordinate & gotoCoord, double forwardFlightLoiterRadius = 0.0) const virtual
Command vehicle to move to specified location (altitude is included and relative)
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 144 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeGotoLocation().
guidedModeLand()
void FirmwarePlugin::guidedModeLand (Vehicle * vehicle) const virtual
Command vehicle to land at current location.
Reimplemented in ArduCopterFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 131 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeLand().
guidedModeRTL()
void FirmwarePlugin::guidedModeRTL (Vehicle * vehicle, bool smartRTL) const virtual
Command vehicle to return to launch.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 124 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeRTL().
guidedModeTakeoff()
void FirmwarePlugin::guidedModeTakeoff (Vehicle * vehicle, double takeoffAltRel) const virtual
Command vehicle to takeoff from current location to the specified height.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 137 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::guidedModeTakeoff().
hasGimbal()
bool FirmwarePlugin::hasGimbal (Vehicle * vehicle, bool & rollSupported, bool & pitchSupported, bool & yawSupported) const virtual
Used to determine whether a vehicle has a gimbal.
Parameters
[out] rollSupported Gimbal supports roll
[out] pitchSupported Gimbal supports pitch
[out] yawSupported Gimbal supports yaw
Returns
true: vehicle has gimbal, false: gimbal support unknown
Definition at line 280 of file FirmwarePlugin.cc.
hasGripper()
virtual bool FirmwarePlugin::hasGripper (const Vehicle *) const inline virtual
Returns
Return true if the GCS has enabled Grip_enable option
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 196 of file FirmwarePlugin.h.
Referenced by Vehicle::hasGripper().
highLatencyCustomModeTo32Bits()
virtual uint32_t FirmwarePlugin::highLatencyCustomModeTo32Bits (uint16_t hlCustomMode) const inline virtual
Convert from HIGH_LATENCY2.custom_mode value to correct 32 bit value.
Reimplemented in PX4FirmwarePlugin.
Definition at line 367 of file FirmwarePlugin.h.
initializeVehicle()
virtual void FirmwarePlugin::initializeVehicle (Vehicle *) inline virtual
Called when Vehicle is first created to perform any firmware specific setup.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 104 of file FirmwarePlugin.h.
Referenced by Vehicle::Vehicle(), and Vehicle::Vehicle().
isCapable()
virtual bool FirmwarePlugin::isCapable (const Vehicle * , FirmwareCapabilities) const inline virtual
Returns
true: Firmware supports all specified capabilites
Reimplemented in APMFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 107 of file FirmwarePlugin.h.
Referenced by VehicleSupports::changeHeading(), Vehicle::flightModeSetAvailable(), VehicleSupports::guidedMode(), VehicleSupports::guidedTakeoffWithAltitude(), VehicleSupports::guidedTakeoffWithoutAltitude(), VehicleSupports::orbitMode(), VehicleSupports::pauseVehicle(), VehicleSupports::roiMode(), and VehicleSupports::takeoffMissionCommand().
isGuidedMode()
virtual bool FirmwarePlugin::isGuidedMode (const Vehicle *) const inline virtual
Returns whether the vehicle is in guided mode or not.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 156 of file FirmwarePlugin.h.
Referenced by Vehicle::guidedMode().
landFlightMode()
virtual QString FirmwarePlugin::landFlightMode (void) const inline virtual
Returns the flight mode for Land.
Reimplemented in ArduCopterFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 141 of file FirmwarePlugin.h.
Referenced by Vehicle::landFlightMode().
MAV_CMD_DO_SET_MODE_is_supported()
virtual bool FirmwarePlugin::MAV_CMD_DO_SET_MODE_is_supported () const inline virtual
returns true if this flight stack supports MAV_CMD_DO_SET_MODE
Reimplemented in APMFirmwarePlugin.
Definition at line 124 of file FirmwarePlugin.h.
Referenced by Vehicle::setFlightMode().
maximumEquivalentAirspeed()
virtual double FirmwarePlugin::maximumEquivalentAirspeed (Vehicle *) const inline virtual
Returns
The maximum equivalent airspeed setpoint.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 190 of file FirmwarePlugin.h.
Referenced by Vehicle::maximumEquivalentAirspeed(), APMFirmwarePlugin::maximumEquivalentAirspeed(), and PX4FirmwarePlugin::maximumEquivalentAirspeed().
maximumHorizontalSpeedMultirotor()
virtual double FirmwarePlugin::maximumHorizontalSpeedMultirotor (Vehicle *) const inline virtual
Returns
The maximum horizontal groundspeed for a multirotor.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 187 of file FirmwarePlugin.h.
Referenced by Vehicle::maximumHorizontalSpeedMultirotor(), APMFirmwarePlugin::maximumHorizontalSpeedMultirotor(), and PX4FirmwarePlugin::maximumHorizontalSpeedMultirotor().
minimumEquivalentAirspeed()
virtual double FirmwarePlugin::minimumEquivalentAirspeed (Vehicle *) const inline virtual
Returns
The minimum equivalent airspeed setpoint
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 193 of file FirmwarePlugin.h.
Referenced by Vehicle::minimumEquivalentAirspeed(), APMFirmwarePlugin::minimumEquivalentAirspeed(), and PX4FirmwarePlugin::minimumEquivalentAirspeed().
minimumTakeoffAltitudeMeters()
virtual double FirmwarePlugin::minimumTakeoffAltitudeMeters (Vehicle *) const inline virtual
Returns
The minimum takeoff altitude (relative) for guided takeoff.
Reimplemented in APMFirmwarePlugin.
Definition at line 184 of file FirmwarePlugin.h.
Referenced by Vehicle::minimumTakeoffAltitudeMeters(), and APMFirmwarePlugin::minimumTakeoffAltitudeMeters().
missionCommandOverrides()
QString FirmwarePlugin::missionCommandOverrides (QGCMAVLink::VehicleClass_t vehicleClass) const virtual
Returns the name of the mission command json override file for the specified vehicle type.
Parameters
vehicleClass Vehicle class to return file for, VehicleClassGeneric is a request for overrides for all vehicle types
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 83 of file FirmwarePlugin.cc.
References QGCMAVLink::VehicleClassFixedWing, QGCMAVLink::VehicleClassGeneric, QGCMAVLink::VehicleClassMultiRotor, QGCMAVLink::VehicleClassRoverBoat, QGCMAVLink::VehicleClassSub, and QGCMAVLink::VehicleClassVTOL.
Referenced by MissionCommandTree::MissionCommandTree().
missionFlightMode()
virtual QString FirmwarePlugin::missionFlightMode (void) const inline virtual
Returns the flight mode for running missions.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 130 of file FirmwarePlugin.h.
Referenced by Vehicle::missionFlightMode(), and Vehicle::setEventsMetadata().
motorDetectionFlightMode()
virtual QString FirmwarePlugin::motorDetectionFlightMode () const inline virtual
Returns the flight mode for Motor Detection.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 147 of file FirmwarePlugin.h.
Referenced by Vehicle::motorDetectionFlightMode().
mulirotorSpeedLimitsAvailable()
virtual bool FirmwarePlugin::mulirotorSpeedLimitsAvailable (Vehicle *) const inline virtual
Returns
Return true if we have received the ground speed limits for the mulirotor.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 199 of file FirmwarePlugin.h.
multiRotorCoaxialMotors()
virtual bool FirmwarePlugin::multiRotorCoaxialMotors (Vehicle *) const inline virtual
Returns
true: Motors are coaxial like an X8 config, false: Quadcopter for example
Reimplemented in ArduCopterFirmwarePlugin.
Definition at line 314 of file FirmwarePlugin.h.
Referenced by Vehicle::coaxialMotors().
multiRotorXConfig()
virtual bool FirmwarePlugin::multiRotorXConfig (Vehicle *) const inline virtual
Returns
true: X confiuration, false: Plus configuration
Reimplemented in ArduCopterFirmwarePlugin.
Definition at line 317 of file FirmwarePlugin.h.
Referenced by Vehicle::xConfigMotors().
offlineEditingParamFile()
virtual QString FirmwarePlugin::offlineEditingParamFile (Vehicle *) const inline virtual
Return the resource file which contains the set of params loaded for offline editing.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 320 of file FirmwarePlugin.h.
Referenced by APMFirmwarePlugin::initializeVehicle().
paramNameRemapMajorVersionMap()
const FirmwarePlugin::remapParamNameMajorVersionMap_t & FirmwarePlugin::paramNameRemapMajorVersionMap (void) const virtual
Returns the mapping structure which is used to map from one parameter name to another based on firmware version.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, and ArduSubFirmwarePlugin.
Definition at line 185 of file FirmwarePlugin.cc.
pauseFlightMode()
virtual QString FirmwarePlugin::pauseFlightMode (void) const inline virtual
Returns The flight mode which indicates the vehicle is paused.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 127 of file FirmwarePlugin.h.
Referenced by APMFirmwarePlugin::guidedModeChangeAltitude(), Vehicle::pauseFlightMode(), and APMFirmwarePlugin::pauseVehicle().
pauseVehicle()
void FirmwarePlugin::pauseVehicle (Vehicle * vehicle) const virtual
Causes the vehicle to stop at current position. If guide mode is supported, vehicle will be let in guide mode. If not, vehicle will be left in Loiter.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 118 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by guidedModeChangeAltitude(), and Vehicle::pauseVehicle().
remapParamNameHigestMinorVersionNumber()
virtual int FirmwarePlugin::remapParamNameHigestMinorVersionNumber (int) const inline virtual
Returns the highest major version number that is known to the remap for this specified major version.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, and ArduSubFirmwarePlugin.
Definition at line 311 of file FirmwarePlugin.h.
rtlFlightMode()
virtual QString FirmwarePlugin::rtlFlightMode (void) const inline virtual
Returns the flight mode for RTL.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 133 of file FirmwarePlugin.h.
Referenced by Vehicle::rtlFlightMode().
sendGCSMotionReport()
void FirmwarePlugin::sendGCSMotionReport (Vehicle * vehicle, const FollowMe::GCSMotionReport & motionReport, uint8_t estimationCapabilities) const virtual
Sends the appropriate mavlink message for follow me support.
Reimplemented in APMFirmwarePlugin.
Definition at line 396 of file FirmwarePlugin.cc.
References FollowMe::GCSMotionReport::altMetersAMSL, MAVLinkProtocol::getComponentId(), MAVLinkProtocol::instance(), FollowMe::GCSMotionReport::lat_int, FollowMe::GCSMotionReport::lon_int, FollowMe::GCSMotionReport::pos_std_dev, VehicleLinkManager::primaryLink(), qgcApp, Vehicle::sendMessageOnLinkThreadSafe(), Vehicle::vehicleLinkManager(), FollowMe::GCSMotionReport::vxMetersPerSec, and FollowMe::GCSMotionReport::vyMetersPerSec.
sendHomePositionToVehicle()
virtual bool FirmwarePlugin::sendHomePositionToVehicle (void) const inline virtual
Determines how to handle the first item of the mission item list. Internally to QGC the first item is always the home position. Generic stack does not want home position sent in the first position. Subsequent sequence numbers must be adjusted. This is the mavlink spec default.
Returns
true: Send first mission item as home position to vehicle. When vehicle has no mission items on it, it may or may not return a home position back in position 0. false: Do not send first item to vehicle, sequence numbers must be adjusted
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 278 of file FirmwarePlugin.h.
Referenced by PlanManager::_handleMissionItem(), MissionController::currentMissionIndex(), MissionManager::generateResumeMission(), MissionController::resumeMission(), MissionController::resumeMissionIndex(), Vehicle::setCurrentMissionSequence(), and PlanManager::writeMissionItems().
setFlightMode()
bool FirmwarePlugin::setFlightMode (const QString & flightMode, uint8_t * base_mode, uint32_t * custom_mode) const virtual
Sets base_mode and custom_mode to specified flight mode.
Parameters
[out] base_mode Base mode for SET_MODE mavlink message
[out] custom_mode Custom mode for SET_MODE mavlink message
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 72 of file FirmwarePlugin.cc.
References flightMode().
setGuidedMode()
void FirmwarePlugin::setGuidedMode (Vehicle * vehicle, bool guidedMode) const virtual
Set guided flight mode.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 111 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::setGuidedMode().
smartRTLFlightMode()
virtual QString FirmwarePlugin::smartRTLFlightMode () const inline virtual
Returns the flight mode for Smart RTL.
Reimplemented in APMFirmwarePlugin.
Definition at line 136 of file FirmwarePlugin.h.
Referenced by Vehicle::smartRTLFlightMode().
stabilizedFlightMode()
virtual QString FirmwarePlugin::stabilizedFlightMode (void) const inline virtual
Returns the flight mode for Stabilized.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 150 of file FirmwarePlugin.h.
Referenced by Vehicle::stabilizedFlightMode().
startMission()
void FirmwarePlugin::startMission (Vehicle * vehicle) const virtual
Command the vehicle to start the mission.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 180 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::startMission().
startTakeoff()
void FirmwarePlugin::startTakeoff (Vehicle * vehicle) const virtual
Command the vehicle to start a takeoff.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 174 of file FirmwarePlugin.cc.
References guided_mode_not_supported_by_vehicle, and qgcApp.
Referenced by Vehicle::startTakeoff().
supportedMissionCommands()
virtual QList< MAV_CMD > FirmwarePlugin::supportedMissionCommands (QGCMAVLink::VehicleClass_t) const inline virtual
List of supported mission commands. Empty list for all commands supported.
Reimplemented in APMFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 301 of file FirmwarePlugin.h.
Referenced by CameraSection::cameraModeSupported(), MissionCommandTree::getCommandsForCategory(), MissionController::insertCancelROIMissionItem(), and MissionController::insertROIMissionItem().
supportsJSButton()
virtual bool FirmwarePlugin::supportsJSButton () const inline virtual
Returns true if the firmware supports the AP_JSButton library, which allows joystick buttons to be assigned via parameters in firmware. Default is false.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 245 of file FirmwarePlugin.h.
Referenced by VehicleSupports::jsButton().
supportsMotorInterference()
virtual bool FirmwarePlugin::supportsMotorInterference () const inline virtual
Returns true if the firmware supports calibrating motor interference offsets for the compass (CompassMot). Default is true.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 249 of file FirmwarePlugin.h.
Referenced by VehicleSupports::motorInterference().
supportsNegativeThrust()
virtual bool FirmwarePlugin::supportsNegativeThrust (Vehicle *) const inline virtual
Returns true if the vehicle and firmware supports the use of negative thrust Typically supported rover.
Reimplemented in ArduRoverFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 237 of file FirmwarePlugin.h.
Referenced by VehicleSupports::negativeThrust().
supportsRadio()
virtual bool FirmwarePlugin::supportsRadio () const inline virtual
Returns true if the firmware supports the use of the RC radio and requires the RC radio setup page. Returns true by default.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 241 of file FirmwarePlugin.h.
Referenced by VehicleSupports::radio().
supportsSmartRTL()
virtual bool FirmwarePlugin::supportsSmartRTL () const inline virtual
Reimplemented in ArduCopterFirmwarePlugin, and ArduRoverFirmwarePlugin.
Definition at line 138 of file FirmwarePlugin.h.
Referenced by VehicleSupports::smartRTL().
supportsThrottleModeCenterZero()
virtual bool FirmwarePlugin::supportsThrottleModeCenterZero () const inline virtual
Returns true if the vehicle and firmware supports the use of a throttle joystick that is zero when centered. Typically not supported on vehicles that have bidirectional throttle.
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 233 of file FirmwarePlugin.h.
takeControlFlightMode()
virtual QString FirmwarePlugin::takeControlFlightMode (void) const inline virtual
Returns the flight mode to use when the operator wants to take back control from autonomouse flight.
Reimplemented in ArduCopterFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 153 of file FirmwarePlugin.h.
Referenced by Vehicle::takeControlFlightMode().
takeOffFlightMode()
virtual QString FirmwarePlugin::takeOffFlightMode (void) const inline virtual
Returns the flight mode for TakeOff.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 144 of file FirmwarePlugin.h.
Referenced by Vehicle::setEventsMetadata(), and APMFirmwarePlugin::startTakeoff().
toolIndicators()
const QVariantList & FirmwarePlugin::toolIndicators (const Vehicle * vehicle) virtual
Returns the list of toolbar tool indicators associated with a vehicle signals toolIndicatorsChanged
Returns
A list of QUrl with the indicators
Reimplemented in APMFirmwarePlugin.
Definition at line 192 of file FirmwarePlugin.cc.
References _toolIndicatorList.
Referenced by Vehicle::toolIndicators(), and APMFirmwarePlugin::toolIndicators().
toolIndicatorsChanged
void FirmwarePlugin::toolIndicatorsChanged () signal
updateAvailableFlightModes()
virtual void FirmwarePlugin::updateAvailableFlightModes (FlightModeList & flightModeList) inline virtual
Update Available flight modes recieved from vehicle.
Reimplemented in ArduCopterFirmwarePlugin, ArduPlaneFirmwarePlugin, ArduRoverFirmwarePlugin, ArduSubFirmwarePlugin, and PX4FirmwarePlugin.
Definition at line 392 of file FirmwarePlugin.h.
References _updateFlightModeList().
Referenced by StandardModes::gotMessage().
vehicleImageOpaque()
virtual QString FirmwarePlugin::vehicleImageOpaque (const Vehicle *) const inline virtual
Return the resource file which contains the vehicle icon used in the flight view when the view is dark (Satellite for instance)
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 329 of file FirmwarePlugin.h.
Referenced by Vehicle::vehicleImageOpaque().
vehicleImageOutline()
virtual QString FirmwarePlugin::vehicleImageOutline (const Vehicle *) const inline virtual
Return the resource file which contains the vehicle icon used in the flight view when the view is light (Map for instance)
Reimplemented in ArduSubFirmwarePlugin.
Definition at line 332 of file FirmwarePlugin.h.
Referenced by Vehicle::vehicleImageOutline().
versionCompare() [1/2]
int FirmwarePlugin::versionCompare (const Vehicle * vehicle, const QString & compare) const
Used to check if running current version is equal or higher than the one being compared. returns 1 if current > compare, 0 if current == compare, -1 if current < compare
Definition at line 381 of file FirmwarePlugin.cc.
References versionCompare().
Referenced by Vehicle::versionCompare(), versionCompare(), and Vehicle::versionCompare().
versionCompare() [2/2]
int FirmwarePlugin::versionCompare (const Vehicle * vehicle, int major, int minor, int patch) const
Definition at line 361 of file FirmwarePlugin.cc.
References Vehicle::firmwareMajorVersion(), Vehicle::firmwareMinorVersion(), and Vehicle::firmwarePatchVersion().
Member Data Documentation
_flightModeList
FlightModeList FirmwarePlugin::_flightModeList protected
Definition at line 425 of file FirmwarePlugin.h.
Referenced by _addNewFlightMode(), _updateFlightModeList(), APMFirmwarePlugin::flightModes(), PX4FirmwarePlugin::flightModes(), APMFirmwarePlugin::setFlightMode(), and PX4FirmwarePlugin::setFlightMode().
_modeEnumToString
FlightModeCustomModeMap FirmwarePlugin::_modeEnumToString protected
Definition at line 426 of file FirmwarePlugin.h.
Referenced by _setModeEnumToModeStringMapping(), _updateFlightModeList(), flightMode(), APMFirmwarePlugin::flightMode(), PX4FirmwarePlugin::flightMode(), ArduCopterFirmwarePlugin::followFlightMode(), ArduRoverFirmwarePlugin::followFlightMode(), PX4FirmwarePlugin::followFlightMode(), PX4FirmwarePlugin::gotoFlightMode(), APMFirmwarePlugin::guidedFlightMode(), ArduCopterFirmwarePlugin::landFlightMode(), PX4FirmwarePlugin::landFlightMode(), APMFirmwarePlugin::missionFlightMode(), PX4FirmwarePlugin::missionFlightMode(), ArduSubFirmwarePlugin::motorDetectionFlightMode(), ArduCopterFirmwarePlugin::pauseFlightMode(), ArduPlaneFirmwarePlugin::pauseFlightMode(), ArduRoverFirmwarePlugin::pauseFlightMode(), PX4FirmwarePlugin::pauseFlightMode(), APMFirmwarePlugin::rtlFlightMode(), PX4FirmwarePlugin::rtlFlightMode(), APMFirmwarePlugin::smartRTLFlightMode(), ArduCopterFirmwarePlugin::stabilizedFlightMode(), ArduPlaneFirmwarePlugin::stabilizedFlightMode(), ArduRoverFirmwarePlugin::stabilizedFlightMode(), ArduSubFirmwarePlugin::stabilizedFlightMode(), PX4FirmwarePlugin::stabilizedFlightMode(), ArduCopterFirmwarePlugin::takeControlFlightMode(), PX4FirmwarePlugin::takeControlFlightMode(), ArduPlaneFirmwarePlugin::takeOffFlightMode(), and PX4FirmwarePlugin::takeOffFlightMode().
_modeIndicatorList
QVariantList FirmwarePlugin::_modeIndicatorList protected
Definition at line 429 of file FirmwarePlugin.h.
_toolIndicatorList
QVariantList FirmwarePlugin::_toolIndicatorList protected
Definition at line 428 of file FirmwarePlugin.h.
Referenced by toolIndicators().
The documentation for this class was generated from the following files:
src/FirmwarePlugin/FirmwarePlugin.h
src/FirmwarePlugin/FirmwarePlugin.cc