QGroundControl: OsmParserThread Class Reference
OsmParserThread Class Reference
#include <OsmParserThread.h>
Classes
struct BuildingType_t
Signals
void fileParsed (bool isValid)
void startThread (const QString &filePath)
Public Member Functions
OsmParserThread (QObject *parent=nullptr)
~OsmParserThread ()
void start (const QString &filePath)
const QGeoCoordinate & gpsRefPoint () const
const QMap< uint64_t, QGeoCoordinate > & mapNodes () const
const QMap< uint64_t, BuildingType_t > & mapBuildings () const
const QGeoCoordinate & coordinateMin () const
const QGeoCoordinate & coordinateMax () const
Friends
class OsmParserThreadTest
Detailed Description
Definition at line 16 of file OsmParserThread.h.
Constructor & Destructor Documentation
OsmParserThread()
OsmParserThread::OsmParserThread (QObject * parent = nullptr) explicit
Definition at line 217 of file OsmParserThread.cc.
References startThread().
~OsmParserThread()
OsmParserThread::~OsmParserThread ()
Definition at line 227 of file OsmParserThread.cc.
Member Function Documentation
coordinateMax()
const QGeoCoordinate & OsmParserThread::coordinateMax () const inline
Definition at line 47 of file OsmParserThread.h.
coordinateMin()
const QGeoCoordinate & OsmParserThread::coordinateMin () const inline
Definition at line 46 of file OsmParserThread.h.
fileParsed
void OsmParserThread::fileParsed (bool isValid) signal
gpsRefPoint()
const QGeoCoordinate & OsmParserThread::gpsRefPoint () const inline
Definition at line 43 of file OsmParserThread.h.
mapBuildings()
const QMap< uint64_t, BuildingType_t > & OsmParserThread::mapBuildings () const inline
Definition at line 45 of file OsmParserThread.h.
Referenced by OsmParser::buildingToMesh().
mapNodes()
const QMap< uint64_t, QGeoCoordinate > & OsmParserThread::mapNodes () const inline
Definition at line 44 of file OsmParserThread.h.
start()
void OsmParserThread::start (const QString & filePath)
Definition at line 234 of file OsmParserThread.cc.
References startThread().
Referenced by OsmParser::parseOsmFile().
startThread
void OsmParserThread::startThread (const QString & filePath) signal
Referenced by OsmParserThread(), and start().
Friends And Related Symbol Documentation
OsmParserThreadTest
friend class OsmParserThreadTest friend
Definition at line 20 of file OsmParserThread.h.
The documentation for this class was generated from the following files:
src/Viewer3D/Providers/Osm/OsmParserThread.h
src/Viewer3D/Providers/Osm/OsmParserThread.cc