QGroundControl: QSerialPortPrivate Class Reference
QSerialPortPrivate Class Reference
#include <qserialport_p.h>
Public Member Functions
QSerialPortPrivate ()
bool open (QIODevice::OpenMode mode)
void close ()
bool flush ()
bool clear (QSerialPort::Directions directions)
QSerialPort::PinoutSignals pinoutSignals ()
bool setDataTerminalReady (bool set)
bool setRequestToSend (bool set)
bool setBaudRate ()
bool setBaudRate (qint32 baudRate, QSerialPort::Directions directions)
bool setDataBits (QSerialPort::DataBits dataBits)
bool setParity (QSerialPort::Parity parity)
bool setStopBits (QSerialPort::StopBits stopBits)
bool setFlowControl (QSerialPort::FlowControl flowControl)
bool setBreakEnabled (bool set)
void setError (const QSerialPortErrorInfo &errorInfo)
void setBindableError (QSerialPort::SerialPortError error_)
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, QSerialPort::SerialPortError, error, &QSerialPortPrivate::setBindableError, QSerialPort::NoError) bool setBindableDataBits(QSerialPort
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, QSerialPort::DataBits, dataBits, &QSerialPortPrivate::setBindableDataBits, QSerialPort::Data8) bool setBindableParity(QSerialPort
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, QSerialPort::Parity, parity, &QSerialPortPrivate::setBindableParity, QSerialPort::NoParity) bool setBindableStopBits(QSerialPort
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, QSerialPort::StopBits, stopBits, &QSerialPortPrivate::setBindableStopBits, QSerialPort::OneStop) bool setBindableFlowControl(QSerialPort
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, QSerialPort::FlowControl, flowControl, &QSerialPortPrivate::setBindableFlowControl, QSerialPort::NoFlowControl) bool setBindableBreakEnabled(bool isBreakEnabled_)
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate, bool, isBreakEnabled, &QSerialPortPrivate::setBindableBreakEnabled, false) bool waitForReadyRead(int msec)
bool waitForBytesWritten (int msec)
bool startAsyncRead ()
qint64 writeData (const char *data, qint64 maxSize)
void newDataArrived (const char *bytes, int length)
void exceptionArrived (const QString &ex)
Static Public Member Functions
static QList< qint32 > standardBaudRates ()
Public Attributes
QString systemLocation
qint32 inputBaudRate = QSerialPort::Baud9600
qint32 outputBaudRate = QSerialPort::Baud9600
qint64 readBufferMaxSize = 0
int descriptor = -1
Detailed Description
Definition at line 56 of file qserialport_p.h.
Constructor & Destructor Documentation
QSerialPortPrivate()
QSerialPortPrivate::QSerialPortPrivate ()
Definition at line 51 of file qserialport.cpp.
References QSERIALPORT_BUFFERSIZE.
Member Function Documentation
clear()
bool QSerialPortPrivate::clear (QSerialPort::Directions directions)
Definition at line 379 of file qserialport_android.cpp.
References QSerialPort::Input, QSerialPort::Output, AndroidSerial::purgeBuffers(), setError(), and QSerialPort::UnknownError.
close()
void QSerialPortPrivate::close ()
Definition at line 66 of file qserialport_android.cpp.
References AndroidSerial::close(), descriptor, INVALID_DEVICE_ID, setError(), systemLocation, QSerialPort::UnknownError, and AndroidSerial::unregisterPointer().
exceptionArrived()
void QSerialPortPrivate::exceptionArrived (const QString & ex)
Definition at line 85 of file qserialport_android.cpp.
References setError(), and QSerialPort::UnknownError.
flush()
bool QSerialPortPrivate::flush ()
Definition at line 368 of file qserialport_android.cpp.
References setError(), and QSerialPort::UnknownError.
newDataArrived()
void QSerialPortPrivate::newDataArrived (const char * bytes, int length)
Definition at line 182 of file qserialport_android.cpp.
References readBufferMaxSize.
Referenced by AndroidSerial::jniDeviceNewData().
open()
QT_BEGIN_NAMESPACE bool QSerialPortPrivate::open (QIODevice::OpenMode mode)
Definition at line 14 of file qserialport_android.cpp.
References QSerialPort::AllDirections, QSerialPort::DeviceNotFoundError, AndroidSerial::getDeviceHandle(), INVALID_DEVICE_ID, AndroidSerial::open(), QSerialPort::OpenError, AndroidSerial::registerPointer(), and AndroidSerial::unregisterPointer().
pinoutSignals()
QSerialPort::PinoutSignals QSerialPortPrivate::pinoutSignals ()
Definition at line 393 of file qserialport_android.cpp.
References AndroidSerial::getControlLines().
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [1/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , bool , isBreakEnabled , &QSerialPortPrivate::setBindableBreakEnabled , false)
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [2/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , QSerialPort::DataBits , dataBits , &QSerialPortPrivate::setBindableDataBits , QSerialPort::Data8) inline
Definition at line 96 of file qserialport_p.h.
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [3/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , QSerialPort::FlowControl , flowControl , &QSerialPortPrivate::setBindableFlowControl , QSerialPort::NoFlowControl) inline
Definition at line 117 of file qserialport_p.h.
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [4/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , QSerialPort::Parity , parity , &QSerialPortPrivate::setBindableParity , QSerialPort::NoParity) inline
Definition at line 103 of file qserialport_p.h.
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [5/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , QSerialPort::SerialPortError , error , &QSerialPortPrivate::setBindableError , QSerialPort::NoError) inline
Definition at line 89 of file qserialport_p.h.
Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS() [6/6]
QSerialPortPrivate::Q_OBJECT_COMPAT_PROPERTY_WITH_ARGS (QSerialPortPrivate , QSerialPort::StopBits , stopBits , &QSerialPortPrivate::setBindableStopBits , QSerialPort::OneStop) inline
Definition at line 110 of file qserialport_p.h.
setBaudRate() [1/2]
bool QSerialPortPrivate::setBaudRate ()
Definition at line 434 of file qserialport_android.cpp.
References QSerialPort::AllDirections, inputBaudRate, and setBaudRate().
Referenced by setBaudRate().
setBaudRate() [2/2]
bool QSerialPortPrivate::setBaudRate (qint32 baudRate, QSerialPort::Directions directions)
Definition at line 439 of file qserialport_android.cpp.
References QSerialPort::AllDirections, inputBaudRate, outputBaudRate, setError(), QSerialPort::UnknownError, and QSerialPort::UnsupportedOperationError.
setBindableError()
void QSerialPortPrivate::setBindableError (QSerialPort::SerialPortError error_) inline
Definition at line 85 of file qserialport_p.h.
References setError().
setBreakEnabled()
bool QSerialPortPrivate::setBreakEnabled (bool set)
Definition at line 576 of file qserialport_android.cpp.
References AndroidSerial::setBreak(), setError(), and QSerialPort::UnknownError.
setDataBits()
bool QSerialPortPrivate::setDataBits (QSerialPort::DataBits dataBits)
Definition at line 483 of file qserialport_android.cpp.
References inputBaudRate, setError(), and QSerialPort::UnknownError.
setDataTerminalReady()
bool QSerialPortPrivate::setDataTerminalReady (bool set)
Definition at line 398 of file qserialport_android.cpp.
References AndroidSerial::setDataTerminalReady(), setError(), and QSerialPort::UnknownError.
setError()
void QSerialPortPrivate::setError (const QSerialPortErrorInfo & errorInfo)
Definition at line 57 of file qserialport.cpp.
References error, QSerialPortErrorInfo::errorCode, and QSerialPortErrorInfo::errorString.
Referenced by clear(), close(), exceptionArrived(), flush(), setBaudRate(), setBindableError(), setBreakEnabled(), setDataBits(), setDataTerminalReady(), setFlowControl(), setParity(), setRequestToSend(), setStopBits(), startAsyncRead(), waitForBytesWritten(), and writeData().
setFlowControl()
bool QSerialPortPrivate::setFlowControl (QSerialPort::FlowControl flowControl)
Definition at line 565 of file qserialport_android.cpp.
References setError(), AndroidSerial::setFlowControl(), and QSerialPort::UnknownError.
setParity()
bool QSerialPortPrivate::setParity (QSerialPort::Parity parity)
Definition at line 513 of file qserialport_android.cpp.
References inputBaudRate, setError(), and QSerialPort::UnknownError.
setRequestToSend()
bool QSerialPortPrivate::setRequestToSend (bool set)
Definition at line 409 of file qserialport_android.cpp.
References setError(), AndroidSerial::setRequestToSend(), and QSerialPort::UnknownError.
setStopBits()
bool QSerialPortPrivate::setStopBits (QSerialPort::StopBits stopBits)
Definition at line 539 of file qserialport_android.cpp.
References inputBaudRate, setError(), and QSerialPort::UnknownError.
standardBaudRates()
QList< qint32 > QSerialPortPrivate::standardBaudRates () static
Definition at line 592 of file qserialport_android.cpp.
References kStandardBaudRates.
Referenced by QSerialPortInfo::standardBaudRates().
startAsyncRead()
bool QSerialPortPrivate::startAsyncRead ()
Definition at line 91 of file qserialport_android.cpp.
References AndroidSerial::readThreadRunning(), setError(), AndroidSerial::startReadThread(), and QSerialPort::UnknownError.
waitForBytesWritten()
bool QSerialPortPrivate::waitForBytesWritten (int msec)
Definition at line 302 of file qserialport_android.cpp.
References setError(), and QSerialPort::TimeoutError.
writeData()
qint64 QSerialPortPrivate::writeData (const char * data, qint64 maxSize)
Definition at line 357 of file qserialport_android.cpp.
References setError(), and QSerialPort::WriteError.
Member Data Documentation
descriptor
int QSerialPortPrivate::descriptor = -1
Definition at line 143 of file qserialport_p.h.
Referenced by close().
inputBaudRate
qint32 QSerialPortPrivate::inputBaudRate = QSerialPort::Baud9600
Definition at line 140 of file qserialport_p.h.
Referenced by setBaudRate(), setBaudRate(), setDataBits(), setParity(), and setStopBits().
outputBaudRate
qint32 QSerialPortPrivate::outputBaudRate = QSerialPort::Baud9600
Definition at line 141 of file qserialport_p.h.
Referenced by setBaudRate().
readBufferMaxSize
qint64 QSerialPortPrivate::readBufferMaxSize = 0
Definition at line 142 of file qserialport_p.h.
Referenced by newDataArrived().
systemLocation
QString QSerialPortPrivate::systemLocation
Definition at line 139 of file qserialport_p.h.
Referenced by close().
The documentation for this class was generated from the following files:
src/Android/qtandroidserialport/qserialport_p.h
src/Android/qtandroidserialport/qserialport.cpp
src/Android/qtandroidserialport/qserialport_android.cpp