QGroundControl: QGCStateMachine Class Reference
QGCStateMachine Class Reference
QGroundControl specific state machine with enhanced error handling.
#include <QGCStateMachine.h>
Public Slots
void start ()
Start the state machine with debug logging.
Signals
void error ()
void progressUpdate (float progress)
void machineEvent (const QString &eventName)
void currentStateNameChanged ()
Emitted when the current state changes (for QML binding)
void runningChanged ()
Emitted when the running state changes (for QML binding)
void stateHistoryChanged ()
Emitted when the state history changes (for QML binding)
Protected Member Functions
virtual void onEnter ()
Override to perform actions when machine starts.
virtual void onLeave ()
Override to perform actions when machine stops.
void onEntry (QEvent *event) override
void onExit (QEvent *event) override
bool event (QEvent *event) override
Detailed Description
QGroundControl specific state machine with enhanced error handling.
Definition at line 60 of file QGCStateMachine.h.
Member Function Documentation
currentStateNameChanged
void QGCStateMachine::currentStateNameChanged () signal
Emitted when the current state changes (for QML binding)
error
void QGCStateMachine::error () signal
Referenced by SubMachineState::onEntry().
event()
bool QGCStateMachine::event (QEvent * event) override protected
Definition at line 959 of file QGCStateMachine.cc.
References event().
Referenced by event(), onEntry(), and onExit().
machineEvent
void QGCStateMachine::machineEvent (const QString & eventName) signal
Emitted when a named event is posted to the machine Used by EventQueuedState to detect events
Parameters
eventName Name of the posted event
Referenced by EventQueuedState::connectWaitSignal().
onEnter()
virtual void QGCStateMachine::onEnter () inline protected virtual
Override to perform actions when machine starts.
Definition at line 694 of file QGCStateMachine.h.
Referenced by onEntry().
onEntry()
void QGCStateMachine::onEntry (QEvent * event) override protected
Definition at line 937 of file QGCStateMachine.cc.
References event(), and onEnter().
onExit()
void QGCStateMachine::onExit (QEvent * event) override protected
Definition at line 948 of file QGCStateMachine.cc.
References event(), and onLeave().
onLeave()
virtual void QGCStateMachine::onLeave () inline protected virtual
Override to perform actions when machine stops.
Definition at line 697 of file QGCStateMachine.h.
Referenced by onExit().
progressUpdate
void QGCStateMachine::progressUpdate (float progress) signal
Emitted when progress changes (if progress tracking is enabled)
Parameters
progress Overall progress from 0.0 to 1.0
runningChanged
void QGCStateMachine::runningChanged () signal
Emitted when the running state changes (for QML binding)
start
void QGCStateMachine::start () slot
Start the state machine with debug logging.
Definition at line 63 of file QGCStateMachine.cc.
Referenced by SubMachineState::onEntry(), RequestMetaDataTypeStateMachine::request(), ComponentInformationManager::requestAllComponentInformation(), and InitialConnectStateMachine::start().
stateHistoryChanged
void QGCStateMachine::stateHistoryChanged () signal
Emitted when the state history changes (for QML binding)
The documentation for this class was generated from the following files:
src/Utilities/StateMachine/QGCStateMachine.h
src/Utilities/StateMachine/QGCStateMachine.cc