QGroundControl: Gimbal Class Reference
Gimbal Class Reference
#include <Gimbal.h>
Signals
void pitchRateChanged ()
void yawRateChanged ()
void yawLockChanged ()
void retractedChanged ()
void gimbalHaveControlChanged ()
void gimbalOthersHaveControlChanged ()
void capabilityFlagsChanged ()
Signals inherited from FactGroup
void factNamesChanged ()
void factGroupNamesChanged ()
void telemetryAvailableChanged (bool telemetryAvailable)
Public Member Functions
Gimbal (GimbalController *parent)
Gimbal (const Gimbal &other)
const Gimbal & operator= (const Gimbal &other)
~Gimbal ()
Fact * absoluteRoll ()
Fact * absolutePitch ()
Fact * bodyYaw ()
Fact * absoluteYaw ()
Fact * deviceId ()
Fact * managerCompid ()
float pitchRate () const
float yawRate () const
bool yawLock () const
bool retracted () const
bool gimbalHaveControl () const
bool gimbalOthersHaveControl () const
void setAbsoluteRoll (float absRoll)
void setAbsolutePitch (float absPitch)
void setBodyYaw (float yaw)
void setAbsoluteYaw (float absYaw)
void setDeviceId (uint id)
void setManagerCompid (uint id)
void setPitchRate (float pitchRate)
void setYawRate (float yawRate)
void setYawLock (bool yawLock)
void setRetracted (bool retracted)
void setGimbalHaveControl (bool set)
void setGimbalOthersHaveControl (bool set)
void setCapabilityFlags (uint32_t flags)
bool supportsRetract () const
bool supportsYawLock () const
Additional Inherited Members
Protected Slots inherited from FactGroup
virtual void _updateAllValues ()
Protected Member Functions inherited from FactGroup
void _addFact (Fact *fact, const QString &name)
void _addFact (Fact *fact)
void _addFactGroup (FactGroup *factGroup, const QString &name)
void _addFactGroup (FactGroup *factGroup)
void _loadFromJsonArray (const QJsonArray &jsonArray)
void _setTelemetryAvailable (bool telemetryAvailable)
Protected Attributes inherited from FactGroup
const int _updateRateMSecs = 0
Update rate for Fact::valueChanged signals, 0: immediate update.
QMap< QString, Fact * > _nameToFactMap
QMap< QString, FactGroup * > _nameToFactGroupMap
QMap< QString, FactMetaData * > _nameToFactMetaDataMap
QStringList _factNames
Detailed Description
Definition at line 8 of file Gimbal.h.
Constructor & Destructor Documentation
Gimbal() [1/2]
Gimbal::Gimbal (GimbalController * parent)
Definition at line 7 of file Gimbal.cc.
Gimbal() [2/2]
Gimbal::Gimbal (const Gimbal & other)
Definition at line 15 of file Gimbal.cc.
~Gimbal()
Gimbal::~Gimbal ()
Definition at line 22 of file Gimbal.cc.
Member Function Documentation
absolutePitch()
Fact * Gimbal::absolutePitch () inline
Definition at line 35 of file Gimbal.h.
Referenced by setAbsolutePitch().
absoluteRoll()
Fact * Gimbal::absoluteRoll () inline
Definition at line 34 of file Gimbal.h.
Referenced by setAbsoluteRoll().
absoluteYaw()
Fact * Gimbal::absoluteYaw () inline
Definition at line 37 of file Gimbal.h.
Referenced by setAbsoluteYaw().
bodyYaw()
Fact * Gimbal::bodyYaw () inline
Definition at line 36 of file Gimbal.h.
Referenced by setBodyYaw().
capabilityFlagsChanged
void Gimbal::capabilityFlagsChanged () signal
Referenced by setCapabilityFlags().
deviceId()
Fact * Gimbal::deviceId () inline
Definition at line 38 of file Gimbal.h.
Referenced by setDeviceId().
gimbalHaveControl()
bool Gimbal::gimbalHaveControl () const inline
Definition at line 45 of file Gimbal.h.
gimbalHaveControlChanged
void Gimbal::gimbalHaveControlChanged () signal
Referenced by setGimbalHaveControl().
gimbalOthersHaveControl()
bool Gimbal::gimbalOthersHaveControl () const inline
Definition at line 46 of file Gimbal.h.
gimbalOthersHaveControlChanged
void Gimbal::gimbalOthersHaveControlChanged () signal
Referenced by setGimbalOthersHaveControl().
managerCompid()
Fact * Gimbal::managerCompid () inline
Definition at line 39 of file Gimbal.h.
Referenced by setManagerCompid().
operator=()
const Gimbal & Gimbal::operator= (const Gimbal & other)
Definition at line 27 of file Gimbal.cc.
pitchRate()
float Gimbal::pitchRate () const inline
Definition at line 41 of file Gimbal.h.
Referenced by setPitchRate().
pitchRateChanged
void Gimbal::pitchRateChanged () signal
Referenced by setPitchRate().
retracted()
bool Gimbal::retracted () const inline
Definition at line 44 of file Gimbal.h.
Referenced by setRetracted().
retractedChanged
void Gimbal::retractedChanged () signal
Referenced by setRetracted().
setAbsolutePitch()
void Gimbal::setAbsolutePitch (float absPitch) inline
Definition at line 49 of file Gimbal.h.
References absolutePitch().
setAbsoluteRoll()
void Gimbal::setAbsoluteRoll (float absRoll) inline
Definition at line 48 of file Gimbal.h.
References absoluteRoll().
setAbsoluteYaw()
void Gimbal::setAbsoluteYaw (float absYaw) inline
Definition at line 51 of file Gimbal.h.
References absoluteYaw().
setBodyYaw()
void Gimbal::setBodyYaw (float yaw) inline
Definition at line 50 of file Gimbal.h.
References bodyYaw().
setCapabilityFlags()
void Gimbal::setCapabilityFlags (uint32_t flags)
Definition at line 69 of file Gimbal.cc.
References capabilityFlagsChanged().
setDeviceId()
void Gimbal::setDeviceId (uint id) inline
Definition at line 52 of file Gimbal.h.
References deviceId().
setGimbalHaveControl()
void Gimbal::setGimbalHaveControl (bool set) inline
Definition at line 59 of file Gimbal.h.
References gimbalHaveControlChanged().
setGimbalOthersHaveControl()
void Gimbal::setGimbalOthersHaveControl (bool set) inline
Definition at line 60 of file Gimbal.h.
References gimbalOthersHaveControlChanged().
setManagerCompid()
void Gimbal::setManagerCompid (uint id) inline
Definition at line 53 of file Gimbal.h.
References managerCompid().
setPitchRate()
void Gimbal::setPitchRate (float pitchRate) inline
Definition at line 55 of file Gimbal.h.
References pitchRate(), and pitchRateChanged().
Referenced by GimbalController::gimbalPitchStart(), and GimbalController::gimbalPitchStop().
setRetracted()
void Gimbal::setRetracted (bool retracted) inline
Definition at line 58 of file Gimbal.h.
References retracted(), and retractedChanged().
setYawLock()
void Gimbal::setYawLock (bool yawLock) inline
Definition at line 57 of file Gimbal.h.
References yawLock(), and yawLockChanged().
setYawRate()
void Gimbal::setYawRate (float yawRate) inline
Definition at line 56 of file Gimbal.h.
References yawRate(), and yawRateChanged().
Referenced by GimbalController::gimbalYawStart(), and GimbalController::gimbalYawStop().
supportsRetract()
bool Gimbal::supportsRetract () const inline
Definition at line 63 of file Gimbal.h.
supportsYawLock()
bool Gimbal::supportsYawLock () const inline
Definition at line 64 of file Gimbal.h.
yawLock()
bool Gimbal::yawLock () const inline
Definition at line 43 of file Gimbal.h.
Referenced by setYawLock().
yawLockChanged
void Gimbal::yawLockChanged () signal
Referenced by setYawLock().
yawRate()
float Gimbal::yawRate () const inline
Definition at line 42 of file Gimbal.h.
Referenced by setYawRate().
yawRateChanged
void Gimbal::yawRateChanged () signal
Referenced by setYawRate().
The documentation for this class was generated from the following files:
src/Gimbal/Gimbal.h
src/Gimbal/Gimbal.cc