QGroundControl: QGCQGeoCoordinate Class Reference
QGCQGeoCoordinate Class Reference
This is a QGeoCoordinate within a QObject such that it can be used on a QmlObjectListModel.
#include <QGCQGeoCoordinate.h>
Signals
void coordinateChanged (QGeoCoordinate coordinate)
void dirtyChanged (bool dirty)
Public Member Functions
QGCQGeoCoordinate (const QGeoCoordinate &coord, QObject *parent=nullptr)
QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY coordinateChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) QGeoCoordinate coordinate(void) const
void setCoordinate (const QGeoCoordinate &coordinate)
bool dirty (void) const
void setDirty (bool dirty)
Detailed Description
This is a QGeoCoordinate within a QObject such that it can be used on a QmlObjectListModel.
Definition at line 7 of file QGCQGeoCoordinate.h.
Constructor & Destructor Documentation
QGCQGeoCoordinate()
QGCQGeoCoordinate::QGCQGeoCoordinate (const QGeoCoordinate & coord, QObject * parent = nullptr)
Definition at line 5 of file QGCQGeoCoordinate.cc.
Member Function Documentation
coordinateChanged() [1/2]
QGeoCoordinate coordinate READ coordinate WRITE setCoordinate NOTIFY QGCQGeoCoordinate::coordinateChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) const inline
Definition at line 14 of file QGCQGeoCoordinate.h.
Referenced by setCoordinate().
coordinateChanged [2/2]
void QGCQGeoCoordinate::coordinateChanged (QGeoCoordinate coordinate) signal
dirty()
bool QGCQGeoCoordinate::dirty (void) const inline
Definition at line 19 of file QGCQGeoCoordinate.h.
Referenced by setDirty().
dirtyChanged
void QGCQGeoCoordinate::dirtyChanged (bool dirty) signal
Referenced by setDirty().
setCoordinate()
void QGCQGeoCoordinate::setCoordinate (const QGeoCoordinate & coordinate)
Definition at line 13 of file QGCQGeoCoordinate.cc.
References coordinateChanged(), and setDirty().
setDirty()
void QGCQGeoCoordinate::setDirty (bool dirty)
Definition at line 22 of file QGCQGeoCoordinate.cc.
References dirty(), and dirtyChanged().
Referenced by setCoordinate().
The documentation for this class was generated from the following files:
src/QmlControls/QGCQGeoCoordinate.h
src/QmlControls/QGCQGeoCoordinate.cc