QGroundControl: Mixer::ChannelConfigInstance Class Reference
Mixer::ChannelConfigInstance Class Reference
#include <Mixer.h>
Signals
void visibleChanged ()
void enabledChanged ()
Public Member Functions
ChannelConfigInstance (QObject *parent, Fact *fact, ChannelConfig &config)
ChannelConfig *config READ channelConfig CONSTANT (Fact *fact READ fact CONSTANT) 1(bool visible READ visible NOTIFY visibleChanged) 1(bool enabled READ enabled NOTIFY enabledChanged) ChannelConfig *channelConfig() const
Fact * fact ()
bool visible () const
bool enabled () const
bool visibleRule () const
bool enabledRule () const
void setVisibleRule (bool visible)
void setEnabledRule (bool enabled)
void setVisibleAxis (bool visible)
int ruleApplyIdentifierIdx () const
void setRuleApplyIdentifierIdx (int idx)
virtual void allInstancesInitialized (QmlObjectListModel *configInstances)
Protected Attributes
Fact * _fact {nullptr}
Detailed Description
Per-channel instance for a ChannelConfig
Definition at line 187 of file Mixer.h.
Constructor & Destructor Documentation
ChannelConfigInstance()
Mixer::ChannelConfigInstance::ChannelConfigInstance (QObject * parent, Fact * fact, ChannelConfig & config) inline
Definition at line 191 of file Mixer.h.
Member Function Documentation
allInstancesInitialized()
virtual void Mixer::ChannelConfigInstance::allInstancesInitialized (QmlObjectListModel * configInstances) inline virtual
Reimplemented in Mixer::ChannelConfigInstanceVirtualAxis.
Definition at line 217 of file Mixer.h.
Referenced by Mixer::MixerChannel::MixerChannel().
CONSTANT()
ChannelConfig *config READ channelConfig Mixer::ChannelConfigInstance::CONSTANT (Fact *fact READ fact CONSTANT) const inline
Definition at line 194 of file Mixer.h.
enabled()
bool Mixer::ChannelConfigInstance::enabled () const inline
Definition at line 204 of file Mixer.h.
Referenced by setEnabledRule().
enabledChanged
void Mixer::ChannelConfigInstance::enabledChanged () signal
Referenced by Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), and setEnabledRule().
enabledRule()
bool Mixer::ChannelConfigInstance::enabledRule () const inline
Definition at line 207 of file Mixer.h.
fact()
Fact * Mixer::ChannelConfigInstance::fact () inline
Definition at line 201 of file Mixer.h.
References _fact.
Referenced by Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), Mixer::MixerChannel::applyRule(), Mixer::MixerChannel::getFact(), and Mixer::MixerChannel::getGeometry().
ruleApplyIdentifierIdx()
int Mixer::ChannelConfigInstance::ruleApplyIdentifierIdx () const inline
Definition at line 214 of file Mixer.h.
Referenced by Mixer::MixerChannel::applyRule().
setEnabledRule()
void Mixer::ChannelConfigInstance::setEnabledRule (bool enabled) inline
Definition at line 210 of file Mixer.h.
References enabled(), and enabledChanged().
Referenced by Mixer::MixerChannel::applyRule().
setRuleApplyIdentifierIdx()
void Mixer::ChannelConfigInstance::setRuleApplyIdentifierIdx (int idx) inline
Definition at line 215 of file Mixer.h.
setVisibleAxis()
void Mixer::ChannelConfigInstance::setVisibleAxis (bool visible) inline
Definition at line 212 of file Mixer.h.
References visible(), and visibleChanged().
setVisibleRule()
void Mixer::ChannelConfigInstance::setVisibleRule (bool visible) inline
Definition at line 209 of file Mixer.h.
References visible(), and visibleChanged().
Referenced by Mixer::MixerChannel::applyRule().
visible()
bool Mixer::ChannelConfigInstance::visible () const inline
Definition at line 203 of file Mixer.h.
Referenced by setVisibleAxis(), and setVisibleRule().
visibleChanged
void Mixer::ChannelConfigInstance::visibleChanged () signal
Referenced by Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), Mixer::ChannelConfig::channelInstanceCreated(), setVisibleAxis(), and setVisibleRule().
visibleRule()
bool Mixer::ChannelConfigInstance::visibleRule () const inline
Definition at line 206 of file Mixer.h.
Member Data Documentation
_fact
Fact* Mixer::ChannelConfigInstance::_fact {nullptr} protected
Definition at line 224 of file Mixer.h.
Referenced by Mixer::ChannelConfigInstanceVirtualAxis::allInstancesInitialized(), and fact().
The documentation for this class was generated from the following file:
src/Vehicle/Actuators/Mixer.h