QGroundControl: QGCFenceCircle Class Reference
QGCFenceCircle Class Reference
The QGCFenceCircle class provides a cicle used by GeoFence support.
#include <QGCFenceCircle.h>
Signals
void inclusionChanged (bool inclusion)
Signals inherited from QGCMapCircle
void dirtyChanged (bool dirty)
void centerChanged (QGeoCoordinate center)
void interactiveChanged (bool interactive)
void showRotationChanged (bool showRotation)
void clockwiseRotationChanged (bool clockwiseRotation)
Public Member Functions
QGCFenceCircle (QObject *parent=nullptr)
QGCFenceCircle (const QGeoCoordinate &center, double radius, bool inclusion, QObject *parent=nullptr)
QGCFenceCircle (const QGCFenceCircle &other, QObject *parent=nullptr)
const QGCFenceCircle & operator= (const QGCFenceCircle &other)
bool inclusion READ inclusion WRITE setInclusion NOTIFY inclusionChanged void saveToJson (QJsonObject &json)
bool loadFromJson (const QJsonObject &json, QString &errorString)
bool inclusion (void) const
void setInclusion (bool inclusion)
Public Member Functions inherited from QGCMapCircle
QGCMapCircle (QObject *parent=nullptr)
QGCMapCircle (const QGeoCoordinate &center, double radius, QObject *parent=nullptr)
QGCMapCircle (const QGeoCoordinate &center, double radius, bool showRotation, bool clockwiseRotation, QObject *parent=nullptr)
QGCMapCircle (const QGCMapCircle &other, QObject *parent=nullptr)
const QGCMapCircle & operator= (const QGCMapCircle &other)
bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged (QGeoCoordinate center READ center WRITE setCenter NOTIFY centerChanged) 1(Fact *radius READ radius CONSTANT) 1(bool interactive READ interactive WRITE setInteractive NOTIFY interactiveChanged) 1(bool showRotation READ showRotation WRITE setShowRotation NOTIFY showRotationChanged) 1(bool clockwiseRotation READ clockwiseRotation WRITE setClockwiseRotation NOTIFY clockwiseRotationChanged) void saveToJson(QJsonObject &json)
bool loadFromJson (const QJsonObject &json, QString &errorString)
bool dirty (void) const
QGeoCoordinate center (void) const
Fact * radius (void)
bool interactive (void) const
bool showRotation (void) const
bool clockwiseRotation (void) const
void setDirty (bool dirty)
void setCenter (QGeoCoordinate newCenter)
void setInteractive (bool interactive)
void setShowRotation (bool showRotation)
void setClockwiseRotation (bool clockwiseRotation)
Additional Inherited Members
Static Public Attributes inherited from QGCMapCircle
static constexpr const char * jsonCircleKey = "circle"
Detailed Description
The QGCFenceCircle class provides a cicle used by GeoFence support.
Definition at line 6 of file QGCFenceCircle.h.
Constructor & Destructor Documentation
QGCFenceCircle() [1/3]
QGCFenceCircle::QGCFenceCircle (QObject * parent = nullptr)
Definition at line 4 of file QGCFenceCircle.cc.
QGCFenceCircle() [2/3]
QGCFenceCircle::QGCFenceCircle (const QGeoCoordinate & center, double radius, bool inclusion, QObject * parent = nullptr)
Definition at line 11 of file QGCFenceCircle.cc.
QGCFenceCircle() [3/3]
QGCFenceCircle::QGCFenceCircle (const QGCFenceCircle & other, QObject * parent = nullptr)
Definition at line 18 of file QGCFenceCircle.cc.
Member Function Documentation
inclusion()
bool QGCFenceCircle::inclusion (void) const inline
Definition at line 31 of file QGCFenceCircle.h.
Referenced by GeoFenceManager::sendToVehicle(), and setInclusion().
inclusionChanged
void QGCFenceCircle::inclusionChanged (bool inclusion) signal
Referenced by setInclusion().
loadFromJson()
bool QGCFenceCircle::loadFromJson (const QJsonObject & json, QString & errorString)
Load a QGCFenceCircle from json
Parameters
json Json object to load from
errorString Error string if return is false
Returns
true: success, false: failure (errorString set)
Definition at line 51 of file QGCFenceCircle.cc.
References errorString, JsonHelper::jsonVersionKey, QGCMapCircle::loadFromJson(), setInclusion(), and JsonHelper::validateKeys().
Referenced by GeoFenceController::load().
operator=()
const QGCFenceCircle & QGCFenceCircle::operator= (const QGCFenceCircle & other)
Definition at line 30 of file QGCFenceCircle.cc.
References QGCMapCircle::operator=(), and setInclusion().
saveToJson()
void QGCFenceCircle::saveToJson (QJsonObject & json)
Saves the QGCFenceCircle to the json object.
Parameters
json Json object to save to
Definition at line 44 of file QGCFenceCircle.cc.
References JsonHelper::jsonVersionKey.
Referenced by GeoFenceController::save().
setInclusion()
void QGCFenceCircle::setInclusion (bool inclusion)
Definition at line 77 of file QGCFenceCircle.cc.
References inclusion(), and inclusionChanged().
Referenced by loadFromJson(), and operator=().
The documentation for this class was generated from the following files:
src/QmlControls/QGCFenceCircle.h
src/QmlControls/QGCFenceCircle.cc