QGroundControl: ObjectListModelBase Class Reference
ObjectListModelBase Class Reference abstract
Base class for custom object list models: QmlObjectListModel, SparselObjectListModel.
#include <ObjectListModelBase.h>
Signals
void countChanged (int count)
void dirtyChanged (bool dirtyChanged)
Public Member Functions
ObjectListModelBase (QObject *parent=nullptr)
~ObjectListModelBase ()
int count READ count NOTIFY countChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) bool dirty() const
void beginResetModel ()
Supported nesting of calls such that only outermost call has effect.
void endResetModel ()
Supported nesting of calls such that only outermost call has effect.
virtual int count () const =0
virtual bool isEmpty () const
virtual void setDirty (bool dirty)=0
virtual void clear ()=0
virtual void clearAndDeleteContents ()=0
Clears the list and calls deleteLater on each entry.
virtual QObject * removeOne (const QObject *object)=0
virtual bool contains (const QObject *object)=0
Protected Slots
void _childDirtyChanged (bool dirty)
Protected Member Functions
int rowCount (const QModelIndex &parent=QModelIndex()) const override=0
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override=0
bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex()) override=0
bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex()) override=0
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override=0
void _signalCountChangedIfNotNested ()
QHash< int, QByteArray > roleNames (void) const override
Protected Attributes
bool _dirty
bool _skipDirtyFirstItem
uint _resetModelNestingCount = 0
Static Protected Attributes
static constexpr int ObjectRole = Qt::UserRole
static constexpr int TextRole = Qt::UserRole + 1
Detailed Description
Base class for custom object list models: QmlObjectListModel, SparselObjectListModel.
Definition at line 20 of file ObjectListModelBase.h.
Constructor & Destructor Documentation
ObjectListModelBase()
ObjectListModelBase::ObjectListModelBase (QObject * parent = nullptr)
Definition at line 18 of file ObjectListModelBase.cc.
~ObjectListModelBase()
ObjectListModelBase::~ObjectListModelBase ()
Definition at line 26 of file ObjectListModelBase.cc.
References _resetModelNestingCount.
Member Function Documentation
_childDirtyChanged
void ObjectListModelBase::_childDirtyChanged (bool dirty) protected slot
Definition at line 43 of file ObjectListModelBase.cc.
References _dirty, and dirtyChanged().
_signalCountChangedIfNotNested()
void ObjectListModelBase::_signalCountChangedIfNotNested () protected
Definition at line 76 of file ObjectListModelBase.cc.
References _resetModelNestingCount, count(), and countChanged().
Referenced by QmlObjectListModel::insertRows(), and QmlObjectListModel::removeRows().
beginResetModel()
void ObjectListModelBase::beginResetModel ()
Supported nesting of calls such that only outermost call has effect.
Definition at line 51 of file ObjectListModelBase.cc.
References _resetModelNestingCount.
Referenced by QGCMapPolygon::beginReset(), QGCMapPolyline::beginReset(), QmlObjectListModel::clear(), and QmlObjectListModel::swapObjectList().
clear()
virtual void ObjectListModelBase::clear () pure virtual
Implemented in QmlObjectListModel.
clearAndDeleteContents()
virtual void ObjectListModelBase::clearAndDeleteContents () pure virtual
Clears the list and calls deleteLater on each entry.
Implemented in QmlObjectListModel.
contains()
virtual bool ObjectListModelBase::contains (const QObject * object) pure virtual
Implemented in QmlObjectListModel.
count()
virtual int ObjectListModelBase::count () const pure virtual
Implemented in QmlObjectListModel.
Referenced by _signalCountChangedIfNotNested(), and endResetModel().
countChanged() [1/2]
int count READ count NOTIFY ObjectListModelBase::countChanged (bool dirty READ dirty WRITE setDirty NOTIFY dirtyChanged) const inline
Returns true if any of the items in the list are dirty. Requires each object to have a dirty property and dirtyChanged signal.
Definition at line 28 of file ObjectListModelBase.h.
Referenced by _signalCountChangedIfNotNested(), endResetModel(), GeoFenceController::GeoFenceController(), and RallyPointController::RallyPointController().
countChanged [2/2]
void ObjectListModelBase::countChanged (int count) signal
data()
QVariant ObjectListModelBase::data (const QModelIndex & index, int role = Qt::DisplayRole) const override protected pure virtual
Implemented in QmlObjectListModel.
dirtyChanged
void ObjectListModelBase::dirtyChanged (bool dirtyChanged) signal
Referenced by _childDirtyChanged(), GeoFenceController::GeoFenceController(), and QmlObjectListModel::setDirty().
endResetModel()
void ObjectListModelBase::endResetModel ()
Supported nesting of calls such that only outermost call has effect.
Definition at line 61 of file ObjectListModelBase.cc.
References _resetModelNestingCount, count(), and countChanged().
Referenced by QmlObjectListModel::clear(), QGCMapPolygon::endReset(), QGCMapPolyline::endReset(), and QmlObjectListModel::swapObjectList().
insertRows()
bool ObjectListModelBase::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) override protected pure virtual
Implemented in QmlObjectListModel.
isEmpty()
virtual bool ObjectListModelBase::isEmpty () const inline virtual
Reimplemented in QmlObjectListModel.
Definition at line 39 of file ObjectListModelBase.h.
removeOne()
virtual QObject * ObjectListModelBase::removeOne (const QObject * object) pure virtual
Implemented in QmlObjectListModel.
removeRows()
bool ObjectListModelBase::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) override protected pure virtual
Implemented in QmlObjectListModel.
roleNames()
QHash< int, QByteArray > ObjectListModelBase::roleNames (void) const override protected
Definition at line 33 of file ObjectListModelBase.cc.
References ObjectRole, and TextRole.
rowCount()
int ObjectListModelBase::rowCount (const QModelIndex & parent = QModelIndex()) const override protected pure virtual
Implemented in QmlObjectListModel.
setData()
bool ObjectListModelBase::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override protected pure virtual
Implemented in QmlObjectListModel.
setDirty()
virtual void ObjectListModelBase::setDirty (bool dirty) pure virtual
Implemented in QmlObjectListModel.
Member Data Documentation
_dirty
bool ObjectListModelBase::_dirty protected
Definition at line 64 of file ObjectListModelBase.h.
Referenced by _childDirtyChanged(), and QmlObjectListModel::setDirty().
_resetModelNestingCount
uint ObjectListModelBase::_resetModelNestingCount = 0 protected
Definition at line 66 of file ObjectListModelBase.h.
Referenced by _signalCountChangedIfNotNested(), beginResetModel(), endResetModel(), and ~ObjectListModelBase().
_skipDirtyFirstItem
bool ObjectListModelBase::_skipDirtyFirstItem protected
Definition at line 65 of file ObjectListModelBase.h.
Referenced by QmlObjectListModel::insert(), QmlObjectListModel::insert(), and QmlObjectListModel::removeAt().
ObjectRole
constexpr int ObjectListModelBase::ObjectRole = Qt::UserRole static constexpr protected
Definition at line 68 of file ObjectListModelBase.h.
Referenced by QmlObjectListModel::data(), roleNames(), and QmlObjectListModel::setData().
TextRole
constexpr int ObjectListModelBase::TextRole = Qt::UserRole + 1 static constexpr protected
Definition at line 69 of file ObjectListModelBase.h.
Referenced by QmlObjectListModel::data(), and roleNames().
The documentation for this class was generated from the following files:
src/QmlControls/ObjectListModelBase.h
src/QmlControls/ObjectListModelBase.cc