QGroundControl: InstrumentValueData Class Reference
InstrumentValueData Class Reference
#include <InstrumentValueData.h>
Public Types
enum RangeType { NoRangeInfo = 0 , ColorRange , OpacityRange , IconSelectRange }
Signals
void factChanged (Fact *fact)
void factNameChanged (const QString &factName)
void factGroupNameChanged (const QString &factGroup)
void textChanged (QString text)
void showUnitsChanged (bool showUnits)
void iconChanged (const QString &icon)
void factGroupNamesChanged (void)
void factValueNamesChanged (void)
void rangeTypeChanged (RangeType rangeType)
void rangeValuesChanged (const QVariantList &rangeValues)
void rangeColorsChanged (const QVariantList &rangeColors)
void rangeIconsChanged (const QVariantList &rangeIcons)
void rangeOpacitiesChanged (const QVariantList &rangeOpacities)
void currentColorChanged (const QColor &currentColor)
void currentOpacityChanged (double currentOpacity)
void currentIconChanged (const QString &currentIcon)
Public Member Functions
InstrumentValueData (FactValueGrid *factValueGrid, QObject *parent)
FactValueGrid *factValueGrid MEMBER _factValueGrid CONSTANT (QStringList factGroupNames READ factGroupNames NOTIFY factGroupNamesChanged) 1(QStringList factValueNames READ factValueNames NOTIFY factValueNamesChanged) 1(QString factGroupName READ factGroupName NOTIFY factGroupNameChanged) 1(QString factName READ factName NOTIFY factNameChanged) 1(Fact *fact READ fact NOTIFY factChanged) 1(QString text READ text WRITE setText NOTIFY textChanged) 1(QString icon READ icon WRITE setIcon NOTIFY iconChanged) 1(bool showUnits READ showUnits WRITE setShowUnits NOTIFY showUnitsChanged) 1(QStringList rangeTypeNames MEMBER _rangeTypeNames CONSTANT) 1(RangeType rangeType READ rangeType WRITE setRangeType NOTIFY rangeTypeChanged) 1(QVariantList rangeValues READ rangeValues WRITE setRangeValues NOTIFY rangeValuesChanged) 1(QVariantList rangeColors READ rangeColors WRITE setRangeColors NOTIFY rangeColorsChanged) 1(QVariantList rangeIcons READ rangeIcons WRITE setRangeIcons NOTIFY rangeIconsChanged) 1(QVariantList rangeOpacities READ rangeOpacities WRITE setRangeOpacities NOTIFY rangeOpacitiesChanged) 1(QColor currentColor MEMBER _currentColor NOTIFY currentColorChanged) 1(double currentOpacity MEMBER _currentOpacity NOTIFY currentOpacityChanged) 1(QString currentIcon MEMBER _currentIcon NOTIFY currentIconChanged) 1 void setFact(const QString &factGroupName
< If !isEmpty icon will be show instead of label
void clearFact (void)
bool isValidColor (const QColor &color)
QColor invalidColor (void)
void addRangeValue (void)
void removeRangeValue (int index)
QStringList factGroupNames (void) const
QStringList factValueNames (void) const
QString factGroupName (void) const
QString factName (void) const
Fact * fact (void) const
QString text (void) const
bool showUnits (void) const
QString icon (void) const
RangeType rangeType (void) const
QVariantList rangeValues (void) const
QVariantList rangeColors (void) const
QVariantList rangeIcons (void) const
QVariantList rangeOpacities (void) const
void setText (const QString &text)
void setShowUnits (bool showUnits)
void setIcon (const QString &icon)
void setRangeType (RangeType rangeType)
void setRangeValues (const QVariantList &rangeValues)
void setRangeColors (const QVariantList &rangeColors)
void setRangeIcons (const QVariantList &rangeIcons)
void setRangeOpacities (const QVariantList &rangeOpacities)
Public Attributes
FactValueGrid *factValueGrid MEMBER _factValueGrid const QString & factName
Static Public Attributes
static constexpr const char * vehicleFactGroupName = "Vehicle"
Detailed Description
Definition at line 12 of file InstrumentValueData.h.
Member Enumeration Documentation
RangeType
enum InstrumentValueData::RangeType
Enumerator
NoRangeInfo
ColorRange
OpacityRange
IconSelectRange
Definition at line 18 of file InstrumentValueData.h.
Constructor & Destructor Documentation
InstrumentValueData()
InstrumentValueData::InstrumentValueData (FactValueGrid * factValueGrid, QObject * parent) explicit
Definition at line 17 of file InstrumentValueData.cc.
References FactGroup::factGroupNamesChanged(), factGroupNamesChanged(), rangeColorsChanged(), rangeIconsChanged(), rangeOpacitiesChanged(), rangeTypeChanged(), and rangeValuesChanged().
Member Function Documentation
addRangeValue()
void InstrumentValueData::addRangeValue (void)
Definition at line 196 of file InstrumentValueData.cc.
References ColorRange, FactValueGrid::iconNames(), IconSelectRange, NoRangeInfo, OpacityRange, rangeColorsChanged(), rangeIconsChanged(), rangeOpacitiesChanged(), and rangeValuesChanged().
clearFact()
void InstrumentValueData::clearFact (void)
Definition at line 47 of file InstrumentValueData.cc.
References factChanged(), factGroupNameChanged(), factNameChanged(), factValueNamesChanged(), iconChanged(), showUnitsChanged(), and textChanged().
CONSTANT()
FactValueGrid *factValueGrid MEMBER _factValueGrid InstrumentValueData::CONSTANT (QStringList factGroupNames READ factGroupNames NOTIFY factGroupNamesChanged) const &
< If !isEmpty icon will be show instead of label
currentColorChanged
void InstrumentValueData::currentColorChanged (const QColor & currentColor) signal
currentIconChanged
void InstrumentValueData::currentIconChanged (const QString & currentIcon) signal
currentOpacityChanged
void InstrumentValueData::currentOpacityChanged (double currentOpacity) signal
fact()
Fact * InstrumentValueData::fact (void) const inline
Definition at line 58 of file InstrumentValueData.h.
Referenced by SubtitleWriter::startCapturingTelemetry().
factChanged
void InstrumentValueData::factChanged (Fact * fact) signal
Referenced by clearFact().
factGroupName()
QString InstrumentValueData::factGroupName (void) const inline
Definition at line 56 of file InstrumentValueData.h.
factGroupNameChanged
void InstrumentValueData::factGroupNameChanged (const QString & factGroup) signal
Referenced by clearFact().
factGroupNames()
QStringList InstrumentValueData::factGroupNames (void) const
Definition at line 325 of file InstrumentValueData.cc.
References vehicleFactGroupName.
factGroupNamesChanged
void InstrumentValueData::factGroupNamesChanged (void) signal
Referenced by InstrumentValueData().
factName()
QString InstrumentValueData::factName (void) const inline
Definition at line 57 of file InstrumentValueData.h.
factNameChanged
void InstrumentValueData::factNameChanged (const QString & factName) signal
Referenced by clearFact().
factValueNames()
QStringList InstrumentValueData::factValueNames (void) const
Definition at line 337 of file InstrumentValueData.cc.
References vehicleFactGroupName.
factValueNamesChanged
void InstrumentValueData::factValueNamesChanged (void) signal
Referenced by clearFact().
icon()
QString InstrumentValueData::icon (void) const inline
Definition at line 61 of file InstrumentValueData.h.
Referenced by setIcon().
iconChanged
void InstrumentValueData::iconChanged (const QString & icon) signal
Referenced by clearFact(), and setIcon().
invalidColor()
QColor InstrumentValueData::invalidColor (void) inline
Definition at line 50 of file InstrumentValueData.h.
isValidColor()
bool InstrumentValueData::isValidColor (const QColor & color) inline
Definition at line 49 of file InstrumentValueData.h.
rangeColors()
QVariantList InstrumentValueData::rangeColors (void) const inline
Definition at line 64 of file InstrumentValueData.h.
Referenced by setRangeColors().
rangeColorsChanged
void InstrumentValueData::rangeColorsChanged (const QVariantList & rangeColors) signal
Referenced by addRangeValue(), InstrumentValueData(), removeRangeValue(), and setRangeColors().
rangeIcons()
QVariantList InstrumentValueData::rangeIcons (void) const inline
Definition at line 65 of file InstrumentValueData.h.
Referenced by setRangeIcons().
rangeIconsChanged
void InstrumentValueData::rangeIconsChanged (const QVariantList & rangeIcons) signal
Referenced by addRangeValue(), InstrumentValueData(), removeRangeValue(), and setRangeIcons().
rangeOpacities()
QVariantList InstrumentValueData::rangeOpacities (void) const inline
Definition at line 66 of file InstrumentValueData.h.
Referenced by setRangeOpacities().
rangeOpacitiesChanged
void InstrumentValueData::rangeOpacitiesChanged (const QVariantList & rangeOpacities) signal
Referenced by addRangeValue(), InstrumentValueData(), removeRangeValue(), and setRangeOpacities().
rangeType()
RangeType InstrumentValueData::rangeType (void) const inline
Definition at line 62 of file InstrumentValueData.h.
Referenced by setRangeType().
rangeTypeChanged
void InstrumentValueData::rangeTypeChanged (RangeType rangeType) signal
Referenced by InstrumentValueData(), and setRangeType().
rangeValues()
QVariantList InstrumentValueData::rangeValues (void) const inline
Definition at line 63 of file InstrumentValueData.h.
Referenced by setRangeValues().
rangeValuesChanged
void InstrumentValueData::rangeValuesChanged (const QVariantList & rangeValues) signal
Referenced by addRangeValue(), InstrumentValueData(), removeRangeValue(), and setRangeValues().
removeRangeValue()
void InstrumentValueData::removeRangeValue (int index)
Definition at line 220 of file InstrumentValueData.cc.
References ColorRange, IconSelectRange, NoRangeInfo, OpacityRange, rangeColorsChanged(), rangeIconsChanged(), rangeOpacitiesChanged(), and rangeValuesChanged().
setIcon()
void InstrumentValueData::setIcon (const QString & icon)
Definition at line 124 of file InstrumentValueData.cc.
References icon(), and iconChanged().
setRangeColors()
void InstrumentValueData::setRangeColors (const QVariantList & rangeColors)
Definition at line 146 of file InstrumentValueData.cc.
References rangeColors(), and rangeColorsChanged().
setRangeIcons()
void InstrumentValueData::setRangeIcons (const QVariantList & rangeIcons)
Definition at line 152 of file InstrumentValueData.cc.
References rangeIcons(), and rangeIconsChanged().
setRangeOpacities()
void InstrumentValueData::setRangeOpacities (const QVariantList & rangeOpacities)
Definition at line 158 of file InstrumentValueData.cc.
References rangeOpacities(), and rangeOpacitiesChanged().
setRangeType()
void InstrumentValueData::setRangeType (RangeType rangeType)
Definition at line 132 of file InstrumentValueData.cc.
References rangeType(), and rangeTypeChanged().
setRangeValues()
void InstrumentValueData::setRangeValues (const QVariantList & rangeValues)
Definition at line 140 of file InstrumentValueData.cc.
References rangeValues(), and rangeValuesChanged().
setShowUnits()
void InstrumentValueData::setShowUnits (bool showUnits)
Definition at line 116 of file InstrumentValueData.cc.
References showUnits(), and showUnitsChanged().
setText()
void InstrumentValueData::setText (const QString & text)
Definition at line 108 of file InstrumentValueData.cc.
References text(), and textChanged().
showUnits()
bool InstrumentValueData::showUnits (void) const inline
Definition at line 60 of file InstrumentValueData.h.
Referenced by setShowUnits().
showUnitsChanged
void InstrumentValueData::showUnitsChanged (bool showUnits) signal
Referenced by clearFact(), and setShowUnits().
text()
QString InstrumentValueData::text (void) const inline
Definition at line 59 of file InstrumentValueData.h.
Referenced by setText().
textChanged
void InstrumentValueData::textChanged (QString text) signal
Referenced by clearFact(), and setText().
Member Data Documentation
factName
FactValueGrid *factValueGrid MEMBER _factValueGrid const QString& InstrumentValueData::factName
Definition at line 47 of file InstrumentValueData.h.
vehicleFactGroupName
constexpr const char* InstrumentValueData::vehicleFactGroupName = "Vehicle" static constexpr
Definition at line 76 of file InstrumentValueData.h.
Referenced by factGroupNames(), and factValueNames().
The documentation for this class was generated from the following files:
src/QmlControls/InstrumentValueData.h
src/QmlControls/InstrumentValueData.cc