QGroundControl: TerrainTileCopernicus Class Reference
TerrainTileCopernicus Class Reference
Implements an interface for https://terrain-ce.suite.auterion.com/api/v1/.
#include <TerrainTileCopernicus.h>
Public Member Functions
TerrainTileCopernicus (const QByteArray &byteArray)
~TerrainTileCopernicus ()
Public Member Functions inherited from TerrainTile
TerrainTile (const QByteArray &byteArray)
virtual ~TerrainTile ()
bool isValid () const
double elevation (const QGeoCoordinate &coordinate) const
double minElevation () const
double maxElevation () const
double avgElevation () const
Static Public Member Functions
static QByteArray serializeFromData (const QByteArray &input)
static QJsonValue getJsonFromData (const QByteArray &input)
Static Public Attributes
static constexpr double kTileSizeDegrees = 0.01
Each terrain tile represents a square area .01 degrees in lat/lon.
static constexpr double kTileValueSpacingDegrees = (1.0 / 3600)
1 Arc-Second spacing of elevation values
static constexpr double kTileValueSpacingMeters = 30.0
Friends
class TerrainTileTest
Additional Inherited Members
Protected Attributes inherited from TerrainTile
struct TerrainTile::TileInfo_t Q_PACKED
Detailed Description
Implements an interface for https://terrain-ce.suite.auterion.com/api/v1/.
Definition at line 11 of file TerrainTileCopernicus.h.
Constructor & Destructor Documentation
TerrainTileCopernicus()
TerrainTileCopernicus::TerrainTileCopernicus (const QByteArray & byteArray) explicit
Constructor from serialized elevation data (either from file or web)
Parameters
byteArray
Definition at line 13 of file TerrainTileCopernicus.cc.
~TerrainTileCopernicus()
TerrainTileCopernicus::~TerrainTileCopernicus ()
Definition at line 18 of file TerrainTileCopernicus.cc.
Member Function Documentation
getJsonFromData()
QJsonValue TerrainTileCopernicus::getJsonFromData (const QByteArray & input) static
Definition at line 23 of file TerrainTileCopernicus.cc.
References errorString, QGCNetworkHelper::parseCompressedJson(), and JsonHelper::validateKeys().
Referenced by serializeFromData().
serializeFromData()
QByteArray TerrainTileCopernicus::serializeFromData (const QByteArray & input) static
Definition at line 72 of file TerrainTileCopernicus.cc.
References TerrainTile::TileInfo_t::avgElevation, errorString, getJsonFromData(), TerrainTile::TileInfo_t::gridSizeLat, TerrainTile::TileInfo_t::gridSizeLon, TerrainTile::TileInfo_t::maxElevation, TerrainTile::TileInfo_t::minElevation, TerrainTile::TileInfo_t::neLat, TerrainTile::TileInfo_t::neLon, TerrainTile::TileInfo_t::swLat, TerrainTile::TileInfo_t::swLon, and JsonHelper::validateKeys().
Referenced by CopernicusElevationProvider::serialize().
Friends And Related Symbol Documentation
TerrainTileTest
friend class TerrainTileTest friend
Definition at line 13 of file TerrainTileCopernicus.h.
Member Data Documentation
kTileSizeDegrees
constexpr double TerrainTileCopernicus::kTileSizeDegrees = 0.01 static constexpr
Each terrain tile represents a square area .01 degrees in lat/lon.
Definition at line 24 of file TerrainTileCopernicus.h.
Referenced by CopernicusElevationProvider::lat2tileY(), and CopernicusElevationProvider::long2tileX().
kTileValueSpacingDegrees
constexpr double TerrainTileCopernicus::kTileValueSpacingDegrees = (1.0 / 3600) static constexpr
1 Arc-Second spacing of elevation values
Definition at line 25 of file TerrainTileCopernicus.h.
Referenced by TerrainTileManager::addCarpetQuery().
kTileValueSpacingMeters
constexpr double TerrainTileCopernicus::kTileValueSpacingMeters = 30.0 static constexpr
Definition at line 26 of file TerrainTileCopernicus.h.
The documentation for this class was generated from the following files:
src/Terrain/Providers/TerrainTileCopernicus.h
src/Terrain/Providers/TerrainTileCopernicus.cc