QGroundControl: VehicleSupports Class Reference
VehicleSupports Class Reference
#include <VehicleSupports.h>
Signals
void terrainFrameChanged ()
Public Member Functions
VehicleSupports (Vehicle *vehicle)
bool throttleModeCenterZero READ throttleModeCenterZero CONSTANT (bool negativeThrust READ negativeThrust CONSTANT) 1(bool jsButton READ jsButton CONSTANT) 1(bool radio READ radio CONSTANT) 1(bool motorInterference READ motorInterference CONSTANT) 1(bool smartRTL READ smartRTL CONSTANT) 1(bool terrainFrame READ terrainFrame NOTIFY terrainFrameChanged) 1(bool guidedMode READ guidedMode CONSTANT) 1(bool pauseVehicle READ pauseVehicle CONSTANT) 1(bool orbitMode READ orbitMode CONSTANT) 1(bool roiMode READ roiMode CONSTANT) 1(bool takeoffMissionCommand READ takeoffMissionCommand CONSTANT) 1(bool guidedTakeoffWithAltitude READ guidedTakeoffWithAltitude CONSTANT) 1(bool guidedTakeoffWithoutAltitude READ guidedTakeoffWithoutAltitude CONSTANT) 1(bool changeHeading READ changeHeading CONSTANT) bool throttleModeCenterZero() const
bool negativeThrust () const
bool jsButton () const
bool radio () const
bool motorInterference () const
bool smartRTL () const
bool terrainFrame () const
bool guidedMode () const
bool pauseVehicle () const
bool orbitMode () const
bool roiMode () const
bool takeoffMissionCommand () const
bool guidedTakeoffWithAltitude () const
bool guidedTakeoffWithoutAltitude () const
bool changeHeading () const
Detailed Description
Definition at line 9 of file VehicleSupports.h.
Constructor & Destructor Documentation
VehicleSupports()
VehicleSupports::VehicleSupports (Vehicle * vehicle) explicit
Definition at line 6 of file VehicleSupports.cc.
References Vehicle::firmwareTypeChanged(), and terrainFrameChanged().
Member Function Documentation
changeHeading()
bool VehicleSupports::changeHeading () const
Definition at line 85 of file VehicleSupports.cc.
References FirmwarePlugin::ChangeHeadingCapability, Vehicle::firmwarePlugin(), and FirmwarePlugin::isCapable().
Referenced by Vehicle::guidedModeChangeHeading().
CONSTANT()
bool throttleModeCenterZero READ throttleModeCenterZero VehicleSupports::CONSTANT (bool negativeThrust READ negativeThrust CONSTANT) const
guidedMode()
bool VehicleSupports::guidedMode () const
Definition at line 48 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::GuidedModeCapability, and FirmwarePlugin::isCapable().
Referenced by Vehicle::guidedModeChangeAltitude(), Vehicle::guidedModeChangeEquivalentAirspeedMetersSecond(), Vehicle::guidedModeChangeGroundSpeedMetersSecond(), Vehicle::guidedModeGotoLocation(), Vehicle::guidedModeLand(), Vehicle::guidedModeRTL(), and Vehicle::guidedModeTakeoff().
guidedTakeoffWithAltitude()
bool VehicleSupports::guidedTakeoffWithAltitude () const
Definition at line 73 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::GuidedTakeoffCapability, and FirmwarePlugin::isCapable().
guidedTakeoffWithoutAltitude()
bool VehicleSupports::guidedTakeoffWithoutAltitude () const
Definition at line 78 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::GuidedTakeoffCapability, FirmwarePlugin::isCapable(), and FirmwarePlugin::TakeoffVehicleCapability.
jsButton()
bool VehicleSupports::jsButton () const
Definition at line 23 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), and FirmwarePlugin::supportsJSButton().
motorInterference()
bool VehicleSupports::motorInterference () const
Definition at line 33 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), and FirmwarePlugin::supportsMotorInterference().
negativeThrust()
bool VehicleSupports::negativeThrust () const
Definition at line 18 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), and FirmwarePlugin::supportsNegativeThrust().
orbitMode()
bool VehicleSupports::orbitMode () const
Definition at line 58 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::isCapable(), and FirmwarePlugin::OrbitModeCapability.
Referenced by Vehicle::guidedModeOrbit().
pauseVehicle()
bool VehicleSupports::pauseVehicle () const
Definition at line 53 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::isCapable(), and FirmwarePlugin::PauseVehicleCapability.
Referenced by Vehicle::pauseVehicle().
radio()
bool VehicleSupports::radio () const
Definition at line 28 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), and FirmwarePlugin::supportsRadio().
Referenced by APMAutoPilotPlugin::vehicleComponents().
roiMode()
bool VehicleSupports::roiMode () const
Definition at line 63 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::isCapable(), and FirmwarePlugin::ROIModeCapability.
Referenced by Vehicle::guidedModeROI(), and Vehicle::stopGuidedModeROI().
smartRTL()
bool VehicleSupports::smartRTL () const
Definition at line 38 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), and FirmwarePlugin::supportsSmartRTL().
takeoffMissionCommand()
bool VehicleSupports::takeoffMissionCommand () const
Definition at line 68 of file VehicleSupports.cc.
References Vehicle::firmwarePlugin(), FirmwarePlugin::isCapable(), and FirmwarePlugin::TakeoffVehicleCapability.
Referenced by MissionController::setCurrentPlanViewSeqNum().
terrainFrame()
bool VehicleSupports::terrainFrame () const
Definition at line 43 of file VehicleSupports.cc.
References Vehicle::px4Firmware().
terrainFrameChanged
void VehicleSupports::terrainFrameChanged () signal
Referenced by VehicleSupports().
The documentation for this class was generated from the following files:
src/Vehicle/VehicleSupports.h
src/Vehicle/VehicleSupports.cc