QGroundControl: BatteryIndicatorSettings Class Reference
BatteryIndicatorSettings Class Reference
#include <BatteryIndicatorSettings.h>
Public Member Functions
BatteryIndicatorSettings (QObject *parent=nullptr)
Fact *valueDisplay READ valueDisplay CONSTANT Fact * valueDisplay ()
Fact *threshold1 READ threshold1 CONSTANT Fact * threshold1 ()
Fact *threshold2 READ threshold2 CONSTANT Fact * threshold2 ()
Fact *consolidateMultipleBatteries READ consolidateMultipleBatteries CONSTANT Fact * consolidateMultipleBatteries ()
void setThreshold1 (int value)
void setThreshold2 (int value)
Public Member Functions inherited from SettingsGroup
SettingsGroup (const QString &name, const QString &settingsGroup, QObject *parent=nullptr)
bool userVisible READ userVisible WRITE setUserVisible NOTIFY virtual userVisibleChanged bool userVisible ()
virtual void setUserVisible (bool vis)
QString settingsGroup () const
Static Public Attributes
static const char * name = "BatteryIndicator"
static const char * settingsGroup = "BatteryIndicator"
static const char * valueDisplayName = "valueDisplay"
static const char * threshold1Name = "threshold1"
static const char * threshold2Name = "threshold2"
static const char * consolidateMultipleBatteriesName = "consolidateMultipleBatteries"
Additional Inherited Members
Signals inherited from SettingsGroup
void userVisibleChanged ()
Protected Member Functions inherited from SettingsGroup
SettingsFact * _createSettingsFact (const QString &factName)
Protected Attributes inherited from SettingsGroup
bool _userVisible
QString _name
QString _settingsGroup
QMap< QString, FactMetaData * > _nameToMetaDataMap
Detailed Description
Definition at line 7 of file BatteryIndicatorSettings.h.
Constructor & Destructor Documentation
BatteryIndicatorSettings()
BatteryIndicatorSettings::BatteryIndicatorSettings (QObject * parent = nullptr)
Definition at line 5 of file BatteryIndicatorSettings.cc.
Member Function Documentation
consolidateMultipleBatteries()
Fact * BatteryIndicatorSettings::consolidateMultipleBatteries ()
Definition at line 10 of file BatteryIndicatorSettings.cc.
setThreshold1()
void BatteryIndicatorSettings::setThreshold1 (int value)
Definition at line 52 of file BatteryIndicatorSettings.cc.
References threshold1(), and threshold2().
setThreshold2()
void BatteryIndicatorSettings::setThreshold2 (int value)
Definition at line 70 of file BatteryIndicatorSettings.cc.
References threshold1(), and threshold2().
threshold1()
Fact * BatteryIndicatorSettings::threshold1 ()
Definition at line 12 of file BatteryIndicatorSettings.cc.
References Fact::rawValueChanged().
Referenced by setThreshold1(), and setThreshold2().
threshold2()
Fact * BatteryIndicatorSettings::threshold2 ()
Definition at line 21 of file BatteryIndicatorSettings.cc.
References Fact::rawValueChanged().
Referenced by setThreshold1(), and setThreshold2().
valueDisplay()
Fact * BatteryIndicatorSettings::valueDisplay ()
Definition at line 9 of file BatteryIndicatorSettings.cc.
Member Data Documentation
consolidateMultipleBatteriesName
const char * BatteryIndicatorSettings::consolidateMultipleBatteriesName = "consolidateMultipleBatteries" static
Definition at line 20 of file BatteryIndicatorSettings.h.
name
const char * BatteryIndicatorSettings::name = "BatteryIndicator" static
Definition at line 15 of file BatteryIndicatorSettings.h.
settingsGroup
const char * BatteryIndicatorSettings::settingsGroup = "BatteryIndicator" static
Definition at line 15 of file BatteryIndicatorSettings.h.
threshold1Name
const char * BatteryIndicatorSettings::threshold1Name = "threshold1" static
Definition at line 18 of file BatteryIndicatorSettings.h.
threshold2Name
const char * BatteryIndicatorSettings::threshold2Name = "threshold2" static
Definition at line 19 of file BatteryIndicatorSettings.h.
valueDisplayName
const char * BatteryIndicatorSettings::valueDisplayName = "valueDisplay" static
Definition at line 17 of file BatteryIndicatorSettings.h.
The documentation for this class was generated from the following files:
src/Settings/BatteryIndicatorSettings.h
src/Settings/BatteryIndicatorSettings.cc