QGroundControl: GPSProvider Class Reference
GPSProvider Class Reference
#include <GPSProvider.h>
Classes
struct rtk_data_s
Public Types
enum class GPSType { u_blox , trimble , septentrio , femto }
Signals
void satelliteInfoUpdate (const satellite_info_s &message)
void sensorGnssRelativeUpdate (const sensor_gnss_relative_s &message)
void sensorGpsUpdate (const sensor_gps_s &message)
void RTCMDataUpdate (const QByteArray &message)
void surveyInStatus (float duration, float accuracyMM, double latitude, double longitude, float altitude, bool valid, bool active)
Public Member Functions
GPSProvider (const QString &device, GPSType type, const rtk_data_s &rtkData, const std::atomic_bool &requestStop, QObject *parent=nullptr)
~GPSProvider ()
int callback (GPSCallbackType type, void *data1, int data2)
Detailed Description
Definition at line 22 of file GPSProvider.h.
Member Enumeration Documentation
GPSType
enum class GPSProvider::GPSType strong
Enumerator
u_blox
trimble
septentrio
femto
Definition at line 27 of file GPSProvider.h.
Constructor & Destructor Documentation
GPSProvider()
GPSProvider::GPSProvider (const QString & device, GPSType type, const rtk_data_s & rtkData, const std::atomic_bool & requestStop, QObject * parent = nullptr)
Definition at line 21 of file GPSProvider.cc.
~GPSProvider()
GPSProvider::~GPSProvider ()
Definition at line 33 of file GPSProvider.cc.
Member Function Documentation
callback()
int GPSProvider::callback (GPSCallbackType type, void * data1, int data2)
Definition at line 67 of file GPSProvider.cc.
References QSerialPort::bytesAvailable(), QSerialPort::setBaudRate(), surveyInStatus(), QSerialPort::waitForBytesWritten(), and QSerialPort::waitForReadyRead().
RTCMDataUpdate
void GPSProvider::RTCMDataUpdate (const QByteArray & message) signal
Referenced by GPSRtk::connectGPS().
satelliteInfoUpdate
void GPSProvider::satelliteInfoUpdate (const satellite_info_s & message) signal
Referenced by GPSRtk::connectGPS().
sensorGnssRelativeUpdate
void GPSProvider::sensorGnssRelativeUpdate (const sensor_gnss_relative_s & message) signal
sensorGpsUpdate
void GPSProvider::sensorGpsUpdate (const sensor_gps_s & message) signal
Referenced by GPSRtk::connectGPS().
surveyInStatus
void GPSProvider::surveyInStatus (float duration, float accuracyMM, double latitude, double longitude, float altitude, bool valid, bool active) signal
Referenced by callback(), and GPSRtk::connectGPS().
The documentation for this class was generated from the following files:
src/GPS/GPSProvider.h
src/GPS/GPSProvider.cc