QGroundControl: GimbalController Class Reference
GimbalController Class Reference
#include <GimbalController.h>
Public Slots
void gimbalYawLock (bool yawLock)
void centerGimbal ()
void gimbalPitchStart (int direction)
void gimbalYawStart (int direction)
void gimbalPitchStop ()
void gimbalYawStop ()
Signals
void activeGimbalChanged ()
void showAcquireGimbalControlPopup ()
Detailed Description
Definition at line 12 of file GimbalController.h.
Member Function Documentation
activeGimbalChanged
void GimbalController::activeGimbalChanged () signal
centerGimbal
void GimbalController::centerGimbal () slot
Definition at line 424 of file GimbalController.cc.
gimbalPitchStart
void GimbalController::gimbalPitchStart (int direction) slot
Definition at line 377 of file GimbalController.cc.
References GimbalControllerSettings::joystickButtonsSpeed(), and Gimbal::setPitchRate().
gimbalPitchStop
void GimbalController::gimbalPitchStop () slot
Definition at line 402 of file GimbalController.cc.
References Gimbal::setPitchRate().
gimbalYawLock
void GimbalController::gimbalYawLock (bool yawLock) inline slot
Definition at line 52 of file GimbalController.h.
gimbalYawStart
void GimbalController::gimbalYawStart (int direction) slot
Definition at line 390 of file GimbalController.cc.
References GimbalControllerSettings::joystickButtonsSpeed(), and Gimbal::setYawRate().
gimbalYawStop
void GimbalController::gimbalYawStop () slot
Definition at line 413 of file GimbalController.cc.
References Gimbal::setYawRate().
showAcquireGimbalControlPopup
void GimbalController::showAcquireGimbalControlPopup () signal
The documentation for this class was generated from the following files:
src/Gimbal/GimbalController.h
src/Gimbal/GimbalController.cc