QGroundControl: QGCCameraParamIO Class Reference
QGCCameraParamIO Class Reference
Camera parameter handler.
#include <QGCCameraIO.h>
Public Member Functions
QGCCameraParamIO (MavlinkCameraControlInterface *control, Fact *fact, Vehicle *vehicle)
~QGCCameraParamIO ()
void handleParamAck (const mavlink_param_ext_ack_t &ack)
void handleParamValue (const mavlink_param_ext_value_t &value)
void setParamRequest ()
bool paramDone () const
void paramRequest (bool reset=true)
void sendParameter (bool updateUI=false)
Detailed Description
Camera parameter handler.
Definition at line 12 of file QGCCameraIO.h.
Constructor & Destructor Documentation
QGCCameraParamIO()
QGCCameraParamIO::QGCCameraParamIO (MavlinkCameraControlInterface * control, Fact * fact, Vehicle * vehicle)
Definition at line 17 of file QGCCameraIO.cc.
References Fact::containerRawValueChanged(), Fact::rawValueChanged(), FactMetaData::valueTypeBool, FactMetaData::valueTypeCustom, FactMetaData::valueTypeDouble, FactMetaData::valueTypeFloat, FactMetaData::valueTypeInt16, FactMetaData::valueTypeInt32, FactMetaData::valueTypeInt64, FactMetaData::valueTypeInt8, FactMetaData::valueTypeString, FactMetaData::valueTypeUint16, FactMetaData::valueTypeUint32, FactMetaData::valueTypeUint64, and FactMetaData::valueTypeUint8.
~QGCCameraParamIO()
QGCCameraParamIO::~QGCCameraParamIO ()
Definition at line 83 of file QGCCameraIO.cc.
Member Function Documentation
handleParamAck()
void QGCCameraParamIO::handleParamAck (const mavlink_param_ext_ack_t & ack)
Definition at line 215 of file QGCCameraIO.cc.
References MavlinkCameraControlInterface::factChanged(), and MavlinkCameraControlInterface::validateParameter().
handleParamValue()
void QGCCameraParamIO::handleParamValue (const mavlink_param_ext_value_t & value)
Definition at line 309 of file QGCCameraIO.cc.
References MavlinkCameraControlInterface::_paramDone(), MavlinkCameraControlInterface::factChanged(), MavlinkCameraControlInterface::incomingParameter(), Fact::rawValueChanged(), and Fact::valueChanged().
paramDone()
bool QGCCameraParamIO::paramDone () const inline
Definition at line 21 of file QGCCameraIO.h.
paramRequest()
void QGCCameraParamIO::paramRequest (bool reset = true)
Definition at line 334 of file QGCCameraIO.cc.
References MavlinkCameraControlInterface::_paramDone(), MavlinkCameraControlInterface::compID(), MAVLinkProtocol::getComponentId(), MAVLinkProtocol::getSystemId(), Vehicle::id(), MAVLinkProtocol::instance(), VehicleLinkManager::primaryLink(), Vehicle::sendMessageOnLinkThreadSafe(), and Vehicle::vehicleLinkManager().
sendParameter()
void QGCCameraParamIO::sendParameter (bool updateUI = false)
Definition at line 371 of file QGCCameraIO.cc.
setParamRequest()
void QGCCameraParamIO::setParamRequest ()
Definition at line 379 of file QGCCameraIO.cc.
The documentation for this class was generated from the following files:
src/Camera/QGCCameraIO.h
src/Camera/QGCCameraIO.cc