QGroundControl: ActuatorOutputs::ChannelConfig Class Reference
ActuatorOutputs::ChannelConfig Class Reference
#include <ActuatorOutputs.h>
Public Types
enum class Function {
Unspecified = 0 , OutputFunction , Disarmed , Minimum ,
Maximum , Failsafe
}
Describes the meaning of the parameter.
Signals
void visibleChanged ()
Public Member Functions
ChannelConfig (QObject *parent, const Parameter &param, Function function, const Condition &visibilityCondition)
QString label READ label CONSTANT (bool advanced READ advanced CONSTANT) 1(bool visible READ visible NOTIFY visibleChanged) const QString &label() const
const QString & parameter () const
Function function () const
const Condition & visibilityCondition () const
bool advanced () const
bool visible () const
Parameter::DisplayOption displayOption () const
int indexOffset () const
void reevaluate ()
Detailed Description
Config parameters that apply to individual channels
Definition at line 46 of file ActuatorOutputs.h.
Member Enumeration Documentation
Function
enum class ActuatorOutputs::ChannelConfig::Function strong
Describes the meaning of the parameter.
Enumerator
Unspecified
OutputFunction
Disarmed
Minimum
Maximum
Failsafe
Definition at line 52 of file ActuatorOutputs.h.
Constructor & Destructor Documentation
ChannelConfig()
ActuatorOutputs::ChannelConfig::ChannelConfig (QObject * parent, const Parameter & param, Function function, const Condition & visibilityCondition) inline
Definition at line 61 of file ActuatorOutputs.h.
Member Function Documentation
advanced()
bool ActuatorOutputs::ChannelConfig::advanced () const inline
Definition at line 73 of file ActuatorOutputs.h.
References Parameter::advanced.
CONSTANT()
QString label READ label ActuatorOutputs::ChannelConfig::CONSTANT (bool advanced READ advanced CONSTANT) const & inline
Definition at line 65 of file ActuatorOutputs.h.
References Parameter::label.
displayOption()
Parameter::DisplayOption ActuatorOutputs::ChannelConfig::displayOption () const inline
Definition at line 76 of file ActuatorOutputs.h.
References Parameter::displayOption.
function()
Function ActuatorOutputs::ChannelConfig::function () const inline
Definition at line 71 of file ActuatorOutputs.h.
Referenced by ActuatorOutputs::ActuatorOutput::forEachOutputFunction().
indexOffset()
int ActuatorOutputs::ChannelConfig::indexOffset () const inline
Definition at line 77 of file ActuatorOutputs.h.
References Parameter::indexOffset.
parameter()
const QString & ActuatorOutputs::ChannelConfig::parameter () const inline
Definition at line 70 of file ActuatorOutputs.h.
References Parameter::name.
Referenced by ActuatorOutputs::ActuatorOutputChannel::ActuatorOutputChannel().
reevaluate()
void ChannelConfig::reevaluate ()
Definition at line 6 of file ActuatorOutputs.cc.
References visibleChanged().
Referenced by Actuators::parametersChanged().
visibilityCondition()
const Condition & ActuatorOutputs::ChannelConfig::visibilityCondition () const inline
Definition at line 72 of file ActuatorOutputs.h.
visible()
bool ActuatorOutputs::ChannelConfig::visible () const inline
Definition at line 74 of file ActuatorOutputs.h.
References Condition::evaluate().
visibleChanged
void ActuatorOutputs::ChannelConfig::visibleChanged () signal
Referenced by reevaluate().
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/ActuatorOutputs.h
src/Vehicle/Actuators/ActuatorOutputs.cc