QGroundControl: Mixer::ChannelConfig Class Reference
Mixer::ChannelConfig Class Reference
#include <Mixer.h>
Signals
void visibleChanged ()
Public Member Functions
ChannelConfig (QObject *parent, const MixerParameter &parameter, bool isActuatorTypeConfig=false)
QString label READ label CONSTANT (bool visible READ visible NOTIFY visibleChanged) 1(bool advanced READ advanced CONSTANT) const QString &label() const
Function function () const
bool advanced () const
bool isActuatorTypeConfig () const
bool visible () const
const QList< float > & fixedValues () const
Parameter::DisplayOption displayOption () const
int indexOffset () const
const QString & identifier () const
const MixerParameter & config () const
virtual ChannelConfigInstance * instantiate (int paramIndex, int actuatorTypeIndex, ParameterManager *parameterManager, std::function< void(Function, Fact *)> factAddedCb)
Protected Member Functions
void channelInstanceCreated (ChannelConfigInstance *instance)
Detailed Description
Config parameters that apply to individual channels
Definition at line 126 of file Mixer.h.
Constructor & Destructor Documentation
ChannelConfig()
Mixer::ChannelConfig::ChannelConfig (QObject * parent, const MixerParameter & parameter, bool isActuatorTypeConfig = false) inline
Definition at line 131 of file Mixer.h.
Member Function Documentation
advanced()
bool Mixer::ChannelConfig::advanced () const inline
Definition at line 140 of file Mixer.h.
References Parameter::advanced, and Mixer::MixerParameter::param.
channelInstanceCreated()
void ChannelConfig::channelInstanceCreated (ChannelConfigInstance * instance) protected
Definition at line 50 of file Mixer.cc.
References Mixer::ChannelConfigInstance::visibleChanged().
Referenced by instantiate(), and Mixer::ChannelConfigVirtualAxis::instantiate().
config()
const MixerParameter & Mixer::ChannelConfig::config () const inline
Definition at line 152 of file Mixer.h.
Referenced by Mixer::Mixers::update().
CONSTANT()
QString label READ label Mixer::ChannelConfig::CONSTANT (bool visible READ visible NOTIFY visibleChanged) const & inline
Definition at line 134 of file Mixer.h.
References Parameter::label, and Mixer::MixerParameter::param.
displayOption()
Parameter::DisplayOption Mixer::ChannelConfig::displayOption () const inline
Definition at line 147 of file Mixer.h.
References Parameter::displayOption, and Mixer::MixerParameter::param.
Referenced by instantiate().
fixedValues()
const QList< float > & Mixer::ChannelConfig::fixedValues () const inline
Definition at line 145 of file Mixer.h.
References Mixer::MixerParameter::values.
Referenced by instantiate().
function()
Function Mixer::ChannelConfig::function () const inline
Definition at line 139 of file Mixer.h.
References Mixer::MixerParameter::function.
Referenced by instantiate().
identifier()
const QString & Mixer::ChannelConfig::identifier () const inline
Definition at line 150 of file Mixer.h.
References Mixer::MixerParameter::identifier.
indexOffset()
int Mixer::ChannelConfig::indexOffset () const inline
Definition at line 148 of file Mixer.h.
References Parameter::indexOffset, and Mixer::MixerParameter::param.
Referenced by instantiate().
instantiate()
ChannelConfigInstance * ChannelConfig::instantiate (int paramIndex, int actuatorTypeIndex, ParameterManager * parameterManager, std::function< void(Function, Fact *)> factAddedCb) virtual
Reimplemented in Mixer::ChannelConfigVirtualAxis.
Definition at line 6 of file Mixer.cc.
References Parameter::Bitset, Parameter::BoolTrueIfPositive, channelInstanceCreated(), ParameterManager::defaultComponentId, displayOption(), fixedValues(), function(), ParameterManager::getParameter(), indexOffset(), Parameter::name, Mixer::MixerParameter::param, ParameterManager::parameterExists(), FactMetaData::setDecimalPlaces(), FactMetaData::setReadOnly(), and FactMetaData::valueTypeFloat.
isActuatorTypeConfig()
bool Mixer::ChannelConfig::isActuatorTypeConfig () const inline
Definition at line 141 of file Mixer.h.
visible()
bool Mixer::ChannelConfig::visible () const inline
Definition at line 143 of file Mixer.h.
visibleChanged
void Mixer::ChannelConfig::visibleChanged () signal
The documentation for this class was generated from the following files:
src/Vehicle/Actuators/Mixer.h
src/Vehicle/Actuators/Mixer.cc