QGroundControl: QGCDeviceInfo::QGCAmbientTemperature Class Reference
QGCDeviceInfo::QGCAmbientTemperature Class Reference
#include <DeviceInfo.h>
Signals
void temperatureUpdated (qreal temperature)
Public Member Functions
QGCAmbientTemperature (QObject *parent=nullptr)
~QGCAmbientTemperature ()
qreal temperature () const
bool init ()
void quit ()
Static Public Member Functions
static QGCAmbientTemperature * instance ()
Detailed Description
Definition at line 29 of file DeviceInfo.h.
Constructor & Destructor Documentation
QGCAmbientTemperature()
QGCDeviceInfo::QGCAmbientTemperature::QGCAmbientTemperature (QObject * parent = nullptr)
Definition at line 20 of file DeviceInfo.cc.
References error, and init().
~QGCAmbientTemperature()
QGCDeviceInfo::QGCAmbientTemperature::~QGCAmbientTemperature ()
Definition at line 36 of file DeviceInfo.cc.
Member Function Documentation
init()
bool QGCDeviceInfo::QGCAmbientTemperature::init ()
Definition at line 41 of file DeviceInfo.cc.
References temperatureUpdated().
Referenced by QGCAmbientTemperature().
instance()
QGCAmbientTemperature * QGCDeviceInfo::QGCAmbientTemperature::instance () static
Definition at line 15 of file DeviceInfo.cc.
Referenced by APMFirmwarePlugin::startCompensatingBaro().
quit()
void QGCDeviceInfo::QGCAmbientTemperature::quit ()
Definition at line 96 of file DeviceInfo.cc.
temperature()
qreal QGCDeviceInfo::QGCAmbientTemperature::temperature () const inline
Definition at line 39 of file DeviceInfo.h.
temperatureUpdated
void QGCDeviceInfo::QGCAmbientTemperature::temperatureUpdated (qreal temperature) signal
Referenced by init(), and APMFirmwarePlugin::startCompensatingBaro().
The documentation for this class was generated from the following files:
src/Utilities/DeviceInfo.h
src/Utilities/DeviceInfo.cc