QGroundControl: SensorsComponentController Class Reference
SensorsComponentController Class Reference
Sensors Component MVC Controller for SensorsComponent.qml.
#include <SensorsComponentController.h>
Signals
void showGyroCalAreaChanged (void)
void showOrientationCalAreaChanged (void)
void orientationCalSidesDoneChanged (void)
void orientationCalSidesVisibleChanged (void)
void orientationCalSidesInProgressChanged (void)
void orientationCalSidesRotateChanged (void)
void resetStatusTextArea (void)
void waitingForCancelChanged (void)
void magCalComplete (void)
void calibrationActiveChanged (void)
Signals inherited from FactPanelController
void missingParametersAvailable ()
Public Member Functions
SensorsComponentController (void)
QQuickItem *statusLog MEMBER _statusLog (QQuickItem *progressBar MEMBER _progressBar) 1(QQuickItem *orientationCalAreaHelpText MEMBER _orientationCalAreaHelpText) 1(bool calibrationActive READ calibrationActive NOTIFY calibrationActiveChanged) 1(bool showOrientationCalArea MEMBER _showOrientationCalArea NOTIFY showOrientationCalAreaChanged) 1(bool orientationCalDownSideDone MEMBER _orientationCalDownSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalUpsideDownSideDone MEMBER _orientationCalUpsideDownSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalLeftSideDone MEMBER _orientationCalLeftSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalRightSideDone MEMBER _orientationCalRightSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalNoseDownSideDone MEMBER _orientationCalNoseDownSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalTailDownSideDone MEMBER _orientationCalTailDownSideDone NOTIFY orientationCalSidesDoneChanged) 1(bool orientationCalDownSideVisible MEMBER _orientationCalDownSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalUpsideDownSideVisible MEMBER _orientationCalUpsideDownSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalLeftSideVisible MEMBER _orientationCalLeftSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalRightSideVisible MEMBER _orientationCalRightSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalNoseDownSideVisible MEMBER _orientationCalNoseDownSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalTailDownSideVisible MEMBER _orientationCalTailDownSideVisible NOTIFY orientationCalSidesVisibleChanged) 1(bool orientationCalDownSideInProgress MEMBER _orientationCalDownSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalUpsideDownSideInProgress MEMBER _orientationCalUpsideDownSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalLeftSideInProgress MEMBER _orientationCalLeftSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalRightSideInProgress MEMBER _orientationCalRightSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalNoseDownSideInProgress MEMBER _orientationCalNoseDownSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalTailDownSideInProgress MEMBER _orientationCalTailDownSideInProgress NOTIFY orientationCalSidesInProgressChanged) 1(bool orientationCalDownSideRotate MEMBER _orientationCalDownSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool orientationCalUpsideDownSideRotate MEMBER _orientationCalUpsideDownSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool orientationCalLeftSideRotate MEMBER _orientationCalLeftSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool orientationCalRightSideRotate MEMBER _orientationCalRightSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool orientationCalNoseDownSideRotate MEMBER _orientationCalNoseDownSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool orientationCalTailDownSideRotate MEMBER _orientationCalTailDownSideRotate NOTIFY orientationCalSidesRotateChanged) 1(bool waitingForCancel MEMBER _waitingForCancel NOTIFY waitingForCancelChanged) 1 void calibrateCompass(void)
void calibrateGyro (void)
void calibrateAccel (void)
void calibrateLevel (void)
void calibrateAirspeed (void)
void cancelCalibration (void)
bool usingUDPLink (void)
void resetFactoryParameters ()
bool calibrationActive () const
Additional Inherited Members
Protected Member Functions inherited from FactPanelController
bool _allParametersExists (int componentId, const QStringList &names) const
void _reportMissingParameter (int componentId, const QString &name) const
Report a missing parameter.
Protected Attributes inherited from FactPanelController
Vehicle * _vehicle = nullptr
Detailed Description
Sensors Component MVC Controller for SensorsComponent.qml.
Definition at line 12 of file SensorsComponentController.h.
Constructor & Destructor Documentation
SensorsComponentController()
SensorsComponentController::SensorsComponentController (void)
Definition at line 9 of file SensorsComponentController.cc.
References Vehicle::sensorsParametersResetAck().
Member Function Documentation
_statusLog()
QQuickItem *statusLog MEMBER SensorsComponentController::_statusLog (QQuickItem *progressBar MEMBER _progressBar)
calibrateAccel()
void SensorsComponentController::calibrateAccel (void)
Definition at line 175 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, QGCMAVLink::CalibrationAccel, and Vehicle::startCalibration().
calibrateAirspeed()
void SensorsComponentController::calibrateAirspeed (void)
Definition at line 187 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, QGCMAVLink::CalibrationPX4Airspeed, and Vehicle::startCalibration().
calibrateGyro()
void SensorsComponentController::calibrateGyro (void)
Definition at line 163 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, QGCMAVLink::CalibrationGyro, and Vehicle::startCalibration().
calibrateLevel()
void SensorsComponentController::calibrateLevel (void)
Definition at line 181 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, QGCMAVLink::CalibrationLevel, and Vehicle::startCalibration().
calibrationActive()
bool SensorsComponentController::calibrationActive () const inline
Definition at line 67 of file SensorsComponentController.h.
calibrationActiveChanged
void SensorsComponentController::calibrationActiveChanged (void) signal
cancelCalibration()
void SensorsComponentController::cancelCalibration (void)
Definition at line 458 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, Vehicle::stopCalibration(), and waitingForCancelChanged().
magCalComplete
void SensorsComponentController::magCalComplete (void) signal
orientationCalSidesDoneChanged
void SensorsComponentController::orientationCalSidesDoneChanged (void) signal
orientationCalSidesInProgressChanged
void SensorsComponentController::orientationCalSidesInProgressChanged (void) signal
orientationCalSidesRotateChanged
void SensorsComponentController::orientationCalSidesRotateChanged (void) signal
orientationCalSidesVisibleChanged
void SensorsComponentController::orientationCalSidesVisibleChanged (void) signal
resetFactoryParameters()
void SensorsComponentController::resetFactoryParameters ()
Definition at line 481 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, Vehicle::defaultComponentId(), and Vehicle::sendMavCommand().
resetStatusTextArea
void SensorsComponentController::resetStatusTextArea (void) signal
showGyroCalAreaChanged
void SensorsComponentController::showGyroCalAreaChanged (void) signal
showOrientationCalAreaChanged
void SensorsComponentController::showOrientationCalAreaChanged (void) signal
usingUDPLink()
bool SensorsComponentController::usingUDPLink (void)
Definition at line 49 of file SensorsComponentController.cc.
References FactPanelController::_vehicle, VehicleLinkManager::primaryLink(), and Vehicle::vehicleLinkManager().
waitingForCancelChanged
void SensorsComponentController::waitingForCancelChanged (void) signal
Referenced by cancelCalibration().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/SensorsComponentController.h
src/AutoPilotPlugins/PX4/SensorsComponentController.cc