QGroundControl: TerrainQueryInterface Class Reference
TerrainQueryInterface Class Reference
Base class for offline/online terrain queries.
#include <TerrainQueryInterface.h>
Signals
void coordinateHeightsReceived (bool success, const QList< double > &heights)
void pathHeightsReceived (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > &heights)
void carpetHeightsReceived (bool success, double minHeight, double maxHeight, const QList< QList< double > > &carpet)
Public Member Functions
TerrainQueryInterface (QObject *parent=nullptr)
virtual ~TerrainQueryInterface ()
virtual void requestCoordinateHeights (const QList< QGeoCoordinate > &coordinates)
virtual void requestPathHeights (const QGeoCoordinate &fromCoord, const QGeoCoordinate &toCoord)
virtual void requestCarpetHeights (const QGeoCoordinate &swCoord, const QGeoCoordinate &neCoord, bool statsOnly)
void signalCoordinateHeights (bool success, const QList< double > &heights)
void signalPathHeights (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > &heights)
void signalCarpetHeights (bool success, double minHeight, double maxHeight, const QList< QList< double > > &carpet)
Protected Member Functions
virtual void _requestFailed ()
Protected Attributes
TerrainQuery::QueryMode _queryMode = TerrainQuery::QueryMode::QueryModeNone
Detailed Description
Base class for offline/online terrain queries.
Definition at line 26 of file TerrainQueryInterface.h.
Constructor & Destructor Documentation
TerrainQueryInterface()
TerrainQueryInterface::TerrainQueryInterface (QObject * parent = nullptr) explicit
Definition at line 12 of file TerrainQueryInterface.cc.
~TerrainQueryInterface()
TerrainQueryInterface::~TerrainQueryInterface () virtual
Definition at line 18 of file TerrainQueryInterface.cc.
Member Function Documentation
_requestFailed()
void TerrainQueryInterface::_requestFailed () protected virtual
Definition at line 59 of file TerrainQueryInterface.cc.
References _queryMode, carpetHeightsReceived(), coordinateHeightsReceived(), pathHeightsReceived(), TerrainQuery::QueryModeCarpet, TerrainQuery::QueryModeCoordinates, and TerrainQuery::QueryModePath.
Referenced by TerrainOnlineQuery::_requestFinished().
carpetHeightsReceived
void TerrainQueryInterface::carpetHeightsReceived (bool success, double minHeight, double maxHeight, const QList< QList< double > > & carpet) signal
Referenced by _requestFailed(), signalCarpetHeights(), and TerrainAreaQuery::TerrainAreaQuery().
coordinateHeightsReceived
void TerrainQueryInterface::coordinateHeightsReceived (bool success, const QList< double > & heights) signal
Referenced by _requestFailed(), TerrainAtCoordinateBatchManager::setTerrainQueryInterface(), signalCoordinateHeights(), and TerrainAtCoordinateBatchManager::TerrainAtCoordinateBatchManager().
pathHeightsReceived
void TerrainQueryInterface::pathHeightsReceived (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > & heights) signal
Referenced by _requestFailed(), signalPathHeights(), and TerrainPathQuery::TerrainPathQuery().
requestCarpetHeights()
void TerrainQueryInterface::requestCarpetHeights (const QGeoCoordinate & swCoord, const QGeoCoordinate & neCoord, bool statsOnly) virtual
Request terrain heights for the rectangular area specified. Signals: carpetHeights when data is available
Parameters
swCoord South-West bound of rectangular area to query
neCoord North-East bound of rectangular area to query
statsOnly true: Return only stats, no carpet data
Reimplemented in TerrainQueryCopernicus, and TerrainOfflineQuery.
Definition at line 36 of file TerrainQueryInterface.cc.
Referenced by TerrainAreaQuery::requestData().
requestCoordinateHeights()
void TerrainQueryInterface::requestCoordinateHeights (const QList< QGeoCoordinate > & coordinates) virtual
Request terrain heights for specified coodinates. Signals: coordinateHeights when data is available
Parameters
coordinates to query
Reimplemented in TerrainQueryCopernicus, and TerrainOfflineQuery.
Definition at line 23 of file TerrainQueryInterface.cc.
requestPathHeights()
void TerrainQueryInterface::requestPathHeights (const QGeoCoordinate & fromCoord, const QGeoCoordinate & toCoord) virtual
Requests terrain heights along the path specified by the two coordinates. Signals: pathHeights
Parameters
coordinates to query
Reimplemented in TerrainQueryCopernicus, and TerrainOfflineQuery.
Definition at line 29 of file TerrainQueryInterface.cc.
Referenced by TerrainPathQuery::requestData().
signalCarpetHeights()
void TerrainQueryInterface::signalCarpetHeights (bool success, double minHeight, double maxHeight, const QList< QList< double > > & carpet)
Definition at line 54 of file TerrainQueryInterface.cc.
References carpetHeightsReceived().
Referenced by TerrainTileManager::addCarpetQuery().
signalCoordinateHeights()
void TerrainQueryInterface::signalCoordinateHeights (bool success, const QList< double > & heights)
Definition at line 44 of file TerrainQueryInterface.cc.
References coordinateHeightsReceived().
Referenced by TerrainTileManager::addCoordinateQuery().
signalPathHeights()
void TerrainQueryInterface::signalPathHeights (bool success, double distanceBetween, double finalDistanceBetween, const QList< double > & heights)
Definition at line 49 of file TerrainQueryInterface.cc.
References pathHeightsReceived().
Referenced by TerrainTileManager::addPathQuery().
Member Data Documentation
_queryMode
TerrainQuery::QueryMode TerrainQueryInterface::_queryMode = TerrainQuery::QueryMode::QueryModeNone protected
Definition at line 63 of file TerrainQueryInterface.h.
Referenced by _requestFailed(), TerrainQueryCopernicus::requestCarpetHeights(), TerrainOfflineQuery::requestCarpetHeights(), TerrainQueryCopernicus::requestCoordinateHeights(), TerrainOfflineQuery::requestCoordinateHeights(), TerrainQueryCopernicus::requestPathHeights(), and TerrainOfflineQuery::requestPathHeights().
The documentation for this class was generated from the following files:
src/Terrain/TerrainQueryInterface.h
src/Terrain/TerrainQueryInterface.cc