QGroundControl: Section Class Reference
Section Class Reference abstract
#include <Section.h>
Signals
void availableChanged (bool available)
void settingsSpecifiedChanged (bool settingsSpecified)
void dirtyChanged (bool dirty)
void itemCountChanged (int itemCount)
Public Member Functions
Section (PlanMasterController *masterController, QObject *parent=nullptr)
bool available READ available WRITE setAvailable NOTIFY availableChanged (bool settingsSpecified READ settingsSpecified NOTIFY settingsSpecifiedChanged) 1(bool dirty READ dirty WRITE setDirty NOTIFY availableChanged) virtual bool available(void) const =0
virtual bool settingsSpecified (void) const =0
virtual bool dirty (void) const =0
virtual void setAvailable (bool available)=0
virtual void setDirty (bool dirty)=0
virtual bool scanForSection (QmlObjectListModel *visualItems, int scanIndex)=0
virtual void appendSectionItems (QList< MissionItem * > &items, QObject *missionItemParent, int &nextSequenceNumber)=0
virtual int itemCount (void) const =0
Protected Attributes
PlanMasterController * _masterController = nullptr
Detailed Description
Definition at line 9 of file Section.h.
Constructor & Destructor Documentation
Section()
Section::Section (PlanMasterController * masterController, QObject * parent = nullptr) inline
Definition at line 14 of file Section.h.
Member Function Documentation
appendSectionItems()
virtual void Section::appendSectionItems (QList< MissionItem * > & items, QObject * missionItemParent, int & nextSequenceNumber) pure virtual
Appends the mission items associated with this section
Parameters
items List to append to
missionItemParent QObject parent for created MissionItems
nextSequenceNumber[in,out] Sequence number for first item, updated as items are added
Implemented in CameraSection, and SpeedSection.
availableChanged [1/2]
void Section::availableChanged (bool available) signal
availableChanged() [2/2]
bool available READ available WRITE setAvailable NOTIFY Section::availableChanged (bool settingsSpecified READ settingsSpecified NOTIFY settingsSpecifiedChanged) const pure virtual
Referenced by CameraSection::setAvailable(), and SpeedSection::setAvailable().
dirty()
virtual bool Section::dirty (void) const pure virtual
Implemented in CameraSection, and SpeedSection.
dirtyChanged
void Section::dirtyChanged (bool dirty) signal
Referenced by MissionSettingsItem::MissionSettingsItem(), CameraSection::setDirty(), and SpeedSection::setDirty().
itemCount()
virtual int Section::itemCount (void) const pure virtual
Returns the number of mission items represented by this section. Signals: itemCountChanged
Implemented in CameraSection, and SpeedSection.
itemCountChanged
void Section::itemCountChanged (int itemCount) signal
Referenced by MissionSettingsItem::MissionSettingsItem(), and SpeedSection::setSpecifyFlightSpeed().
scanForSection()
virtual bool Section::scanForSection (QmlObjectListModel * visualItems, int scanIndex) pure virtual
Scans the loaded items for the section items
Parameters
visualItems Item list
scanIndex Index to start scanning from
Returns
true: section found, items added, scanIndex updated
Implemented in CameraSection, and SpeedSection.
setAvailable()
virtual void Section::setAvailable (bool available) pure virtual
Implemented in CameraSection, and SpeedSection.
setDirty()
virtual void Section::setDirty (bool dirty) pure virtual
Implemented in CameraSection, and SpeedSection.
settingsSpecified()
virtual bool Section::settingsSpecified (void) const pure virtual
Implemented in CameraSection, and SpeedSection.
settingsSpecifiedChanged
void Section::settingsSpecifiedChanged (bool settingsSpecified) signal
Referenced by CameraSection::scanForSection(), and SpeedSection::SpeedSection().
Member Data Documentation
_masterController
PlanMasterController* Section::_masterController = nullptr protected
Definition at line 55 of file Section.h.
Referenced by SpeedSection::appendSectionItems(), CameraSection::cameraModeSupported(), SpeedSection::scanForSection(), SpeedSection::setAvailable(), and SpeedSection::SpeedSection().
The documentation for this class was generated from the following file:
src/MissionManager/Section.h