QGroundControl: SensorsComponent Class Reference
SensorsComponent Class Reference
#include <SensorsComponent.h>
Public Member Functions
SensorsComponent (Vehicle *vehicle, AutoPilotPlugin *autopilot, QObject *parent=nullptr)
bool airspeedCalSupported READ _airspeedCalSupported STORED false NOTIFY setupCompleteChanged (bool airspeedCalRequired READ _airspeedCalRequired STORED false NOTIFY setupCompleteChanged) QStringList setupCompleteChangedTriggerList(void) const override
virtual QString name (void) const override
virtual QString description (void) const override
virtual QString iconResource (void) const override
virtual bool requiresSetup (void) const override
virtual bool setupComplete (void) const override
virtual QUrl setupSource (void) const override
virtual QUrl summaryQmlSource (void) const override
QStringList sections () const override
bool showFirstSectionOnRootClick () const override
When true, clicking the root component in the tree selects the first section instead of showing all.
bool sectionSetupComplete (const QString &sectionName) const override
Returns setup-complete status for a named section. Default returns true (no per-section tracking).
Additional Inherited Members
Signals inherited from VehicleComponent
void setupCompleteChanged ()
void setupSourceChanged ()
void sectionsChanged ()
Protected Slots inherited from VehicleComponent
void _triggerUpdated (QVariant)
Protected Attributes inherited from VehicleComponent
Vehicle * _vehicle = nullptr
AutoPilotPlugin * _autopilot = nullptr
AutoPilotPlugin::KnownVehicleComponent _KnownVehicleComponent
Detailed Description
Definition at line 5 of file SensorsComponent.h.
Constructor & Destructor Documentation
SensorsComponent()
SensorsComponent::SensorsComponent (Vehicle * vehicle, AutoPilotPlugin * autopilot, QObject * parent = nullptr)
Definition at line 5 of file SensorsComponent.cc.
References VehicleComponent::_vehicle, Vehicle::airship(), Vehicle::firmwareMajorVersion(), Vehicle::firmwareMinorVersion(), Vehicle::fixedWing(), and Vehicle::vtol().
Member Function Documentation
description()
QString SensorsComponent::description (void) const override virtual
Reimplemented from VehicleComponent.
Definition at line 26 of file SensorsComponent.cc.
iconResource()
QString SensorsComponent::iconResource (void) const override virtual
Implements VehicleComponent.
Definition at line 31 of file SensorsComponent.cc.
name()
QString SensorsComponent::name (void) const override virtual
Implements VehicleComponent.
Definition at line 21 of file SensorsComponent.cc.
requiresSetup()
bool SensorsComponent::requiresSetup (void) const override virtual
Implements VehicleComponent.
Definition at line 36 of file SensorsComponent.cc.
sections()
QStringList SensorsComponent::sections () const override virtual
Section names for sidebar navigation. Auto-populated from vehicleConfigJson() JSON. Repeat sections are expanded by probing vehicle parameters.
Reimplemented from VehicleComponent.
Definition at line 92 of file SensorsComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), ParameterManager::parameterExists(), and Vehicle::parameterManager().
sectionSetupComplete()
bool SensorsComponent::sectionSetupComplete (const QString & sectionName) const override virtual
Returns setup-complete status for a named section. Default returns true (no per-section tracking).
Reimplemented from VehicleComponent.
Definition at line 154 of file SensorsComponent.cc.
References VehicleComponent::_vehicle, ParameterManager::defaultComponentId, ParameterManager::getParameter(), and Vehicle::parameterManager().
setupComplete()
bool SensorsComponent::setupComplete (void) const override virtual
Implements VehicleComponent.
Definition at line 41 of file SensorsComponent.cc.
References VehicleComponent::_vehicle, Vehicle::airship(), ParameterManager::defaultComponentId, Vehicle::firmwareMajorVersion(), Vehicle::firmwareMinorVersion(), Vehicle::fixedWing(), ParameterManager::getParameter(), ParameterManager::parameterExists(), Vehicle::parameterManager(), and Vehicle::vtol().
setupCompleteChanged()
bool airspeedCalSupported READ _airspeedCalSupported STORED false NOTIFY SensorsComponent::setupCompleteChanged (bool airspeedCalRequired READ _airspeedCalRequired STORED false NOTIFY setupCompleteChanged) const override
setupSource()
QUrl SensorsComponent::setupSource (void) const override virtual
Implements VehicleComponent.
Definition at line 87 of file SensorsComponent.cc.
showFirstSectionOnRootClick()
bool SensorsComponent::showFirstSectionOnRootClick () const inline override virtual
When true, clicking the root component in the tree selects the first section instead of showing all.
Reimplemented from VehicleComponent.
Definition at line 27 of file SensorsComponent.h.
summaryQmlSource()
QUrl SensorsComponent::summaryQmlSource (void) const override virtual
Implements VehicleComponent.
Definition at line 118 of file SensorsComponent.cc.
References VehicleComponent::_vehicle, Vehicle::airship(), Vehicle::fixedWing(), and Vehicle::vtol().
The documentation for this class was generated from the following files:
src/AutoPilotPlugins/PX4/SensorsComponent.h
src/AutoPilotPlugins/PX4/SensorsComponent.cc