var dir_b1a742ea28d3031b3ffcd65fa736bb83 =
[
    [ "BluetoothSettings.qml", "BluetoothSettings_8qml.html", null ],
    [ "DebugWindow.qml", "DebugWindow_8qml.html", null ],
    [ "GcsPositionStatus.qml", "GcsPositionStatus_8qml.html", null ],
    [ "HelpSettings.qml", "HelpSettings_8qml.html", null ],
    [ "LinkConfigurationManager.qml", "LinkConfigurationManager_8qml.html", null ],
    [ "LogReplaySettings.qml", "LogReplaySettings_8qml.html", null ],
    [ "MapProviderSettings.qml", "MapProviderSettings_8qml.html", null ],
    [ "MavlinkActionSettings.qml", "MavlinkActionSettings_8qml.html", null ],
    [ "MavlinkLinkStatus.qml", "MavlinkLinkStatus_8qml.html", null ],
    [ "MockLink.qml", "MockLink_8qml.html", null ],
    [ "MockLinkSettings.qml", "MockLinkSettings_8qml.html", null ],
    [ "NmeaGpsSettings.qml", "NmeaGpsSettings_8qml.html", null ],
    [ "NtripConnectionStatus.qml", "NtripConnectionStatus_8qml.html", null ],
    [ "NtripMountpointBrowser.qml", "NtripMountpointBrowser_8qml.html", null ],
    [ "NtripServerSettings.qml", "NtripServerSettings_8qml.html", null ],
    [ "OfflineMapEditor.qml", "OfflineMapEditor_8qml.html", null ],
    [ "OfflineMapInfo.qml", "OfflineMapInfo_8qml.html", null ],
    [ "OfflineMapSettings.qml", "OfflineMapSettings_8qml.html", null ],
    [ "PX4LogControl.qml", "PX4LogControl_8qml.html", null ],
    [ "PX4LogFileManager.qml", "PX4LogFileManager_8qml.html", null ],
    [ "PX4LogUploadSettings.qml", "PX4LogUploadSettings_8qml.html", null ],
    [ "QmlTest.qml", "QmlTest_8qml.html", null ],
    [ "RemoteIDGpsLocation.qml", "RemoteIDGpsLocation_8qml.html", null ],
    [ "SerialSettings.qml", "SerialSettings_8qml.html", null ],
    [ "SettingsPage.qml", "SettingsPage_8qml.html", null ],
    [ "TcpSettings.qml", "TcpSettings_8qml.html", null ],
    [ "UdpSettings.qml", "UdpSettings_8qml.html", null ]
];