QGroundControl: src/FirmwarePlugin/FirmwarePlugin.cc File Reference
FirmwarePlugin.cc File Reference
#include "FirmwarePlugin.h"
#include "AutoPilotPlugin.h"
#include "Autotune.h"
#include "GenericAutoPilotPlugin.h"
#include "MAVLinkProtocol.h"
#include "QGCApplication.h"
#include "QGCCameraManager.h"
#include "QGCFileDownload.h"
#include "QGCLoggingCategory.h"
#include "VehicleCameraControl.h"
#include "VehicleComponent.h"
#include <QtCore/QRegularExpression>
#include <QtCore/QThread>
Variables
static const QString guided_mode_not_supported_by_vehicle = QObject::tr("Guided mode not supported by Vehicle.")
Variable Documentation
guided_mode_not_supported_by_vehicle
const QString guided_mode_not_supported_by_vehicle = QObject::tr("Guided mode not supported by Vehicle.") static
Definition at line 18 of file FirmwarePlugin.cc.
Referenced by Vehicle::guidedModeChangeAltitude(), FirmwarePlugin::guidedModeChangeAltitude(), Vehicle::guidedModeChangeEquivalentAirspeedMetersSecond(), FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), Vehicle::guidedModeChangeGroundSpeedMetersSecond(), FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), FirmwarePlugin::guidedModeChangeHeading(), Vehicle::guidedModeGotoLocation(), FirmwarePlugin::guidedModeGotoLocation(), Vehicle::guidedModeLand(), FirmwarePlugin::guidedModeLand(), Vehicle::guidedModeRTL(), FirmwarePlugin::guidedModeRTL(), Vehicle::guidedModeTakeoff(), FirmwarePlugin::guidedModeTakeoff(), FirmwarePlugin::pauseVehicle(), FirmwarePlugin::setGuidedMode(), FirmwarePlugin::startMission(), and FirmwarePlugin::startTakeoff().