QGroundControl: src/VideoManager/VideoReceiver/GStreamer/gstqgc/gstqgcvideosinkbin.cc File Reference
gstqgcvideosinkbin.cc File Reference
#include "gstqgcvideosinkbin.h"
#include "gstqgcelements.h"
#include <gst/gl/gl.h>
Macros
#define GST_CAT_DEFAULT gst_qgc_video_sink_bin_debug
#define DEFAULT_ENABLE_LAST_SAMPLE FALSE
#define DEFAULT_FORCE_ASPECT_RATIO TRUE
#define DEFAULT_PAR_N 0
#define DEFAULT_PAR_D 1
#define DEFAULT_SYNC TRUE
#define DEFAULT_MAX_LATENESS G_GINT64_CONSTANT(-1)
#define PROP_ENABLE_LAST_SAMPLE_NAME "enable-last-sample"
#define PROP_LAST_SAMPLE_NAME "last-sample"
#define PROP_WIDGET_NAME "widget"
#define PROP_FORCE_ASPECT_RATIO_NAME "force-aspect-ratio"
#define PROP_PIXEL_ASPECT_RATIO_NAME "pixel-aspect-ratio"
#define PROP_SYNC_NAME "sync"
#define PROP_MAX_LATENESS_NAME "max-lateness"
#define gst_qgc_video_sink_bin_parent_class parent_class
Enumerations
enum {
PROP_0 , PROP_ENABLE_LAST_SAMPLE , PROP_LAST_SAMPLE , PROP_WIDGET ,
PROP_FORCE_ASPECT_RATIO , PROP_PIXEL_ASPECT_RATIO , PROP_SYNC , PROP_MAX_LATENESS ,
PROP_LAST
}
Functions
GST_DEBUG_CATEGORY_STATIC (gst_qgc_video_sink_bin_debug)
G_DEFINE_TYPE_WITH_CODE (GstQgcVideoSinkBin, gst_qgc_video_sink_bin, GST_TYPE_BIN, GST_DEBUG_CATEGORY_INIT(gst_qgc_video_sink_bin_debug, "qgcsinkbin", 0, "QGC Video Sink Bin"))
GST_ELEMENT_REGISTER_DEFINE_WITH_CODE (qgcvideosinkbin,"qgcvideosinkbin", GST_RANK_NONE,(gst_qgc_video_sink_bin_get_type()), qgc_element_init(plugin))
static void gst_qgc_video_sink_bin_set_property (GObject *object, guint prop_id, const GValue *value, GParamSpec *pspec)
static void gst_qgc_video_sink_bin_get_property (GObject *object, guint prop_id, GValue *value, GParamSpec *pspec)
static void gst_qgc_video_sink_bin_class_init (GstQgcVideoSinkBinClass *klass)
static gboolean gst_qgc_video_sink_bin_ghost_pad (GstQgcVideoSinkBin *self, GstElement *inner)
static void gst_qgc_video_sink_bin_init (GstQgcVideoSinkBin *self)
Variables
static GParamSpec * properties [PROP_LAST]
Macro Definition Documentation
DEFAULT_ENABLE_LAST_SAMPLE
#define DEFAULT_ENABLE_LAST_SAMPLE FALSE
Definition at line 12 of file gstqgcvideosinkbin.cc.
DEFAULT_FORCE_ASPECT_RATIO
#define DEFAULT_FORCE_ASPECT_RATIO TRUE
Definition at line 13 of file gstqgcvideosinkbin.cc.
DEFAULT_MAX_LATENESS
#define DEFAULT_MAX_LATENESS G_GINT64_CONSTANT(-1)
Definition at line 17 of file gstqgcvideosinkbin.cc.
DEFAULT_PAR_D
#define DEFAULT_PAR_D 1
Definition at line 15 of file gstqgcvideosinkbin.cc.
DEFAULT_PAR_N
#define DEFAULT_PAR_N 0
Definition at line 14 of file gstqgcvideosinkbin.cc.
DEFAULT_SYNC
#define DEFAULT_SYNC TRUE
Definition at line 16 of file gstqgcvideosinkbin.cc.
GST_CAT_DEFAULT
#define GST_CAT_DEFAULT gst_qgc_video_sink_bin_debug
Definition at line 9 of file gstqgcvideosinkbin.cc.
gst_qgc_video_sink_bin_parent_class
#define gst_qgc_video_sink_bin_parent_class parent_class
Definition at line 42 of file gstqgcvideosinkbin.cc.
PROP_ENABLE_LAST_SAMPLE_NAME
#define PROP_ENABLE_LAST_SAMPLE_NAME "enable-last-sample"
Definition at line 19 of file gstqgcvideosinkbin.cc.
PROP_FORCE_ASPECT_RATIO_NAME
#define PROP_FORCE_ASPECT_RATIO_NAME "force-aspect-ratio"
Definition at line 22 of file gstqgcvideosinkbin.cc.
PROP_LAST_SAMPLE_NAME
#define PROP_LAST_SAMPLE_NAME "last-sample"
Definition at line 20 of file gstqgcvideosinkbin.cc.
PROP_MAX_LATENESS_NAME
#define PROP_MAX_LATENESS_NAME "max-lateness"
Definition at line 25 of file gstqgcvideosinkbin.cc.
PROP_PIXEL_ASPECT_RATIO_NAME
#define PROP_PIXEL_ASPECT_RATIO_NAME "pixel-aspect-ratio"
Definition at line 23 of file gstqgcvideosinkbin.cc.
PROP_SYNC_NAME
#define PROP_SYNC_NAME "sync"
Definition at line 24 of file gstqgcvideosinkbin.cc.
PROP_WIDGET_NAME
#define PROP_WIDGET_NAME "widget"
Definition at line 21 of file gstqgcvideosinkbin.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ENABLE_LAST_SAMPLE
PROP_LAST_SAMPLE
PROP_WIDGET
PROP_FORCE_ASPECT_RATIO
PROP_PIXEL_ASPECT_RATIO
PROP_SYNC
PROP_MAX_LATENESS
PROP_LAST
Definition at line 27 of file gstqgcvideosinkbin.cc.
Function Documentation
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (GstQgcVideoSinkBin , gst_qgc_video_sink_bin , GST_TYPE_BIN , GST_DEBUG_CATEGORY_INIT(gst_qgc_video_sink_bin_debug, "qgcsinkbin", 0, "QGC Video Sink Bin"))
GST_DEBUG_CATEGORY_STATIC()
GST_DEBUG_CATEGORY_STATIC (gst_qgc_video_sink_bin_debug)
GST_ELEMENT_REGISTER_DEFINE_WITH_CODE()
GST_ELEMENT_REGISTER_DEFINE_WITH_CODE (qgcvideosinkbin , "qgcvideosinkbin" , GST_RANK_NONE , (gst_qgc_video_sink_bin_get_type()) , qgc_element_init(plugin))
gst_qgc_video_sink_bin_class_init()
static void gst_qgc_video_sink_bin_class_init (GstQgcVideoSinkBinClass * klass) static
Definition at line 62 of file gstqgcvideosinkbin.cc.
References DEFAULT_ENABLE_LAST_SAMPLE, DEFAULT_FORCE_ASPECT_RATIO, DEFAULT_MAX_LATENESS, DEFAULT_PAR_D, DEFAULT_PAR_N, DEFAULT_SYNC, gst_qgc_video_sink_bin_get_property(), gst_qgc_video_sink_bin_set_property(), PROP_ENABLE_LAST_SAMPLE, PROP_FORCE_ASPECT_RATIO, PROP_LAST, PROP_LAST_SAMPLE, PROP_MAX_LATENESS, PROP_PIXEL_ASPECT_RATIO, PROP_SYNC, PROP_WIDGET, and properties.
gst_qgc_video_sink_bin_get_property()
static void gst_qgc_video_sink_bin_get_property (GObject * object, guint prop_id, GValue * value, GParamSpec * pspec) static
Definition at line 325 of file gstqgcvideosinkbin.cc.
References DEFAULT_MAX_LATENESS, PROP_ENABLE_LAST_SAMPLE, PROP_ENABLE_LAST_SAMPLE_NAME, PROP_FORCE_ASPECT_RATIO, PROP_FORCE_ASPECT_RATIO_NAME, PROP_LAST_SAMPLE, PROP_LAST_SAMPLE_NAME, PROP_MAX_LATENESS, PROP_MAX_LATENESS_NAME, PROP_PIXEL_ASPECT_RATIO, PROP_PIXEL_ASPECT_RATIO_NAME, PROP_SYNC, PROP_SYNC_NAME, PROP_WIDGET, and PROP_WIDGET_NAME.
Referenced by gst_qgc_video_sink_bin_class_init().
gst_qgc_video_sink_bin_ghost_pad()
static gboolean gst_qgc_video_sink_bin_ghost_pad (GstQgcVideoSinkBin * self, GstElement * inner) static
Definition at line 131 of file gstqgcvideosinkbin.cc.
Referenced by gst_qgc_video_sink_bin_init().
gst_qgc_video_sink_bin_init()
static void gst_qgc_video_sink_bin_init (GstQgcVideoSinkBin * self) static
Definition at line 155 of file gstqgcvideosinkbin.cc.
References gst_qgc_video_sink_bin_ghost_pad(), and PROP_ENABLE_LAST_SAMPLE_NAME.
gst_qgc_video_sink_bin_set_property()
static void gst_qgc_video_sink_bin_set_property (GObject * object, guint prop_id, const GValue * value, GParamSpec * pspec) static
Definition at line 252 of file gstqgcvideosinkbin.cc.
References PROP_ENABLE_LAST_SAMPLE, PROP_ENABLE_LAST_SAMPLE_NAME, PROP_FORCE_ASPECT_RATIO, PROP_FORCE_ASPECT_RATIO_NAME, PROP_MAX_LATENESS, PROP_MAX_LATENESS_NAME, PROP_PIXEL_ASPECT_RATIO, PROP_PIXEL_ASPECT_RATIO_NAME, PROP_SYNC, PROP_SYNC_NAME, PROP_WIDGET, and PROP_WIDGET_NAME.
Referenced by gst_qgc_video_sink_bin_class_init().
Variable Documentation
properties
GParamSpec* properties[PROP_LAST] static
Definition at line 40 of file gstqgcvideosinkbin.cc.
Referenced by gst_qgc_video_sink_bin_class_init().