QGroundControl: src/Joystick/JoystickManager.cc File Reference
JoystickManager.cc File Reference
#include "JoystickManager.h"
#include "Joystick.h"
#include "Vehicle.h"
#include "MultiVehicleManager.h"
#include "SettingsManager.h"
#include "JoystickManagerSettings.h"
#include "JoystickSDL.h"
#include "SDLJoystick.h"
#include "QGCLoggingCategory.h"
#include <QtCore/QApplicationStatic>
#include <QtCore/QSettings>
#include <QtGui/QVector3D>
Typedefs
using JoystickBackend = JoystickSDL
Functions
Q_APPLICATION_STATIC (JoystickManager, _joystickManager)
Typedef Documentation
JoystickBackend
using JoystickBackend = JoystickSDL
Definition at line 15 of file JoystickManager.cc.
Function Documentation
Q_APPLICATION_STATIC()
Q_APPLICATION_STATIC (JoystickManager , _joystickManager)
References MultiVehicleManager::activeVehicleChanged(), AndroidEvents::instance(), SDLJoystick::pumpEvents(), Fact::rawValueChanged(), and AndroidEvents::resumed().