QGroundControl: src/MAVLink/MAVLinkMessageType.h File Reference
MAVLinkMessageType.h File Reference
#include <stdint.h>
#include <mavlink_types.h>
Macros
#define HAVE_MAVLINK_CHANNEL_T
#define MAVLINK_COMM_NUM_BUFFERS 16
#define MAVLINK_MAX_SIGNING_STREAMS MAVLINK_COMM_NUM_BUFFERS
#define MAVLINK_EXTERNAL_RX_STATUS
#define MAVLINK_GET_CHANNEL_STATUS
Enumerations
enum mavlink_channel_t : uint8_t {
MAVLINK_COMM_0 , MAVLINK_COMM_1 , MAVLINK_COMM_2 , MAVLINK_COMM_3 ,
MAVLINK_COMM_4 , MAVLINK_COMM_5 , MAVLINK_COMM_6 , MAVLINK_COMM_7 ,
MAVLINK_COMM_8 , MAVLINK_COMM_9 , MAVLINK_COMM_10 , MAVLINK_COMM_11 ,
MAVLINK_COMM_12 , MAVLINK_COMM_13 , MAVLINK_COMM_14 , MAVLINK_COMM_15
}
Functions
mavlink_status_t * mavlink_get_channel_status (uint8_t chan)
Variables
mavlink_status_t m_mavlink_status [16]
Macro Definition Documentation
HAVE_MAVLINK_CHANNEL_T
#define HAVE_MAVLINK_CHANNEL_T
Lightweight header providing only MAVLink base types (mavlink_message_t, mavlink_status_t, mavlink_channel_t, etc.) WITHOUT pulling in the full dialect message definitions.
Use this instead of MAVLinkLib.h in headers that only reference mavlink_message_t in function signatures. This avoids moc parsing ~118k lines of MAVLink message pack/unpack code.
Definition at line 11 of file MAVLinkMessageType.h.
MAVLINK_COMM_NUM_BUFFERS
#define MAVLINK_COMM_NUM_BUFFERS 16
Definition at line 33 of file MAVLinkMessageType.h.
MAVLINK_EXTERNAL_RX_STATUS
#define MAVLINK_EXTERNAL_RX_STATUS
Definition at line 38 of file MAVLinkMessageType.h.
MAVLINK_GET_CHANNEL_STATUS
#define MAVLINK_GET_CHANNEL_STATUS
Definition at line 43 of file MAVLinkMessageType.h.
MAVLINK_MAX_SIGNING_STREAMS
#define MAVLINK_MAX_SIGNING_STREAMS MAVLINK_COMM_NUM_BUFFERS
Definition at line 34 of file MAVLinkMessageType.h.
Enumeration Type Documentation
mavlink_channel_t
enum mavlink_channel_t : uint8_t
Enumerator
MAVLINK_COMM_0
MAVLINK_COMM_1
MAVLINK_COMM_2
MAVLINK_COMM_3
MAVLINK_COMM_4
MAVLINK_COMM_5
MAVLINK_COMM_6
MAVLINK_COMM_7
MAVLINK_COMM_8
MAVLINK_COMM_9
MAVLINK_COMM_10
MAVLINK_COMM_11
MAVLINK_COMM_12
MAVLINK_COMM_13
MAVLINK_COMM_14
MAVLINK_COMM_15
Definition at line 13 of file MAVLinkMessageType.h.
Function Documentation
mavlink_get_channel_status()
mavlink_status_t * mavlink_get_channel_status (uint8_t chan) extern
Definition at line 51 of file QGCMAVLink.cc.
References QGCMAVLink::isValidChannel(), m_mavlink_status, and MAVLINK_COMM_NUM_BUFFERS.
Referenced by QGCMAVLink::getChannelStatus(), and MAVLinkSigning::initSigning().
Variable Documentation
m_mavlink_status
mavlink_status_t m_mavlink_status[16] extern
Definition at line 47 of file QGCMAVLink.cc.
Referenced by mavlink_get_channel_status().