QGroundControl: MAVLinkSigning Namespace Reference
MAVLinkSigning Namespace Reference
Functions
bool secureConnectionAcceptUnsignedCallback (const mavlink_status_t *status, uint32_t message_id)
bool insecureConnectionAcceptUnsignedCallback (const mavlink_status_t *status, uint32_t message_id)
bool initSigning (mavlink_channel_t channel, QByteArrayView key, mavlink_accept_unsigned_t callback)
bool checkSigningLinkId (mavlink_channel_t channel, const mavlink_message_t &message)
void createSetupSigning (mavlink_channel_t channel, mavlink_system_t target_system, QByteArrayView keyBytes, mavlink_setup_signing_t &setup_signing)
Create a SETUP_SIGNING payload using the given key bytes directly.
bool isSigningEnabled (mavlink_channel_t channel)
void createDisableSigning (mavlink_system_t target_system, mavlink_setup_signing_t &setup_signing)
bool isMessageSigned (const mavlink_message_t &message)
Returns true if the message has a MAVLink2 signature.
bool verifySignature (QByteArrayView key, const mavlink_message_t &message)
Verify a key against a signed message's signature.
QString tryDetectKey (mavlink_channel_t channel, const mavlink_message_t &message)
Function Documentation
checkSigningLinkId()
bool MAVLinkSigning::checkSigningLinkId (mavlink_channel_t channel, const mavlink_message_t & message)
Definition at line 112 of file MAVLinkSigning.cc.
createDisableSigning()
void MAVLinkSigning::createDisableSigning (mavlink_system_t target_system, mavlink_setup_signing_t & setup_signing)
Definition at line 147 of file MAVLinkSigning.cc.
Referenced by Vehicle::sendDisableSigning().
createSetupSigning()
void MAVLinkSigning::createSetupSigning (mavlink_channel_t channel, mavlink_system_t target_system, QByteArrayView keyBytes, mavlink_setup_signing_t & setup_signing)
Create a SETUP_SIGNING payload using the given key bytes directly.
Definition at line 123 of file MAVLinkSigning.cc.
Referenced by Vehicle::sendSetupSigning().
initSigning()
bool MAVLinkSigning::initSigning (mavlink_channel_t channel, QByteArrayView key, mavlink_accept_unsigned_t callback)
Initialize the signing for a channel, both incoming and outgoing If key is empty signing will be turned off for channel
Definition at line 76 of file MAVLinkSigning.cc.
References MAVLINK_COMM_NUM_BUFFERS, and mavlink_get_channel_status().
Referenced by LinkInterface::initMavlinkSigning(), Vehicle::sendDisableSigning(), Vehicle::sendSetupSigning(), and tryDetectKey().
insecureConnectionAcceptUnsignedCallback()
bool MAVLinkSigning::insecureConnectionAcceptUnsignedCallback (const mavlink_status_t * status, uint32_t message_id)
Definition at line 65 of file MAVLinkSigning.cc.
Referenced by Vehicle::sendSetupSigning(), and tryDetectKey().
isMessageSigned()
bool MAVLinkSigning::isMessageSigned (const mavlink_message_t & message)
Returns true if the message has a MAVLink2 signature.
Definition at line 154 of file MAVLinkSigning.cc.
Referenced by tryDetectKey().
isSigningEnabled()
bool MAVLinkSigning::isSigningEnabled (mavlink_channel_t channel)
Definition at line 141 of file MAVLinkSigning.cc.
Referenced by tryDetectKey().
secureConnectionAcceptUnsignedCallback()
bool MAVLinkSigning::secureConnectionAcceptUnsignedCallback (const mavlink_status_t * status, uint32_t message_id)
Definition at line 57 of file MAVLinkSigning.cc.
tryDetectKey()
QString MAVLinkSigning::tryDetectKey (mavlink_channel_t channel, const mavlink_message_t & message)
Try all stored signing keys against a signed message. If a match is found, configure signing on the channel with that key. Returns the matching key name, or empty string if no match.
Definition at line 185 of file MAVLinkSigning.cc.
References initSigning(), insecureConnectionAcceptUnsignedCallback(), isMessageSigned(), isSigningEnabled(), and verifySignature().
verifySignature()
bool MAVLinkSigning::verifySignature (QByteArrayView key, const mavlink_message_t & message)
Verify a key against a signed message's signature.
Definition at line 159 of file MAVLinkSigning.cc.
Referenced by tryDetectKey().