QGroundControl: QGC Namespace Reference
QGC Namespace Reference
Functions
float limitAngleToPMPIf (double angle)
double limitAngleToPMPId (double angle)
quint32 crc32 (const quint8 *src, unsigned len, unsigned state)
bool fuzzyCompare (double value1, double value2)
Returns true if the two values are equal or close. Correctly handles 0 and NaN values.
bool fuzzyCompare (double value1, double value2, double tolerance)
bool fuzzyCompare (float value1, float value2)
bool fuzzyCompare (float value1, float value2, float tolerance)
QString numberToString (quint64 number)
Locale-aware decimal integer formatting (e.g. "1,234,567").
QString bigSizeToString (quint64 size)
Locale-aware byte-size with unit: B, KB, MB, GB, TB. 1 fractional digit above 1 KB.
QString bigSizeMBToString (quint64 sizeMB)
Locale-aware size scaled to MB, GB, or TB. Input is in MB.
void showAppMessage (const QString &message, const QString &title=QString())
Show a modal application message. Queued if the UI isn't ready yet.
void showCriticalVehicleMessage (const QString &message)
void showRebootAppMessage (const QString &message, const QString &title=QString())
Show a modal reboot-required message. Debounced within 2 minutes.
bool runningUnitTests ()
True if the app is running in unit-test mode. Returns false if qgcApp() doesn't exist yet.
Variables
static const quint32 crctab []
Function Documentation
bigSizeMBToString()
QString QGC::bigSizeMBToString (quint64 sizeMB)
Locale-aware size scaled to MB, GB, or TB. Input is in MB.
Definition at line 192 of file QGC.cc.
Referenced by VehicleCameraControl::storageFreeStr().
bigSizeToString()
QString QGC::bigSizeToString (quint64 size)
Locale-aware byte-size with unit: B, KB, MB, GB, TB. 1 fractional digit above 1 KB.
Definition at line 174 of file QGC.cc.
crc32()
quint32 QGC::crc32 (const quint8 * src, unsigned len, unsigned state)
Definition at line 101 of file QGC.cc.
References crctab.
fuzzyCompare() [1/4]
bool QGC::fuzzyCompare (double value1, double value2)
Returns true if the two values are equal or close. Correctly handles 0 and NaN values.
Definition at line 110 of file QGC.cc.
Referenced by VisualMissionItem::setAltDifference(), VisualMissionItem::setAltPercent(), VisualMissionItem::setAzimuth(), FlightPathSegment::setCoord1AMSLAlt(), FlightPathSegment::setCoord2AMSLAlt(), VisualMissionItem::setDistance(), VisualMissionItem::setDistanceFromStart(), VisualMissionItem::setMissionFlightStatus(), SimpleMissionItem::setMissionFlightStatus(), StructureScanComplexItem::setMissionFlightStatus(), TransectStyleComplexItem::setMissionFlightStatus(), VisualMissionItem::setMissionVehicleYaw(), VisualMissionItem::setTerrainPercent(), and VTOLLandingComplexItem::VTOLLandingComplexItem().
fuzzyCompare() [2/4]
bool QGC::fuzzyCompare (double value1, double value2, double tolerance)
Definition at line 123 of file QGC.cc.
fuzzyCompare() [3/4]
bool QGC::fuzzyCompare (float value1, float value2)
Definition at line 134 of file QGC.cc.
fuzzyCompare() [4/4]
bool QGC::fuzzyCompare (float value1, float value2, float tolerance)
Definition at line 147 of file QGC.cc.
limitAngleToPMPId()
double QGC::limitAngleToPMPId (double angle)
Definition at line 37 of file QGC.cc.
limitAngleToPMPIf()
float QGC::limitAngleToPMPIf (double angle)
Definition at line 14 of file QGC.cc.
numberToString()
QString QGC::numberToString (quint64 number)
Locale-aware decimal integer formatting (e.g. "1,234,567").
Definition at line 169 of file QGC.cc.
Referenced by VehicleCameraControl::batteryRemainingStr().
runningUnitTests()
bool QGC::runningUnitTests ()
True if the app is running in unit-test mode. Returns false if qgcApp() doesn't exist yet.
Definition at line 227 of file QGC.cc.
References qgcApp.
Referenced by FirmwarePlugin::_cachedParameterMetaDataFile(), PlanManager::_startAckTimeout(), AppSettings::AppSettings(), FirmwarePlugin::checkIfIsLatestStable(), FTPManager::FTPManager(), RequestMessageCoordinator::handleReceivedMessage(), PX4AirframeLoader::loadAirframeMetaData(), ParameterManager::ParameterManager(), MockLink::run1HzTasks(), AudioOutput::say(), SettingsFact::SettingsFact(), TransectStyleComplexItem::TransectStyleComplexItem(), and Vehicle::Vehicle().
showAppMessage()
void QGC::showAppMessage (const QString & message, const QString & title)
Show a modal application message. Queued if the UI isn't ready yet.
Definition at line 206 of file QGC.cc.
References qgcApp.
Referenced by PX4FirmwarePlugin::_changeAltAfterPause(), LandingComplexItem::_load(), FirmwarePlugin::_versionFileDownloadFinished(), AppSettings::AppSettings(), ComplexMissionItem::deletePreset(), MissionManager::generateResumeMission(), Vehicle::guidedModeChangeAltitude(), FirmwarePlugin::guidedModeChangeAltitude(), APMFirmwarePlugin::guidedModeChangeAltitude(), ArduRoverFirmwarePlugin::guidedModeChangeAltitude(), PX4FirmwarePlugin::guidedModeChangeAltitude(), Vehicle::guidedModeChangeEquivalentAirspeedMetersSecond(), FirmwarePlugin::guidedModeChangeEquivalentAirspeedMetersSecond(), Vehicle::guidedModeChangeGroundSpeedMetersSecond(), FirmwarePlugin::guidedModeChangeGroundSpeedMetersSecond(), Vehicle::guidedModeChangeHeading(), FirmwarePlugin::guidedModeChangeHeading(), APMFirmwarePlugin::guidedModeChangeHeading(), PX4FirmwarePlugin::guidedModeChangeHeading(), Vehicle::guidedModeGotoLocation(), APMFirmwarePlugin::guidedModeGotoLocation(), PX4FirmwarePlugin::guidedModeGotoLocation(), FirmwarePlugin::guidedModeGotoLocation(), Vehicle::guidedModeLand(), FirmwarePlugin::guidedModeLand(), Vehicle::guidedModeOrbit(), Vehicle::guidedModeROI(), Vehicle::guidedModeRTL(), FirmwarePlugin::guidedModeRTL(), Vehicle::guidedModeTakeoff(), FirmwarePlugin::guidedModeTakeoff(), PX4FirmwarePlugin::guidedModeTakeoff(), PlanMasterController::loadFromArchive(), PlanMasterController::loadFromFile(), PlanMasterController::loadFromVehicle(), QGCMapPolygon::loadKMLOrSHPFile(), QGCMapPolyline::loadKMLOrSHPFile(), ComplexMissionItem::loadPreset(), CorridorScanComplexItem::loadPreset(), SurveyComplexItem::loadPreset(), MAVLinkProtocol::logSentBytes(), MavlinkActionsSettings::MavlinkActionsSettings(), PX4AutoPilotPlugin::parametersReadyPreChecks(), Vehicle::pauseVehicle(), FirmwarePlugin::pauseVehicle(), LinkInterface::reportMavlinkV1Traffic(), ComplexMissionItem::savePreset(), PlanMasterController::saveToFile(), PlanMasterController::saveToKml(), APMFirmwarePlugin::sendGCSMotionReport(), PlanMasterController::sendToVehicle(), MavCommandQueue::sendWorker(), FirmwarePlugin::setGuidedMode(), ShowAppMessageState::ShowAppMessageState(), MavCommandQueue::showCommandAckError(), FirmwarePlugin::startMission(), APMFirmwarePlugin::startMission(), PX4FirmwarePlugin::startMission(), VideoManager::startRecording(), FirmwarePlugin::startTakeoff(), APMFirmwarePlugin::startTakeoff(), PX4FirmwarePlugin::startTakeoff(), Vehicle::stopGuidedModeROI(), SimulatedCameraControl::takePhoto(), and VehicleCameraControl::takePhoto().
showCriticalVehicleMessage()
void QGC::showCriticalVehicleMessage (const QString & message)
Show a non-modal vehicle message. PreArm/preflight messages are routed through the Vehicle path and suppressed here.
Definition at line 213 of file QGC.cc.
References qgcApp.
showRebootAppMessage()
void QGC::showRebootAppMessage (const QString & message, const QString & title)
Show a modal reboot-required message. Debounced within 2 minutes.
Definition at line 220 of file QGC.cc.
References qgcApp.
Variable Documentation
crctab
const quint32 QGC::crctab[] static
Definition at line 65 of file QGC.cc.
Referenced by crc32().