QGroundControl: AndroidInterface Namespace Reference
AndroidInterface Namespace Reference
Classes
class JniLocalRef
Functions
static void jniLogDebug (JNIEnv *, jobject, jstring message)
static void jniLogWarning (JNIEnv *, jobject, jstring message)
static void jniStoragePermissionsResult (JNIEnv *, jobject, jboolean granted)
static void jniOnImportResult (JNIEnv *env, jobject, jstring filePathA)
void setNativeMethods ()
bool checkStoragePermissions ()
QString getSDCardPath ()
void openFileImportDialog (const QString &destPath, std::function< void(const QString &)> callback)
void setKeepScreenOn (bool on)
template<typename... Args>
bool callStaticIntMethod (QJniEnvironment &env, jclass cls, jmethodID method, const char *caller, const QLoggingCategory &logCategory, jint &result, Args... args)
template<typename... Args>
bool callStaticBooleanMethod (QJniEnvironment &env, jclass cls, jmethodID method, const char *caller, const QLoggingCategory &logCategory, jboolean &result, Args... args)
Variables
static std::function< void(const QString &)> s_importCallback
static QSharedPointer< QLocks::QLockBase > s_partialWakeLock
static QSharedPointer< QLocks::QLockBase > s_wifiLock
constexpr const char * kJniQGCActivityClassName = "org/mavlink/qgroundcontrol/QGCActivity"
Function Documentation
callStaticBooleanMethod()
template<typename... Args> bool AndroidInterface::callStaticBooleanMethod (QJniEnvironment & env, jclass cls, jmethodID method, const char * caller, const QLoggingCategory & logCategory, jboolean & result, Args... args) inline
Definition at line 91 of file AndroidInterface.h.
Referenced by AndroidSerial::callBoolMethod(), AndroidSerial::callBoolSetMethod(), AndroidSerial::close(), AndroidSerial::isOpen(), AndroidSerial::purgeBuffers(), AndroidSerial::setFlowControl(), and AndroidSerial::setParameters().
callStaticIntMethod()
template<typename... Args> bool AndroidInterface::callStaticIntMethod (QJniEnvironment & env, jclass cls, jmethodID method, const char * caller, const QLoggingCategory & logCategory, jint & result, Args... args) inline
Definition at line 78 of file AndroidInterface.h.
Referenced by AndroidSerial::getDeviceHandle(), AndroidSerial::getDeviceId(), AndroidSerial::getFlowControl(), and AndroidSerial::open().
checkStoragePermissions()
bool AndroidInterface::checkStoragePermissions ()
Definition at line 120 of file AndroidInterface.cc.
References checkStoragePermissions(), and kJniQGCActivityClassName.
Referenced by checkStoragePermissions(), getSDCardPath(), and Platform::setupPostApp().
getSDCardPath()
QString AndroidInterface::getSDCardPath ()
Definition at line 139 of file AndroidInterface.cc.
References checkStoragePermissions(), getSDCardPath(), and kJniQGCActivityClassName.
Referenced by AppSettings::AppSettings(), getSDCardPath(), and jniStoragePermissionsResult().
jniLogDebug()
static void AndroidInterface::jniLogDebug (JNIEnv * , jobject , jstring message) static
Definition at line 27 of file AndroidInterface.cc.
References jniLogDebug().
Referenced by jniLogDebug(), and setNativeMethods().
jniLogWarning()
static void AndroidInterface::jniLogWarning (JNIEnv * , jobject , jstring message) static
Definition at line 32 of file AndroidInterface.cc.
References jniLogWarning().
Referenced by jniLogWarning(), and setNativeMethods().
jniOnImportResult()
static void AndroidInterface::jniOnImportResult (JNIEnv * env, jobject , jstring filePathA) static
Definition at line 89 of file AndroidInterface.cc.
References jniOnImportResult(), and s_importCallback.
Referenced by jniOnImportResult(), and setNativeMethods().
jniStoragePermissionsResult()
static void AndroidInterface::jniStoragePermissionsResult (JNIEnv * , jobject , jboolean granted) static
Definition at line 37 of file AndroidInterface.cc.
References AppSettings::androidDontSaveToSDCard(), getSDCardPath(), jniStoragePermissionsResult(), qgcApp, and AppSettings::savePath().
Referenced by jniStoragePermissionsResult(), and setNativeMethods().
openFileImportDialog()
void AndroidInterface::openFileImportDialog (const QString & destPath, std::function< void(const QString &)> callback)
Definition at line 161 of file AndroidInterface.cc.
References kJniQGCActivityClassName, openFileImportDialog(), and s_importCallback.
Referenced by QGCFileDialogController::importFromNativePicker(), and openFileImportDialog().
setKeepScreenOn()
void AndroidInterface::setKeepScreenOn (bool on)
Definition at line 185 of file AndroidInterface.cc.
References s_partialWakeLock, s_wifiLock, and setKeepScreenOn().
Referenced by setKeepScreenOn().
setNativeMethods()
void AndroidInterface::setNativeMethods ()
Definition at line 102 of file AndroidInterface.cc.
References jniLogDebug(), jniLogWarning(), jniOnImportResult(), jniStoragePermissionsResult(), kJniQGCActivityClassName, and setNativeMethods().
Referenced by JNI_OnLoad(), and setNativeMethods().
Variable Documentation
kJniQGCActivityClassName
constexpr const char* AndroidInterface::kJniQGCActivityClassName = "org/mavlink/qgroundcontrol/QGCActivity" constexpr
Definition at line 18 of file AndroidInterface.h.
Referenced by checkStoragePermissions(), getSDCardPath(), jniSetNativeMethods(), openFileImportDialog(), and setNativeMethods().
s_importCallback
std::function<void(const QString&)> AndroidInterface::s_importCallback static
Definition at line 25 of file AndroidInterface.cc.
Referenced by jniOnImportResult(), and openFileImportDialog().
s_partialWakeLock
QSharedPointer<QLocks::QLockBase> AndroidInterface::s_partialWakeLock static
Definition at line 182 of file AndroidInterface.cc.
Referenced by setKeepScreenOn().
s_wifiLock
QSharedPointer<QLocks::QLockBase> AndroidInterface::s_wifiLock static
Definition at line 183 of file AndroidInterface.cc.
Referenced by setKeepScreenOn().