QGroundControl: DataFlashParser Namespace Reference
DataFlashParser Namespace Reference
Functions
bool getTagsFromLog (const char *data, qint64 size, QList< GeoTagData > &cameraFeedback, QString &errorMessage)
bool getTagsFromLog (const QByteArray &logBuffer, QList< GeoTagData > &cameraFeedback, QString &errorMessage)
Detailed Description
Parser for ArduPilot DataFlash binary logs (.bin files) Extracts camera trigger events (CAM messages) with GPS coordinates
Function Documentation
getTagsFromLog() [1/2]
bool DataFlashParser::getTagsFromLog (const char * data, qint64 size, QList< GeoTagData > & cameraFeedback, QString & errorMessage)
Parse DataFlash log from raw memory and extract camera capture events
Parameters
data Pointer to the binary log data (can be memory-mapped)
size Size of the data in bytes
cameraFeedback Output list of camera capture events
errorMessage Output error message if parsing fails
Returns
true if parsing succeeded
Definition at line 80 of file DataFlashParser.cc.
References GeoTagData::coordinate, getTagsFromLog(), DataFlashUtility::isValidHeader(), DataFlashUtility::iterateMessages(), DataFlashUtility::parseFmtMessages(), and DataFlashUtility::parseMessage().
Referenced by getTagsFromLog(), and getTagsFromLog().
getTagsFromLog() [2/2]
bool DataFlashParser::getTagsFromLog (const QByteArray & logBuffer, QList< GeoTagData > & cameraFeedback, QString & errorMessage) inline
Parse DataFlash log and extract camera capture events
Parameters
logBuffer The binary log file contents
cameraFeedback Output list of camera capture events
errorMessage Output error message if parsing fails
Returns
true if parsing succeeded
Definition at line 30 of file DataFlashParser.h.
References getTagsFromLog().