QGroundControl: GStreamer Namespace Reference
GStreamer Namespace Reference
Enumerations
enum VideoDecoderOptions {
ForceVideoDecoderDefault = 0 , ForceVideoDecoderSoftware , ForceVideoDecoderNVIDIA , ForceVideoDecoderVAAPI ,
ForceVideoDecoderDirectX3D , ForceVideoDecoderVideoToolbox , ForceVideoDecoderIntel , ForceVideoDecoderVulkan ,
ForceVideoDecoderHardware
}
Functions
void _registerPlugins ()
void _qtGstLog (GstDebugCategory *category, GstDebugLevel level, const gchar *file, const gchar *function, gint line, GObject *object, GstDebugMessage *message, gpointer data)
void _setGstEnvVars ()
void _logPlugin (gpointer data, gpointer)
bool _verifyPlugins ()
void _logDecoderRanks ()
void _lowerSoftwareDecoderRanks (GstRegistry *registry)
void _changeFeatureRank (GstRegistry *registry, const char *featureName, uint16_t rank)
void _prioritizeByHardwareClass (GstRegistry *registry, uint16_t prioritizedRank, bool requireHardware)
void _setCodecPriorities (GStreamer::VideoDecoderOptions option)
bool initialize ()
void * createVideoSink (QQuickItem *widget, QObject *)
void releaseVideoSink (void *sink)
VideoReceiver * createVideoReceiver (QObject *parent)
gboolean is_valid_rtsp_uri (const gchar *uri_str)
bool is_hardware_decoder_factory (GstElementFactory *factory)
Enumeration Type Documentation
VideoDecoderOptions
enum GStreamer::VideoDecoderOptions
Enumerator
ForceVideoDecoderDefault
ForceVideoDecoderSoftware
ForceVideoDecoderNVIDIA
ForceVideoDecoderVAAPI
ForceVideoDecoderDirectX3D
ForceVideoDecoderVideoToolbox
ForceVideoDecoderIntel
ForceVideoDecoderVulkan
ForceVideoDecoderHardware
Definition at line 14 of file GStreamer.h.
Function Documentation
_changeFeatureRank()
void GStreamer::_changeFeatureRank (GstRegistry * registry, const char * featureName, uint16_t rank)
Definition at line 360 of file GStreamer.cc.
References _changeFeatureRank().
Referenced by _changeFeatureRank(), _prioritizeByHardwareClass(), and _setCodecPriorities().
_logDecoderRanks()
void GStreamer::_logDecoderRanks ()
Definition at line 277 of file GStreamer.cc.
References _logDecoderRanks().
Referenced by _logDecoderRanks(), and initialize().
_logPlugin()
void GStreamer::_logPlugin (gpointer data, gpointer)
Definition at line 221 of file GStreamer.cc.
References _logPlugin().
Referenced by _logPlugin(), and _verifyPlugins().
_lowerSoftwareDecoderRanks()
void GStreamer::_lowerSoftwareDecoderRanks (GstRegistry * registry)
Definition at line 337 of file GStreamer.cc.
References _lowerSoftwareDecoderRanks().
Referenced by _lowerSoftwareDecoderRanks(), and _prioritizeByHardwareClass().
_prioritizeByHardwareClass()
void GStreamer::_prioritizeByHardwareClass (GstRegistry * registry, uint16_t prioritizedRank, bool requireHardware)
Definition at line 377 of file GStreamer.cc.
References _changeFeatureRank(), _lowerSoftwareDecoderRanks(), _prioritizeByHardwareClass(), and is_hardware_decoder_factory().
Referenced by _prioritizeByHardwareClass(), and _setCodecPriorities().
_qtGstLog()
void GStreamer::_qtGstLog (GstDebugCategory * category, GstDebugLevel level, const gchar * file, const gchar * function, gint line, GObject * object, GstDebugMessage * message, gpointer data)
Definition at line 124 of file GStreamer.cc.
References _qtGstLog().
Referenced by _qtGstLog(), and initialize().
_registerPlugins()
void GStreamer::_registerPlugins ()
Definition at line 59 of file GStreamer.cc.
References _registerPlugins().
Referenced by _registerPlugins(), and initialize().
_setCodecPriorities()
void GStreamer::_setCodecPriorities (GStreamer::VideoDecoderOptions option)
Definition at line 430 of file GStreamer.cc.
References _changeFeatureRank(), _prioritizeByHardwareClass(), _setCodecPriorities(), ForceVideoDecoderDefault, ForceVideoDecoderDirectX3D, ForceVideoDecoderHardware, ForceVideoDecoderIntel, ForceVideoDecoderNVIDIA, ForceVideoDecoderSoftware, ForceVideoDecoderVAAPI, ForceVideoDecoderVideoToolbox, and ForceVideoDecoderVulkan.
Referenced by _setCodecPriorities(), and initialize().
_setGstEnvVars()
void GStreamer::_setGstEnvVars ()
Definition at line 169 of file GStreamer.cc.
References _setGstEnvVars().
Referenced by _setGstEnvVars(), and initialize().
_verifyPlugins()
bool GStreamer::_verifyPlugins ()
Definition at line 233 of file GStreamer.cc.
References _logPlugin(), and _verifyPlugins().
Referenced by _verifyPlugins(), and initialize().
createVideoReceiver()
VideoReceiver * GStreamer::createVideoReceiver (QObject * parent)
Definition at line 572 of file GStreamer.cc.
References createVideoReceiver().
Referenced by createVideoReceiver().
createVideoSink()
void * GStreamer::createVideoSink (QQuickItem * widget, QObject *)
Definition at line 552 of file GStreamer.cc.
References createVideoSink().
Referenced by createVideoSink().
initialize()
bool GStreamer::initialize ()
Definition at line 490 of file GStreamer.cc.
References _logDecoderRanks(), _qtGstLog(), _registerPlugins(), _setCodecPriorities(), _setGstEnvVars(), _verifyPlugins(), error, and AppSettings::gstDebugLevelName.
is_hardware_decoder_factory()
bool GStreamer::is_hardware_decoder_factory (GstElementFactory * factory)
Definition at line 29 of file GStreamerHelpers.cc.
Referenced by _prioritizeByHardwareClass().
is_valid_rtsp_uri()
gboolean GStreamer::is_valid_rtsp_uri (const gchar * uri_str)
Definition at line 11 of file GStreamerHelpers.cc.
releaseVideoSink()
void GStreamer::releaseVideoSink (void * sink)
Definition at line 566 of file GStreamer.cc.
References releaseVideoSink().
Referenced by releaseVideoSink().