QGroundControl: KMLHelper Namespace Reference
KMLHelper Namespace Reference
Functions
QDomDocument _loadFile (const QString &kmlFile, QString &errorString)
bool _parseCoordinateString (const QString &coordinatesString, QList< QGeoCoordinate > &coords, QString &errorString)
void _filterVertices (QList< QGeoCoordinate > &vertices, double filterMeters, int minVertices)
void _checkAltitudeMode (const QDomNode &geometryNode, const QString &geometryType, int index)
ShapeFileHelper::ShapeType determineShapeType (const QString &file, QString &errorString)
int getEntityCount (const QString &kmlFile, QString &errorString)
Get the number of geometry entities in the KML file.
bool loadPolygonsFromFile (const QString &kmlFile, QList< QList< QGeoCoordinate > > &polygons, QString &errorString, double filterMeters=ShapeFileHelper::kDefaultVertexFilterMeters)
bool loadPolylinesFromFile (const QString &kmlFile, QList< QList< QGeoCoordinate > > &polylines, QString &errorString, double filterMeters=ShapeFileHelper::kDefaultVertexFilterMeters)
bool loadPointsFromFile (const QString &kmlFile, QList< QGeoCoordinate > &points, QString &errorString)
Load all point entities.
Variables
constexpr const char * _errorPrefix = QT_TR_NOOP("KML file load failed. %1")
Function Documentation
_checkAltitudeMode()
void KMLHelper::_checkAltitudeMode (const QDomNode & geometryNode, const QString & geometryType, int index)
Definition at line 111 of file KMLHelper.cc.
References KMLSchemaValidator::instance().
Referenced by loadPointsFromFile(), loadPolygonsFromFile(), and loadPolylinesFromFile().
_filterVertices()
void KMLHelper::_filterVertices (QList< QGeoCoordinate > & vertices, double filterMeters, int minVertices)
Definition at line 95 of file KMLHelper.cc.
Referenced by loadPolygonsFromFile(), and loadPolylinesFromFile().
_loadFile()
QDomDocument KMLHelper::_loadFile (const QString & kmlFile, QString & errorString)
Definition at line 22 of file KMLHelper.cc.
References errorString.
Referenced by determineShapeType(), getEntityCount(), loadPointsFromFile(), loadPolygonsFromFile(), and loadPolylinesFromFile().
_parseCoordinateString()
bool KMLHelper::_parseCoordinateString (const QString & coordinatesString, QList< QGeoCoordinate > & coords, QString & errorString)
Definition at line 47 of file KMLHelper.cc.
References errorString.
Referenced by loadPointsFromFile(), loadPolygonsFromFile(), and loadPolylinesFromFile().
determineShapeType()
ShapeFileHelper::ShapeType KMLHelper::determineShapeType (const QString & file, QString & errorString)
Definition at line 133 of file KMLHelper.cc.
References _loadFile(), and errorString.
getEntityCount()
int KMLHelper::getEntityCount (const QString & kmlFile, QString & errorString)
Get the number of geometry entities in the KML file.
Definition at line 161 of file KMLHelper.cc.
References _loadFile(), and errorString.
loadPointsFromFile()
bool KMLHelper::loadPointsFromFile (const QString & kmlFile, QList< QGeoCoordinate > & points, QString & errorString)
Load all point entities.
Definition at line 298 of file KMLHelper.cc.
References _checkAltitudeMode(), _loadFile(), _parseCoordinateString(), and errorString.
loadPolygonsFromFile()
bool KMLHelper::loadPolygonsFromFile (const QString & kmlFile, QList< QList< QGeoCoordinate > > & polygons, QString & errorString, double filterMeters = ShapeFileHelper::kDefaultVertexFilterMeters)
Load all polygon entities
Parameters
filterMeters Filter vertices closer than this distance (0 to disable)
Definition at line 175 of file KMLHelper.cc.
References _checkAltitudeMode(), _filterVertices(), _loadFile(), _parseCoordinateString(), and errorString.
loadPolylinesFromFile()
bool KMLHelper::loadPolylinesFromFile (const QString & kmlFile, QList< QList< QGeoCoordinate > > & polylines, QString & errorString, double filterMeters = ShapeFileHelper::kDefaultVertexFilterMeters)
Load all polyline entities
Parameters
filterMeters Filter vertices closer than this distance (0 to disable)
Definition at line 245 of file KMLHelper.cc.
References _checkAltitudeMode(), _filterVertices(), _loadFile(), _parseCoordinateString(), and errorString.
Variable Documentation
_errorPrefix
constexpr const char* KMLHelper::_errorPrefix = QT_TR_NOOP("KML file load failed. %1") constexpr
Definition at line 19 of file KMLHelper.cc.