QGroundControl: ULogParser Namespace Reference
ULogParser Namespace Reference
Functions
GeoTagData parseGeoTagData (const ulog_cpp::TypedDataView &sample)
bool getTagsFromLog (const char *data, qint64 size, QList< GeoTagData > &cameraFeedback, QString &errorMessage)
bool getTagsFromLog (const QByteArray &log, QList< GeoTagData > &cameraFeedback, QString &errorMessage)
Function Documentation
getTagsFromLog() [1/2]
bool ULogParser::getTagsFromLog (const char * data, qint64 size, QList< GeoTagData > & cameraFeedback, QString & errorMessage)
Get GeoTags from a ULog using streamed parsing (raw memory version)
Parameters
data Pointer to the ULog data (can be memory-mapped)
size Size of the data in bytes
cameraFeedback Output list of camera capture events
errorMessage Output error message if parsing fails
Returns
true on success, false on failure with errorMessage set
Definition at line 57 of file ULogParser.cc.
References ULogUtility::iterateMessages(), and parseGeoTagData().
Referenced by getTagsFromLog().
getTagsFromLog() [2/2]
bool ULogParser::getTagsFromLog (const QByteArray & log, QList< GeoTagData > & cameraFeedback, QString & errorMessage) inline
Get GeoTags from a ULog using streamed parsing (QByteArray version)
Returns
true on success, false on failure with errorMessage set
Definition at line 31 of file ULogParser.h.
References getTagsFromLog().
parseGeoTagData()
GeoTagData ULogParser::parseGeoTagData (const ulog_cpp::TypedDataView & sample)
Parse a TypedDataView sample into GeoTagData
Parameters
sample The typed data view from a camera_capture message
Returns
Populated GeoTagData structure
Definition at line 11 of file ULogParser.cc.
References GeoTagData::attitude, GeoTagData::captureResult, GeoTagData::coordinate, GeoTagData::groundDistance, GeoTagData::imageSequence, parseGeoTagData(), GeoTagData::Success, GeoTagData::timestamp, and GeoTagData::timestampUTC.
Referenced by getTagsFromLog(), and parseGeoTagData().