QGroundControl: ExifParser Namespace Reference
ExifParser Namespace Reference
Functions
QDateTime readTime (const QByteArray &buffer)
bool write (QByteArray &buffer, const GeoTagData &geotag)
Function Documentation
readTime()
QDateTime ExifParser::readTime (const QByteArray & buffer)
Definition at line 13 of file ExifParser.cc.
References ExifUtility::loadFromBuffer(), ExifUtility::readString(), and readTime().
Referenced by readTime().
write()
bool ExifParser::write (QByteArray & buffer, const GeoTagData & geotag)
Definition at line 32 of file ExifParser.cc.
References GeoTagData::coordinate, ExifUtility::createNew(), ExifUtility::createTag(), ExifUtility::loadFromBuffer(), ExifUtility::saveToBuffer(), write(), ExifUtility::writeGpsAltRef(), ExifUtility::writeGpsCoordinate(), ExifUtility::writeGpsRef(), and ExifUtility::writeRational().
Referenced by write().