QGroundControl: src/Camera/QGCCameraManager.cc File Reference
QGCCameraManager.cc File Reference
#include "QGCCameraManager.h"
#include "CameraMetaData.h"
#include "FirmwarePlugin.h"
#include "Joystick.h"
#include "JoystickManager.h"
#include "MavlinkCameraControl.h"
#include "MultiVehicleManager.h"
#include "QGCLoggingCategory.h"
#include "QGCVideoStreamInfo.h"
#include "SimulatedCameraControl.h"
#include <cmath>
#include "GimbalControllerSettings.h"
#include "SettingsManager.h"
#include <numbers>
Functions
static void _requestFovOnZoom_Handler (void *user, MAV_RESULT result, Vehicle::RequestMessageResultHandlerFailureCode_t failureCode, const mavlink_message_t &message)
static void _handleCameraInfoRetry (QGCCameraManager::CameraStruct *cameraInfo)
static void _requestCameraInfoCommandResultHandler (void *resultHandlerData, int, const mavlink_command_ack_t &ack, Vehicle::MavCmdResultFailureCode_t failureCode)
static void _requestCameraInfoMessageResultHandler (void *resultHandlerData, MAV_RESULT result, Vehicle::RequestMessageResultHandlerFailureCode_t failureCode, const mavlink_message_t &message)
static void _requestCameraInfoHelper (QGCCameraManager *manager, QGCCameraManager::CameraStruct *pInfo)
Variables
constexpr double kPi = std::numbers::pi_v<double>
Function Documentation
_handleCameraInfoRetry()
static void _handleCameraInfoRetry (QGCCameraManager::CameraStruct * cameraInfo) static
Definition at line 556 of file QGCCameraManager.cc.
References _requestCameraInfoHelper(), and QGCMAVLink::compIdToString().
Referenced by _requestCameraInfoCommandResultHandler(), and _requestCameraInfoMessageResultHandler().
_requestCameraInfoCommandResultHandler()
static void _requestCameraInfoCommandResultHandler (void * resultHandlerData, int , const mavlink_command_ack_t & ack, Vehicle::MavCmdResultFailureCode_t failureCode) static
Definition at line 505 of file QGCCameraManager.cc.
References _handleCameraInfoRetry(), QGCMAVLink::compIdToString(), Vehicle::mavCmdResultFailureCodeToString(), and QGCMAVLink::mavResultToString().
Referenced by _requestCameraInfoHelper().
_requestCameraInfoHelper()
static void _requestCameraInfoHelper (QGCCameraManager * manager, QGCCameraManager::CameraStruct * pInfo) static
Definition at line 531 of file QGCCameraManager.cc.
References _requestCameraInfoCommandResultHandler(), _requestCameraInfoMessageResultHandler(), QGCMAVLink::compIdToString(), Vehicle::requestMessage(), and Vehicle::MavCmdAckHandlerInfo_s::resultHandler.
Referenced by _handleCameraInfoRetry().
_requestCameraInfoMessageResultHandler()
static void _requestCameraInfoMessageResultHandler (void * resultHandlerData, MAV_RESULT result, Vehicle::RequestMessageResultHandlerFailureCode_t failureCode, const mavlink_message_t & message) static
Definition at line 518 of file QGCCameraManager.cc.
References _handleCameraInfoRetry(), QGCMAVLink::compIdToString(), QGCMAVLink::mavResultToString(), and Vehicle::requestMessageResultHandlerFailureCodeToString().
Referenced by _requestCameraInfoHelper().
_requestFovOnZoom_Handler()
static void _requestFovOnZoom_Handler (void * user, MAV_RESULT result, Vehicle::RequestMessageResultHandlerFailureCode_t failureCode, const mavlink_message_t & message) static
Definition at line 29 of file QGCCameraManager.cc.
Variable Documentation
kPi
constexpr double kPi = std::numbers::pi_v<double> constexpr
Definition at line 17 of file QGCCameraManager.cc.