QGroundControl: src/QtLocationPlugin/QGCTileCacheDatabase.cpp File Reference
QGCTileCacheDatabase.cpp File Reference
#include "QGCTileCacheDatabase.h"
#include <QtCore/QCoreApplication>
#include <QtCore/QDateTime>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QSettings>
#include <QtCore/QUuid>
#include <QtSql/QSqlDatabase>
#include <QtSql/QSqlError>
#include <QtSql/QSqlQuery>
#include <atomic>
#include "QGCCacheTile.h"
#include "QGCLoggingCategory.h"
#include "QGCMapUrlEngine.h"
#include "QGCTile.h"
Classes
class TransactionGuard
struct ScopedExportDB
Functions
static QString placeholders (int n)
Variables
static std::atomic< int > s_exportSessionCounter {0}
static std::atomic< quint64 > s_connectionCounter {0}
Function Documentation
placeholders()
static QString placeholders (int n) static
Definition at line 52 of file QGCTileCacheDatabase.cpp.
Referenced by QGCTileCacheDatabase::createTileSet(), QGCTileCacheDatabase::deleteTileSet(), and QGCTileCacheDatabase::getTileDownloadList().
Variable Documentation
s_connectionCounter
std::atomic<quint64> s_connectionCounter {0} static
Definition at line 63 of file QGCTileCacheDatabase.cpp.
s_exportSessionCounter
std::atomic<int> s_exportSessionCounter {0} static
Definition at line 36 of file QGCTileCacheDatabase.cpp.
Referenced by ScopedExportDB::ScopedExportDB().