QGroundControl: OsmParserThread::BuildingType_t Struct Reference
OsmParserThread::BuildingType_t Struct Reference
#include <OsmParserThread.h>
Public Member Functions
void append (const std::vector< QGeoCoordinate > &newPoints, bool isInner)
void append (const std::vector< QVector2D > &newPoints, bool isInner)
Public Attributes
std::vector< QGeoCoordinate > points_gps
std::vector< QGeoCoordinate > points_gps_inner
std::vector< QVector2D > points_local
std::vector< QVector2D > points_local_inner
QVector2D bb_max = QVector2D(-1e6, -1e6)
QVector2D bb_min = QVector2D(1e6, 1e6)
float height = 0
float levels = 0
Detailed Description
Definition at line 23 of file OsmParserThread.h.
Member Function Documentation
append() [1/2]
void OsmParserThread::BuildingType_t::append (const std::vector< QGeoCoordinate > & newPoints, bool isInner)
Definition at line 201 of file OsmParserThread.cc.
References points_gps, and points_gps_inner.
Referenced by OsmBuildingHandler::relation().
append() [2/2]
void OsmParserThread::BuildingType_t::append (const std::vector< QVector2D > & newPoints, bool isInner)
Definition at line 207 of file OsmParserThread.cc.
Member Data Documentation
bb_max
QVector2D OsmParserThread::BuildingType_t::bb_max = QVector2D(-1e6, -1e6)
Definition at line 29 of file OsmParserThread.h.
Referenced by OsmBuildingHandler::relation(), and OsmBuildingHandler::way().
bb_min
QVector2D OsmParserThread::BuildingType_t::bb_min = QVector2D(1e6, 1e6)
Definition at line 30 of file OsmParserThread.h.
Referenced by OsmBuildingHandler::relation(), and OsmBuildingHandler::way().
height
float OsmParserThread::BuildingType_t::height = 0
Definition at line 31 of file OsmParserThread.h.
Referenced by OsmBuildingHandler::relation(), and OsmBuildingHandler::way().
levels
float OsmParserThread::BuildingType_t::levels = 0
Definition at line 32 of file OsmParserThread.h.
Referenced by OsmBuildingHandler::relation(), and OsmBuildingHandler::way().
points_gps
std::vector<QGeoCoordinate> OsmParserThread::BuildingType_t::points_gps
Definition at line 25 of file OsmParserThread.h.
Referenced by append(), and OsmBuildingHandler::way().
points_gps_inner
std::vector<QGeoCoordinate> OsmParserThread::BuildingType_t::points_gps_inner
Definition at line 26 of file OsmParserThread.h.
Referenced by append().
points_local
std::vector<QVector2D> OsmParserThread::BuildingType_t::points_local
Definition at line 27 of file OsmParserThread.h.
Referenced by OsmBuildingHandler::way().
points_local_inner
std::vector<QVector2D> OsmParserThread::BuildingType_t::points_local_inner
Definition at line 28 of file OsmParserThread.h.
The documentation for this struct was generated from the following files:
src/Viewer3D/Providers/Osm/OsmParserThread.h
src/Viewer3D/Providers/Osm/OsmParserThread.cc