QGroundControl: KMLSchemaValidator::ValidationResult Struct Reference
KMLSchemaValidator::ValidationResult Struct Reference
#include <KMLSchemaValidator.h>
Public Member Functions
void addError (const QString &msg)
void addWarning (const QString &msg)
Public Attributes
bool isValid = true
QStringList errors
QStringList warnings
Detailed Description
Definition at line 17 of file KMLSchemaValidator.h.
Member Function Documentation
addError()
void KMLSchemaValidator::ValidationResult::addError (const QString & msg) inline
Definition at line 22 of file KMLSchemaValidator.h.
References errors, and isValid.
Referenced by KMLSchemaValidator::validate(), and KMLSchemaValidator::validateFile().
addWarning()
void KMLSchemaValidator::ValidationResult::addWarning (const QString & msg) inline
Definition at line 23 of file KMLSchemaValidator.h.
References warnings.
Referenced by KMLSchemaValidator::validate().
Member Data Documentation
errors
QStringList KMLSchemaValidator::ValidationResult::errors
Definition at line 19 of file KMLSchemaValidator.h.
Referenced by addError().
isValid
bool KMLSchemaValidator::ValidationResult::isValid = true
Definition at line 18 of file KMLSchemaValidator.h.
Referenced by addError().
warnings
QStringList KMLSchemaValidator::ValidationResult::warnings
Definition at line 20 of file KMLSchemaValidator.h.
Referenced by addWarning().
The documentation for this struct was generated from the following file:
src/Utilities/Geo/KMLSchemaValidator.h